### ISSUE TITLE
failure in run_once task while using strategy free leads to all other hosts finishing immediately

### ISSUE THREAD

**Issue by GlysVenture** [ansible/ansible#80737]
### Summary

When I use the run_once keyword with `strategy: free` and the keyworded task fails, instead of it having no effect on the play, it makes all other running hosts finish their last task and terminates the play.

This is especially problematic when including roles from others, where the run_once keyword could be somewhere you didn't know, and it could break your plays if you are using the free strategy.

### Issue Type

Bug Report

### Component Name

run_once

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Archcraft x86_64 - kernel 6.3.1-arch1-1 (Arch)

But I also experienced the same issue using 
Debian 5.10.103-1

### Steps to Reproduce

playbook.yml
```yaml (paste below)
- name: Test
  hosts: all
  gather_facts: false
  strategy: free
  tasks:
    - name: fail if success_run_once is false
      fail:
      run_once: true
      when: success_run_once == false

    - name: wait some time
      ansible.builtin.wait_for:
        timeout: 10
      delegate_to: localhost

    - name: simulate say hi
      debug:
        msg: "hi from {{ inventory_hostname }}"

    - name: simulate do fail
      fail:
      when: inventory_hostname == 'host1'

    - name: say hi
      debug:
        msg: "{{ inventory_hostname }} just finished its tasks"
```

inventory.yml
```yaml (paste below)
all:
  hosts:
    host1:
      ansible_hostname: 127.0.0.1
      success_run_once: true
    host2:
      ansible_hostname: 127.0.0.1
      success_run_once: true
    host3:
      ansible_hostname: 127.0.0.1
      success_run_once: false
```

Run ansible-playbook:
`ansible-playbook -i inventory.yml playbook.yml`

### Expected Results

I expected run_once to not have any effect on the play and tasks, as if it wasn't there.

Sample expected output obtained by removing the run_once keyword:
```
PLAY [Test] *************************************************************************************************************************************************************************************************

TASK [fail if success_run_once is false] ********************************************************************************************************************************************************************
skipping: [host1]
skipping: [host2]
fatal: [host3]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

TASK [wait some time] ***************************************************************************************************************************************************************************************
ok: [host1 -> localhost]
ok: [host2 -> localhost]

TASK [simulate say hi] **************************************************************************************************************************************************************************************
ok: [host1] => {
    "msg": "hi from host1"
}
ok: [host2] => {
    "msg": "hi from host2"
}

TASK [simulate do fail] *************************************************************************************************************************************************************************************
fatal: [host1]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}
skipping: [host2]

TASK [say hi] ***********************************************************************************************************************************************************************************************
ok: [host2] => {
    "msg": "host2 just finished its tasks"
}

PLAY RECAP **************************************************************************************************************************************************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
host2                      : ok=3    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
host3                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Actual Results

```console
After one of the hosts fails in the run_once task, all the other finish their current task, and the play ends reporting stats, with no indication that something went wrong with the other hosts (A part from the lower total of tasks done).


PLAY [Test] *************************************************************************************************************************************************************************************************
[WARNING]: Using run_once with the free strategy is not currently supported. This task will still be executed for every host in the inventory list.

TASK [fail if success_run_once is false] ********************************************************************************************************************************************************************
skipping: [host1]
skipping: [host2]
fatal: [host3]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

TASK [wait some time] ***************************************************************************************************************************************************************************************
ok: [host2 -> localhost]
ok: [host1 -> localhost]

PLAY RECAP **************************************************************************************************************************************************************************************************
host1                      : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
host2                      : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
host3                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
