### ISSUE TITLE
import_tasks ignores variables

### ISSUE THREAD

**Issue by skwde** [ansible/ansible#80783]
### Summary

When using a task file named `"{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"` even though I define it as a variable `taskfile` (at different levels). I always get 

```out
ERROR! Error when evaluating variable in import path: {{ taskfile }}.

When using static imports, ensure that any variables used in their names are defined in vars/vars_files
or extra-vars passed in from the command line. Static imports cannot use variables from facts or inventory
sources like group or host vars.
```

Something similar was fixed with this pull request: <https://github.com/ansible/ansible/pull/40982>

### Issue Type

Bug Report

### Component Name

import_tasks

### Ansible Version

```console
$  ansible --version
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/miniconda3/envs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /opt/miniconda3/envs/ansible/bin/ansible
  python version = 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] (/opt/miniconda3/envs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/collections']
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['$HOME/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['$HOME/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', '/etc/ansible/roles']
GALAXY_COLLECTION_SKELETON(/etc/ansible/ansible.cfg) = /usr/share/ansible/collection_skeletons/mydefault
GALAXY_COLLECTION_SKELETON_IGNORE(/etc/ansible/ansible.cfg) = ['^.git$', '^.*/.git_keep$', '^.*/.gitkeep$']
```

### OS / Environment

Rocky9

### Steps to Reproduce

The playbook: `test.yml`
```yaml (paste below)
- name: Test
  hosts: rhel9
  gather_facts: true
  roles:
    - role: test
  #     vars:
  #       taskfile:  "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  # vars:
  #   taskfile:  "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
```

The tasks file `roles/test/tasks/main.yml`

```yml
---
- name: Handle ssh files
  ansible.builtin.import_tasks: "{{ taskfile }}"
  vars:
    taskfile:  "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
```

The tasks file `roles/tests/tasks/RedHat9.yml`

```yml
---
- name: Debug
  ansible.builtin.debug:
    msg:
      - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}"
      - "{{ taskfile }}"
```

The optional variables files `roles/test/{defaults,vars}/main.yml`

```yml
---
taskfile:  "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
```

Then running 

```sh
ansible-playbook test.yml
```

### Expected Results

The playbook runs and outputs

```
"msg": [
        "RedHat9",
        "RedHat9.yml"
    ]
```

### Actual Results

```console
ERROR! Error when evaluating variable in import path: {{ taskfile }}.

When using static imports, ensure that any variables used in their names are defined in vars/vars_files
or extra-vars passed in from the command line. Static imports cannot use variables from facts or inventory
sources like group or host vars.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
