### ISSUE TITLE
deb822_repository fails to fetch signed_by key: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by sebdanielsson** [ansible/ansible#80809]
### Summary

When I try to add the cloudflared repo with the new deb822_repository module I get the following response:

fatal: [xxxxxx]: FAILED! => {"changed": false, "msg": "Could not fetch signed_by key: HTTP Error 403: Forbidden"}

I've tested the module with the Tailscale repo and that worked. Then I tested if there was something up with the cloudflare repo but fetching the gpg key with `wget` and `curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null` work as expected. Must be some kind of mismatch between this module and the cloudflared repository but I'm not really skilled enough to troubleshoot this further.

### Issue Type

Bug Report

### Component Name

deb822_repository

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/Users/sebastian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/sebastian/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = False
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

macOS Ventura 13.3.1 (a)

### This code doesn't work

```yaml
---
- name: xxxxxx Proxmox
  hosts: xxxxxx

  tasks:
    - name: Add cloudflared repository
      become: true
      ansible.builtin.deb822_repository:
        name: cloudflared
        types: deb
        uris: https://pkg.cloudflare.com/cloudflared
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: https://pkg.cloudflare.com/cloudflare-main.gpg
        state: present
```

### This code is working

```yaml
---
- name: xxxxxx Proxmox
  hosts: xxxxxx

  tasks:
    - name: Add tailscale repository
      become: true
      ansible.builtin.deb822_repository:
        name: tailscale
        types: deb
        uris: https://pkgs.tailscale.com/stable/debian
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg
        state: absent
```

### Expected Results

I expected the repository to be added with the specified key.

### Actual Results

```console
ansible-playbook -i ./inventory.yml ./apt_beta.yml

PLAY [xxxxxx Proxmox] ****************************************************************

TASK [Gathering Facts] ******************************************************************
ok: [xxxxxx]

TASK [Add cloudflared repository] ***********************************************
fatal: [xxxxxx]: FAILED! => {"changed": false, "msg": "Could not fetch signed_by key: HTTP Error 403: Forbidden"}

PLAY RECAP ******************************************************************************
xxxxxx                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
