### ISSUE TITLE
ansible.builtin.file diff could not be disabled

### ISSUE THREAD

**Issue by F-PMOR** [ansible/ansible#80817]
### Summary

I'm trying to desactivate diff in ansible.builtin.file task like below while using the diff_mode (ansible-playbook playbook.yml --diff)  : 

```
- name: "Create Folder ../artifacts/{{ inventory_hostname }}/ if not exist"
  ansible.builtin.file:
    path: "../artifacts/{{ inventory_hostname }}"
    mode: 0755
    state: directory
  delegate_to: localhost
  diff: false
```
The option "diff: false" seams not beeing implemented in file module.

**The output is :**
```
TASK [orange.vpn : Create Folder ../artifacts/NEXUS-93180-1/ if not exist] **************************************************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "mode": "0777",
+    "mode": "0755",
     "path": "../artifacts/NEXUS-93180-1"
 }
```

**It should be :** 
```
TASK [orange.vpn : Create Folder ../artifacts/NEXUS-93180-1/ if not exist] **************************************************************************************************************************************************************************************************************************************************************
changed: [NEXUS-93180-1 -> localhost]
```

### Issue Type

Feature Idea

### Component Name

ansible.builtin.file

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
