### ISSUE TITLE
conditional include_task loops in handlers are broken

### ISSUE THREAD

**Issue by mnasiadka** [ansible/ansible#80848]
### Summary

conditional include_task loops in handlers are broken after https://github.com/ansible/ansible/commit/65366f663de7d044f42ae6dd53368fd4c1f88b35

ansible-core 2.14.2 is the last version it works with (from 2.14 series)

tasks are not executed serially

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.5]
  config file = None
  configured module search path = ['/home/cloud-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cloud-user/kolla-venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/cloud-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cloud-user/kolla-venv/bin/ansible
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/home/cloud-user/kolla-venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Rocky Linux 9, Ubuntu, probably any

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  tasks:
    - name: Trigger handlers
      debug:
        msg: hi
      changed_when: true
      notify: Handler
  handlers:
    - name: Handler
      include_tasks: include.yml
      with_inventory_hostnames: all
      when: inventory_hostname == item

include.yml:
---
- name: Included
  debug:
    msg: Included

- name: sleep
  pause:
    seconds: 5
```

### Expected Results

Tasks from include.yml are executed in serial fashion (ansible-core 2.14.2 example):

```console
PLAY [all] ***********************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [h1]
ok: [h2]

TASK [Trigger handlers] **********************************************************************************************************************************************************
changed: [h1] => {
    "msg": "hi"
}
changed: [h2] => {
    "msg": "hi"
}

RUNNING HANDLER [Handler] ********************************************************************************************************************************************************
skipping: [h1] => (item=h2)
skipping: [h2] => (item=h1)
included: /home/cloud-user/test/include.yml for h1 => (item=h1)
included: /home/cloud-user/test/include.yml for h2 => (item=h2)

RUNNING HANDLER [Included] *******************************************************************************************************************************************************
ok: [h1] => {
    "msg": "Included"
}

RUNNING HANDLER [sleep] **********************************************************************************************************************************************************
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [h1]

RUNNING HANDLER [Included] *******************************************************************************************************************************************************
ok: [h2] => {
    "msg": "Included"
}

RUNNING HANDLER [sleep] **********************************************************************************************************************************************************
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [h2]

PLAY RECAP ***********************************************************************************************************************************************************************
h1                         : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
h2                         : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Actual Results

```console
PLAY [all] ***********************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [h1]
ok: [h2]

TASK [Trigger handlers] **********************************************************************************************************************************************************
changed: [h1] => {
    "msg": "hi"
}
changed: [h2] => {
    "msg": "hi"
}

RUNNING HANDLER [Handler] ********************************************************************************************************************************************************
skipping: [h1] => (item=h2)
skipping: [h2] => (item=h1)
included: /home/cloud-user/test/include.yml for h1 => (item=h1)
included: /home/cloud-user/test/include.yml for h2 => (item=h2)

RUNNING HANDLER [Included] *******************************************************************************************************************************************************
ok: [h1] => {
    "msg": "Included"
}

TASK [Included] ******************************************************************************************************************************************************************
ok: [h2] => {
    "msg": "Included"
}

RUNNING HANDLER [sleep] **********************************************************************************************************************************************************
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [h1]

PLAY RECAP ***********************************************************************************************************************************************************************
h1                         : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
h2                         : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mnasiadka** [comment]
@mkrizek would you be able to have a look?

**Comment by markgoddard** [comment]
This is an important feature for running multiple handler tasks serially for each host. It's used for performing rolling updates that require multiple steps per host (such as waiting for a service to come up), without requiring the use of `serial`, which has performance implications.

**Comment by mnasiadka** [comment]
> 

I don't think it's possible:
ERROR! 'throttle' is not a valid attribute for a HandlerTaskInclude

**Comment by sivel** [comment]
I'm unsure after looking at the code, whether any attempt at restoring this behavior should be made.  It appears as though the behavior you were relying on was unintentional, and just happened to be a confluence of unexpected logic that led to the code behaving like this.

I more narrow reproducer:

```yaml
---
- hosts: all
  force_handlers: true
  tasks:
    - name: Trigger handlers
      debug:
        msg: hi
      changed_when: true
      notify: Handler
  handlers:
    - name: Handler
      include_tasks: include.yml
      loop:
        - '{{ inventory_hostname }}'
```

It basically took advantage of the fact that `item` made the include unique, and the deduping code wouldn't merge the includes as a single include, spanning multiple hosts, because the "include args" were different for each.

Here is an example playbook, modified to operate via expected mechanisms in the way you desire:

```yaml
- hosts: all
  force_handlers: true
  tasks:
    - name: Trigger handlers
      debug:
        msg: hi
      changed_when: true
      notify: Handler
  handlers:
    - name: Handler
      add_host:
        name: '{{ inventory_hostname }}'
        groups:
          - serial_handlers

- hosts: serial_handlers
  serial: 1
  tasks:
    - name: Included
      debug:
        msg: Included

    - name: sleep
      pause:
        seconds: 5
```

I'm also unsure what this realistically means, when the outcome is identical:

> without requiring the use of serial, which has performance implications.

**Comment by markgoddard** [comment]
Thank you for the explanation and proposed solution @sivel. Here's a slightly modified version that uses a handler to avoid registering variables everywhere you want to trigger a restart:

```yaml
---
- hosts: all
  tasks:
    - name: Trigger handlers
      debug:
        msg: hi
      changed_when: true
      notify: trigger serial restart

  handlers:
    - name: trigger serial restart
      group_by:
        key: serial_handlers

- hosts: serial_handlers
  serial: 1
  tasks:
    - name: Included
      debug:
        msg: Included

    - name: sleep
      pause:
        seconds: 5
```

It feels a bit more clunky than our original design, but I expect we could make it work.

---

I have tried a couple of other approaches, neither of which worked.

1. Use some symlinks to make the included files appear unique:

```
for i in $(seq 0 4); do ln -s include.yml include-batch-$i.yml; done
```

```yaml
---
- hosts: all
  force_handlers: true
  tasks:
    - name: Trigger handlers
      debug:
        msg: hi
      changed_when: true
      notify: Handler
  handlers:
    - name: Handler
      include_tasks: include-batch-{{ groups['all'].index(inventory_hostname) % 4 }}.yml
```

Ansible 2.14.5 sees through this and dedups the tasks.

2. Same playbook as above, but using import_tasks:

```
for i in $(seq 0 3); do echo '- import_tasks: include.yml' > include-batch-$i.yml; done
```
Fails with the following
```yaml
ERROR! Error when evaluating variable in dynamic parent include path: include-batch-{{ groups['all'].index(inventory_hostname) % 4 }}.yml. When using static imports, the parent dynamic include cannot utilize host facts or variables from inventory
```
