### ISSUE TITLE
ansible.builtin.copy doesn't preserve destination execution rights

### ISSUE THREAD

**Issue by ari75** [ansible/ansible#80849]
### Summary

I'm in the process of migrating an Ansible 2.9 playbook to 2.12 but i'm currently block by an unexpected behavior. Before, the file permissions for a file using copy would preserve destination permissions if mode is not set. This doesn't work anymore with ansible 2.12.

*EDIT: it also doesn't work with Ansible 2.14.4*

### Issue Type

Bug Report

### Component Name

ansible.builtin.copy

### Ansible Version

```console
$ ansible --version
{
    "msg": "Ansible version is  2.12.4",
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false
}
{
    "msg": "community.general version 4.7.0",
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false
}
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
Using Ansible Tower, I don't have access to the ansible control node
```

### OS / Environment

RHEL 8.7

### Steps to Reproduce

```yaml (paste below)
- name: Print Ansible version
  ansible.builtin.debug:
    msg: "Ansible version is  {{ ansible_version.full }}"

- name: Check version of community.general
  ansible.builtin.debug:
    msg: "community.general version {{ lookup('community.general.collection_version', 'community.general') }}"

- name: Ensure target directory doesn't exist
  file:
    path: "/tmp/ansible"
    state: absent

- name: Ensure target zip structure doesn't exist
  file:
    path: "/tmp/test"
    state: absent

- name: Ensure zip files doesn't exist
  file:
    path: "/tmp/test.zip"
    state: absent

- name: Ensure dummy file doesn't exist on ansible control node
  file:
    path: "/tmp/run.sh"
    state: absent
  delegate_to: 127.0.0.1

- name: Create dummy target structure on target node
  file:
    path: '/tmp/ansible/'
    state: directory
    mode: 0750

- name: Create dummy zip structure on target node
  file:
    path: '/tmp/test/bin/'
    state: directory
    mode: 0750

- name: Create dummy zip run.sh on target node with executable permissions
  ansible.builtin.copy:
    dest: "/tmp/test/bin/run.sh"
    mode: "0744"
    content: |
      Content: AAA

- name: Create dummy zip on target node
  community.general.archive:
    path: /tmp/test
    dest: /tmp/test.zip
    format: zip

- name: Unarchive dummy zip into target
  ansible.builtin.unarchive:
    src: "/tmp/test.zip"
    dest: "/tmp/ansible"
    remote_src: yes

- name: Stat run.sh after unarchive
  ansible.builtin.stat: path="/tmp/ansible/test/bin/run.sh"
  register: st

- name: Display file content after unarchive
  shell: |
    cat /tmp/ansible/test/bin/run.sh
  register: file_content

- name: Debug file content after unarchive
  ansible.builtin.debug:
    msg: "Run.sh created by zip file on target node: {{file_content.stdout}}"

- name: Create dummy run.sh on ansible control node with default git permissions
  ansible.builtin.copy:
    dest: "/tmp/run.sh"
    mode: "0644"
    content: |
      Content: CCC
  delegate_to: 127.0.0.1

- name: Stat run.sh on ansible control node
  ansible.builtin.stat: path="/tmp/run.sh"
  register: st
  delegate_to: 127.0.0.1

- name: Display run.sh file content on ansible control node
  shell: |
    cat /tmp/run.sh
  register: file_content
  delegate_to: 127.0.0.1

- name: Debug run.sh file content on ansible control node
  ansible.builtin.debug:
    msg: "Run.sh created on ansible control node: {{file_content.stdout}}"
  delegate_to: 127.0.0.1

- name: Replace run.sh using copy on target
  ansible.builtin.copy:
    src: "/tmp/run.sh"
    dest: "/tmp/ansible/test/bin/run.sh"

- name: Stat run.sh after copy
  ansible.builtin.stat: path="/tmp/ansible/test/bin/run.sh"
  register: st

- name: Display run.sh file content on target node after copy
  shell: |
    cat /tmp/ansible/test/bin/run.sh
  register: file_content

- name: Debug run.sh file content on target node after copy
  ansible.builtin.debug:
    msg: "Run.sh copied to ansible target node: {{file_content.stdout}}"
```

### Expected Results

I would expect the copied file to retains the permissions of the existing file, as mode is not set. 

### Actual Results

```console
In this case, we see that the permissions are the one of the source file instead.

See the logs:
PLAY [Run GitHub-Debug roles] **************************************************

TASK [Gathering Facts] *********************************************************
ok: [target.host]

TASK [GitHub-Debug : Print Ansible version] ************************************
ok: [target.host] => {
    "msg": "Ansible version is  2.12.4"
}

TASK [GitHub-Debug : Check version of community.general] ***********************
ok: [target.host] => {
    "msg": "community.general version 4.7.0"
}

TASK [GitHub-Debug : Ensure target directory doesn't exist] ********************
changed: [target.host] => {"changed": true, "path": "/tmp/ansible", "state": "absent"}

TASK [GitHub-Debug : Ensure target zip structure doesn't exist] ****************
changed: [target.host] => {"changed": true, "path": "/tmp/test", "state": "absent"}

TASK [GitHub-Debug : Ensure zip files doesn't exist] ***************************
changed: [target.host] => {"changed": true, "path": "/tmp/test.zip", "state": "absent"}

TASK [GitHub-Debug : Ensure dummy file doesn't exist on ansible control node] ***
ok: [target.host -> 127.0.0.1] => {"changed": false, "path": "/tmp/run.sh", "state": "absent"}

TASK [GitHub-Debug : Create dummy target structure on target node] *************
changed: [target.host] => {"changed": true, "gid": 41601, "group": "myuser", "mode": "0750", "owner": "myuser", "path": "/tmp/ansible/", "size": 6, "state": "directory", "uid": 41601}

TASK [GitHub-Debug : Create dummy zip structure on target node] ****************
changed: [target.host] => {"changed": true, "gid": 41601, "group": "myuser", "mode": "0750", "owner": "myuser", "path": "/tmp/test/bin/", "size": 6, "state": "directory", "uid": 41601}

TASK [GitHub-Debug : Create dummy zip run.sh on target node with executable permissions] ***
changed: [target.host] => {"changed": true, "checksum": "ed476cb81180f0861b40465ff6c47139167dcfb5", "dest": "/tmp/test/bin/run.sh", "gid": 41601, "group": "myuser", "md5sum": "8d34b63365d4713c5e7353e5509e33c5", "mode": "0744", "owner": "myuser", "size": 13, "src": "/var/tmp/ansible-tmp-1684520005.7636242-92-133689932874379/source", "state": "file", "uid": 41601}

TASK [GitHub-Debug : Create dummy zip on target node] **************************
changed: [target.host] => {"archived": ["/tmp/test/bin/run.sh"], "arcroot": "/tmp/", "changed": true, "dest": "/tmp/test.zip", "dest_state": "archive", "expanded_exclude_paths": [], "expanded_paths": ["/tmp/test"], "gid": 41601, "group": "myuser", "missing": [], "mode": "0644", "owner": "myuser", "size": 237, "state": "file", "uid": 41601}

TASK [GitHub-Debug : Unarchive dummy zip into target] **************************
changed: [target.host] => {"changed": true, "dest": "/tmp/ansible", "extract_results": {"cmd": ["/bin/unzip", "-o", "/tmp/test.zip", "-d", "/tmp/ansible"], "err": "", "out": "Archive:  /tmp/test.zip\\n   creating: /tmp/ansible/test/bin/\\n  inflating: /tmp/ansible/test/bin/run.sh  \\n", "rc": 0}, "gid": 41601, "group": "myuser", "handler": "ZipArchive", "mode": "0750", "owner": "myuser", "size": 18, "src": "/tmp/test.zip", "state": "directory", "uid": 41601}

TASK [GitHub-Debug : Stat run.sh after unarchive] ******************************
ok: [target.host] => {"changed": false, "stat": {"atime": 1684520006.0, "attr_flags": "", "attributes": [], "block_size": 4096, "blocks": 8, "charset": "us-ascii", "checksum": "ed476cb81180f0861b40465ff6c47139167dcfb5", "ctime": 1684520007.9843633, "dev": 64776, "device_type": 0, "executable": true, "exists": true, "gid": 41601, "gr_name": "myuser", "inode": 138, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "text/plain", "mode": "0744", "mtime": 1684520006.0, "nlink": 1, "path": "/tmp/ansible/test/bin/run.sh", "pw_name": "myuser", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 13, "uid": 41601, "version": "3170330855", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": true}}

TASK [GitHub-Debug : Display file content after unarchive] *********************
changed: [target.host] => {"changed": true, "cmd": "cat /tmp/ansible/test/bin/run.sh\\n", "delta": "0:00:00.003673", "end": "2023-05-19 20:13:28.798596", "msg": "", "rc": 0, "start": "2023-05-19 20:13:28.794923", "stderr": "", "stderr_lines": [], "stdout": "Content: AAA", "stdout_lines": ["Content: AAA"]}

TASK [GitHub-Debug : Debug file content after unarchive] ***********************
ok: [target.host] => {
    "msg": "Run.sh created by zip file on target node: Content: AAA"
}

TASK [GitHub-Debug : Create dummy run.sh on ansible control node with default git permissions] ***
changed: [target.host -> 127.0.0.1] => {"changed": true, "checksum": "faa230ae84f2f631abefc985e6cc93f8b8f70d31", "dest": "/tmp/run.sh", "gid": 41704, "group": "awx", "md5sum": "6a14dc3d23936ce591fc4c34d35263b1", "mode": "0644", "owner": "awx", "size": 13, "src": "/var/lib/awx/.ansible/tmp/ansible-tmp-1684520008.9312723-150-278476160912569/source", "state": "file", "uid": 41704}

TASK [GitHub-Debug : Stat run.sh on ansible control node] **********************
ok: [target.host -> 127.0.0.1] => {"changed": false, "stat": {"atime": 1684520009.2816467, "attr_flags": "", "attributes": [], "block_size": 4096, "blocks": 8, "charset": "us-ascii", "checksum": "faa230ae84f2f631abefc985e6cc93f8b8f70d31", "ctime": 1684520009.2826467, "dev": 64777, "device_type": 0, "executable": false, "exists": true, "gid": 41704, "gr_name": "awx", "inode": 2118034, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "text/plain", "mode": "0644", "mtime": 1684520009.111646, "nlink": 1, "path": "/tmp/run.sh", "pw_name": "awx", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 13, "uid": 41704, "version": "377694436", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}

TASK [GitHub-Debug : Display run.sh file content on ansible control node] ******
changed: [target.host -> 127.0.0.1] => {"changed": true, "cmd": "cat /tmp/run.sh\\n", "delta": "0:00:00.004871", "end": "2023-05-19 18:13:29.804308", "msg": "", "rc": 0, "start": "2023-05-19 18:13:29.799437", "stderr": "", "stderr_lines": [], "stdout": "Content: CCC", "stdout_lines": ["Content: CCC"]}

TASK [GitHub-Debug : Debug run.sh file content on ansible control node] ********
ok: [target.host -> 127.0.0.1] => {
    "msg": "Run.sh created on ansible control node: Content: CCC"
}

TASK [GitHub-Debug : Replace run.sh using copy on target] **********************
changed: [target.host] => {"changed": true, "checksum": "faa230ae84f2f631abefc985e6cc93f8b8f70d31", "dest": "/tmp/ansible/test/bin/run.sh", "gid": 41601, "group": "myuser", "md5sum": "6a14dc3d23936ce591fc4c34d35263b1", "mode": "0644", "owner": "myuser", "size": 13, "src": "/var/tmp/ansible-tmp-1684520009.934914-210-204219023532810/source", "state": "file", "uid": 41601}

TASK [GitHub-Debug : Stat run.sh after copy] ***********************************
ok: [target.host] => {"changed": false, "stat": {"atime": 1684520010.4903717, "attr_flags": "", "attributes": [], "block_size": 4096, "blocks": 8, "charset": "us-ascii", "checksum": "faa230ae84f2f631abefc985e6cc93f8b8f70d31", "ctime": 1684520010.4993718, "dev": 64776, "device_type": 0, "executable": false, "exists": true, "gid": 41601, "gr_name": "myuser", "inode": 142, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "text/plain", "mode": "0644", "mtime": 1684520010.237371, "nlink": 1, "path": "/tmp/ansible/test/bin/run.sh", "pw_name": "myuser", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 13, "uid": 41601, "version": "4034807983", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}

TASK [GitHub-Debug : Display run.sh file content on target node after copy] ****
changed: [target.host] => {"changed": true, "cmd": "cat /tmp/ansible/test/bin/run.sh\\n", "delta": "0:00:00.004064", "end": "2023-05-19 20:13:31.201734", "msg": "", "rc": 0, "start": "2023-05-19 20:13:31.197670", "stderr": "", "stderr_lines": [], "stdout": "Content: CCC", "stdout_lines": ["Content: CCC"]}

TASK [GitHub-Debug : Debug run.sh file content on target node after copy] ******
ok: [target.host] => {
    "msg": "Run.sh copied to ansible target node: Content: CCC"
}

PLAY RECAP *********************************************************************
target.host             : ok=23   changed=13   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
