### ISSUE TITLE
When creating DNAT rules with different destinations then only 1 will be created

### ISSUE THREAD

**Issue by toralf** [ansible/ansible#80856]
### Summary

When creating DNAT rules with different destinations then only 1 will be created:

```
- name: DNAT incoming TCP v6 to the global scope ipv6 address (except first xx addresses)
  ansible.builtin.iptables:
    ip_version: ipv6
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: "! {{ _ipv6_prefix }}::/{{ item }}"
    to_destination: "{{ _ipv6 }}"
    jump: DNAT
  with_items: 
    - 118
    - 102 
```

### Issue Type

Bug Report

### Component Name

ansible.builtin.iptables

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = /home/tfoerste/devel/tor-relays/ansible.cfg
  configured module search path = ['/home/tfoerste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/tfoerste/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/lib/python-exec/python3.11/ansible
  python version = 3.11.3 (main, May  6 2023, 19:42:44) [GCC 12.2.1 20230428] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

stable Gentoo 

### Steps to Reproduce

run that task

### Expected Results

2 rules

### Actual Results

```console
TASK [setup : DNAT ******************************************************************************************
changed: [buddelflink] => (item=118)
ok: [buddelflink] => (item=102)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
