### ISSUE TITLE
Windows: Connection retry logic

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#8085]
##### Summary:

If Ansible tries to connect to a server which is in reboot (and therefore briefly unavailable), it will just hang there, never completing (not even after the computer has finished restarting). A better way would to be to implement some "retry" logic for a certain amount of time. For example, attempt to probe the port before setting up the winrm connection.
##### Steps To Reproduce:

Run a module against a windows computer which is currently being rebooted
##### Expected Results:

Ansible should try and reconnect to the node (with a timeout)
##### Actual Results:

Ansible just hangs there, not timing out nor connecting

**Comment by mpdehaan** [comment]
Ansible doesn't really do connection retry logic, but I agree there should be a timeout.

Perhaps this is a parameter that can be passed to the winrm library.

**Comment by trondhindenes** [comment]
Yup. That would allow us to build a role with some logic to handle reboots at least. I guess Windows just requires more reboots than a linux-based system.

**Comment by sivel** [comment]
Just curious as to why you wouldn't use `wait_for` to handle waiting for reboots?  That is typically what is done.  Using a `local_action` such as:

```
- name: wait for windows system reboot
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host|default(inventory_hostname) }}"
    port: "{{ ansible_ssh_port|default(5986) }}"
    delay: 30
    timeout: 600
    state: started
```
