### ISSUE TITLE
any_errors_fatal does not work when using groups task

### ISSUE THREAD

**Issue by satellite-no** [ansible/ansible#80861]
### Summary

I have a bit of an edge case here.  My playbook that will create new ec2 hosts and then configure them.  It does this by running against 'localhost' at first then once the instances are created adding them with `ansible.builtin.add_host` and running following plays against the new hosts.  When using `any_errors_fatal` in this fashion it does not count the new hosts in this and will only truly fail if `localhost` fails which is what the inventory originally targets. 

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.6]
  config file = /opt/dev/sean.elliott/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python3-virtualenvs/py39venv-ansible-latest/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/python3-virtualenvs/py39venv-ansible-latest/bin/ansible
  python version = 3.9.1 (default, Dec 17 2020, 15:23:46) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CACHE_PLUGIN(/opt/dev/user/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/opt/dev/user/ansible/ansible.cfg) = /opt/ansible/fact_cache
CACHE_PLUGIN_TIMEOUT(/opt/dev/user/ansible/ansible.cfg) = 43200
CALLBACKS_ENABLED(/opt/dev/user/ansible/ansible.cfg) = ['community.general.splunk']
DEFAULT_FORKS(/opt/dev/user/ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/opt/dev/user/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/opt/dev/user/ansible/ansible.cfg) = ['/opt/ansible/inventories']
DEFAULT_STDOUT_CALLBACK(/opt/dev/user/ansible/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/opt/dev/user/ansible/ansible.cfg) = /opt/ansible/vault-env.py
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INTERPRETER_PYTHON(/opt/dev/user/ansible/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/opt/dev/user/ansible/ansible.cfg) = False

CACHE:
=====

jsonfile:
________
_timeout(/opt/dev/user/ansible/ansible.cfg) = 43200
_uri(/opt/dev/user/ansible/ansible.cfg) = /opt/ansible/fact_cache

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(env: ANSIBLE_HOST_KEY_CHECKING) = False

ssh:
___
host_key_checking(env: ANSIBLE_HOST_KEY_CHECKING) = False
pipelining(/opt/dev/user/ansible/ansible.cfg) = True
reconnection_retries(/opt/dev/user/ansible/ansible.cfg) = 3
```

### OS / Environment

NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

Fail as `any_errors_fatal` it would with normal inventory targeting.

### Actual Results

```console
The Playbook will continue running on all hosts that have not failed/error'd yet.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/pip.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/pip.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
Please provide a playbook that reproduces this issue, and the output of running that playbook.

This reproducer shows this works as expected:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - add_host:
        name: localhost{{ item }}
        groups:
          - new
      loop: '{{ range(3) }}'

- hosts: new
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - fail:
      when: groups.new[1] == inventory_hostname

    - debug:
```

<details>
<summary>Output...</summary>
<p>

```

PLAY [localhost] ***************************************************************

TASK [add_host] ****************************************************************
changed: [localhost] => (item=0)
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)

PLAY [new] *********************************************************************

TASK [fail] ********************************************************************
skipping: [localhost0]
fatal: [localhost1]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}
skipping: [localhost2]

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
localhost0                 : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
localhost1                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
localhost2                 : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

</p>
</details>

**Comment by s-hertel** [comment]
needs_info

**Comment by satellite-no** [comment]
Hmm sort of weird, I get the same result as @sivel if I use your example playbook.  The playbook I'm using is pretty long with lots of custom roles and multiple plays.  From my understanding Ansible finishes the fatal task on all hosts in the current batch, then stops executing the play on all hosts.  So the below output should not happen if its working as expected, ya or am I misunderstanding.  Im not sure if it has to do with the failures happening in roles being called our why but giving the entirety of the playbook roles, custom collections, and etc would be very difficult :(. 

```text
TASK [splunk_server_common : Set new fact if we already have the desired version of Splunk] ***

TASK [splunk_server_common : Verify Correct Splunk Version is Installed] *******
fatal: [lic.cicd1334.opsenglab.redacted.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'splunk_prefix' is undefined\n\nThe error appears to be in '/opt/ansible/roles/splunk_server_common/tasks/main.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Verify Correct Splunk Version is Installed\"\n  ^ here\n"}
fatal: [hf1.cicd1334.opsenglab.redacted.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'splunk_prefix' is undefined\n\nThe error appears to be in '/opt/ansible/roles/splunk_server_common/tasks/main.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Verify Correct Splunk Version is Installed\"\n  ^ here\n"}
changed: [idx2.cicd1334.opsenglab.redacted.com]
changed: [idx1.cicd1334.opsenglab.redacted.com]
changed: [sh1.cicd1334.opsenglab.redacted.com]

TASK [splunk_server_common : Verify Correct Splunk Version is Upgraded to new version] ***

TASK [splunk_server_common : If Splunk was just installed, get hashed password to use in seed file] ***
changed: [idx1.cicd1334.opsenglab.redacted.com]
changed: [idx2.cicd1334.opsenglab.redacted.com]
[WARNING]: Module remote_tmp /opt/app/splunk/.ansible/tmp did not exist and was
created with a mode of 0700, this may cause issues when running as another
user. To avoid this, create the remote_tmp dir with the correct permissions
manually
changed: [sh1.cicd1334.opsenglab.redacted.com]

TASK [splunk_server_common : If Splunk was just installed, create seed file] ***
changed: [idx1.cicd1334.opsenglab.redacted.com]
changed: [idx2.cicd1334.opsenglab.redacted.com]
changed: [sh1.cicd1334.opsenglab.redacted.com]

TASK [splunk_server_common : If Splunk was just installed/upgraded: Disable boot-start] ***
changed: [idx1.cicd1334.opsenglab.redacted.com]
changed: [idx2.cicd1334.opsenglab.redacted.com]
changed: [sh1.cicd1334.opsenglab.redacted.com]
```

```yaml
- name: "Configure Servers"
  hosts: new_deployment
  any_errors_fatal: true
  tags: configuration
  collections: 
    - fd_splunk.splunk_common
  become: True
  become_user: root
  vars:
    # Custom Vars
    server_fqdn: "{{ inventory_hostname }}"
    server_shortname: "{{ inventory_hostname_short }}"
    splunk_binary: "splunk-9.0.4-de405f4a7979-linux-2.6-x86_64.rpm"
    splunk_binary_version: "{{ splunk_binary | regex_search('splunk-([^\\-]+)', '\\1') | first }}"
    splunk_rpm_url: "http://download.splunk.com/products/splunk/releases/{{ splunk_binary_version }}/linux/{{ splunk_binary }}"
    splunk_path: "/opt/splunk"
    local_splunk_generic_repo: "{{ playbook_dir }}/files/git/generic/Splunk"

    # Vars previously set in localhost facts
    client_name: "{{ hostvars['localhost']['client_name'] }}"
    splunk_password: "{{ hostvars['localhost']['splunk_password'] }}"
    splunk_pass4symmkey: "{{ hostvars['localhost']['splunk_pass4symmkey'] }}"
    splk_srv_acct_for_xsoar_pwd: "{{ hostvars['localhost']['splk_srv_acct_for_xsoar_pwd'] }}"
    splk_srv_acct_for_st2_pwd: "{{ hostvars['localhost']['splk_srv_acct_for_st2_pwd'] }}"
    fwd_cert_password: "{{ hostvars['localhost']['splunk_forwarder_crt_pwd'] }}"
    idx_cert_password: "{{ hostvars['localhost']['splunk_indexer_crt_pwd'] }}"
    splunkldap_bind_dn_password: "{{ hostvars['localhost']['splunkldap_bind_dn_password'] }}"
    resource_groups: "{{ hostvars['localhost']['resource_groups'] }}"
    shared_deployment_server_and_port: "{{ hostvars['localhost']['shared_deployment_server_and_port'] }}"
    fwd_pem: "{{ hostvars['localhost']['fwd_cert_from_onepass'][0] }}"
    indexer_pem: "{{ hostvars['localhost']['idx_cert_from_onepass'][0] }}"
    email_username: "{{ hostvars['localhost']['email_username'] }}"
    email_from: "{{ hostvars['localhost']['email_from'] }}"
    email_mailserver: "{{ hostvars['localhost']['email_mailserver'] }}"
    email_password: "{{ hostvars['localhost']['email_password'] }}"
    customer_domain: "{{ hostvars['localhost']['customer_domain'] }}"

  roles:
    - { role: get_server_status, tags: status }
    - { role: configure_os_hostname, tags: hostname }
    - { role: bash_global_profile }
    - { role: uninstall_splunk, tags: uninstall_splunk, when: uninstall_splunk_first is defined and uninstall_splunk_first|bool }
    - { role: server_common, tags: common }
    - { role: server_filesystems, tags: filesystem }
    - { role: splunk_server_common, tags: splunk_common }
    - { role: set_splunk_bashprofile, tags: splunk_common }
    - { role: set_splunk_thp, tags: splunk_common }
    - { role: set_splunk_ulimits, tags: splunk_common }
    - { role: splunk_configuration_baseline, tags: splunk_config }
    - { role: splunk_cluster_bundle, tags: splunk_config, when: "'lic' in group_names" }

  tasks:
    - ansible.builtin.include_role:
        name: fd_splunk.splunk_common.splunk_create_user
      vars:
        new_user: 'demisto_{{ client_name|lower }}'
        new_user_password: '{{ splk_srv_acct_for_xsoar_pwd }}'
        new_user_roles: '{{ "fd-soar" if "sh" in group_names else "power" }}'
        splunk_admin_user: '{{ splunk_admin }}'
        splunk_admin_password: '{{ splunk_password }}'
      when:
        - "'sh' in group_names or 'lic' in group_names"
    - ansible.builtin.include_role:
        name: fd_splunk.splunk_common.splunk_create_user
      vars:
        new_user: 'st2_{{ client_name|lower }}'
        new_user_password: '{{ splk_srv_acct_for_st2_pwd }}'
        new_user_roles: 'fd-st2'
        splunk_admin_user: '{{ splunk_admin }}'
        splunk_admin_password: '{{ splunk_password }}'
      when:
        - "'sh' in group_names or 'lic' in group_names"
    - ansible.builtin.include_role:
        name: deploy_custom_facts_installed_apps
    - ansible.builtin.include_role:
        name: install_vector
```
