### ISSUE TITLE
Unable to use sudo via ansible ssh `{"msg": "Incorrect sudo password"}`

### ISSUE THREAD

**Issue by wbehrens-on-gh** [ansible/ansible#80893]
### Summary

When attempting to use the `become` functionality over a remote ssh connection ansible always fails with `{"msg": "Incorrect sudo password"}`. I've verified the password being entered is correct and for some reason this issue only occurs when trying to access a remote machine. If I attempt target localhost `become` just gets caught on a 2fa prompt(separate but expected issue). I'm able to perform non-sudo tasks via ansible(without `become`) just fine on a remote connection.

### Issue Type

Bug Report

### Component Name

become

### Ansible Version

```console
ansible [core 2.13.9]
  config file = /home/wbehrens@domain.local/Code/devops/playbooks/ansible.cfg
  configured module search path = ['/home/wbehrens@domain.local/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/wbehrens@domain.local/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/wbehrens@domain.local/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/wbehrens@domain.local/.local/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
DEFAULT_HOST_LIST(/home/wbehrens@domain.local/Code/devops/playbooks/ansible.cfg) = ['/home/wbehrens@domain.local/Code/devops/playbooks/inventory']
```

### OS / Environment

Ubuntu 20.04 (Focal Fossa)

### Steps to Reproduce

Works fine:
```yaml
- name: Non root example
  hosts: my_remote_machine
  tasks:
    - name: Create file in user home directory
      ansible.builtin.file: 
        path: "{{lookup('env', 'HOME')}}/test.txt"
        state: touch
```

doesn't work
```
- name: Become example
  # This works fine when the host is set to localhost
  hosts: my_remote_machine
  become: true  
  tasks:
    - name: Create file in the root directory
      ansible.builtin.file: 
        path: "/test.txt"
        state: touch
```
note the above is run with `--ask-become-pass`

### Expected Results

A file to be created in the root directory of the target host

### Actual Results

```console
ansible-playbook [core 2.13.9]
  config file = /home/wbehrens@domain.local/Code/devops/playbooks/ansible.cfg
  configured module search path = ['/home/wbehrens@domain.local/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/wbehrens@domain.local/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/wbehrens@domain.local/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/wbehrens@domain.local/.local/bin/ansible-playbook
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
Using /home/wbehrens@domain.local/Code/devops/playbooks/ansible.cfg as config file
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: deploy-jenkins.yml ***************************************************
1 plays in playbooks/deploy-jenkins.yml

PLAY [Deploy Jenkins] **********************************************************

TASK [Gathering Facts] *********************************************************
task path: /home/wbehrens@domain.local/Code/devops/playbooks/playbooks/deploy-jenkins.yml:1
ok: [jenkins-machine]
META: ran handlers

TASK [Deploy Jenkins] **********************************************************
task path: /home/wbehrens@domain.local/Code/devops/playbooks/playbooks/deploy-jenkins.yml:15
statically imported: /home/wbehrens@domain.local/Code/devops/playbooks/playbooks/roles/docker/tasks/ubuntu.yml
redirecting (type: modules) community.general.ufw to community.general.system.ufw
redirecting (type: modules) community.general.ufw to community.general.system.ufw
redirecting (type: modules) community.general.ufw to community.general.system.ufw
redirecting (type: modules) community.general.ufw to community.general.system.ufw

TASK [docker : Download GPG signing key] ***************************************
task path: /home/wbehrens@domain.local/Code/devops/playbooks/playbooks/roles/docker/tasks/ubuntu.yml:5
fatal: [jenkins-machine]: FAILED! => {"msg": "Incorrect sudo password"}

PLAY RECAP *********************************************************************
jenkins-machine            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
