### ISSUE TITLE
Redshift module doesn't allow RA3 node type

### ISSUE THREAD

**Issue by rushikeshmagar492** [ansible/ansible#80918]
### Summary

The Redshift module doesn't allow ra3.* as a node type option, this is a [newly supported instance types in aws redshift.](https://aws.amazon.com/blogs/big-data/use-amazon-redshift-ra3-with-managed-storage-in-your-modern-data-architecture/)

### Issue Type

Bug Report

### Component Name

redshift

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.2]
  config file = /home/rushikesh/PX/Repos/px-platform/ansible.cfg
  configured module search path = ['/home/rushikesh/PX/Repos/px-platform/programmatic-roles/library']
  ansible python module location = /home/rushikesh/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/rushikesh/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rushikesh/.local/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_FORCE_COLOR(/home/rushikesh/PX/Repos/px-platform/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/rushikesh/PX/Repos/px-platform/ansible.cfg) = ['/home/rushikesh/PX/Repos/px-platform/default']
DEFAULT_MANAGED_STR(/home/rushikesh/PX/Repos/px-platform/ansible.cfg) = managed by intersection ansible
DEFAULT_MODULE_PATH(/home/rushikesh/PX/Repos/px-platform/ansible.cfg) = ['/home/rushikesh/PX/Repos/px-platform/programmatic-roles/l>
DEFAULT_ROLES_PATH(/home/rushikesh/PX/Repos/px-platform/ansible.cfg) = ['/home/rushikesh/PX/Repos/px-platform/roles', '/home/rushik>
DEFAULT_TRANSPORT(/home/rushikesh/PX/Repos/px-platform/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/rushikesh/.vault_pass
HOST_KEY_CHECKING(/home/rushikesh/PX/Repos/px-platform/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/rushikesh/PX/Repos/px-platform/ansible.cfg) = False
```

### OS / Environment

Ubuntu 20.04.6 LTS

### Steps to Reproduce

```yaml (paste below)
  - name: Create Redshift cluster
    community.aws.redshift:
      command: create
      db_name: "{{ redshift_db_name }}"
      elastic_ip: "{{ eip.public_ip }}"
      enhanced_vpc_routing: true
      node_type: ra3.4xlarge
      identifier: "{{ redshift_cluster_name }}"
      username: "{{ redshift_cluster_admin_name }}"
      password: "{{ redshift_cluster_admin_password }}"
      vpc_security_group_ids: "{{ redshift_security_group_id }}"
      cluster_subnet_group_name: "{{ redshift_subnetgroup_name }}"
      region: "{{ aws_region }}"
      publicly_accessible: true
      automated_snapshot_retention_period: "{{ redshift_snapshot_retention_period }}"
      tags: "{{ tags }}"
      wait: true
```

### Expected Results

Redshift cluster with `ra3.4xlarge` node type created.

### Actual Results

```console
TASK [redshift : Create Redshift cluster] ******************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of node_type must be one of: ds1.xlarge, ds1.8xlarge, ds2.xlarge, ds2.8xlarge, dc1.large, dc2.large, dc1.8xlarge, dw1.xlarge, dw1.8xlarge, dw2.large, dw2.8xlarge, got: ra3.4xlarge"}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
