### ISSUE TITLE
`ansible-playbook --tags` only run a dependency role if the first caller was tagged

### ISSUE THREAD

**Issue by adgross** [ansible/ansible#80913]
### Summary

When we have multiple roles with a common dependency,  if we use `--tags` and the first role to use the dependency is not tagged, the dependency will never run.

The `--tags` feature and role dependencies are not working well together.

### Issue Type

Bug Report

### Component Name

ansible-playbook

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/test/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

archlinux

### Steps to Reproduce

Testing tree:
```text
├── playbook.yml
└── roles
    ├── dep
    │   └── tasks
    │       └── main.yml
    ├── role_A
    │   ├── meta
    │   │   └── main.yml
    │   └── tasks
    │       └── main.yml
    └── role_B
        ├── meta
        │   └── main.yml
        └── tasks
            └── main.yml
```

Content of `meta/main.yml` for `role_A` and `role_B`:
```yaml
dependencies:
  - role: dep
```

Content of `tasks/main.yml` for all roles:
```yaml
- ansible.builtin.debug:
    msg: "{{role_name}}"
```
---
Case 1
---
Run `ansible-playbook playbook.yml --tags test` with the following `playbook.yml`:
```yaml
- name: Playbook
  hosts: localhost
  roles:
    - { role: role_A }
    - { role: role_B, tags: test }
```
Output:
```log
ok: [localhost] => {
    "msg": "role_B"
}
```
`dep` didn't run.

---
Case 2
---
Now run `ansible-playbook playbook.yml --tags test` with the following `playbook.yml`:
```yaml
- name: Playbook
  hosts: localhost
  roles:
    - { role: role_A, tags: test }
    - { role: role_B }
```
Output:
```log
ok: [localhost] => {
    "msg": "dep"
}
ok: [localhost] => {
    "msg": "role_A"
}
```
`dep` ran.

---
Case 3
---
In this case we will reference `dep` in the playbook, run `ansible-playbook playbook.yml --tags test` with the following `playbook.yml`:
```yaml
- name: Playbook
  hosts: localhost
  roles:
    - { role: dep }
    - { role: role_A, tags: test }
    - { role: role_B, tags: test  }
```
Output:
```log
ok: [localhost] => {
    "msg": "role_A"
}
ok: [localhost] => {
    "msg": "role_B"
}
```
`dep` **first caller** (or _virtual_ caller) was the playbook itself, `dep` didn't run.

---
Case 4
---
Here we will also tag `dep` in the playbook, run `ansible-playbook playbook.yml --tags test` with the following `playbook.yml`:
```yaml
- name: Playbook
  hosts: localhost
  roles:
    - { role: dep, tags: test }
    - { role: role_A, tags: test }
    - { role: role_B, tags: test  }
```
Output:
```log
ok: [localhost] => {
    "msg": "dep"
}
ok: [localhost] => {
    "msg": "dep"
}
ok: [localhost] => {
    "msg": "role_A"
}
ok: [localhost] => {
    "msg": "role_B"
}
```
`dep` ran **two** times.

### Expected Results

For _Case 4_ I expect `dep` to run once.

I expect all cases to have the same dependency output. 

1. The dependency `dep` should run in _Case 1_ and _Case 3_, given `dep` has never been run before. It was referenced but not actually executed. Given it is marked as dependency, it **should execute** before the role that depends on it really executes, and then be marked as executed, so we have the "run once" behavior checking for that.
    - Workaround:
      - disable ansible "run once" for `dep` role: set `allow_duplicates: true` in `dep/meta/main.yml`.
      - manually control the "run once" using a `block:` and `when:` condition in `dep/tasks/main.yml`.
    ```yaml
    - name: Workaround to run once
      when: dep_run_once is not defined
      block:
        - ansible.builtin.debug:
            msg: "{{role_name}}"
        - set_fact:
            dep_run_once: true
    ```

4. `--tags` filter out the dependencies, and all _Cases_ dont execute `dep` as "_role dependency_".

### Actual Results

```console
We have 2 behaviors:
1. The dependency will run if the first caller was tagged.
2. The dependency never run if all but the first caller were tagged.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
