### ISSUE TITLE
Success message not shown for `assert` module when `quiet` specified

### ISSUE THREAD

**Issue by lonix1** [ansible/ansible#80910]
## Summary

When using `assert` module:
- if `quiet` not specified and `success_msg` specified, then a successful result shows the success message
- *but, if `quiet` and `success_msg` specified, then a successful result does not show the success message*

I expected the success message to be shown in both cases, since I specified `success_msg`.

## Issue Type

Bug Report

### Component Name

assert

## Ansible Version

```console
$ ansible --version

ansible [core 2.14.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

## Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = /etc/ansible/ansible.cfg
```

## OS / Environment

ubuntu 22.04

## Steps to Reproduce

```yaml (paste below)
# without quiet

- ansible.builtin.assert:
    that: "1 == 1"
    success_msg: it succeeded!
    fail_msg: it failed!

- ansible.builtin.assert:
    that: "1 == 2"
    success_msg: it succeeded!
    fail_msg: it failed!
  ignore_errors: true

# with quiet

- ansible.builtin.assert:
    that: "1 == 1"
    success_msg: it succeeded!                      # <-------------------------------------------
    fail_msg: it failed!
    quiet: true

- ansible.builtin.assert:
    that: "1 == 2"
    success_msg: it succeeded!
    fail_msg: it failed!
    quiet: true
  ignore_errors: true
```

## Expected Results
```console
TASK [playbook : ansible.builtin.assert] *****************************************************************************
ok: [myserver] => {
    "changed": false,
    "msg": "it succeeded!"
}

TASK [playbook : ansible.builtin.assert] *****************************************************************************
fatal: [myserver]: FAILED! => {
    "assertion": "1 == 2",
    "changed": false,
    "evaluated_to": false,
    "msg": "it failed!"
}
...ignoring

TASK [playbook : ansible.builtin.assert] *****************************************************************************
ok: [myserver]: SUCCEEDED! => {"assertion": "1 == 1", "changed": false, "evaluated_to": true, "msg": "it succeeded!"}   # <-------------------- 

TASK [playbook : ansible.builtin.assert] *****************************************************************************
fatal: [myserver]: FAILED! => {"assertion": "1 == 2", "changed": false, "evaluated_to": false, "msg": "it failed!"}
...ignoring
```

### Actual Results

```console
TASK [playbook : ansible.builtin.assert] *****************************************************************************
ok: [myserver] => {
    "changed": false,
    "msg": "it succeeded!"
}

TASK [playbook : ansible.builtin.assert] *****************************************************************************
fatal: [myserver]: FAILED! => {
    "assertion": "1 == 2",
    "changed": false,
    "evaluated_to": false,
    "msg": "it failed!"
}
...ignoring

TASK [playbook : ansible.builtin.assert] *****************************************************************************
ok: [myserver]      # <--------------------

TASK [playbook : ansible.builtin.assert] *****************************************************************************
fatal: [myserver]: FAILED! => {"assertion": "1 == 2", "changed": false, "evaluated_to": false, "msg": "it failed!"}
...ignoring
```

## Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/assert.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/assert.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This is not a bug, it is the expected behaviour. `quiet` disables forced verbosity, which means the default callback will not show a detailed result for successful tasks. If you want the message to be shown, use a callback with different behaviour or do not use `quiet`.

```yaml
- hosts: localhost
  tasks:
    - name: Output will not be visible, because the task succeeded
      command: grep doom /etc/services

    - name: You can see the output, because the task failed
      command: sed -e 's/doom/fortnite' /etc/services
      ignore_errors: true
```

```
PLAY [localhost] ***************************************************************

TASK [Output will not be visible, because the task succeeded] ********************
changed: [localhost]

TASK [You can see the output, because the task failed] *************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["sed", "-e", "s/doom/fortnite", "/etc/services"], "delta": "0:00:00.003885", "end": "2023-05-28 10:37:02.553244", "msg": "non-zero return code", "rc": 1, "start": "2023-05-28 10:37:02.549359", "stderr": "sed: -e expression #1, char 15: unterminated `s' command", "stderr_lines": ["sed: -e expression #1, char 15: unterminated `s' command"], "stdout": "", "stdout_lines": []}
...ignoring
```
