### ISSUE TITLE
Handler inherits "when" condition from the last task from the same role

### ISSUE THREAD

**Issue by simaishi** [ansible/ansible#80925]
### Summary

A handler that was notified earlier gets "when" condition applied at the time it runs, if the last task from that same role where handler is coming from had "when" condition in a block.

### Issue Type

Bug Report

### Component Name

handler

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, Dec 21 2022, 10:57:18) [GCC 8.5.0 20210514 (Red Hat 8.5.0-17)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

RHEL 8.7

### Steps to Reproduce

playbook
```yaml (paste below)
- hosts: group1:group2
  tasks:
    - include_role:
        name: role1

    - include_role:
        name: role2

    - block:
        - include_role:
            name: role1
            tasks_from: main2.yml
      when: inventory_hostname in groups['group2']
```
role1/handlers/main.yml
```yaml (paste below)
- name: handler_in_role1
  debug:
    msg: "Handler in role1"
```
role2/tasks/main.yml
```yaml (paste below)
- debug:
    msg: "main in role2"
  changed_when: true
  notify: handler_in_role1
```

### Expected Results

The handler runs for both hosts (this output is from 2.14.6)
```yaml
...
TASK [role2 : debug] ************************************************************************************************************************************************************************************
task path: /tmp/test/roles/role2/tasks/main.yml:1
NOTIFIED HANDLER role1 : handler_in_role1 for host1
changed: [host1] => {
    "msg": "main in role2"
}
NOTIFIED HANDLER role1 : handler_in_role1 for host2
changed: [host2] => {
    "msg": "main in role2"
}

TASK [include_role : role1] *****************************************************************************************************************************************************************************
task path: /tmp/test/test.yml:11
skipping: [host1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [role1 : debug] ************************************************************************************************************************************************************************************
task path: /tmp/test/roles/role1/tasks/main2.yml:1
ok: [host2] => {
    "msg": "main2 in role1"
}

RUNNING HANDLER [role1 : handler_in_role1] **************************************************************************************************************************************************************
task path: /tmp/test/roles/role1/handlers/main.yml:1
ok: [host1] => {
    "msg": "Handler in role1"
}
ok: [host2] => {
    "msg": "Handler in role1"
}
```

### Actual Results

```console
...
TASK [role2 : debug] ************************************************************************************************************************************************************************************
task path: /tmp/test/roles/role2/tasks/main.yml:1
Notification for handler handler_in_role1 has been saved.
changed: [host1] => {
    "msg": "main in role2"
}
Notification for handler handler_in_role1 has been saved.
changed: [host2] => {
    "msg": "main in role2"
}

TASK [include_role : role1] *****************************************************************************************************************************************************************************
task path: /tmp/test/test.yml:11
skipping: [host1] => {"changed": false, "false_condition": "inventory_hostname in groups['group2']", "skip_reason": "Conditional result was False"}

TASK [role1 : debug] ************************************************************************************************************************************************************************************
task path: /tmp/test/roles/role1/tasks/main2.yml:1
ok: [host2] => {
    "msg": "main2 in role1"
}
NOTIFIED HANDLER role1 : handler_in_role1 for host1
NOTIFIED HANDLER role1 : handler_in_role1 for host2

RUNNING HANDLER [role1 : handler_in_role1] **************************************************************************************************************************************************************
task path: /tmp/test/roles/role1/handlers/main.yml:1
skipping: [host1] => {"false_condition": "inventory_hostname in groups['group2']"}
ok: [host2] => {
    "msg": "Handler in role1"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
