### ISSUE TITLE
ansible.builtin.unarchive does not respect destination mode (permission)

### ISSUE THREAD

**Issue by 4wk-** [ansible/ansible#80936]
### Summary

When using `ansible.builtin.unarchive`, permissions of the destination folder (mode) are not preserved, as it should be.

The [documentation ](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html#parameter-mode) specify: 
> If mode is not specified and the destination filesystem object does exist, the mode of the existing filesystem object will be used.

See my minimal, reproducible example below.

### Issue Type

Bug Report

### Component Name

unarchive

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = /home/xxx/main/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

WSL 2 on Debian 11.6 (Windows 10 host)

### Steps to Reproduce

```yaml (paste below)
  - name: create directory
    ansible.builtin.file:
      path: /srv/foo
      state: directory
      owner: root
      group: "adm"
      # 2 = setgid flag
      mode: '2750'
      access_time: preserve
      modification_time: preserve

  - name: Download and unarchive runner package
    ansible.builtin.unarchive:
      src: "https://github.com/actions/runner/releases/download/v2.304.0/actions-runner-linux-x64-2.304.0.tar.gz"
      dest: /srv/foo
      owner: root
      group: "adm"
      remote_src: yes
```

### Expected Results

After the first task, permissions on `/srv/foo` directory are: 
```
drwxr-s--- 2 root adm  4096 May 31 12:02 foo
```
=> this is **OK**
I expect the permission to **stay the same** after using `ansible.builtin.unarchive` task.

### Actual Results

After the second task, permissions on /srv/foo directory are:
```
drwxr-xr-x 4 root adm  4096 Apr 26 22:05 foo
```
=> this is **NOT OK**, it should have stayed the same `drwxr-s---`

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/unarchive.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/unarchive.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by 4wk-** [comment]
Also kinda related to https://github.com/ansible/ansible/issues/46742 for the `setgid` bit part.

**Comment by Akasurde** [comment]
@4wk- I am not able to reproduce this - 

```yaml

---
- hosts: localhost
  gather_facts: no
  vars:
    dir: './src'
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        mode: '2750'
        owner: akasurde
        group: staff
        access_time: preserve
        modification_time: preserve

    - name: Get permissions before unarchive
      stat:
        path: "{{ dir }}"
      register: before_st

    - name: Download and unarchive runner package
      ansible.builtin.unarchive:
        src: spam.tar.gz
        dest: "{{ dir }}"

    - name: Get permissions after unarchive
      stat:
        path: "{{ dir }}"
      register: after_st
  
    - assert:
        that:
          - before_st.stat.mode == after_st.stat.mode
```
