### ISSUE TITLE
delegate_to localhost not work for 127.0.0.1 

### ISSUE THREAD

**Issue by reini-1** [ansible/ansible#80946]
### Summary

There seems to be a bug in Ansible 2.15, when using `delegate_to: localhost` and then accessing hostvars[127.0.0.1] first in a task, then the variable is undefined, when accessing hostvars[localhost] first and than hostvars[127.0.0.1] everything is ok.

The same happens when using `delegate_to: 127.0.0.1` but reversed.

With Ansible 2.12 this works as expected.

### Issue Type

Bug Report

### Component Name

ansible core

### Ansible Version

```console
macOS-13.4> $ ansible --version | sed "s/$(id -un)/reini/g" 
ansible [core 2.15.0]
  config file = /Users/reini/Source/ops/ansible/ansible.cfg
  configured module search path = ['/Users/reini/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/reini/.ansible/collections:/usr/share/ansible/collections:/Users/reini/Source/ops/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/Cellar/ansible/8.0.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

Debian-11> $ ansible --version | sed "s/$(id -un)/reini/g"
ansible [core 2.12.10]
  config file = /home/reini/Source/ops/ansible/ansible.cfg
  configured module search path = ['/home/reini/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/reini/.ansible/collections:/usr/share/ansible/collections:/home/reini/Source/ops/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'

macOS-13.4> $ ansible-config dump --only-changed -t all | sed "s/$(id -un)/reini/g"
ANSIBLE_PIPELINING(/Users/reini/Source/ops/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/Users/reini/Source/ops/ansible/ansible.cfg) = ['/Users/reini/.ansible/collections', '/usr/share/ansible/collections', '/Users/reini/Source/ops/ansible/collections']
CONFIG_FILE() = /Users/reini/Source/ops/ansible/ansible.cfg
DEFAULT_HOST_LIST(/Users/reini/Source/ops/ansible/ansible.cfg) = ['/Users/reini/Source/ops/ansible/inventory.yml']
DEFAULT_LOAD_CALLBACK_PLUGINS(/Users/reini/Source/ops/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/Users/reini/Source/ops/ansible/ansible.cfg) = ['/Users/reini/Source/ops/ansible/roles']
DEFAULT_TRANSPORT(/Users/reini/Source/ops/ansible/ansible.cfg) = smart
DEPRECATION_WARNINGS(/Users/reini/Source/ops/ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/Users/reini/Source/ops/ansible/ansible.cfg) = False
EDITOR(env: EDITOR) = vi
INTERPRETER_PYTHON(/Users/reini/Source/ops/ansible/ansible.cfg) = auto_silent

CALLBACK:
========

default:
_______
display_skipped_hosts(/Users/reini/Source/ops/ansible/ansible.cfg) = False
pretty_results(/Users/reini/Source/ops/ansible/ansible.cfg) = True
show_task_path_on_failure(/Users/reini/Source/ops/ansible/ansible.cfg) = True

minimal:
_______
pretty_results(/Users/reini/Source/ops/ansible/ansible.cfg) = True

CONNECTION:
==========

local:
_____
pipelining(/Users/reini/Source/ops/ansible/ansible.cfg) = True

psrp:
____
pipelining(/Users/reini/Source/ops/ansible/ansible.cfg) = True

ssh:
___
pipelining(/Users/reini/Source/ops/ansible/ansible.cfg) = True
scp_executable(/Users/reini/Source/ops/ansible/ansible.cfg) = /usr/bin/scp
scp_if_ssh(/Users/reini/Source/ops/ansible/ansible.cfg) = True
ssh_executable(/Users/reini/Source/ops/ansible/ansible.cfg) = /usr/bin/ssh

winrm:
_____
pipelining(/Users/reini/Source/ops/ansible/ansible.cfg) = True


Debian-11> $ ansible-config dump --only-changed -t all | sed "s/$(id -un)/reini/g"
ANSIBLE_PIPELINING(/home/reini/Source/ops/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/home/reini/Source/ops/ansible/ansible.cfg) = ['/home/reini/.ansible/collections', '/usr/share/ansible/collections', '/home/reini/Source/ops/ansible/collections']
DEFAULT_HOST_LIST(/home/reini/Source/ops/ansible/ansible.cfg) = ['/home/reini/Source/ops/ansible/inventory.yml']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/reini/Source/ops/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/reini/Source/ops/ansible/ansible.cfg) = ['/home/reini/Source/ops/ansible/roles']
DEFAULT_TRANSPORT(/home/reini/Source/ops/ansible/ansible.cfg) = smart
DEPRECATION_WARNINGS(/home/reini/Source/ops/ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/reini/Source/ops/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/reini/Source/ops/ansible/ansible.cfg) = auto_silent

BECOME:
======

CACHE:
=====

CALLBACK:
========

default:
_______
display_skipped_hosts(/home/reini/Source/ops/ansible/ansible.cfg) = False
show_task_path_on_failure(/home/reini/Source/ops/ansible/ansible.cfg) = True

CLICONF:
=======

CONNECTION:
==========

local:
_____
pipelining(/home/reini/Source/ops/ansible/ansible.cfg) = True

psrp:
____
pipelining(/home/reini/Source/ops/ansible/ansible.cfg) = True

ssh:
___
scp_executable(/home/reini/Source/ops/ansible/ansible.cfg) = /usr/bin/scp
scp_if_ssh(/home/reini/Source/ops/ansible/ansible.cfg) = True
ssh_executable(/home/reini/Source/ops/ansible/ansible.cfg) = /usr/bin/ssh

winrm:
_____
pipelining(/home/reini/Source/ops/ansible/ansible.cfg) = True

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

macOS 13.4, Debian Linux 11

### Steps to Reproduce

```yaml
---
- name: GATHER LOCAL FACTS
  hosts: all
  gather_facts: false
  run_once: true
  tags: always
  tasks:
    - name: Gather only necessary local facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - date_time
          - machine
          - distribution
      delegate_to: localhost
      # delegate_to: 127.0.0.1
      delegate_facts: true

    # Seems to be a bug, when using `delegate_to: localhost` and then accessing hostvars[127.0.0.1]
    # first in a task, then the variable is undefined, when accessing hostvars[localhost] first,
    # everything is ok.

    - name: Show hostvars[127.0.0.1], hostvars[localhost]
      ansible.builtin.debug:
        msg:
          - 'hostvars[127.0.0.1]:'
          - 'ansible_hostname: {{ hostvars["127.0.0.1"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["127.0.0.1"].ansible_nodename | default("UNDEFINED") }}'
          - 'hostvars[localhost]:'
          - 'ansible_hostname: {{ hostvars["localhost"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["localhost"].ansible_nodename | default("UNDEFINED") }}'

    - name: Show hostvars[localhost], hostvars[127.0.0.1]
      ansible.builtin.debug:
        msg:
          - 'hostvars[localhost]:'
          - 'ansible_hostname: {{ hostvars["localhost"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["localhost"].ansible_nodename | default("UNDEFINED") }}'
          - 'hostvars[127.0.0.1]:'
          - 'ansible_hostname: {{ hostvars["127.0.0.1"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["127.0.0.1"].ansible_nodename | default("UNDEFINED") }}'

    - name: Show hostvars[localhost]
      ansible.builtin.debug:
        msg:
          - 'hostvars[localhost]:'
          - 'ansible_hostname: {{ hostvars["localhost"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["localhost"].ansible_nodename | default("UNDEFINED") }}'

    - name: Show hostvars[127.0.0.1]
      ansible.builtin.debug:
        msg:
          - 'hostvars[127.0.0.1]:'
          - 'ansible_hostname: {{ hostvars["127.0.0.1"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["127.0.0.1"].ansible_nodename | default("UNDEFINED") }}'

- name: GATHER FACTS
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Gather Facts
      block:
        - name: Gather only necessary remote facts
          ansible.builtin.setup:
            gather_subset:
              - '!all'
              - '!min'
              - machine
              - distribution

- name: SHOW RESULTS
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Show hostvars[127.0.0.1], hostvars[localhost]
      ansible.builtin.debug:
        msg:
          - 'hostvars[127.0.0.1]:'
          - 'ansible_hostname: {{ hostvars["127.0.0.1"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["127.0.0.1"].ansible_nodename | default("UNDEFINED") }}'
          - 'hostvars[localhost]:'
          - 'ansible_hostname: {{ hostvars["localhost"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["localhost"].ansible_nodename | default("UNDEFINED") }}'

    - name: Show hostvars[localhost], hostvars[127.0.0.1]
      ansible.builtin.debug:
        msg:
          - 'hostvars[localhost]:'
          - 'ansible_hostname: {{ hostvars["localhost"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["localhost"].ansible_nodename | default("UNDEFINED") }}'
          - 'hostvars[127.0.0.1]:'
          - 'ansible_hostname: {{ hostvars["127.0.0.1"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["127.0.0.1"].ansible_nodename | default("UNDEFINED") }}'

    - name: Show hostvars[localhost]
      ansible.builtin.debug:
        msg:
          - 'hostvars[localhost]:'
          - 'ansible_hostname: {{ hostvars["localhost"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["localhost"].ansible_nodename | default("UNDEFINED") }}'

    - name: Show hostvars[127.0.0.1]
      ansible.builtin.debug:
        msg:
          - 'hostvars[127.0.0.1]:'
          - 'ansible_hostname: {{ hostvars["127.0.0.1"].ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_nodename: {{ hostvars["127.0.0.1"].ansible_nodename | default("UNDEFINED") }}'

    - name: Show remote vars
      ansible.builtin.debug:
        msg:
          - 'remote host facts:'
          - 'ansible_hostname: {{ ansible_hostname | default("UNDEFINED") }}'
          - 'ansible_distribution: {{ ansible_distribution | default("UNDEFINED") }}'
          - 'ansible_distribution_release: {{ ansible_distribution_release | default("UNDEFINED") }}'

    - name: Hostvars.localhost
      ansible.builtin.debug:
        var: hostvars.localhost
      when: ('verbose' in ansible_run_tags)

    - name: Hostvars
      ansible.builtin.debug:
        var: hostvars
      when: ('debug' in ansible_run_tags)
```

### Expected Results

hostvars[localhost] and hostvars[127.0.0.1] should always have a value.

### Actual Results

```console
PLAY [GATHER LOCAL FACTS] ******************************************************

TASK [Gather only necessary local facts] ***************************************
ok: [test.example.com -> localhost]

TASK [Show hostvars[127.0.0.1], hostvars[localhost]] ***************************
ok: [test.example.com] => {
    "msg": [
        "hostvars[127.0.0.1]:",
        "ansible_hostname: UNDEFINED",
        "ansible_nodename: UNDEFINED",
        "hostvars[localhost]:",
        "ansible_hostname: UNDEFINED",
        "ansible_nodename: UNDEFINED"
    ]
}

TASK [Show hostvars[localhost], hostvars[127.0.0.1]] ***************************
ok: [test.example.com] => {
    "msg": [
        "hostvars[localhost]:",
        "ansible_hostname: MBP-009",
        "ansible_nodename: MBP-009",
        "hostvars[127.0.0.1]:",
        "ansible_hostname: MBP-009",
        "ansible_nodename: MBP-009"
    ]
}

TASK [Show hostvars[localhost]] ************************************************
ok: [test.example.com] => {
    "msg": [
        "hostvars[localhost]:",
        "ansible_hostname: MBP-009",
        "ansible_nodename: MBP-009"
    ]
}

TASK [Show hostvars[127.0.0.1]] ************************************************
ok: [test.example.com] => {
    "msg": [
        "hostvars[127.0.0.1]:",
        "ansible_hostname: UNDEFINED",
        "ansible_nodename: UNDEFINED"
    ]
}

PLAY [GATHER FACTS] ************************************************************

TASK [Gather only necessary remote facts] **************************************
ok: [test.example.com]

PLAY [SHOW RESULTS] ************************************************************

TASK [Show hostvars[127.0.0.1], hostvars[localhost]] ***************************
ok: [test.example.com] => {
    "msg": [
        "hostvars[127.0.0.1]:",
        "ansible_hostname: UNDEFINED",
        "ansible_nodename: UNDEFINED",
        "hostvars[localhost]:",
        "ansible_hostname: UNDEFINED",
        "ansible_nodename: UNDEFINED"
    ]
}

TASK [Show hostvars[localhost], hostvars[127.0.0.1]] ***************************
ok: [test.example.com] => {
    "msg": [
        "hostvars[localhost]:",
        "ansible_hostname: MBP-009",
        "ansible_nodename: MBP-009",
        "hostvars[127.0.0.1]:",
        "ansible_hostname: MBP-009",
        "ansible_nodename: MBP-009"
    ]
}

TASK [Show hostvars[localhost]] ************************************************
ok: [test.example.com] => {
    "msg": [
        "hostvars[localhost]:",
        "ansible_hostname: MBP-009",
        "ansible_nodename: MBP-009"
    ]
}

TASK [Show hostvars[127.0.0.1]] ************************************************
ok: [test.example.com] => {
    "msg": [
        "hostvars[127.0.0.1]:",
        "ansible_hostname: UNDEFINED",
        "ansible_nodename: UNDEFINED"
    ]
}

TASK [Show remote vars] ********************************************************
ok: [test.example.com] => {
    "msg": [
        "remote host facts:",
        "ansible_hostname: test",
        "ansible_distribution: Debian",
        "ansible_distribution_release: bullseye"
    ]
}

PLAY RECAP *********************************************************************
test.example.com : ok=11   changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
