### ISSUE TITLE
ca_cert not found on macOS without workaround

### ISSUE THREAD

**Issue by ctipper** [ansible/ansible#80955]
### Summary

I'm experiencing a basic certififcate validation error which I can mitigate by putting a soft link to /etc/ssl/cert.pem in the ansible settings directory. I am not sure if it is affected by this PR [Fix HTTP tests on FreeBSD when running split.](https://github.com/ansible/ansible/blame/0982d5fa98e64d241249cfd6dd024e70ae20d0c3/test/integration/targets/uri/tasks/main.yml#L184) which introduced a clause before macOS ca-cert at `/etc/ssl/cert.pem` is checked.

### Issue Type

Bug Report

### Component Name

get_url

### Ansible Version

```console
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  python version = 3.10.11 (main, Apr  8 2023, 02:11:11) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10)
  jinja version = 3.1.2
  libyaml = False
```

### Configuration

```console
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

$ uname -a
Darwin metope.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64

### Steps to Reproduce

```
- name: download the Let's Encrypt intermediate CA
  get_url:
    url: "{{ ler53_intermediate_download_url }}"
    dest: "{{ ler53_cert_dir }}/{{ ler53_intermediate_file_name }}"
    owner: "{{ ler53_cert_files_owner }}"
    group: "{{ ler53_cert_files_group }}"
    mode: "{{ ler53_cert_files_mode }}"
  register: ler53_intermediate_download_task
  when: ler53_intermediate_download | bool
```

### Expected Results

That this does not happen `<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]`

### Actual Results

```console
`<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
