### ISSUE TITLE
with_fileglob is executed even task is part of skipped block

### ISSUE THREAD

**Issue by msl0** [ansible/ansible#80956]
### Summary

My task is in a block which is executed if the specified directory exists on the controller. When whole block is skipped because the condition is not met (directory doesn't exists), then I'm getting warnings
```
TASK [Copy files] ************************************************************************************************************************************************************
[WARNING]: Unable to find 'xxx' in expected paths (use -vvvvv to see paths)
[WARNING]: Unable to find 'xxx' in expected paths (use -vvvvv to see paths)
```
In next tasks in the same block I'm using fileglob but this way `lookup('ansible.builtin.fileglob', path)` in module parameters (not in loop) and I don't see any errors.

Should fileglob lookup execution be skipped when whole task is skipped? I'm not sure if the current behavior is intended.

### Issue Type

Bug Report

### Component Name

with_fileglob

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.7]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
- name: Test
  hosts: all
  connection: localhost
  tasks:
    - block:
      when: false
      - name: Copy files
        ansible.builtin.copy:
          src: "{{ item }}"
          dest: "/tmp/{{ item | basename }}"
        with_fileglob:
          - "non-existing-path
        loop_control:
          label: "{{ item | basename }}"
        register: copy
    - name: Get list of manually added files in destination
      ansible.builtin.find:
        path: /tmp
        file_type: any
        pattern:
          - "*[!~]" # Exclude files ending with tilde
        excludes: "{{ lookup('ansible.builtin.fileglob', 'non-existing-path' wantlist=True) | map('basename') }}"
      register: files_to_remove
```

### Expected Results

Output for skipped task with with_fileglob without warnings when specified file not exists **if current behavior is wrong** 

### Actual Results

```console
Getting warnings for skipped task when path does not exit

TASK [Copy files] ************************************************************************************************************************************************************
[WARNING]: Unable to find 'xxx' in expected paths (use -vvvvv to see paths)
[WARNING]: Unable to find 'xxx' in expected paths (use -vvvvv to see paths)
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
