### ISSUE TITLE
No_log parameter in ansible modules gets ignored when task is looped

### ISSUE THREAD

**Issue by WallsTalk** [ansible/ansible#80966]
### Summary

I'm making some POST requests using ansible "uri" module. Now when I'm calling this module a single time in task the module parameter set with no_log to true obeys this rule. When I put such task into a loop, I can see the url_password field as open text which normally is a no log parameter inside of the ansible module. For me this does not seem like intended behavior, was wondering if a fix was possible. Currently as a work around I set whole task to no_log, and extract the output through the register variable in a later task, but it seems like an overkill every time. The issue is persistent with costume and built in modules alike.

### Issue Type

Feature Idea

### Component Name

loop

### Additional Information

**some_var_file.yml**
```yaml

password: |
  ANSIBLE VAULTED VALUE...
  asdsadasdaasdsada
  adsadasdsadsadasd

```
**exectution.yml**
```yaml
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - some_var_file.yml
  tasks:
    - uri:
        url: "some_endpoint"
        url_username: "{{ username }}"
        url_password: "{{ password }}"
        force_basic_auth: yes
        method: "POST"
        body_format: "json"
        status_code: [ 200 ]
        body:
          x: "{{ item }}"
      register: status
      loop: "{{ a list of x }}"

```

The issue exists on 2.9 and 2.12, Note that we are using ansible tower to check the logs, and we have no way to test it directly on execution environment, so it could be somehow that its AT issue.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
I'll make some assumptions, and guess that the task really looks more like this:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - uri:
        url: '{{ item.url }}'
        user: '{{ item.user }}'
        password: '{{ item.password }}'
        force_basic_auth: yes
      loop:
        - url: https://httpbingo.org/basic-auth/user/passwd
          user: user
          password: passwd
```

And that the password being seen is part of the loop output, which is completely disconnected from any argument that a module declares as `no_log`

Example output:

```
TASK [uri] *********************************************************************
ok: [localhost] => (item={'url': 'https://httpbingo.org/basic-auth/user/passwd', 'user': 'user', 'password': 'passwd'}) => {"access_control_allow_credentials": "true", "access_control_allow_origin": "*", "ansible_loop_var": "item", "changed": false, "content_length": "43", "content_type": "application/json; encoding=utf-8", "cookies": {}, "cookies_string": "", "date": "Mon, 05 Jun 2023 19:36:15 GMT", "elapsed": 0, "fly_request_id": "01H26GYR07XFV30GA6QGJ9X3G9-dfw", "item": {"password": "passwd", "url": "https://httpbingo.org/basic-auth/user/passwd", "user": "user"}, "json": {"authorized": true, "user": "user"}, "msg": "OK (43 bytes)", "redirected": false, "server": "Fly/bba2dac0 (2023-06-02)", "status": 200, "url": "https://httpbingo.org/basic-auth/user/********", "via": "1.1 fly.io"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

needs_info
