### ISSUE TITLE
 Warning Module remote_tmp /var/lib/postgresql/.ansible/tmp did not exist ...

### ISSUE THREAD

**Issue by dioguinhocst** [ansible/ansible#80986]
### Summary

Hello,

I have this warning ([WARNING]: Module remote_tmp /var/lib/postgresql/.ansible/tmp did not exist and was created with a mode of 0700,
this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct
permissions manually) but i don't understand why i have it.

I add some tasks to correct this warning, but that's not working ... 

    - name: Vérifier et créer le répertoire remote_tmp
      stat:
        path: /var/lib/postgresql/.ansible/remote_tmp
      register: remote_tmp_dir

    - name: Créer le répertoire remote_tmp si nécessaire
      become: true
      file:
        path: /var/lib/postgresql/.ansible/remote_tmp
        state: directory
        owner: postgres
        group: postgres
        mode: '0777'
      when: not remote_tmp_dir.stat.exists

    - name: Définir le mot de passe pour l'utilisateur "postgres"
      postgresql_user:
        name: postgres
        password: "{{ new_password }}"
      become_user: postgres
      
    
Can someone help me get rid of this warning
Have a nice day !

### Issue Type

Bug Report

### Component Name

remote_tmp

### Ansible Version

```console
$ ansible --version

ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/terrible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/terrible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

PRETTY_NAME="Ubuntu 22.04.2 LTS"

### Steps to Reproduce

```yaml (paste below)
  - name: Vérifier et créer le répertoire remote_tmp
      stat:
        path: /var/lib/postgresql/.ansible/remote_tmp
      register: remote_tmp_dir

    - name: Créer le répertoire remote_tmp si nécessaire
      become: true
      file:
        path: /var/lib/postgresql/.ansible/remote_tmp
        state: directory
        owner: postgres
        group: postgres
        mode: '0777'
      when: not remote_tmp_dir.stat.exists

    - name: Définir le mot de passe pour l'utilisateur "postgres"
      postgresql_user:
        name: postgres
        password: "{{ new_password }}"
      become_user: postgres
```

### Expected Results

```
TASK [Vérifier et créer le répertoire remote_tmp] *******************************************************************
ok: [Psql]

TASK [Créer le répertoire remote_tmp si nécessaire] *****************************************************************
changed: [Psql]

TASK [Définir le mot de passe pour l'utilisateur "postgres"] ********************************************************
changed: [Psql]
```

### Actual Results

```console
TASK [Vérifier et créer le répertoire remote_tmp] *******************************************************************
ok: [Psql]

TASK [Créer le répertoire remote_tmp si nécessaire] *****************************************************************
changed: [Psql]

TASK [Définir le mot de passe pour l'utilisateur "postgres"] ********************************************************
[WARNING]: Module remote_tmp /var/lib/postgresql/.ansible/tmp did not exist and was created with a mode of 0700,
this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct
permissions manually
changed: [Psql]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
