### ISSUE TITLE
Support useradd --add-subids-for-system option

### ISSUE THREAD

**Issue by GerardoGR** [ansible/ansible#80988]
### Summary

`useradd` introduced in version [4.12](https://github.com/shadow-maint/shadow/releases/tag/4.12) the [--add-subids-for-system](https://github.com/shadow-maint/shadow/pull/540/files) option. This option creates the `subuid` and `subgid` entries respecting the `login.defs` configuration for **system users**.

Implementing this option will simplify the maintenance of the `subuid` and `subgid` entries for system users.

This addresses in a simplified way: https://github.com/ansible/ansible/issues/68199

### Issue Type

Feature Idea

### Component Name

user

### Additional Information

The `user` module could include a new `add_subids_for_system` (boolean) option, like:
```yaml (paste below)
- name: Create the system user 'my-vpn'
  ansible.builtin.user:
    name: my-vpn
    shell: /sbin/nologin
    create_home: true
    system: true
    add_subids_for_system: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
