### ISSUE TITLE
Emphasise `variable_start_string`/`variable_end_string` affects templated `vars`

### ISSUE THREAD

**Issue by stephenfin** [ansible/ansible#80996]
### Summary

I want to template a file that is already a Jinja2 template. This necessitates configuring `variable_start_string`, `variable_end_string` etc. However, it turns out setting these also affects evaluation of templated variables defined in the same step. It is necessary to use the new marker strings for any templated variables. For example:

```yaml
---
# ...
- hosts: bastion
  tasks:
  # ...
  - name: Copy globals.yml file
    ansible.builtin.copy:
      src: files/globals.yml
    ansible.builtin.template:
      src: templates/globals.yml.j2
      dest: /etc/kolla/globals.yml
      block_start_string: "<%"
      block_end_string: "%>"
      variable_start_string: "<<"
      variable_end_string: ">>"
    vars:
      internal_vip_address: "<< hostvars['host-00']['ansible_host'] >>"
  # ...
```

This was previously reported as https://github.com/ansible/ansible/issues/43886, however, that was closed as the issue could not be fixed. This is understandable, however, there's no reason we shouldn't document it.

### Issue Type

Documentation Report

### Component Name

lib/ansible/modules/template.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/home/cloud/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /etc/kolla/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/cloud/.ansible/collections:/usr/share/ansible/collections
  executable location = /etc/kolla/venv/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/etc/kolla/venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Ubuntu 22.04

### Additional Information

The documentation should emphasise that the `variable_start_string`, `variable_end_string` etc. settings affects templated `vars`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
