### ISSUE TITLE
Variable set with lookup in playbook is empty in role

### ISSUE THREAD

**Issue by Toemmsn** [ansible/ansible#8099]
##### Summary:

Creating variables whose content is filled via file lookup are empty when being used inside a role. Using them inside the playbook directly they are OK.
##### Steps To Reproduce:

Create a playbook like the following:

```

---
- hosts: test-hosts
  vars:
    - testingthis:
      - value_1
      - value_2
      - "{{ lookup('file', ‘testfile1’) }}"
      - "{{ lookup('file', ‘testfile2’) }}"
  roles:
    - role: my-test-role
```

Create a role my-test-role where tasks/mail.yml looks like

```

---
- name: check
  debug: msg=“variable content is {{ item }}"
  with_items: testingthis
```

Create the files testfile1 and testfile2 with a single line of text and run the playbook
##### Expected Results:

The run of the playbook should give me the values value_1, value_2, content of testfile1, content of testfile2
##### Actual Results:

I can see value_1, value_2 and then "" for testfile1 and testfile2

Trying to change the playbook the following way

```

---
- hosts: test-hosts
  vars:
    - testingthis:
      - value_1
      - value_2
      - "{{ lookup('file', ‘testfile1’) }}"
      - "{{ lookup('file', ‘testfile2’) }}"
  tasks:
    - debug: msg="variable content is {{ item }}"
      with_items: testingthis
```

gives the expected result.
