### ISSUE TITLE
dnf module : gcc-toolset-12-binutils package does not gets updated

### ISSUE THREAD

**Issue by rdulhani-official** [ansible/ansible#81018]
### Summary

dnf module : gcc-toolset-12-binutils package does not gets updated using the ansible playbook using the dnf module.
rest all the packages gets updated . Tried and tested using the below ansible playbook.
```
- hosts: localhost
  tasks:
   - name: update wget
     dnf:
       name: httpd,gcc-toolset-12-binutils
       state: latest
       update_cache: yes
       update_only: yes
```

### Issue Type

Bug Report

### Component Name

dnf

### Ansible Version

```console
$ ansible --version

# rpm -qa | grep ansible-core
ansible-core-2.14.2-3.el8.x86_64

# ansible --version
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb 17 2023, 09:28:16) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.8 (Ootpa)

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  tasks:
   - name: update wget
     dnf:
       name: httpd,gcc-toolset-12-binutils
       state: latest
       update_cache: yes
       update_only: yes
```

### Expected Results

both the packages httpd,gcc-toolset-12-binutils should be updated to the latest with is not the case with the gcc-toolset-12-binutils package. it does not gets updated.

### Actual Results

```console
# rpm -qa | grep  gcc-toolset-12-binutils
gcc-toolset-12-binutils-gold-2.38-17.el8.x86_64
gcc-toolset-12-binutils-2.38-16.el8.x86_64

[root@rhel84 ~]# rpm -qa | grep httpd
httpd-2.4.37-56.module+el8.8.0+18758+b3a9c8da.6.x86_64
httpd-tools-2.4.37-56.module+el8.8.0+18758+b3a9c8da.6.x86_64
redhat-logos-httpd-84.5-1.el8.noarch
httpd-filesystem-2.4.37-56.module+el8.8.0+18758+b3a9c8da.6.noarch


Latest package of gcc-toolset-12-binutils is available.

~~~
# yum list gcc-toolset-12-binutils

Updating Subscription Management repositories.
Last metadata expiration check: 0:14:40 ago on Sat 10 Jun 2023 02:25:31 AM IST.
Installed Packages
gcc-toolset-12-binutils.x86_64                               2.38-16.el8                               @rhel-8-for-x86_64-appstream-rpms
Available Packages
gcc-toolset-12-binutils.x86_64                               2.38-17.el8                               rhel-8-for-x86_64-appstream-rpms 
~~~
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dnf.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
I have verified that this is indeed a problem in the `dnf` module.

The problem causing this is with our custom parsing of `name`:
https://github.com/ansible/ansible/blob/2cd1744be3d96f1eec674e1b66433c3730caa24f/lib/ansible/modules/dnf.py#L515
which fails on names like `gcc-toolset-12-binutils` where `-` would be incorrectly considered a delimiter for individual parts of `nevra`. We then use the result of incorrect parsing to check whether the package is installed.

To achieve the `update_only` functionality you would have to unfortunately do something like the following:
```yaml
- command: rpm -q gcc-toolset-12-binutils
  register: is_installed
  ignore_errors: true
    
- dnf:
    name: gcc-toolset-12-binutils
    state: latest
  when: is_installed.rc == 0
```
