### ISSUE TITLE
URI multipart file is changed

### ISSUE THREAD

**Issue by PandeoF1** [ansible/ansible#81048]
### Summary

When uploading zip file using builtin.uri using form/multipart, the uploads fails on my api because the file is corrupted. But using curl/postman/python it work fine. (The zip is corrupted when he is received by the api using ansbile, on my computer the zip is fine)

### Issue Type

Bug Report

### Component Name

builtin.uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/.local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

WSL Ubuntu 22.0

### Steps to Reproduce

(host: localhost)
```yam
- name: Upload zip file
  ansible.builtin.uri:
    method: POST
    url: "{{ api_endpoint }}/resource/groups"
    body_format: form-multipart
    body: 
      groups:
        filename: "./policies.zip"
      mime_type: application/octet-stream
    headers:
      Content-Type: multipart/form-data
      authorization: "Bearer {{ access_token }}"
    status_code: 201
  register: result  
```

### Expected Results

It should return a 201 OK when the zip is uploaded. But my api return a 400 invalid file format.
I have try on a http listener to look the file and there is a difference between curl/postman and ansible on the file :

 - curl/postman : 
![image](https://github.com/ansible/ansible/assets/58373303/9950c6d8-5914-44ec-90fc-06006d31989d)
![image](https://github.com/ansible/ansible/assets/58373303/768e15cd-a215-40e1-b053-cd1f18ebcaf4)
 - ansible :
![image](https://github.com/ansible/ansible/assets/58373303/12e96635-6eb5-46bd-9a61-f95d04001a73)
![image](https://github.com/ansible/ansible/assets/58373303/f452bb36-ec85-42e1-af04-6cabffdb7e6c)

### Actual Results

```console
...400 Invalid format...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
I cannot replicate this behavior with an RFC compliant web server.

I'm going to assume that the webserver you are dealing with is ignoring the `Content-Transfer-Encoding` header which is communicating that the data is `base64` encoded, and as such, it's taking the base64 data as the literal contents of the file, instead of decoding it first.

<details>
<summary>Test playbook...</summary>
<p>

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - stat:
        path: "./policies.zip"
        checksum_algorithm: sha256
      register: policies

    - debug:
        var: policies.stat.checksum

    - name: Upload zip file
      ansible.builtin.uri:
        method: POST
        url: "http://127.0.0.1:5000"
        body_format: form-multipart
        body:
          groups:
            filename: "./policies.zip"
          mime_type: application/octet-stream
        headers:
          Content-Type: multipart/form-data
      register: result

    - debug:
        var: result.json.files.groups.sha256

    - assert:
        that:
          - policies.stat.checksum == result.json.files.groups.sha256
```

</p>
</details>

<details>
<summary>Results...</summary>
<p>

```
No config file found; using defaults

PLAY [localhost] ***************************************************************

TASK [stat] ********************************************************************
ok: [localhost] => {"changed": false, "stat": {"atime": 1686674657.6710324, "attr_flags": "", "attributes": [], "birthtime": 1686674633.9050438, "block_size": 4096, "blocks": 8, "charset": "binary", "checksum": "e53f9a8e883e30412db31e60cf38fad351b1b03f13a61b9db0b91eb7bb49a95d", "ctime": 1686674646.3576086, "dev": 16777229, "device_type": 0, "executable": false, "exists": true, "flags": 0, "generation": 0, "gid": 20, "gr_name": "staff", "inode": 61011327, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "application/zip", "mode": "0644", "mtime": 1686674633.9054587, "nlink": 1, "path": "./policies.zip", "pw_name": "sivel", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 447, "uid": 501, "version": null, "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "policies.stat.checksum": "e53f9a8e883e30412db31e60cf38fad351b1b03f13a61b9db0b91eb7bb49a95d"
}

TASK [Upload zip file] *********************************************************
ok: [localhost] => {"changed": false, "connection": "close", "content_length": "431", "content_type": "application/json", "cookies": {}, "cookies_string": "", "date": "Tue, 13 Jun 2023 16:54:10 GMT", "elapsed": 0, "json": {"files": {"groups": {"filename": "policies.zip", "headers": {"Content-Disposition": "form-data; name=\"groups\"; filename=\"policies.zip\"", "Content-Transfer-Encoding": "base64", "Content-Type": "application/zip"}, "sha256": "e53f9a8e883e30412db31e60cf38fad351b1b03f13a61b9db0b91eb7bb49a95d"}}, "form": {"mime_type": "application/octet-stream"}}, "msg": "OK (431 bytes)", "redirected": false, "server": "Werkzeug/2.1.2 Python/3.10.5", "status": 200, "url": "http://127.0.0.1:5000"}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "result.json.files.groups.sha256": "e53f9a8e883e30412db31e60cf38fad351b1b03f13a61b9db0b91eb7bb49a95d"
}

TASK [assert] ******************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

</p>
</details>

The stdlib cpython libraries being used to generate the multipart/form-data body, only support ascii characters, and therefore must use base64 encoding for binary data.

needs_info
