### ISSUE TITLE
overarching `when` conditional should negate evaluating `loop` within block

### ISSUE THREAD

**Issue by hazelfire5** [ansible/ansible#81055]
### Summary

I would like to mention and bring up some behavior that just plain doesn't make sense to me. I have seen a few other folks create issues against this too:
https://github.com/ansible/ansible/issues/45976
https://github.com/ansible/ansible/issues/67310

the `when` conditional should negate the `loop` execution. From reading the links that have been attached to the other issues, if the reason is so that each item can be evaluated by the conditional, why not just put the conditional above the loop statement? why would the loop need to be evaluated even when its overarching conditional is False? or in my case, a null value? that doesn't really make sense to me. I placed my conditional using a block and even so the loop is still being evaluated while the first tasks are skipped as expected? How is this not a bug? as Will Ferrell said in zoolander, "I feel like I'm taking crazy pills" 🥴 or maybe i am just tired and missing something obvious.

### Issue Type

Bug Report

### Component Name

when, loop

### Ansible Version

```console
$ ansible --version

ansible [core 2.13.7]
  config file = None
  configured module search path = ['/Users/someone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/someone/Library/Python/3.8/lib/python/site-packages/ansible
  ansible collection location = /Users/someone/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.9 (default, May 17 2022, 12:55:41) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = False
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

Nothing comes up when i run this:
% ansible-config dump --only-changed -t all
test %
```

### OS / Environment

CentOS / MacOS / Ubuntu

### Steps to Reproduce

Interestingly enough, i followed the recommendation from the other issues such as:
 `loop: "{{ infra_setup.urls.distro.unsigned|default({})| dict2items}}"`
and 
`loop: "{{ infra_setup.urls.distro.unsigned|default({}) }}"` 
but i still get the same error. It seems like a bad idea to allow this to happen in the first place and i think not correcting this behavior is only prolonging the bug fix.
```yaml (paste below)
---
- name: check this stuff
  hosts: localhost
  gather_facts: false
  vars:
    infra_setup:
      urls:
        distro:
          signed:
            - url: "https://dist.scaleft.com/pki/scaleft_deb_key.asc"
              dest: "other/scaleft.asc"
              repo: "http://pkg.scaleft.com/deb linux main"
          unsigned:
   tasks:
        - name: tests - unsigned
          block:
            - name: tests - unsigned - 1
              ansible.builtin.debug:
                msg: "{{ infra_setup.urls.distro.unsigned }}"
            - name: tests - unsigned - 1
              ansible.builtin.debug:
                msg: "{{ infra_setup.urls.distro.unsigned is defined }}"
            - name: tests - unsigned - 2
              ansible.builtin.debug:
                msg: "{{ infra_setup.urls.distro.unsigned == None }}"
            - name: tests - unsigned - 3
              ansible.builtin.debug:
                msg: "{{ infra_setup.urls.distro.unsigned != None }}"
            - name: tests - unsigned - 4
              ansible.builtin.debug:
                msg: "{{ infra_setup.urls.distro.unsigned is defined and infra_setup.urls.distro.unsigned != None and infra_setup.urls.distro.unsigned | length > 0 }}"
            - name: tests - unsigned - 5
              ansible.builtin.debug:
                msg: "{{ item.repo }}"
              loop: "{{ infra_setup.urls.distro.unsigned }}"
          when: 
            - infra_setup.urls.distro.unsigned is defined 
            - infra_setup.urls.distro.unsigned != None
            - infra_setup.urls.distro.unsigned | length > 0
```

### Expected Results
```
TASK [tests - unsigned - 1] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 1] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 2] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 3] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 4] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 5] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]
```
### Actual Results

```console
The top tasks skipping makes complete sense but when executing 5, the behavior is abnormal.

TASK [tests - unsigned - 1] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 1] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 2] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 3] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 4] **********************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [tests - unsigned - 5] **********************************************************************************************************************************************************************************************************************
1. setting default and dict2items `(loop: "{{ infra_setup.urls.distro.unsigned|default({})| dict2items }}")`

fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ infra_setup.urls.distro.unsigned|default({})| dict2items }}): dict2items requires a dictionary, got <class 'NoneType'> instead."}

2. setting just default `(loop: "{{ infra_setup.urls.distro.unsigned|default({})}}")`

fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: . Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}

3. simplified `(loop: "{{ infra_setup.urls.distro.unsigned }}")`

fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: . Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by hazelfire5** [comment]
If anyone is reading this and needs a workaround that "just works" here is my solution. You must shove your task in another file. That way it never gets evaluated in the first place. 

**main.yaml**
```
---
- name: check this stuff
  hosts: localhost
  gather_facts: false
  vars:
    infra_setup:
      urls:
        distro:
          signed:
            - url: "https://dist.scaleft.com/pki/scaleft_deb_key.asc"
              dest: "other/scaleft.asc"
              repo: "http://pkg.scaleft.com/deb linux main"
          unsigned:

  tasks:
    - name: tests
      block:
        - name: tests - signed
          block:
            - name: import unsigned tasks
              include_tasks: unsigned.yaml
          when: 
            - infra_setup.urls.distro.unsigned is defined 
            - infra_setup.urls.distro.unsigned != None
            - infra_setup.urls.distro.unsigned | length > 0
```


**unsigned.yaml**
```
- name: tests - unsigned
  block:
    - name: tests - unsigned - 1
      ansible.builtin.debug:
        msg: "{{ infra_setup.urls.distro.unsigned is defined }}"
    - name: tests - unsigned - 2
      ansible.builtin.debug:
        msg: "{{ infra_setup.urls.distro.unsigned == None }}"
    - name: tests - unsigned - 3
      ansible.builtin.debug:
        msg: "{{ infra_setup.urls.distro.unsigned != None }}"
    - name: tests - unsigned - 4
      ansible.builtin.debug:
        msg: "{{ infra_setup.urls.distro.unsigned is defined and infra_setup.urls.distro.unsigned != None and infra_setup.urls.distro.unsigned | length > 0 }}"
    - name: tests - unsigned - 5
      ansible.builtin.debug:
        msg: "{{ item.repo }}"
      loop: "{{ infra_setup.urls.distro.unsigned }}"
```
Which to me seems unnecessary but will work.
```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [check this stuff] **************************************************************************************************************************************************************************************************************************

TASK [import unsigned tasks] *********************************************************************************************************************************************************************************************************************
skipping: [localhost]
```

**Comment by mkrizek** [comment]
> why would the loop need to be evaluated even when its overarching conditional is False?

Because the conditional can be evaluated differently per loop iteration, for example `when: item != foo`.

>  I placed my conditional using a block and even so the loop is still being evaluated

At the point of execution `block` does not exist. `block` is processed at parsing time, all its keywords are applied to tasks within the block, so:

```yaml
- block:
  - debug:
  - debug:
    loop:
      - item1
      - item2
  when: foo == bar
```
is converted into the following before the play is executed:
```yaml
- debug:
  when: foo == bar
- debug:
  loop:
    - item1
    - item2
  when: foo == bar
```
So `block` is (also) a mechanism for users to group common keywords for multiple tasks in one place.

The above is same for `import_tasks`. Whereas for `include_tasks`, as you have shown in your example, the `when` conditional (and other keywords) are applied to the `include_tasks` itself, as opposed to tasks within.

This is all by design and documented
* https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_blocks.html#grouping-tasks-with-blocks
* https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#standard-loops
* https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#loops-and-conditionals

**Comment by bcoca** [comment]
closin as per above

**Comment by carnite5** [comment]
i am sorry, i am struggling to understand this still and don't feel like this should be closed
```
- debug:
  when: foo == bar
- debug:
  loop:
    - item1
    - item2
  when: foo == bar
```
i get what you are saying on how the conditional itself works but why still evaluate the loop? Based on the example above, would item1,item2 still get printed through debug? 

But above all of this, how do you get my example to work in the first place? i tried using default but that doesn't work, it still fails as i have attached.

**Comment by hazelfire5** [comment]
sorry, i have 2 github accounts, carnite5 is also me.

**Comment by bcoca** [comment]
@carnite5 because we need the loop in case you use something from the loop in the conditional, since the `when` is PER LOOP ITERATION.  Most commonly you would think that we could just detect `item` in the `when` and skip it, but that does not cover all loop variables nor indirect usages of it. 

One example w/o using `item` that would force us to evaluate the conditional per loop iteration
```
- set_fact:
     bar: '{{[foo, other,yetanother]|random(item)}}'
  loop:
    - 1
    - 2
  when: foo == bar

```

**Comment by hazelfire5** [comment]
i think where we are misunderstanding each other the most is the location of the conditional since my `block` should be (in my opinion) an outer/overarching step/conditional. The fact that something within a conditional is still executed even when the conditional isn't met, doesn't make programmatic sense.

For example, Python's conditional (if statement):
```python
try:
    if foo:
        # foo is something so this conditional is met
        print('this line is printed')
        for i in foo:
            # this iterates because foo contains something we can iterate over and is not nothing
            print(i)
except:
    # foo is nothing/not defined
    print('there is no foo')
```  
We wouldn't be running/executing the `for i in foo` in any form when foo is not defined or is nothing. As i am trying to mention, this is not possible in Ansible unless you shove the task into another file which makes it cumbersome. 

My point for when evaluating an `item` against a conditional is for it to be located above the `when` conditional:
```yaml
  vars:
    foo: 4
    bar: 3
  tasks:
    - set_fact:
        debug: msg="{{ item }}"
      when: item == bar
      loop:
        - 1
        - 2
```
which outputs:
```
PLAY [check this stuff] **************************************************************************************************************************************************************************************************************************

TASK [set_fact] **********************************************************************************************************************************************************************************************************************************
skipping: [localhost] => (item=1) 
skipping: [localhost] => (item=2) 

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```
or in the case the conditional is met:
```yaml
  vars:
    foo: 1
    bar: 1
  tasks:
    - set_fact:
        debug: msg="{{ item }}"
      when: item == bar
      loop:
        - 1
        - 2
```
would output: 
```
PLAY [check this stuff] **************************************************************************************************************************************************************************************************************************

TASK [set_fact] **********************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=1)
skipping: [localhost] => (item=2) 

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

But no worries, i sorta expected this issue would be closed and I am just happy I gave a workaround for others who stumble across this limitation. The other issues were closed and i couldn't add my workaround as the comment section is seemingly closed.
