### ISSUE TITLE
Ansible win_package stuck forever

### ISSUE THREAD

**Issue by akdasari** [ansible/ansible#81086]
### Summary

I'm trying to install jre exe file using win_package and it stuck forever. This was working previously
my env is :  on rhel ec2 instance I have created  virtualenv with  ansible 3.0.0

Can somebody help me please...

_While running playbook this is the logs I see_ 

TASK [../roles/jre : install jre] ***************************************************************************************************************************************************
task path: /home/xxxxxx/environment/scip-config/roles/jre/tasks/main.yml:10
redirecting (type: modules) ansible.builtin.win_package to ansible.windows.win_package
Using module file /home/xxxxxxx/environment/vpy36/local/lib/python3.6/dist-packages/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
Pipelining is enabled.
<10.0.xxx.xxx> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 10.0.xxx.xxx
<10.0.xxx.xxx> WINRM CONNECT: transport=ssl endpoint=https://10.0.xxx.xxx:5986/wsman
<10.0.xxx.xxx> WINRM OPEN SHELL: 355F89A2-6100-4551-AC24-759B66EA40C3
EXEC (via pipeline wrapper)
<10.0.xxx.xxx> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBhAFEAQgBtAEEAQwBBAEEASwBBAEEAawBBAEYAQQBBAFUAdwBCAFcAQQBHAFUAQQBjAGcAQ

this just stops here and don't see any mode debug info.

### Issue Type

Bug Report

### Component Name

win_package

### Ansible Version

```console
$ ansible --version
/home/xxxxxx/environment/vpy36/local/lib/python3.6/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.exceptions import InvalidSignature
ansible 2.10.17
  config file = /home/ec2-user/environment/scip-config/test_jump/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/environment/vpy36/local/lib/python3.6/dist-packages/ansible
  executable location = /home/ec2-user/environment/vpy36/bin/ansible
  python version = 3.6.12 (default, Nov  2 2022, 07:14:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
environment/vpy36/local/lib/python3.6/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.exceptions import InvalidSignature
DEFAULT_HOST_LIST(/home/ec2-user/environment/scip-config/test_jump/ansible.cfg) = ['/home/ec2-user/environment/scip-config/test_jump/inventory']
DEFAULT_STDOUT_CALLBACK(/home/ec2-user/environment/scip-config/test_jump/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/ec2-user/environment/scip-config/test_jump/ansible.cfg) = False
```

### OS / Environment

Amazon Linux

### Steps to Reproduce

```yaml (paste below)
**ansible.cfg**
[defaults]
become = true
gather_facts = true
host_key_checking = false
inventory = inventory
stdout_callback = yaml


**inventory**
[testvm]
10.0.xxx.xxx

[testvm:vars]
ansible_connection=winrm
ansible_user=administrator
ansible_password="xxxxxxxxxxxxxxxxxxxxxx"
ansible_winrm_server_cert_validation=ignore

test.yml
- name: install 
  hosts: "testvm"
  roles:
    - ../roles/jre

role/jre/tasks/main.yml
- name: install jre
  win_package:
    path: 'C:\Downloads\jre-8u202\jre-8u202-windows-i586.exe'
    product_id: auto
    state: present
    arguments:
    - /install
    - /passive
    - /quite
    - /norestart
    log_path: 'C:\Downloads\jre_install.log'
  register: getresult
- debug: 
    msg="{{ getresult.msg }}" 
  when: getresult.changed
```

### Expected Results

expected to install jre, but hangs...

### Actual Results

```console
TASK [../roles/jre : install jre] ***************************************************************************************************************************************************
task path: /home/ec2-user/environment/scip-config/roles/jre/tasks/main.yml:10
redirecting (type: modules) ansible.builtin.win_package to ansible.windows.win_package
Using module file /home/ec2-user/environment/vpy36/local/lib/python3.6/dist-packages/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
Pipelining is enabled.
<10.0.xxx.xxx> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 10.0.xxx.xxx
EXEC (via pipeline wrapper)
```

### Code of Conduct

- [ ] I agree to follow the Ansible Code of Conduct
