### ISSUE TITLE
ansible.builtin.copy has unexpected behaviour when copying recursively with remote_src: true

### ISSUE THREAD

**Issue by simon-frankau** [ansible/ansible#81126]
### Summary

*When I copy some files recursively around the remote file system, I want the behaviour to match the documentation, and give me control over file modes.*

In the following, I'm specifically talking about the case where `remote_src: true`, and none of the destination files exist yet.

When copying single files, ansible.builtin.copy sets file permissions based on the `mode` that has been set in the config, which may in turn use the default umask. The source mode is ignored, unless `mode: preserve` is set. This gives plenty of control to the ansible script.

When copying files recursively, I would expect the behaviour to be the same, with the exception that directories would take their permissions from `directory_mode` instead of `directory`. As far as I can tell, this is what the [documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html) suggests should happen.

What happens in practice is that the permissions of the source files are always copied, with the exception of enclosing directories: The root directory, if copied (no trailing slash on source) seems to get the system default if the destination has no trailing slash, and `mode` otherwise. `mode` seems to be used for creating enclosing directories, unless the source has no trailing slash and the destination has a trailing slash, in which case `directory_mode` is used.

This doesn't seem to match the documentation, or have an obvious logic to it. It also means I can't set the file permissions to a desired value from my ansible script during the copy, unlike with single files.

My suggestion is that the documentation just explicitly say that for local recursive copies permissions are preserved, and tidy up how modes are set on the enclosing directories that are created (use `directory_mode`?), and generally improve the documentation around this area.

### Issue Type

Bug Report

### Component Name

ansible.builtin.copy

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/Users/sgf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/sgf/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.4 (main, Jun 15 2023, 07:52:47) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/Cellar/ansible/8.0.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = emacs
PAGER(env: PAGER) = less
```

### OS / Environment

Host:
```
$ uname -a
Darwin wellington.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64
```

Target is a vagrant-based VM: 
```
uname -a
Linux controller 5.10.0-22-cloud-arm64 #1 SMP Debian 5.10.178-3 (2023-04-22) aarch64 GNU/Linux
```

### Steps to Reproduce

```yaml
---
- name: Local directory copy test
  hosts: controller
  tasks:
    - ansible.builtin.command: "mkdir -p /tmp/test/subdir"
    - ansible.builtin.command: "touch /tmp/test/a"
    - ansible.builtin.command: "touch /tmp/test/subdir/b"
    - ansible.builtin.command: "chmod u=r,g=w,o= /tmp/test/a"
    - ansible.builtin.command: "chmod u=rx,g=wx,o=x /tmp/test/subdir/b"
    - ansible.builtin.command: "chmod u=rx,g=r,o=x /tmp/test/subdir"
    - ansible.builtin.command: "chmod u=rx,g=x,o=w /tmp/test"
    - name: Copy files 1/4
      ansible.builtin.copy:
        src: /tmp/test
        dest: /tmp/no_trailing_to_no_trailing
        remote_src: true
        mode: u=rw,g=,o=r
        directory_mode: u=rwx,g=rx,o=x
    - name: Copy files 2/4
      ansible.builtin.copy:
        src: /tmp/test/
        dest: /tmp/trailing_to_no_trailing
        remote_src: true
        mode: u=rw,g=,o=r
        directory_mode: u=rwx,g=rx,o=x
    - name: Copy files 3/4
      ansible.builtin.copy:
        src: /tmp/test
        dest: /tmp/no_trailing_to_trailing/
        remote_src: true
        mode: u=rw,g=,o=r
        directory_mode: u=rwx,g=rx,o=x
    - name: Copy files 4/4
      ansible.builtin.copy:
        src: /tmp/test/
        dest: /tmp/trailing_to_trailing/
        remote_src: true
        mode: u=rw,g=,o=r
        directory_mode: u=rwx,g=rx,o=x
```

### Expected Results

My expectations, based on the documentation, was that all files that the result of the copy would have file permissions based on the `mode` set in the ansible script, and all directories would have their permissions based on `directory_mode`.

### Actual Results

```console
vagrant@controller:/tmp$ sudo ls -lR | grep -v total
.:
drw----r-- 3 vagrant vagrant 4096 Jun 26 14:18 no_trailing_to_no_trailing
drwxr-x--x 3 vagrant vagrant 4096 Jun 26 14:18 no_trailing_to_trailing
dr-x--x-w- 3 vagrant vagrant 4096 Jun 26 14:18 test
drw----r-- 3 vagrant vagrant 4096 Jun 26 14:18 trailing_to_no_trailing
drw----r-- 3 vagrant vagrant 4096 Jun 26 14:18 trailing_to_trailing

./no_trailing_to_no_trailing:
drwxr-xr-x 3 vagrant vagrant 4096 Jun 26 14:18 test

./no_trailing_to_no_trailing/test:
-r---w---- 1 vagrant vagrant    0 Jun 26 14:18 a
dr-xr----x 2 vagrant vagrant 4096 Jun 26 14:18 subdir

./no_trailing_to_no_trailing/test/subdir:
-r-x-wx--x 1 vagrant vagrant 0 Jun 26 14:18 b

./no_trailing_to_trailing:
drw----r-- 3 vagrant vagrant 4096 Jun 26 14:18 test

./no_trailing_to_trailing/test:
-r---w---- 1 vagrant vagrant    0 Jun 26 14:18 a
dr-xr----x 2 vagrant vagrant 4096 Jun 26 14:18 subdir

./no_trailing_to_trailing/test/subdir:
-r-x-wx--x 1 vagrant vagrant 0 Jun 26 14:18 b

./test:
-r---w---- 1 vagrant vagrant    0 Jun 26 14:18 a
dr-xr----x 2 vagrant vagrant 4096 Jun 26 14:18 subdir

./test/subdir:
-r-x-wx--x 1 vagrant vagrant 0 Jun 26 14:18 b

./trailing_to_no_trailing:
-r---w---- 1 vagrant vagrant    0 Jun 26 14:18 a
dr-xr----x 2 vagrant vagrant 4096 Jun 26 14:18 subdir

./trailing_to_no_trailing/subdir:
-r-x-wx--x 1 vagrant vagrant 0 Jun 26 14:18 b

./trailing_to_trailing:
-r---w---- 1 vagrant vagrant    0 Jun 26 14:18 a
dr-xr----x 2 vagrant vagrant 4096 Jun 26 14:18 subdir

./trailing_to_trailing/subdir:
-r-x-wx--x 1 vagrant vagrant 0 Jun 26 14:18 b
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
