### ISSUE TITLE
Allow reload of collection during play

### ISSUE THREAD

**Issue by larkoie** [ansible/ansible#81153]
### Summary

From what I understood, the collections are loaded at the beginning of a playbook run and can't be reloaded (or refreshed like the inventory for exemple) during the play.

We ran into the case where we wanted to have a single playbook that would both install the collections and run collection playbooks/roles. We wanted to ease the process by having an umbrella playbook and not having to first run a playbook that would set the environment (install collections) and then run a second playbook that would use the collection roles.

This "umbrella" playbook would:

1. run a pre_task to install collections with '**community.general.ansible_galaxy_install**' module
2. run tasks '**include_role**' to include collection roles that were installed in step 1

```yaml 
---
- name: Install galaxy and import PDP playbook
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Install collection(s)
      community.general.ansible_galaxy_install:
        type: collection
        requirements_file: requirements.yml
        dest: "{{ playbook_dir }}/collections"

  tasks:
    #will not work because collection role was not installed at the beginning of the play
    - name: Include role from collection
      ansible.builtin.include_role:
        name: my_namespace.my_collection.my_role
```

 

It does not work because Ansible will not find the collection role(s) that were installed in the same play as collections are loaded  at the very begining of the playbook and never refreshed during the play.

The workaround is to first run the "install_collection.yml" playbook and then independently run "run_collection_roles.yml" playbook (we can't use "playbook_import" to embed the second playbook because the imported playbook still runs in the root playbook context and does not reload collections either).

There is the module '**ansible.builtin.meta**' that has a '**refresh_inventory**' to reload the inventory during the run, we could for example imagine an option '**refresh_collections**' the same way?

### Issue Type

Feature Idea

### Component Name

collection

### Additional Information

```yaml (paste below)
---
- name: Install galaxy and import PDP playbook
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Install collection(s)
      community.general.ansible_galaxy_install:
        type: collection
        requirements_file: requirements.yml
        dest: "{{ playbook_dir }}/collections"
    - name: refresh collection
      ansible.builtin.meta: refresh_collections
  

  tasks:
    - name: Include role from collection
      ansible.builtin.include_role:
        name: my_namespace.my_collection.my_role
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
