### ISSUE TITLE
Ansible used for CI systems

### ISSUE THREAD

**Issue by TheKushIsGood** [ansible/ansible#81162]
### Summary

Using Ansible for host verification. 

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

```yaml (paste below)
---
 
- name: slurp
  hosts: all
  tasks:
  - name: "get data" #contains "some data" 
    slurp:
      src: "/tmp/hello"
    register: data
 
  - name: "check content of hello"
    assert:
      that:
        - " '/foo' in data['content'] | b64decode"
        - " 'hn1' in data['content'] | b64decode"
```

We use the JUNIT module for CI integration. 
We would like to check both assertions. If one assertion fails, it should not stop everything. Instead it should continue as there are more test.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
