### ISSUE TITLE
install suggested packages with apt module

### ISSUE THREAD

**Issue by rmbleeker** [ansible/ansible#81173]
### Summary

The ansible.builtin.apt module has an option to install recommended packages with install_recommends, overriding the system default. I think it would be useful to add an install_suggests option to enable installing suggested packages in the same manner. Package suggestions are often documentation or optional libraries or helper programs that can be useful to users of the Ansible managed system.

### Issue Type

Feature Idea

### Component Name

apt

### Additional Information

```yaml (paste below)
- name: Install apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    install_suggests: yes
```
The above example would install `apache2-doc` and `apache2-suexec-pristine` alongside `apache2` on a Debian 12 system.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
