### ISSUE TITLE
Composer module fails to work correctly on OSX

### ISSUE THREAD

**Issue by cjunge-work** [ansible/ansible#8117]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.6
##### Environment:

OSX
##### Summary:

Output from composer module is not correct. Composer has been installed using Homebrew, but the composer module doesn't seem to run correctly.

Same settings work fine on Linux.
##### Steps To Reproduce:

Run this task:

```
    -   name: Composer install
        environment: symfony_environment
        tags: [ "composer" ]
        composer:
            working_dir: "{{ composer_dir }}"
            optimize_autoloader: yes
            prefer_dist: yes
            no_dev: "{{ composer_no_dev }}"
```

{{ composer_dir }} is where the composer.json file is.
##### Expected Results:

Standard composer output from running composer install.
##### Actual Results:

```
TASK: [Composer install] *******************************************
<localhost> REMOTE_MODULE composer no_dev=False working_dir=/tmp/deploy
<localhost>
 EXEC ['/bin/sh', '-c', 'mkdir -p
$HOME/.ansible/tmp/ansible-tmp-1404425204.93-218640203058643 &&
chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1404425204.93-218640203058643
&& echo
$HOME/.ansible/tmp/ansible-tmp-1404425204.93-218640203058643']
<localhost>
 PUT /var/folders/fx/51cy7j4978xdtx6b4ck5jcl00000gp/T/tmpwxXuuC TO
/Users/markc/.ansible/tmp/ansible-tmp-1404425204.93-218640203058643/composer
<localhost>
 EXEC ['/bin/sh', '-c', u'LC_CTYPE=en_US.UTF-8 SYMFONY_ENV=dev
LANG=en_US.UTF-8 /usr/bin/python
/Users/markc/.ansible/tmp/ansible-tmp-1404425204.93-218640203058643/composer;
 rm -rf
/Users/markc/.ansible/tmp/ansible-tmp-1404425204.93-218640203058643/
>/dev/null 2>&1']
ok:
[localhost] => {"changed": false, "msg": "/usr/bin/env php -d
allow_url_fopen=On -d detect_unicode=Off
/usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar $*"}
```
