### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED with url_get and unarchive

### ISSUE THREAD

**Issue by naisanzaa** [ansible/ansible#81170]
### Summary

```
TASK [download] ******************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  dest: chromedriver_mac_arm64.zip
  elapsed: 0
  msg: 'Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>'
  url: https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac_arm64.zip

```

### Issue Type

Bug Report

### Component Name

get_url, unarchive

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.1]
  config file = /home/eric/werk/lab/github/antsable/ansible.cfg
  configured module search path = ['/Users/eric/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/eric/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.11/bin/ansible
  python version = 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] (/Library/Frameworks/Python.framework/Versions/3.11/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Mac OS X 14.0 Beta (23A5276g)

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  connection: local
  tasks:

    - set_fact:
        version: 114.0.5735.90

    # use Google Chrome Stable to match driver
    - name: Download linux {{ version }}
      unarchive:
        src: https://chromedriver.storage.googleapis.com/{{ version }}/chromedriver_linux64.zip
        dest: /tmp
        remote_src: yes
      when: ansible_facts.distribution == "Linux"

    - name: download
      get_url:
        url: https://chromedriver.storage.googleapis.com/{{ version }}/chromedriver_mac_arm64.zip
        dest: chromedriver_mac_arm64.zip

    - name: Download mac m1 {{ version }}
      unarchive:
        src: https://chromedriver.storage.googleapis.com/{{ version }}/chromedriver_mac_arm64.zip
        dest: /tmp
        remote_src: yes
      when: ansible_facts.distribution == "MacOSX" and ansible_facts.processor == "Apple M1"

    - name: Download windows {{ version }}
      unarchive:
        src: https://chromedriver.storage.googleapis.com/{{ version }}/chromedriver_win32.zip
        dest: /tmp
        remote_src: yes
      when: ansible_facts.distribution == "Windows"

    - name: Install chromedriver {{ version }}
      copy:
        src: /tmp/chromedriver
        dest: /usr/local/bin/chromedriver
        remote_src: yes
        mode: 0755
      become: yes

```

### Expected Results

Download. 

### Actual Results

```console
PLAY [localhost] *****************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
ok: [localhost]

TASK [set_fact] ******************************************************************************************************************************************************************************************
ok: [localhost] => changed=false 
  ansible_facts:
    version: 114.0.5735.90

TASK [Download linux 114.0.5735.90] **********************************************************************************************************************************************************************
skipping: [localhost] => changed=false 
  false_condition: ansible_facts.distribution == "Linux"
  skip_reason: Conditional result was False

TASK [download] ******************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  dest: chromedriver_mac_arm64.zip
  elapsed: 0
  msg: 'Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>'
  url: https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac_arm64.zip


PLAY RECAP ***********************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
