### ISSUE TITLE
Cannot pass omit variables to include_tasks apply delegate_to

### ISSUE THREAD

**Issue by xiaoyao9184** [ansible/ansible#81174]
### Summary

When passed to the `include_tasks` task `apply` parameter `delegate_to` by setting the omit variable, the variable was not parsed correctly.

### Issue Type

Bug Report

### Component Name

include_tasks

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/xy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']     
  ansible python module location = /home/xy/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/xy/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xy/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

WSL debian 11

### Steps to Reproduce

```yaml

- name: test
  vars:
    run_debug: |
      ansible-playbook \
        -vvv \
        --inventory $PWD/ansible-inventories \
        $PWD/../../../test/seed/include_tasks.delegate_to/ansible-playbook.test.yml
    run_normal: |
      ansible-playbook \
        --inventory $PWD/ansible-inventories \
        $PWD/../../../test/seed/include_tasks.delegate_to/ansible-playbook.test.yml
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ env_path | default('') }}"
  hosts: docker
  run_once: true
  tasks:

    - name: omit fact
      vars:
        host_delegate_to: "{{ omit }}"
        host_run_once: "{{ omit }}"
      ansible.builtin.set_fact:
        _test:
          delegate_to: "{{ host_delegate_to }}"
          run_once: "{{ host_run_once }}"
        _default:
          delegate_to: node2
          run_once: false

    - name: ansible-tasks.test
      include_tasks:
        file: ansible-tasks.test.yml
        apply:
          delegate_to: "{{ _default.delegate_to | default(omit) }}"
          run_once: "{{ _default.run_once | default(false) }}"

    - name: ansible-tasks.test
      include_tasks:
        file: ansible-tasks.test.yml
        apply:
          delegate_to: "{{ _test.delegate_to | default(omit) }}"
          run_once: "{{ _test.run_once | default(false) }}"

```
ansible-tasks.test.yml
```yaml
---

- name: stat path
  ansible.builtin.stat:
    path: "/home"
  register: device_stat
  ignore_errors: true
```

inventory.yml
```yaml
all:
  hosts:
    node1:
      ansible_host: localhost
      ansible_connection: local
    node2:
      ansible_host: localhost
      ansible_connection: local
    node3:
      ansible_host: localhost
      ansible_connection: local
    node4:
      ansible_host: localhost
      ansible_connection: local

  children:
    docker:
      hosts:
        node1:
        node2:
        node3:
        node4:

    docker-manager:
      hosts:
        node1:

```

### Expected Results

Expected to indicate unset when passing omit variable to include_tasks apply delegate_to, 
but in this example the template is not parsed see `node1 -> {{ _test.delegate_to | default(omit) }}`

### Actual Results

```console
ansible-playbook [core 2.14.4]
  config file = None
  configured module search path = ['/home/xy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xy/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/xy/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xy/.local/bin/ansible-playbook
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /mnt/e/code/homelab-workspace/.config/test@local/test@docker/ansible-inventories/inventory.yml as it did not pass its verify_file() method
script declined parsing /mnt/e/code/homelab-workspace/.config/test@local/test@docker/ansible-inventories/inventory.yml as it did not pass its verify_file() method
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Parsed /mnt/e/code/homelab-workspace/.config/test@local/test@docker/ansible-inventories/inventory.yml inventory source with yaml plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: ansible-playbook.test.yml ******************************************************************************
1 plays in /mnt/e/code/homelab-workspace/.config/test@local/test@docker/../../../test/seed/include_tasks.delegate_to/ansible-playbook.test.yml

PLAY [test] ******************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************
task path: /mnt/e/code/homelab-workspace/test/seed/include_tasks.delegate_to/ansible-playbook.test.yml:3
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: xy
<localhost> EXEC /bin/sh -c 'echo ~xy && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xy/.ansible/tmp `"&& mkdir "` echo /home/xy/.ansible/tmp/ansible-tmp-1688543826.545673-16072-80509040268017 `" && echo ansible-tmp-1688543826.545673-16072-80509040268017="` echo /home/xy/.ansible/tmp/ansible-tmp-1688543826.545673-16072-80509040268017 `" ) && sleep 0'
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: xy
<localhost> EXEC /bin/sh -c 'echo ~xy && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xy/.ansible/tmp `"&& mkdir "` echo /home/xy/.ansible/tmp/ansible-tmp-1688543826.8771214-16086-211556745859043 `" && echo ansible-tmp-1688543826.8771214-16086-211556745859043="` echo /home/xy/.ansible/tmp/ansible-tmp-1688543826.8771214-16086-211556745859043 `" ) && sleep 0'   
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: xy
<localhost> EXEC /bin/sh -c 'echo ~xy && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xy/.ansible/tmp `"&& mkdir "` echo /home/xy/.ansible/tmp/ansible-tmp-1688543827.0624278-16100-17427431175809 `" && echo ansible-tmp-1688543827.0624278-16100-17427431175809="` echo /home/xy/.ansible/tmp/ansible-tmp-1688543827.0624278-16100-17427431175809 `" ) && sleep 0'      
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: xy
<localhost> EXEC /bin/sh -c 'echo ~xy && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xy/.ansible/tmp `"&& mkdir "` echo /home/xy/.ansible/tmp/ansible-tmp-1688543827.2619014-16114-44693419762785 `" && echo ansible-tmp-1688543827.2619014-16114-44693419762785="` echo /home/xy/.ansible/tmp/ansible-tmp-1688543827.2619014-16114-44693419762785 `" ) && sleep 0'      
<node2> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<node4> Attempting python interpreter discovery
<node3> Attempting python interpreter discovery
<node1> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.9 && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.9 && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.9 && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.9 && sleep 0'
Using module file /home/xy/.local/lib/python3.9/site-packages/ansible/modules/setup.py
<localhost> PUT /home/xy/.ansible/tmp/ansible-local-16068_ng_jlh6/tmpqznj28p0 TO /home/xy/.ansible/tmp/ansible-tmp-1688543826.545673-16072-80509040268017/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/xy/.ansible/tmp/ansible-tmp-1688543826.545673-16072-80509040268017/ /home/xy/.ansible/tmp/ansible-tmp-1688543826.545673-16072-80509040268017/AnsiballZ_setup.py && sleep 0'
Using module file /home/xy/.local/lib/python3.9/site-packages/ansible/modules/setup.py
Using module file /home/xy/.local/lib/python3.9/site-packages/ansible/modules/setup.py
Using module file /home/xy/.local/lib/python3.9/site-packages/ansible/modules/setup.py
<localhost> PUT /home/xy/.ansible/tmp/ansible-local-16068_ng_jlh6/tmph4_w4etn TO /home/xy/.ansible/tmp/ansible-tmp-1688543826.8771214-16086-211556745859043/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/xy/.ansible/tmp/ansible-tmp-1688543826.8771214-16086-211556745859043/ /home/xy/.ansible/tmp/ansible-tmp-1688543826.8771214-16086-211556745859043/AnsiballZ_setup.py && sleep 0'        
<localhost> PUT /home/xy/.ansible/tmp/ansible-local-16068_ng_jlh6/tmpk2oa03lu TO /home/xy/.ansible/tmp/ansible-tmp-1688543827.0624278-16100-17427431175809/AnsiballZ_setup.py
<localhost> PUT /home/xy/.ansible/tmp/ansible-local-16068_ng_jlh6/tmpw79msth1 TO /home/xy/.ansible/tmp/ansible-tmp-1688543827.2619014-16114-44693419762785/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/xy/.ansible/tmp/ansible-tmp-1688543827.0624278-16100-17427431175809/ /home/xy/.ansible/tmp/ansible-tmp-1688543827.0624278-16100-17427431175809/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'chmod u+x /home/xy/.ansible/tmp/ansible-tmp-1688543827.2619014-16114-44693419762785/ /home/xy/.ansible/tmp/ansible-tmp-1688543827.2619014-16114-44693419762785/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/xy/.ansible/tmp/ansible-tmp-1688543826.545673-16072-80509040268017/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/xy/.ansible/tmp/ansible-tmp-1688543826.8771214-16086-211556745859043/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/xy/.ansible/tmp/ansible-tmp-1688543827.2619014-16114-44693419762785/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/xy/.ansible/tmp/ansible-tmp-1688543827.0624278-16100-17427431175809/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/xy/.ansible/tmp/ansible-tmp-1688543826.545673-16072-80509040268017/ > /dev/null 2>&1 && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/xy/.ansible/tmp/ansible-tmp-1688543827.0624278-16100-17427431175809/ > /dev/null 2>&1 && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/xy/.ansible/tmp/ansible-tmp-1688543826.8771214-16086-211556745859043/ > /dev/null 2>&1 && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/xy/.ansible/tmp/ansible-tmp-1688543827.2619014-16114-44693419762785/ > /dev/null 2>&1 && sleep 0'
ok: [node3]
ok: [node1]
ok: [node2]
ok: [node4]

TASK [omit fact] *************************************************************************************************
task path: /mnt/e/code/homelab-workspace/test/seed/include_tasks.delegate_to/ansible-playbook.test.yml:20
ok: [node1] => {
    "ansible_facts": {
        "_default": {
            "delegate_to": "node2",
            "run_once": false
        },
        "_test": {}
    },
    "changed": false
}

TASK [ansible-tasks.test] ****************************************************************************************
task path: /mnt/e/code/homelab-workspace/test/seed/include_tasks.delegate_to/ansible-playbook.test.yml:32
included: /mnt/e/code/homelab-workspace/test/seed/include_tasks.delegate_to/ansible-tasks.test.yml for node1

TASK [stat path] *************************************************************************************************
task path: /mnt/e/code/homelab-workspace/test/seed/include_tasks.delegate_to/ansible-tasks.test.yml:3
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: xy
<localhost> EXEC /bin/sh -c 'echo ~xy && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xy/.ansible/tmp `"&& mkdir "` echo /home/xy/.ansible/tmp/ansible-tmp-1688543830.1501763-16424-22595239798190 `" && echo ansible-tmp-1688543830.1501763-16424-22595239798190="` echo /home/xy/.ansible/tmp/ansible-tmp-1688543830.1501763-16424-22595239798190 `" ) && sleep 0'      
Using module file /home/xy/.local/lib/python3.9/site-packages/ansible/modules/stat.py
<localhost> PUT /home/xy/.ansible/tmp/ansible-local-16068_ng_jlh6/tmp2atrdz8x TO /home/xy/.ansible/tmp/ansible-tmp-1688543830.1501763-16424-22595239798190/AnsiballZ_stat.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/xy/.ansible/tmp/ansible-tmp-1688543830.1501763-16424-22595239798190/ /home/xy/.ansible/tmp/ansible-tmp-1688543830.1501763-16424-22595239798190/AnsiballZ_stat.py && sleep 0'
<localhost> EXEC /bin/sh -c 'PATH=/home/xy/.local/bin:/home/xy/git-subrepo/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib: /usr/bin/python3 /home/xy/.ansible/tmp/ansible-tmp-1688543830.1501763-16424-22595239798190/AnsiballZ_stat.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/xy/.ansible/tmp/ansible-tmp-1688543830.1501763-16424-22595239798190/ > /dev/null 2>&1 && sleep 0'
ok: [node1 -> node2(localhost)] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "checksum_algorithm": "sha1",
            "follow": false,
            "get_attributes": true,
            "get_checksum": true,
            "get_md5": false,
            "get_mime": true,
            "path": "/home"
        }
    },
    "stat": {
        "atime": 1686551634.7115216,
        "attr_flags": "e",
        "attributes": [
            "extents"
        ],
        "block_size": 4096,
        "blocks": 8,
        "charset": "binary",
        "ctime": 1682063915.636811,
        "dev": 2080,
        "device_type": 0,
        "executable": true,
        "exists": true,
        "gid": 0,
        "gr_name": "root",
        "inode": 16386,
        "isblk": false,
        "ischr": false,
        "isdir": true,
        "isfifo": false,
        "isgid": false,
        "islnk": false,
        "isreg": false,
        "issock": false,
        "isuid": false,
        "mimetype": "inode/directory",
        "mode": "0755",
        "mtime": 1682063915.636811,
        "nlink": 3,
        "path": "/home",
        "pw_name": "root",
        "readable": true,
        "rgrp": true,
        "roth": true,
        "rusr": true,
        "size": 4096,
        "uid": 0,
        "version": "1487222603",
        "wgrp": false,
        "woth": false,
        "writeable": false,
        "wusr": true,
        "xgrp": true,
        "xoth": true,
        "xusr": true
    }
}

TASK [ansible-tasks.test] ****************************************************************************************
task path: /mnt/e/code/homelab-workspace/test/seed/include_tasks.delegate_to/ansible-playbook.test.yml:44
included: /mnt/e/code/homelab-workspace/test/seed/include_tasks.delegate_to/ansible-tasks.test.yml for node1

TASK [stat path] *************************************************************************************************
task path: /mnt/e/code/homelab-workspace/test/seed/include_tasks.delegate_to/ansible-tasks.test.yml:3
<inventory_hostname> ESTABLISH SSH CONNECTION FOR USER: None
<inventory_hostname> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/xy/.ansible/cp/42ef6ae34b"' inventory_hostname '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<inventory_hostname> (255, b'', b'ssh: Could not resolve hostname inventory_hostname: Name or service not known\r\n')
fatal: [node1 -> {{ _test.delegate_to | default(omit) }}]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname inventory_hostname: Name or service not known",
    "unreachable": true
}

PLAY RECAP *******************************************************************************************************
node1                      : ok=5    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

node2                      : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

node3                      : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

node4                      : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
