### ISSUE TITLE
User module doesn't update uid/gid on Alpine

### ISSUE THREAD

**Issue by vaygr** [ansible/ansible#81186]
### Summary

Ansible doesn't update user uid/gid on Alpine.

May be related: #61911

### Issue Type

Bug Report

### Component Name

user

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0]
  ...
  executable location = /usr/bin/ansible
  python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

N/A
```

### OS / Environment

Manjaro 23.0.0pre-1

### Steps to Reproduce

Create a user with uid=1000, gid=1000.
Create a group `admin` with gid=8000.

```yaml (paste below)
- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: johnd
    comment: John Doe
    uid: 8000
    group: admin
```

### Expected Results

The user changed its uid/gid.

### Actual Results

```console
The user remained unchanged.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
