### ISSUE TITLE
Ansible should provide a way to define custom data Types

### ISSUE THREAD

**Issue by dangoncalves** [ansible/ansible#81201]
### Summary

Currently, Ansible defines `!unsafe` and `!vault` data types in the yaml parsing python module ([here](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/yaml/constructor.py#L170) and [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/yaml/constructor.py#L174)) .

As far as I understand, there is no way to provide custom data type in collections. Such feature could be useful, so that we could define a more general type for sensitive data that could be defined in third party collections (like [hashi_vault](https://github.com/ansible-collections/community.hashi_vault)) and stdout callback plugins could know that this is sensitive data and not display them like it's currently done with Ansible vault.

### Issue Type

Feature Idea

### Component Name

parsing.yaml

### Additional Information

```yaml
---
name: Custom data type
hosts: all
vars:
    my_var: "{{ lookup('hashi_vault','secret=secret/data/path/to/my namespace=my-namespace').secret }}"

  tasks:
    - name: Debug secret
      debug:
        var: my_var
```

Should display
```
PLAY [Debug Extra vars] ********************************************************
TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]
TASK [Debug organization_name] *************************************************
ok: [127.0.0.1] => {
    "my_var": "!community.hashi_vault.sensitive-data 'Anything that is defined in the collection\'s parser'"
}
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
