### ISSUE TITLE
enable mutually_exclusive for modules on suboptions

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible#81214]
### Summary

This is a follow up of Issue https://github.com/ansible-collections/azure/pull/1206 in the azure ansible collection.

During this update of the module I noticed that mutually_exclusive only seems to work on the first level options.

Example from that module:
```
- name: Change VM to use Managed Bootdiagnostics
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ _client_secret }}"
    tenant: "{{ tenant }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{ resourceGroup }}"
    name: VM1
    boot_diagnostics:
      enabled: true
      type: managed
      #storage_account: name_of_storage_account  # if I do not set type
```

Now I could make client_id and name mutually_exclusive by setting it in the module
https://github.com/ansible-collections/azure/blob/8409f877aba784a42428d320409873632389444d/plugins/modules/azure_rm_virtualmachine.py#L1125

But I can not make boot_diagnostics.type mutually_exclusive with boot_diagnostics.storage_account which would be what I want to achieve.

### Issue Type

Feature Idea

### Component Name

ansible-core
lib/ansible/module_utils/common/arg_spec.py
lib/ansible/module_utils/common/validation.py

### Additional Information

```yaml (paste below)
- name: Change VM to use Managed Bootdiagnostics
  azure_rm_virtualmachine:
    client_id: "{{ client_id }}"
    secret: "{{ _client_secret }}"
    tenant: "{{ tenant }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{ resourceGroup }}"
    name: VM1
    boot_diagnostics:
      enabled: true
      type: managed
      storage_account: name_of_storage_account  # if I do not set type
```

This should throw an error by using the mutually_exclusive function ansible provides for modules.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/module_utils/common/arg_spec.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/arg_spec.py)
* [`lib/ansible/module_utils/common/validation.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/validation.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
It's not clear to me why you think this won't work?

```python
from ansible.module_utils.basic import AnsibleModule

def main():
    argspec = dict(
        foo=dict(
            type='dict',
            options=dict(
                mint=dict(type='str'),
                orange=dict(type='str'),
            ),
            mutually_exclusive=[['mint', 'orange']],
        )
    )

    module = AnsibleModule(
        argument_spec=argspec,
    )

    module.exit_json(changed=True)


if __name__ == '__main__':
    main()
```

```yaml
- hosts: localhost
  tasks:
    - flowerysong.test.args:
        foo:
          orange: juice
          mint: toothpaste
```

```
PLAY [localhost] *********************************************************************

TASK [flowerysong.test.args] *********************************************************
fatal: [localhost]: FAILED! =>
    changed: false
    msg: 'parameters are mutually exclusive: mint|orange found in foo'
```
