### ISSUE TITLE
Proxmox clone doesn't start sshd.service automatically 

### ISSUE THREAD

**Issue by ismailbouhlel611** [ansible/ansible#81215]
### Summary

when i created the proxmox vm template i made sure that sshd is enabled so it starts on boot.
when i tested the cloning manually in proxmox the newly created vm had sshd automatically started while when cloning using ansible "proxmox_kvm" sshd was stopped.
this is the ansible code:
> - name: Proxmox stuff
  hosts: all
  vars:
    name: arch
  tasks:
    - set_fact:
        yeppers: "arch-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
    - proxmox_kvm:
        api_user    : root@pam
        api_password: *****
        api_host    :  ip@
        clone       : ArchTemplate
        name        : "{{ yeppers }}"
        node        : pve
        storage     : local-lvm
        format      : qcow2
        timeout     : 500

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ismail/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ismail/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ismail/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ismail/.local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False

ssh:
___
:...skipping...
CONFIG_FILE() = /etc/ansible/ansible.cfg
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/etc/ansible/ansible.cfg) = False
~
~
~
~
~
~
~
~
~
(END)
```

### OS / Environment

lubuntu

### Steps to Reproduce

```yaml (paste below)
 - name: Proxmox stuff
  hosts: all
  vars:
    name: arch
  tasks:
    - set_fact:
        yeppers: "arch-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
    - proxmox_kvm:
        api_user    : root@pam
        api_password: *****
        api_host    :  ip@
        clone       : ArchTemplate
        name        : "{{ yeppers }}"
        node        : pve
        storage     : local-lvm
        format      : qcow2
        timeout     : 500

```

### Expected Results

sshd stopped

### Actual Results

```console
sshd didn't start automatically
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
