### ISSUE TITLE
include_tasks leaks loop_var inside register value

### ISSUE THREAD

**Issue by vladorf** [ansible/ansible#81238]
### Summary

Registered variable from `include_tasks` includes  `include_args` with unresolved values - accessing that variable will trigger resolving of `include_args`, which ends up with error - used variables may be already out-of-scope (e.g. loop variable)

### Issue Type

Bug Report

### Component Name

include_tasks

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.1]
  config file = None
  configured module search path = ['/home/vladorf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vladorf/ansible_bug/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/vladorf/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/vladorf/ansible_bug/venv/bin/ansible
  python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] (/home/vladorf/ansible_bug/venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less
```

### OS / Environment

arch-linux

### Steps to Reproduce

playbook.yml
```yaml (paste below)
- name: "Strange behaviour demonstration"
  hosts: all
  gather_facts: false
  tasks:
    - include_tasks: "tasks.yml"
      args:
        apply:
          vars:
            bar: "{{ item }}"
      loop:
        - foo
      register: output

    # variable is unreadable, it contains reference to `item` from previous task
    - debug:
        msg: "{{ output }}"
```
tasks.yml
```yaml
`# Empty file is enough`
```
test_inventory
```
`remotemachine.example.com`
```

error can be reproduced using
```
ansible-playbook playbook.yml -i test_inventory
```

### Expected Results

`debug` task won't result in playbook fail

### Actual Results

```console
PLAY [Strange behaviour demonstration] ********************************************************************************

TASK [include_tasks] **************************************************************************************************

TASK [set_fact] *******************************************************************************************************
fatal: [remotemachine.example.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {'include': 'tasks.yml', 'include_args': {'apply': {'vars': {'bar': '{{ item }}'}}}, 'changed': False}: 'item' is undefined. 'item' is undefined. {'include': 'tasks.yml', 'include_args': {'apply': {'vars': {'bar': '{{ item }}'}}}, 'changed': False}: 'item' is undefined. 'item' is undefined\n\nThe error appears to be in '/home/vladorf/ansible_bug/playbook.yml': line 13, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    # variable is unreadable, it contains reference to `item` from previous task\n    - set_fact:\n      ^ here\n"}

PLAY RECAP ************************************************************************************************************
remotemachine.example.com  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
