### ISSUE TITLE
Failed to resolve hostname inventory_hostname (Temporary failure in name resolution)

### ISSUE THREAD

**Issue by travisjohnsonga** [ansible/ansible#81269]
### Summary

Trying to run a playbook and get the error Failed to resolve hostname inventory_hostname (Temporary failure in name resolution)

This error does not occur on ansible 2.9.27 with  python version = 2.7.5

ansible-playbook [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/administrator/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/administrator/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/administrator/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
SSH password:
setting up inventory plugins

Parsed /data/ansible/inventory/small_clinic_switches.yml inventory source with yaml plugin
setting up inventory plugins

Parsed /data/ansible/inventory/small_clinic_switches_sdwan.yml inventory source with yaml plugin
redirecting (type: modules) ansible.builtin.asa_command to cisco.asa.asa_command
Loading collection cisco.asa from /home/administrator/.local/lib/python3.10/site-packages/ansible_collections/cisco/asa
redirecting (type: modules) ansible.builtin.ios_command to cisco.ios.ios_command
Loading collection cisco.ios from /home/administrator/.ansible/collections/ansible_collections/cisco/ios
redirecting (type: modules) ansible.builtin.ios_command to cisco.ios.ios_command
redirecting (type: modules) ansible.builtin.aireos_command to community.network.aireos_command
Loading collection community.network from /home/administrator/.ansible/collections/ansible_collections/community/network
Loading callback plugin default of type stdout, v2.0 from /home/administrator/.local/lib/python3.10/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: backup-configs-ios.yml ************************************************************************************************************************************************************************************************************
Positional arguments: ./backup-configs-ios.yml
verbosity: 4
remote_user: ejohn167
connection: smart
timeout: 10
ask_pass: True
become_method: sudo
tags: ('all',)
inventory: ('/data/ansible/inventory',)
subset: 8122-1FMDF-CRT-01
forks: 5
1 plays in ./backup-configs-ios.yml

PLAY [Backup IOS Device Configurations] *****************************************************************************************************************************************************************************************************

TASK [Create a directory] *******************************************************************************************************************************************************************************************************************
task path: /data/ansible/playbooks/backup-configs-ios.yml:7
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: administrator
<localhost> EXEC /bin/sh -c 'echo ~administrator && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/administrator/.ansible/tmp `"&& mkdir "` echo /home/administrator/.ansible/tmp/ansible-tmp-1689363089.448366-4829-150622076733302 `" && echo ansible-tmp-1689363089.448366-4829-150622076733302="` echo /home/administrator/.ansible/tmp/ansible-tmp-1689363089.448366-4829-150622076733302 `" ) && sleep 0'
Using module file /home/administrator/.local/lib/python3.10/site-packages/ansible/modules/file.py
<localhost> PUT /home/administrator/.ansible/tmp/ansible-local-4820yj5rs_ra/tmprssj9sfr TO /home/administrator/.ansible/tmp/ansible-tmp-1689363089.448366-4829-150622076733302/AnsiballZ_file.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/administrator/.ansible/tmp/ansible-tmp-1689363089.448366-4829-150622076733302/ /home/administrator/.ansible/tmp/ansible-tmp-1689363089.448366-4829-150622076733302/AnsiballZ_file.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/administrator/.ansible/tmp/ansible-tmp-1689363089.448366-4829-150622076733302/AnsiballZ_file.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/administrator/.ansible/tmp/ansible-tmp-1689363089.448366-4829-150622076733302/ > /dev/null 2>&1 && sleep 0'
ok: [8122-1FMDF-CRT-01 -> localhost] => {
    "changed": false,
    "diff": {
        "after": {
            "path": "/data/configbackups/8122"
        },
        "before": {
            "path": "/data/configbackups/8122"
        }
    },
    "gid": 1000,
    "group": "administrator",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": null,
            "access_time": null,
            "access_time_format": "%Y%m%d%H%M.%S",
            "attributes": null,
            "follow": true,
            "force": false,
            "group": null,
            "mode": null,
            "modification_time": null,
            "modification_time_format": "%Y%m%d%H%M.%S",
            "owner": null,
            "path": "/data/configbackups/8122",
            "recurse": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "directory",
            "unsafe_writes": false
        }
    },
    "mode": "0775",
    "owner": "administrator",
    "path": "/data/configbackups/8122",
    "size": 4096,
    "state": "directory",
    "uid": 1000
}

TASK [Get show running ASA] *****************************************************************************************************************************************************************************************************************
task path: /data/ansible/playbooks/backup-configs-ios.yml:14
skipping: [8122-1FMDF-CRT-01] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [copy Running config to backup folder asa] *********************************************************************************************************************************************************************************************
task path: /data/ansible/playbooks/backup-configs-ios.yml:19
skipping: [8122-1FMDF-CRT-01] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [Get show running IOS] *****************************************************************************************************************************************************************************************************************
task path: /data/ansible/playbooks/backup-configs-ios.yml:28
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
Loading collection ansible.netcommon from /home/administrator/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /home/administrator/.ansible/collections/ansible_collections/ansible/utils
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
<10.8.48.16> attempting to start connection
<10.8.48.16> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/bin/ansible-connection
<10.8.48.16> local domain socket does not exist, starting it
<10.8.48.16> control socket path is /home/administrator/.ansible/pc/e554972e25
<10.8.48.16> local domain socket listeners started successfully
<10.8.48.16> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /home/administrator/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os ios
<10.8.48.16> ssh type is set to auto
<10.8.48.16> autodetecting ssh_type
<10.8.48.16> ssh type is now set to libssh
<10.8.48.16>
<10.8.48.16> local domain socket path is /home/administrator/.ansible/pc/e554972e25
redirecting (type: modules) ansible.builtin.ios_command to cisco.ios.ios_command
redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
<10.8.48.16> Using network group action ios for ios_command
redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
<10.8.48.16> ANSIBLE_NETWORK_IMPORT_MODULES: enabled
redirecting (type: modules) ansible.builtin.ios_command to cisco.ios.ios_command
<10.8.48.16> ANSIBLE_NETWORK_IMPORT_MODULES: found ios_command  at /home/administrator/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_command.py
<10.8.48.16> ANSIBLE_NETWORK_IMPORT_MODULES: running ios_command
<10.8.48.16> ANSIBLE_NETWORK_IMPORT_MODULES: complete
The full traceback is:
  File "/home/administrator/.ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 60, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/home/administrator/.local/lib/python3.10/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [8122-1FMDF-CRT-01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show running-config"
            ],
            "interval": 1,
            "match": "all",
            "retries": 9,
            "wait_for": null
        }
    },
    "msg": "ssh connection failed: ssh connect failed: Failed to resolve hostname inventory_hostname (Temporary failure in name resolution)"
}

### Issue Type

Bug Report

### Component Name

network_cli

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/administrator/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/administrator/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/administrator/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/administrator/.local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ACTION_WARNINGS(default) = True
AGNOSTIC_BECOME_PROMPT(default) = True
ANSIBLE_CONNECTION_PATH(default) = None
ANSIBLE_COW_ACCEPTLIST(default) = ['bud-frogs', 'bunny', 'cheese', 'daemon', 'default', 'dragon', 'elephant-in-snake', 'elephant', 'eyes', 'hellokitty', 'kitty', 'luke-koala', 'meow', 'milk', 'moofasa', 'moose', 'ren', 'sheep', 'small',>
ANSIBLE_COW_PATH(default) = None
ANSIBLE_COW_SELECTION(default) = default
ANSIBLE_FORCE_COLOR(default) = False
ANSIBLE_HOME(default) = /home/administrator/.ansible
ANSIBLE_NOCOLOR(default) = False
ANSIBLE_NOCOWS(default) = False
ANSIBLE_PIPELINING(default) = False
ANY_ERRORS_FATAL(default) = False
BECOME_ALLOW_SAME_USER(default) = False
BECOME_PASSWORD_FILE(default) = None
BECOME_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/become', '/usr/share/ansible/plugins/become']
CACHE_PLUGIN(default) = memory
CACHE_PLUGIN_CONNECTION(default) = None
CACHE_PLUGIN_PREFIX(default) = ansible_facts
CACHE_PLUGIN_TIMEOUT(default) = 86400
CALLBACKS_ENABLED(default) = []
COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH(default) = warning
COLLECTIONS_PATHS(default) = ['/home/administrator/.ansible/collections', '/usr/share/ansible/collections']
COLLECTIONS_SCAN_SYS_PATH(default) = True
COLOR_CHANGED(default) = yellow
COLOR_CONSOLE_PROMPT(default) = white
COLOR_DEBUG(default) = dark gray
COLOR_DEPRECATE(default) = purple
COLOR_DIFF_ADD(default) = green
COLOR_DIFF_LINES(default) = cyan
COLOR_DIFF_REMOVE(default) = red
COLOR_ERROR(default) = red
COLOR_HIGHLIGHT(default) = white
COLOR_OK(default) = green
COLOR_SKIP(default) = cyan
COLOR_UNREACHABLE(default) = bright red
COLOR_VERBOSE(default) = blue
COLOR_WARN(default) = bright purple
CONFIG_FILE() = /etc/ansible/ansible.cfg
CONNECTION_FACTS_MODULES(default) = {'asa': 'ansible.legacy.asa_facts', 'cisco.asa.asa': 'cisco.asa.asa_facts', 'eos': 'ansible.legacy.eos_facts', 'arista.eos.eos': 'arista.eos.eos_facts', 'frr': 'ansible.legacy.frr_facts', 'frr.frr.frr>
CONNECTION_PASSWORD_FILE(default) = None
COVERAGE_REMOTE_OUTPUT(default) = None
COVERAGE_REMOTE_PATHS(default) = *
DEFAULT_ACTION_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/action', '/usr/share/ansible/plugins/action']
DEFAULT_ALLOW_UNSAFE_LOOKUPS(default) = False
DEFAULT_ASK_PASS(default) = False
DEFAULT_ASK_VAULT_PASS(default) = False
DEFAULT_BECOME(default) = False
DEFAULT_BECOME_ASK_PASS(default) = False
DEFAULT_BECOME_EXE(default) = None
DEFAULT_BECOME_FLAGS(default) = None
DEFAULT_BECOME_METHOD(default) = sudo
DEFAULT_BECOME_USER(default) = root
DEFAULT_CACHE_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/cache', '/usr/share/ansible/plugins/cache']
DEFAULT_CALLBACK_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/callback', '/usr/share/ansible/plugins/callback']
DEFAULT_CLICONF_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/cliconf', '/usr/share/ansible/plugins/cliconf']
DEFAULT_CONNECTION_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/connection', '/usr/share/ansible/plugins/connection']
DEFAULT_DEBUG(default) = False
DEFAULT_EXECUTABLE(default) = /bin/sh
DEFAULT_FACT_PATH(default) = None
DEFAULT_FILTER_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter']
DEFAULT_FORCE_HANDLERS(default) = False
DEFAULT_FORKS(default) = 5
DEFAULT_GATHERING(default) = implicit
DEFAULT_GATHER_SUBSET(default) = None
DEFAULT_GATHER_TIMEOUT(default) = None
DEFAULT_HASH_BEHAVIOUR(default) = replace
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/data/ansible/inventory']
DEFAULT_HTTPAPI_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/httpapi', '/usr/share/ansible/plugins/httpapi']
DEFAULT_INTERNAL_POLL_INTERVAL(default) = 0.001
DEFAULT_INVENTORY_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/inventory', '/usr/share/ansible/plugins/inventory']
DEFAULT_JINJA2_EXTENSIONS(default) = []
DEFAULT_JINJA2_NATIVE(default) = False
DEFAULT_KEEP_REMOTE_FILES(default) = False
DEFAULT_LIBVIRT_LXC_NOSECLABEL(default) = False
DEFAULT_LOAD_CALLBACK_PLUGINS(default) = False
DEFAULT_LOCAL_TMP(default) = /home/administrator/.ansible/tmp/ansible-local-48101doc4cks
DEFAULT_LOG_FILTER(default) = []
DEFAULT_LOG_PATH(default) = None
DEFAULT_LOOKUP_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup']
DEFAULT_MANAGED_STR(default) = Ansible managed
DEFAULT_MODULE_ARGS(default) = None
DEFAULT_MODULE_COMPRESSION(default) = ZIP_DEFLATED
DEFAULT_MODULE_NAME(default) = command
DEFAULT_MODULE_PATH(default) = ['/home/administrator/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(default) = ['/home/administrator/.ansible/plugins/module_utils', '/usr/share/ansible/plugins/module_utils']
DEFAULT_NETCONF_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/netconf', '/usr/share/ansible/plugins/netconf']
DEFAULT_NO_LOG(default) = False
DEFAULT_NO_TARGET_SYSLOG(default) = False
DEFAULT_NULL_REPRESENTATION(default) = None
DEFAULT_POLL_INTERVAL(default) = 15
DEFAULT_PRIVATE_KEY_FILE(default) = None
DEFAULT_PRIVATE_ROLE_VARS(default) = False
DEFAULT_REMOTE_PORT(default) = None
DEFAULT_REMOTE_USER(default) = None
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/data/ansible']
DEFAULT_SELINUX_SPECIAL_FS(default) = ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p', 'vfat']
DEFAULT_STDOUT_CALLBACK(default) = default
DEFAULT_STRATEGY(default) = linear
DEFAULT_STRATEGY_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/strategy', '/usr/share/ansible/plugins/strategy']
DEFAULT_SU(default) = False
DEFAULT_SYSLOG_FACILITY(default) = LOG_USER
DEFAULT_TERMINAL_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/terminal', '/usr/share/ansible/plugins/terminal']
DEFAULT_TEST_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/test', '/usr/share/ansible/plugins/test']
DEFAULT_TIMEOUT(default) = 10
DEFAULT_TRANSPORT(default) = smart
DEFAULT_UNDEFINED_VAR_BEHAVIOR(default) = True
DEFAULT_VARS_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/vars', '/usr/share/ansible/plugins/vars']
DEFAULT_VAULT_ENCRYPT_IDENTITY(default) = None
DEFAULT_VAULT_IDENTITY(default) = default
DEFAULT_VAULT_IDENTITY_LIST(default) = []
DEFAULT_VAULT_ID_MATCH(default) = False
DEFAULT_VAULT_PASSWORD_FILE(default) = None
DEFAULT_VERBOSITY(default) = 0
DEPRECATION_WARNINGS(default) = True
DEVEL_WARNING(default) = True
DIFF_ALWAYS(default) = False
DIFF_CONTEXT(default) = 3
DISPLAY_ARGS_TO_STDOUT(default) = False
DISPLAY_SKIPPED_HOSTS(default) = True
DOCSITE_ROOT_URL(default) = https://docs.ansible.com/ansible-core/
DOC_FRAGMENT_PLUGIN_PATH(default) = ['/home/administrator/.ansible/plugins/doc_fragments', '/usr/share/ansible/plugins/doc_fragments']
DUPLICATE_YAML_DICT_KEY(default) = warn
ENABLE_TASK_DEBUGGER(default) = False
ERROR_ON_MISSING_HANDLER(default) = True
FACTS_MODULES(default) = ['smart']
GALAXY_CACHE_DIR(default) = /home/administrator/.ansible/galaxy_cache
GALAXY_COLLECTION_SKELETON(default) = None
GALAXY_COLLECTION_SKELETON_IGNORE(default) = ['^.git$', '^.*/.git_keep$']
GALAXY_DISABLE_GPG_VERIFY(default) = False
GALAXY_DISPLAY_PROGRESS(default) = None
GALAXY_GPG_KEYRING(default) = None
GALAXY_IGNORE_CERTS(default) = None
GALAXY_IGNORE_INVALID_SIGNATURE_STATUS_CODES(default) = None
GALAXY_REQUIRED_VALID_SIGNATURE_COUNT(default) = 1
GALAXY_ROLE_SKELETON(default) = None
GALAXY_ROLE_SKELETON_IGNORE(default) = ['^.git$', '^.*/.git_keep$']
GALAXY_SERVER(default) = https://galaxy.ansible.com
GALAXY_SERVER_LIST(default) = None
GALAXY_TOKEN_PATH(default) = /home/administrator/.ansible/galaxy_token
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
HOST_PATTERN_MISMATCH(default) = warning
INJECT_FACTS_AS_VARS(default) = True
INTERPRETER_PYTHON(default) = auto
INTERPRETER_PYTHON_FALLBACK(default) = ['python3.11', 'python3.10', 'python3.9', 'python3.8', 'python3.7', 'python3.6', 'python3.5', '/usr/bin/python3', '/usr/libexec/platform-python', 'python2.7', '/usr/bin/python', 'python']
INVALID_TASK_ATTRIBUTE_FAILED(default) = True
INVENTORY_ANY_UNPARSED_IS_FAILED(default) = False
INVENTORY_CACHE_ENABLED(default) = False
INVENTORY_CACHE_PLUGIN(default) = None
INVENTORY_CACHE_PLUGIN_CONNECTION(default) = None
INVENTORY_CACHE_PLUGIN_PREFIX(default) = ansible_inventory_
INVENTORY_CACHE_TIMEOUT(default) = 3600
INVENTORY_ENABLED(default) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml']
INVENTORY_EXPORT(default) = False
INVENTORY_IGNORE_EXTS(default) = ('.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '.rst', '.orig', '.ini', '.cfg', '.retry')
INVENTORY_IGNORE_PATTERNS(default) = []
INVENTORY_UNPARSED_IS_FAILED(default) = False
INVENTORY_UNPARSED_WARNING(default) = True
JINJA2_NATIVE_WARNING(default) = True
LOCALHOST_WARNING(default) = True
MAX_FILE_SIZE_FOR_DIFF(default) = 104448
MODULE_IGNORE_EXTS(default) = ('.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '.rst', '.yaml', '.yml', '.ini')
NETCONF_SSH_CONFIG(default) = None
NETWORK_GROUP_MODULES(default) = ['eos', 'nxos', 'ios', 'iosxr', 'junos', 'enos', 'ce', 'vyos', 'sros', 'dellos9', 'dellos10', 'dellos6', 'asa', 'aruba', 'aireos', 'bigip', 'ironware', 'onyx', 'netconf', 'exos', 'voss', 'slxos']
OLD_PLUGIN_CACHE_CLEARING(default) = False
PARAMIKO_HOST_KEY_AUTO_ADD(default) = False
PARAMIKO_LOOK_FOR_KEYS(default) = True
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 180
PERSISTENT_CONNECT_RETRY_TIMEOUT(default) = 15
PERSISTENT_CONNECT_TIMEOUT(default) = 30
PERSISTENT_CONTROL_PATH_DIR(default) = /home/administrator/.ansible/pc
PLAYBOOK_DIR(default) = None
PLAYBOOK_VARS_ROOT(default) = top
PLUGIN_FILTERS_CFG(default) = None
PYTHON_MODULE_RLIMIT_NOFILE(default) = 0
RETRY_FILES_ENABLED(default) = False
RETRY_FILES_SAVE_PATH(default) = None
RUN_VARS_PLUGINS(default) = demand
SHOW_CUSTOM_STATS(default) = False
STRING_CONVERSION_ACTION(default) = warn
STRING_TYPE_FILTERS(default) = ['string', 'to_json', 'to_nice_json', 'to_yaml', 'to_nice_yaml', 'ppretty', 'json']
SYSTEM_WARNINGS(default) = True
TAGS_RUN(default) = []
TAGS_SKIP(default) = []
TASK_DEBUGGER_IGNORE_ERRORS(default) = True
TASK_TIMEOUT(default) = 0
TRANSFORM_INVALID_GROUP_CHARS(default) = never
USE_PERSISTENT_CONNECTIONS(default) = False
VALIDATE_ACTION_GROUP_METADATA(default) = True
VARIABLE_PLUGINS_ENABLED(default) = ['host_group_vars']
VARIABLE_PRECEDENCE(default) = ['all_inventory', 'groups_inventory', 'all_plugins_inventory', 'all_plugins_play', 'groups_plugins_inventory', 'groups_plugins_play']
VERBOSE_TO_STDERR(default) = False
WIN_ASYNC_STARTUP_TIMEOUT(default) = 5
WORKER_SHUTDOWN_POLL_COUNT(default) = 0
WORKER_SHUTDOWN_POLL_DELAY(default) = 0.1
YAML_FILENAME_EXTENSIONS(default) = ['.yml', '.yaml', '.json']
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
#!/usr/bin/ansible-playbook
- name: "Backup IOS Device Configurations"
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Create a directory
      file:
        path: /data/configbackups/{{  hostvars[inventory_hostname]["sites"][0]["facility"] }}
        state: directory
      delegate_to: localhost
    - name: Get running configs ASA
      block:
      - name: Get show running ASA
        when: ansible_network_os == 'asa'
        asa_command:
          commands:  more system:running-config
        register: ios_cmd
      - name: copy Running config to backup folder asa
        when: ansible_network_os == 'asa'
        copy:
          content: "{{ ios_cmd.stdout[0] }}"
          dest: '/data/configbackups/{{ hostvars[inventory_hostname]["sites"][0]["facility"] }}/config-{{ hostvars[inventory_hostname] }}.txt'

    - name: Get Running Config IOS
      when: ansible_network_os == 'ios'
      block:
      - name: Get show running IOS
        ios_command:
          commands: show running-config
        register: ios_cmd
      - name: copy Running config to backup folder IOS
        when: ansible_network_os == 'ios'
        copy:
          content: "{{ ios_cmd.stdout[0] }}"
          dest: "/data/configbackups/test.txt"
    - name: Get Running Config NXOS
      when: ansible_network_os == 'nxos'
      block:
      - name: Get show running NXOS
        ios_command:
          commands: show running-config
        register: ios_cmd
      - name: copy Running config to backup folder NXOS
        when: ansible_network_os == 'nxos'
        copy:
          content: "{{ ios_cmd.stdout[0] }}"
          dest: '/data/configbackups/{{ hostvars[inventory_hostname]["sites"][0]["facility"] }}/config-{{ hostvars[inventory_hostname] }}.txt'

    - name: Get Running Config WLC
      when: ansible_network_os == 'community.network'
      block:
      - name: Get show running
        aireos_command:
          commands: show run-config commands
        register: output
      - name: copy Running config to backup folder WLC
        copy:
          content: "{{ output.stdout[0] }}"
          dest: '/data/configbackups/{{ hostvars[inventory_hostname]["sites"][0]["facility"] }}/config-{{ hostvars[inventory_hostname] }}.txt'

    - name: remove commented lines with timestamps
      # Cisco/NXOS specific - avoid timestamp from always marking config as changed
      shell: |
        sed -i -e '/^!Time/d' /data/configbackups/{{ FACTS_OUT_PATH }}/config-*.txt
      args:
        warn: no
      delegate_to: localhost
      run_once: true
    - name: commit changes to git
      shell: |
        cd /data/configbackups/
        git add .
        git commit -m "Config snapshot taken $(date +"%Y-%m-%d %H:%M:%S")"
        git push
        # Needed as git commit will fail if there are no changed files
        exit 0
      delegate_to: localhost
      run_once: true

```

### Expected Results

Expect the playbook to ssh to device, however, get name resolution failed.

I am able to ssh to both hostname of device and IP

### Actual Results

```console
The full traceback is:
  File "/home/administrator/.ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 60, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/home/administrator/.local/lib/python3.10/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [8122-1FMDF-CRT-01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show running-config"
            ],
            "interval": 1,
            "match": "all",
            "retries": 9,
            "wait_for": null
        }
    },
    "msg": "ssh connection failed: ssh connect failed: Failed to resolve hostname inventory_hostname (Temporary failure in name resolution)"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
