### ISSUE TITLE
Recursive copy with remote_src changes parent directory permissions

### ISSUE THREAD

**Issue by wally007** [ansible/ansible#81292]
### Summary

When `copy` module is run with `remote_src: true` the behavior of how permissions are set  using `mode/directory_mode` is different than when run without.
This has been mentioned couple of times but I didnt find any bug report that had been followed up on.

For example here, it is commented here that "this seems wrong" but not followed up.
https://github.com/ansible/ansible/issues/61187#issuecomment-717564979

I'm using RHEL8.8, AAP 2.4, Execution Env based on ansible 2.15.0 with Python 3.9.16

### Issue Type

Bug Report

### Component Name

copy module

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, May 31 2023, 12:21:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
bash-4.4$
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL8.8

### Steps to Reproduce

```yaml (paste below)
- name: Copy files
  ansible.builtin.copy:
    src: /tmp/etc/
    dest: /usr/local/etc
    mode: "0644"
    directory_mode: "0755"
    remote_src: true
    owner: root
    group: root
```
The top-level `/usr/local/etc` directory on the remote server gets changed from 755 to 644 (along with all the files which is expected)

When running the exact same task **but without** `remote_src: true`
```yaml (paste below)
- name: Copy files
  ansible.builtin.copy:
    src: /tmp/etc/
    dest: /usr/local/etc
    mode: "0644"
    directory_mode: "0755"
    owner: root
    group: root
```

The top-level `/usr/local/etc` directory on the remote server does not get touched at all.

### Expected Results

 The top-level directory should not get its permissions changed when used with remote_src= true
 
 The behaviour of setting the permissions should be the same whether the `remote_src` is set to `true` or `false`

### Actual Results

```console
The top-level directory permissions get changed when used with remote_src= true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/copy.py)
* [`lib/ansible/plugins/action/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/copy.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/mkrizek/ansibotmini/blob/main/README.md) bot command.

**Comment by paulrenn67** [comment]
I hit the same issue, the top level dest directory mode is set to the file `mode`, not `directory_mode`, even if the top level directory previously existed.

**Comment by db-wally007** [comment]
My ticket with RH is still opened - no update if they are looking at it though in the last few months (and in the meantime I've done manual workarounds in my playbook)

**Comment by hmoffatt** [comment]
I discovered this too. I'm using ansible-core 2.17.0. The documentation says that copy should not change the permissions on any directory that already exists, but it does. 

Here is my sample playbook.

```
---
- hosts: all
  become: true
  tasks:
    - ansible.builtin.file:
        path: dir1
        state: directory
        owner: root
        group: root
        mode: "0755"

    - ansible.builtin.file:
        path: dir2
        state: directory
        owner: root
        group: root
        mode: "0755"

    - ansible.builtin.copy:
        remote_src: true
        src: dir1/
        dest: dir2/
        mode: "0644"
        directory_mode: "0755"
        owner: "root"
        group: "root"
```
