### ISSUE TITLE
uri / get_url: support passage of proxy credentials via module options

### ISSUE THREAD

**Issue by amg1127** [ansible/ansible#81331]
### Summary

This request is for [uri](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html) and [get_url](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html) modules to support passing of network proxy credentials via new module options `proxy_username` and `proxy_password`, as their Windows-equivalent modules [win_uri](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_uri_module.html) and [win_get_url](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_get_url_module.html) modules currently do:

```
---
- hosts: localhost
  gather_facts: no
  vars:
    proxyScheme: http
    proxyAddress: localhost
    proxyPort: 3128
    proxyInfo: "{{ proxyScheme }}://{{ proxyAddress }}:{{ proxyPort }}"
  environment:
    http_proxy: "{{ proxyInfo }}"
    https_proxy: "{{ proxyInfo }}"
  tasks:

    - name: Issue a HTTP request via proxy
      uri:
        url: 'http://ip4.me/'
        return_content: yes
        proxy_username: "{{ proxyUser }}"
        proxy_password: "{{ proxyPassword }}"
      no_log: yes
```

### Issue Type

Feature Idea

### Component Name

lib/ansible/module_utils/urls.py

### Additional Information

Under corporate environments, the access from internal devices to the internet is frequently indirect and controlled by network proxies. As a result, it is common that software implementations rely on `${http_proxy}` and `${https_proxy}` environment variables to find addresses of network webproxies whenever they require access to the public internet. Examples of this are the [curl utility](https://curl.se/docs/manpage.html) and the [_requests_ Python library](https://requests.readthedocs.io/en/latest/user/advanced/#proxies).

Frequently, network webproxies require prior user authentication for access to the internet. To support user authentication, most implementations that rely on `${http_proxy}` and `${https_proxy}` environment variables accept a special URL format that includes usernames and passwords separated by an `:` and prepended to the proxy hostname with an `@`: `scheme://user:password@host:port`. Such format is recognized by Ansible's [uri](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html) and [get_url](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html) modules:
- https://github.com/ansible/ansible/blob/5167618e46c18ecabe190fb5fe7342c9f8a9dc3d/lib/ansible/module_utils/urls.py#L1505C25-L1505C26
- https://github.com/python/cpython/blob/cdeb1a6caad5e3067f01d6058238803b8517f9de/Lib/urllib/request.py#L728

The problem is that passing of proxy credentials via environment variables is insecure, as processes are able to read the content of environment variables of any other processes running in the system via the `/proc` pseudo-filesystem. Besides, if Ansible is invoked with a verbosity level of 3 and Ansible effectively controls the proxy environment variables supplied to `uri` and `get_url` modules, then Ansible will disclose proxy credentials on its standard output, as exemplified below.

```
# vault.yml
---
proxyUser: myuser
proxyPassword: secretPassword
```

```
# playbook.yml
---
- hosts: localhost
  gather_facts: no
  vars:
    proxyScheme: http
    proxyAddress: localhost
    proxyPort: 3128
    proxyInfo: "{{ proxyScheme }}://{{ proxyUser | urlencode }}:{{ proxyPassword | urlencode }}@{{ proxyAddress }}:{{ proxyPort }}"
  environment:
    http_proxy: "{{ proxyInfo }}"
    https_proxy: "{{ proxyInfo }}"
  tasks:

    - name: Issue a HTTP request via proxy
      uri:
        url: 'http://ip4.me/'
        return_content: yes
      no_log: yes
```

Running the `playbook.yml` playbook above with `-vvv` argument causes Ansible to disclose the proxy credentials declared inside a vault file:

```
$ ansible-playbook -vvv playbook.yml --extra-vars @vault.yml --ask-vault-pass
ansible-playbook [core 2.15.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/amg1127/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/amg1127/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
Vault password: 
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
redirecting (type: callback) ansible.builtin.profile_tasks to ansible.posix.profile_tasks
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: playbook.yml *********
1 plays in playbook.yml

PLAY [localhost] *********

TASK [Issue a HTTP request via proxy] *********
task path: /tmp/kde-amg1127/playbook.yml:14
Saturday 22 July 2023  17:32:10 +1200 (0:00:00.011)       0:00:00.011 ********* 
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: amg1127
<127.0.0.1> EXEC /bin/sh -c 'echo ~amg1127 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/amg1127/.ansible/tmp `"&& mkdir "` echo /home/amg1127/.ansible/tmp/ansible-tmp-1690003930.6723623-688215-159013547289316 `" && echo ansible-tmp-1690003930.6723623-688215-159013547289316="` echo /home/amg1127/.ansible/tmp/ansible-tmp-1690003930.6723623-688215-159013547289316 `" ) && sleep 0'
Using module file /usr/lib/python3.11/site-packages/ansible/modules/uri.py
<127.0.0.1> PUT /home/amg1127/.ansible/tmp/ansible-local-688210v5v_260l/tmp_qauc0cy TO /home/amg1127/.ansible/tmp/ansible-tmp-1690003930.6723623-688215-159013547289316/AnsiballZ_uri.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/amg1127/.ansible/tmp/ansible-tmp-1690003930.6723623-688215-159013547289316/ /home/amg1127/.ansible/tmp/ansible-tmp-1690003930.6723623-688215-159013547289316/AnsiballZ_uri.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'http_proxy=http://myuser:secretPassword@localhost:3128 https_proxy=http://myuser:secretPassword@localhost:3128 /usr/bin/python /home/amg1127/.ansible/tmp/ansible-tmp-1690003930.6723623-688215-159013547289316/AnsiballZ_uri.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/amg1127/.ansible/tmp/ansible-tmp-1690003930.6723623-688215-159013547289316/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": false
}

PLAY RECAP *********
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Saturday 22 July 2023  17:32:11 +1200 (0:00:00.966)       0:00:00.977 ********* 
========= 
Issue a HTTP request via proxy -------- 0.97s
/tmp/kde-amg1127/playbook.yml:14 --------
```

As a workaround, it is possible to avoid the accidental disclosure of proxy credentials by manually building the `Proxy-Authorization` request header. However, it is not an optional solution; it will not work if the network proxy requires authentication schemes other than `Basic`.

```
# playbook2.yml
---
- hosts: localhost
  gather_facts: no
  vars:
    proxyScheme: http
    proxyAddress: localhost
    proxyPort: 3128
    proxyInfo: "{{ proxyScheme }}://{{ proxyAddress }}:{{ proxyPort }}"
  environment:
    http_proxy: "{{ proxyInfo }}"
    https_proxy: "{{ proxyInfo }}"
  tasks:

    - name: Issue a HTTP request via proxy
      uri:
        url: 'http://ip4.me/'
        return_content: yes
        headers:
          'Proxy-Authorization': "Basic {{ (proxyUser ~ ':' ~ proxyPassword) | b64encode }}"
      no_log: yes
```

It would be useful if the `uri` and `get_url` modules could receive proxy credentials via module options, as [win_uri](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_uri_module.html) and [win_get_url](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_get_url_module.html) modules do:

> - proxy_username
>         The username to use for proxy authentication.
>         default: null
>         type: str
> 
> - proxy_password
>         The password for `proxy_username'.
>         default: null
>         type: str
        

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
