### ISSUE TITLE
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version

### ISSUE THREAD

**Issue by dj-wasabi** [ansible/ansible#81338]
### Summary

I want to authenticate against a Keycloak that is behind an AWS Application Load Balancer which only allows TLS1.3 requests. The task worked before, when also older TLS versions were accepted by the ALB. The playbook is executed from a Mac and also from a Vagrant box with Fedora 38, which both experience the same problems.

According to Python it should use the recent openssl3 version (Fedora) (just booted/created this morning as an attempt for a workaround).
```
[vagrant@localhost ansible]$ python --version; python -c "import ssl; print (ssl.OPENSSL_VERSION)"
Python 3.11.2
OpenSSL 3.0.8 7 Feb 2023
$ openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
```

When I execute it on my Mac, I get:
```
$  python --version; python -c "import ssl; print (ssl.OPENSSL_VERSION)"
Python 3.11.4
OpenSSL 1.1.1u  30 May 2023
$ openssl version
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
```

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
[vagrant@localhost ansible]$ ansible --version
ansible [core 2.15.2]
  config file = /opt/code/deployment/ansible/ansible.cfg
  configured module search path = ['/opt/code/deployment/ansible/library']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 13.0.1 20230208 (Red Hat 13.0.1-0)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /opt/code/deployment/ansible/ansible.cfg
DEFAULT_FORKS(/opt/code/deployment/ansible/ansible.cfg) = 6
DEFAULT_MODULE_PATH(/opt/code/deployment/ansible/ansible.cfg) = ['/opt/code/deployment/ansible/library']
DEFAULT_ROLES_PATH(/opt/code/deployment/ansible/ansible.cfg) = ['/opt/code/deployment/ansible/roles']
DEFAULT_TIMEOUT(/opt/code/deployment/ansible/ansible.cfg) = 30
EDITOR(env: EDITOR) = /usr/bin/nano
HOST_KEY_CHECKING(/opt/code/deployment/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/opt/code/deployment/ansible/ansible.cfg) = /usr/bin/python3
INVENTORY_ANY_UNPARSED_IS_FAILED(/opt/code/deployment/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/opt/code/deployment/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/opt/code/deployment/ansible/ansible.cfg) = False
ssh_args(/opt/code/deployment/ansible/ansible.cfg) = -o UserKnownHostsFile=/dev/null
timeout(/opt/code/deployment/ansible/ansible.cfg) = 30

ssh:
___
host_key_checking(/opt/code/deployment/ansible/ansible.cfg) = False
ssh_args(/opt/code/deployment/ansible/ansible.cfg) = -o UserKnownHostsFile=/dev/null
timeout(/opt/code/deployment/ansible/ansible.cfg) = 30
```

### OS / Environment

NAME="Fedora Linux"
VERSION="38 (Cloud Edition)"

But also on Mac OSX (13.4 (22F66))

### Steps to Reproduce

```yaml (paste below)

    - name: "Authenticate to get an access_token"
      ansible.builtin.uri:
        url: "https://keycloak.example.com/auth/realms/myrealm/protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        validate_certs: false
        body:
          grant_type: "client_credentials"
          client_id: "myclient"
          client_secret: "verysecr3t"
        status_code:
          - 200
          - 201
      register: _state_keycloak_authenticate_data
      until: _state_keycloak_authenticate_data is succeeded
```

### Expected Results

I would expect to have a '200' back with the actual information from the endpoint.

### Actual Results

```console
TASK [Authenticate to get an access_token] ***************************************************************************************************************************************************************************************************
fatal: [ip-10-3-35-10.eu-west-1.compute.internal]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200, 201]: Request failed: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1091)>", "redirected": false, "status": -1, "url": "https://keycloak.example.com/auth/realms/myrealm/protocol/openid-connect/token"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
