### ISSUE TITLE
Evaluate Jinja2 expression lazily

### ISSUE THREAD

**Issue by xiaoyao9184** [ansible/ansible#81337]
### Summary

There is a general task file whose conditional is non-static and needs to be passed through external playbook variables

playbook.yml
```yaml
    - name: fact conditionals
      ansible.builtin.set_fact:
        conditionals:
          - foo is defined
          - not ( foo == 'b' )

    - name: task
      vars:
        conditionals: "{{ conditionals }}"
      include_tasks: tasks.yml
```

tasks.yml
```yaml
    - name: fact foo
      ansible.builtin.set_fact:
        foo: a

    - name: fail when any conditional not pass
      loop: "{{ conditionals }}"
      loop_control:
        loop_var: conditional
      when: "not {{ conditional }}"
      fail:
        msg: "conditional {{ conditional }} result was false!"

```

This gives a "conditional statements should not include jinja2 templating delimiters" warning, but works fine.

When the conditional expression is defined outside, the expression is out of the evaluation context and cannot be evaluated outside, and the lazy evaluation scenario appears.

Is there any way to evaluate a raw Jinja2 expression in a variable?

playbook.yml
```yaml
    - name: fact conditionals
      ansible.builtin.set_fact:
        conditionals:
          - foo is defined
          - not ( foo == 'b' )

    - name: task
      vars:
        conditionals: "{{ conditionals }}"
      include_tasks: tasks.yml
```
tasks.yml
```yaml
    - name: fact foo
      ansible.builtin.set_fact:
        foo: b

    - name: evaluate conditional
      loop: "{{ conditionals }}"
      loop_control:
        loop_var: conditional
      vars:
        # TODO evaluate conditional from string var
        result: {{ conditional }}
      ansible.builtin.debug:
        msg:
          - "conditional expression: {{ conditional }}"
          - "conditional result: {{ result }}"

```

### Issue Type

Feature Idea

### Component Name

when

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/mkrizek/ansibotmini/blob/main/README.md) bot command.

**Comment by mkrizek** [comment]
For demonstration purposes this is simplified version of your first example:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - fail:
      loop: "{{ whens }}"
      when: "not {{ item }}"
      vars:
        foo: a
        whens:
          - foo is defined
          - foo == "b"
```

While it is something we would call an anti-pattern, it does work, as you mentioned:
```
PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [fail] **********************************************************************************************************************************************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: not {{ item }}
skipping: [localhost] => (item=foo is defined) 
failed: [localhost] (item=foo == "b") => {"ansible_loop_var": "item", "changed": false, "item": "foo == \"b\"", "msg": "Failed as requested from task"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

As you can see from the warning it does rely on behavior which is (likely) kept for backwards compatibility.

From the second example you provided I am not clear what is the feature request, can you elaborate and show expected and actual result?

needs_info

**Comment by xiaoyao9184** [comment]
@mkrizek Yes, I rely on this compatibility feature, need a way to evaluate the result of a string expression like this

```yaml
---

- name: test
  hosts: localhost
  gather_facts: no
  tasks:

    # define the conditional expression string before foo initialized
    - name: fact conditionals
      ansible.builtin.set_fact:
        conditionals:
          - foo is defined
          - not ( foo == 'b' )

    # foo fact
    - name: fact foo
      ansible.builtin.set_fact:
        foo: a

    # evaluable conditional expression string after foo initialized
    - name: evaluate conditional
      loop: "{{ conditionals }}"
      loop_control:
        loop_var: conditional
      vars:
        # TODO evaluate conditional from string
        # eval expression string "foo is defined" to true
        # eval expression string "not ( foo == 'b' )" to true
        result: "{{ conditional }}"
        list: "{{ conditional_results | default([]) }}"
      ansible.builtin.set_fact:
        conditional_results: "{{ list + [ result ] }}"
 
    - name: print evaluate
      ansible.builtin.debug:
        var: conditional_results

    - name: fail when any conditional result not true
      loop: "{{ conditional_results }}"
      loop_control:
        loop_var: conditional
      when: not conditional
      fail:
        msg: "conditional result was false!"

```


expected result
```log
PLAY [test] **********************************************************************************************************************

TASK [fact conditionals] *********************************************************************************************************
ok: [localhost]

TASK [fact foo] ******************************************************************************************************************
ok: [localhost]

TASK [evaluate conditional] ******************************************************************************************************
ok: [localhost] => (item=foo is defined)
ok: [localhost] => (item=not ( foo == 'b' ))

TASK [print evaluate] ************************************************************************************************************
ok: [localhost] => {
    "conditional_results": [
        true,
        true
    ]
}

TASK [fail when any conditional result not true] *********************************************************************************
skipping: [localhost] => (item=True)
skipping: [localhost] => (item=True)
skipping: [localhost]

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

**Comment by mkrizek** [comment]
I suppose I am missing a broader context of your playbook but I am not clear why your first example or my simplified version aren't sufficient.

In any case if I understand this correctly the feature request here is to provide some mechanism to double template a variable (the first templating gets the content of the variable and the second templating templates the content): `result: "{{ conditional }}"` would have to be templated twice in your example to achieve the result listed in "expected result". Which is why the first example works because `when` provides implicit templating so if you put a template into `when` it will be templated twice.

To again simplify the example of the feature idea [0]:
```yaml
- debug:
    msg: "{{ conditional }}"  # double template this variable to 1. get the conditional and 2. evaluate it
  vars:
    conditional: "foo is defined"
    foo: hello
```

Personally I would be -1 on introducing such feature, 1. the templating is complicated as is, 2. I am afraid it would encourage users to do (more) programming in playbooks which are not designed for it.

---

[0] Although even in `debug` one can make use of implicit templating of its `var` parameter. But this is IMO, as in the case of `when`, relying on "unsupported functionality" which is not advised:

```yaml
- debug:
    var: "{{ conditional }}"
  vars:
    conditional: "foo is defined"
    foo: hello
  # potentially add:
  # register: result
  # failed_when: result[conditional]
```

**Comment by flowerysong** [comment]
The default behaviour is for variables to be lazily evaluated, so if you just use variables normally and don't evaluate them early by using `set_fact` everything Just Works™:

```
- hosts: localhost
  gather_facts: false
  vars:
    conditionals:
      - "{{ foo is defined }}"
      - "{{ foo != 'b' }}"
  tasks:
    - name: Set foo
      ansible.builtin.set_fact:
        foo: a

    - name: Fail when any conditional result is false
      ansible.builtin.assert:
        that:
          - conditionals is all

    - name: Set foo
      ansible.builtin.set_fact:
        foo: b

    - name: Fail when any conditional result is false
      ansible.builtin.assert:
        that:
          - conditionals is all
```

Result:
```
PLAY [localhost] ****************************************************************
TASK [Set foo] ******************************************************************
ok: [localhost]

TASK [Fail when any conditional result is false] ********************************
ok: [localhost] =>
    changed: false
    msg: All assertions passed

TASK [Set foo] ******************************************************************
ok: [localhost]

TASK [Fail when any conditional result is false] ********************************
fatal: [localhost]: FAILED! =>
    assertion: conditionals is all
    changed: false
    evaluated_to: false
    msg: Assertion failed
```

It's very unclear what constraints might have led you to structuring the playbook the way you have it, but if you really need to evaluate arbitrary strings as Jinja expressions I suggest writing a custom filter that does so, rather than trying to introduce new and confusing behaviour to Ansible's templating system.
