### ISSUE TITLE
apt_repository please support deb822 format

### ISSUE THREAD

**Issue by Zugschlus** [ansible/ansible#81343]
### Summary

Hi,

apt_repository currently writes classic sources.list format to /etc/apt/sources.list and /etc/apt/sources.list.d. The old file format with one line per repository is clumsy, hard to read and hard to write. apt has recently (2015 *cough*) grown a new file format which blends in better with other configuration files in deb822 format. See https://salsa.debian.org/apt-team/apt/-/blob/main/doc/sources.list.5.xml for documentation.

The new files are easily distinguishible because they no longer end in .list, but in .sources. The old format is not going to go away any time soon, but the apt authors are planning to slowly make deb822 the new default as it is more flexible and some option already cannot be put in traditional format files.

As far as I can see from the changelog, python-apt supports the new format since version 2.5, so ansible can now start supporting the new format now as well. It would be good if an apt_repository task would automatically write in new format if the destination file is /etc/apt/sources.list.d/foo.sources. If it is currently possible to just specify a plain file name with apt_repository adding .list by default, this should stay the default for the time being, while emitting a warning in a few years.

Greetings
Marc

### Issue Type

Feature Idea

### Component Name

apt_repository

### Additional Information

```
- name: Remove specified repository from sources list
  ansible.builtin.apt_repository:
    types: 'deb' (optionally, a list!)
    URIs: 'http://deb.debian.org/debian'
    suites:  'hardy' (optionally, a list!)
    components: ['main', 'contrib', 'non-free'] (optionally, a single string)
    enabled: yes
    state: absent
```

(see other options documented in sources.list(5), link above)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
