### ISSUE TITLE
Files modules parameters values and spaces

### ISSUE THREAD

**Issue by knopkodav** [ansible/ansible#8136]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.6.6
```
##### Environment:

OSX 10.9.3
##### Summary:

Some Files modules failed working with pathnames having spaces.
##### Steps To Reproduce:

Try to use 'copy' or 'synchronize' module with 'src' or 'dest' parameter containing path with spaces, e.g.:

```
  synchronize: >
    src="/Users/ilya/Awesome Projects/some/interesting/project/"
    dest=/srv/project
    mode=push
    recursive=yes
```
##### Expected Results:

Execution without any errors.
##### Actual Results:

```
failed: [hostname.redacted] => {"cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --exclude=.git --out-format='<<CHANGED>>%i %n%L' /Users/ilya/Awesome Projects/some/interesting/project/ user@hostname.redacted:/srv/project", "failed": true, "rc": 23}
msg: rsync: link_stat "/Users/ilya/Awesome" failed: No such file or directory (2)
rsync: link_stat "/Users/ilya/Awesome Projects/some/interesting/project/deploy/Projects/some/interesting/project/deploy" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]
```

So, rsync thinks it's a SEVERAL directories to sync.

**Comment by pesterhazy** [comment]
A similar problem exists with the `fetch` module:

```
       - name: fetch main db dump
         fetch: >
             src=/home/ubuntu/main.sql.gz dest=../data/main.sql.gz
             validate_md5=no flat=yes fail_on_missing=yes
```

If the current directory is "/User/user/a b c/bla", then this will actually write to a file called "a" instead of main.sql.gz.

Maybe OSX-specific? Also using OSX 10.9.3 here.

**Comment by knopkodav** [comment]
@pesterhazy it's not os-related problem, it's just names :-) E.g., we have Jenkins working directories named "Build and deploy to DEV", it's default Jenkins behavior to create directories called like task. On any server, any OS. So, the directory contains spaces as you see. And this is the problem :)

You can write a workaround to use ENV variables like this:

```
- name: copy folder to the server
  local_action: >
    command
    rsync -lrpt
    --exclude=.git
    $SRC
    {{ inventory_hostname }}:/path/to/the/folder
  environment:
    SRC: "/a/folder name/with spaces/"

```

Works great, but only for self-composed shell commands.

**Comment by nathanhruby** [comment]
Hi,

After an upgrade to 1.6.10 I now see failures from command module when trying to use a directory name with spaces in for chdir= or creates=.  

This did not occur fir me in 1.6.6 or 1.6.8 that I can tell, so possibly not related, or possibly a side effect of other var changes that created this issue?

Here's a sample playbook to illustrate

``` yaml
---
- name: test a dir with spaces
  hosts: all
  vars:
    - space_path: "/tmp/pigs in spaaaaace"
  tasks:
    # works
    - file: state=directory path="{{ space_path }}"

    # works
    - stat: path="{{ space_path }}"
      register: stat_space_dir
      failed_when: stat_space_dir.isdir is defined and stat_space_dir.isdir == False

    # fails
    - command: /usr/bin/true chdir="{{ space_path }}"
      register: somevar

    # fails
    - command: /usr/bin/false creates="{{ space_path }}"

```
