### ISSUE TITLE
copy / with_first_found creates subdirectory

### ISSUE THREAD

**Issue by BlaM** [ansible/ansible#8140]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7
##### Environment:

Debian Linux Wheezy (both "ansible host" and "target")
##### Summary:

I try to copy a file from the ansible host with "with_first_found", but ansible overwrites the target filename I specify.
##### Steps To Reproduce:

```
- name: php5 config
  action: copy src=files/etc/php5/conf.d/{{item}} dest=/etc/php5/conf.d/interdose.ini
  with_first_found:
    - files:
      - "interdose.{{ ansible_hostname }}.ini"
      - interdose.ini
      paths:
      - files/etc/php5/conf.d/
```
##### Expected Results:

Find the first matched file (either interdose.hostname.ini or interdose.ini) and save it to the server as interdose.ini - no matter what the source file name was.
##### Actual Results:

Ansible _creates_ a subdirectory /etc/php5/conf.d/interdose.ini and stores the found file in there with its original file name. 

I would expect that behaviour if I had put _dest=/etc/php5/conf.d/interdose.ini/{{item}}_. Right now it looks as if I can't set the target filename myself without ansible interfering.
