### ISSUE TITLE
include_role behaves different with global vars and vars on the include block

### ISSUE THREAD

**Issue by Tux12Fun** [ansible/ansible#81402]
### Summary

The Role behaves differnt if I use the playbook vars then wehen using vars on include role
See Examples.

### Issue Type

Bug Report

### Component Name

include_role

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/library']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/etc/ansible/collections']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/library']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 300
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Linux testhost 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

### Steps to Reproduce

Role: ansible_bug --> Contains only this tasks/main.yml

```yaml (paste below)
---
   - set_fact:
        apache_mods: '{{apache_mods + [{"name":item.mod, "state":item.state}] }}'
     with_items:
        - { mod: "info",  state: "absent"  }
        - { mod: "status",state: "absent"  }
        - { mod: "ssl",   state: "present" }

   - fail:
       msg: "{{apache_mods}}"
```

**Works like expected**
---- Playbook ---
```yaml (paste below)
---
- hosts:                         "localhost"
  remote_user:                   root

  vars:
    apache_mods:
          - { name: "php",         state: "present", pkg_name: "libapache2-mod-php8.1" }
          - { name: "headers",     state: "present"  }
          - { name: "rewrite",     state: "present"  }

  tasks:
     - name: "test1"
       include_role:
          name: "ansible_bug"
```
Result:
```
PLAY [localhost] **********************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
ok: [localhost]

TASK [test1] **************************************************************************************************************************

TASK [ansible_bug : set_fact] *********************************************************************************************************
ok: [localhost] => (item={'mod': 'info', 'state': 'absent'})
ok: [localhost] => (item={'mod': 'status', 'state': 'absent'})
ok: [localhost] => (item={'mod': 'ssl', 'state': 'present'})

TASK [ansible_bug : fail] *************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg:
  - name: php
    pkg_name: libapache2-mod-php8.1
    state: present
  - name: headers
    state: present
  - name: rewrite
    state: present
  - name: info
    state: absent
  - name: status
    state: absent
  - name: ssl
    state: present
```

**Is this a Bug?**
---- Playbook ---
```yaml (paste below)
---
- hosts:                         "localhost"
  remote_user:                   root

  tasks:
     - name: "test2"
       include_role:
         name: "ansible_bug"
       vars:
         apache_mods:
           - { name: "php",         state: "present", pkg_name: "libapache2-mod-php8.1" }
           - { name: "headers",     state: "present"  }
           - { name: "rewrite",     state: "present"  }
```
Result:
```
PLAY [localhost] **********************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
ok: [localhost]

TASK [test2] **************************************************************************************************************************

TASK [ansible_bug : set_fact] *********************************************************************************************************
ok: [localhost] => (item={'mod': 'info', 'state': 'absent'})
ok: [localhost] => (item={'mod': 'status', 'state': 'absent'})
ok: [localhost] => (item={'mod': 'ssl', 'state': 'present'})

TASK [ansible_bug : fail] *************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg:
  - name: php
    pkg_name: libapache2-mod-php8.1
    state: present
  - name: headers
    state: present
  - name: rewrite
    state: present
```

### Expected Results

I expected the same result on both Methods

Or does this make a difference for the Variable Scope? 
If so this is not clear in the ansible documentation.

### Actual Results

```console
See the output in the above examples
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/include_role.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/include_role.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/mkrizek/ansibotmini/blob/main/README.md) bot command.

**Comment by flowerysong** [comment]
This does not appear to be a bug. Play vars are a lower precedence than set_fact, while role params are higher precedence. See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence (entries 12, 19, and 20.)

**Comment by Tux12Fun** [comment]
I thought i should use 
```
include_role:
   name:   xy
vars:
     xxx: "yy"
```
for better readabillity then global vars. Is the a way that behaves like global vars to pass values to a included role?
