### ISSUE TITLE
Base64 encoding with carriage return

### ISSUE THREAD

**Issue by axellebot** [ansible/ansible#81475]
### Summary

I'm trying to upload files through [databricks api](https://docs.databricks.com/api/azure/workspace/workspace/import). It works well with postman but wrong with ansible `uri` module.

It looks like the base64 encoding is not done properly with `uri` module.
Using `slurp` module fixed my issue.

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
5.10
```

### Configuration

```console
N/C
```

### OS / Environment

N/C

### Steps to Reproduce

```yaml
- name: "Import '{{ databricks_workspace_import_local_path }}' to workspace '{{ databricks_workspace_import_remote_path }}'"
  uri:
    url: "https://{{ databricks_host }}/api/2.0/workspace/import"
    method: POST
    headers:
      Authorization: "Bearer {{ databricks_bearer_token }}"
    body_format: form-multipart
    remote_src: false # files are on ansible "controller node"
    body:
      path: "{{ databricks_workspace_import_remote_path }}"
      format: "{{ databricks_workspace_import_source }}"
      language: "{{ databricks_workspace_import_language }}"
      content:
        filename: "{{ databricks_workspace_import_local_path }}"
```

### Expected Results

Expecting text/scala/python source code on databricks.

### Actual Results

```console
Having base64 of my file with carriage return on databricks web interface.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/uri.py)
* [`lib/ansible/plugins/action/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/uri.py)
* [`lib/ansible/plugins/test/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/test/uri.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by sivel** [comment]
I cannot replicate this, but the description of the issue is also extremely vague.  I don't understand where the carriage return is missing from. Without more information about how exactly this is being incorrectly encoded or modified, I'm not sure there is enough to go on.

I have a test application I use when testing this written in flask that looks like:

<details>
<summary>Flask app...</summary>
<p>

```python
import hashlib
import base64
import quopri
from io import BytesIO

from flask import Flask, jsonify, request

app = Flask(__name__)

@app.route('/', methods=['POST', 'PUT', 'PATCH'])
def upload_file():
    files = {}
    for key, file in request.files.items():
        cte = file.headers.get('Content-Transfer-Encoding')
        if cte == 'base64':
            contents = base64.b64decode(file.stream.read())
        elif cte in ('7bit', '8bit'):
            output = BytesIO()
            quopri.decode(file.stream, output)
            contents = output.getvalue()
        else:
            contents = file.stream.read()
        files[key] = {
            'filename': file.filename,
            'sha256': hashlib.sha256(contents).hexdigest(),
            'headers': dict(file.headers),
        }
        try:
            files[key]['contents'] = contents.decode()
        except Exception:
            pass

    return jsonify(
        files=files,
        form=request.form,
    )


if __name__ == '__main__':
    app.run(debug=True)
```

</p>
</details>

And with this test file, that includes mixed `\n` and `\r\n`:

```python
import sys\n
var = 'foo'\r\n
print(var)\n
sys.exit(0)\r\n
```

And test playbook:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - stat:
        path: test.py
        checksum_algorithm: sha256
      register: stat_result

    - uri:
        url: http://127.0.0.1:5000
        method: POST
        body_format: form-multipart
        body:
          field1: foo
          content:
            filename: test.py
        remote_src: false
      register: result

    - debug:
        var: result

    - assert:
        that:
          - result.json.files.content.sha256 == stat_result.stat.checksum
```

And the output, confirming the source and what the app decoded are identical:

```
No config file found; using defaults

PLAY [localhost] ***************************************************************

TASK [stat] ********************************************************************
ok: [localhost] => {"changed": false, "stat": {"atime": 1691596202.0479252, "attr_flags": "", "attributes": [], "birthtime": 1691596201.115717, "block_size": 4096, "blocks": 8, "charset": "us-ascii", "checksum": "869c8e776c18a747fd2d80bf4eb4aa4bcd4e927a28a809c893f57f7ebe11eced", "ctime": 1691596201.121499, "dev": 16777230, "device_type": 0, "executable": false, "exists": true, "flags": 0, "generation": 0, "gid": 20, "gr_name": "staff", "inode": 64106660, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "text/plain", "mode": "0644", "mtime": 1691596201.1158698, "nlink": 1, "path": "test.py", "pw_name": "sivel", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 48, "uid": 501, "version": null, "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}

TASK [uri] *********************************************************************
ok: [localhost] => {"changed": false, "connection": "close", "content_length": "474", "content_type": "application/json", "cookies": {}, "cookies_string": "", "date": "Thu, 10 Aug 2023 19:15:34 GMT", "elapsed": 0, "json": {"files": {"content": {"contents": "import sys\nvar = 'foo'\r\nprint(var)\nsys.exit(0)\r\n", "filename": "test.py", "headers": {"Content-Disposition": "form-data; name=\"content\"; filename=\"test.py\"", "Content-Transfer-Encoding": "base64", "Content-Type": "text/x-python"}, "sha256": "869c8e776c18a747fd2d80bf4eb4aa4bcd4e927a28a809c893f57f7ebe11eced"}}, "form": {"field1": "foo"}}, "msg": "OK (474 bytes)", "redirected": false, "server": "Werkzeug/2.1.2 Python/3.10.5", "status": 200, "url": "http://127.0.0.1:5000"}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "result": {
        "changed": false,
        "connection": "close",
        "content_length": "474",
        "content_type": "application/json",
        "cookies": {},
        "cookies_string": "",
        "date": "Thu, 10 Aug 2023 19:15:34 GMT",
        "elapsed": 0,
        "failed": false,
        "json": {
            "files": {
                "content": {
                    "contents": "import sys\nvar = 'foo'\r\nprint(var)\nsys.exit(0)\r\n",
                    "filename": "test.py",
                    "headers": {
                        "Content-Disposition": "form-data; name=\"content\"; filename=\"test.py\"",
                        "Content-Transfer-Encoding": "base64",
                        "Content-Type": "text/x-python"
                    },
                    "sha256": "869c8e776c18a747fd2d80bf4eb4aa4bcd4e927a28a809c893f57f7ebe11eced"
                }
            },
            "form": {
                "field1": "foo"
            }
        },
        "msg": "OK (474 bytes)",
        "redirected": false,
        "server": "Werkzeug/2.1.2 Python/3.10.5",
        "status": 200,
        "url": "http://127.0.0.1:5000"
    }
}

TASK [assert] ******************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by sivel** [comment]
Ok, so looking at the API, it expects that you are publishing a JSON object, where the `content` key is a base64 encoded string of the content.

The `form-multipart` is not going to achieve the goal as stated by the API.

For one thing, when specifying `filename` we read and encode that as base64, but then indicate that the `Content-Transfer-Encoding` is `base64` indicating that the base64 encoding should be stripped to get the content.  The databricks API however expects the actual content to be base64 encoded.

So this is a disconnect between what the API wants, and the data you are ultimately giving it.  I imagine that is why when using `slurp` which will give you the base64 data, and then you are providing that as `content`, it works, since there is no CTE specified for that file/field in the request body.

Based on the API documentation, I believe you would want to do:

```yaml
- name: get base64 of {{ databricks_workspace_import_local_path }}
  slurp:
    path: '{{ databricks_workspace_import_local_path }}'
  register: local_path_data

- name: "Import '{{ databricks_workspace_import_local_path }}' to workspace '{{ databricks_workspace_import_remote_path }}'"
  uri:
    url: "https://{{ databricks_host }}/api/2.0/workspace/import"
    method: POST
    headers:
      Authorization: "Bearer {{ databricks_bearer_token }}"
    body_format: json
    body:
      path: "{{ databricks_workspace_import_remote_path }}"
      format: "{{ databricks_workspace_import_source }}"
      language: "{{ databricks_workspace_import_language }}"
      content: "{{ local_path_data.content }}"
```
