### ISSUE TITLE
show diff when copy all files recursively

### ISSUE THREAD

**Issue by stonebeaver** [ansible/ansible#81476]
### Workaround for https://github.com/ansible/ansible/issues/74947

convert
```yaml
# test.yml
- hosts: all
  tasks:
    - copy:
      src: /tmp/src/
      dest: /tmp/dest/
```
to
```yaml
# test.yml
- hosts: all
  tasks:
    - copy:
      src: "/tmp/src/{{ item.path }}"
      dest: "/tmp/dest/{{ item.path }}"
      with_filetree: /tmp/src/
      when: item.state == 'file'
```

Discussion was closed. Sorry for redundant post.
