### ISSUE TITLE
Usage of `Content-Transfer-Encoding` in HTTP is deprecated

### ISSUE THREAD

**Issue by Mazorius** [ansible/ansible#81523]
### Summary

I had an issue with GitLab by uploading binary files via `ansible.builtin.uri`.

It seems that that module uploads binaries with the help of the `Content-Transfer-Encoding` which was [deprecated in HTTP in 2015](https://datatracker.ietf.org/doc/html/rfc7578#section-4.7).

Due to that GitLab means that this should be fixed on Ansible site.

Here is the issue on GitLab site: https://gitlab.com/gitlab-org/gitlab/-/issues/216067#note_1514173404

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/Users/mustermann/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/mustermann/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Linux and MacOS

### Steps to Reproduce

I upload the appearance images into a freshly installed GitLab.

1. Run GitLab CE inside Docker
1. Create a PAT inside GitLab with admin_mode
1. Execute the Ansible script

```yaml
- name: Set Images in Appearance (application)
  ansible.builtin.uri:
    url: '{{ gitlab_rest_api_url }}/application/appearance'
    method: PUT
    status_code: 200
    headers:
      private-token: '{{ personalAccessToken.stdout }}'
    body_format: form-multipart
    body:
      favicon:
        filename: "{{ gitlab_appearance_image.favicon }}"
        mime_type: image/vnd.microsoft.icon
      header_logo:
        filename: "{{ gitlab_appearance_image.header_logo }}"
        mime_type: image/png
      logo:
        filename: "{{ gitlab_appearance_image.logo }}"
        mime_type: image/svg+xml
```

Uploading via curl and without base64 is fine. See the following playbook:

```yaml
- name: Set Images in Appearance (application)
  command: >-
    curl
    --silent
    --location
    --request PUT
    --header "PRIVATE-TOKEN: {{ personalAccessToken.stdout }}"
    "{{ gitlab_rest_api_url }}/application/appearance"
    --form "favicon=@{{ gitlab_appearance_image.favicon }}"
    --form "header_logo=@{{ gitlab_appearance_image.header_logo }}"
    --form "logo=@{{ gitlab_appearance_image.logo }}"
```

### Expected Results

Images are successfully uploaded.

### Actual Results

```console
Two different behaviours:

### Favicon

The favicon cannot be uploaded as the mime type cannot be checked due to base64 encoding.

### Logo and Header Logo

Are uploaded successfully but cannot be shown as the file content is base64 encoded.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
