### ISSUE TITLE
False negative test result for junit callback

### ISSUE THREAD

**Issue by acmcg** [ansible/ansible#81564]
### Summary

I run a junit callback on my ansible playbooks. However some successfully run playbooks return a failed status 

```xml
<testcase classname="/home/avanoso_admin/myagent/_work/1/s/Deployment/ansible-playbooks/prod/xxxx/activeDirectory.yml:65" name="[yyyy] Active Directory Configuration: Create Standard Users" time="3.089686870574951">
<failure message="All items completed" type="failure">......</failure>
</testcase>
```

These all have loops in the playbook
```YAML
  - name: Create Standard Users
    microsoft.ad.user:
      name: "{{ item.name }}" 
      identity: "{{ item.identity }}" # Must specifiy identity or the code generates and error that object exists
      firstname: "{{ item.firstname }}" 
      surname: "{{ item.surname }}" 
      display_name: "{{ item.display_name }}" 
      company: avanosa
      upn: "{{ item.upn }}" 
      password: placeholderPassword
      update_password: on_create
      state: present
      path: ou=users,ou=lab,dc=xxx,dc=yyy
      groups:
        set:
        - SG-AD-RemoteDeskopUsers
        - Domain Users
      attributes:
        set:
          manager: cn=Andrew McGregor,ou=users,ou=lab,dc=avanosa,dc=local
    loop:
      - { name: "Rock Bogan", identity: "rock.bogan", firstname: "Rock",surname: "Bogan",display_name: "Rock Bogan",upn: "rock.bogan@xxx.local"}
      - { name: "Lance Uppercut", identity: "lance.uppercut", firstname: "Lance",surname: "Uppercut",display_name: "Lance Uppercut",upn: "lance.uppercut@xxx.local"}
      - { name: "Max Power", identity: "max.power", firstname: "Max",surname: "Power",display_name: "Max Power",upn: "max.power@xxx.local"}
```

### Issue Type

Bug Report

### Component Name

junit callback 

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/avanoso_admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/avanoso_admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Linux xxxx 5.15.0-1042-azure #49-Ubuntu SMP Tue Jul 11 17:28:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

```yaml (paste below)
  - name: Create Standard Users
    microsoft.ad.user:
      name: "{{ item.name }}" 
      identity: "{{ item.identity }}" # Must specifiy identity or the code generates and error that object exists
      firstname: "{{ item.firstname }}" 
      surname: "{{ item.surname }}" 
      display_name: "{{ item.display_name }}" 
      company: avanosa
      upn: "{{ item.upn }}" 
      password: placeholderPassword
      update_password: on_create
      state: present
      path: ou=users,ou=lab,dc=xxx,dc=yyy
      groups:
        set:
        - SG-AD-RemoteDeskopUsers
        - Domain Users
      attributes:
        set:
          manager: cn=Andrew McGregor,ou=users,ou=lab,dc=avanosa,dc=local
    loop:
      - { name: "Rock Bogan", identity: "rock.bogan", firstname: "Rock",surname: "Bogan",display_name: "Rock Bogan",upn: "rock.bogan@avanosa.local"}
      - { name: "Lance Uppercut", identity: "lance.uppercut", firstname: "Lance",surname: "Uppercut",display_name: "Lance Uppercut",upn: "lance.uppercut@avanosa.local"}
      - { name: "Max Power", identity: "max.power", firstname: "Max",surname: "Power",display_name: "Max Power",upn: "max.power@avanosa.local"}
```

### Expected Results

Playbook completes successfully, but the junit result says failed

### Actual Results

```console
<testcase classname="/home/avanoso_admin/myagent/_work/1/s/Deployment/ansible-playbooks/prod/xxxx/activeDirectory.yml:65" name="[yyyy] Active Directory Configuration: Create Standard Users" time="3.089686870574951">
<failure message="All items completed" type="failure">......</failure>
</testcase>
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
