### ISSUE TITLE
Suspicion of privilege escalation bug in functionality (No security bug/incident!)

### ISSUE THREAD

**Issue by kwoot** [ansible/ansible#81561]
### Summary

I have a server configured with 2 step security:

1. First I login over ssh as userid@server
2. This user has no sudo rights
3. Next I do: su - admin.userid
4. Enter password here
5. This brings me to a user that has sudo rights
6. Next I do: sudo some command
7. Enter Password here
8. And the command is done with elevated rights.

There is no way I can copy this behavior into a playbook. And belive me I've tried.

My command line is: ansible-playbook -vvv -i 10.1.1.1, -u userid test-pxm.yml -kK

### Issue Type

Bug Report

### Component Name

become

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/jeroen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
<nothing>
```

### OS / Environment

Debian 11.7

### Steps to Reproduce

```yaml (paste below)
---

- name: Playbook to test privilege escalation on Proxmox server
  hosts: all

  become: true
  become_method: su
  become_flags: " "
  become_user: "myuserid"

  tasks:

  - name: Test if we can connect to the Proxmox server
    ping:
    register: result    

  - debug:
      var: result

  - name: Gather the package facts
    package_facts:
      manager: auto

  - name: Try to get a list of created vm's
    become: true
    become_method: sudo
    become_flags: " -H -n  "
    become_user: "admin.{{ ansible_user_id }}"
    shell:
      cmd: /sbin/qm list
    register: result

  - debug:
      var: result
```

### Expected Results

I expect to see a list of virtual machines defined in this case. But any executable would be fine.

### Actual Results

```console
https://gist.github.com/kwoot/5b68cc6fc60217b3369ffe73f2e3d59c
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
