### ISSUE TITLE
Support piped stdin for raw commands

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible#81570]
### Summary

I am trying to run raw SSH commands on Palo Alto firewall appliances. These firewalls support SSH, but do not support the SSH command line syntax i.e.

`ssh user@appliance debug swm info`

will stall out the appliance.

However 

`echo debug swm info | ssh user@appliance`

succeeds. I have encountered other devices and some specialized PC environments with this problem.

In ansible, the underlying command raw uses [_low_level_execute_command](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/__init__.py#L1263) to implement the `raw` module.

This command supports an `in_data` parameter already to pass data via stdin to the executed command. Testing with a custom action module, this properly supports the necessary functionality simply by passing an extra parameter.

The `raw` command should be augmented with an `in_data` or `stdin` parameter which allows populating this variable when making raw calls, and should correctly pass a zero-length string for the `cmd` parameter rather then `None`.

This would fully address the issue, and from a cursory search of common Ansible issues solve many problems with the need to send stdin to remotely executed raw commands.

### Issue Type

Feature Idea

### Component Name

raw

### Additional Information

A practical example for doing an in-line identification of an appliance:

```yaml
- name: Check whether this is a Palo Alto firewall appliance
  raw:
    stdin: debug swm info
  register: palo_alto_check
  vars:
    ansible_connection: ssh

- set_fact:
    device_type: "PANOS"
  when: palo_alto_check.stdout|default("") is regex("\s*PAN Image information.*")
```

Unlock an SSH LUKS-crypt system which simply prompts for a password when connected to:

```yaml
- name: Unlock remote server disk
  raw:
    stdin: "{{ luks_master_key }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
