### ISSUE TITLE
Add `key_content` option to `git` module

### ISSUE THREAD

**Issue by ivanov17** [ansible/ansible#81598]
### Summary

I would like to have a `key_content` option for the `git` module in addition to the existing `key_file` option.

Currently, if I need to fetch any private repository, I also need to store the private key as the file on a remote machine. If I no longer need to update this repository, for example if I check it out to a temporary directory, I don't need to permanently store the private key. In result, I should to delete key file if I don't need it anymore. It increases the number of actions and breaks the idempotency.

If there was a `key_content` option in the `git` module, I could read the contents of the private key from disk, store it in a variable, and use it on the remote host only once, without copying it.

This change should not break any existing workflows.

### Issue Type

Feature Idea

### Component Name

git

### Additional Information

```yaml (paste below)
- ansible.builtin.tempfile:
    state: directory
  register: tmp_dir

- ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ tmp_dir.path }}"
    version: "{{ repo_version }}"
    single_branch: yes
    key_content: "{{ lookup('ansible.builtin.file', '~/.ssh/id_ed25519') }}"
    accept_hostkey: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
