### ISSUE TITLE
Faster package updates with ansible.builtin.dnf when specifying multiple packages

### ISSUE THREAD

**Issue by tomkivlin** [ansible/ansible#81596]
### Summary

I am managing RHEL servers using Ansible, and have noticed that the `ansible.builtin.dnf` module is particularly slow when specifying multiple packages, compared to converting the list of packages to a string and using the `ansible.builtin.shell` module.

I wonder if the "Updating Subscription Management Repositories" part is being done each time rather than just once as per the faster approach?

I've tested this both when the packages are in place (i.e. "Nothing to do") and also when they aren't and they need installing.  The difference is similar with both.  The examples below are for installing.

### Issue Type

Feature Idea

### Component Name

dnf

### Additional Information

```yaml
- name: Install useful tools
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.tools }}"
```

is much slower (~4x) than

```yaml
- name: Install useful tools
  ansible.builtin.shell: dnf install -y {{ packages.tools | join(' ') }}
```

The timings of each are:

```bash
kvm-setup : Install useful tools ----------------------------------- 28.90s

vs

kvm-setup : Install useful tools ----------------------------------- 7.39s
```

For both, the vars are:

```yaml
packages:
  tools:
    - jq
    - tar
    - wget
    - bind-utils
    - nmstate
```

(Yes, I did uninstall the packages before each run.)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dnf.py)
* [`lib/ansible/plugins/action/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/dnf.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by tomkivlin** [comment]
Just to add, there is very little difference when dealing with just one package - it's only with multiple packages the difference is noticed.

**Comment by mkrizek** [comment]
```yaml
- name: Install useful tools
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.tools }}"
```

It is expected that this will be slower as it is running the `dnf` module once per each item in the list. Since the `name` parameter takes a list it will be more efficient to pass the list directly instead of looping over it:

```yaml
- name: Install useful tools
  ansible.builtin.dnf:
    name: "{{ packages.tools }}"
    state: present
```

That way the `dnf` module is executed just once.

**Comment by tomkivlin** [comment]
Ahhh amazing.  Thanks for that - I hadn't realised.  Confirmed, this is much quicker:

```yaml
- name: Install useful tools
  ansible.builtin.dnf:
    name: "{{ packages.tools }}"
    state: present
```

results in

```bash
kvm-setup : Install useful tools -------------------------------------------- 9.40s
```
