### ISSUE TITLE
name clash of global var and var in include breaks interpolation

### ISSUE THREAD

**Issue by cigor** [ansible/ansible#816]
Assume the following playbooks:

--- test1.yml

```
- name: included subtask
  action: command echo $myvar
```

-- test.yml

```
- name: test playbook
  vars:
    myvar: somevalue
  user: root
  hosts: all
  tasks:
   - include: test1.yml myvar=$myvar
```
## 

The included tasks will not have $myvar replaced (it stays as the literal $myvar). 
If instead of myvar=$myvar one uses myvar=${myvar}_test (or some other expression), ansible-playbook will exit with
ERROR: template recursion depth exceeded

This seems fragile and counterintuitive to me.

This is with git rev 093bbd1c825458fbe4acdcd9b0290d30e9942cff from Aug-09-2012
