### ISSUE TITLE
Creating a windows VM using community.vmware.vmware_guest module and a template creates "Authenticated Users"

### ISSUE THREAD

**Issue by SagunShrestha404** [ansible/ansible#81654]
### Summary

Creating a windows VM using community.vmware.vmware_guest module and a template adds "Authenticated Users" to P drive and E drive with modify and write permissions. Standard VM build using template does not have this issue.

### Issue Type

Bug Report

### Component Name

community.vmware.vmware_guest 

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, May 31 2023, 12:21:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Windows server 2019

### Steps to Reproduce

```yaml (paste below)
 - name: Clone the template for NSSC
    community.vmware.vmware_guest:
    # Cloning a VM in NSSC and adding a server to a folder
      hostname: "{{ vCenterServerName }}"
      username: "{{ AD_username }}"
      password: "{{ AD_password }}"
      validate_certs: false
      name: "{{ NewServerName | upper }}"
      template: "{{ TemplateToUse }}"
      datacenter: "{{ DatacenterTobuildVM }}"
      folder: "{{ folderTobuildVM }}"
      cluster: "{{ clusterTobuildVM }}"
      datastore: "{{ datastoreTobuildVM }}"
      state: present
      wait_for_ip_address: true
      wait_for_customization: true
      # Setting up network in the newly created VM
      networks:
        - name: "{{ NewVMnetworkName }}"
          ip: "{{ NewVMIP }}"
          netmask: "{{ NewVMMask }}"
          gateway: "{{ NewVMGateway }}"
          type: static
          dns_servers:
            - 10.252.26.1
            - 10.252.34.1
      # Setting up CPU and Memory
      hardware:
        memory_mb: "{{ req_mem_mb }}"
        num_cpus: "{{ req_total_cpus }}"
        num_cpu_cores_per_socket: "{{ req_num_cpu_cores_per_socket }}"
      # Setting windows default password and time zone
      customization:
        password: "{{ windows_admin_password }}"
        timezone: "015"
        existing_vm: true
      # Adding notes to vmware
      annotation: "Build date: {{ creationdate }}; Builder: {{ builder_name }} "
```

using the above playbook we can create a Windows VM, The template has C:, P: and E: drives. P: and E: drive has "authenticated user" under drive "Group or user names:" in security tab.

### Expected Results

The vm should not have "authenticated user" under drive "Group or user names:" in security tab for P: and E: drive.

### Actual Results

```console
Job completes soccessfully but the "authenticated user" should not have access to P: and E drive.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
