### ISSUE TITLE
Being able to install collections from git via a playbook file

### ISSUE THREAD

**Issue by Julicraft44** [ansible/ansible#81665]
### Summary

Hi there.

Currently, when using ansible collections from git, I need to manually download them via `ansible-galaxy install git+GITREPO` and only after installing them, I can use the collection in a playbook file.
_For example, I need to download a different version or a custom version of a collection to my project._
Moreover, whenever a git repository is getting updated to the latest version, it will not update automatically to the latest version if needed.
I tried using dependencies inside the collection but that didn't worked as planned.

So I would like to be able to install a dependency from a git repo like I could do in a requirements.yml file for ansible-galaxy but just in a playbook file something like I mentioned here.

If there are any other approches that I didn't consider or there is a better way to handle this, I would like to hear about.

### Issue Type

Feature Idea

### Component Name

ansible-galaxy, ansible-playbook

### Additional Information

```yaml
---
- hosts: all
  collections: 
    - name: git+https://github.com/collection/name.git
      type: git
      version: main
      state: present?
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
