### ISSUE TITLE
Support `try-restart` action in systemd_service module

### ISSUE THREAD

**Issue by septatrix** [ansible/ansible#81674]
### Summary

I am deploying systemd service files using ansible. As a handler I tell systemd to restart the service whenever the service file changes. This introduces the side-effect that the service gets started even when it was not previously running.

Systemd provides the action `try-restart` for this scenario which restarts the service iff it is currently running.

A workaround is to query `service_facts` in the handlers though this is fragile if the service did not exist during facts gathering or its state changed since then. An alternative workaround would be to notify two handlers, one of which registers a variable with the service state, though the systemd_service module currently does not support query-only mode (and wants either enabled or state) so this would require a `cmd`...

---

If this is implemented, it would also be great to add other actions like `reload-or-restart` and `try-reload-or-restart` which are currently similarly hard if not even harder to archive..

### Issue Type

Feature Idea

### Component Name

systemd_service

### Additional Information

[systemctl manual](https://www.freedesktop.org/software/systemd/man/systemctl.html#try-restart%20PATTERN%E2%80%A6)

```yaml
- name: Copy systemd service
  ansible.builtin.template:
    src: foobar.service
    dest: /etc/systemd/system/
  notify:
    - Reload systemd daemon
    - Restart foobar service
... 
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart foobar service
  ansible.builtin.systemd:
    name: foobar.service
    # could also be controlled by separate parameter
    state: try-restarted
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
