### ISSUE TITLE
Check run failed to get new state of created directory

### ISSUE THREAD

**Issue by mdaffad** [ansible/ansible#81703]
### Summary

When i try to run playbook with `--check` for playbook with directory creation, the next task is failed because it depends on the directory created from the current task. I use `ansible.builtin.file` with state `directory`

### Issue Type

Bug Report

### Component Name

ansible.modules.file

### Ansible Version

```console
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/mdaffad/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mdaffad/.cache/pypoetry/virtualenvs/redacted-jHOEiURl-py3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /home/mdaffad/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mdaffad/.cache/pypoetry/virtualenvs/redacted-jHOEiURl-py3.9/bin/ansible
  python version = 3.9.18 (main, Aug 25 2023, 13:20:14) [GCC 11.4.0] (/home/mdaffad/.cache/pypoetry/virtualenvs/redacted-jHOEiURl-py3.9/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = None
PAGER(env: PAGER) = less
```

### OS / Environment

Host
Kernel release: `6.2.0-32-generic`
Codename: `jammy`

Target
Kernel release: `5.15.0-79-generic`
Codename: `focal`

### Steps to Reproduce

```yaml
...
tasks:
    - name: Create actions runner directory
      ansible.builtin.file:
        path: /home/user/foo
        state: directory

    - name: Download and untar actions runner program
      shell: |
        curl -o actions-runner-linux-x64-2.309.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.309.0/actions-runner-linux-x64-2.309.0.tar.gz
        tar xzf ./actions-runner-linux-x64-2.309.0.tar.gz
      args:
        chdir: /home/user/foo
...
```

### Expected Results

I expected to have no error, because when i run without `--check` i found no error.

### Actual Results

```console
fatal: [redacted]: FAILED! => {"changed": false, "cmd": "curl -o actions-runner-linux-x64-2.309.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.309.0/actions-runner-linux-x64-2.309.0.tar.gz\ntar xzf ./actions-runner-linux-x64-2.309.0.tar.gz\n", "delta": null, "end": null, "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: b'/home/user/foo'", "rc": null, "start": null, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by mkrizek** [comment]
This is working as intended. The second task should be run only if the first task wasn't skipped by adding a conditional like so:
```yaml
...
tasks:
    - name: Create actions runner directory
      ansible.builtin.file:
        path: /home/user/foo
        state: directory
      register: r

    - name: Download and untar actions runner program
      shell: |
        curl -o actions-runner-linux-x64-2.309.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.309.0/actions-runner-linux-x64-2.309.0.tar.gz
        tar xzf ./actions-runner-linux-x64-2.309.0.tar.gz
      args:
        chdir: /home/user/foo
      when: not r is skipped
...
```

Ansible does not keep state, the second task is not aware of the result of the first task. It has to be explicitly added to the playbook.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
