### ISSUE TITLE
when use package module on centOS 8, ansible_pkg_mgr use yum and report error

### ISSUE THREAD

**Issue by pcleon** [ansible/ansible#81702]
### Summary

my previous playbook write with package module on centos7
now i run it under centos 8 but get something wrong
i found ansible use yum as default ansible_pkg_mgr under centos8
but there's not python lib with yum on centos8, so it occur ImportError, there is the code in [ansible/modules/yum.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/yum.py) at line 420 and 1700
```
try:
    import yum
    HAS_YUM_PYTHON = True
except ImportError:
    HAS_YUM_PYTHON = False
.......
       error_msgs = []
        if not HAS_RPM_PYTHON:
            error_msgs.append('The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.')
        if not HAS_YUM_PYTHON:
            error_msgs.append('The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.')
```
i don't want to change my module package to dnf ,because it compatible with other system
can it  change ansible_pkg_mgr default yum to dnf on centos8？

### Issue Type

Bug Report

### Component Name

yum,dnf,package

### Ansible Version

```console
$ ansible --version
2.14.9
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

centOS 8

### Steps to Reproduce

```yaml (paste below)
ansible localhost -m setup  -a "filter=ansible_pkg_mgr"
| SUCCESS => {
    "ansible_facts": {
        "ansible_pkg_mgr": "yum",
        "discovered_interpreter_python": "/usr/bin/python3.6"
    },
    "changed": false
}

ansible localhost -m package -a "name=mtr" -b
| FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.6"
    },
    "changed": false,
    "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."
}
```

### Expected Results

| SUCCESS => {
    "ansible_facts": {
        "ansible_pkg_mgr": "yum",
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false
}

### Actual Results

```console
| FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.6"
    },
    "changed": false,
    "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
