### ISSUE TITLE
Add commit/push capability to git module

### ISSUE THREAD

**Issue by vwbusguy** [ansible/ansible#81708]
### Summary

I have a few cases where I interact with git repos with Ansible, using the ansible.builtin.git to clone and pull from git repositories.  Occasionally, I also push to a git repository from a playbook, but am currently using shell to do the push.  It would be great for consistency for the builtin git module to have the capability to commit/push to the remote repository when there have been changes to the git repository on the remote.

### Issue Type

Feature Idea

### Component Name

git

### Additional Information

What I'm currently doing as a workaround for this missing functionality (it's not very pretty):

```yaml (paste below)
    - name: Tell git all about you
      ansible.builtin.shell: 
        cmd: "git config user.email {{ tower_user_email }} && git config user.name {{ tower_user_name }}"
        chdir: ./some_repo
        
    - name: Commit changes
      ansible.builtin.shell: 
        cmd: "git commit -am \"Committing detected zone changes \" && GIT_SSH_COMMAND='ssh -i {{ lookup(\"env\", \"JOB_SSH_KEY\") }} -o IdentitiesOnly=yes -oStrictHostKeyChecking=no' git push"
        chdir: ./some_repo
      when: git_diff.stdout | int > 0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
