### ISSUE TITLE
Random vars evaluated twice

### ISSUE THREAD

**Issue by yanghua-ola** [ansible/ansible#81723]
### Summary

With below playbook, the `confirm_code` variable would be evaluated twice, making the equality check fail unconditionally. Suspect it to be a side effect of `vars_prompt`
```
- name: Require confirmation
  hosts: localhost
  vars:
    confirm_code: "{{ lookup('community.general.random_string', length=6, upper=false, special=false) }}"
  vars_prompt:
    - name: input_code
      prompt: |
        Your are making changes to production servers.
        Please type "{{ confirm_code }}" to confirm.
      private: true
  gather_facts: false
  tasks:
    - name: Abort
      ansible.builtin.fail:
        msg: "Input {{ input_code }} does not match {{ confirm_code }}, abort"
      when: input_code != confirm_code
```

### Issue Type

Bug Report

### Component Name

vars_prompt

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.4]
  config file = /Users/yanghua/repos/pt-migration/ansible.cfg
  configured module search path = ['/Users/yanghua/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/yanghua/.local/share/virtualenvs/pt-migration-PYQ9SW8S/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/yanghua/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/yanghua/.local/share/virtualenvs/pt-migration-PYQ9SW8S/bin/ansible
  python version = 3.9.18 (main, Aug 24 2023, 21:32:48) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/yanghua/.local/share/virtualenvs/pt-migration-PYQ9SW8S/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/Users/yanghua/repos/pt-migration/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/yanghua/repos/pt-migration/ansible.cfg) = True
CACHE_PLUGIN(/Users/yanghua/repos/pt-migration/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/yanghua/repos/pt-migration/ansible.cfg) = ~/ansible_facts
CONFIG_FILE() = /Users/yanghua/repos/pt-migration/ansible.cfg
DEFAULT_GATHERING(/Users/yanghua/repos/pt-migration/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/Users/yanghua/repos/pt-migration/ansible.cfg) = ['/Users/yanghua/repos/pt-migra>
DEFAULT_JINJA2_NATIVE(/Users/yanghua/repos/pt-migration/ansible.cfg) = True
DEFAULT_LOG_PATH(/Users/yanghua/repos/pt-migration/ansible.cfg) = /Users/yanghua/repos/pt-migratio>
DEFAULT_STDOUT_CALLBACK(/Users/yanghua/repos/pt-migration/ansible.cfg) = ansible.posix.debug
DEFAULT_TIMEOUT(/Users/yanghua/repos/pt-migration/ansible.cfg) = 40
DEFAULT_VAULT_IDENTITY_LIST(/Users/yanghua/repos/pt-migration/ansible.cfg) = ['private@~/.vault/pr>
HOST_KEY_CHECKING(/Users/yanghua/repos/pt-migration/ansible.cfg) = False

CACHE:
=====

jsonfile:
________
_uri(/Users/yanghua/repos/pt-migration/ansible.cfg) = /Users/yanghua/ansible_facts

CONNECTION:
==========

local:
_____
pipelining(/Users/yanghua/repos/pt-migration/ansible.cfg) = True

paramiko_ssh:
____________
host_key_checking(/Users/yanghua/repos/pt-migration/ansible.cfg) = False
timeout(/Users/yanghua/repos/pt-migration/ansible.cfg) = 40

psrp:
____
pipelining(/Users/yanghua/repos/pt-migration/ansible.cfg) = True

ssh:
___
host_key_checking(/Users/yanghua/repos/pt-migration/ansible.cfg) = False
pipelining(/Users/yanghua/repos/pt-migration/ansible.cfg) = True
timeout(/Users/yanghua/repos/pt-migration/ansible.cfg) = 40

winrm:
_____
pipelining(/Users/yanghua/repos/pt-migration/ansible.cfg) = True

SHELL:
=====

sh:
__
remote_tmp(/Users/yanghua/repos/pt-migration/ansible.cfg) = /tmp
```

### OS / Environment

Mac OS 13.5.2, Macbook 16 Intel

### Steps to Reproduce

```yaml (paste below)
- name: Require confirmation
  hosts: localhost
  vars:
    confirm_code: "{{ lookup('community.general.random_string', length=6, upper=false, special=false) }}"
  vars_prompt:
    - name: input_code
      prompt: |
        Your are making changes to production servers.
        Please type "{{ confirm_code }}" to confirm.
      private: true
  gather_facts: false
  tasks:
    - name: Abort
      ansible.builtin.fail:
        msg: "Input {{ input_code }} does not match {{ confirm_code }}, abort"
      when: input_code != confirm_code
```

### Expected Results

Expect `confirm_code` to be initialized once only

### Actual Results

```console
Your are making changes to production servers.
Please type "mggq27" to confirm.
: 

PLAY [Require confirmation] ***********************************************************************

TASK [Abort] **************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

Input mggq27 does not match f2h52j, abort

PLAY RECAP ****************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
