### ISSUE TITLE
Add a simple way to verify fingerprint and checksum of keys downloaded by/for deb822_repository

### ISSUE THREAD

**Issue by coderjoe** [ansible/ansible#81731]
### Summary

**Describe the new feature/improvement**

I would like to be able to specify a fingerprint, checksum, or both to be used to validate that the GPG keyring fetched using a url in signed_by of `ansible.builtin.deb822_repository` is the keyring that is expecetd.

**Provide examples of real-world use cases that would enable and how it solves the problems**

Not all of my clients allow me to use ansible-galaxy packages in their implementations. But nearly all of them require that I install at least one PPA.

The two most common PPAs being the microsoft PPA and the 1password PPA.

Both provide me keys to download and parameters I could use to verify those keys beyond just trusting the SSL connection. In most cases my clients request I validate the keys in some manner so they are aware if the keys change.

**How do you solve this now?**

1. Downloading the file with `ansible.builtin.get_url` and checking the checksum if needed
2. Writing a series of piped commands into an `ansible.builtin.shell` to convert ASCII armored keys to gpg keys if necessary
3. More shell to fetch the fingerprint from the downloaded key
4. Validation steps to halt processing if the keys do not match (using community.crypto.gpg_fingerprint if the client allows or via more complicated shell scripts if they do not)
5. Then finally use of `deb822_repository` to add the repository if and only if the prior steps have not failed

This then gets copy/pasted across projects and client integrations as needed based on their requests.
I have contemplated spinning up an `ansible-galaxy` collection which contains help for key download and verification, but so far all my clients have requested I avoid non-standard collections making it difficult for me to justify spending the time.

**Could there be a different approach to solving this issue**

1. I could do as described above and implement key checking as a series of commands storing output to variables. 
2. I could continue to try and covince my clients to let me use `community.crypto.gpg_fingerprint` lookup to get the value to check against.
3. A separate/new module could be created with the express intent of working with GPG keys either in files or from URLs which itself handles fingerprints and/or checksums

### Issue Type

Feature Idea

### Component Name

ansible.builtin.deb822_repository

### Additional Information

I would love to be able to verify by checksum, by short fingerprint, long fingerprint, or both checksum and fingerprint.

```yaml (paste below)
- name: Validate a remote gpg key by checksum
  ansible.builtin.deb822_repository:
    name: example
    types: deb
    uris: https://pkgs.example.com/linux/debian
    suites stable
    components: main
    architectures: amd64
    signed_by: https://downloads.example.com/linux/debian/example-archive.asc
    verify_key_checksum: sha256sum:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
    
- name: Validate a remote gpg key by short fingerprint
  ansible.builtin.deb822_repository:
    name: example
    types: deb
    uris: https://pkgs.example.com/linux/debian
    suites stable
    components: main
    architectures: amd64
    signed_by: https://downloads.example.com/linux/debian/example-archive.asc
    verify_key_fingerprint: DEADBEEFDEADBEEF

- name: Validate a remote gpg key by long fingerprint
  ansible.builtin.deb822_repository:
    name: example
    types: deb
    uris: https://pkgs.example.com/linux/debian
    suites stable
    components: main
    architectures: amd64
    signed_by: https://downloads.example.com/linux/debian/example-archive.asc
    verify_key_fingerprint: DEADBEEF0000DEADBEEF0000DEADBEEF00000000

- name: Validate both the checksum and the fingerprint
  ansible.builtin.deb822_repository:
    name: example
    types: deb
    uris: https://pkgs.example.com/linux/debian
    suites stable
    components: main
    architectures: amd64
    signed_by: https://downloads.example.com/linux/debian/example-archive.asc
    verify_key_checksum: sha256sum:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
    verify_key_fingerprint: DEADBEEF0000DEADBEEF0000DEADBEEF00000000

- name: Validation should also work if the key was previously fetched and is stored in a file
  ansible.builtin.deb822_repository:
    name: example
    types: deb
    uris: https://pkgs.example.com/linux/debian
    suites stable
    components: main
    architectures: amd64
    signed_by: /usr/share/keyrings/example-archive-keyring.gpg
    verify_key_checksum: sha256sum:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
    verify_key_fingerprint: DEADBEEF0000DEADBEEF0000DEADBEEF00000000
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by sivel** [comment]
We've talked about this and have decided that this isn't something we plan to change in the module.  Modules that make HTTP requests only provide the minimal functionality, and for anything more complex using `get_url` is needed.

There seems to be a misconception that you need to convert the keys, which you don't.  The keys must be named with either `.asc` or `.gpg` to denote ascii armored or not.  This module doesn't touch them at all, it just inspects them to determine the proper file extension.

```yaml
- get_url:
    url: https://downloads.example.com/linux/debian/example-archive.asc
    dest: /etc/apt/keyrings/example-archive.asc
    mode: "0644"
    checksum: sha256:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
    
- deb822_repository:
    name: example
    types: deb
    uris: https://pkgs.example.com/linux/debian
    suites: stable
    components: main
    architectures: amd64
    signed_by: /etc/apt/keyrings/example-archive.asc
```

As far as verifying the fingerprint, with the above we don't believe this is necessary.  This can be a manual thing done when deciding to use the gpg key to begin with.
