### ISSUE TITLE
Adds the feature to create parent directories during file copying.

### ISSUE THREAD

**Issue by nuno-andre** [ansible/ansible#81760]
### Summary

Currently, to copy a file (or a folder) to a folder that doesn't exist, it's necessary to create it previously. It would be very convenient to have an option to create these directories automatically. E.g. through a `parents` boolean parameter (as in `Path.mkdir`).

It would also be convenient to add a `recurse` option (as in `file`) to _recursively set the specified file attributes on directory contents_.

> [!NOTE]
> This option could also be useful for other modules (such as `template`)

### Issue Type

Feature Idea

### Component Name

copy

### Additional Information

Currently:
```yaml
- ansible.builtin.file:
    path: /tmp/dest/folder
    recurse: true
    state: directory
    mode: 0o644

- ansible.builtin.copy:
    src: foo.conf
    dest: /tmp/dest/folder/foo.conf
    mode: 0o644
```

Proposed:
```yaml
- ansible.builtin.copy:
    src: foo.conf
    dest: /tmp/dest/folder/foo.conf
    parents: true
    recurse: true
    mode: 0o644
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
