### ISSUE TITLE
Ansible galaxy fails to install role - ERROR! Unexpected Exception, this is probably a bug: 'LooseVersion' object has no attribute 'version'

### ISSUE THREAD

**Issue by idolize** [ansible/ansible#81832]
### Summary

When I try to run `ansible-galaxy install -r requirements.yml -vvv` I get an exception with one of my dependencies.

Originally the dependency ([`idolize.dotfiles_stow` role](https://galaxy.ansible.com/ui/standalone/roles/idolize/dotfiles_stow/)) had no version number or git tags, but I also tried adding a git tag of `1.0.0` and that didn't appear to help.

### Issue Type

Bug Report

### Component Name

galaxy.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.2]
  config file = /Users/idol/Dev/home-infra/ansible.cfg
  configured module search path = ['/Users/idol/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/idol/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CACHE_PLUGIN(/Users/idol/Dev/home-infra/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/idol/Dev/home-infra/ansible.cfg) = .fact_cache
CACHE_PLUGIN_TIMEOUT(/Users/idol/Dev/home-infra/ansible.cfg) = 43200
CONFIG_FILE() = /Users/idol/Dev/home-infra/ansible.cfg
DEFAULT_FORKS(/Users/idol/Dev/home-infra/ansible.cfg) = 32
DEFAULT_GATHERING(/Users/idol/Dev/home-infra/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/Users/idol/Dev/home-infra/ansible.cfg) = merge
DEFAULT_HOST_LIST(/Users/idol/Dev/home-infra/ansible.cfg) = ['/Users/idol/Dev/home-infra/inventory/hosts.yml']
DEFAULT_TIMEOUT(/Users/idol/Dev/home-infra/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/Users/idol/Dev/home-infra/ansible.cfg) = /Users/idol/Dev/home-infra/vault-decode-keychain.sh
EDITOR(env: EDITOR) = code -w

CACHE:
=====

jsonfile:
________
_timeout(/Users/idol/Dev/home-infra/ansible.cfg) = 43200
_uri(/Users/idol/Dev/home-infra/ansible.cfg) = /Users/idol/Dev/home-infra/.fact_cache

CONNECTION:
==========

paramiko_ssh:
____________
timeout(/Users/idol/Dev/home-infra/ansible.cfg) = 30

ssh:
___
pipelining(/Users/idol/Dev/home-infra/ansible.cfg) = True
timeout(/Users/idol/Dev/home-infra/ansible.cfg) = 30
```

### OS / Environment

macOS 13.5.2

### Steps to Reproduce

```yaml (paste below)
# requirements.yml
roles:
  - name: idolize.dotfiles_stow
```

Run `ansible-galaxy install -r requirements.yml`

### Expected Results

Install correctly like other roles

### Actual Results

```console
Processing role idolize.dotfiles_stow
Opened /Users/idol/.ansible/galaxy_token
- downloading role 'dotfiles_stow', owned by idolize
ERROR! Unexpected Exception, this is probably a bug: 'LooseVersion' object has no attribute 'version'
the full traceback was:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/cli/__init__.py", line 659, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 715, in run
    return context.CLIARGS['func']()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 117, in method_wrapper
    return wrapped_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1363, in execute_install
    self._execute_install_role(role_requirements)
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/cli/galaxy.py", line 1449, in _execute_install_role
    installed = role.install()
                ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/galaxy/role.py", line 275, in install
    loose_versions.sort()
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/module_utils/compat/version.py", line 60, in __lt__
    c = self._cmp(other)
        ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/module_utils/compat/version.py", line 336, in _cmp
    if self.version == other.version:
                       ^^^^^^^^^^^^^
AttributeError: 'LooseVersion' object has no attribute 'version'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/cli/galaxy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/galaxy.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by s-hertel** [comment]
We should fix the unhandled traceback to give a better error. A workaround is to install the specific version you want: `ansible-galaxy install idolize.dotfiles_stow,1.0.0`.

It looks like there's a version `None` published. You can use `ansible-galaxy role delete github_user github_repo` to remove both versions before importing the correct one again.

It doesn't look like galaxy.ansible.com does much validation of role versions, but a version `None` will never be installable using `ansible-galaxy` after a second is published, because the version in `ansible-galaxy install idolize.dotfiles_stow,None` is interpreted as the string 'None' and will never match Python `None`...

**Comment by idolize** [comment]
That's weird that it shows a version None (I never did that on my end).

I think the genesis of this is because I renamed the repository on GitHub. After doing that other issues started happening.

**Comment by s-hertel** [comment]
I don't think it's directly related to the rename. Importing a role with no tags, ends up publishing a version `None`. I opened a PR to support this #81849.

**Comment by bsmeding** [comment]
same issue, not affected with renaming files

something is changed in the galaxy redirect. Everything works ok couple of days ago now no longer possible to install files from galaxy. Even from CLI (Ansible 2.13 and 2.14 tested) `ansible-galaxy collection install .....` does not work

install direct from git+link still works

**Comment by xbufu** [comment]
I'm encountering the same issue when trying to install roles. Going back to the old galaxy server is what fixed it for me, so it seems to be an issue with the new galaxy?

```ini
[galaxy]
server = https://old-galaxy.ansible.com
```

**Comment by bsmeding** [comment]
@s-hertel yes generated today because of new upload of role version to galaxy, now the role install works again

**Comment by bsmeding** [comment]
I generated a new one on the new galaxy server because i needed to update an galaxy role of mine

Logging in to 'old-galaxy' is not working

Please try to add to 'ansible.cfg' file:

'''
[galaxy]
server = https://old-galaxy.ansible.com
'''

**Comment by xbufu** [comment]
@bsmeding Ah okay that was my previous workaround as well. My final solution now was to simply add a `latest` tag to all commits on my role repository, since the new galaxy won't work without a tag. Still not that elegant, since you have to first delete the role from the galaxy before importing again, as you can't import the same tag twice, but it works for my use case. 

Here is my workflow file if someone needs it. It requires your galaxy API key as `GALAXY_API_KEY` secret and a Github token as `RELEASE_TOKEN` to create the new tag. Also make sure to set your role name instead of `xbufu.base_vm`.

```yml
---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
'on':
  push:
    branches:
      - 'main'

defaults:
  run:
    working-directory: 'xbufu.base_vm'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'xbufu.base_vm'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'xbufu.base_vm'

      - name: Create latest release
        uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          makeLatest: true
          token: ${{ SECRETS.RELEASE_TOKEN }}

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Delete previous role release.
        run: >-
          ansible-galaxy role delete --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
```
