### ISSUE TITLE
Custom task status messages

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#81881]
### Summary

A feature for making playbook output more informative, while saving cycles on debug tasks. A new keyword `status_msg` for task that would work in the same var context as `failed_when`, `changed_when`, etc.
If defined, this string would be evaluated/templated and displayed after the task (or loop iteration) is completed.

```yaml
- name: check some status
  command: /bin/my-status-reporter
  register: run_status
  failed_when: no
  status_msg: |
    Result: {{ 'OK' if run_status.rc == 0 else 'FAIL' }} ({{ run_status.rc }})
    Notes:
    {% for line in run_status.stdout_lines if 'NOTE:' in line %}
      {{ line }}
    {% endfor %}
```
Potentially another keyword `loop_status_msg` that would be evaluated after task loop is completed, with access to registered `results` list. 

evaluated `status_msg` can also be made accessible in registered var for later tasks.

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

```
TASK [some-role : check some status] ****
ok: [host.example.com] => 
  status_msg: |
    Result: OK (0)
    Notes:
      NOTE: check logs
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
