### ISSUE TITLE
Unexpected intersection targeting hosts and groups

### ISSUE THREAD

**Issue by RussTech** [ansible/ansible#81908]
### Summary

defining hosts with a leading intersection operator will run against all hosts in the group.   

```
hosts: :&groupname
```

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
$ ansible --version
ansible-playbook [core 2.15.0]
ansible-playbook [core 2.12.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL 8, Windows 

### Steps to Reproduce

```yaml (paste below)
- name: test play
  hosts: :&groupname
  gather_facts: true

  tasks:

  - name: debug hostvars
    debug:
      msg: "debugging"

```

### Expected Results

I would expect the play to fail because the intersection of Null or "" with should not be valid.  
I would also expect the play to match no hosts because the intersection of "" with groupname hosts should match no hosts.  

### Actual Results

```console
play ran against all hosts in groupname
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
