### ISSUE TITLE
command/shell should have a "negative" failed_when exception

### ISSUE THREAD

**Issue by nerdoc** [ansible/ansible#81963]
### Summary

I started with ansible, and frequently am running in situations where I am missing a feature, when command outputs suggest an error (and ansible stops processing), but *this* kind of error is one I want to ignore.

Example (for adding a domain to an [Uberspace](https://uberspace.de) account:
```yaml
- name: add domain
  command: "uberspace web domain add {{ domain_name }}"
```
The resulting error, if the domain was already added in runs before, is:
```
fatal: [medspeak.io]: FAILED! => {"changed": true, "cmd": ["uberspace", "web", "domain", "add", "example.com"],
 "delta": "0:00:08.713625", "end": "2023-10-12 08:07:23.119196", "msg": "non-zero return code", "rc": 1, "start": 
"2023-10-12 08:07:14.405571", "stderr": "Can't add domain to the configuration. It is already configured for 
your Uberspace account.", "stderr_lines": ["Can't add domain to the configuration. It is already configured for 
your Uberspace account."], "stdout": "", "stdout_lines": []}
```

In this case I want to **not** fail when e.g. "It is already configured for your Uberspace account" is part of the result. I would expect to be able to write something like:
```yaml
- name: add domain
  command: "uberspace web domain add {{ domain_name }}"
  register: result
  not_failed_when: "'It is already configured for your Uberspace account' in result"
```

Maybe I'm still using ansible the wrong way, but I think this is an useful feature. Correct me if I'm wrong.

### Issue Type

Feature Idea

### Component Name

command, shell

### Additional Information

With this feature, it would be easier to filter out some command outputs that suggest errors, but can be ignored in this special case. `ignore_errors` is binary, ignores all of them and is not helpful here. `failed_when` is possible to use here, but it is cumbersome, with double negations:

```yaml
  failed_when: (result.rc != 0) and ("It is already configured for your Uberspace account." not in result.stderr)
  changed_when: (result.rc == 0) or ("It is already configured for your Uberspace account." not in result.stderr)
```
This could be easily written like this, and more
```yaml
  not_failed_when:
    - "It is already configured for your Uberspace account." not in result.stderr
    - result.rc == 5
    - something_other_special_happens
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/command.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/command.py)
* [`lib/ansible/plugins/action/shell.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/shell.py)
* [`lib/ansible/modules/shell.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/shell.py)
* [`lib/ansible/modules/command.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by flowerysong** [comment]
You don't need a new feature to support negation, you can easily build whatever logic you want using `failed_when`.

```yaml
- name: add domain
  command: uberspace web domain add {{ domain_name }}
  register: result
  failed_when:
    - result is failed
    - "'It is already configured for your Uberspace account' not in result"
```

Adding a whole new keyword and having to figure out how it interacts with `failed_when` would be far more cumbersome than just using `not` in your condition.
