### ISSUE TITLE
ansible-test shebang.py docs and code disagree about bash test

### ISSUE THREAD

**Issue by fbicknel** [ansible/ansible#81983]
### WHEREAS
When I try to run `ansible-test --test shebang` against a collection containing a file with the first line of `#!/bin/bash`, it fails with:
```
ERROR: bin/test_a_file.sh:1:1: unexpected non-module shebang: b'#!/bin/bash'
```

#### And

the [documentation](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/shebang.html#shebang) says:
```
shebang
Most executable files should only use one of the following shebangs:

#!/bin/sh

#!/bin/bash

#!/usr/bin/make
```

#### And

 the [code base](https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_util/controller/sanity/code-smell/shebang.py) says:
```
    standard_shebangs = set([
        b'#!/bin/bash -eu',
        b'#!/bin/bash -eux',
        b'#!/bin/sh',
        b'#!/usr/bin/env bash',
        b'#!/usr/bin/env fish',
        b'#!/usr/bin/env pwsh',
        b'#!/usr/bin/env python',
        b'#!/usr/bin/make -f',
    ])
```

#### And

the subject file is:
```
$ head -1 bin/test_a_file.sh
#!/bin/bash
```
### THEREFORE
There is some sort of contradiction. Hopefully that the code base has omitted `#!/bin/bash` from the set above.

### Issue Type

Bug Report

### Component Name

ansible-test

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.5]
  config file = None
  configured module search path = ['/home/<myuserid>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<myuserid>/.pyenv/versions/3.11.6/envs/ve_ansibletest/lib/python3.11/site-packages/ansible
  ansible collection location = /home/<myuserid>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<myuserid>/.pyenv/versions/ve_ansibletest/bin/ansible
  python version = 3.11.6 (main, Oct  9 2023, 15:49:54) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/home/<myuserid>/.pyenv/versions/3.11.6/envs/ve_ansibletest/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
```

### OS / Environment

sh-4.4$ uname -sr
Linux 4.18.0-477.10.1.el8_8.x86_64
sh-4.4$ cat /etc/system-release
Red Hat Enterprise Linux release 8.8 (Ootpa)
sh-4.4$

### Steps to Reproduce

```yaml (paste below)
---
# Didn't quite understand why you wanted this in YAML, so guessed -- maybe a dict? 
Set up a venv to test with: $ pyenv virtualenv 3.11.6 ve_test
Start the venv: $ pyenv activate ve_test
Install ansible: $ pip install ansible
Create a new collection: $ ansible-galaxy collection init sample_fail.ansible_test
Change to your collection: $ cd sample_fail/ansible_test
Create a file to test against: |
  $ cat > test_file.sh <<END
  #!/bin/bash

  echo "This works."
  END
  $ chmod +x test_file.sh
Run ansible-test against the collection: $ ansible-test sanity --test shebang
Observe the carnage: True
Create an ignore file: $ mkdir tests/sanity && echo 'test_file.sh shebang' > tests/sanity/ignore-2.15.txt
Re-run the test the same way: $ ansible-test sanity --test shebang
Observe the carnage: False
```

### Expected Results

I expected this test to pass, since both common sense and the documentation indicate that `#!/bin/bash` is a perfectly legitimate shebang.

### Actual Results

```console
$ ansible-test sanity -vvvv --test shebang
Configured locale: en_US.UTF-8
RLIMIT_NOFILE: (1024, 262144)
Creating container database.
>>> Container Database
{}
Read 0 sanity test ignore line(s) for Ansible 2.15 from: tests/sanity/ignore-2.15.txt
Running sanity test "shebang"
README.md
bin/test_a_file.sh
galaxy.yml
meta/runtime.yml
plugins/README.md
Initializing "/tmp/ansible-test-qptm3_jl-injector" as the temporary injector directory.
Run command with data: /home/<myusername>/.ansible/test/venv/sanity/3.11/4f53cda1/bin/python /home/<myusername>/.pyenv/versions/3.11.6/envs/ve_ansibletest/lib/python3.11/site-packages/ansible_test/_util/controller/sanity/code-smell/shebang.py
Working directory: /home/<myusername>/<mutter>/ansible_collections/sample_fail/ansible_test
Program found: /home/<myusername>/.ansible/test/venv/sanity/3.11/4f53cda1/bin/python
ANSIBLE_COLLECTIONS_PATH=/home/<myusername>/<mutter>
ANSIBLE_CONFIG=/home/<myusername>/.pyenv/versions/3.11.6/envs/ve_ansibletest/lib/python3.11/site-packages/ansible_test/_data/ansible.cfg
ANSIBLE_DEPRECATION_WARNINGS=false
ANSIBLE_DEVEL_WARNING=false
ANSIBLE_FORCE_COLOR=false
ANSIBLE_FORCE_HANDLERS=true
ANSIBLE_HOST_KEY_CHECKING=false
ANSIBLE_HOST_PATTERN_MISMATCH=error
ANSIBLE_INVENTORY=/dev/null
ANSIBLE_LIBRARY=/dev/null
ANSIBLE_PYTHON_MODULE_RLIMIT_NOFILE=1024
ANSIBLE_RETRY_FILES_ENABLED=false
ANSIBLE_TEST_PYTHON_INTERPRETER=/home/<myusername>/.ansible/test/venv/sanity/3.11/4f53cda1/bin/python
ANSIBLE_TEST_PYTHON_VERSION=3.11
ANSIBLE_WORKER_SHUTDOWN_POLL_COUNT=100
ANSIBLE_WORKER_SHUTDOWN_POLL_DELAY=0.1
HOME=/home/<myusername>
LC_ALL=en_US.UTF-8
PAGER=/bin/cat
PATH=/tmp/ansible-test-qptm3_jl-injector:/home/<myusername>/.ansible/test/venv/sanity/3.11/4f53cda1/bin:/tmp/ansible-test-92yv1ba3-bin:/home/<myusername>/.pyenv/versions/ve_ansibletest/bin:/home/<myusername>/.pyenv/libexec:/home/<myusername>/.pyenv/plugins/python-build/bin:/home/<myusername>/.pyenv/plugins/pyenv-virtualenv/bin:/home/<myusername>/.pyenv/plugins/pyenv-update/bin:/home/<myusername>/.pyenv/plugins/pyenv-installer/bin:/home/<myusername>/.pyenv/plugins/pyenv-doctor/bin:/home/<myusername>/.pyenv/shims:/home/<myusername>/.pyenv/bin:/home/<myusername>/bin:/usr/local/bin:/home/<myusername>/.pyenv/bin:/home/<myusername>/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/<myusername>/bin:/home/<myusername>/bin
PYTHONPATH=/tmp/ansible-test-9clynow0
PYTHONUTF8=1
Command exited with status 0 after 0.020501136779785156 seconds.
ERROR: Found 1 shebang issue(s) which need to be resolved:
ERROR: bin/test_a_file.sh:1:1: unexpected non-module shebang: b'#!/bin/bash'
See documentation for help: https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/shebang.html
FATAL: The 1 sanity test(s) listed below (out of 1) failed. See error output above for details.
shebang
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
