### ISSUE TITLE
include_role: Allow non-existing files when using *_from: foo/bar

### ISSUE THREAD

**Issue by Grisu118** [ansible/ansible#81993]
### Summary

We would like to have that, when using `*_from` in `include_role` to behave similar to the default. If the `common.yml` does not exist, simply ignore it, similar to if `main.yml` does not exist.
```yaml
- name: Load common config
  include_role:
    name: "{{ item }}"
    defaults_from: "common"
    handlers_from: "common"
    tasks_from: "common"
    vars_from: "common"
    public: True
  loop:
    - foo
    - bar
```
In the current state, it requires at least an empty `common.yml` in any existing "type" folder. This does not really help with readability. 

The easiest fix would possibly be to not raise an error here, but this might break someone's workflow
[raise AnsibleParserError("Could not find specified file in role: %s/%s" % (subdir, main))](https://github.com/ansible/ansible/blob/5812cabaf53a7c972c73a4e45faa57032e5c1186/lib/ansible/playbook/role/__init__.py#L417)

Another solution would be to add another flag to the `include_role` task, to explicitly enable this new feature. 

Our current workaround is to use additional roles which are then loaded with `include_role`, without the use of `*_from`. But combining this into the same role will improve maintainability of our ansible code. 

### Issue Type

Feature Idea

### Component Name

include_role

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/include_role.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/include_role.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by s-hertel** [comment]
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, as this can already be achieved by using `omit` with the *_from task options and we'd like to avoid adding further complexity to roles. I've added a couple examples of how you could do this, but we thought this use case seemed complicated, so we'd really recommend simplifying your approach instead.

Here's an example using a single task, but it's fragile (to avoid conflicts with internal role lookup precedence, you should include the full path of the role instead of the name):
```yaml
- include_role:
    name: "{{ item }}"
    tasks_from: "{{ lookup('first_found', first_found_params) | default(omit, True) }}"
  vars:
    search_roles: "{{ [playbook_dir, playbook_dir + '/roles'] + lookup('config', 'DEFAULT_ROLES_PATH') }}"
    extensions: "{{ [''] + lookup('config', 'YAML_FILENAME_EXTENSIONS') }}"
    first_found_params:
      files: "{{ extensions | map('regex_replace', '^(.*)$', 'common\\1') | list }}"
      paths: "{{ search_roles | map('regex_replace', '^(.*)$', '\\1' + '/' + item + '/tasks') | list }}"
      skip: True
  loop:
    - foo
    - bar
```

I would instead break this into several tasks:
- use first_found for each role name in the list of roles to include
- for each role that is found, for each *_from subdirectory, determine if the file exists
- for each role that is found, include it (as the full path), and set each *_from field using the found file (or omit if the file didn't exist)

However, we're absolutely always up for discussion.
Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If you or anyone else has any further questions, please let us know by using any of the communication methods listed in the page below:

   * https://docs.ansible.com/ansible/latest/community/communication.html

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
