### ISSUE TITLE
Ansible fails trying to connect remote host and get unreachable issue with exit code -13

### ISSUE THREAD

**Issue by ediz-akarsu** [ansible/ansible#81999]
### Summary

When we are running ansible task, localhost to another remote host we are get unreachable errors intermittently(not reproduceable every time). One task runs on local host and other on remote host. While we are running these task, we are using "remote_tmp=/var/mcp/lock" in ansible.cfg file. 
Also may be we can overcome with using /tmp dir for remote_tmp but i want to use "remote_tmp=/var/mcp/lock"

### Issue Type

Bug Report

### Component Name

setup

### Ansible Version

```console
$ ansible --version
ansible 2.9.9
```

### Configuration

```console
ANSIBLE_NOCOLOR(/etc/ansible/ansible.cfg) = True
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 3
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/var/mcp/raf/commissioning/common/library']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = ['/var/mcp/raf/commissioning/module_utils']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
[ ~]# cat /etc/ansible/ansible.cfg 
[defaults]
ansible_python_interpreter = auto
library = /var/mcp/raf/commissioning/common/library
module_utils = /var/mcp/raf/commissioning/module_utils
gathering = smart
timeout = 60
nocows = True
nocolor = True
remote_tmp = /var/mcp/lock
[ssh_connection]
retries = 3
```

### OS / Environment

RHEL 8

### Steps to Reproduce
```
---
- name: test
  hosts: xxx.xx.xx.xxx
  vars:
    ansible_ssh_user: sysuser
    ansible_ssh_pass: xxxx
    ansible_become: yes               
    ansible_become_method: su     
    ansible_become_password: xxxx
  tasks:
    - name: Uptime check
      command: uptime
```

### Expected Results

changed: [AM11]

### Actual Results

```console
fatal: [AM11]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo /var/mcp/lock `\"&& mkdir /var/mcp/lock/ansible-tmp-1697011485.7946527-2683247-213995000290554 && echo ansible-tmp-1697011485.7946527-2683247-213995000290554=\"` echo /var/mcp/lock/ansible-tmp-1697011485.7946527-2683247-213995000290554 `\" ), exited with result -13", "unreachable": true}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
