### ISSUE TITLE
win_dsc - 'Get-CimClass: Not Found' Error

### ISSUE THREAD

**Issue by BradSherwin** [ansible/ansible#81996]
### Summary

I have a playbook to install SQL Server.  The playbook executes fine on Windows Server 2022 but when I try run the same on Windows 10 it fails with "Get-CimClass: Not Found".

This is validated when I run the below on a fresh Windows 10 box:
```ps1
Install-PackageProvider -Name Nuget -Force

Install-Module -Name SQLServerDSC

$resource = Get-DscResource -Name SQLSetup
Get-CimClass -ClassName $resource.ResourceType -Namespace root\Microsoft\Windows\DesiredStateConfiguration
```

However, if I execute DSC to install a basic SQL instance and then run Get-CimClass...it returns as expected:
```ps1
Set-ExecutionPolicy -ExecutionPolicy bypass

Configuration SQLInstall
{
     Import-DscResource -ModuleName SqlServerDsc

     node localhost
     {
          SqlSetup 'InstallDefaultInstance'
          {
               InstanceName        = 'MSSQLSERVER'
               Features            = 'SQLENGINE'
               SourcePath          = 'E:\'
               SQLSysAdminAccounts = @('Administrators')
          }
     }
}

SQLInstall

Start-DscConfiguration -Path ./SQLInstall -Wait -Force -Verbose

$resource = Get-DscResource -Name SQLSetup
Get-CimClass -ClassName $resource.ResourceType -Namespace root\Microsoft\Windows\DesiredStateConfiguration
```
After doing the above, I can rerun my playbook successfully since the CimClass exists.

I wish I knew what the differences are between Windows Server & Windows 10 when installing the SQLServerDSC but something is a miss.

### Issue Type

Bug Report

### Component Name

win_dsc

### Ansible Version

```console
$ ansible --version

ansible [core 2.15.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/adminuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adminuser/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/adminuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/adminuser/.local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Windows 10 Pro 19045.3570 en-US
Powershell 5.1

### Steps to Reproduce

```yaml (paste below)
---
# Install SQL Server
#
# For a new installation copy the variables found in default/main.yml into /environments/<env>/vars to manage

# - name: Checking if SQL 2022 Developer is installed
#   win_reg_stat:
#     path: HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\160\SQL2022\CurrentVersion
#   register: SQL2022Dev

- name: Install dotNET 4.5
  include_role:
    name: 100-WinFeatures/091-Install-dotNET45
  when: "'Server' in ansible_os_name"

- name: Install SQL 2022 Developer
  block:
  # this block will install sql developer if not found

  - name: Copy the SQL Install ISO
    win_copy:
     src: "{{ cmdb_unc_path.stdout_lines[0] }}\\Software\\Microsoft\\SQL\\SQLServer\\2022\\"
     dest: "C:\\SQLServer\\"
     remote_src: true
    vars:
    # By becoming the account that has the mapped drive it will access credman to access the mapped drive
     ansible_become: true
     ansible_become_method: runas
     ansible_become_user: "{{ ansible_user }}"
     ansible_become_password: "{{ ansible_password }}"

  - name: Install latest Nuget Package
    win_shell: Install-PackageProvider -Name Nuget -Force

  - name: Install SQLServerDSC Module
    win_psmodule:
      name: SQLServerDsc
      state: present
      accept_license: true
      force: true

  - name: Install xNetworking Module
    win_psmodule:
      name: xNetworking
      state: present
      accept_license: true
      force: true

  - name: Install dbatools Module
    win_psmodule:
      name: dbatools
      state: present
      accept_license: true
      force: true

  # Assuming we are allowed to reboot this step will check for pending reboots
  # and execute a reboot, reboot activity can be controlled using the variable mssql_suppress_reboot
  - name: Ensure that a reboot is not pending
    when: ansible_reboot_pending | bool
    debug:
      msg: 'Pending reboot detected'
    changed_when: true
    notify: reboot windows

  - meta: flush_handlers

  - name: Find ISO in downloaded media
    win_find:
      paths: "C:\\SQLServer"
      patterns: '*.iso'
      file_type: file
    register: iso_find

  - name: Mount ISO image of SQL Server
    win_disk_image:
      image_path: "{{ iso_find.files[0].path }}"
      state: present
    register: mount_info

  # If this step fails, logs are in C:\Program Files\Microsoft SQL Server\...\Setup Bootstrap\Log
  # it will often contain the actual error.  If it shows everything passing, the issue is within the DSC logs.
  # In particular completing these steps:
  # https://docs.microsoft.com/en-us/powershell/dsc/troubleshooting#gathering-events-from-a-single-dsc-operation
  # then re-running a failing PowershellDSC job can help you find the source of your error
  # Supported parameters can be found here:
  # https://www.powershellgallery.com/packages/SqlServerDsc/14.2.1/Content/DSCResources%5CDSC_SqlSetup%5Cen-US%5Cabout_SqlSetup.help.txt

  - name: Install SQL Server
    win_dsc:
      resource_name: SQLSetup
      ProductKey: "{{ mssql_product_key }}"
      Action: Install
      UpdateEnabled: True
      SourcePath: "{{ mount_info.mount_paths[0] }}"
      InstanceName: "{{ mssql_instance_name }}"
      SecurityMode: "{{ mssql_security_mode }}"
      Features: "{{ mssql_instance_features }}"
      SQLCollation: "{{ mssql_collation }}"
      AgtSvcStartupType: "{{ mssql_agentsvc_mode  }}"
      BrowserSvcStartupType: "{{ mssql_browsersvc_mode }}"
      SuppressReboot: "{{ mssql_suppress_reboot }}"

      # Service Accounts
      # To install SQL with default accounts i.e NT Service\MSSQLSERVER then comment out
      # To install with custom accounts uncomment and fill in variables

      # SQL Service Account
      #SQLSvcAccount_username: "{{ mssql_sqlsvc_account }}"
      #SQLSvcAccount_password: "{{ mssql_sqlsvc_account_pass }}"

      # SQL Agent Service Account
      #AgtSvcAccount_username: "{{ mssql_agentsvc_account }}"
      #AgtSvcAccount_password: "{{ mssql_agentsvc_account_pass }}"

      # SQL Analysis Services Account
      #ASSvcAccount_username: "{{ mssql_assvc_account }}"
      #ASSvcAccount_password: "{{ mssql_assvc_account_pass }}"

      # Used when installing on a network path, comment out
      # SourceCredential_username: "{{ ansible_user }}"
      # SourceCredential_password: "{{ ansible_password }}"

      # System Admins
      SQLSysAdminAccounts: "{{ mssql_sysadmin_accounts }}"
      # Analysis Services Admins (if installed)
      #ASSysAdminAccounts: "{{ mssql_asadmin_accounts }}"
      SAPwd_username: "sa"
      SAPwd_password: "{{ mssql_sa_password }}"

      # File and Folder Paths
      # To install SQL with default folder locations comment out

      #InstallSharedDir: "{{ mssql_installshared_path }}"
      #InstallSharedwowDir: "{{ mssql_installsharedwow_path }}"
      #InstanceDir: "{{ mssql_instance_path }}"
      #InstallSQLDataDir: "{{ mssql_sqlinstalldata_path }}"
      #SQLUserDBDir: "{{ mssql_sqluserdata_path }}"
      #SQLUserDBLogDir: "{{ mssql_sqluserlog_path }}"
      #SQLTempDBDir: "{{ mssql_sqltempDB_path }}"
      #SQLTempDBLogDir: "{{ mssql_sqltempDBlog_path }}"

  # End of win_dsc for SQL Server

  # Firewall configuration
  - name: Firewall | Open SQL Server 1433
    win_firewall_rule:
      name: "SQL Server 1433"
      localport: "1433"
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes

  # Begin SQL Server configuration
  - name: Enable SQL TCPIP Connectivity
    win_dsc:
      resource_name: SqlProtocol
      InstanceName: "{{ mssql_instance_name }}"
      ProtocolName: TcpIp
      KeepAlive: 30000
      ListenOnAllIpAddresses: Yes
      Enabled: True

  - name: Unmount ISO image of SQL Server
    win_disk_image:
      image_path: '{{ iso_find.files[0].path }}'
      state: absent

  - name: Remove SQL Server Install directory
    win_file:
      path: C:\SQLServer
      state: absent

  # when: SQL2022Dev.exists == false

```

### Expected Results

SQL Server to install as expected on Windows Server 2022

### Actual Results

```console
The full traceback is:
Not found
At line:50 char:17
+ ... $resource = Get-CimClass -ClassName $ClassName -Namespace root\Micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (root\Microsoft\...on:DSC_SqlSetup:String) [Get-CimClass], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041002,Microsoft.Management.Infrastructure.CimCmdlets.GetCimClassCommand

ScriptStackTrace:
at Get-DscCimClassProperty, <No file>: line 50
at Get-OptionSpec, <No file>: line 159
at <ScriptBlock>, <No file>: line 480

Microsoft.Management.Infrastructure.CimException: Not found
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
fatal: [192.168.1.70]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Not found "
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
