### ISSUE TITLE
Using ansible_ssh_host_key_checking in add_host gets ignored

### ISSUE THREAD

**Issue by aph3rson** [ansible/ansible#82005]
### Summary

I'm deploying a VM via Proxmox in my playbook, and I'd like to add the deployed VM back in to my inventory for that same playbook.
Because this is a relatively-early play, before I've been able to customize host certs and such, I need to adjust host key checking.

At first, I tried using this syntax for my task:
```yaml
    - name: Add bootstrapping Gitea to inventory
      ansible.builtin.add_host:
        name: giteabootstrap
        groups:
          - vms
          - bootstrapping
        vmid: "{{ giteabootstrap_vm.vmid }}"
        ansible_host: "{{ new_ip }}"
        ansible_user: bootstrap
        ansible_ssh_private_key_file: "{{ giteabootstrap_dir.path }}/id_ssh_rsa"
        ansible_ssh_host_key_checking: false
```

However, I'm still presented with a host key verification prompt, which won't work for a non-interactive environment.

Instead, I had to use the ansible_ssh_extra_args param, like so:
```yaml
    - name: Add bootstrapping Gitea to inventory
      ansible.builtin.add_host:
        name: giteabootstrap
        groups:
          - vms
          - bootstrapping
        vmid: "{{ giteabootstrap_vm.vmid }}"
        ansible_host: "{{ new_ip }}"
        ansible_user: bootstrap
        ansible_ssh_private_key_file: "{{ giteabootstrap_dir.path }}/id_ssh_rsa"
        # ansible_ssh_host_key_checking: false
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
```

This syntax worked, but I would've expected the former to work fine.

### Issue Type

Bug Report

### Component Name

ssh_connection

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

# No output
```

### OS / Environment

Ubuntu Jammy. Target host is also running Ubuntu Jammy

### Steps to Reproduce

1. Add a host using the `add_host` builtin, specifying the `ansible_ssh_host_key_checking` variable.
2. Attempt to connect to the newly added host, e.g. with the `setup` builtin.
3. Ensure the host in question is not in the local known_hosts file (`~/.ssh/known_hosts`).
4. Execute the playbook, and observe that a host key verification prompt is presented.

### Expected Results

I expected no host key verification to be required.

### Actual Results

```console
The authenticity of host '192.168.99.110 (192.168.99.110)' can't be established.                                        ECDSA key fingerprint is SHA256:xAwhpjh1Y62WS+PhSMg9dJLQ0XjTElWqySPEHk3UXeY.                                            Are you sure you want to continue connecting (yes/no/[fingerprint])? 

# Host key verification prompt displayed by ansible.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
