### ISSUE TITLE
ansible.builtin.service (systemd) fails in check mode if service is not installed

### ISSUE THREAD

**Issue by rtwruck** [ansible/ansible#82048]
### Summary

When the service to be (re)started is not installed, ansible.builtin.service fails even in check mode.
That is bad for plays that try to e.g. install - configure - restart a service.

### Issue Type

Bug Report

### Component Name

service

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.5]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.13 (main, Aug 26 2023, 11:33:35) [GCC 12.2.1 20220924] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
# run in check mode:

  - ansible.builtin.apt:
      name: earlyoom
  - ansible.builtin.service:
      name: earlyoom
      state: restarted
```

### Expected Results

changed: [hostname]

### Actual Results

```console
fatal: [hostname]: FAILED! => {"changed": false, "msg": "Could not find the requested service irqbalance: host"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/service.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/service.py)
* [`lib/ansible/modules/service.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/service.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by bcoca** [comment]
Ansible does not keep state across tasks, so the `service` task is unaware of the `apt` task before it, you CAN control this in several ways, if just for checkmode:

```
  - ansible.builtin.service:
      name: earlyoom
      state: restarted
    register: e_s
     failed_when: e_s is failed and not ansible_check_mode
```

**Comment by rtwruck** [comment]
My point is that tasks that run fine in "live" mode should not require special precautions to also run in check mode.
Since the service will not be restarted in check mode anyway, there's no point in failing here.
It would probably be more intuitive to skip the step in this case.

**Comment by bcoca** [comment]
@rtwruck check mode is to figure out what WOULD happen if the task really runs, the service task in another context would be returning false information if it returns 'ok' without the service itself being present.

For example, would it be correct for this play to return 'OK' in check mode if the service is not installed?
```
- hosts: all
  tasks:
  - ansible.builtin.template:
      src: earlyoom.config.j2
      dest: /etc/earlyoom/confg.ini
  - ansible.builtin.service:
      name: earlyoom
      state: restarted
```

**Comment by rtwruck** [comment]
Well, if you'd use the `command` plugin instead, this would not fail in check mode but *might* in live mode:
```
- hosts: all
  tasks:
  - ansible.builtin.template:
      src: earlyoom.config.j2
      dest: /etc/earlyoom/confg.ini
  - ansible.builtin.command:
      cmd: systemctl restart earlyoom
```
Of course, the `service` plugin knows more about what it's going to do but should it fail here?
If possible, I'd return `skipped: true` in check mode if either the service or systemd is not installed.
(Actually, for `restarted` it could always return `changed` :-) )
Furthermore, this plugin currently has no return values. It *could* however return a value indicating whether the service is installed/loaded/enabled or not -- sneaking in a feature request here.
If it did - would failure still be the right option?
