### ISSUE TITLE
parent group_vars prioritized over child group vars from inventory

### ISSUE THREAD

**Issue by rtwruck** [ansible/ansible#82069]
### Summary

Variables defined in group_vars files always take precedence over any other group vars defined in the inventory itself, even if they apply to parent groups.
This seems to contradict the documented merge order: https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#how-variables-are-merged

### Issue Type

Bug Report

### Component Name

inventory

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.5]
  config file = /opt/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.13 (main, Aug 26 2023, 11:33:35) [GCC 12.2.1 20220924] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
---
# inventory.yaml
all:
  vars:
    my_var: all  
  children:
    level1:
      vars:
        my_var: level1
      children:
        level2:
          vars:
            my_var: level2
          hosts:
            myhost:
---
# group_vars/all/vars.yaml
my_var: group_vars
```

### Expected Results

Since the group_vars apply to the `all` group, the child group setting `level2` should take precedence.

### Actual Results

```console
$ ansible-inventory --graph --vars
@all:
  |--@ungrouped:
  |--@level1:
  |  |--@level2:
  |  |  |--myhost
  |  |  |  |--{my_var = group_vars}
  |  |  |--{my_var = level2}
  |  |--{my_var = level1}
  |--{my_var = group_vars}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
