### ISSUE TITLE
filter "human_to_bytes" will happily parse strings it shouldn't

### ISSUE THREAD

**Issue by leegarrett** [ansible/ansible#82075]
### Summary

When filtering a string through human_to_bytes, there are several cases where it probably shouldn't parse.

1. There is not regex anchor, so any trailing (but not leading) text will be ignored https://github.com/ansible/ansible/blob/bf29458726496ee759f515cefe9e91fc26a533bd/lib/ansible/module_utils/common/text/formatters.py#L56
2. human_to_bytes to will happily take non-ascii numbers, too
3. The unit check will happily take anything, as long as the first character is [BEGKMPTYZ], and ( second letter is "B", or it contains bytes anywhere).
4. Due to the way parsing works, any non-number will terminate parsing early if followed by non-letters.

See below a list of examples sorted by issue.

For most of the issues adding a `$` anchor to the regex should suffice. I'd argue that non-ASCII numbers should not be parsed, as they can easily pretend to be a unit character as in the case of `𖭙`. Most whitespace should also not be ignored, as this allows for a fake negative numbers, as well as truncating parsing(zero width characters).

Since stricter parsing might cause side effects, I propose that it emits a warning for a few releases and falls back to the current parsing method in the examples below. I'm happy to provide the a patch.

### Issue Type

Bug Report

### Component Name

lib/ansible/module_utils/common/text/formatters.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.11]
  config file = None
  configured module search path = ['/home/randall/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/randall/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Debian bookworm, but irrelevant

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  tasks:
    - debug:
        msg: "{{ item | human_to_bytes }}"
      ignore_errors: true
      loop:
        # first two letters are a unit
        - 10 BBQ sticks please  # -> 10
        - 3000 BB guns of justice # -> 3000
        - 1 EBOOK please # -> 1152921504606846976
        - 3 eBulletins # -> 3458764513820540928
        - 1 bBig family # -> 1
        #- 10 other things please # -> correctly fails

        # first letter matches [BEGKMPTYZ] and word contains "byte"
        - 13youcanhaveabyteofmysandwich # -> '15716035654990179271180288'
        - .1 Geggabytes # -> 107374182
        - 3 prettybytes # -> 3377699720527872
        - 10 bytes of cheese, please # -> 10
        - 10 texasburgerbytes, please # -> 10995116277760
        - 12 muppetbytes     # 12582912

        # non-ASCII numbers
        - ৪𖭙 # -> 49
        - 8𖭙B # -> 89
        - 𖭙, this should not return # -> 9
        - ၀k, this should not parse # -> '0'
        - 1.၀k? # -> 1024
        - ᭔ MB # -> 4194304

        # any non-number character will truncate the result
        - 12,000 MB # -> 12
        - 12 000 MB # -> 12
        - '1​000 MB' # U+200B zero-width space after 1, so -> 1

        # leading whitespaces are ignored
        - |
           1
           kB # -> 1024
        - '          12MB' # -> 12582912
        - ' 12 MB' # U+1680 	OGHAM SPACE MARK -> 12582912
        #- '-12 MB' # fails, as it's a negative number

```

### Expected Results

'human_to_bytes() can''t interpret following string: <string>' for every entry

### Actual Results

```console
$ ansible-playbook byte_conversion.yml 
PLAY [localhost] *************************************************************************************************

TASK [debug] *****************************************************************************************************
ok: [localhost] => (item=10 BBQ sticks please) => 
  msg: '10'
ok: [localhost] => (item=3000 BB guns of justice) => 
  msg: '3000'
ok: [localhost] => (item=1 EBOOK please) => 
  msg: '1152921504606846976'
ok: [localhost] => (item=3 eBulletins) => 
  msg: '3458764513820540928'
ok: [localhost] => (item=1 bBig family) => 
  msg: '1'
ok: [localhost] => (item=13youcanhaveabyteofmysandwich) => 
  msg: '15716035654990179271180288'
ok: [localhost] => (item=.1 Geggabytes) => 
  msg: '107374182'
ok: [localhost] => (item=3 prettybytes) => 
  msg: '3377699720527872'
ok: [localhost] => (item=10 bytes of cheese, please) => 
  msg: '10'
ok: [localhost] => (item=10 texasburgerbytes, please) => 
  msg: '10995116277760'
ok: [localhost] => (item=12 muppetbytes) => 
  msg: '12582912'
ok: [localhost] => (item=৪𖭙) => 
  msg: '49'
ok: [localhost] => (item=8𖭙B) => 
  msg: '89'
ok: [localhost] => (item=𖭙, this should not return) => 
  msg: '9'
ok: [localhost] => (item=၀k, this should not parse) => 
  msg: '0'
ok: [localhost] => (item=1.၀k?) => 
  msg: '1024'
ok: [localhost] => (item=᭔ MB) => 
  msg: '4194304'
ok: [localhost] => (item=12,000 MB) => 
  msg: '12'
ok: [localhost] => (item=12 000 MB) => 
  msg: '12'
ok: [localhost] => (item=1​000 MB) => 
  msg: '1'
ok: [localhost] => (item=1
kB # -> 1024
) => 
  msg: '1024'
ok: [localhost] => (item=          12MB) => 
  msg: '12582912'
ok: [localhost] => (item= 12 MB) => 
  msg: '12582912'

PLAY RECAP *******************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
