### ISSUE TITLE
Add new module to community.crypto for Entrust CA Gateway that support Entrust and other private/public PKIs

### ISSUE THREAD

**Issue by sapnajainEntrust** [ansible/ansible#82107]
### Summary

I am trying to add a new module for the crypto collection i.e. entrust_cagw_certificate and the purpose of the module is to be able to request private/public PKI certs from CAs like Entrust Security Manager, Entrust PKIaaS, Entrust SSL CA,  and third party CAs like Microsoft. 
This is how it is different from the existing Entrust plugin ecs_certificate within the community crypto collection -

- Unlike ECS, this plugin can issue certs from both public and private Certificate Authorities supported by CAGW

CA Gateway or CAGW provides a REST based interface that talks to different Certificate Authorities as mentioned above and this new module us supposed to interact with CAGW over API interface. 
I am at a point where I have been able to code complete the module, test with different CAs and even have my integration test suite ready.

### Issue Type

Feature Idea

### Component Name

entrust_cagw_certificate

### Additional Information

```yaml (paste below)
- name: Request a certificate from Entrust Certificate Authority via Entrust CAGW with using the 
   entrust_cagw_certificate:
      path: '{{ output_cert_path }}'
      csr: '{{ csr_path }}'
      host: '{{ entrust_host }}'
      port: '{{ entrust_port }}'
      certificate_authority_id: '{{ ca_id }}'
      certificate_profile_id: '{{ cert_profile_id }}'
      cagw_api_client_cert_path: '{{ entrust_cagw_api_cert }}'
      cagw_api_client_cert_key_path: '{{ entrust_cagw_api_cert_key }}'
      cagw_api_specification_path: '{{ cagw_api_specification_path }}'
      request_type: '{{ request_type }}'
      enrollment_format: '{{ enrollment_format }}'
      connector_name: SM
      force: '{{ force }}'
      validate_certs: '{{ validate_certs }}'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
