### ISSUE TITLE
include_tasks' apply recursivity option

### ISSUE THREAD

**Issue by aklakina** [ansible/ansible#82114]
### Summary

# Context
Consider the following architecture:
_main.yml:_
```yml
- name: include factory
  include_tasks: factory.yml
  apply:
    tags:
      - always
  tags:
    - always
```
_factory.yml:_
```yml
- name: include hourly
  include_tasks: generic.yml
  apply:
    tags:
      - hourly
  loop: "{{ hourly }}"
- name: daily
  include_tasks: generic.yml
  apply:
    tags:
      - daily
  loop: "{{ daily }}"
```

Following the documentation this should work in the following manner if we run the playbook with tag `hourly`:
_main.yml_ &rarr; _factory.yml_ &rarr; _generic.yml_ over the items of `hourly` &rarr; exit

On the other hand it runs the _generic.yml_ over the elements of the `daily` object too. This is probably because the `apply` option creates a block in which it includes the tasks mentioned in the configuration in the task. This causes the tasks to inherit the options from the block and therefore the tagging downwards will break if the upper block has always on it.

# The request
It would be great to have an option to toggle the recursive algorithm on the `include_tasks`' `apply` option. The default could be `yes` so it would keep the backwards compatibility if anyone built playbook using this algorithm.

# Current workaround
_main.yml:_
```yml
- name: include factory
  include_tasks: factory.yml
  tags:
    - always
```
_factory.yml:_
```yml
- name: include hourly
  include_tasks: generic.yml
  apply:
    tags:
      - hourly
  loop: "{{ hourly }}"
  tags:
    - always
- name: daily
  include_tasks: generic.yml
  apply:
    tags:
      - daily
  loop: "{{ daily }}"
  tags:
    - always
```
# Cause of the request
This workaround causes redundancy in code and because the documentation doesn't explicitly mentions the recursive meaning of `apply` option it could confuse developers.

### Issue Type

Documentation Report

### Component Name

include_tasks.py

### Additional Information

# Example usage
_main.yml:_
```yml
- name: include factory
  include_tasks: factory.yml
  apply:
    tags:
      - always
    recursive: no
  tags:
    - always
```
_factory.yml:_
```yml
- name: include hourly
  include_tasks: generic.yml
  apply:
    tags:
      - hourly
  loop: "{{ hourly }}"
- name: daily
  include_tasks: generic.yml
  apply:
    tags:
      - daily
  loop: "{{ daily }}"
```
# Flow of the example:
_main.yml_ &rarr; _factory.yml_ &rarr; _generic.yml_ over the items of `hourly` &rarr; skipping _generic.yml_ over the items of `daily` since the tag is not present &rarr; exit

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
