### ISSUE TITLE
postgresql_user will always give a result of changed once no password change for scram-sha-256

### ISSUE THREAD

**Issue by yinan8128** [ansible/ansible#82176]
### Summary

postgresql_user will always give a result of changed once no password change for scram-sha-256

### Issue Type

Bug Report

### Component Name

postgresql_user 

### Ansible Version

```console
$ ansible --version
ansible 2.9.18
```

### Configuration

```console
N/A
```

### OS / Environment

 Operating System: Virtuozzo release 7.0.14
            Kernel: Linux 3.10.0-1127.8.2.vz7.151.14
      Architecture: x86-64

### Steps to Reproduce

Use a PostgreSQL server with password_encryption = scram-sha-256 parameter on postgresql.conf.

Creates a playbook that creates an user using postgresql_user module with a clear text password:

```
        - name: PostgreSQL | Create database user
          become: yes
          become_user: postgres
          postgresql_user:
            name: "aaa"
            password: "aaa_1"
            encrypted: yes
            state: present
```
Run playbook multiple times.

### Expected Results

From the second run

Ansible log shows ok not changed
```
TASK [PostgreSQL | Create database user] *****************************************************************************************************************************************************
Thursday 09 November 2023  03:11:58 +0000 (0:00:00.303)       0:00:10.876 *****
ok: [hostname]
```

There is no `statement: ALTER USER "aaa" WITH ENCRYPTED PASSWORD 'aaa_1'` part postgresql log

### Actual Results

```console
From the second run

Ansible log shows ok not changed

TASK [PostgreSQL | Create database user] *****************************************************************************************************************************************************
Thursday 09 November 2023  03:11:58 +0000 (0:00:00.303)       0:00:10.876 *****
changed: [hostname]
```

There is `statement: ALTER USER "aaa" WITH ENCRYPTED PASSWORD 'aaa_1'` part postgresql log

There is a similar ticket for ansible 2.7.4, from which ansible new version start to fix it please? 2.11 or 2.12? Thanks
https://github.com/ansible/ansible/issues/49878
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
