### ISSUE TITLE
Vault encrypted variables show up in verbose output

### ISSUE THREAD

**Issue by Stiverton** [ansible/ansible#82172]
### Summary

When running a playbook in verbose mode with a command task that requires usage of a vault-encrypted variable, the plaintext value of the variable is logged.

### Issue Type

Bug Report

### Component Name

ansible-playbook

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.5]
  config file = /home/user/Ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /home/user/Ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/user/Ansible/ansible.cfg) = ['/home/user/Ansible/Ansible/inventories']
DEFAULT_ROLES_PATH(/home/user/Ansible/ansible.cfg) = ['/home/user/Ansible/Ansible/roles']
DEFAULT_VERBOSITY(/home/user/Ansible/ansible.cfg) = 0
HOST_KEY_CHECKING(/home/user/Ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/user/Ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/home/user/Ansible/ansible.cfg) = False
```

### OS / Environment

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

WSL2

### Steps to Reproduce

```yaml (paste below)
---
- name: Login to CLI
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  no_log: true

  tasks:
    - name: Include vault
      ansible.builtin.include_vars:
        file: "../../vaults/vault.yml"

    - name: Log into CLI
      ansible.builtin.command: cli login
      environment:
        CLI_CLIENTID: "{{ cli_client_id }}"
        CLI_CLIENTSECRET: "{{ cli_client_secret }}"
      register: cli_login_result
      changed_when: "'You are logged in!' in cli_login_result.stdout"


ansible-playbook --vault-id vault1@prompt playbooks/cli-log-in.yml -vvv
```

### Expected Results

I expected ansible to scrub the values of vault encrypted variables in verbose task output because I assumed this would be a basic security practice and be easy to do and was shocked when it did not.

### Actual Results

```console
TASK [Include vault] ************************************************************************************************************************************************************************
task path: /home/user/Ansible/Ansible/playbooks/cli-log-in.yml:13
ok: [127.0.0.1] => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": false
}

TASK [Log into CLI] *****************************************************************************************************************************************************************************************
task path: /home/user/Ansible/Ansible/playbooks/cli-log-in.yml:17
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1699452778.550914-7350-62452134291200 `" && echo ansible-tmp-1699452778.550914-7350-62452134291200="` echo /home/user/.ansible/tmp/ansible-tmp-1699452778.550914-7350-62452134291200 `" ) && sleep 0'
Using module file /home/user/.local/lib/python3.10/site-packages/ansible/modules/command.py
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-7317_8ajq91e/tmpcw2y4psw TO /home/user/.ansible/tmp/ansible-tmp-1699452778.550914-7350-62452134291200/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1699452778.550914-7350-62452134291200/ /home/user/.ansible/tmp/ansible-tmp-1699452778.550914-7350-62452134291200/AnsiballZ_command.py && sleep 0'


<127.0.0.1> EXEC /bin/sh -c 'CLI_CLIENTID=plaintextClientId CLI_CLIENTSECRET=plaintextClientSecret /usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1699452778.550914-7350-62452134291200/AnsiballZ_command.py && sleep 0'


<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1699452778.550914-7350-62452134291200/ > /dev/null 2>&1 && sleep 0'
changed: [127.0.0.1] => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": true
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
