### ISSUE TITLE
Handlers: unnotify

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#82174]
### Summary

Sometimes it needed to cancel previously notified handler. For example to cancel a handler that reloads a service if a task was executed that already restarted that service.

Yes, it sort of can be done with `register` on a task and `when` on a handler, but this is crude and requires extra planning.

Adding `unnotify` keyword to remove handler from where `notify` adds it would be a slick solution.

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

```yaml (paste below)
- name: place config
  template:
    src: my_service.conf
    dest: /etc/my_service.conf
  notify:
    - reload my_service

- name: restart some services
  service:
    name: "{{ item }}"
    state: restarted
  when: some_unrelated_important_thing is changed
  loop:
    - other_stuff
    - my_service
    - more_stuff
  unnotify:
    - restart other_stuff
    - reload my_service
    - update more_stuff
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
