### ISSUE TITLE
`delegate_to` executes task on original host when `ansible_host` variable is set

### ISSUE THREAD

**Issue by Yannik** [ansible/ansible#82189]
### Summary

ansible will connect to the original host instead of the `delegate_to` host configured on a task, when the `ansible_host` variable is set for the original host.

Background: Due to using kerberos, we cannot set ansible_host to an IP in the inventory, but need to use the hostname. Specifically, we need to use the fqdn, as we do not have a single non-conflicting search domain. To avoid having to repeat the FQDN over and over again in the inventory, we configured the following in `group_vars` for a group of hosts (as they all share the same fqdn):
```
ansible_host: "{{ inventory_hostname }}.fqdn.com"
```

This for some reason leads to `delegate_to` being broken. (Otherwise, it is working perfectly fine)

### Issue Type

Bug Report

### Component Name

delegate_to

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.1]
  config file = None
  configured module search path = ['/home/yannik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/yannik/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/yannik/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less
```

### OS / Environment

windows server 2022

### Steps to Reproduce

`hosts`:
```ini
[windows]
win1
win2
```

`group_vars/windows.yml`:
```yaml
ansible_host: "{{ inventory_hostname }}.fqdn.com"
ansible_connection: winrm
ansible_winrm_transport: kerberos
ansible_winrm_port: 5985
ansible_user: "user@DOMAIN"
ansible_password: "secret"
```

`playbook.yml`:

```yaml
- hosts: win1
  tasks:
    - name: Delegating task
      ansible.windows.win_shell: hostname
      register: result
      delegate_to: win2
 
    - debug:
        msg: "{{ result.stdout }}"
```

### Expected Results

Winrm should correctly execute the task on the `delegate_to` host, `win2`.

### Actual Results

```console
PLAY [win] ******************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************
TASK [Delegating task] ******************************************************************************************************************************************
changed: [win1 -> win2({{ inventory_hostname }}.fqdn.com)]

TASK [debug] ****************************************************************************************************************************************************
ok: [dc1] => {
    "msg": "win1\r\n"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
