### ISSUE TITLE
Unable to use assert fail_msg in assert condition

### ISSUE THREAD

**Issue by garry-t** [ansible/ansible#82180]
### Summary

Seems like docs is not updated here https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html

In my case it produce error:

```
- name: Check conditions for consul_upstreams
  assert:
    that:
      - item.service_name is not iterable
  when: item.tag is defined
  with_items: "{{ consul_upstreams }}"
  fail_msg: "BLAH BLAH"
  register: assert_result
```
`
 ERROR! conflicting action statements: assert, fail_msg`

### Issue Type

Documentation Report

### Component Name

ansible.builtin.assert

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.1]
  config file = None
  configured module search path = ['/Users/t/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/t/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

mac OS 13.5.2 (22G91)

### Additional Information

no need. I guess. 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/assert.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/assert.py)
* [`lib/ansible/plugins/action/assert.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/assert.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

You are incorrectly trying to use `fail_msg` as a task keyword, when it is a action paramter or option, you need to indent it.
```
- name: Check conditions for consul_upstreams
  assert:
    fail_msg: "BLAH BLAH"
    that:
      - item.service_name is not iterable
  when: item.tag is defined
  with_items: "{{ consul_upstreams }}"
  register: assert_result
```
In the future, this might be a topic better suited for the user list or chat channels.

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
The mailing list and irc are great ways to ask questions, or post if you don't think this particular issue is resolved.

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Thank you once again for this and your interest in Ansible!
