### ISSUE TITLE
Cpanm module doesn't upgrade modules previously installed through Yum

### ISSUE THREAD

**Issue by RyanJarv** [ansible/ansible#8218]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Host: OSx using Vagrant
Guest: CentOS 6.5
##### Summary:

Cpanm module doesn't upgrade modules previously installed through Yum
##### Steps To Reproduce:

In CentOS 6.5 perl-5.10.1 includes the Encode perl module. If you need to get a newer version through Cpan, the following task does not upgrade the Encode module. The same thing happens for any Module previously installed through yum.

```
- name: Install other dependencies through CPAN
  cpanm: name=Encode
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/usr/local/bin"
```
##### Expected Results:

The expected results would be to upgrade the Module to 2.62 just like it would if you called cpanm explicitly:

```
- name: Upgrade Encode
  shell: /usr/local/bin/cpanm -i Encode
```

[vagrant@vagrant-centos65 ~]$ perl -MEncode -e 'print "$Encode::VERSION\n"'
2.62
##### Actual Results:

The results of the cpanm module is that the Encode Perl module is not upgraded and is still on version 2.35.

[vagrant@vagrant-centos65 ~]$ perl -MEncode -e 'print "$Encode::VERSION\n"'
2.35
