### ISSUE TITLE
validate_argument_spec `type=list` and `elements=str` convert bool or int in a list of string

### ISSUE THREAD

**Issue by tanganellilore** [ansible/ansible#82186]
### Summary

Hi team,

I notice that the in the validate_argument_spec module, when we validate a list, validation try to convert it in a list and in case of int or boolean (in python bool is intended as int with `isinstance` function) will be "casted" to string: https://github.com/ansible/ansible/blob/667526c22ff59bbe7bc790bf505b7f09cae3856f/lib/ansible/module_utils/common/validation.py#L390-L410

This is intended?

Moreover there is a way to force the "strict" validation instead a validation that try to "convert" data?
Something like `allow_conversion` that i see in `check_type_str` but that is not used by `validate_argument_spec`.

Becuase in that way we can strict the value and/or use it in the module as parameters (or add it as keyof model), to have a strinct check .

Thanks

### Issue Type

Bug Report

### Component Name

validate_argument_spec

### Ansible Version

```console
ansible [core 2.15.1]
  python version = 3.10.6
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 7200
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart

CACHE:
=====

jsonfile:
________
_timeout(/etc/ansible/ansible.cfg) = 7200
_uri(/etc/ansible/ansible.cfg) = /tmp/facts_cache
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
- name: Test
  hosts: localhost
  vars:
    params:
      add_options: true
  tasks:
    - name: verify 
      ansible.builtin.validate_argument_spec:
        argument_spec: '{{ required_data }}'
        provided_arguments: "{{ params }}"
      vars:
        required_data:
          add_options:
            type: list
            default: []
            elements: str
```

### Expected Results

Task will fail because:

1. Type of add_options is boolean
2. If will be performet a convertion of single element in a list, i'm expect that element in list will be boolean, but is converted to string

### Actual Results

```console
Task will pass
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
