### ISSUE TITLE
lookup('file') does not fail when the file does not exist

### ISSUE THREAD

**Issue by lukad** [ansible/ansible#8219]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Arch Linux 64-bit
##### Summary:

When trying to interact with files using lookup('file') ansible does not fail when the file does not exist.
##### Steps To Reproduce:

I wrote the following task to install multiple public keys for several users.

``` yaml

---
- name: install public keys
  authorized_key:
    user="{{ item[0] }}"
    key="{{ lookup('file', 'public-keys/' + item[1] + '.pub') }}"
  with_nested:
    - ['root']
    - ['luka', 'foo']
```

`public-keys/foo.pub` however, does not not exist and the task should fail.

```
[luka public-keys]$ tree
.
├── files
│   └── public-keys
│       └── luka.pub
└── tasks
    └── main.yml
```

This is also reproducable with simple tasks where you just copy a file.

``` yaml
- name: copy foo
  copy:
    src="{{ lookup('file', 'foo') }}"
    dest=/foo
```
##### Expected Results:

```
[luka public-keys]$ ansible-playbook -i stages/vagrant public-keys.yml -K
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [sandbox-dev]

TASK: [public-keys | install public keys] ************************************* 
changed: [sandbox-dev] => (item=['root', 'luka'])
failed: [sandbox-dev] => (item=['root', 'foo']) => {"failed": true, "item": ["root", "foo"]}
msg: invalid key specified: public-keys/foo.pub

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/luka/public-keys.retry

sandbox-dev                : ok=1    changed=0    unreachable=0    failed=1
```
##### Actual Results:

```
[luka public-keys]$ ansible-playbook -i stages/vagrant public-keys.yml -K
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [sandbox-dev]

TASK: [public-keys | install public keys] ************************************* 
changed: [sandbox-dev] => (item=['root', 'luka'])
ok: [sandbox-dev] => (item=['root', 'foo'])

PLAY RECAP ******************************************************************** 
sandbox-dev                : ok=1    changed=1    unreachable=0    failed=0  
```
