### ISSUE TITLE
ansible.builtin.union documentation not matching implementation

### ISSUE THREAD

**Issue by myllynen** [ansible/ansible#82199]
### Summary

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/union_filter.html#examples shows:

\# return the unique elements of list1 added to list2
\# list1: [1, 2, 5, 1, 3, 4, 10]
\# list2: [1, 2, 3, 4, 5, 11, 99]
{{ list1 | union(list2) }}
\# => [1, 2, 5, 1, 3, 4, 10, 11, 99]

But running a test playbook with the above gives different result:

```yaml
- name: test
  vars:
    list1: [1, 2, 5, 1, 3, 4, 10]
    list2: [1, 2, 3, 4, 5, 11, 99]
  debug:
    msg: |
      {{ list1 | union(list2) | string }}
```

```
ok: [localhost] =>
    msg: |-
	[1, 2, 5, 3, 4, 10, 11, 99]
```

I think documentation not the code needs to be adjusted here. Thanks.

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.6]
  config file = /home/testuser/.ansible.cfg
  configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/testuser/ansible/ansible-2.15/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/testuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/testuser/ansible/ansible-2.15/bin/ansible
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/home/testuser/ansible/ansible-2.15/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
ANSIBLE_NOCOWS(/home/testuser/.ansible.cfg) = True
```

### OS / Environment

This is on RHEL 9 with pip installed ansible 2.15.

### Steps to Reproduce

```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: test
    vars:
      list1: [1, 2, 5, 1, 3, 4, 10]
      list2: [1, 2, 3, 4, 5, 11, 99]
    debug:
      msg: |
        {{ list1 | union(list2) | string }}
```

### Expected Results

Documentation and output match.

### Actual Results

```console
Documentation:

[1, 2, 5, 1, 3, 4, 10, 11, 99]

Actual output:

[1, 2, 5, 3, 4, 10, 11, 99]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
