### ISSUE TITLE
yum enablerepo

### ISSUE THREAD

**Issue by xRTRx** [ansible/ansible#82205]
### Summary

I tried to install a package using the yum module in two different ways. The first method worked without any issues, but the second one did not work. I am unsure of what is causing the problem. The steps to reproduce the issue are given below.
I am using ansible-core 2.15.6 (also tested with 2.15.5) and ansible 8.6.1 (also tested with 8.5.0), but the results were the same.

### Issue Type

Bug Report

### Component Name

yum

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.6]
  config file = None
  configured module search path = ['/home/codespace/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /workspaces/ansible-role-documentserver/.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/codespace/.ansible/collections:/usr/share/ansible/collections
  executable location = /workspaces/ansible-role-documentserver/.venv/bin/ansible
  python version = 3.10.8 (main, Sep 13 2023, 16:52:46) [GCC 9.4.0] (/workspaces/ansible-role-documentserver/.venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

OS: Red Hat Enterprise Linux Server 7.9 (Maipo)
python version: 2.7.5
kernel: 3.10.0-1160.99.1.el7.x86_64
yum version: 3.4.3

### Steps to Reproduce

Working example
```yaml
- name: Install xorg-x11-server-Xvfb
  ansible.builtin.yum:
    name: xorg-x11-server-Xvfb
    enablerepo: "rhel-7-server-rhui-optional-rpms"
    state: present
```
Not working example
```yaml (paste below)
- name: Install xorg-x11-server-Xvfb
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: "xorg-x11-server-Xvfb", enablerepo: "rhel-7-server-rhui-optional-rpms" }
```

### Expected Results

I expect both solutions to work.

### Actual Results

```console
failed: [18.169.184.215] (item={'name': 'xorg-x11-server-Xvfb', 'enablerepo': 'rhel-7-server-rhui-optional-rpms'}) => {"ansible_loop_var": "item", "changed": false, "item": {"enablerepo": "rhel-7-server-rhui-optional-rpms", "name": "xorg-x11-server-Xvfb"}, "msg": "No package matching 'xorg-x11-server-Xvfb' found available, installed or updated", "rc": 126, "results": ["No package matching 'xorg-x11-server-Xvfb' found available, installed or updated"]}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/yum.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/yum.py)
* [`lib/ansible/modules/yum.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/yum.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by xRTRx** [comment]
Forgot about enablerepo itself
```yaml
- name: Install xorg-x11-server-Xvfb
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: present
    enablerepo: "{{ item.enablerepo }}"
  with_items:
    - { name: "xorg-x11-server-Xvfb", enablerepo: "rhel-7-server-rhui-optional-rpms" }
```

**Comment by mkrizek** [comment]
I was unable to replicate the issue with CentOS 7 container and the playbook below:

Container:
```
% podman run --name container --rm -it --entrypoint bash centos:7
[root@61576a778d7a /]# yum --version
3.4.3
  Installed: rpm-4.11.3-45.el7.x86_64 at 2020-11-13 01:54
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2020-09-30 17:30
  Committed: Michal Domonkos <mdomonko@redhat.com> at 2020-06-02

  Installed: yum-3.4.3-168.el7.centos.noarch at 2020-11-13 01:54
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2020-10-01 17:03
  Committed: CentOS Sources <bugs@centos.org> at 2020-09-29

  Installed: yum-plugin-fastestmirror-1.1.31-54.el7_8.noarch at 2020-11-13 01:54
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2020-05-12 16:27
  Committed: Michal Domonkos <mdomonko@redhat.com> at 2020-03-12
[root@61576a778d7a /]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
Inventory:
```
container ansible_connection=podman
```
Playbook:
```yaml
- hosts: container
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - yum:
        name: "{{ item.name }}"
        state: present
        enablerepo: "{{ item.enablerepo }}"
        use_backend: yum
      with_items:
        - { name: "python-perf-3.10.0-1160.88.1.el7.centos.plus", enablerepo: "centosplus" }
```

The `enablerepo` value is properly passed into the module invocation:
```
    "changes": {
        "installed": [
            "python-perf-3.10.0-1160.88.1.el7.centos.plus"
        ]
    },
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "cacheonly": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [
                "centosplus"
            ],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "python-perf-3.10.0-1160.88.1.el7.centos.plus"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "sslverify": true,
            "state": "present",
            "update_cache": false,
            "update_only": false,
            "use_backend": "auto",
            "validate_certs": true
        }
    },
```

Tested with ansible-core 2.15.5.
