### ISSUE TITLE
ansible.builtin.apt: deb: files/XYZ.deb should use file provided by ansible

### ISSUE THREAD

**Issue by APN-Pucky** [ansible/ansible#82206]
### Summary

I want to install a deb file that is stored in my repo/role's `files/`. Intuitively, I'd expect
```
- name: Install XYZ
  ansible.builtin.apt:
    deb: files/XYZ.deb
    state: present
```
to work, but it does not.
Currently my workaround is to copy it to `/tmp` first, but using `files` would be a lot nicer.
Cheers, APN

### Issue Type

Feature Idea

### Component Name

apt

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
