### ISSUE TITLE
Invoking "apt" only once while using a loop via squash_actions is deprecated

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [ansible/ansible#82216]
### Summary

Using `apt` module with a loop results in a warning:
```
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated.
Instead of using a loop to supply multiple items and specifying `name: "{{ item }}"`,
please use `name: '{{ list_var }}'` and remove the loop.
This feature will be removed in version 2.11.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

I think we should be possible to use loop with this module, it shouldn't be deprecated.
The cases:

1. What about the situation where some packages have versions ? (i.e. when `apt` module options depend on the package name)
```yaml
- name: install packages
  apt:
    name: '{{ item }}'
    state: '{{ (item is match(".*=.*")) | ternary("present", "latest") }}'
    force: yes
  with_items:
    - package1
    - package2=1.2.3-r2
    - package3=3.2.1-r3
    - package4
```
2. What if you need to install a long list of packages (for example ~100 packages)
- with loop: you will see a progress of installation (package by package)
- without loop: you will see that ansible hangs without any output for a **LONG time** - how to determine if it is actually stuck on something (ssh connection problem, remote I/O problem, ...) and needs to be aborted or it is working and shouldn't be aborted ?

I think users should have a possibility to use loop with `apt` module.

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/project/ansible.cfg) = True
DEFAULT_EXECUTABLE(/project/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/project/ansible.cfg) = 10
DEFAULT_NO_TARGET_SYSLOG(/project/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/project/ansible.cfg) = debug
DEFAULT_STRATEGY(/project/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/project/ansible.cfg) = [u'/usr/local/mitogen/ansible_mitogen/plugins/strategy']
HOST_KEY_CHECKING(/project/ansible.cfg) = False
INTERPRETER_PYTHON(/project/ansible.cfg) = /usr/bin/python3
TRANSFORM_INVALID_GROUP_CHARS(/project/ansible.cfg) = ignore
```

### OS / Environment

Ubuntu 18.04.4 LTS

### Steps to Reproduce

```yaml (paste below)
- name: install packages
  apt:
    name: '{{ item }}'
    state: '{{ (item is match(".*=.*")) | ternary("present", "latest") }}'
    force: yes
  with_items:
    - package1
    - package2=1.2.3-r2
    - package3=3.2.1-r3
    - package4
```

### Expected Results

No any warning, no deprecation in future versions.

### Actual Results

```console
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: "{{ item }}"`, please use `name: '{{ list_var }}'` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
