### ISSUE TITLE
Permit variable interpolation in hosts field in playbooks in collections

### ISSUE THREAD

**Issue by boite** [ansible/ansible#82219]
### Summary

I would like to create a collection that provides playbooks.  In those playbooks, I don't want to hardcode the values of `hosts:` because I want the playbooks to be reusable.  Integrators using the collection must be able to choose the hosts to which to apply the collection playbooks.

Ansible docs give a [few recommendations for the creation of playbooks in collections](https://docs.ansible.com/ansible/latest/collections_guide/collections_using_playbooks.html), one of which is
> `hosts:` should be generic or at least have a variable input.

There isn't an example of using a non-magic variable in that doc, but it would be nice if it were possible:

```yaml
# my group_vars/all
acme_collection_hosts: webservers_and_loadbalancers

# my site.yaml
- import_playbook: acme.collection.playbook

# acme.collection.playbook (runs on webservers_and_loadbalancers)
- name: Fun stuff
  hosts: "{{ acme_collection_hosts }}"
  # perhaps
  # hosts: acme_collection_hosts
  tasks:
    - ...
```

The collection just needs to document that integrators need to set the `acme_collection_hosts` var to whatever host/group name they wish.

### Issue Type

Feature Idea

### Component Name

import_playbook

### Additional Information

Right now, this isn't possible with Ansible 8 /2.15.  The error is:
```console
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. 
The error was: 'acme_collection_hosts' is undefined.
```

The workaround right now is to set the var where the playbook is imported:

```
# my site.yaml
- import_playbook: acme.collection.playbook
  vars:
    acme_collection_hosts: webservers_and_loadbalancers
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
