### ISSUE TITLE
set_fact not expanding the first item in loop

### ISSUE THREAD

**Issue by jonlarsdizparc** [ansible/ansible#82247]
### Summary

The `set_fact` module does not seem to expand the first item when a loop is used to append to a list.

### Issue Type

Bug Report

### Component Name

ansible.builtin.set_fact

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.6]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/ansible/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Debian 12.2

### Steps to Reproduce

**/home/ansible/ansible/roles/baselines/baseline_windows_server/defaults/main.yaml**
```yaml
---
# which baseline levels to use for the server
baseline_risklevels: [1,2]
```

**/home/ansible/ansible/roles/baselines/baseline_windows_server/tasks/main.yaml**
```yaml
---
- name: Populate list with baseline risklevel directories
  ansible.builtin.set_fact:
    baseline_directories: "{{ baseline_directories | default([]) + ['{{ role_path }}/tasks/risklevel_{{ level }}'] }}"
  loop: "{{ baseline_risklevels }}"
  loop_control:
    loop_var: level

- name: Populate list with baseline risklevel files
  ansible.builtin.set_fact:
    baseline_files: "{{ baseline_files | default([]) + [ lookup('ansible.builtin.fileglob', '{{ path }}/*.yaml') ] }}"
  loop: "{{ baseline_directories }}"
  loop_control:
    loop_var: path
```

### Expected Results

First item ('1') should be expanded as well as `{{ role_path }}`. Done on second item, but not on first.

### Actual Results

```console
TASK [baseline_windows_server : Populate list with baseline risklevel directories] *********************************************************************************************************************************
task path: /home/ansible/ansible/roles/baselines/baseline_windows_server/tasks/main.yaml:2
ok: [server] => (item=1) => {
    "ansible_facts": {
        "baseline_directories": [
            "{{ role_path }}/tasks/risklevel_{{ level }}"
        ]
    },
    "ansible_loop_var": "level",
    "changed": false,                                                                                                                                                                                                   "level": 1
}
ok: [server] => (item=2) => {
    "ansible_facts": {                                                                                                                                                                                                      "baseline_directories": [
            "/home/ansible/ansible/roles/baselines/baseline_windows_server/tasks/risklevel_2",
            "{{ role_path }}/tasks/risklevel_{{ level }}"
        ]
    },
    "ansible_loop_var": "level",
    "changed": false,
    "level": 2
}

TASK [baseline_windows_server : Populate list with baseline risklevel files] ***************************************************************************************************************************************
task path: /home/ansible/ansible/roles/baselines/baseline_windows_server/tasks/main.yaml:9
fatal: [server]: FAILED! => {
    "msg": "['/home/ansible/ansible/roles/baselines/baseline_windows_server/tasks/risklevel_2', '{{ role_path }}/tasks/risklevel_{{ level }}']: 'level' is undefined. 'level' i
s undefined. ['/home/ansible/ansible/roles/baselines/baseline_windows_server/tasks/risklevel_2', '{{ role_path }}/tasks/risklevel_{{ level }}']: 'level' is undefined. 'level'
is undefined"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
