### ISSUE TITLE
delegate_to group works only with lower case group names

### ISSUE THREAD

**Issue by Bludator** [ansible/ansible#82259]
### Summary

Using group from inventory with upper case characters in `delegate_to` does not work.
e.g. `delegate_to: myGroup` 
I have to use `delegate_to: mygroup` instead, which oddly works.

### Issue Type

Bug Report

### Component Name

delegate_to

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.0]
  config file = /root/codes/blupi/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /root/codes/blupi/ansible.cfg
DEFAULT_BECOME_METHOD(/root/codes/blupi/ansible.cfg) = community.general.doas
DEFAULT_ROLES_PATH(/root/codes/blupi/ansible.cfg) = ['/root/codes/blupi/roles', '/root/codes/blupi/functions', '/usr/share/ansible/roles', '/etc/ansible/roles']
PAGER(env: PAGER) = less
```

### OS / Environment

Ubuntu 22.04.3 LTS

### Steps to Reproduce

`playbook.yml`:
```yaml (paste below)
- name: Example Playbook
  hosts: foo
  tasks:
    - name: Task to be delegated to a group
      debug:
        msg: "This task is delegated to the group"
      delegate_to: myGroup

```
`inventory.yml`:
```yaml (paste below)
group:
    hosts:
        foo:
            ansible_host: b.example.com
            ansible_user: user
myGroup:
    hosts:
        bar:
            ansible_host: "192.168.0.1" 
            ansible_user: user
```

### Expected Results

```
ok: [foo-> myGroup] => {
    "msg": "This task is delegated to the group"
}
```

### Actual Results

```console
fatal: [foo-> myGroup]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname myGroup: Name or service not known", "unreachable": true}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
