### ISSUE TITLE
Variable precedence rules for set_fact are far too high

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible#82262]
### Summary

So I found one cause of this: if you use set_fact to configure ansible_become at any point in your playbook, roles or anything else.

Due to variable precedence orders, [set_fact overrides, amongst other things, task variables](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable).

This manifests as an infinite freeze when you wind up waiting on a sudo prompt you don't expect (I see this when switching to connection: local to do some controller specific thing and it tries to sudo).

This is documented, in the sense that it's out there, but it seems absolutely bonkers insane to me: an event which might happen hundreds of playbook tasks ago can apparently override explicit variable specifications on the task in front of you.

Of note: #30411 - the symptoms - has been my common experience of this problem. Ansible attempts sudo in a context where sudo isn't expected, and rather then failing simply hangs forever. It's always resolved by checking my become management, but requires numerous set_fact/task/set_fact blocks to work around.

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
ansible [core 2.15.6]
  config file = /home/will/tmp/ansible.cfg
  configured module search path = ['/home/will/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/.cache/pypoetry/virtualenvs/tmp-RBtO6tdG-py3.10/lib/python3.10/site-packages/ansible
  ansible collection location = /home/will/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/will/.cache/pypoetry/virtualenvs/tmp-RBtO6tdG-py3.10/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/will/.cache/pypoetry/virtualenvs/tmp-RBtO6tdG-py3.10/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
ANSIBLE_NOCOWS(/home/will/tmp/ansible.cfg) = True
CONFIG_FILE() = /home/will/tmp/ansible.cfg
```

### OS / Environment

Ubuntu, any Linux flavor, probably every OS

### Steps to Reproduce

```yaml
---
- hosts: all
  tasks:
  - name: Set fact here
    set_fact:
      ansible_become: true
  - name: Now do a local thing
    copy:
      dest: somefile.txt
      content: |
        somedata
    vars:
      ansible_become: false
    connection: local
  - name: This also won't work
    copy:
      dest: somefile.txt
      content: |
        somedata
    become: false
    connection: local
```

### Expected Results

The above playbook would be expected, from a cursory glance, to run a local command without executing sudo and write the file `somefile.txt`.

Instead, regardless of task-local variable modifiers, Ansible will *always* try to sudo. This not only supercedes "vars" blocks but also what look like system level directives like `become`.

One rogue `set_fact` can change the behavior of every downstream task, and can only be overridden by another `set_fact`.

The only way to supercede the set_fact practically is to use another set_fact:

```
---
- hosts: all
  tasks:
  - name: Set fact here
    set_fact:
      ansible_become: true
# There can be an infinite number of other blocks here before you *have* to remember to set_fact to undo whatever you did. No overrides work!
  - name: Set fact here
    set_fact:
      ansible_become: false
  - name: Now do a local thing
    copy:
      dest: somefile.txt
      content: |
        somedata
    vars:
      ansible_become: false
    connection: local
  - name: This also won't work
    copy:
      dest: somefile.txt
      content: |
        somedata
    become: false
    connection: local
```

### Actual Results

```console
PLAY [all] ***************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Set fact here] *****************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Now do a local thing] **********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Failed to get information on remote file (somefile.txt): sudo: a password is required\n"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/set_fact.py)
* [`lib/ansible/modules/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/set_fact.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#ansibotmini) bot command.

**Comment by flowerysong** [comment]
This is not a bug. The precedence of `set_fact` is well established and, (barring a massive overhaul and simplification of variable handling that is unlikely to ever happen), cannot change since doing so would break a large portion of existing Ansible content.

It's unfortunate that variable and keyword precedence is so complicated that it's difficult to develop an intuitive grasp of it, but that's not a situation that can be changed without causing more pain than it's worth.

As a general piece of advice, overuse of `set_fact` is a bad habit that a lot of people pick up when it's often better to use play-, block-, or task-level `vars`. You also shouldn't use `connection: local` except in very rare circumstances, since doing so has effects that may surprise you. Instead, use [delegation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_delegation.html#delegating-tasks).

```yaml
- hosts: all
  vars:
    ansible_become: true
  tasks:
  - name: Now do a local thing
    copy:
      dest: somefile.txt
      content: |
        somedata
    delegate_to: localhost
    vars:
      ansible_become: false
```
