### ISSUE TITLE
openssl_certificate cannot decrypt ownca privatekey

### ISSUE THREAD

**Issue by sonnenteich** [ansible/ansible#82277]
### Summary

When I try to run the task `openssl_certificate` in my ansible playbook with a vault encrypted _ownca_privatekey_path_-file I always get message `Wrong passphrase provided for private key`. 

When I run the same command with a decrypted _ownca_privatekey_path_-file it works like it should. 

I would expect that ansible decrypt my _ownca_privatekey_path_-file, but it seems something goes wrong. 

### Issue Type

Bug Report

### Component Name

openssl_certificate

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6] 
  config file = /home/xxx/.ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CALLBACKS_ENABLED(/home/xxx/.ansible.cfg) = ['timer']
DEFAULT_FORKS(/home/xxx/.ansible.cfg) = 80
DEFAULT_GATHERING(/home/xxx/.ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/home/xxx/.ansible.cfg) = ['!facter', '!ohai', '!hardware']
DEFAULT_HOST_LIST(/home/xxx/.ansible.cfg) = ['/home/xxx/ansible/hosts']
DEFAULT_LOG_PATH(/home/xxx/.ansible.cfg) = /home/xxx/ansible.log
DEFAULT_MANAGED_STR(/home/xxx/.ansible.cfg) = Ansible managed file: {file}
DEFAULT_POLL_INTERVAL(/home/xxx/.ansible.cfg) = 1
DEFAULT_ROLES_PATH(/home/xxx/.ansible.cfg) = ['/home/xxx/ansible/machines/roles', '/home/xxx/ansible/users/roles']
DEFAULT_STDOUT_CALLBACK(/home/xxx/.ansible.cfg) = debug
HOST_KEY_CHECKING(/home/xxx/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/xxx/.ansible.cfg) = False
SHOW_CUSTOM_STATS(/home/xxx/.ansible.cfg) = True
```

### OS / Environment

Debian bullseye

### Steps to Reproduce

```yaml (paste below)
- name: Generate an OpenSSL certificate signed with your own CA certificate
  openssl_certificate:
  path: /tmp/certs/internal.crt
  csr_path: /tmp/certs/internal.csr
  ownca_path: roles/ssl/files/ownca/My-CA.crt
  ownca_privatekey_path: roles/ssl/files/ownca/MyCA.key
  ownca_privatekey_passphrase: "{{ SECRET_CA_PASSWORD }}"
  provider: ownca
```

### Expected Results

I expect to accept the passphrase for the private key.

### Actual Results

```console
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

Wrong passphrase provided for private key
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
