### ISSUE TITLE
refresh_inventory stops further handlers

### ISSUE THREAD

**Issue by fabrykowski** [ansible/ansible#82281]
### Summary

When `ansible.builtin.meta: refresh_inventory` is one of the handlers, no subsequent handler is executed.

### Issue Type

Bug Report

### Component Name

ansible.builtin.meta

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/9.0.1/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.0 (main, Oct  2 2023, 12:03:24) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/Cellar/ansible/9.0.1/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
PAGER(env: PAGER) = less
```

### OS / Environment

macOS Sonoma 14.1.1

### Steps to Reproduce

```yaml
- name: Minimal reproducible example
  hosts: localhost
  tasks:
    - debug:
        msg: "Main"
      changed_when: true
      notify:
        - handler
  handlers:
    - debug:
        msg: "Before"
      listen:
        - handler
    - meta: refresh_inventory
      listen:
        - handler
    - debug:
        msg: "After"
      listen:
        - handler
```

### Expected Results

The third handler should output "After".

```
PLAY [Minimal reproducible example] ********************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [debug] *******************************************************************
changed: [localhost] => {
    "msg": "Main"
}

RUNNING HANDLER [debug] ********************************************************
ok: [localhost] => {
    "msg": "Before"
}

RUNNING HANDLER [meta] *********************************************************

RUNNING HANDLER [debug] ********************************************************
ok: [localhost] => {
    "msg": "After"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### Actual Results

```console
The third handler is never executed.



PLAY [Minimal reproducible example] ********************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [debug] *******************************************************************
changed: [localhost] => {
    "msg": "Main"
}

RUNNING HANDLER [debug] ********************************************************
ok: [localhost] => {
    "msg": "Before"
}

RUNNING HANDLER [meta] *********************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
