### ISSUE TITLE
Bug - wrong task name with handlers

### ISSUE THREAD

**Issue by Sda79** [ansible/ansible#82307]
### Summary

I could produce a bug with the following playbook and inventory : 

```yaml
---
- name: test reproduction bug
  hosts: all
  tasks:
    - name: block
      block:
        - name: 1_debug
          debug:
            msg: "1 debug msg"

        - name: 2_some changes
          debug:
            msg: "2 debug msg"
          changed_when: true
          notify: handlers

        - name: 3_fail
          failed_when: "inventory_hostname == 'fails'"
          debug:
            msg: "3 fail msg"

        - name: Flush handlers
          meta: flush_handlers

      always:
        - name: 5_debug
          debug:
            msg: "5 debug msg"

  handlers:
    - name: 4_handler_1
      debug:
        msg: "4 handler msg 1"
      listen: "handlers"

    - name: 4_handler_2
      debug:
        msg: "4 handler msg 2"
      listen: "handlers"
```

```yaml
---
all:
  hosts:
    success:
      ansible_host: 127.0.0.1
      ansible_user: foo
    fails:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_port: 2222
```

When the playbook is run (`ansible-playbook -i inventory.yaml playbook.yml`) : 
I get the result : 

```
PLAY [test reproduction bug] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
[WARNING]: Platform darwin on host success is using the discovered Python interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.16/reference_appendices/interpreter_discovery.html for more
information.
ok: [success]
ok: [fails]

TASK [1_debug] ***********************************************************************************************************************************************
ok: [success] => {
    "msg": "1 debug msg"
}
ok: [fails] => {
    "msg": "1 debug msg"
}

TASK [2_some changes] ****************************************************************************************************************************************
changed: [success] => {
    "msg": "2 debug msg"
}
changed: [fails] => {
    "msg": "2 debug msg"
}

TASK [3_fail] ************************************************************************************************************************************************
ok: [success] => {
    "msg": "3 fail msg"
}
fatal: [fails]: FAILED! => {
    "msg": "3 fail msg"
}

TASK [Flush handlers] ****************************************************************************************************************************************

RUNNING HANDLER [4_handler_1] ********************************************************************************************************************************
ok: [success] => {
    "msg": "4 handler msg 1"
}

RUNNING HANDLER [4_handler_2] ********************************************************************************************************************************
ok: [success] => {
    "msg": "4 handler msg 2"
}

TASK [4_handler_2] *******************************************************************************************************************************************
ok: [fails] => {
    "msg": "5 debug msg"
}

TASK [5_debug] ***********************************************************************************************************************************************
ok: [success] => {
    "msg": "5 debug msg"
}

PLAY RECAP ***************************************************************************************************************************************************
fails                      : ok=4    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
success                    : ok=7    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

We can observe that the the task `5_debug` on host `fails` is wrongly named: `4_handler_2`.

This playbook was run with python 3.11.6 and ansible version : 
```
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/Users/sylvaindaste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sylvaindaste/0-Perso/works/bug-ansible/bug-ansible-3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/sylvaindaste/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/sylvaindaste/0-Perso/works/bug-ansible/bug-ansible-3.11/bin/ansible
  python version = 3.11.6 (main, Nov 27 2023, 20:19:53) [Clang 15.0.0 (clang-1500.0.40.1)] (/Users/sylvaindaste/0-Perso/works/bug-ansible/bug-ansible-3.11/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Issue Type

Bug Report

### Component Name

handlers

### Ansible Version

```console
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/Users/sylvaindaste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sylvaindaste/0-Perso/works/bug-ansible/bug-ansible-3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/sylvaindaste/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/sylvaindaste/0-Perso/works/bug-ansible/bug-ansible-3.11/bin/ansible
  python version = 3.11.6 (main, Nov 27 2023, 20:19:53) [Clang 15.0.0 (clang-1500.0.40.1)] (/Users/sylvaindaste/0-Perso/works/bug-ansible/bug-ansible-3.11/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = None
```

### OS / Environment

Macos 14.1.1 (23B81)

### Steps to Reproduce

Playbook
```yaml
---
- name: test reproduction bug
  hosts: all
  tasks:
    - name: block
      block:
        - name: 1_debug
          debug:
            msg: "1 debug msg"

        - name: 2_some changes
          debug:
            msg: "2 debug msg"
          changed_when: true
          notify: handlers

        - name: 3_fail
          failed_when: "inventory_hostname == 'fails'"
          debug:
            msg: "3 fail msg"

        - name: Flush handlers
          meta: flush_handlers

      always:
        - name: 5_debug
          debug:
            msg: "5 debug msg"

  handlers:
    - name: 4_handler_1
      debug:
        msg: "4 handler msg 1"
      listen: "handlers"

    - name: 4_handler_2
      debug:
        msg: "4 handler msg 2"
      listen: "handlers"
```

Inventory file : 
```yaml
---
all:
  hosts:
    success:
      ansible_host: 127.0.0.1
      ansible_user: foo
    fails:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_port: 2222
```

### Expected Results

```yaml
PLAY [test reproduction bug] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
[WARNING]: Platform darwin on host success is using the discovered Python interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.16/reference_appendices/interpreter_discovery.html for more
information.
ok: [success]
ok: [fails]

TASK [1_debug] ***********************************************************************************************************************************************
ok: [success] => {
    "msg": "1 debug msg"
}
ok: [fails] => {
    "msg": "1 debug msg"
}

TASK [2_some changes] ****************************************************************************************************************************************
changed: [success] => {
    "msg": "2 debug msg"
}
changed: [fails] => {
    "msg": "2 debug msg"
}

TASK [3_fail] ************************************************************************************************************************************************
ok: [success] => {
    "msg": "3 fail msg"
}
fatal: [fails]: FAILED! => {
    "msg": "3 fail msg"
}

TASK [Flush handlers] ****************************************************************************************************************************************

RUNNING HANDLER [4_handler_1] ********************************************************************************************************************************
ok: [success] => {
    "msg": "4 handler msg 1"
}

RUNNING HANDLER [4_handler_2] ********************************************************************************************************************************
ok: [success] => {
    "msg": "4 handler msg 2"
}

TASK [5_debug] *******************************************************************************************************************************************
ok: [fails] => {
    "msg": "5 debug msg"
}

TASK [5_debug] ***********************************************************************************************************************************************
ok: [success] => {
    "msg": "5 debug msg"
}

PLAY RECAP ***************************************************************************************************************************************************
fails                      : ok=4    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
success                    : ok=7    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Actual Results

```console
PLAY [test reproduction bug] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
[WARNING]: Platform darwin on host success is using the discovered Python interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.16/reference_appendices/interpreter_discovery.html for more
information.
ok: [success]
ok: [fails]

TASK [1_debug] ***********************************************************************************************************************************************
ok: [success] => {
    "msg": "1 debug msg"
}
ok: [fails] => {
    "msg": "1 debug msg"
}

TASK [2_some changes] ****************************************************************************************************************************************
changed: [success] => {
    "msg": "2 debug msg"
}
changed: [fails] => {
    "msg": "2 debug msg"
}

TASK [3_fail] ************************************************************************************************************************************************
ok: [success] => {
    "msg": "3 fail msg"
}
fatal: [fails]: FAILED! => {
    "msg": "3 fail msg"
}

TASK [Flush handlers] ****************************************************************************************************************************************

RUNNING HANDLER [4_handler_1] ********************************************************************************************************************************
ok: [success] => {
    "msg": "4 handler msg 1"
}

RUNNING HANDLER [4_handler_2] ********************************************************************************************************************************
ok: [success] => {
    "msg": "4 handler msg 2"
}

TASK [4_handler_2] *******************************************************************************************************************************************
ok: [fails] => {
    "msg": "5 debug msg"
}

TASK [5_debug] ***********************************************************************************************************************************************
ok: [success] => {
    "msg": "5 debug msg"
}

PLAY RECAP ***************************************************************************************************************************************************
fails                      : ok=4    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
success                    : ok=7    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
