### ISSUE TITLE
Get delegated host as magic var

### ISSUE THREAD

**Issue by sathieu** [ansible/ansible#82313]
### Summary

I'm trying to construct the `ansible_user` variable dynamicaly from other variables (vlan, data-center, whatever).

When using `delegate_to`, this connection variable is evaluated with the `inventory_hostname` set to caller which is by design.

However I need access to the `delegate_to` parameter as variable.

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

inventory :

```yaml
local_user: "{{ lookup('env', 'USER') }}'
user_prefix: "{% if host_dc == 1 %}AD1_{% endif %}"
ansible_user: "{{ user_prefix }}{{ local_user }}"
```

task:

```yaml
- template:
    src: mysrc.j2
    dest: /tmp/mydest
  delegate_to: host_in_dc1
```  

Here `host_dc` is evaluated in the context of the caller host.

If a new variable `delegate_to_hostname` was defined we would change the inventory to:

```yaml
local_user: "{{ lookup('env', 'USER') }}'
user_prefix: "{% if hostvars[delegate_to_hostname].host_dc == 1 %}AD1_{% endif %}"
ansible_user: "{{ user_prefix }}{{ local_user }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
