### ISSUE TITLE
Tags selector with "and" strategy

### ISSUE THREAD

**Issue by FlorianPerrot** [ansible/ansible#82318]
### Summary

I have a use case where it is necessary to select many tags `--tags` with AND condition, not OR.

### Issue Type

Feature Idea

### Component Name

tags

### Additional Information

Use case example: 

```yaml
# playbook
- hosts: all
  roles:
    - role: my_role
      foo: bar1
      tags: my_role_bar1

    - role: my_role
      foo: bar2
      tags: my_role_bar2

    - role: my_role
      foo: bar3
      tags: my_role_bar3

    # ... others roles
```

```yaml
# role/my_role/tasks/main.yml
- name: Slow task 
  ansible.builtin.pause:
    minutes: 1

- name: Post task 
  ansible.builtin.pause:
    seconds: 1
  tags: post_task
```

I want to run task with the tag `post_task` of the role with tags `my_role_bar1`.
- I can't use `--tags my_role_bar1,post_task` because "Slow task" will be run.
- It's not ideal to use `--tags=post_task --skip-tags=my_role_bar2,my_role_bar3` because i have many other roles with tags `my_role_barX`.

Same request :
- https://stackoverflow.com/questions/30036126/how-can-i-run-only-ansible-tasks-with-multiple-tags

# Proposal

- Add config, example: `TAGS_AND_STRATEGY` False by default. 
- Add arg, example: `--with-tags` 
- Best proposition ?

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
