### ISSUE TITLE
Register on skipped task to not be done.

### ISSUE THREAD

**Issue by aklakina** [ansible/ansible#82328]
### Summary

Let's start by having a general playbook for unified systems. This can be os independent. Mostly. Now let's think of a scenario where you have to read a file.
```yml
- name: read file win
  win_shell: |
    *do stuff*
  register: file
  when: *check if windows*
- name: read file linux
  shell: |
    *do same stuff but on linux*
  register: file
  when: *check if linux*
*and then process the file*
```
Currently this role would fail if the os was windows because the second task overrides the first register with task has been skipped.
There has been multiple bug tickets, mailings, feature requests even back from 2018 to turn this off.
To name a few: #17500 #4297 #15195 

# Why is this a nonsense
If a task is skipped you can also just write the when statement of that task into the when statement of the second task. If the when statement is too long or complex one will use set_fact to store it's value either way.

Please turn this feature off or give an example playbook where it is really useful and makes life easier.

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

```yaml (paste below)
- name: read file win
  win_shell: |
    *do stuff*
  register: file
  when: *check if windows*
- name: read file linux
  shell: |
    *do same stuff but on linux*
  register: file
  when: *check if linux*
*and then process the file*
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
