### ISSUE TITLE
add when_all and when_either and move jinja2 operators to yaml nodes for tree-style logic.

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#82333]
### Summary

Currently tasks only support the `when` keyword to make them conditional. Specifying a list will result in all of the list items having to be true. Because a logical `AND` is not always the desired option I'd like to request the addition of both `when_all` and `when_either` to allow both a logical `AND` and `OR`.

The main addition is the 2nd one `when_either` which similarly to the current `when` will accept a list but instead of a logical `AND` will do a logical `OR`.
The `when_all` should be added for clarity reasons to make be self documenting and clearly indicate that the list items are processed using a logical `AND`.

The current `when` either becomes just an alias for `when_all`, or could be extended to support logic like shown below in the Additional Information section. This wouldn't be a breaking change, as that syntax isn't valid atm and when parsing everything that contains a list and isn't just a string can be considered a keyword. And thereby be automatically transformed by Ansible into the "ugly" (current) format. Therefore the keywords like `AND` and `OR` in this example would just be the current jinja2 operators (written in all upper case by convention). And therefore it is also easily extendable.

For comparison this is the current syntax that is uglier and more confusing to read.
```yaml
when:
  - is_foo|default(true)
  - is_bar|default(false) or (is_foobar|default(true) and is_barfoo|default(false))
```

### Issue Type

Feature Idea

### Component Name

core, when

### Additional Information

```yaml
- debug:
    msg: 'Hello World'
  when:
    - AND:
        - is_foo|default(true)
        - OR:
          - is_bar|default(false)
          - AND:
            - is_foobar|default(true)
            - is_barfoo|default(false)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
