### ISSUE TITLE
ansible-test sanity should allow multiple documents in EXAMPLES

### ISSUE THREAD

**Issue by tremble** [ansible/ansible#82353]
### Summary

EXAMPLES are intended to be copy-and-paste ready.

While most of the documentation is expected to be a single document, it's reasonable to expect that within examples (especially for inventory plugins), there may be multiple documents in there.  If only a single document is permitted, then when multiple examples are added for an inventory plugin, attempting to lint the YAML results in key-duplicates errors.

See also https://github.com/ansible/ansible-lint/issues/3860

### Issue Type

Feature Idea

### Component Name

ansible-test

### Additional Information

```yaml (paste below)
EXAMPLES = r""" 
---

# Example using groups to assign the running hosts to a group based on vpc_id
plugin: amazon.aws.aws_ec2
profile: aws_profile
# Populate inventory with instances in these regions
regions:
  - us-east-2
filters:
  # All instances with their state as `running`
  instance-state-name: running
keyed_groups:
  - prefix: tag
    key: tags
compose:
  ansible_host: public_dns_name
groups:
  libvpc: vpc_id == 'vpc-####'

---

# Define prefix and suffix for host variables coming from AWS.
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
hostvars_prefix: 'aws_'
hostvars_suffix: '_ec2'
"""
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
