### ISSUE TITLE
TOML Inventory creates extra empty invalid groups

### ISSUE THREAD

**Issue by evilhamsterman** [ansible/ansible#82373]
### Summary

When using the toml inventory plugin, at least with recent versions of python, extra groups are create like `all.vars` or `groupname.hosts`

### Issue Type

Bug Report

### Component Name

ansible.builtin.toml

### Ansible Version

```console
ansible [core 2.16.1]
  config file = /workspaces/work/ansible.cfg
  configured module search path = ['/workspaces/work/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /workspaces/work/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /workspaces/workt/.ansible/collections:/usr/share/ansible/collections
  executable location = /workspaces/work/.venv/bin/ansible
  python version = 3.12.0 (main, Nov  1 2023, 12:56:53) [GCC 12.2.0] (/workspaces/work/.venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
ACTION_WARNINGS(/workspaces/work/ansible.cfg) = True
ANSIBLE_HOME(env: ANSIBLE_HOME) = /workspaces/work/.ansible
CALLBACKS_ENABLED(/workspaces/work/ansible.cfg) = ['timer', 'yaml', 'community.general.log_plays']
CONFIG_FILE() = /workspaces/work/ansible.cfg
DEFAULT_FORKS(/workspaces/work/ansible.cfg) = 10
DEFAULT_STDOUT_CALLBACK(/workspaces/work/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/workspaces/work/ansible.cfg) = /workspaces/work/vault-pass
EDITOR(env: EDITOR) = code --wait
HOST_KEY_CHECKING(/workspaces/work/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/workspaces/work/ansible.cfg) = False

ssh:
___
host_key_checking(/workspaces/work/ansible.cfg) = False
```

### OS / Environment

Any

### Steps to Reproduce

```toml
# Example 1 from the documentation https://docs.ansible.com/ansible/latest/collections/ansible/builtin/toml_inventory.html
[all.vars]
has_java = false

[web]
children = [
    "apache",
    "nginx"
]
vars = { http_port = 8080, myvar = 23 }

[web.hosts]
host1 = {}
host2 = { ansible_port = 222 }

[apache.hosts]
tomcat1 = {}
tomcat2 = { myvar = 34 }
tomcat3 = { mysecret = "03#pa33w0rd" }

[nginx.hosts]
jenkins1 = {}

[nginx.vars]
has_java = true
```

Run `ansible-inventory -i inventory.toml --graph`

### Expected Results

```
@all:
  |--@ungrouped:
  |--@web:
  |  |--@apache:
  |  |  |--tomcat1
  |  |  |--tomcat2
  |  |  |--tomcat3
  |  |--@nginx:
  |  |  |--jenkins1
  |  |--host1
  |  |--host2
```

### Actual Results

```console
Not replacing invalid character(s) "{'.'}" in group name (all.vars)
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Not replacing invalid character(s) "{'.'}" in group name (all.vars)
Parsed /workspaces/Eng-Desktop-Management/playground/test.toml inventory source with toml plugin
@all:
  |--@ungrouped:
  |--@all.vars:
  |--@web:
  |  |--@apache:
  |  |  |--tomcat1
  |  |  |--tomcat2
  |  |  |--tomcat3
  |  |--@nginx:
  |  |  |--jenkins1
  |  |--host1
  |  |--host2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
