### ISSUE TITLE
error not returned if jinja default used

### ISSUE THREAD

**Issue by jon-nfc** [ansible/ansible#82389]
### Summary

When using jinja variable with default i.e. `{{ non_existing_var_random_name | default('any type or value') }}` and the variable would have created an error if default was not specified. No error is returned and the default value as specified is returned.

using `ignore_errors=false` has no effect.

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
$ (python_venv) sysadmin@laptop2:~/git/project-production$ ansible --version
ansible [core 2.16.1]
  config file = /home/sysadmin/git/project-production/ansible.cfg
  configured module search path = ['/home/sysadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sysadmin/git/python_venv/lib/python3.11/site-packages/ansible
  ansible collection location = /etc/ansible/collections:/runner/collections:/home/sysadmin/.ansible/collections/ansible_collections
  executable location = /home/sysadmin/git/python_venv/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/sysadmin/git/python_venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
(python_venv) sysadmin@laptop2:~/git/project-production$
```

### Configuration

```console
(python_venv) sysadmin@laptop2:~/git/project-production$ ansible-config dump --only-changed -t all
COLLECTIONS_PATHS(/home/sysadmin/git/project-production/ansible.cfg) = ['/etc/ansible/collections', '/runner/collections', '/home/sysadmin/.ansible/collections/ansible_collections']
CONFIG_FILE() = /home/sysadmin/git/project-production/ansible.cfg
DEFAULT_LOG_PATH(/home/sysadmin/git/project-production/ansible.cfg) = /home/sysadmin/ansible.log
DEFAULT_ROLES_PATH(/home/sysadmin/git/project-production/ansible.cfg) = ['/etc/ansible/roles', '/runner/roles', '/workdir/roles', '/home/sysadmin/aa-shits-and-gigs/ansible-roles-repo']
HOST_KEY_CHECKING(/home/sysadmin/git/project-production/ansible.cfg) = False
INVENTORY_ENABLED(/home/sysadmin/git/project-production/ansible.cfg) = ['yaml', 'script']
INVENTORY_IGNORE_PATTERNS(/home/sysadmin/git/project-production/ansible.cfg) = ['gitlab-ci/*']
SHOW_CUSTOM_STATS(/home/sysadmin/git/project-production/ansible.cfg) = True

CALLBACK:
========

default:
_______
show_custom_stats(/home/sysadmin/git/project-production/ansible.cfg) = True

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/sysadmin/git/project-production/ansible.cfg) = False

ssh:
___
host_key_checking(/home/sysadmin/git/project-production/ansible.cfg) = False
```

### OS / Environment

debian 12 Bash and AWX 23.5.1

### Steps to Reproduce

```yaml (paste below)
---
- name: Test hiding error with default
  hosts: localhost
  gather_facts: true
  vars:
    ansible_connection: local
    existing_var_random_name: 
      - 'a value here'
      - 'b value here'
      - "{{ this_var_doesnt_exist }}"


  tasks:


    - name: debug existing var with undefined var that should error
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name | default([]) }}" 
        - "{{ existing_var_random_name | default([]) | length }}" 
        - "{{ existing_var_random_name | default([]) | length | int }}" 
        - "{{ existing_var_random_name | default([]) | length | int > 0 }}" 


    - name: debug existing var with undefined var that should error (ignore_error=false)
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name | default([]) }}" 
        - "{{ existing_var_random_name | default([]) | length }}" 
        - "{{ existing_var_random_name | default([]) | length | int }}" 
        - "{{ existing_var_random_name | default([]) | length | int > 0 }}"
      ignore_errors: false


    - name: debug should error but doesn't string
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name| default('string') }}" 


    - name: debug now shows error as default not hiding
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name }}" 
        - "{{ existing_var_random_name | default([]) }}" 
        - "{{ existing_var_random_name | default([]) | length }}" 
        - "{{ existing_var_random_name | default([]) | length | int }}" 
        - "{{ existing_var_random_name | default([]) | length | int > 0 }}" 

```

`ansible-playbook test.yaml -vvv`

### Expected Results

that if an error would have been presented if `default()` was not used, that the error still be presented if `default()` is used

### Actual Results

```console
ansible-playbook [core 2.16.1]
  config file = /home/sysadmin/git/project-production/ansible.cfg
  configured module search path = ['/home/sysadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sysadmin/git/python_venv/lib/python3.11/site-packages/ansible
  ansible collection location = /etc/ansible/collections:/runner/collections:/home/sysadmin/.ansible/collections/ansible_collections
  executable location = /home/sysadmin/git/python_venv/bin/ansible-playbook
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/sysadmin/git/python_venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/sysadmin/git/project-production/ansible.cfg as config file
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: backup-test.yaml ****************************************************************************************************************************************************************************************
1 plays in /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml

PLAY [Test hiding error with default] *****************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: sysadmin
<127.0.0.1> EXEC /bin/sh -c 'echo ~sysadmin && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sysadmin/.ansible/tmp `"&& mkdir "` echo /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921 `" && echo ansible-tmp-1702141519.557717-224195-172826351344921="` echo /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921 `" ) && sleep 0'
Using module file /home/sysadmin/git/python_venv/lib/python3.11/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/sysadmin/.ansible/tmp/ansible-local-224192wmwwgrik/tmpb7pwpm6k TO /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/ /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/sysadmin/git/python_venv/bin/python3 /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [debug existing var with undefined var that should error] ****************************************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:16
ok: [localhost] => {
    "msg": [
        [],
        "0",
        "0",
        false
    ]
}

TASK [debug existing var with undefined var that should error (ignore_error=false)] *******************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:25
ok: [localhost] => {
    "msg": [
        [],
        "0",
        "0",
        false
    ]
}

TASK [debug should error but doesn't string] **********************************************************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:35
ok: [localhost] => {
    "msg": [
        "string"
    ]
}

TASK [debug now shows error as default not hiding] ****************************************************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:41
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: ['a value here', 'b value here', '{{ this_var_doesnt_exist }}']: 'this_var_doesnt_exist' is undefined. 'this_var_doesnt_exist' is undefined. ['a value here', 'b value here', '{{ this_var_doesnt_exist }}']: 'this_var_doesnt_exist' is undefined. 'this_var_doesnt_exist' is undefined\n\nThe error appears to be in '/home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml': line 41, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: debug now shows error as default not hiding\n      ^ here\n"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

edit: 
1. added awx environment
2. Added the correct playbook (and play output) as its the nested var that creates the error that should not be hidden.

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
This is not a bug, this is the entire purpose of `default()`; it provides a default if the variable is undefined.

If you don't want to provide a default value, don't use `default()`.

**Comment by jon-nfc** [comment]
> This is not a bug, this is the entire purpose of `default()`; it provides a default if the variable is undefined.
> 
> If you don't want to provide a default value, don't use `default()`.

My mistake, I forgot the nesting. description updated to reflect the actual problem.

**Comment by flowerysong** [comment]
This is still not a bug, though it is something that has changed relatively recently. See the second bullet point in https://docs.ansible.com/ansible-core/2.14/porting_guides/porting_guide_core_2.14.html#playbook

A "partially defined" variable is now consistently treated as undefined, so the behaviour you're seeing is expected.

**Comment by jon-nfc** [comment]
> This is still not a bug, though it is something that has changed relatively recently. See the second bullet point in https://docs.ansible.com/ansible-core/2.14/porting_guides/porting_guide_core_2.14.html#playbook

in what part of the link above does it state your quote below?? as this links example is not even the same
 
> A "partially defined" variable is now consistently treated as undefined, so the behaviour you're seeing is expected.

the issue is that in my example `existing_var_random_name` is defined and exists so should be returned, however contains an undefined variable `this_var_doesnt_exist` without a default which causes an error as it should. The bug in this case is that the default value for variable  `existing_var_random_name` is used when it should error

**Comment by flowerysong** [comment]
The example is exactly what you're experiencing.

> One particular case of a change in behavior to note is the task below which uses the undefined test. Prior to version 2.14 this would result in a fatal error trying to access the undefined value in the dictionary. In 2.14 the assertion passes as the dictionary is evaluated as undefined through one of its undefined values:

```
- assert:
    that:
      - some_defined_dict_with_undefined_values is undefined
  vars:
    dict_value: 1
    some_defined_dict_with_undefined_values:
      key1: value1
      key2: '{{ dict_value }}'
      key3: '{{ undefined_dict_value }}'
```

This is a partially defined variable ("contains an undefined variable") and is now evaluated as undefined.

```yaml
- debug:
    msg: "{{ some_defined_dict_with_undefined_values | default('') }}"
  vars:
    dict_value: 1
    some_defined_dict_with_undefined_values:
      key1: value1
      key2: '{{ dict_value }}'
      key3: '{{ undefined_dict_value }}'
```
Since `some_defined_dict_with_undefined_values` is undefined, `default()` applies to it the same way it applies to any undefined variable, and does not produce an error.

**Comment by jon-nfc** [comment]
And what you've show should produce an error not be hidden. This is the crux of what I am reporting.

This hasn't been the case since 2.14, as i just upgraded from 2.14.5 and it wasn't present. now I'm getting errors on awx and cli because of. This is new as the cve clearly shows `CVE-2023-5764` which isn't even a month old.

Why anyone would think it's a good idea to hide an error from the end user is beyond me.  There is nothing wise about this at all. This "so called feature" is going to create a headach and not just for me; as all playbooks need to be reviewed and additional tasks put in place to cater for checking that sub-variables exist before use. which is completely absurd as it should be captured at runtime like it used to.

If this indeed as you say "not a bug but a feature", that has clearly just been introduced I'm still reporting this as a bug or if you like a "feature request" not to hide errors behind a function that you can't control. I have never seen or even heard of this occuring in any application.

bottom line an error is an error and in any application if the error is not specifically handled then execution must cease. 

extended playbook from OP as a further example of hiding errors

``` yaml
---
- name: Test hiding error with default
  hosts: localhost
  gather_facts: true
  vars:
    ansible_connection: local
    existing_var_random_name:
      - 'a value here'
      - 'b value here'
      - "{{ this_var_doesnt_exist }}"
    another_existing_variable: |
      this variable exists and has a default value specified.
      however, I'm now going to include an undefined variable
      here {{ variable_that_doesnt_exist }}. This should cause
      an error and not be hidden by the default jinja function.


  tasks:


    - name: debug existing var with undefined var that should error
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name | default([]) }}"
        - "{{ existing_var_random_name | default([]) | length }}"
        - "{{ existing_var_random_name | default([]) | length | int }}"
        - "{{ existing_var_random_name | default([]) | length | int > 0 }}"


    - name: debug existing var with undefined var that should error (ignore_error=false)
      ansible.builtin.debug:
        msg:
        - "{{ existing_var_random_name | default([]) }}"
        - "{{ existing_var_random_name | default([]) | length }}"
        - "{{ existing_var_random_name | default([]) | length | int }}"
        - "{{ existing_var_random_name | default([]) | length | int > 0 }}"
      ignore_errors: false


    - name: debug should error but doesn't string
      ansible.builtin.debug:
        msg:
        - "{{ existing_var_random_name| default('string') }}"


    - name: debug existing var containing undefined var that should error and not have error hidden by default
      ansible.builtin.debug:
        msg:
        - "{{ another_existing_variable | default('') }}"



# Only have one test un commented at a time.


      # Test 1
    # - name: Test 1 - debug now shows error as default not hiding the error
    #   ansible.builtin.debug:
    #     msg: 
    #     - "{{ existing_var_random_name }}" 
    #     - "{{ existing_var_random_name | default([]) }}" 
    #     - "{{ existing_var_random_name | default([]) | length }}" 
    #     - "{{ existing_var_random_name | default([]) | length | int }}" 
    #     - "{{ existing_var_random_name | default([]) | length | int > 0 }}"

      # Test 2
    - name: Test 2 - debug now shows error as default not hiding the error
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name }}" 

```

as shown in the output of test 1 and test 2, they are errors that should not be hidden. However `{{ another_existing_variable | default('') }}` hides the error behind an empty strin in this case. this needs to be fixed.

**Comment by flowerysong** [comment]
The entire purpose of `default()` is to hide errors from undefined variables. Your variable is undefined. If you don't want to hide errors, don't use `default()`.

**Comment by jon-nfc** [comment]
> The entire purpose of `default()` is to hide errors from undefined variables. Your variable is undefined. If you don't want to hide errors, don't use `default()`.

wrong. `existing_var_random_name` is defined. `variable_that_doesnt_exist` isn't defined. however is part of `existing_var_random_name`. calling `existing_var_random_name` without default correctly errors. however using `existing_var_random_name | default('')` hides the error.
as `existing_var_random_name` exists, it's default value should not be used, just because there is an error. 

if `existing_var_random_name` was not defined at all, i.e. doesn't exist than that's then only time it's default value should be specified. 

``` bash
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: ['a value here', 'b value here', '{{ this_var_doesnt_exist }}']: 'this_var_doesnt_exist' is undefined. 'this_var_doesnt_exist' is undefined. ['a value here', 'b value here', '{{ this_var_doesnt_exist }}']: 'this_var_doesnt_exist' is undefined. 'this_var_doesnt_exist' is undefined\n\nThe error appears to be in '/home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml': line 67, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      # Test 2\n    - name: Test 1 - debug now shows error as default not hiding the error\n      ^ here\n"
}
```
just because default is used, the called variable exists, alas with an error, so should produce it not have it hidden behind default.

**Comment by flowerysong** [comment]
`existing_var_random_name` is not defined. You've attempted to define it but failed to do so, so it is not defined. It will cause an error if you use it in a place where a defined variable is required. Equally, if you use it in a place where an undefined variable is allowed, it will act like an undefined variable.

This is not how things used to work, but it is logically consistent and avoids having variables exist in a third state that's somewhere between "defined" and "undefined" and behaves differently than either.

**Comment by flowerysong** [comment]
Note that if you need to check whether an attempt at a definition exists but the variable is undefined, you can use `assert` to do so:

```yaml
- hosts: localhost
  vars:
    pdef:
      a: eh
      b: "{{ b }}"
    fdef:
      c: sea
  tasks:
    - assert:
        that: query('varnames', '^nodef$') == [] or nodef is defined

    - assert:
        that: query('varnames', '^fdef$') == [] or fdef is defined

    - assert:
        that: query('varnames', '^pdef$') == [] or pdef is defined
```

```
TASK [assert] ******************************************************************
ok: [localhost] =>
    changed: false
    msg: All assertions passed

TASK [assert] ******************************************************************
ok: [localhost] =>
    changed: false
    msg: All assertions passed

TASK [assert] ******************************************************************
fatal: [localhost]: FAILED! =>
    assertion: query('varnames', '^pdef$') == [] or pdef is defined
    changed: false
    evaluated_to: false
    msg: Assertion failed
```

**Comment by jon-nfc** [comment]
> `existing_var_random_name` is not defined. 

What? The very existence of `existing_var_random_name`  is a definition.

file.yaml
``` yaml
# defined. empty string
existing_var_random_name: ""

# defined. string
existing_var_random_name: "an array of chars"

# defined, empty list. The elements of the list are undefined, however the list is still defined.
existing_var_random_name: []

# defined, empty dict. The elements of the dict are undefined, however the dict is still defined.
existing_var_random_name: {}

# defined, string
existing_var_random_name: "{{ jinja_templating_var }}"

# defined, string
existing_var_random_name: "this is a valid yaml string too {{ jinja_templating_var }}"


```
The above code block are all valid yaml definitions for a string, list and dict. the presence of jinja barces `{{}}` within a string must be enclosed in braces. to the overall definition of the string object, the braces are irrelevant. bottom line All items in this yaml example are defined. An example using the yaml above of an undefined value??? any value not listed.

Any processing of the yaml must adhere to this. Why? it's the yaml way. If not, why use yaml at all.

> You've attempted to define it but failed to do so, so it is not defined. It will cause an error if you use it in a place where a defined variable is required. 

again what? this is yaml not a programming language. It's existance is a definition and it's a valid yaml string and must be treated as such.
The issue arises when the templating engine tries to process it, in this case jinja. It's not an undefined error, but that of not being able to template the object due to containing an undefined variable. The item being templated is clearly defined yaml object.


``` yaml
existing_var_random_name:
      - 'a value here'
      - 'b value here'
      - "{{ this_var_doesnt_exist }}"

another_existing_variable: |
      this variable exists and has a default value specified.
      however, I'm now going to include an undefined variable
      here {{ variable_that_doesnt_exist }}. This should cause
      an error and not be hidden by the default jinja function.
```

when both vars are templated, this is where the problem arises.

- `existing_var_random_name` is a valid definition for a yaml list of strings.
- `existing_var_random_name[2]` is a list element that is also a valid string
- when `existing_var_random_name` is templated the error arises from an element of the list, this error is that there is a variable that is undefined.
- `existing_var_random_name | default('')` should not hide this error as default or an undefined check should still pass as `existing_var_random_name` is a valid yaml list that is defined. it's got a templating error that should be displayed.

- `another_existing_variable` is a valid definition of a yaml string
- when `another_existing_variable`  is templated the error is not because it's undefined, its because `variable_that_doesnt_exist` doesn't exist or is undefined/not defined.
- using `another_existing_variable | default('')` should not hide this templating error. the item `another_existing_variable` is still a valid yaml definition for a string.

>Equally, if you use it in a place where an undefined variable is allowed, it will act like an undefined variable.
> This is not how things used to work, but it is logically consistent and avoids having variables exist in a third state that's somewhere between "defined" and "undefined" and behaves differently than either.

And herein lies the problem, existence of a valid declaration in yaml is being treated as undefined if there is an error from the templating engine. the crux of this entire issue.

Consistent, how so? Ansible in this case is treating a jinja templating error as an item that is not defined in the yaml document when it is and is valid yaml.
