### ISSUE TITLE
Ansible Network Connection Plugin need to be refined handling status logic.

### ISSUE THREAD

**Issue by mahoutukaisali** [ansible/ansible#82391]
### Summary

- Ansible connection helper regards the task status as "failed" when network appliances output includes specific keywords like “error”.  However, even if those outputs include "error" words, some commands succeed in running actually. 

### Issue Type

Feature Idea

### Component Name

ansible.module_utils.connection

### Additional Information

In this case, the below playbook will be regarded as `failed` because `request support information` command will include `error` words. However, `request support information` command itself actually succeeds.

```yaml 
- name: Capture support information
  junipernetworks.junos.junos_command:
    commands: "request support information"
```

Looking at the source code, I see this comes from the below logic. Are there any other ideas to handle tasks to avoid `failed` for the above case?
https://github.com/ansible/ansible/blob/v2.16.1/lib/ansible/module_utils/connection.py#L196

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by bcoca** [comment]
The code you pointed at is not looking for 'error' in the string response but a specific 'error' key returned by the networking code, this is the convention used and should not match any random appearances of the word 'error' in the output. 

Please add a simple full reproducer of your issue.

needs_info

**Comment by mahoutukaisali** [comment]
Hi @bcoca , here is the issue example.

playbook:
```
  tasks:
    - name: run show version on remote devices
      junipernetworks.junos.junos_command:
        commands: "request support information"
      register: rsi
```
A part of execution logs: 
```
(...)
show services advanced-anti-malware statistics\r\n\r\n\r\nerror: syntax error, expecting <command>: advanced-anti-malware\r\n\r\n{master}\r\nUSER@EXAMPLE.HOST.COM> "

PLAY RECAP *********************************************************************
USER@EXAMPLE.HOST.COM : ok=0    changed=0    unreachable=0   failed=1   skipped=0    rescued=0    ignored=0   
Please review the log for errors.
```

As you can see in the above execution logs, `show services advanced-anti-malware` command is launched by `request support information` command in Junos but it failed because of the syntax error. I know this is likely a bug of Junos, but   `request support information` command itself is successing, so I think the Ansible task should be regarded as `success`.
