### ISSUE TITLE
backup option: implement custom naming for files ( ansible_managed like )

### ISSUE THREAD

**Issue by andreagrax** [ansible/ansible#82408]
### Summary

This feature requests is based on  [issue 16305](https://github.com/ansible/ansible/issues/16305) but takes out of the way  the management of the permissions for the new files that would be created, since we are just adding more control over the naming scheme (except for #3, maybe )
It would be great if the naming of the backup file can be controlled via something similar to the [ansible_managed](https://docs.ansible.com/archive/ansible/2.4/intro_configuration.html#ansible-managed) inside the `ansible.cfg` 

in this way setting it I could address the following use cases:
1. decide to create a single backup file ( setting it to `${filename}.backup` ) 
2. change the format of the backup name  ( `$filename.$( date "+%s")`)
3.  change the path of the file ( `.backup/$filename.$( date "+%s")` . **Creation of the backup directory must be handled by another task** 

### Issue Type

Feature Idea

### Component Name

template, copy

### Additional Information

ansible.cfg 
```cfg
[defaults]
ansible_backup = {target_file}.%Y%m%d_%H%M%S
```

task.yml
```yaml 
- name: Apply the template
  hosts: your_hosts
  vars:
    dest_file: /path/to/your/file.conf

  tasks:
    - name: Apply the template
      template:
        src: your_template.j2
        dest: "{{ dest_file }}"
        backup: true
```

This will create `/path/to/your/file.conf.20231212.142835`

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/lookup/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/template.py)
* [`lib/ansible/plugins/action/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/copy.py)
* [`lib/ansible/plugins/action/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/template.py)
* [`lib/ansible/modules/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/template.py)
* [`lib/ansible/modules/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/copy.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by nightgryphon** [comment]
Any chances this will be implemented any soon? 
File naming with PID before timestamp completely mess the backup files order so that's become a pain to find the correct backup file to restore and produce human errors

**Comment by nkfilis** [comment]
> Any chances this will be implemented any soon? File naming with PID before timestamp completely mess the backup files order so that's become a pain to find the correct backup file to restore and produce human errors

probably not. there's a Pull Request to simply reverse the order of PID and timestamp: https://github.com/ansible/ansible/pull/82434 but it was closed instead of just merged. So no relief in sight apart from maintaining a private patch

**Comment by bcoca** [comment]
check PR linked above and test if this meets your needs

**Comment by andreagrax** [comment]
hello @bcoca , sorry for the late reply.

I am testing with this playbook :

```yaml
---
- name: Default empty playbook
  hosts: localhost
  become: false
  gather_facts: true

  tasks:

  - name: Copy using inline content
    ansible.builtin.copy:
      content: '{{ ansible_date_time.iso8601 }}'
      dest: /tmp/template
      backup: true

  - name: Copy using inline content
    ansible.builtin.copy:
      content: '{{ ansible_date_time.iso8601 }}'
      dest: /tmp/template
      backup: true
```


and this command from your branch :

```bash
[root@ebd71149a926 ~]# ANSIBLE_BACKUP_FILE_NAME_TEMPLATE='{basename}.{timestamp}.{pid}'  ANSIBLE_LOCALHOST_WARNING=False ANSIBLE_INVENTORY_UNPARSED_WARNING=False python3.11  ./ansible/bin/ansible-playbook  -e ansible_connection=local -i localhost, do.yml    ; ls -l /tmp/template*
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can become unstable at any point.

PLAY [Default empty playbook] **********************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************
[WARNING]: Platform linux on host localhost is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python
interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/devel/reference_appendices/interpreter_discovery.html for more
information.
ok: [localhost]

TASK [Copy using inline content] *******************************************************************************************************************************
changed: [localhost]

TASK [Copy using inline content] *******************************************************************************************************************************
ok: [localhost]

PLAY RECAP *****************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

-rw-r--r-- 1 root root 20 Mar  6 13:43 /tmp/template
-rw-r--r-- 1 root root 20 Mar  6 13:39 /tmp/template.1357.2025-03-06@13:43:17~
-rw-r--r-- 1 root root 20 Mar  6 13:43 /tmp/template.1458.2025-03-06@13:43:28~
-rw-r--r-- 1 root root 20 Mar  6 13:43 /tmp/template.1559.2025-03-06@13:43:36~
-rw-r--r-- 1 root root 20 Mar  6 13:43 /tmp/template.1660.2025-03-06@13:43:39~
```


But I guess that I'm setting wrong `ANSIBLE_BACKUP_FILE_NAME_TEMPLATE`
