### ISSUE TITLE
difference filter not behaving correctly

### ISSUE THREAD

**Issue by juresaht2** [ansible/ansible#82428]
### Summary

ansible.builtin.difference filter is not behaving as expected, when a list of strings is saved to file and then retrieved and compared with a variable.

I am permitting the possibility that I'm doing something wrong, however I was not able to figure this one out, especially with how the output looks.

### Issue Type

Bug Report

### Component Name

ansible.builtin.difference

### Ansible Version

```console
ansible [core 2.16.2]
  config file = /home/jsah/dev-jsah/ansible.cfg
  configured module search path = ['/home/jsah/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/jsah/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.5 (main, Oct 25 2023, 14:45:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-21)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = /home/jsah/dev-jsah/ansible.cfg
DEFAULT_NO_LOG(/home/jsah/dev-jsah/ansible.cfg) = False
DEFAULT_ROLES_PATH(/home/jsah/dev-jsah/ansible.cfg) = ['/home/jsah/dev-jsah/roles', '/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/jsah/dev-jsah/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/jsah/dev-jsah/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/jsah/dev-jsah/ansible.cfg) = False

ssh:
___
host_key_checking(/home/jsah/dev-jsah/ansible.cfg) = False
```

### OS / Environment

CentOS 8 stream machine, fully updated

### Steps to Reproduce

```yaml
---
- name: "debug"
  hosts: "localhost"
  vars:
    test_var:
      - "apple"
      - "pear"
      - "banana"
  tasks:
    - slurp:
        src: "/tmp/test_var"
      register: slurp_result

    - set_fact:
        old_var: "{{ slurp_result['content'] | b64decode }}"

    - set_fact:
        added_items: "{{ old_var | difference(test_var) }}"
        removed_items: "{{ test_var | difference(old_var) }}"

    - debug:
        msg: "{{ added_items }}"

    - debug:
        msg: "{{ removed_items }}"

    - copy:
        content: "{{ test_var | to_nice_yaml }}"
        dest: "/tmp/test_var"
```

### Expected Results

Assuming /tmp/test_var exists and contains what this script would write, I'd expect it to return two empty lists, as `test_var` contains the same list as the file.

### Actual Results

```console
PLAY [debug] **********************************************************************************************

TASK [Gathering Facts] ************************************************************************************
ok: [localhost]

TASK [slurp] **********************************************************************************************
ok: [localhost]

TASK [set_fact] *******************************************************************************************
ok: [localhost]

TASK [set_fact] *******************************************************************************************
ok: [localhost]

TASK [debug] **********************************************************************************************
ok: [localhost] => 
  msg:
  - l
  - p
  - e
  - ""
  - '-'
  - n
  - r
  - b
  - a
  - ' '

TASK [debug] **********************************************************************************************
ok: [localhost] => 
  msg:
  - banana
  - pear
  - apple

TASK [copy] ***********************************************************************************************
ok: [localhost]

PLAY RECAP ************************************************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
