### ISSUE TITLE
Lookup or filter variant of include_vars

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#82424]
### Summary

`include_vars` reads a file as YAML then renders Jinja inside string nodes and replaces them with results. There is no equivalent lookup or filter.

`lookup('template', file) | from_yaml` reads a file as Jinja, then parses YAML.

Please add equivalent of `include_vars` as a lookup and/or filter: `lookup('file', file) | read_vars`, `lookup('read_vars', file)`

### Issue Type

Feature Idea

### Component Name

base

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/cache/base.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/cache/base.py)
* [`lib/ansible/playbook/base.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/base.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by bcoca** [comment]
lookup data is considered 'unsafe' so we tag it as such to specifically avoid templating it. The `template` lookup doing the templating itself instead of relying on the main engine for it

**Comment by Vladimir-csp** [comment]
`vars_files` operates at play scope.

`include_vars` operates in runtime, which is basically play scope minus the temporal part that came before `include_vars` task is called.

If there is a need to pull vars from inside a template, or into value of `vars:` at task/block level, only template lookup is available. And one has to keep in mind that content structure for jinja>yaml has to be different from yaml>jinja with no simple file reuse.

**Comment by bcoca** [comment]
`include_vars` is host scoped

basically you are asking for a `template_unsafe`  or `make_safe' filter so the vars from `file` are templated or to have `vars_files` also at block/task level?

**Comment by Vladimir-csp** [comment]
Basically yes. Anything that can be scoped to block/task/template/value, but expects yaml with templated values (the same way as `vars_files` or `include_vars`).

**Comment by nitzmahone** [comment]
It's not really clear to us what exactly you're trying to accomplish- can you give a more concrete use case for why the existing `include_vars` doesn't do what you want?

**Comment by Vladimir-csp** [comment]
Reuse `vars/*.yaml` files in tasks or templates without having to mind different syntax. `include_vars` is yet another task, it wastes time and adds vars to wide context.

**Comment by s-hertel** [comment]
One existing way this could be accomplished is using a custom vars plugin. Whatever source it draws from (could be a file, or not) could be temporarily populated and then deleted. The `host_group_vars` vars plugin currently can't do this because 1) it caches vars files (so they can't be modified mid-play and take effect) and 2) loads the files as unsafe.

<details>
<summary>POC</summary>
<br>

```yaml
# {{ playbook_dir }}/playbook.yml
---
- hosts: all
  gather_facts: no
  tasks:
    - name: validate variable is undefined
      assert:
        that: myvar is undefined

    - name: create some vars
      delegate_to: localhost
      run_once: true
      block:
        - name: Create group_vars
          file:
            state: directory
            dest: "{{ playbook_dir }}/group_vars"
          # run POC in empty directory to avoid breaking your stuff
          register: existing_stuff
          failed_when: existing_stuff is not changed

        - name: Create group_vars/all.yml
          copy:
            content: |
              myvar: defined
            dest: "{{ playbook_dir }}/group_vars/all.yml"

    - block:
        - name: validate variable is defined
          assert:
            that: myvar is defined
      always:
        - name: Remove group_vars
          file:
            state: absent
            dest: "{{ playbook_dir }}/group_vars/"
          delegate_to: localhost
          run_once: True

    - name: validate variable is undefined
      assert:
        that: myvar is undefined
```

```python
# {{ playbook_dir }}/vars_plugins/unsafe_host_group_vars_no_cache.py

from ansible.plugins.vars import host_group_vars


def load_unsafe_no_cache(func):
    def wrapper(*args, **kwargs):
        kwargs['cache'] = False
        kwargs['unsafe'] = True
        return func(*args, **kwargs)
    return wrapper


# This is bad, just convenient for demo purposes. Don't use non-base plugin as base class, it might change any time.
class VarsModule(host_group_vars.VarsModule):
    REQUIRES_ENABLED = True

    def get_vars(self, loader, path, entities, cache=True):
        host_group_vars.NAK.clear()
        host_group_vars.FOUND.clear()

        loader_before = loader.load_from_file
        loader.load_from_file = load_unsafe_no_cache(loader.load_from_file)
        try:
            return super(VarsModule, self).get_vars(loader, path, entities, cache)
        finally:
            loader.load_from_file = loader_before
```

```bash
$ ANSIBLE_VARS_ENABLED=unsafe_host_group_vars_no_cache ansible-playbook -i host1,host2 playbook.yml

PLAY [all] **************************************************************************************************************************************************************************************************************************

TASK [validate variable is undefined] ***********************************************************************************************************************************************************************************************
ok: [host1] => {
    "changed": false,
    "msg": "All assertions passed"
}
ok: [host2] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Create group_vars] ************************************************************************************************************************************************************************************************************
changed: [host1 -> localhost]

TASK [Create group_vars/all.yml] ****************************************************************************************************************************************************************************************************
changed: [host1 -> localhost]

TASK [validate variable is defined] *************************************************************************************************************************************************************************************************
ok: [host1] => {
    "changed": false,
    "msg": "All assertions passed"
}
ok: [host2] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Remove group_vars] ************************************************************************************************************************************************************************************************************
changed: [host1 -> localhost]

TASK [validate variable is undefined] ***********************************************************************************************************************************************************************************************
ok: [host1] => {
    "changed": false,
    "msg": "All assertions passed"
}
ok: [host2] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP **************************************************************************************************************************************************************************************************************************
host1                      : ok=6    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
host2                      : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

</details>
