### ISSUE TITLE
ERROR: Syntax Error while loading YAML script,

### ISSUE THREAD

**Issue by mrniranjan** [ansible/ansible#8243]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Fedora 20 (x86_64)
##### Summary:

I am having difficulty running ansible-playbook

I have my playbook having tasks divided in different files
##### Steps To Reproduce:
1. Create a main yml file as below:

``` ---
- hosts: pkiservers
   tasks:
   - include: tasks/infra.yml
   - include: tasks/openldap.yml 
```

Below  tasks/openldap.yml file 

```

---
 - name: Check out the openldap test git repo
   git: repo=http://test.example.com/git/openldap.git dest=/opt/openldap-tests
 - name: Run the make file
   shell: make -C /opt/openldap-tests/ run
   notify:
   - restart slapd
 handlers:
   - name: restart slapd
     service: slapd.service state=restarted
```

Run ansible-playbook

```
ansible-playbook test6.yml
ERROR: Syntax Error while loading YAML script, /source/test/ansible/tasks/openldap.yml
Note: The error may actually appear before this position: line 8, column 2
   - restart slapd
 handlers:
 ^
```
##### Expected Results:

I expect ansible-playbook to not throw any errors or at-least be specific as to what is the issue with the syntax
##### Actual Results:

```
ansible-playbook test6.yml
ERROR: Syntax Error while loading YAML script, /source/test/ansible/tasks/openldap.yml
Note: The error may actually appear before this position: line 8, column 2
  - restart slapd
 handlers:
 ^
```

**Comment by mpdehaan** [comment]
You have an indentation error and this is not a bug, in fact, Ansible is letting you know about this error.

For help, stop by #ansible on freenode, or the ansible-project mailing list and we'd be glad to help out.

**Comment by douglasdiasds** [comment]
Hello guys,i have the same problem with syntax,the terminal says that error is in line 8 but no have nothing in line 8 and the indention apparently to me is right,where i wrong?
the file:

```
- hosts: all
  sudo: True
  user: vagrant
  tasks:
   - name: "Atualiza pacotes e instala nginx"
     apt: name=nginx state=latest update_cache=yes
     install_recommends=yes
```

thanks!!!
