### ISSUE TITLE
ansible.builtin.deb822_repository always reports task changed

### ISSUE THREAD

**Issue by alexcernat** [ansible/ansible#82454]
### Summary

When I try to add a debian repository in deb822 format using the new module ansible.builtin.deb822_repository the task is always reported as "changed", even if no modification was made on ansible task.

### Issue Type

Bug Report

### Component Name

ansible.builtin.deb822_repository

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/collections']
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/callback_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/filter_plugins']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = True

ssh:
___
host_key_checking(/etc/ansible/ansible.cfg) = True
pipelining(/etc/ansible/ansible.cfg) = True
```

### OS / Environment

Debian 12

### Steps to Reproduce

```yaml (paste below)
- name: Add HPE repository
  ansible.builtin.deb822_repository:
    name: hpe-proliant
    uris: https://downloads.linux.hpe.com/SDR/repo/mcp
    types: deb
    suites: "{{ ansible_distribution_release }}/{{ hpe_mcp_repository_version }}"
    components: non-free
#    architectures: amd64
    signed_by: /etc/apt/keyrings/hpe-sdr.asc
    state: present
  register: hpe_repo
  tags:
    - apt-sources
```

### Expected Results

no changes on second consecutive run

### Actual Results

```console
that task appears as "changed" because the repo .sources file on disk always changes

this is the debug of some consecutive playbook runs without changing anything
    "repo": "X-Repolib-Name: hpe-proliant\nSuites: stretch/current\nComponents: non-free\nURIs: https://downloads.linux.hpe.com/SDR/repo/mcp\nSigned-By: /etc/apt/keyrings/hpe-sdr.asc\nTypes: deb\n",
    "repo": "Suites: stretch/current\nSigned-By: /etc/apt/keyrings/hpe-sdr.asc\nURIs: https://downloads.linux.hpe.com/SDR/repo/mcp\nComponents: non-free\nTypes: deb\nX-Repolib-Name: hpe-proliant\n",
    "repo": "Suites: stretch/current\nTypes: deb\nURIs: https://downloads.linux.hpe.com/SDR/repo/mcp\nComponents: non-free\nX-Repolib-Name: hpe-proliant\nSigned-By: /etc/apt/keyrings/hpe-sdr.asc\n",
    "repo": "Suites: stretch/current\nSigned-By: /etc/apt/keyrings/hpe-sdr.asc\nX-Repolib-Name: hpe-proliant\nTypes: deb\nComponents: non-free\nURIs: https://downloads.linux.hpe.com/SDR/repo/mcp\n",

by looking at the source I think the cause is located into the deb822 python module, which seems to not return idempotent results
   repo = deb822.dump()

there is any simple workaround for this?
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
