### ISSUE TITLE
wait_for_ip_address on vmware_guest does not work

### ISSUE THREAD

**Issue by fs30000** [ansible/ansible#82468]
### Summary

When having **wait_for_ip_address: true**  and **wait_for_ip_address_timeout:** configured on **vmware_guest module**, it still shows the task as finished even tough, it is not. Making the consecutive tasks to fail as they depend on the respective ip to be active. This executing the playbook from a debian12 machine. VMs are also debian12.

### Issue Type

Bug Report

### Component Name

vmware_guest

### Ansible Version

```console
$ ansible --version

ansible [core 2.14.3]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH(/plays/ansible.cfg) = ignore
CONFIG_FILE() = /plays/ansible.cfg
DEFAULT_FORKS(/plays/ansible.cfg) = 20
DEFAULT_HOST_LIST(/plays/ansible.cfg) = ['/plays/inventory']
DEPRECATION_WARNINGS(/plays/ansible.cfg) = False
HOST_KEY_CHECKING(/plays/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/plays/ansible.cfg) = False

ssh:
___
host_key_checking(/plays/ansible.cfg) = False
pipelining(/plays/ansible.cfg) = True
```

### OS / Environment

Debian 12

### Steps to Reproduce

```yaml

 - name: VMs
      community.vmware.vmware_guest:
        hostname: "{{ vchost }}"
        username: "{{ vcusername }}"
        password: "{{ vcpassword }}"
        validate_certs: false
        datacenter: "{{ vcdatacenter }}"
        cluster: "{{ vccluster }}"
        datastore: "{{ vcdatastore }}"
        folder: "{{ item.value.folder }}"
        name: "{{ item.value.hostname }}"
        state: poweredon
        template: d12
        networks:
        - name: "{{ item.value.vlan }}"
          start_connected: true
          ip: "{{ item.value.ip }}"
          netmask: "{{ item.value.netmask }}"
          gateway: "{{ item.value.gw }}"
          type: static
        customization:
          hostname: "{{ item.value.hostname }}"
          dns_servers: "{{ item.value.dns }}"
        wait_for_ip_address: true
        wait_for_ip_address_timeout: 120
      loop: "{{ list }}"
      register: c1
      async: 900
      poll: 0

    - name: status 
      async_status:
        jid: "{{ item.ansible_job_id }}"
      until: tasks1.finished
      register: tasks1
      retries: 120
      delay: 10
      with_items:
        - "{{ c1.results }}"

```

### Expected Results

Tasks should not  be considered as changed if the ip is not yet active.

### Actual Results

```console
Tasks as marked as changed, but some VMs do not have the IP active.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
