### ISSUE TITLE
User module should not set password in plaintext

### ISSUE THREAD

**Issue by guillaumevincent** [ansible/ansible#8249]
##### Issue Type:

“Bug Report”, “Feature Idea”
##### Ansible Version:

`ansible 1.6.7`
##### Environment:

I'm running mac OS X and I'm managing a debian wheezy 7 server
##### Summary:

It seems that the password is set in plaintext after running the user module
##### Steps To Reproduce:

execute a playbook like this :

```
  vars_prompt:
    - name: "root_password"
      prompt: "What is the server root password ?"
      private: yes

  tasks:
    - name: change root password
      user: name=root  password="{{root_password}}"
```
##### Expected Results:

On the server the password is not encrypted : 

```
cat /etc/shadow
root:MY_ENCRYPTED_PASSWORD:16273:0:99999:7:::
```
##### Actual Results:

```
cat /etc/shadow
root:PLAIN_TEXT_PASSWORD:16273:0:99999:7:::
```

I don't know if it is a bug or a feature, but maybe if this is a feature, we should update the module documentation and add an example like : 

```
# Change johnd's password
- user: name=johnd password="YOUR_PASSWORD_ENCRYPTED"
```
