### ISSUE TITLE
Add support for iptables TCPMSS --clamp-mss-to-pmtu

### ISSUE THREAD

**Issue by accuris-infrastructure** [ansible/ansible#82525]
### Summary

I am attempting to use the iptables module in 2.13.0 to create an iptables rule for clamping MSS values on a specific GRE tunnel interface, however it appears that there is no option to set the `--clamp-mss-to-pmtu` flag anywhere for TCPMSS. To make this work I'm currently just using templates to replace the iptables-persistent files and load the rules from there, however this results in my docker rules being removed from the system as those are dynamically generated by docker which is not ideal to have removed.

### Issue Type

Feature Idea

### Component Name

iptables

### Additional Information

The equivalent iptables command would be the following:
```
iptables -A POSTROUTING -o tunnel200 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
```
I believe this should translate to the following task
```yaml
- name: Clamp MSS for GRE tunnels
  ansible.builtin.iptables:
    table: mangle
    chain: POSTROUTING
    out_interface: tunnel200
    protocol: tcp
    match: tcp
    tcp_flags:
      flags:
        - "SYN,RST"
        - "SYN"
      flags_set: []
    jump: TCPMSS
    clamp_mss_to_pmtu: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/iptables.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/iptables.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by romeupalos** [comment]
I also would like to support for this on ansible.
Additionally, maybe the TCP flags attribute should be:
```yaml
        tcp_flags:
          flags:
            - SYN
            - RST
          flags_set:
            - SYN
```
