### ISSUE TITLE
Allow to silence warning about loop variable already in use

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#82538]
### Summary

I'm recursively including a tasks file in one of my roles and I noticed that currently it is not possible to silence the warning about reusing the loop variable. It would be great to be able to somehow say that overwriting a variable is intentional.

Example: https://gitlab.agowa338.de/agowa338-ansible/ansible-arch-makepkg/-/blob/14eb6f1d65e4dff29281b87006d0a60057c360dd/tasks/build/jack.yml#L5

### Issue Type

Feature Idea

### Component Name

loop_control

### Additional Information

```yaml
- include_tasks: ../build.yml
  loop_control:
    loop_var: item
    loop_var_overwrites: True
  loop:
    - loopItem1
    - loopItem2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
