### ISSUE TITLE
explicit handler flush not working as expected

### ISSUE THREAD

**Issue by j20d** [ansible/ansible#82531]
### Summary

I have a role that gets imported twice, the second import is done with a `when:`-condition. When that condition evaluates to `false` that second import "masks" the handler-notifications triggered during the first import during a handler_flush happening before the second import

### Issue Type

Bug Report

### Component Name

handler

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansiblebug/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/ansiblebug/.venv/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/user/ansiblebug/.venv/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Debian 12.2 (reproducer), discovered on RHEL8.x

### Steps to Reproduce

Basic setup, two playbooks, one role with two task-files and one defined handler:
`roles/test/tasks/call.yml`:
``` yaml
---
- name: "Notify Handler"
  debug:
    msg: "Notifying ..."
  changed_when: true
  notify: "run_my_handler"
  ```
`roles/test/tasks/mask.yml`:
``` yaml
---
- name: "Mask handler"
  debug:
    msg: "Masking Handler"
```
`roles/test/handlers/main.yml`:
``` yaml
---
- name: "run_my_handler"
  debug:
    msg: "Handler was called"
```
`./run.yml`:
``` yaml
---
- name: "Working Code"
  hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: test
        tasks_from: call.yml
```
`./break.yml`:
``` yaml
--
- name: "Reproducer"
  hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: test
        tasks_from: call.yml
    - ansible.builtin.meta: flush_handlers
    - ansible.builtin.import_role:
        name: test
        tasks_from: mask.yml
      when: true == false
```
to reproduce:
``` bash
python3 -m venv .venv
source .venv/bin/activate
pip install ansible
ansible-playbook -i localhost run.yml
ansible-playbook -i localhost break.yml
```

### Expected Results

I expect the handlers notified during the unconditional `ansible.builtin.import_role` to be called during the explicit `meta: flush_handlers`.

### Actual Results

```console
(.venv) user@host:~/ansiblebug$ ansible-playbook -i localhost break.yml -v
No config file found; using defaults
[WARNING]: Unable to parse /home/user/ansiblebug/localhost as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Reproducer] ***************************************************************************************************************************************************************************************************

TASK [test : Notify Handler] ****************************************************************************************************************************************************************************************
changed: [localhost] => {
    "msg": "Notifying ..."
}

TASK [ansible.builtin.meta] *****************************************************************************************************************************************************************************************

RUNNING HANDLER [test : run_my_handler] *****************************************************************************************************************************************************************************
skipping: [localhost] => {"false_condition": "true == false"}

TASK [test : Mask handler] ******************************************************************************************************************************************************************************************
skipping: [localhost] => {"false_condition": "true == false"}

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
