### ISSUE TITLE
Support Incus in lxd_container module

### ISSUE THREAD

**Issue by johnmaguire** [ansible/ansible#82546]
### Summary

When I try to use https://docs.ansible.com/ansible/latest/collections/community/general/lxd_container_module.html to create a container, I get an error that `/1.0/instances` does not exist.

Incus is a fork of LXD by the original maintainers. According to them, this API path is deprecated even in LXD proper: https://discuss.linuxcontainers.org/t/ansible-guidance-receiving-errors-when-using-lxd-container-plugin/18734

### Issue Type

Bug Report

### Component Name

lxd_container

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.7]
  config file = None
  configured module search path = ['/Users/jmaguire/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/jmaguire/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.18 (main, Aug 24 2023, 21:19:58) [Clang 14.0.3 (clang-1403.0.22.14.1)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
n/a
```

### OS / Environment

Arch Linux, Incus 0.4-2

### Steps to Reproduce

```yaml (paste below)
community.general.lxd_container:
   name: docker
   state: started
   type: container
   config:
     security.nesting: "true"
     security.syscalls.intercept.mknod: "true"
     security.syscalls.intercept.setxattr: "true"
   devices:
     docker:
       path: /var/lib/docker
       pool: default
       type: disk
       source: docker
   source:
     protocol: simplestreams
     type: image
     mode: pull
     server: https://images.linuxcontainers.org
     alias: debian/bookworm
   profiles: ["default"]
   wait_for_ipv4_addresses: true
   timeout: 600
   url: "unix:/var/lib/incus/unix.socket"
```

### Expected Results

Created an LXD container - instead I get a 404 from the daemon.

### Actual Results

```console
no longer handy
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
