### ISSUE TITLE
Download of Windows Update fails

### ISSUE THREAD

**Issue by MaKaNu** [ansible/ansible#82553]
### Summary

I running a test WIN11 VM which is connected via ssh. When I run the `win_updates` module, it finds some updates, but after logging into the machine I still being prompted by a failed update. The tasks are running without noticing.

### Issue Type

Bug Report

### Component Name

win_updates

### Ansible Version

```console
$ ansible --version

ansible [core 2.16.2]
  config file = /home/testuser/Dokumente/ansible/ansible-testing/ansible.cfg
  configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/testuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = /home/testuser/Dokumente/ansible/ansible-testing/ansible.cfg
```

### OS / Environment

MS Windows 11 22H2

### Steps to Reproduce

Having a Windows 11 System with pending KB4023057

```yaml (paste below)
---
- name: Search for Windows Updates
  hosts: ansible_w11_01

  tasks:
    - name: Set a server alive interval during update stage for the ssh connection plugin
      ansible.windows.win_updates:
        category_names: "*"
        reboot: true
      vars:
        # This can be set in a few ways, see the ssh connection plugin for more
        # information. ControlMaster should be disabled to ensure the new timeout
        # value is applied for this connection instead of through the cached
        # connection.
        ansible_ssh_args: -o ControlMaster=no -o ServerAliveInterval=30
      register: result

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg:
          - "Failed Updates: {{ result.failed_update_count }}"
          - "Updates Found: {{ result.found_update_count }}"
          - "Updates: {{ result.updates }}"
```

### Expected Results

I expect that at least Failed Updates is sitting at 1.

But the Upgrade is shown as Downloaded and Installed as you can see below.

### Actual Results

```console
PLAY [Search for Windows Updates] **********************************************

TASK [Gathering Facts] *********************************************************
ok: [ansible_w11_01]

TASK [Set a server alive interval during update stage for the ssh connection plugin] ***
changed: [ansible_w11_01]

TASK [Print return information from the previous task] *************************
ok: [ansible_w11_01] => {
    "msg": [
        "Failed Updates: 0",
        "Updates Found: 2",
        "Updates: {'b72f9896-57cc-412e-81f9-a00aff44a4ee': {'title': 'Security Intelligence-Update für Microsoft Defender Antivirus – KB2267602 (Version 1.403.2272.0) – Aktueller Kanal (Allgemein)', 'kb': ['2267602'], 'categories': ['Definition Updates', 'Microsoft Defender Antivirus'], 'id': 'b72f9896-57cc-412e-81f9-a00aff44a4ee', 'downloaded': True, 'installed': True}, 'a86b89c3-c593-4b6f-9be5-da1a081f2307': {'title': '2023-10 Update für Windows 11 Version 22H2 für x64-basierte Systeme (KB4023057)', 'kb': ['4023057'], 'categories': ['Critical Updates'], 'id': 'a86b89c3-c593-4b6f-9be5-da1a081f2307', 'downloaded': True, 'installed': True}}"
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
