### ISSUE TITLE
HttpApi connection not working on macOS because of urllib proxy handling

### ISSUE THREAD

**Issue by multipleofzero** [ansible/ansible#82558]
### Summary

When using the community Zabbix module (`community/zabbix/plugins/httpapi/zabbix.py` which uses an `HttpApi` connection), any task related to Zabbix fails with a JSON error.

    _exec_jsonrpc
    ansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to api_version(). Received 'None'

Lenghty debugging led to the conclusion, that the problematic call is in `urllib/request.py`'s `getproxies_macosx_sysconf()`: `_get_proxies()`. It just seems to return `None`.

The official Python documentation [has a warning about this](https://docs.python.org/3.11/library/urllib.request.html) right at the top:

> Warning
> On macOS it is unsafe to use this module in programs using [os.fork()](https://docs.python.org/3.11/library/os.html#os.fork) because the [getproxies()](https://docs.python.org/3.11/library/urllib.request.html#urllib.request.getproxies) implementation for macOS uses a higher-level system API. Set the environment variable no_proxy to * to avoid this problem (e.g. os.environ["no_proxy"] = "*").

I *think* `ansible-connection` is using `fork()`, so this might apply. In any case, using `export no_proxy=*` resolves the issue.

I have tried various different versions of Ansible with the same result.

### Issue Type

Bug Report

### Component Name

ansible/cli/scripts/ansible_connection_cli_stub.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.4]
  config file = <home>/Documents/mgm/ansible.cfg
  configured module search path = ['<home>/Documents/mgm/library']
  ansible python module location = <home>/.pyenv/versions/mgm/lib/python3.11/site-packages/ansible
  ansible collection location = <home>/.ansible/collections:/usr/share/ansible/collections
  executable location = <home>/.pyenv/versions/mgm/bin/ansible
  python version = 3.11.3 (main, May 10 2023, 08:16:51) [Clang 14.0.3 (clang-1403.0.22.14.1)] (<home>/.pyenv/versions/mgm/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(<home>/Documents/mgm/ansible.cfg) = True
CONFIG_FILE() = <home>/Documents/mgm/ansible.cfg
DEFAULT_FORKS(<home>/Documents/mgm/ansible.cfg) = 50
DEFAULT_HOST_LIST(<home>/Documents/mgm/ansible.cfg) = ['<home>/Documents/mgm/production/hosts']
DEFAULT_MODULE_PATH(<home>/Documents/mgm/ansible.cfg) = ['<home>/Documents/mgm/library']
DEFAULT_ROLES_PATH(<home>/Documents/mgm/ansible.cfg) = ['<home>/Documents/mgm/roles']
DIFF_ALWAYS(<home>/Documents/mgm/ansible.cfg) = True
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(<home>/Documents/mgm/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
ssh_args(<home>/Documents/mgm/ansible.cfg) = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=120s ->

ssh:
___
pipelining(<home>/Documents/mgm/ansible.cfg) = True
ssh_args(<home>/Documents/mgm/ansible.cfg) = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=120s ->
```

### OS / Environment

macOS Sonoma (14.2.1)

Interestingly I do not experience the problem when I use a Homebrew installed version of Ansible (I am using a virtualenv with pyenv for daily work).

### Steps to Reproduce

I was using an minimal playbook for debugging (I think it is possible to reproduce the issue in `--check` mode w/o having a Zabbix server available):

```yaml (paste below)
    - name: Get zabbix user info
      # set task level variables as we change ansible_connection plugin here
      vars:
        zabbix_user: <username>
        zabbix_password: <redacted>
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_use_ssl: true
        ansible_user: "{{ zabbix_user }}"
        ansible_httpapi_pass: "{{ zabbix_password }}"
        ansible_host: "monitoring.example.com"
      community.zabbix.zabbix_user_info:
        username: "{{ zabbix_user }}"
      register:
        myuserinfo
```

### Expected Results

Get "user info" from Zabbix.

### Actual Results

```console
_exec_jsonrpc
    ansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to api_version(). Received 'None'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
