### ISSUE TITLE
Module Aliasing

### ISSUE THREAD

**Issue by silenced1** [ansible/ansible#82573]
### Summary

# Module Aliasing
I didn't find anything around this subject, so I thought I'd put it out there and see what others thought. I believe this would actually be helpful for the overall community.

I ran into a case where I needed to decide between yum and dnf (pretty trivial all in all, but got me thinking). Per RedHat's recommendations, yum should be used for RHEL7 and dnf for 8+, although both are supported on all platforms (for now). In order to meet the recommendation, I have to define a "when" clause all over my playbook or split my sub-playbooks between operating systems, which makes me want to lean over to over generalizing it instead. 

Since we cannot provide variables directly in the module name (makes sense since that changes the language requirements), I'm wondering if we can instead define aliases of modules, whith an option to include their commands.

So basically, I could say "use ansible.builtin.yum when I reference module_alias.pkg_mgr", after defining the alias using something like:
```
- name: Set alias module to yum or dnf based on PKG_MGR variable
  ansible.builtin.module_alias:
    name: "pkg_mgr"
    module: "ansible.builtin.{{ PKG_MGR }}"
    state: present

- name: Run system package manager
  module_alias.pkg_mgr:
    name:
      - nginx
      - postgresql
      - postgresql-server
    state: present
```
Or... even template that command using presets like:
```
- name: Set alias module to yum or dnf
  ansible.builtin.module_alias:
    name: "pkg_mgr"
    module: "ansible.builtin.{{ PKG_MGR }}"
      options:
        name:
          - nginx
          - "{{ postgres }}-{{ version }}"
          - "{{ postgres }}-{{ version }}-server"
        state: present
    state: present

- name: Run system package manager with predefined arguments
  module_alias.pkg_mgr:
```

So this would give you the option to just use Ansible the way it is, or you could write your Ansible in a way where you can configure separate use cases/requirements easily depending on the host you're working on using logical definitions of tasks without writing that logic in many places unnecessarily.

I hope I described that well. I really could use a feature like this as some of my playbooks are a bit bloated where I can see patterns where it could be slimmed down.

### Issue Type

Feature Idea

### Component Name

module_alias

### Additional Information

# Use cases
* For upgrades between commands that support backwards compatibility between different but similar products (yum vs dnf is a simple example, but there are much more complicated ones out there).
* For staging long repetitive commands into a simple module alias, allowing for a drop in lines of script (allows performing finer grain treatment to hosts while knowing less about them).
* For aliasing existing modules into a more programmatical method (slim code down by allowing patterns of module use and configuration).
  * Ex: module_alias.{{ PKG_MGR }} vs module_alias.{{ OS_TYPE}}.{{ ARCH_TYPE }}.{{ ALIAS_MODULE_WITH_PRESET_INSTRUCTION }}
* Pro: Should not impact existing modules since this does nothing more than reference them and their current abilities. The main goal here is reducing writing and adding more programmability.

```yaml (paste below)
# Following example assumes a playbook for RedHat 7+ where yum will be used for RedHat 7 and dnf will be used for RedHat 8+

- name: Set default system manager var
  ansible.builtin.set_fact:
    PKG_MGR: "dnf"

- name: Set default system manager
  ansible.builtin.set_fact:
    PKG_MGR: "yum"
  when: "ansible_facts['distribution'] in ['RedHat'] and ansible_facts['distribution_major_version'] == '7'"

- name: Set alias module to yum or dnf
  ansible.builtin.module_alias:
    name: "pkg_mgr"
    module: "ansible.builtin.{{ PKG_MGR }}"
      options: <could support additional arguments for commands that do not need change between use>
    state: present

- name: Use alias module to run as intended
  module_alias.pkg_mgr:
    name:
      - nginx
      - postgresql
      - postgresql-server
    state: present
```

For clarity, module_alias would allow a "name" value of something like "rh.x86.pkg_mgr" if it were defined as `name: "{{ OS_TYPE}}.{{ ARCH_TYPE }}.pkg_mgr"` and be referenced as `module_alias.rh.x86.pkg_mgr`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
For this specific case: `yum` is actually an action plugin that dynamically decides whether to call the `yum`, `dnf`, or `dnf5` module based on the system facts, so you don't actually need to determine that on your own in most situations. If your situation is special, you can tell it which backend you want to use: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html#parameter-use_backend

In the general case, you can use the `action` action plugin if you need to template the name of a module that you're calling:

```yaml
- set_fact:
    my_module: "{{ 'ansible.builtin.debug' if inventory_hostname == 'localhost' else 'ansible.builtin.ping' }}"
- action:
    module: "{{ my_module }}"
```
Output:
```
TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [{{ my_module }}] *********************************************************
ok: [localhost] =>
    msg: Hello world!
```

**Comment by bcoca** [comment]
This specific case aside, you already have multiple ways to alias a module, including action plugins, symlinks, variables (as shown above) and collection meta runtime configurations.

**Comment by silenced1** [comment]
Ah... no kidding. I had no idea and it's not easily referenced. Thank you for the feedback.

**Comment by silenced1** [comment]
So I tried using the method you described above, but all I'm getting is the error `ERROR! couldn't resolve module/action '{{ pkg_mgr }}'. This often indicates a misspelling, missing collection, or incorrect module path`.

For the yum vs dnf case, I only chose this as the scenario because it's a straight forward and simple approach. Basically, if we can achieve what I'm describing in the feature request, then I can do this easily and perform even more complex scenarios.

Here's what I tried (the last 3 statements being ran individually with the rest above):
```
# Set default - will evaluate as "yum" if RHEL7 (would be combined with the below using distribution facts)
- name: Set default PKG_MGR
  ansible.builtin.set_fact:
    PKG_MGR: "dnf"

- name: Set module fact
  ansible.builtin.set_fact:
    pkg_mgr: "{{ 'ansible.builtin.yum' if PKG_MGR == 'yum' else 'ansible.builtin.dnf' }}"

# Tried each of these separately
- name: Use module fact
  "{{ pkg_mgr }}"
	name: nano
	state: present

- name: Use module fact
  pkg_mgr:
	name: nano
	state: present

- name: Use module via action
  action:
    module: "{{ pkg_mgr }}"
	name: nano
	state: present
```

If there's a question of versions:
* Ansible core: 2.16.2
* Python: 3.11.5
* Jinja: 3.1.3

**Comment by flowerysong** [comment]
You cannot get that exact error with any of the tasks you listed, so I think you need to redo your tests.

```yaml
- name: Use module fact
  "{{ pkg_mgr }}"
    name: nano
    state: present
```
This won't even parse, because it's invalid YAML. The error from this will be:
```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected '-' indicator
```

```yaml
- name: Use module fact
  "{{ pkg_mgr }}":
    name: nano
    state: present
```

This fixed version is the only thing that can cause this error:
```
ERROR! couldn't resolve module/action '{{ pkg_mgr }}'. This often indicates a misspelling, missing collection, or incorrect module path.
```

```yaml
- name: Use module fact
  pkg_mgr:
    name: nano
    state: present
```

This will throw a similar error, but without the Jinja delimiters because they're not present in the task:
```
ERROR! couldn't resolve module/action 'pkg_mgr'. This often indicates a misspelling, missing collection, or incorrect module path.
```

```yaml
- name: Use module via action
  action:
    module: "{{ pkg_mgr }}"
    name: nano
    state: present
```

This one is valid and cannot cause the error you indicated. Even if you try to call a module that does not exist, the error will be a completely different one:
```
fatal: [localhost]: FAILED! => {"msg": "The module ansible.builtin.dn was not found in configured module paths"}
```
