### ISSUE TITLE
add reset-failed to ansible.builtin.systemd_service module

### ISSUE THREAD

**Issue by ravench** [ansible/ansible#82596]
### Summary

I need to reset the failed state of services before running further operations on them. I haven't found a way to do this with ansible.builtin.systemd_service so far and would like to avoid just running it as a shell comand.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.systemd_service

### Additional Information

```yaml (paste below)
- name: Systemd: reset failed services
  ansible.builtin.systemd_service:
    reset-failed: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
