### ISSUE TITLE
1.6.7 Error, A variable inserted a new parameter into the module args

### ISSUE THREAD

**Issue by woledzki** [ansible/ansible#8260]
##### Issue Type:

Bug Report
##### Ansible Version:

v1.6.7
##### Environment:

From: OSX
To: Centos 6
##### Summary:

84759faa0950146a6bae8452580b4a4cede6d871 broke 1.6.7 version and looks like it's not related to the `lineinfile` module.

There might be error in my task definition, but it just works in version <= 1.6.6. 
##### Steps To Reproduce:

Create task

``` yml
- name: Add the node.js binary to the system path
  lineinfile: "{{item}}"
  with_items:
    - dest=/etc/profile regexp='^NODE_HOME=/usr/local/nodejs/default' line="NODE_HOME=/usr/local/nodejs/default" state=present
    - dest=/etc/profile regexp='^PATH=.*NODE_HOME.*' line="PATH=$PATH:$NODE_HOME/bin" state=present
```
##### Expected Results:

```
TASK: [nodejs | Add the node.js binary to the system path] ********************
changed: [default] => (item=dest=/etc/profile regexp='^NODE_HOME=/usr/local/nodejs/default' line="NODE_HOME=/usr/local/nodejs/default" state=present)
changed: [default] => (item=dest=/etc/profile regexp='^PATH=.*NODE_HOME.*' line="PATH=$PATH:$NODE_HOME/bin" state=present)
```
##### Actual Results:

```
TASK: [nodejs | Add the node.js binary to the system path] ********************
fatal: [default] => A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Yep, this is going to be a legitimate thing now (i.e. we're not going to be able to make a change here), because of the way we must guard against argument insertion from potentially untrusted data sources.

There are easy fixes though, which are:

```
 lineinfile: "dest={{item.dest}} line={{item.line}} state={{item.state}}"
 with_items:
     - { dest: '/etc/profile', regexp: 'blarg', state: 'blarg' }
     - ....
```

**Comment by woledzki** [comment]
Thanks for update, I will change my playbooks!

**Comment by vervas** [comment]
The bug still occurs on ansible 1.8.1 on OS X 10.10. The suggested fix does not solve the issue.

**Comment by amine7536** [comment]
Still occurs on Ansible 1.8.2 on OS X 10.10

You can use :

``` yaml
- name: node.js Add the node.js binary to the system path
  lineinfile:
    dest: /etc/profile
    regexp: "^NODE_HOME=/usr/local/nodejs/default"
    line: "NODE_HOME=/usr/local/nodejs/default"
    state: present
  lineinfile:
    dest: /etc/profile
    regexp: "^PATH=.*NODE_HOME.*"
    line: "PATH=$PATH:$NODE_HOME/bin"
    state: present
```
