### ISSUE TITLE
Inconsistent return for debug var

### ISSUE THREAD

**Issue by kenorb** [ansible/ansible#82632]
### Summary

When `debug` is used to print variable, its return is inconsistent when printing message.

So when I print `msg` using `debug` and register in `result`, I can find its result in `result.msg`.

However, when printing variable with `var`, in `result`, no `var` returned, but name of variable it-self. This is problematic especially when printing more complex variables (such as `lookup('something', input)`), then to check its content in registered `result` to do some conditions, it's almost not possible to reference it.

### Issue Type

Bug Report

### Component Name

debug

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.2]
```
### Configuration

```
$ ansible-config dump -t all
Unable to open source file for reading:
  InputError: [Errno 2] No such file or directory: 'dump'
```

### OS / Environment

Ubuntu

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  tasks:
    - name: Print some message
      ansible.builtin.debug:
        msg: Message
      register: result
    - ansible.builtin.debug:
        var: result
    - name: Print some variable
      ansible.builtin.debug:
        var: ansible_os_family
      register: result
    - ansible.builtin.debug:
        var: result
```

Now run: `ansible-playbook -c local -i "localhost," test.yml -vv`

### Expected Results

The `debug` module with var, should return content of variable in `var` key, not `ansible_os_family` (which is name of the variable. If the return key is unpredictable, then it's not possible to do further conditions based on `result.var` which doesn't actually exist (in comparison to `result.msg`).

### Actual Results

```console
TASK [Print some message] *********************************************************************************************************************************************************************************
task path: /media/12TB/home/kenorb/Sources/GitHub/EA/ansible-role-mt-runner/test.yml:4
ok: [localhost] => {
    "msg": "Message"
}

TASK [ansible.builtin.debug] ******************************************************************************************************************************************************************************
task path: /media/12TB/home/kenorb/Sources/GitHub/EA/ansible-role-mt-runner/test.yml:8
ok: [localhost] => {
    "result": {
        "changed": false,
        "failed": false,
        "msg": "Message"
    }
}

TASK [Print some variable] ********************************************************************************************************************************************************************************
task path: /media/12TB/home/kenorb/Sources/GitHub/EA/ansible-role-mt-runner/test.yml:10
ok: [localhost] => {
    "ansible_os_family": "Debian"
}

TASK [ansible.builtin.debug] ******************************************************************************************************************************************************************************
task path: /media/12TB/home/kenorb/Sources/GitHub/EA/ansible-role-mt-runner/test.yml:14
ok: [localhost] => {
    "result": {
        "ansible_os_family": "Debian",
        "changed": false,
        "failed": false
    }
}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
