### ISSUE TITLE
builtin yum module not adhering to ansible_python_interpreter for centos 6

### ISSUE THREAD

**Issue by iqfx** [ansible/ansible#82638]
### Summary

Here's an output of what I have encountered with the ansible yum module

```
TASK [GROG.package : ansible.builtin.debug] **************************************************************************************************************************************************************************
ok: [somehost] => {
    "msg": "/usr/bin/python2.7"
}

TASK [GROG.package : Yum] ********************************************************************************************************************************************************************************************
failed: [somehost] (item={'name': 'sudo'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "sudo"}, "msg": "ansible-core requires a minimum of Python2 version 2.7 or Python3 version 3.6. Current version: 2.6.6 (r266:84292, Jun 20 2019, 14:14:55) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]"}

NO MORE HOSTS LEFT ***************************************************************************************************************************************************************************************************

PLAY RECAP ***********************************************************************************************************************************************************************************************************
somehost      : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
here are the tasks as shown in the output above:

```
- ansible.builtin.debug:
    msg: "{{ ansible_python_interpreter }}"
- name: Yum
  ansible.builtin.yum:
    name: "{{ item.yum | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
  when: (item.yum_ignore|default('no'))|string in 'False,false,No,no'
  with_items: "{{ packages }}"

```

### Issue Type

Bug Report

### Component Name

yum

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.3]
  config file = /Users/user/Documents/ansible/playbooks/users/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/user/Documents/ansible/playbooks/users/roles
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOLOR(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = False
ANY_ERRORS_FATAL(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = True
COLLECTIONS_PATHS(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = ['/Users/user/Documents/ansible/playbooks/users/roles']
CONFIG_FILE() = /Users/user/Documents/ansible/playbooks/users/ansible.cfg
DEFAULT_DEBUG(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = False
DEFAULT_HOST_LIST(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = ['/Users/user/Documents/ansible/playbooks/users/roles/signet_connectivity.inventory/inventory-prod.yml']
DEFAULT_MANAGED_STR(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = Ansible managed: modified on %Y-%m-%d %H:%M:%S
DEFAULT_ROLES_PATH(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = ['/Users/user/Documents/ansible/playbooks/users/roles']
DEFAULT_VERBOSITY(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = 0
HOST_KEY_CHECKING(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = False
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = False

ssh:
___
host_key_checking(/Users/user/Documents/ansible/playbooks/users/ansible.cfg) = False
```

### OS / Environment

Centos 6 on the target machine

### Steps to Reproduce

```yaml (paste below)
---
- ansible.builtin.debug:
    msg: "{{ ansible_python_interpreter }}"
- name: Yum
  ansible.builtin.yum:
    name: "{{ item.yum | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
  when: (item.yum_ignore|default('no'))|string in 'False,false,No,no'
  with_items: "{{ packages }}"

```

### Expected Results

I expect the yum module to not complain about an old python version because the ansible_python_interpreter has been clearly set a supported version.

### Actual Results

```console
failed: [somehost] (item={'name': 'sudo'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "sudo"}, "msg": "ansible-core requires a minimum of Python2 version 2.7 or Python3 version 3.6. Current version: 2.6.6 (r266:84292, Jun 20 2019, 14:14:55) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
