### ISSUE TITLE
chown failed ERR 38 Function not implemented: /run/vmblock-fuse

### ISSUE THREAD

**Issue by Cynnexis** [ansible/ansible#82649]
### Summary

When trying to set the owner and group to a directory structure (recursively) on a VM as the target machine, I sometimes get the following error:

```yaml
TASK [agent : Ensure that the whole cache directory is owned by the user] *******************************
task path: project/roles/agent/tasks/configure.yml:178
The full traceback is:
  File "/tmp/ansible_file_payload_bc16rt0n/ansible_file_payload.zip/ansible/module_utils/basic.py", line 841, in set_owner_if_different
    os.lchown(b_path, uid, -1)
fatal: [my-vm]: FAILED! => changed=false
  gid: 0
  group: root
  invocation:
    module_args:
      _diff_peek: null
      _original_basename: null
      access_time: null
      access_time_format: '%Y%m%d%H%M.%S'
      attributes: null
      follow: true
      force: false
      group: my-user
      mode: null
      modification_time: null
      modification_time_format: '%Y%m%d%H%M.%S'
      owner: my-user
      path: /home/my-user/installation_path/cache
      recurse: true
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: null
      state: directory
      unsafe_writes: false
  mode: '0555'
  msg: 'chown failed: [Errno 38] Function not implemented: b''/run/vmblock-fuse'''
  owner: root
  path: /run/vmblock-fuse
  size: 4096
  state: directory
  uid: 0
```

The task that I used is:

```yaml
# git_clone_result is a register from `git`

- name: Ensure that the whole cache directory is owned by the user
  when: git_clone_result.changed
  file:
    path: "{{ install_path }}/cache"
    recurse: true
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
```

### Issue Type

Bug Report

### Component Name

file

### Ansible Version

```console
$ ansible --version

ansible [core 2.15.3]
  config file = ~/project/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/miniconda3/envs/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/miniconda3/envs/ansible/bin/ansible
  python version = 3.9.15 (main, Nov 24 2022, 14:31:59) [GCC 11.2.0] (~/miniconda3/envs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ansible-config [core 2.15.3]
  config file = ~/project/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/miniconda3/envs/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/miniconda3/envs/ansible/bin/ansible-config
  python version = 3.9.15 (main, Nov 24 2022, 14:31:59) [GCC 11.2.0] (~/miniconda3/envs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using ~/project/ansible.cfg as config file
ANSIBLE_NOCOWS(~/project/ansible.cfg) = True
ANSIBLE_PIPELINING(~/project/ansible.cfg) = True
CACHE_PLUGIN(~/project/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(~/project/ansible.cfg) = /tmp/ansible-facts
CACHE_PLUGIN_PREFIX(~/project/ansible.cfg) = project_fact
CALLBACKS_ENABLED(~/project/ansible.cfg) = ['log_plays', 'profile_tasks']
CONFIG_FILE() = ~/project/ansible.cfg
DEFAULT_FORKS(~/project/ansible.cfg) = 10
DEFAULT_GATHERING(~/project/ansible.cfg) = smart
DEFAULT_HOST_LIST(~/project/ansible.cfg) = ['~/project/hosts.yml']
DEFAULT_STDOUT_CALLBACK(~/project/ansible.cfg) = yaml
DEFAULT_TIMEOUT(~/project/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(~/project/ansible.cfg) = ~/project/scripts/get-ansible-password.sh
DEFAULT_VERBOSITY(~/project/ansible.cfg) = 3
DISPLAY_SKIPPED_HOSTS(~/project/ansible.cfg) = False
EDITOR(env: EDITOR) = /usr/bin/vim
PAGER(env: PAGER) = less
SHOW_CUSTOM_STATS(~/project/ansible.cfg) = True
```

### OS / Environment

# Host machine:

Microsoft WSL Ubuntu 20.04 focal, running on Windows 10, AMD 64-bits.

# Target machine

Virtual machine

Virtual Machine Ubuntu 20.04 focal, AMD 64-bits, running on VMware vSphere.

### Steps to Reproduce

```yaml
# git_clone_result is a register from `git`

- name: Ensure that the whole cache directory is owned by the user
  when: git_clone_result.changed
  file:
    path: "{{ install_path }}/cache"
    recurse: true
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
```

### Expected Results

I expected the task to have the status **ok** since the directory already has the right owner and group (the directory is a git repo, cloned using the [`git`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html) module, and `become: true`, `become_user: {{ user.username }}`

### Actual Results

```console
TASK [agent : Ensure that the whole cache directory is owned by the user] *******************************
task path: project/roles/agent/tasks/configure.yml:178
The full traceback is:
  File "/tmp/ansible_file_payload_bc16rt0n/ansible_file_payload.zip/ansible/module_utils/basic.py", line 841, in set_owner_if_different
    os.lchown(b_path, uid, -1)
fatal: [my-vm]: FAILED! => changed=false
  gid: 0
  group: root
  invocation:
    module_args:
      _diff_peek: null
      _original_basename: null
      access_time: null
      access_time_format: '%Y%m%d%H%M.%S'
      attributes: null
      follow: true
      force: false
      group: my-user
      mode: null
      modification_time: null
      modification_time_format: '%Y%m%d%H%M.%S'
      owner: my-user
      path: /home/my-user/installation_path/cache
      recurse: true
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: null
      state: directory
      unsafe_writes: false
  mode: '0555'
  msg: 'chown failed: [Errno 38] Function not implemented: b''/run/vmblock-fuse'''
  owner: root
  path: /run/vmblock-fuse
  size: 4096
  state: directory
  uid: 0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
