### ISSUE TITLE
ansible.builtin.service can't start user services

### ISSUE THREAD

**Issue by filipopo** [ansible/ansible#82645]
### Summary

Consider having this user service /etc/systemd/user/myservice.service
```
[Unit]
Description=Script Daemon For Test User Services

[Service]
Type=simple
ExecStart=sh /opt/test.sh
Restart=on-failure

[Install]
WantedBy=default.target
```
that starts this simple script /opt/test.sh
```
#!/bin/sh

now=$(date)
me=$(whoami)

echo "User $me at $now"
```
Outside of ansible this would be started with the following command `systemctl --user start myservice.service` and this works good but using ansible.builtin.service I receive the following error
```
fatal: [z.x.c.v]: FAILED! => {"changed": false, "msg": "Could not find the requested service myservice: host"}
```
This could be due to the fact that omitting the --user flag as in `systemctl start myservice` gives this error
```
Failed to start myservice.service: Unit myservice.service not found.
```

### Issue Type

Bug Report

### Component Name

service

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/Users/fstoja02/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/9.0.1/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/fstoja02/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.0 (main, Oct  2 2023, 12:03:24) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/Cellar/ansible/9.0.1/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

```
root@mobilna-sila:/# hostnamectl
 Static hostname: mobilna-sila
       Icon name: computer-vm
         Chassis: vm
      Machine ID: df5a661c34ee440796ffd8a330b9de74
         Boot ID: ed35bdf450de4f08a0a1aaf1909e9222
  Virtualization: kvm
Operating System: Ubuntu 22.04.3 LTS              
          Kernel: Linux 5.15.0-92-generic
    Architecture: x86-64
 Hardware Vendor: Hetzner
  Hardware Model: vServer
```

### Steps to Reproduce

ansible-playbook -i hosts test.yml -u myuser
```yaml (paste below)
---
- name: Minimal playbook to start a service
  hosts: servers

  tasks:
    - name: Start user service
      ansible.builtin.service:
        name: myservice
        state: started
```

### Expected Results

I expected the service to start

### Actual Results

```console
fatal: [z.x.c.v]: FAILED! => {"changed": false, "msg": "Could not find the requested service myservice: host"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/service.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/service.py)
* [`lib/ansible/plugins/action/service.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/service.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
This is not a bug. `ansible.builtin.service` is just a convenience wrapper that documents the minimal set of arguments supported by all of the modules it might choose to call. If you're doing something outside that, you have to read the documentation for the actual module that you're using (in this case [`ansible.builtin.systemd_service`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html)) to find out what arguments are supported.

```yaml
    - name: Start user service
      ansible.builtin.service:
        name: myservice
        state: started
        scope: user
```

Personally, I would use `systemd_service` directly for this task, since the wrapper isn't providing any utility here (if it calls a different module the task will fail, because `scope` is not implemented there.)

```yaml
    - name: Start user service
      ansible.builtin.systemd_service:
        name: myservice
        state: started
        scope: user
```
