### ISSUE TITLE
Ansible 2.15.9/2.16.3 sometimes renders template into subdirectory 'filename'/'filename'.j2

### ISSUE THREAD

**Issue by cah-wael-ladki** [ansible/ansible#82654]
### Summary

When using ansible 2.15.9 and 2.16.3 , sometimes the template is being rendered as follows: 
` "dest": "/opt/test/project/nginx/nginx.conf/nginx.conf.j2"`
instead of 
` "dest": "/opt/test/project/nginx/nginx.conf"`

This is only happening in this specific task for some reason, I am not being able to reproduce this error, it happens when I am running tests.

Everything else in the playbook continues normally.

### Issue Type

Bug Report

### Component Name

ansible.builtin.template

### Ansible Version

```console
Happens in 2.15.9 and 2.16.3
$ ansible --version
ansible [core 2.15.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jenkins/.local/venv/project/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/jenkins/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jenkins/.local/venv/project/bin/ansible
  python version = 3.11.5 (main, Oct 25 2023, 16:19:59) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/home/jenkins/.local/venv/project/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
N/A
```

### OS / Environment

RHEL 8

### Steps to Reproduce

N/A

### Expected Results

/file/path/filename

### Actual Results

```console
/file/path/filename/filename.j2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/lookup/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/template.py)
* [`lib/ansible/plugins/action/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/template.py)
* [`lib/ansible/modules/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/template.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by jborean93** [comment]
Does the directory `/opt/test/project/nginx/nginx.conf` already exist when the template has run? The `template` module uses the `copy` module under the covers which I believe will append the filename to `dest` if it already exists but I would need to check that.

**Comment by jborean93** [comment]
Just as a test

```yaml
- hosts: localhost
  gather_facts: false

  tasks:
  - file:
      path: /tmp/test
      state: '{{ item }}'
    loop:
    - absent
    - directory

  - copy:
      src: main.yml
      dest: /tmp/test
```

The output from the run

```
$ ansible-playbook main.yml -v
PLAY [localhost] *********************************************************************************************************************************************************************

TASK [file] **************************************************************************************************************************************************************************
changed: [localhost] => (item=absent) =>
    ansible_loop_var: item
    changed: true
    item: absent
    path: /tmp/test
    state: absent
changed: [localhost] => (item=directory) =>
    ansible_loop_var: item
    changed: true
    gid: 1000
    group: jborean
    item: directory
    mode: '0755'
    owner: jborean
    path: /tmp/test
    size: 40
    state: directory
    uid: 1000

TASK [copy] **************************************************************************************************************************************************************************
changed: [localhost] =>
    changed: true
    checksum: 573699bdbcce886edad2c2400c84db6a40de76f8
    dest: /tmp/test/main.yml
    gid: 1000
    group: jborean
    md5sum: 5ca333381e4abdceabefd89091717ac2
    mode: '0644'
    owner: jborean
    size: 202
    src: /home/jborean/.ansible/tmp/ansible-tmp-1707439892.6889622-61016-99609380632429/.source.yml
    state: file
    uid: 1000

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

We can see that the `dest` is `dest: /tmp/test/main.yml` meaning it has just placed it in the directory specified by `dest` with the filename of the source file.

**Comment by cah-wael-ladki** [comment]
@jborean93, first I would like to thank you for your cooperation on this.
Second `/opt/test/project/nginx/nginx.conf` does not exist when that happens, in fact `/opt/test/project/nginx` does in fact exists.

We run it as follows
```
- name: Make sure nginx directory exists
  file:
    state: directory
    path: "{{ project_dir }}/nginx"
    mode: 0755
  tags: ["nginx"]
- name: Copy nginx config
  ansible.builtin.template:
    src: nginx/nginx.conf.j2
    dest: "{{ project_dir }}/nginx/nginx.conf"
    mode: 0755
  notify:
    - project up
    - restart nginx
  tags: ["nginx"]
```
