### ISSUE TITLE
gce module returns - msg: Missing required create instance variable

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#8265]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.8
##### Environment:

RHEL-6
##### Summary:

Adding @erjohnso for consideration.

The 'gce' module doesn't seem to want to create a `rhel-6` image.  It's entirely likely that I'm providing the incorrect information for the `rhel-6` image.  According to [the docs](https://developers.google.com/compute/docs/images#public_images), `rhel-6` is a supported image type.
##### Steps To Reproduce:
1. Run the following playbook...

``` yaml

---
- hosts: local

  vars:
    instance_name: 'testing123'
    zone: 'us-central1-a'
    machine_type: 'n1-standard-1'
    service_account_email: 'FIXME'
    pem_file: 'FIXME'
    project_id: 'FIXME'

  tasks:
    - name: launch/locate instances
      gce:
        state: present
        name: '{{instance_name}}-{{item}}'
        machine_type: '{{machine_type}}'
        image: '{{item}}'
        zone: '{{zone}}'
        service_account_email: '{{ service_account_email }}'
        pem_file: '{{ pem_file }}'
        project_id: '{{ project_id }}'
      with_items:
        - centos-6
        - rhel-6
      register: gce
```
##### Expected Results:

```
PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [Launch instances] ****************************************************** 
changed: [127.0.0.1] => (item=centos-6)
changed: [127.0.0.1] => (item=rhel-6)

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=2    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [Launch instances] ****************************************************** 
changed: [127.0.0.1] => (item=centos-6)
failed: [127.0.0.1] => (item=rhel-6) => {"changed": false, "failed": true, "item": "rhel-6"}
msg: Missing required create instance variable

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/jlaska/test_gce.retry

127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1   
```
