### ISSUE TITLE
ansible_loop_var and ansible_index_var not working with ansible.builtin.include_tasks

### ISSUE THREAD

**Issue by shadowguardian507-irl** [ansible/ansible#82655]
### Summary

when trying to use `ansible.builtin.include_tasks` in a loop `ansible_loop_var` and `ansible_index_var` do not appear to work

### Issue Type

Bug Report

### Component Name

ansible.builtin.include_tasks

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/Users/shadowguardian507/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/9.1.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/shadowguardian507/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/usr/local/Cellar/ansible/9.1.0/libexec/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = nano
```

### OS / Environment

macOS 13.6.4 (22G513)

### Steps to Reproduce

playbook.yml
```yaml
---

- hosts: localhost
  gather_facts: false
  serial: 1
  vars:
    custom_suffix: "top"
    loop_data:
      - name: "one"
      - name: "two"
  tasks:
    - name: loop test
      ansible.builtin.include_tasks: include_tasks.yml
      loop: "{{ loop_data }}"
      loop_control:
        loop_var: "custom_dynamic_name_{{ custom_suffix }}"
        index_var: "custom_dynamic_index_{{ custom_suffix }}"
```

include_tasks.yml
``` yaml
---

- name: debug print ansible_loop_var
  ansible.builtin.debug:
    var: ansible_loop_var
    
- name: debug print ansible_index_var
  ansible.builtin.debug:
    var: ansible_index_var
```

place both the above in the same folder, then run the command `ansible-playbook ./playbook.yml` in that folder

### Expected Results

[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] **************************************************************************************************************************************************

TASK [loop test] **************************************************************************************************************************************************
included: /Users/shadowguardian507/dev/minimal-example/include_tasks.yml for localhost => (item={'name': 'one'})
included: /Users/shadowguardian507/dev/minimal-example/include_tasks.yml for localhost => (item={'name': 'two'})

TASK [debug print ansible_loop_var] *******************************************************************************************************************************
ok: [localhost] => {
    "ansible_loop_var": "custom_dynamic_name_top"
}

TASK [debug print ansible_index_var] ******************************************************************************************************************************
ok: [localhost] => {
    "ansible_index_var": "custom_dynamic_index_top"
}

TASK [debug print ansible_loop_var] *******************************************************************************************************************************
ok: [localhost] => {
    "ansible_loop_var": "custom_dynamic_name_top"
}

TASK [debug print ansible_index_var] ******************************************************************************************************************************
ok: [localhost] => {
    "ansible_index_var": "custom_dynamic_index_top"
}

### Actual Results

```console
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] **************************************************************************************************************************************************

TASK [loop test] **************************************************************************************************************************************************
included: /Users/shadowguardian507/dev/minimal-example/include_tasks.yml for localhost => (item={'name': 'one'})
included: /Users/shadowguardian507/dev/minimal-example/include_tasks.yml for localhost => (item={'name': 'two'})

TASK [debug print ansible_loop_var] *******************************************************************************************************************************
ok: [localhost] => {
    "ansible_loop_var": "VARIABLE IS NOT DEFINED!"
}

TASK [debug print ansible_index_var] ******************************************************************************************************************************
ok: [localhost] => {
    "ansible_index_var": "VARIABLE IS NOT DEFINED!"
}

TASK [debug print ansible_loop_var] *******************************************************************************************************************************
ok: [localhost] => {
    "ansible_loop_var": "VARIABLE IS NOT DEFINED!"
}

TASK [debug print ansible_index_var] ******************************************************************************************************************************
ok: [localhost] => {
    "ansible_index_var": "VARIABLE IS NOT DEFINED!"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
