### ISSUE TITLE
Version comparison failed: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by mowgli** [ansible/ansible#82667]
### Summary

```yaml
- name: Test
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg: "Test"
      when: '"1.6-6" is version ("1.6.3-3", ">=")'
```

The versions are clearly not int, they are both strings. But I get the error above.

For many other combinations, it work, but not for this.

The error happens under different ansibe versions like 7.7.0 or 2.7.7.

### Issue Type

Bug Report

### Component Name

version

### Ansible Version

```console
$ ansible --version

> ansible --version                    
ERROR: Ansible requires the locale encoding to be UTF-8; Detected ISO8859-1.
```

```console
> LC_ALL=C ansible --version
ERROR: Ansible requires the locale encoding to be UTF-8; Detected None.
```

```console
> LC_ALL=C.utf8 ansible --version
ansible [core 2.14.11]
  config file = /home/klaus/.ansible.cfg
  configured module search path = ['/home/klaus/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/klaus/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

(It is strange that there is a utf8 for C as C is per definition plain ASCII!

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

Doesn't apply, I have the error under many different configurations

### OS / Environment

Devuan but doesn't matter

### Steps to Reproduce

```yaml
- name: Test
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg: "Test"
      when: '"1.6-6" is version ("1.6.3-3", ">=")'
```

The versions are clearly not int, they are both strings. But I get the error above.

For many other combinations, it work, but not for this.

The error happens under different ansibe versions like 7.7.0 or 2.7.7.

### Expected Results

It works

### Actual Results

It doesn't work

### Code of Conduct

- [ ] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@mowgli `ansible-core` 2.14 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by mowgli** [comment]
As I wrote, that error happens under _ANY_ version! Even the oldest ever.

I tested under 2.7.7, 2.10.7 and the above, 7.7.0. I have no system where the version is higher than this one (7.7.0).

**Comment by mowgli** [comment]
I added a test playbook in the bug, so this can be easily checked under any version you are running.

**Comment by mkrizek** [comment]
This does not appear to be a bug.

> 1.6.3-3

What kind of versioning type are you using? Since you haven't specified [version_type](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/version_test.html#parameter-version_type) the default `loose` is used and so what happens with your example is comparison between `[1, 6, "-", 6]` and `[1, 6, 3, "-", 3]` - when comparing the third elements `"-"` and `3` you get `'<' not supported between instances of 'str' and 'int'`.

Maybe `pep440` (https://peps.python.org/pep-0440/#post-release-separators) would be suitable for your use case?

---
> As I wrote, that error happens under ANY version! Even the oldest ever.

The bot just parses the output of `ansible --version` given in the issue description, hence the comment about the unsupported version. The bot still have a ways to go before making sense of anything else written in the description :-)

**Comment by flowerysong** [comment]
> As I wrote, that error happens under _ANY_ version! Even the oldest ever.
> 
> I tested under 2.7.7, 2.10.7 and the above, 7.7.0. I have no system where the version is higher than this one (7.7.0).

Older versions are not relevant. You cannot know that a behaviour happens under "any version" until you've tested a newer version. If this were a legitimate bug, it could have been something that was fixed in 2.15.

**Comment by webknjaz** [comment]
Hey @mowgli why did you revoke the agreement to follow the Code of Conduct?

**Comment by mowgli** [comment]
Hi,

Am Fr den  9. Feb 2024 um 20:03 schrieb Sviatoslav Sydorenko (?????????????????? ??????????????????):
> Hey @mowgli why did you revoke the agreement to follow the Code of Conduct?

Because I do not know it, been no part of it, often the code of conduct
is used to harass others in a subtle kind and cause I never seen one
that I can agree with.

I try to be polite to others when they are.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by mowgli** [comment]
Hi,

Am Fr den  9. Feb 2024 um 11:16 schrieb Martin Krizek:
> This does not appear to be a bug.

Well, explain...

> > 1.6.3-3
> 
> What kind of versioning type are you using? Since you haven't specified [version_type](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/version_test.html#parameter-version_type) the default `loose` is used and so what happens with your example is comparison between `[1, 6, "-", 6]` and `[1, 6, 3, "-", 3]` - when comparing the third elements `"-"` and `3` you get `'<' not supported between instances of 'str' and 'int'`.
> 
> Maybe `pep440` (https://peps.python.org/pep-0440/#post-release-separators) would be suitable for your use case?

I did not specify cause I did not specify it.

That pep one could be a solution but it is not compatible to the
versions that are supported by the OS I use.

But even if it could be a solution, the version comparing should never
crash with such an error if both strings _are_ strings. Every input
should at least return true or false. That can be wrong if the wrong
scheme is chosen but it should be still true or false.

> > As I wrote, that error happens under ANY version! Even the oldest ever.
> 
> The bot just parses the output of `ansible --version` given in the issue description, hence the comment about the unsupported version. The bot still have a ways to go before making sense of anything else written in the description :-)

Ah, ok, I did feel a bit offended by that answer that seems not to
consider my full report.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by konstruktoid** [comment]
`ansible [core 2.16.3]`: 

```yaml
---
- name: Testing
  hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - debug:
        msg: "Test"
      when: '"1.6-6" is version ("1.6.3-3", ">=")'   
```

```sh
fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check '\"1.6-6\" is version (\"1.6.3-3\", \">=\")' failed. The error was: Version comparison failed: '<' not supported between instances of 'str' and 'int'\n\nThe error appears to be in '/home/tsj/Code/Git/tmpvag/test.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug:\n      ^ here\n"}
```

The following works, just as @mkrizek said:

```sh
---
- name: Testing
  hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - debug:
        msg: "Test"
      when: '"1.6-6" is version ("1.6.3-3", ">=", version_type="pep440" )'
```

**Comment by mowgli** [comment]
Hi,

Am Fr den  9. Feb 2024 um 11:16 schrieb Martin Krizek:
> What kind of versioning type are you using? Since you haven't specified [version_type](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/version_test.html#parameter-version_type) the default `loose` is used and so what happens with your example is comparison between `[1, 6, "-", 6]` and `[1, 6, 3, "-", 3]` - when comparing the third elements `"-"` and `3` you get `'<' not supported between instances of 'str' and 'int'`.
> 
> Maybe `pep440` (https://peps.python.org/pep-0440/#post-release-separators) would be suitable for your use case?

For that particular versions, it works. But in when I use that pep
scheme, version "1:6.7-1" does not anymore.

I need to compare the version scheme that can appear with a devuan (or
other distribution). At least it should not break.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by konstruktoid** [comment]
just out of curiosity, is `1:6.7-1` an actual version?

can you give some more real world examples when this doesn't work?

**Comment by mowgli** [comment]
Am So den 11. Feb 2024 um 11:40 schrieb Thomas Sjögren:
> just out of curiosity, is `1:6.7-1` an actual version?
> 
> can you give some more real world examples when this doesn't work?

```
~> dpkg -l ethtool
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name           Version      Architektur  Beschreibung
+++-==============-============-============-==========================================
ii  ethtool        1:6.7-1      amd64        display or change Ethernet device settings
```

I do some work depending tu the version as debian decided to make higher
versions incompatible to lowers in therme of where to find the tool.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by konstruktoid** [comment]
Depending if you're concerned about the epoch version (https://www.debian.org/doc/debian-policy/ch-controlfields.html#version), you can always do a comparison on that was well.

```yaml
---
- name: Testing
  hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  vars:
    version_test: 1:5.16-1
  tasks:
    - name: Print version
      ansible.builtin.debug:
        msg: Version is {{ version_test }}

    - name: Parse version
      ansible.builtin.set_fact:
        version: "{{ version_test | split(':') }}"

    - name: Test is version is <= 1:5.15-1
      ansible.builtin.debug:
        msg: Test <= 5.15-1
      when: version[1] is version("5.15-1", "<=", version_type="pep440")

    - name: Test is version is >= 1:5.15-1
      ansible.builtin.debug:
        msg: Test >= 5.15-1
      when: version[1] is version("5.15-1", ">=", version_type="pep440")
 ```
