### ISSUE TITLE
ansible-inventory extra vars

### ISSUE THREAD

**Issue by jseifeddine** [ansible/ansible#82673]
### Summary

https://docs.ansible.com/ansible/latest/cli/ansible-inventory.html#cmdoption-ansible-inventory-e

Here it documents the option to pass extra variable to ansible-inventory... 

I made a custom [mysql dynamic inventory plugin](https://github.com/j-oss2023/mysql-dynamic-inventory)  that builds an inventory from MySQL query, using a .yml for inventory config like so:
```yaml
#   Required columns: 
#   'inventory_group', 'inventory_hostname'
#
#   TLDR:
#   Besides the required columns, each column will be assigned 
#   as an ansible hostvar dynamically.

plugin: mysql-dynamic-inventory
db_host: mysql_server
db_user: mysql_user
db_pass: mysql_pass
db_name: mysql_database
db_query: |
  SELECT 'some_inventory_hostname' as inventory_hostname, 'some_inventory_group' as inventory_group, 'some_ansible_host' as ansible_host, 'somerandomvar' as coolrandomvar
```

Why can't I access the extra vars ? What is the point of the -e option for ansible-inventory if it doesn't work... it's not documented very well and driving me down a rabbit hole..

### Issue Type

Documentation Report

### Component Name

ansible-inventory

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CACHE_PLUGIN(/etc/ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /etc/ansible/.ansible-cache
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 86400
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/action_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/plugins/filter']
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventory/hosts.yml']
DEFAULT_INVENTORY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/plugins/inventory']
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /etc/ansible/.tmp/ansible-local-3092018t1per_u4
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/.ssh/id_rsa
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python

CACHE:
=====

jsonfile:
________
_timeout(/etc/ansible/ansible.cfg) = 86400
_uri(/etc/ansible/ansible.cfg) = /etc/ansible/.ansible-cache

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

### Additional Information

It would be nice to use the vars like so... 

```yaml
#   Required columns: 
#   'inventory_group', 'inventory_hostname'
#
#   TLDR:
#   Besides the required columns, each column will be assigned 
#   as an ansible hostvar dynamically.

plugin: mysql-dynamic-inventory
db_host: "{{mysql_server}}"
db_user: "{{mysql_user}}"
db_pass: "{{mysql_pass}}"
db_name: "{{mysql_database}}"
db_query: |
  SELECT 'some_inventory_hostname' as inventory_hostname, 'some_inventory_group' as inventory_group, 'some_ansible_host' as ansible_host, '{{random_extra_var}}' as coolrandomvar
```

Having clear concise explanation of -e option in ansible-inventory, namely explaining that it doesnt work like everywhere else as expected would be wonderful 

Thanks :) 

@jborean93 mentioned it could use clarification in this closed issue

https://github.com/ansible/ansible/issues/77339#issuecomment-1077971932

I agree 👍 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
