### ISSUE TITLE
[dnf] Installing package does not respect wildcard character in local filename

### ISSUE THREAD

**Issue by batbattur** [ansible/ansible#82689]
### Summary

I have a custom file `/tmp/build/beanstalkd-git-1.13_x86_64.rpm`:

The following task fails when trying to use a wildcard in the name:

```
- name: 'Install beanstalkd package'
  ansible.builtin.dnf:
    name: "/tmp/build/beanstalkd-git-*.rpm"
    state: present
```

Output:
```
Could not open: /tmp/build/beanstalkd/beanstalkd-git-*.rpm\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

Manually installing with `dnf install /tmp/build/beanstalkd/beanstalkd-git-*.rpm` works fine and finds the file using the wildcard.

I see wildcard support for dnf remove command in https://github.com/ansible/ansible/issues/36970 but not sure if it also works for install.

### Issue Type

Bug Report

### Component Name

dnf

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.2]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Fedora 39

### Steps to Reproduce

```yaml (paste below)
- name: 'Install beanstalkd package'
  ansible.builtin.dnf:
    name: "/tmp/build/beanstalkd-git-*.rpm"
    state: present
```

### Expected Results

To respect the wildcard for filenames. 

### Actual Results

```console
Could not open: /tmp/build/beanstalkd/beanstalkd-git-*.rpm\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
