### ISSUE TITLE
Inconsistent vars handling within set_fact block

### ISSUE THREAD

**Issue by mhitza** [ansible/ansible#82698]
### Summary

Using `vars` alongside `set_fact` has inconsistent behaviour when an existing variable is overwritten in the vars block.

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.3]
  config file = /repo/ansible.cfg
  configured module search path = ['/home/dm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dm/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /repo/collections
  executable location = /home/dm/.local/bin/ansible
  python version = 3.12.1 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
COLLECTIONS_PATHS(/repo/ansible.cfg) = ['/repo/collections']
CONFIG_FILE() = /repo/ansible.cfg
DEFAULT_PRIVATE_KEY_FILE(/repo/ansible.cfg) = /repo/id_ansible_rsa
DEFAULT_REMOTE_USER(/repo/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/repo/ansible.cfg) = ['/repo/roles']
EDITOR(env: EDITOR) = /usr/bin/vim
HOST_KEY_CHECKING(/repo/ansible.cfg) = False
VARIABLE_PLUGINS_ENABLED(/repo/ansible.cfg) = ['host_group_vars', 'community.sops.sops'] 

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/repo/ansible.cfg) = False
private_key_file(/repo/ansible.cfg) = id_ansible_rsa
remote_user(/repo/ansible.cfg) = ansible

ssh:
___
host_key_checking(/repo/ansible.cfg) = False
private_key_file(/repo/ansible.cfg) = id_ansible_rsa
remote_user(/repo/ansible.cfg) = ansible
```

### OS / Environment

Ubuntu 22.04 guest, and Fedora 39 host.

### Steps to Reproduce

```yaml (paste below)
- ansible.builtin.set_fact:
    status: "no a json"

- ansible.builtin.shell: >
     echo "{ \"Self\": { \"Online\": true }, \"Version\": 1.0 }"
  changed_when: false
  register: tailscale_status

- vars:
    status: "{{ tailscale_status.stdout | from_json }}" # <- does not take place
  ansible.builtin.set_fact:
    tailscale_is_online: "{{ status.Self.Online }}"
    tailscale_version: "{{ status.Version }}"
```

### Expected Results

Consistency. Either `status` is updated all the time, or never within the set_fact block.

### Actual Results

```console
If `status` is not already defined beforehand the instruction pointed at is executed, and value usable in followup set_fact. If `status` is already defined, the current `status` value is used within the set_fact.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/set_fact.py)
* [`lib/ansible/plugins/action/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/set_fact.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
This is not a bug. The value of `status` is consistent with the documented variable precedence in https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#ansible-variable-precedence

"set_fact" is 19th on the list, "task vars" is 17th. 19 is higher than 17, so the value from the first `set_fact` is the correct one for `status` to have when evaluating this task's arguments.

**Comment by mhitza** [comment]
Thanks for the note, I wasn't aware of that precendence list further on than the order in which vars are loaded from files (and even then I have to look them up).

Where I've encountered the error, the status variable was set via the register attribute on a replace module call, eg:

```yaml
- name: Activate gpg-check for config files
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: ^\s*gpgcheck\W.*
    replace: gpgcheck=1
    mode: "0644"
  register: status
  failed_when: status.rc is defined and status.rc not in (257, 0)
  loop:
    - /etc/yum.conf
    - /etc/dnf/dnf.conf
    - /etc/yum/pluginconf.d/rhnplugin.conf
```

What kind of var is status in this case? Still a task var? Because that triggers the error as well, and set_fact is how I created the PoC without knowing about the precendence list.
