### ISSUE TITLE
delegate_to does not replace jinja variables

### ISSUE THREAD

**Issue by skwde** [ansible/ansible#82693]
### Summary

When I try to delegate a task to some machine, ansible does not replace the jinja variables but rather tries to connect to the template variables, e.g. `[clt-mgt06 -> srv01({{ inventory_hostname_short }}.{{ global__host_domain }})]`

### Issue Type

Bug Report

### Component Name

delegate_to

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.3]
  config file = $HOME/_tests/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = <mambaforge base>/envs/ansible/lib/python3.12/site-packages/ansible
  ansible collection location = $HOME/.ansible/collections:/usr/share/ansible/collections
  executable location = <mambaforge base>/envs/ansible/bin/ansible
  python version = 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0] (<mambaforge base>/envs/ansible/bin/python3.12)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = $HOME/_tests/ansible.cfg
EDITOR(env: EDITOR) = vim
```

### OS / Environment

Rocky9

### Steps to Reproduce

Use following inventory
```yaml
---
all:
  vars:
    # ## ssh related
    global__host_domain: sub.mydomain.net
    ansible_host: "{{ inventory_hostname_short }}.{{ global__host_domain }}"

test:
  hosts:
    clt-mgt06:
    srv01:
```

and run the playbook `test-plybk.yml`

```yml
- name: Test stuff
  gather_facts: true
  gather_subset: ["system", "!all", "!min"]
  hosts: clt-mgt06
  tasks:
    - name: No delegation debug
      ansible.builtin.shell: echo $(hostname -f)
    - name: Delegation debug
      ansible.builtin.shell: echo $(hostname -f)
      delegate_to: srv01
```

via 

```sh
ansible-playbook -i test-inventory.yml test-plybk.yml -v
```

and notice

```out
TASK [No delegation debug] ***************************************************************************************************************
changed: [clt-mgt06] => {"changed": true, "cmd": "echo $(hostname -f)", "delta": "0:00:00.003391", "end": "2024-02-15 06:46:38.995940", "msg": "", "rc": 0, "start": "2024-02-15 06:46:38.992549", "stderr": "", "stderr_lines": [], "stdout": "clt-mgt06.mydomain.net", "stdout_lines": ["clt-mgt06.mydomain.net"]}

TASK [Delegation debug] ******************************************************************************************************************
changed: [clt-mgt06 -> srv01({{ inventory_hostname_short }}.{{ global__host_domain }})] => {"changed": true, "cmd": "echo $(hostname -f)", "delta": "0:00:00.005980", "end": "2024-02-15 07:46:39.526996", "msg": "", "rc": 0, "start": "2024-02-15 07:46:39.521016", "stderr": "", "stderr_lines": [], "stdout": "srv01.mydomain.net", "stdout_lines": ["srv01.mydomain.net"]}
```

especially `ok: [clt-mgt06 -> srv01({{ inventory_hostname_short }}.{{ global__host_domain }})] => {`

### Expected Results

I would expect that instead of `ok: [clt-mgt06 -> srv01({{ inventory_hostname_short }}.{{ global__host_domain }})] => {`
`ok: [clt-mgt06 -> srv01(srv01.sub.mydomain.net)] => {` is used and that the echo output is `srv01.sub.mydomain.net` instead of `srv01.mydomain.net` (which is the default)

### Actual Results

```console
Delegation not working as expected. The jinja variables from the inventory are not replaced which leads to the wrong domain.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
