### ISSUE TITLE
Ansible Requires Collections and Roles for Skipped Tasks When Using Tags

### ISSUE THREAD

**Issue by jangel97** [ansible/ansible#82716]
#### Summary:
When running an Ansible playbook with specific tags to skip certain roles/tasks, Ansible still requires the presence of collections and roles that are entirely skipped due to the tag selection. 

This behavior seems inefficient and counterintuitive, as users might expect that skipping tasks/roles with tags would also skip their dependencies unless those dependencies are needed by other included tasks/roles.

#### Issue Description:
While using tags to control the execution of certain parts of a playbook, it has been observed that Ansible still mandates the installation or presence of collections and roles that are not involved in the current execution path. For example, if a playbook includes roles or tasks tagged with 'setup', 'deploy', and 'cleanup', and the playbook is run with `--tags "deploy"`, Ansible would still require the collections and roles associated with 'setup' and 'cleanup', even though they are clearly not going to be executed.

#### Steps to Reproduce:
1. Create a playbook that includes multiple roles or tasks, each tagged with distinct tags.
2. Ensure at least one role or task requires a collection or role not currently installed or present.
3. Run the playbook with the `--tags` option to specifically include only a subset of the roles/tasks that do not require the missing collection/role.
4. Observe that Ansible fails due to the missing collection/role, despite it not being needed for the selected tasks.

#### Expected Behavior:
Ansible should analyze the execution path based on the specified tags and skip the requirement checks for collections and roles associated with tasks/roles that are not included in the execution due to the tag selection.

#### Actual Behavior:
Ansible fails the playbook run due to missing collections/roles that are dependencies of tasks/roles skipped by the tag selection.

### Issue Type

Bug Report

### Component Name

core ansible

### Ansible Version

```console
$ ansible --version
#### Ansible Version:

[cloud-user@rhel9---default ~]$ ansible --version
ansible [core 2.14.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/cloud-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/cloud-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
```


### Configuration

```console
### Configuration


[cloud-user@rhel9---default ~]$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

RHEL 9

#### 1. Create Sample Roles
First, create two sample roles with distinct tasks that would normally require different collections or roles not present in your base installation.

1. **Role A**: Create a role named `role_a` that includes tasks or dependencies requiring a specific collection or role.
2. **Role B**: Create a role named `role_b` with tasks that do not require any additional collections or roles.

#### 2. Create a Playbook
Create a playbook named `sample_playbook.yml` that includes both `role_a` and `role_b`, each tagged appropriately.

```yaml
---
- hosts: all
  gather_facts: no
  tasks:
    - name: Include role_a
      ansible.builtin.include_role:
        name: role_a
      tags: 
        - setup

    - name: Include role_b
      ansible.builtin.include_role:
        name: role_b
      tags:
        - deploy
```

#### 3. Omit Required Collection or Role for Role A
Ensure that the collection or role required by `role_a` is not installed. This setup is crucial to demonstrate that Ansible attempts to check for dependencies of skipped tasks.

#### 4. Run the Playbook with Tags to Include Only Role B
Execute the playbook with the `--tags` option to only run tasks tagged with `deploy`, which should theoretically skip `role_a` and its dependencies.

```bash
ansible-playbook -i your_inventory_file sample_playbook.yml --tags "deploy"
```

#### 5. Observe the Behavior
The expected behavior is that Ansible will only execute tasks associated with `role_b` and ignore `role_a` since it's not tagged for execution. However, if the bug is present, Ansible will fail the execution or report an error indicating that the dependencies for `role_a` (which are not necessary for the tagged tasks to run) are missing.

### Expected vs. Actual Behavior:
- **Expected Behavior**: Ansible skips the checks for dependencies related to `role_a` since it is not included in the execution path defined by the `--tags "deploy"` option.
- **Actual Behavior**: Ansible fails or reports an error due to missing dependencies for `role_a`, despite it being irrelevant to the tasks selected for execution.

This discrepancy highlights the bug and demonstrates that Ansible's current behavior may not align with logical expectations regarding tag-based execution and dependency resolution.

### Expected Results

- **Expected Behavior**: Ansible skips the checks for dependencies related to `role_a` since it is not included in the execution path defined by the `--tags "deploy"` option.

### Actual Results

```console
- **Actual Behavior**: Ansible fails or reports an error due to missing dependencies for `role_a`, despite it being irrelevant to the tasks selected for execution.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`bin/ansible`](https://github.com/ansible/ansible/blob/devel/bin/ansible)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by sivel** [comment]
I cannot reproduce with the information you have provided.  When describing actual behavior it is best to actually provide the output.  Additionally, a full reproducer is needed, otherwise we have to make assumptions about how to reconstruct something we've never seen, with missing output.

It should be noted that adding `tags` to an include only tags the include itself, and not the tasks within. So unless there is more information concerning the tagging of the tasks within, this playbook is a noop effectively.

That aside, includes work exactly as you desire.  If the tag doesn't match, the include never happens, and nothing within the role is evaluated.

Much more information is required for us to have any clue what is going on in your actual playbooks.

**Comment by jangel97** [comment]
Hello,

I'm finding an issue while executing a playbook designed to configure various system aspects. Here's the playbook in question:

```yaml
# base_configuration.yml
---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  collections:
    - community.hashi_vault
  vars:
    override_ipaclient_force_join: false
    force_clevis_update: false

  pre_tasks:
    - name: Write to log
      community.general.syslogger:
        msg: Base configuration
        ident: "<<<=== AAP ===>>>"
        priority: notice
        facility: user

  roles:
    - role: redhatit.subscriptionmanager_wrap
      when: no_sat6_registration is undefined
      tags: subscription_manager

    - role: redhatit.root_pw
      when: no_root_pw is undefined
      tags: root_password

    - role: redhatit.motd
      when: no_motd is undefined
      tags: motd

    - role: redhatit.bash_prompt
      when: no_bash_prompt is undefined
      tags: bash_prompt

    - role: redhatit.ca-trust
      when: no_ca_trust is undefined
      tags: ca_trust

    - role: redhatit.bluetooth_disable
      when: no_bluetooth_disable is undefined
      tags: bluetooth_disable

    - role: redhatit.auditd
      when: no_auditd is undefined
      tags: auditd

    - role: redhatit.logrotate
      when: no_logrotate is undefined
      tags: logrotate

    - role: redhatit.custom-policy-tune
      when: no_custom_policy_tune is undefined
      tags: custom_policy_tune

    - role: redhatit.common-tooling
      when: no_common_tooling is undefined
      tags: common_tooling

    - role: redhatit.software_update
      when: no_software_update is undefined
      tags: software_update

    - role: redhatit.ipaclient_wrap
      when: no_ipaclient_wrap is undefined
      tags: ipa_client

    - role: redhatit.sshd_wrap
      when: no_sshd_wrap is undefined
      tags: sshd_wrap

    - role: redhatit.splunk_client
      vars:
        splunk_skip_repo: true
      when: no_splunk_client is undefined
      tags: splunk_client

    - role: redhatit.signalfx_otel_collector_wrap
      vars:
        signalfx_extraDimensions:
          appcode: "{{ inventory_hostname.split('.')[1] | upper }}"
        sfx_skip_repo: true
      when: no_signalfx_smart_agent_wrap is undefined
      tags: signalfx_otel_collector

    - role: redhatit.sshd_remedy
      when: no_sshd_remedy is undefined
      tags: sshd_remedy

    - role: redhatit.sudo
      when: itiam_sudoers is defined
      tags: sudo

    - role: redhatit.crypto-policies
      when:
        - no_crypto_policies is undefined
        - ansible_distribution_major_version >= '8'
      tags: crypto-policies

    - role: qualys-cloud-agent
      when:
        - no_qualys_agent is undefined
        - qualys_activation_id | default('', true)
        - qualys_customer_id | default('', true)
      tags: qualys-cloud-agent

  tasks:
    - name: "NTP configuration"
      ansible.builtin.include_tasks: tasks/timesync.yml
      when: no_ntp is undefined
      tags: ntp

    - name: "SELinux configuration"
      ansible.builtin.include_tasks: tasks/selinux.yml
      when: no_selinux is undefined
      tags: selinux

    - name: "Journald configuration"
      ansible.builtin.include_tasks: tasks/journald.yml
      when: no_journald is undefined
      tags: journald

    - name: "Postfix configuration"
      ansible.builtin.include_tasks: tasks/postfix.yml
      when: no_postfix is undefined
      tags: postfix

    - name: "Kernel network configuration"
      ansible.builtin.include_tasks: tasks/network-kernel.yml
      when: no_network_kernel is undefined
      tags: network_kernel

    - name: "Grub configuration"
      ansible.builtin.include_tasks: tasks/grub.yml
      when: no_grub_config is undefined
      tags: grub

    - name: "Firewalld configuration"
      ansible.builtin.include_tasks: tasks/firewalld.yml
      when: no_firewalld is undefined
      tags: firewalld

    - name: "SSH Client"
      ansible.builtin.include_tasks: tasks/ssh_client.yml
      when: no_ssh_client is undefined
      tags: ssh_client

    - name: Run clevis role
      ansible.builtin.include_role:
        name: redhatit.clevis
      when: no_clevis is undefined
      tags: clevis
```

I attempted to run this playbook specifically targeting the `sshd_remedy` tag using the command `ansible-playbook base_configuration.yml -i localhost --tags "sshd_remedy"`.

However, I received the following error message:

```
ERROR! the role 'redhatit.subscriptionmanager_wrap' was not found in community.hashi_vault:ansible.legacy:/home/cloud-user/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/cloud-user
```

This error suggests that Ansible is attempting to validate or load roles not relevant to the specific tags requested for execution, in this case, `sshd_remedy`. Based on my understanding, roles and tasks not included in the specified tags should be ignored, including their dependencies or prerequisites.

Is my interpretation correct, or am I missing something? I anticipated that only tasks and roles tagged with `sshd_remedy` would be considered for execution, thus bypassing the need for the `redhatit.subscriptionmanager_wrap` role in this instance.
