### ISSUE TITLE
module_utils/common/respawn.py fails when arguments include string with dictionary literal

### ISSUE THREAD

**Issue by eravin-duo** [ansible/ansible#82738]
### Summary

When we tried to use `module_utils/common/respawn.py` in our Ansible module, it failed with `Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed` when we passed it a dictionary with a key whose value was `'{\\"dict1\\": {\\"thing1\\": \\"abcdefghijklmnopqrstuvwxyz\\", \\"thing2\\": \\"foo/bar/\\"}}'` (a string literal that represents a dictionary).

### Issue Type

Bug Report

### Component Name

respawn.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.9]
  config file = None
  configured module search path = ['/home/edravin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/edravin/ansible-upgrade-3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /home/edravin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/edravin/ansible-upgrade-3.9/bin/ansible
  python version = 3.9.18 (main, Feb 20 2024, 19:40:58) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/home/edravin/ansible-upgrade-3.9/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

CentOS7

### Steps to Reproduce

```yaml (paste below)
[ans-test]$ find . -type f
./library/respawnme.py
./inventory
./respawn.yml

[ans-test]$ cat library/respawnme.py 
#!/usr/bin/python

import os
import sys

from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.common.respawn import respawn_module, has_respawned


def main():
    mod = AnsibleModule(argument_spec=dict(
        thing=dict(required=True, type='dict')
    ))

    if not has_respawned():
        new_interpreter = os.path.join(mod.tmpdir, 'anotherpython')
        os.symlink(sys.executable, new_interpreter)
        respawn_module(interpreter_path=new_interpreter)

        # respawn should always exit internally- if we continue executing here, it's a bug
        raise Exception('FAIL, should never reach this line')
    else:
        # return the current interpreter, as well as a signal that we created a different one
        mod.exit_json(created_interpreter=sys.executable, interpreter_path=sys.executable, thing=mod.params['thing'])


if __name__ == '__main__':
    main()

ans-test]$ cat respawn.yml 
---

- name: test respawn with arguments
  hosts: funhosts
  gather_facts: no

  tasks:
  - name: show Ansible version
    debug:
      var: ansible_version.full

  - name: test respawn module
    respawnme:
      thing:
        nested_dict_string: '{\\"dict1\\": {\\"thing1\\": \\"abcdefghijklmnopqrstuvwxyz\\", \\"thing2\\": \\"foo/bar/\\"}}'
    ignore_errors: true

  - name: test it again with something less strenuous
    respawnme:
      thing:
        normal_string: 'the quick brown fox jumped over the lazy dog.'
    register: done

  - name: show args received by respawned module
    debug:
      var: done
```

### Expected Results

Module should be able to respawn successfully, regardless of what strings are in the arguments.

The example below is based on the unit test in `ansible/test/integration/targets/module_utils_common.respawn`

### Actual Results

```console
[ans-test]$ ansible-playbook -i inventory  respawn.yml 

PLAY [test respawn with arguments] *********************************************

TASK [show Ansible version] ****************************************************
ok: [testhost] => {
    "ansible_version.full": "2.15.9"
}

TASK [test respawn module] *****************************************************
fatal: [testhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed"}
...ignoring

TASK [test it again with something less strenuous] *****************************
ok: [testhost]

TASK [show args received by respawned module] **********************************
ok: [testhost] => {
    "done": {
        "ansible_facts": {
            "discovered_interpreter_python": "/usr/bin/python"
        },
        "changed": false,
        "created_interpreter": "/root/.ansible/tmp/ansible-tmp-1708733422.4494996-13210-16673739077408/anotherpython",
        "failed": false,
        "interpreter_path": "/root/.ansible/tmp/ansible-tmp-1708733422.4494996-13210-16673739077408/anotherpython",
        "thing": {
            "normal_string": "the quick brown fox jumped over the lazy dog."
        }
    }
}

PLAY RECAP *********************************************************************
testhost : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
