### ISSUE TITLE
docker module doesn't restart container

### ISSUE THREAD

**Issue by rubycut** [ansible/ansible#8278]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Ubuntu 12.04, managing ubuntu 12.04
##### Summary:

Docker module doesn't restart container if wrong tag is running.
##### Steps To Reproduce:

start container with one tag

use docker module to put container in running state with another tag
##### Expected Results:

Container should be restarted with proper tag.
##### Actual Results:

Nothing happens, old version remains running, msg is:

```
"msg": "pull 0 restarted 0 started 0 created 0 stopped 0 removed 0 killed 0  container(s) running image docker.xxx.net/app:3.4.21 with command None"
```

**Comment by mpdehaan** [comment]
Can you please share the ansible commands you used for each of the above steps?

It's unclear how to reproduce this for me right now and that would help a lot.

Thanks!

**Comment by rubycut** [comment]
```
# Dockerfile
FROM ubuntu:12.04
RUN echo test image   
CMD sleep 1000
```

Make first image:

```
docker build -t test:1.0 .
```

Edit file:

```
 # Dockerfile 2.0
FROM ubuntu:12.04
RUN echo test image  2
CMD sleep 1000
```

Make second image:

```
docker build -t test:2.0 .
```

Ansible recipe:

```
- hosts:
    - myhost
  tasks:
    - docker: image=test:1.0  state=running
```

Run version 1:

```
ansible-playbook test_docker.yml
```

Try switching to version 2:

```
---
- hosts:
  - sysmon.jenkins
  tasks:
    - docker: image=test:2.0  state=running
```

Run version 2:

```
ansible-playbook test_docker.yml
```

docker image with tag 1.0 is still running, It was not restarted switched to image with version 2
