### ISSUE TITLE
module_utils/urls.py MAXHEADERS

### ISSUE THREAD

**Issue by dc-tec** [ansible/ansible#82780]
### Summary

When using a module that uses the underlying module_utils/urls.py and a API response returns more than 100 headers an error is thrown.

The default is set to return a max of 100 headers. However we are doing a API call agains VMWare Cloud Director and this API call returns 109 headers and thus throws an error. 

A quick and dirty fix is to set: `http.client._MAXHEADERS = 1000` for example under module_utils/urls.py.

There is probably a better way to handle this.

### Issue Type

Bug Report

### Component Name

/lib/ansible/module_utils/urls.py

### Ansible Version

```console
ansible [core 2.16.4]
  config file = None
  configured module search path = ['/home/roelc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/linuxbrew/.linuxbrew/Cellar/ansible/9.3.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /home/roelc/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/linuxbrew/.linuxbrew/bin/ansible
  python version = 3.12.2 (main, Feb  6 2024, 20:19:44) [GCC 11.4.0] (/home/linuxbrew/.linuxbrew/Cellar/ansible/9.3.0/libexec/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
ansible-vcd-collection ❯ ansible-config dump --only-changed                                                                                    on  development [!+] via 🐍 v3.12.2 (base)
CONFIG_FILE() = None
EDITOR(env: EDITOR) = nvim
PAGER(env: PAGER) = less
```

### OS / Environment

Ubuntu 24.04 (workstation)
CentOS Stream9 (Ansible Execution Environment)

### Steps to Reproduce

```yaml
- name: Login VCD API
  hosts: localhost
  connection: local

  tasks:
    - name: Login VCD
      vcd_api_login:
        username: "{{ vcd_user }}"
        password: "{{ vcd_password }}"
        api_version: "38.1" ## Defaults to 38.1
        provider: True ## Defaults to false
      register: auth
      no_log: False

    - name: Get DC group ID
      ansible.builtin.uri:
        url: "https://portal.xyz.com/cloudapi/1.0.0/vdcGroups?page=1&pageSize=100&sort&links=false"
        headers:
          Authorization: "Bearer {{ auth.token }}"
          Accept: "application/json;version=38.1"
        method: GET
        status_code: 200
      register: result

    - name: debug
      debug:
        msg: "{{ result }}"

```

### Expected Results
```console
PLAY [Login VCD API] ***********************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Login VCD] ***************************************************************
changed: [localhost]

TASK [Get VDC Group] ***********************************************************
changed: [localhost]

TASK [Get DC group ID] *********************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "cache_control": "no-store, must-revalidate",
        "changed": false,
        "connection": "close",
        "content_location": "https://portal.xyz.com/cloudapi/1.0.0/vdcGroups",
        "content_type": "application/json;version=38.1",
        "cookies": {},
        "cookies_string": "",
        "date": "Wed, 06 Mar 2024 21:45:46 GMT",
        "elapsed": 0,
        "failed": false,
        "json": {
            "associations": null,
            "page": 1,
            "pageCount": 1,
            "pageSize": 100,
            "resultTotal": 31,
            "values": []
....
```
### Actual Results

```console
PLAY [Login VCD API] ***********************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Login VCD] ***************************************************************
changed: [localhost]

TASK [Get VDC Group] ***********************************************************
changed: [localhost]

TASK [Get DC group ID] *********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: http.client.HTTPException: got more than 100 headers
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: An unknown error occurred: got more than 100 headers", "redirected": false, "status": -1, "url": "https://portal.simaccloud.com/cloudapi/1.0.0/vdcGroups?page=1&pageSize=100&sort&links=false"}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
