### ISSUE TITLE
ansible.builtin.to_datetime filter - seconds and total_seconds return the same value

### ISSUE THREAD

**Issue by msl0** [ansible/ansible#82813]
### Summary

`to_datetime` filter not working properly

### Issue Type

Bug Report

### Component Name

ansible.builtin.to_datetime

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.13]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
---
- name: Test
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - ansible.builtin.debug:
        msg: 
          - "{{ (('2016-08-14 20:00:12' | to_datetime) - ('2016-08-14 18:00:00' | to_datetime)).seconds }}"
          - "{{ (('2016-08-14 20:00:12' | to_datetime) - ('2016-08-14 18:00:00' | to_datetime)).total_seconds() }}"
          - "{{ (('2016-08-14 20:00:12' | to_datetime) - ('2015-12-25' | to_datetime('%Y-%m-%d'))).seconds }}"
          - "{{ (('2016-08-14 20:00:12' | to_datetime) - ('2015-12-25' | to_datetime('%Y-%m-%d'))).total_seconds() }}"
```

### Expected Results

According to the documentation, the expected result from the first line of output of the debug module is "12"
https://github.com/ansible/ansible/blob/d9e798b48f62fdc2b604a84c36eb83c985f87754/lib/ansible/plugins/filter/to_datetime.yml#L25-L27

### Actual Results
The first two lines of output return the same number of seconds, so there is no difference between `.seconds` and 
```console
`.total_seconds()`
TASK [ansible.builtin.debug] *******************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "7212",
        "7212.0",
        "72012",
        "20203212.0"
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
