### ISSUE TITLE
Ansible Facts/variables not saving multi-host play debug to a file

### ISSUE THREAD

**Issue by lurk-er** [ansible/ansible#82824]
### Summary

I am trying to manage files and view the changes when running through a playbook. At each play, I am registering debug output into a variable, and then at the very end of the play book, i am trying to print all variables to a file for logging. to do this, here is a very basic view of what my playbook looks like.

when i try to save this to a file, its a 50/50 chance that all hosts have their debug information added to the file.
this is where things get interesting If i add a debug line like this at the end of the play book, all facts get printed to the console.

(I could use ansibles debug/logging feature, however i need to apply some specific logic to it to get the data i need in the format i want based on the collected facts, from my understanding, i cant do that with ansible debug).

### Issue Type

Bug Report

### Component Name

variables

### Ansible Version

```console
ansible [core 2.16.4]
  config file = /home/user/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = /home/user/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/user/ansible/ansible.cfg) = ['/home/user/ansible/hosts']
DEFAULT_PRIVATE_KEY_FILE(/home/user/ansible/ansible.cfg) = /home/user/.ssh/id_ansible
DEFAULT_STDOUT_CALLBACK(/home/user/ansible/ansible.cfg) = ansible.builtin.default

CONNECTION:
==========

paramiko_ssh:
____________
private_key_file(/home/user/ansible/ansible.cfg) = ~/.ssh/id_ansible

ssh:
___
private_key_file(/home/user/ansible/ansible.cfg) = ~/.ssh/id_ansible
```

### OS / Environment

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
WSL 2

### Steps to Reproduce

```yaml
- hosts: all
  become: true
  tasks:
      # the hostname contains '.' so they need to be stripped at the first one
    - name: get hostnames
      ansible.builtin.command:
        cmd: hostname
      register: hostname

    - name: get file hash
      ansible.builtin.stat:
        checksum_algorithm: sha512
        get_checksum: true
        path: /foo/bar.tmp
      register: file_stats

    - name: write to tmp file
      ansible.builtin.lineinfile:
        path: ./working/audit.tmp
        create: true
        line: "{{ hostname.stdout.split('.')[0] | to_nice_yaml}}{{ ansible_date_time.iso8601 | to_nice_yaml }}{{ file_stats.stat.checksum | to_nice_yaml }}{{ file_stats.stat.path | to_nice_yaml }}"
      delegate_to: localhost
      
  - debug:
    msg: "{{ hostname.stdout.split('.')[0] | to_nice_yaml}}{{ ansible_date_time.iso8601 | to_nice_yaml }}{{ file_stats.stat.checksum | to_nice_yaml }}{{ file_stats.stat.path | to_nice_yaml }}"

```

### Expected Results

I expect that all debug output registered in debug msg should be written to the file every time

### Actual Results

```console
The play book runs as expected, sometimes only some host information gets saved to the file, sometimes all host information gets saved to the file. all host information is always printed with debug successfully every time
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
