### ISSUE TITLE
Unable to install Python 3.10.13 with Ansible 2.10.6.

### ISSUE THREAD

**Issue by jimmyihuoma1** [ansible/ansible#82830]
### Summary

Unable to install Python 3.10.13 with Ansible 2.10.6. I'm sure this is a compatibility issue with pip3 version 21.3.1. Can someone help

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
3.9 to 3.10
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL 8

### Steps to Reproduce
```
---
- name: Get ansible executable
  command: "which ansible"
  ignore_errors: yes
  register: ansible_check

- name: Install ansible
  block:
    - name: Packages to install
      set_fact:
        ansible_dep_list_rhel7:
          - python3-pip
          - libselinux-python3
        ansible_dep_list_rhel8:
          - python3-pip
          - python3-libselinux

    - name: install pip3 and libselinux-python3
      shell: "yum install -y {{ item }}"
      with_items: "{{ ansible_dep_list_rhel7 }}"
      when: ansible_facts ['distribution_major_version'] == '7'

    - name: install pip3 and libselinux-python3
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ ansible_dep_list_rhel8 }}"
      when: ansible_facts ['distribution_major_version'] == '8'

    - name: upgrade pip3
      pip:
        name: "pip"      #"pip=={{ ansible_pip3_version }}"
        executable: "{{ pip3_executable }}"
        umask: "0022"
        state: latest     #present
      when: ansible_logstash|bool
      become: yes

    - name: upgrade pip3
      pip:
        name: "pip"   #"pip=={{ pip3_version }}"
        executable: "{{ pip3_executable }}"
        umask: "0022"
        state: latest     #present
      when: not ansible_logstash|bool
      become: yes

    - name: pip install setuptools_rust
      pip:
        name: setuptools_rust
        state: present
        executable: pip3

    - name: install ansible w/ dependencies
      pip:
        name:
          - "ansible=={{ custom_ansible_version }}"
          - "awscli=={{ awscli_version }}"
          - boto3
        state: present
        executable: pip3

```
### Expected Results

To successfully upgrade our ansible from 3.9 to 3.10

### Actual Results

```console
Unable to ssh to packer after the ansible installation with python 3.10. 
Tried reconfiguring the script to use latest pip version to install python upgrade, ansible etc. That didn't work
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
