### ISSUE TITLE
DOCUMENTATION block suboptions in dynamic inventory plugin do not work as expected

### ISSUE THREAD

**Issue by Hapshanko** [ansible/ansible#82832]
### Summary

Im writing the DOCUMENTATION variable for my dynamic inventory plugin.
[documentation ](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-block)
 (same for modules from what I understand) and I encountered a non desired behavior.

```
options:
  parent:
    description: test
    type: dict
    required: true
    suboptions:
      child:
        description: test2
        type: int
        required: true
```

Whenever suboptions is used, `required` and `default` are ignored for suboptions.
In this example, 'parent' will be required, but 'child' (parent.child) will not be required, even though it is the desired behavior, and I stated 'required: true'

### Issue Type

Bug Report

### Component Name

Dynamic Inventory Plugin 

### Ansible Version

```console
$ ansible --version
Not relevant but 2.11.9
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
Not relevant
```

### OS / Environment

RHEL 7

### Steps to Reproduce
Create a Dynamic Inventory Plugin python file, in the DOCUMENTATION block variable set the following: (after name description, short_description)

```yaml (paste below)
options:
  parent:
    description: test
    type: dict
    required: true
    suboptions:
      child:
        description: test2
        type: int
        required: true
```
Now try to parse using this logic.
ansible-inventory -i file.yml --list

### Expected Results

I expected the 'child' suboption to be 'required' but it is not. Only 'parent' is required, same with 'default'.

### Actual Results

```console
'child' suboption is not 'required' even though 'required: true' was set. Same behavior happens with 'default'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
