### ISSUE TITLE
2.16 unsafe conditionals check - Just makes things harder?

### ISSUE THREAD

**Issue by jantari** [ansible/ansible#82833]
### Summary

Trying to upgrade from ansible core 2.15.x to 2.16.4, the new [unsafe conditonals validation](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_9.html#playbook) broke one of our playbooks.

Unfortunately the porting guide only contains an extremely simple example that didn't help me fix *my* task, which I've included in the "Steps to Reproduce" section.

I then found a workaround that makes my task work with 2.16.x again, also included in "Steps to Reproduce", but now this has me questioning whether either:

1. The original task / conditional should not have been considered unsafe
2. The workaround I implemented circumvents the CVE-fix and should still be considered unsafe but isn't

Thank you.

### Issue Type

Bug Report

### Component Name

lib/ansible/utils/unsafe_proxy.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.4]
  config file = /work/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.13 (main, Mar 12 2024, 12:22:40) [GCC 12.2.0] (/usr/local/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
/bin/sh: 1: less: not found
```

### OS / Environment

testing was done in our internal ansible docker containers, built from the `python:3.10-slim` container as a base image.

ansible run from: Debian GNU/Linux 12 (bookworm), Python 3.10.12
Fortinet FortiGate Firewall network device: Model 40F, Firmware 7.0.14

### Original Task, worked until 2.16.x

```yaml
---

- hosts: all
  gather_facts: no
  connection: httpapi
  strategy: linear
  collections:
  - fortinet.fortios
  vars:
    allowed_fortios_firmware_versions:
      - 7.0.12
      - 7.0.14
  tasks:
    - name: Get firwall system status and firmware version
      fortios_configuration_fact:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token | default(omit) }}"
        selector: system_status
      register: _system_status
      check_mode: no

    - name: Assert that firewall firmware version is correct
      ansible.builtin.assert:
        that: >
          [
            {% for firmware_version in allowed_fortios_firmware_versions %}
              {{ firmware_version in _system_status.meta.version }},
            {% endfor %}
          ] is any or 'test' in group_names
        fail_msg: >
          Ensure the firewall is running one of firmware {{ allowed_fortios_firmware_versions }} or,
          if you're testing a new firmware, add the firewall to the 'test' inventory group.
```

It asserts that the firmware version fetched from the network device, which is a string that will contain the firmware version (e.g. 7.0.14) somewhere within it, is one that we allow in production. The full content of `_system_status.meta.version` could be something like `v7.0.14 build0601` which is why I need to to the substring testing.

This task, which previously worked fine, now fails in ansible 9 (2.16.4) with:

```
fatal: [devicename]: FAILED! =>
  msg: |-
    The conditional check '[
          False,
          True,
      ] is any or 'test' in group_names
    ' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated.
```

For the longest time, I struggled with how I should update this for ansible 9, as testing a single string against a list of possible substrings is not easily accomplished with ansibles' on-board string-comparison filters. You can only really test a list of strings against one substring with filters, not the other way.

Anyway, now I found that this works:

### Updated Task, works in 2.16.x

```yaml
---

- hosts: all
  gather_facts: no
  connection: httpapi
  strategy: linear
  collections:
  - fortinet.fortios
  vars:
    allowed_fortios_firmware_versions:
      - 7.0.12
      - 7.0.14
  tasks:
    - name: Get firwall system status and firmware version
      fortios_configuration_fact:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token | default(omit) }}"
        selector: system_status
      register: _system_status
      check_mode: no

    - name: Assert that firewall firmware version is correct
      ansible.builtin.assert:
        that: >
          _firmware_version_tests is any or 'test' in group_names
        fail_msg: >
          Ensure the firewall is running one of firmware {{ allowed_fortios_firmware_versions }} or,
          if you're testing a new firmware, add the firewall to the 'test' inventory group.
      vars:
        _firmware_version_tests: >-
          [
            {% for firmware_version in allowed_fortios_firmware_versions %}
              {{ firmware_version in _system_status.meta.version }},
            {% endfor %}
          ]
```

The workaround would be fine with me, I can just add a comment explaining why the seemingly unnecessary extra variable declaration has to happen, but then what is the security benefit here? We are still evaluating the exact same variables and conditional, it's just been split in two now. Is this a bug? Should the original conditional not have been considered unsafe? Or should my workaround not work, and also be considered unsafe? It feels like it has to be one of these two.

My apologies if I'm misunderstanding the new unsafe conditional behavior, there was not a lot of context in the porting guide.

### Expected Results

I think either the original task should not be considered unsafe or the updated task should still be considered unsafe.

### Actual Results

```console
The original task is considered unsafe but the updated task, which just adds an intermediary variable declaration but handles the exact same data and conditional logic, is considered safe.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/utils/unsafe_proxy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/unsafe_proxy.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
The basic problem that causes this failure is your approach to writing the condition, which unnecessarily embeds additional templating layers inside of something that's already a template. This means that in order to evaluate it a single template has to be run through the templating engine twice, which is unsafe (though historically allowed by Ansible.)

Splitting that embedded template into a separate variable as you did is a safe approach (the condition only needs to be templated once, and the variable only needs to be templated once), but the best way to fix the issue is to write it as a Jinja expression without any nesting.

```yaml
    - name: Assert that firewall firmware version is correct
      ansible.builtin.assert:
        that: (allowed_fortios_firmware_versions | select('in', _system_status.meta.version)) is any
        fail_msg: >
          Ensure the firewall is running one of firmware {{ allowed_fortios_firmware_versions }} or,
          if you're testing a new firmware, add the firewall to the 'test' inventory group.
      when: "'test' not in group_names"
```
