### ISSUE TITLE
Omitting the trailing slash in the dest argument of fetch may print misleading message about checksum mismatch

### ISSUE THREAD

**Issue by stenno** [ansible/ansible#82878]
### Summary

Omitting the trailing slash for the `dest` argument of the `fetch` module may result in an error message complaining about mismatching checksum instead of failing because the directory already exists.
This seems to be a regression from https://github.com/ansible/ansible/issues/27312 .

### Issue Type

Bug Report

### Component Name

ansible.builtin.fetch

### Ansible Version

```console
ansible [core 2.16.4]
  config file = None
  configured module search path = ['/home/texxeo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/texxeo/.local/pipx/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/texxeo/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/texxeo/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/home/texxeo/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = None
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/texxeo/.vault_password_file
```

### OS / Environment

Ubuntu 22.04 on host and remote

### Steps to Reproduce

The following will fail with a `checksum mismatch` error:
```yaml (paste below)
- name: Sync parameters from remote host
  fetch:
    src: "{{ host_folder }}/app/config/parameters.yml"
    dest: "{{ deployment_dir }}/app/config"
    flat: true
```

### Expected Results

I expect the command to fail with a message `destination is a directory`.

### Actual Results

```console
fatal: [remote_hostname]: FAILED! => {"changed": false, "checksum": null, "dest": "/home/texxeo/Deployment/xxx/app/config", "file": "/var/www/html/texxeo-xxx/app/config/parameters.yml", "md5sum": null, "msg": "checksum mismatch", "remote_checksum": "ec0055ac93b7b919b3a489dfd8faee9237070cb5", "remote_md5sum": null}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/fetch.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/fetch.py)
* [`lib/ansible/modules/fetch.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/fetch.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by stenno** [comment]
For now, i will mitigate the issue by simply disabling checksum checks with `validate_checksum: false`

**Comment by stenno** [comment]
I was made aware that my `dest` call misses a trailing `/`. When adding this one, the file gets the correct checksum. The scope of this bug has therefore changed, and it seems that a misleading error message about checksums was created, instead of the actual expected error: `dest is an existing directory`. Should i create a new issue for this?

**Comment by nitzmahone** [comment]
You can just re-title/edit this one if you want...

**Comment by jborean93** [comment]
I am unable to replicate

```yaml
- hosts: localhost
  gather_facts: false

  tasks:
  - copy:
      content: data
      dest: /tmp/source.txt

  - file:
      path: /tmp/target
      state: '{{ item }}'
    loop:
    - absent
    - directory

  - fetch:
      src: /tmp/source.txt
      dest: /tmp/target
      flat: true
```

This fails (as expected) with

```yaml
fatal: [localhost]: FAILED! =>
    changed: false
    msg: dest is an existing directory, use a trailing slash if you want to fetch src
        into that directory
```

I've tried a few permutations like

+ Setting dest to an existing file
+ Setting dest to a non-existing path
+ Setting dest to an existing and non-existing folder with `/`

All of these work as expected and doesn't fail with the error about a checksum. Can you share more about your example so we can potentially try and replicate the error?

**Comment by allixx** [comment]
This is a possible reproducer (I'm just not too sure it is the same scenario described by stenno):

```
test.yml
---
- hosts: host
  gather_facts: false

  tasks:
    - fetch:
        src: /var/tmp/test_file
        dest: /tmp/outdir/
        flat: true
```

TEST 1: All good

```
% ls -l  /tmp/outdir
total 0

% ansible-playbook test.yml
PLAY [host] ************************************************************************************************************************************************************************************************************************************

TASK [fetch] ***********************************************************************************************************************************************************************************************************************************
changed: [host]

PLAY RECAP *************************************************************************************************************************************************************************************************************************************
host                       : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

% ls -l /tmp/outdir
total 60
-rw-r--r-- 1 user user 57984 Mar 22 11:09 test_file
```

TEST 2: Checksum mismatch error, file is still transferred to unexpected location

```
% rm /tmp/outdir/test_file
% mkdir /tmp/outdir/test_file
% ls -l /tmp/outdir
total 0
drwxr-xr-x 2 user user 40 Mar 22 11:10 test_file

% ansible-playbook test.yml
PLAY [host] ************************************************************************************************************************************************************************************************************************************

TASK [fetch] ***********************************************************************************************************************************************************************************************************************************
fatal: [host]: FAILED! => {"changed": false, "checksum": null, "dest": "/tmp/outdir/test_file", "file": "/var/tmp/test_file", "md5sum": null, "msg": "checksum mismatch", "remote_checksum": "c5a9c32c90a910eb717b287d15917fa8e292d81d", "remote_md5sum": null}

PLAY RECAP *************************************************************************************************************************************************************************************************************************************
host                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

% tree /tmp/outdir/
/tmp/outdir/
└── test_file
    └── test_file

2 directories, 1 file
```

**Comment by jborean93** [comment]
Thanks for sharing, I still cannot replicate based on your information. I've tried it where a folder exists in `'{{ dest }}/{{ src_filename }}` like in your example but `fetch` just seems to remove the directory and place the file there. I can get it to fail if `src` is pointed towards a directory as expected but not the checksum mismatch. Can you create a example where `hosts: localhost` and the source and target setup is created inside the playbook itself.

**Comment by allixx** [comment]
```
- hosts: localhost
  gather_facts: false
  tasks:
    - file:
        path: /tmp/test
        state: absent
    - file:
        path: /tmp/test/file
        state: directory

- hosts: host
  gather_facts: false
  tasks:
    - copy:
        content: test file
        dest: /tmp/file
    - fetch:
        flat: true
        src: /tmp/file
        dest: /tmp/test/
```

Does not reproduce when `host` is localhost (connection: local), proper expected message is generated:
```
TASK [fetch] *************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "failed to transfer file to /tmp/test/file: [Errno 21] Is a directory: b'/tmp/test/file'"}
```

However, when `host` is available via ssh connection, this is what we get:
```
TASK [fetch] *************************************************************************************************
fatal: [host]: FAILED! => {"changed": false, "checksum": null, "dest": "/tmp/test/file", "file": "/tmp/file", "md5sum": null, "msg": "checksum mismatch", "remote_checksum": "8f93542443e98f41fe98e97d6d2a147193b1b005", "remote_md5sum": null}
```
