### ISSUE TITLE
Race condition in ec2_eip module

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#8290]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.7 (devel 57f89b85eb) last updated 2014/07/25 10:51:27 (GMT -400)
##### Environment:

OSX
##### Summary:

When provisioning ec2_eips and assigned them to instances, a race condition occurs in which the module believes that the eip is ready, but attempts to assign it to the instance fail
##### Steps To Reproduce:

```
- hosts: localhost
  tasks:
  - name: create vpc
    action:
      module: ec2_vpc
      state: present
      cidr_block: 172.22.0.0/16
      resource_tags: { "Name":"fix2387" }
      subnets:
        - cidr: 172.22.1.0/24
          resource_tags: { "Name":"fix2387" }
      internet_gateway: True
      route_tables:
        - subnets:
            - 172.22.1.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw
      region: us-east-1
      wait: yes
    register: vpc

  - name: create admin access
    action:
      module: ec2_group
      name: admin_access
      description: SSH access for admins and tower
      region: us-east-1
      vpc_id: "{{ vpc.vpc_id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
    tags: security_groups
    register: admin_access

  - name: launch instances
    action:
      module: ec2
      assign_public_ip: no
      region: us-east-1
      key_name: jmartin
      group_id:
      - "{{ admin_access.group_id }}"
      instance_type: m1.small
      vpc_subnet_id: "{{ vpc.subnets[0].id }}"
      image: ami-8997afe0
      wait: yes
      wait_timeout: 500
      exact_count: 5
      count_tag:
         env: fix2387
      instance_tags:
         env: fix2387
    register: ec2

  - name: associate EIPs with instances
    ec2_eip: instance_id={{ item.id }} region=us-east-1 in_vpc=yes
    with_items: ec2.tagged_instances
```
##### Expected Results:

EIPs are provisioned and assigned to hosts.
##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If showing example output, indent your output by four spaces so it will render correctly in GitHub.

TASK: [associate EIPs with instances] *****************************************
<localhost> REMOTE_MODULE ec2_eip instance_id=i-5ac38076 region=us-east-1 in_vpc=yes
changed: [localhost] => (item={u'ramdisk': None, u'kernel': u'aki-88aa75e1', u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-22-1-209.ec2.internal', u'key_name': u'jmartin', u'public_ip': None, u'image_id': u'ami-8997afe0', u'private_ip': u'172.22.1.209', u'public_dns_name': u'', u'state_code': 16, u'id': u'i-5ac38076', u'placement': u'us-east-1b', u'ami_launch_index': u'3', u'dns_name': u'', u'region': u'us-east-1', u'ebs_optimized': False, u'launch_time': u'2014-07-23T18:52:25.000Z', u'instance_type': u'm1.small', u'state': u'running', u'root_device_name': u'/dev/sda1', u'hypervisor': u'xen', u'virtualization_type': u'paravirtual', u'architecture': u'x86_64'}) => {"changed": true, "item": {"ami_launch_index": "3", "architecture": "x86_64", "dns_name": "", "ebs_optimized": false, "hypervisor": "xen", "id": "i-5ac38076", "image_id": "ami-8997afe0", "instance_type": "m1.small", "kernel": "aki-88aa75e1", "key_name": "jmartin", "launch_time": "2014-07-23T18:52:25.000Z", "placement": "us-east-1b", "private_dns_name": "ip-172-22-1-209.ec2.internal", "private_ip": "172.22.1.209", "public_dns_name": "", "public_ip": null, "ramdisk": null, "region": "us-east-1", "root_device_name": "/dev/sda1", "root_device_type": "ebs", "state": "running", "state_code": 16, "virtualization_type": "paravirtual"}, "public_ip": "54.210.74.1"}
<localhost> REMOTE_MODULE ec2_eip instance_id=i-5bc38077 region=us-east-1 in_vpc=yes
failed: [localhost] => (item={u'ramdisk': None, u'kernel': u'aki-88aa75e1', u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-22-1-208.ec2.internal', u'key_name': u'jmartin', u'public_ip': None, u'image_id': u'ami-8997afe0', u'private_ip': u'172.22.1.208', u'public_dns_name': u'', u'state_code': 16, u'id': u'i-5bc38077', u'placement': u'us-east-1b', u'ami_launch_index': u'4', u'dns_name': u'', u'region': u'us-east-1', u'ebs_optimized': False, u'launch_time': u'2014-07-23T18:52:25.000Z', u'instance_type': u'm1.small', u'state': u'running', u'root_device_name': u'/dev/sda1', u'hypervisor': u'xen', u'virtualization_type': u'paravirtual', u'architecture': u'x86_64'}) => {"failed": true, "item": {"ami_launch_index": "4", "architecture": "x86_64", "dns_name": "", "ebs_optimized": false, "hypervisor": "xen", "id": "i-5bc38077", "image_id": "ami-8997afe0", "instance_type": "m1.small", "kernel": "aki-88aa75e1", "key_name": "jmartin", "launch_time": "2014-07-23T18:52:25.000Z", "placement": "us-east-1b", "private_dns_name": "ip-172-22-1-208.ec2.internal", "private_ip": "172.22.1.208", "public_dns_name": "", "public_ip": null, "ramdisk": null, "region": "us-east-1", "root_device_name": "/dev/sda1", "root_device_type": "ebs", "state": "running", "state_code": 16, "virtualization_type": "paravirtual"}}
msg: Address '54.210.103.44' not found.
<localhost> REMOTE_MODULE ec2_eip instance_id=i-54c38078 region=us-east-1 in_vpc=yes
failed: [localhost] => (item={u'ramdisk': None, u'kernel': u'aki-88aa75e1', u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-22-1-206.ec2.internal', u'key_name': u'jmartin', u'public_ip': None, u'image_id': u'ami-8997afe0', u'private_ip': u'172.22.1.206', u'public_dns_name': u'', u'state_code': 16, u'id': u'i-54c38078', u'placement': u'us-east-1b', u'ami_launch_index': u'1', u'dns_name': u'', u'region': u'us-east-1', u'ebs_optimized': False, u'launch_time': u'2014-07-23T18:52:25.000Z', u'instance_type': u'm1.small', u'state': u'running', u'root_device_name': u'/dev/sda1', u'hypervisor': u'xen', u'virtualization_type': u'paravirtual', u'architecture': u'x86_64'}) => {"failed": true, "item": {"ami_launch_index": "1", "architecture": "x86_64", "dns_name": "", "ebs_optimized": false, "hypervisor": "xen", "id": "i-54c38078", "image_id": "ami-8997afe0", "instance_type": "m1.small", "kernel": "aki-88aa75e1", "key_name": "jmartin", "launch_time": "2014-07-23T18:52:25.000Z", "placement": "us-east-1b", "private_dns_name": "ip-172-22-1-206.ec2.internal", "private_ip": "172.22.1.206", "public_dns_name": "", "public_ip": null, "ramdisk": null, "region": "us-east-1", "root_device_name": "/dev/sda1", "root_device_type": "ebs", "state": "running", "state_code": 16, "virtualization_type": "paravirtual"}}
msg: Address '54.210.123.205' not found.
<localhost> REMOTE_MODULE ec2_eip instance_id=i-55c38079 region=us-east-1 in_vpc=yes
failed: [localhost] => (item={u'ramdisk': None, u'kernel': u'aki-88aa75e1', u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-22-1-207.ec2.internal', u'key_name': u'jmartin', u'public_ip': None, u'image_id': u'ami-8997afe0', u'private_ip': u'172.22.1.207', u'public_dns_name': u'', u'state_code': 16, u'id': u'i-55c38079', u'placement': u'us-east-1b', u'ami_launch_index': u'2', u'dns_name': u'', u'region': u'us-east-1', u'ebs_optimized': False, u'launch_time': u'2014-07-23T18:52:25.000Z', u'instance_type': u'm1.small', u'state': u'running', u'root_device_name': u'/dev/sda1', u'hypervisor': u'xen', u'virtualization_type': u'paravirtual', u'architecture': u'x86_64'}) => {"failed": true, "item": {"ami_launch_index": "2", "architecture": "x86_64", "dns_name": "", "ebs_optimized": false, "hypervisor": "xen", "id": "i-55c38079", "image_id": "ami-8997afe0", "instance_type": "m1.small", "kernel": "aki-88aa75e1", "key_name": "jmartin", "launch_time": "2014-07-23T18:52:25.000Z", "placement": "us-east-1b", "private_dns_name": "ip-172-22-1-207.ec2.internal", "private_ip": "172.22.1.207", "public_dns_name": "", "public_ip": null, "ramdisk": null, "region": "us-east-1", "root_device_name": "/dev/sda1", "root_device_type": "ebs", "state": "running", "state_code": 16, "virtualization_type": "paravirtual"}}
msg: Address '54.210.118.116' not found.
<localhost> REMOTE_MODULE ec2_eip instance_id=i-57c3807b region=us-east-1 in_vpc=yes
failed: [localhost] => (item={u'ramdisk': None, u'kernel': u'aki-88aa75e1', u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-22-1-205.ec2.internal', u'key_name': u'jmartin', u'public_ip': None, u'image_id': u'ami-8997afe0', u'private_ip': u'172.22.1.205', u'public_dns_name': u'', u'state_code': 16, u'id': u'i-57c3807b', u'placement': u'us-east-1b', u'ami_launch_index': u'0', u'dns_name': u'', u'region': u'us-east-1', u'ebs_optimized': False, u'launch_time': u'2014-07-23T18:52:25.000Z', u'instance_type': u'm1.small', u'state': u'running', u'root_device_name': u'/dev/sda1', u'hypervisor': u'xen', u'virtualization_type': u'paravirtual', u'architecture': u'x86_64'}) => {"failed": true, "item": {"ami_launch_index": "0", "architecture": "x86_64", "dns_name": "", "ebs_optimized": false, "hypervisor": "xen", "id": "i-57c3807b", "image_id": "ami-8997afe0", "instance_type": "m1.small", "kernel": "aki-88aa75e1", "key_name": "jmartin", "launch_time": "2014-07-23T18:52:25.000Z", "placement": "us-east-1b", "private_dns_name": "ip-172-22-1-205.ec2.internal", "private_ip": "172.22.1.205", "public_dns_name": "", "public_ip": null, "ramdisk": null, "region": "us-east-1", "root_device_name": "/dev/sda1", "root_device_type": "ebs", "state": "running", "state_code": 16, "virtualization_type": "paravirtual"}}
msg: Address '54.210.130.249' not found.
