### ISSUE TITLE
Add support for subid options in user_module

### ISSUE THREAD

**Issue by m00nwtchr** [ansible/ansible#82924]
### Summary

I'm setting up rootless podman using a system user, which by default doesn't receive entries in `/etc/subuid` and `/etc/subgid`.
It looks like there is now an option in `useradd` to create these entries for system users, though:
```
       -F, --add-subids-for-system
           Update /etc/subuid and /etc/subgid even when creating a system account with -r option.
```
Support for the `usermod` options which add subids would be appreciated as well, though.

### Issue Type

Feature Idea

### Component Name

user

### Additional Information

```yaml (paste below)
- name: Create podman user
  ansible.builtin.user:
    name: podman
    group: podman
    password: "!"
    system: true
    home: "/var/lib/podman"
    create_home: true
    add_subids: true # New option
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
