### ISSUE TITLE
systemd_service: Support for the "machine" parameter

### ISSUE THREAD

**Issue by jimmy-lt** [ansible/ansible#82958]
### Summary

When trying to run systemd as another user, the following is advised: 

```yaml
- name: Run a user service when XDG_RUNTIME_DIR is not set on remote login
  ansible.builtin.systemd_service:
    name: myservice
    state: started
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ myuid }}"
```

However, this may not always work and can fail in various ways, typically:

```
Failed to connect to bus: Operation not permitted
```

Since [systemd 248](https://lists.freedesktop.org/archives/systemd-devel/2021-March/046289.html), the `--machine` option is available to to open a connection to the session bus of a specific user.

### Issue Type

Feature Idea

### Component Name

systemd_service

### Additional Information

```yaml
- name: Run from within a specific user session
  ansible.builtin.systemd_service:
    name: myservice
    state: started
    scope: user
    machine: myuser@.host
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/systemd_service.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/systemd_service.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by konstruktoid** [comment]
Out of curiosity,  wouldn't it be advised to use `become_user` as well, in order not to trigger the permission issue?

**Comment by jimmy-lt** [comment]
`become_user` does overcome the permission denied issue. The `--machine` option however provides better integration with systemd and simplifies the task definition (no `become` or `environment` required).

**Comment by tisba** [comment]
wow, just what I was looking for, thank you @jimmy-lt 🙇 

Any change that somebody could look at [the PR](https://github.com/ansible/ansible/pull/82959) (@nitzmahone, @konstruktoid)? That would be super awesome! 💕

**Comment by konstruktoid** [comment]
I got no issues with it, but I'm not in a position to accept/merge

**Comment by PascalKont** [comment]
Still open in 2026.
I need this feature to properly configure rootless containers running as their own user in a headless system.

**Comment by lethedata** [comment]
> `become_user` does overcome the permission denied issue. The `--machine` option however provides better integration with systemd and simplifies the task definition (no `become` or `environment` required).

Full example of what "simplifies" under a new `ansible.builtin.systemd_service` flag 

```yaml
    - name: Fetch target user details from passwd database
      ansible.builtin.getent:
        database: passwd
        key: rootless

    - name: Start and enable user systemd service
      ansible.builtin.systemd_service:
        name: podman.socket # Replace with your actual service name
        state: started
        enabled: true
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['getent_passwd']['rootless'][1] }}"
        DBUS_SESSION_BUS_ADDRESS: "{{ ansible_facts['getent_passwd']['rootless'][1] }}"
      become: true
      become_user: rootless
```
