### ISSUE TITLE
group_by doesn't work when associated with --tag on the command-line

### ISSUE THREAD

**Issue by p-wieser** [ansible/ansible#82966]
### Summary

I dynamically define groups in a playbook with the group_by module.
When I run this playbook with `--tag` option in the command-line, I get warnings : "[WARNING]: Could not match supplied host pattern, ignoring: <my_group_here>".
All works fine when I remove the `--tag` option.

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.9]
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/ansible/library']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /home/ansible/.ansible.cfg
DEFAULT_GATHERING(/home/ansible/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/ansible/.ansible.cfg) = ['/home/ansible/ansible/bin/inventory.pl']
DEFAULT_MODULE_PATH(/home/ansible/.ansible.cfg) = ['/home/ansible/ansible/library']
DEFAULT_ROLES_PATH(/home/ansible/.ansible.cfg) = ['/home/ansible/ansible/roles']
RETRY_FILES_ENABLED(/home/ansible/.ansible.cfg) = False
VARIABLE_PLUGINS_ENABLED(/home/ansible/.ansible.cfg) = ['ansible.builtin.host_group_vars'
```

### OS / Environment

Rocky Linux 9
$ uname -a
Linux admin9.trychlos.lan 5.14.0-362.24.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 13 17:33:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

```yaml (paste below)
# play #1: gather hosts facts and group them by system/architecture
- name: "Dynamically build hosts groups"
  hosts: all
  tasks:
  - ansible.builtin.group_by:
      key: "system_{{ ansible_system }}"
  - ansible.builtin.group_by:
      key: "arch_{{ ansible_architecture }}"

# play #2:
#- name: "the list fo groups of each host"
#  hosts: all
#  tasks:
#  - ansible.builtin.debug:
#      var: group_names

# play #2: display the full list of groups, and the list of hosts for each group
# not very usefull as this full list is displayed for each host of the play
#- name: "the full list of groups, and the list of hosts in each group"
#  hosts: all
#  tasks:
#  - ansible.builtin.debug:
#      var: groups

# play #3 
- name: "Standard setup for Raspi2 machines"
  hosts: system_Linux:&arch_armv7l
  tasks:
  - ansible.builtin.debug:
      # the list of hosts in this play
      var: play_hosts
  roles:
  - { role: uni-ziplogs,      tags: [req-uni-024, uni-ziplogs] }

# play #4 
- name: "Standard setup for Raspi4 machines"
  hosts: system_Linux:&arch_aarch64
  vars_files:
  - "{{ sisSiteDir }}/site_vars.yml"
  tasks:
  - ansible.builtin.debug:
      var: play_hosts
  roles:
  - { role: uni-ziplogs,      tags: [req-uni-024, uni-ziplogs] }

# play #5 
- name: "Standard setup for x86 servers"
  hosts: system_Linux:&physical:&arch_x86_64
  tasks:
  - ansible.builtin.debug:
      var: play_hosts
  roles:
  - { role: uni-ziplogs,      tags: [req-uni-024, uni-ziplogs] }

```

### Expected Results

$ ansible-playbook playbooks/tt.yml --limit ns92,piwall,mnemos 

PLAY [Dynamically build hosts groups] **********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************************************************************
ok: [mnemos]
ok: [piwall]
ok: [ns92]

TASK [ansible.builtin.group_by] ****************************************************************************************************************************************************************************************************************************************
changed: [mnemos]
changed: [piwall]
changed: [ns92]

TASK [ansible.builtin.group_by] ****************************************************************************************************************************************************************************************************************************************
changed: [mnemos]
changed: [piwall]
changed: [ns92]
[WARNING]: Could not match supplied host pattern, ignoring: arch_armv7l

PLAY [Standard setup for Raspi2 machines] ******************************************************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY [Standard setup for Raspi4 machines] ******************************************************************************************************************************************************************************************************************************

TASK [uni-ziplogs : (req-uni-024|main) populate ziplogs_config with role-level default values] *************************************************************************************************************************************************************************
ok: [piwall]

TASK [uni-ziplogs : (req-uni-024|main) include role-level distribution-specific vars] **********************************************************************************************************************************************************************************
ok: [piwall] => (item=/home/ansible/ansible/roles/uni-ziplogs/vars/Debian.yml)

TASK [uni-ziplogs : (req-uni-024|main) merge role-level distribution-specific vars into ziplogs_config] ****************************************************************************************************************************************************************
ok: [piwall]

TASK [uni-ziplogs : (req-uni-024|main) include site-level distribution-specific vars] **********************************************************************************************************************************************************************************
skipping: [piwall]

TASK [uni-ziplogs : (req-uni-024|main) merge site-level distribution-specific vars into ziplogs_config] ****************************************************************************************************************************************************************
ok: [piwall]

TASK [uni-ziplogs : ansible.builtin.debug] *****************************************************************************************************************************************************************************************************************************
ok: [piwall] => {
    "msg": "ziplogs_config: {'compress': {}}"
}

TASK [uni-ziplogs : ansible.builtin.include_tasks] *********************************************************************************************************************************************************************************************************************
included: /home/ansible/ansible/roles/uni-ziplogs/tasks/linux_setup.yml for piwall

TASK [uni-ziplogs : (req-uni-024|linux_setup) only run on targeted systems] ********************************************************************************************************************************************************************************************
skipping: [piwall]

TASK [uni-ziplogs : ansible.builtin.fail] ******************************************************************************************************************************************************************************************************************************
skipping: [piwall]

TASK [ansible.builtin.debug] *******************************************************************************************************************************************************************************************************************************************
ok: [piwall] => {
    "play_hosts": [
        "piwall"
    ]
}

PLAY [Standard setup for x86 servers] **********************************************************************************************************************************************************************************************************************************

TASK [uni-ziplogs : (req-uni-024|main) populate ziplogs_config with role-level default values] *************************************************************************************************************************************************************************
ok: [mnemos]

TASK [uni-ziplogs : (req-uni-024|main) include role-level distribution-specific vars] **********************************************************************************************************************************************************************************
ok: [mnemos] => (item=/home/ansible/ansible/roles/uni-ziplogs/vars/Rocky-9.yml)

TASK [uni-ziplogs : (req-uni-024|main) merge role-level distribution-specific vars into ziplogs_config] ****************************************************************************************************************************************************************
ok: [mnemos]

TASK [uni-ziplogs : (req-uni-024|main) include site-level distribution-specific vars] **********************************************************************************************************************************************************************************
skipping: [mnemos]

TASK [uni-ziplogs : (req-uni-024|main) merge site-level distribution-specific vars into ziplogs_config] ****************************************************************************************************************************************************************
ok: [mnemos]

TASK [uni-ziplogs : ansible.builtin.debug] *****************************************************************************************************************************************************************************************************************************
ok: [mnemos] => {
    "msg": "ziplogs_config: {'compress': {}}"
}

TASK [uni-ziplogs : ansible.builtin.include_tasks] *********************************************************************************************************************************************************************************************************************
included: /home/ansible/ansible/roles/uni-ziplogs/tasks/linux_setup.yml for mnemos

TASK [uni-ziplogs : (req-uni-024|linux_setup) only run on targeted systems] ********************************************************************************************************************************************************************************************
skipping: [mnemos]

TASK [uni-ziplogs : ansible.builtin.fail] ******************************************************************************************************************************************************************************************************************************
skipping: [mnemos]

TASK [ansible.builtin.debug] *******************************************************************************************************************************************************************************************************************************************
ok: [mnemos] => {
    "play_hosts": [
        "mnemos"
    ]
}

PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************
mnemos                     : ok=10   changed=2    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
ns92                       : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
piwall                     : ok=10   changed=2    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   

### Actual Results

```console
$ ansible-playbook playbooks/tt.yml --limit ns92,piwall,mnemos --tag uni-ziplogs

PLAY [Dynamically build hosts groups] **********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************************************************************
ok: [ns92]
ok: [mnemos]
ok: [piwall]
[WARNING]: Could not match supplied host pattern, ignoring: system_Linux
[WARNING]: Could not match supplied host pattern, ignoring: arch_armv7l

PLAY [Standard setup for Raspi2 machines] ******************************************************************************************************************************************************************************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: arch_aarch64

PLAY [Standard setup for Raspi4 machines] ******************************************************************************************************************************************************************************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: arch_x86_64

PLAY [Standard setup for x86 servers] **********************************************************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************
mnemos                     : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
ns92                       : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
piwall                     : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@p-wieser `ansible-core` 2.14 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by p-wieser** [comment]
Hello,
Regarding my ansible version, I was not conscious of the end of the 2.14 support. This is unfortunately the most recent available in Rocky Linux 9 :(
@flowerysong, I may be wrong, but I believed that the lines
```
roles:
  - { role: uni-ziplogs,      tags: [req-uni-024, uni-ziplogs] }
```
were enough to say that each play has one role which exhibits the requested tag. Or did I have missed something ?

**Comment by flowerysong** [comment]
Your first play, the one with the `group_by` tasks that are not running, has no tags.

```yaml
# play #1: gather hosts facts and group them by system/architecture
- name: "Dynamically build hosts groups"
  hosts: all
  tasks:
  - ansible.builtin.group_by:
      key: "system_{{ ansible_system }}"
  - ansible.builtin.group_by:
      key: "arch_{{ ansible_architecture }}"
```

**Comment by p-wieser** [comment]
Oh. Yes, I understand: when I ask for tags in the command-line, this play doesn't run because it doesn't hold any tag, so groups are not built.
Is there a sort of magic key which would say "do not apply tags here" or some sort of wildcard tag ?
In my playbook, tags are thought to be able to apply each role individually, with some sort of aliasing capabilities. Group_by would have let me spare the groups declarations at the inventory level, by taking advantage of the dynamic facts of ansible...
Would you have any suggestion on the way I could go ?

**Comment by bcoca** [comment]
see previous answer, add an `always` tag:

```
# play #1: gather hosts facts and group them by system/architecture
- name: "Dynamically build hosts groups"
  hosts: all
  tags:
    - always
  tasks:
  - ansible.builtin.group_by:
      key: "system_{{ ansible_system }}"
  - ansible.builtin.group_by:
      key: "arch_{{ ansible_architecture }}"

```
