### ISSUE TITLE
Allow uri module to send HTTPs traffic through HTTPS proxy

### ISSUE THREAD

**Issue by Valgueiro** [ansible/ansible#82962]
### Summary

I was trying to use a https proxy that we have internally in a `ansible.builtin.uri` block but It is not working because it is trying to use the proxy as a HTTP one, not HTTPS. 

The proxy is setup using the environment variables as so:

```bash
$ env | grep -i proxy
no_proxy=localhost,127.0.0.0/8
https_proxy=https://user:pass@proxy.url:443
NO_PROXY=localhost,127.0.0.0/8
HTTPS_PROXY=https:///user:pass@proxy.url:443
```

And curl works as expected:

```env
$ curl https://httpbin.org/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.68.0",
    "X-Amzn-Trace-Id": "Root=1-660c6698-35a659b808eea16050827085"
  },
  "origin": "52.250.73.122",
  "url": "https://httpbin.org/get"
}
```
But when using the ` ansible.builtin.uri`, the proxy is not able to continue with the request because it is receiving a HTTP message, not HTTPS. When taking a look online, I found that [urllib requires a specific variable to be set in order to work with HTTPS traffic in a HTTPS proxy](https://urllib3.readthedocs.io/en/stable/advanced-usage.html#http-and-https-proxies):

```
For HTTPS proxies we also support forwarding your requests to HTTPS destinations with an [absolute URI](https://datatracker.ietf.org/doc/html/rfc9112#name-absolute-form) if the use_forwarding_for_https argument is set to True. We strongly recommend you only use this option with trusted or corporate proxies as the proxy will have full visibility of your requests.
```

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.6]
...
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
does not apply...
```

### OS / Environment

Linux (ubuntu 20.04) - Azure distribution

### Steps to Reproduce

```yaml (paste below)
- name: HTTPS in HTTPS proxy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Try to get into httpbin
      ansible.builtin.uri:
        url: https://httpbin.org/get
      environment:
        no_proxy: localhost,127.0.0.0/8
        https_proxy: https://user:pass@proxy.url:443
        NO_PROXY: localhost,127.0.0.0/8
        HTTPS_PROXY: https://user:pass@proxy.url:443
```

### Expected Results

It should be able to send HTTPS traffic through a HTTPS Proxy

### Actual Results

```console
TASK [Try to get into httpbin] *******************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  elapsed: 0
  msg: 'Status code was -1 and not [200]: Request failed: <urlopen error Tunnel connection failed: 400 Bad Request>'
  redirected: false
  status: -1
  url: https://httpbin.org/get
```
On the logs/wireshark of the Proxy, I can see that it is receiving a HTTP request, not HTTPS

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
