### ISSUE TITLE
Feature Req: Display date/time stamp during playbooks run using verbose?

### ISSUE THREAD

**Issue by rgaufman** [ansible/ansible#83005]
### Summary

I think a useful feature, especially when running longer playbooks, would be to show the time stamp at the beginning of each new task, possibly only when running in verbose mode.

### Issue Type

Feature Idea

### Component Name

ansible-playbook

### Additional Information

e.g.
```
2024-03-19 09:29:30 GATHERING FACTS ********************* 
ok: [10.51.10.76]

2024-03-19 09:29:33 TASK: [install all needed packages] ********************* 
ok: [10.51.10.76] => {"changed": false}

2024-03-19 09:29:52 TASK: [Stop Apache] ********************* 
changed: [10.51.10.76] => {"changed": true, "name": "apache2", "state": "stopped"}
or something similar. Maybe only use if running in verbose AND a flag is called similar to --timed. This would help determine if something has hung on the remote side.
```

Thoughts?

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`bin/ansible`](https://github.com/ansible/ansible/blob/devel/bin/ansible)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by rgaufman** [comment]
That's fair, but after close to a decade using Ansible to manage over a thousand servers, this was just 1 too many callbacks on top of other hacks, workarounds and frustrations.

We ended up creating our own solution which gave us these advantages:
- 11x fewer lines (35k lines of yml recipes down to 3k of clean/concise Ruby DSL)
- 35x faster to run (from 20 minutes with Ansible to around 34 seconds with Ruby)
- readable log output, easier profiling, many other advantages

Here is an example of the output, showing only the changes being made, with clear timestamps and durations. In contrast to having countless pages of difficult to parse Ansible output before:

![Screenshot 2024-04-22 at 01 24 33](https://github.com/ansible/ansible/assets/33842342/7ce23fad-24a9-4497-8b7e-27c774c4b5f8)

The recipes are much more concise, for example:

```ruby
# note, the secret_key_base is generated in the erb template
template(secrets_path, 'secrets.sample.yml', mode: '644', user: 'deployer:deployer', overwrite: false)
```

Instead of:

```
- name: Check if secrets yml already exists
  ansible.builtin.stat:
    path: "{{ deploy_to }}/config/secrets.yml"
  register: tetherbox_secrets_yml

- name: Generate Rails secret_key_base
  ansible.builtin.command:
    cmd: "openssl rand -hex 64"
  register: secret_key_base
  changed_when: false
  when: tetherbox_secrets_yml.stat.exists is false

- name: Create secrets yml
  ansible.builtin.template:
    src: 'secrets.yml.j2'
    dest: "{{ deploy_to }}/config/secrets.yml"
    mode: '0644'
    owner: '{{ username }}'
    group: '{{ username }}'
  when: tetherbox_secrets_yml.stat.exists is false
```

We will do a bit more testing and refining and will release this as open source as an alternative to those that want something a bit more opinionated and out of the box, without needing to do callbacks/hacks for basics like standard log output.
