### ISSUE TITLE
ansible hang when execute the sshfs mount command

### ISSUE THREAD

**Issue by chaoshuaihaohao** [ansible/ansible#83010]
### Summary

ansible hang when execute the sshfs mount command,and not return ok.

### Issue Type

Bug Report

### Component Name

dnf

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.14]
  config file = /home/hao/nfs/virtio-hands-on/ansible.cfg
  configured module search path = ['/home/hao/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/hao/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Jan 24 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /home/hao/nfs/virtio-hands-on/ansible.cfg
DEFAULT_BECOME_ASK_PASS(/home/hao/nfs/virtio-hands-on/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/hao/nfs/virtio-hands-on/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/hao/nfs/virtio-hands-on/ansible.cfg) = root
DEFAULT_HOST_LIST(/home/hao/nfs/virtio-hands-on/ansible.cfg) = ['/home/hao/nfs/virtio-hands-on/inventory']
HOST_KEY_CHECKING(/home/hao/nfs/virtio-hands-on/ansible.cfg) = False

BECOME:
======

runas:
_____
become_user(/home/hao/nfs/virtio-hands-on/ansible.cfg) = root

su:
__
become_user(/home/hao/nfs/virtio-hands-on/ansible.cfg) = root

sudo:
____
become_user(/home/hao/nfs/virtio-hands-on/ansible.cfg) = root

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/hao/nfs/virtio-hands-on/ansible.cfg) = False

ssh:
___
host_key_checking(/home/hao/nfs/virtio-hands-on/ansible.cfg) = False
```

### OS / Environment

centos-stream 9

### Steps to Reproduce

```yaml (paste below)
---
- name: Mount remote directory via SSHFS
  hosts: kvm_host
  vars:
    remote_user: hao
    remote_host: 10.2.27.225
    remote_path: /home/hao/nfs
    ssh_key_path: /home/hao/.ssh/id_rsa
  become: yes
  tasks:
    - name: Install sshfs (if not already installed)
      yum:
        name: sshfs
        state: present
        update_cache: yes
      when: ansible_os_family == 'Centos'

    - name: Create local mount point if it does not exist
      file:
        path: /mnt/nfs
        state: directory
        mode: '0755'

    - name: Mount remote directory using sshfs
      shell: sudo sshfs {{ remote_user }}@{{ remote_host }}:{{ remote_path }} /mnt/nfs -o rw,allow_other,IdentityFile={{ ssh_key_path }}
      become: yes

```

### Expected Results

the dir /home/hao/nfs is mounted at /mnt/nfs，and the ansible return ok.

### Actual Results

```console
host1) ansible -i inventory 192.168.2.190 -m command -a "sshfs hao@10.2.27.225:/home/hao/nfs /home/chenhao/mount-test " -u chenhao -vvv
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Sep 10 2021, 09:13:53) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /root/ansible/inventory as it did not pass its verify_file() method
script declined parsing /root/ansible/inventory as it did not pass its verify_file() method
auto declined parsing /root/ansible/inventory as it did not pass its verify_file() method
Parsed /root/ansible/inventory inventory source with ini plugin
META: ran handlers
<192.168.2.190> ESTABLISH SSH CONNECTION FOR USER: chenhao
<192.168.2.190> SSH: EXEC sshpass -d9 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="chenhao"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/2534e46258 192.168.2.190 '/bin/sh -c '"'"'echo ~chenhao && sleep 0'"'"''
<192.168.2.190> (0, b'/home/chenhao\n', b'')
<192.168.2.190> ESTABLISH SSH CONNECTION FOR USER: chenhao
<192.168.2.190> SSH: EXEC sshpass -d9 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="chenhao"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/2534e46258 192.168.2.190 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/chenhao/.ansible/tmp/ansible-tmp-1712730639.3515742-220442692124249 `" && echo ansible-tmp-1712730639.3515742-220442692124249="` echo /home/chenhao/.ansible/tmp/ansible-tmp-1712730639.3515742-220442692124249 `" ) && sleep 0'"'"''
<192.168.2.190> (0, b'ansible-tmp-1712730639.3515742-220442692124249=/home/chenhao/.ansible/tmp/ansible-tmp-1712730639.3515742-220442692124249\n', b'')
Using module file /usr/lib/python3.6/site-packages/ansible/modules/commands/command.py
<192.168.2.190> PUT /root/.ansible/tmp/ansible-local-273259kefazu3d/tmpm3u_vtf6 TO /home/chenhao/.ansible/tmp/ansible-tmp-1712730639.3515742-220442692124249/AnsiballZ_command.py
<192.168.2.190> SSH: EXEC sshpass -d9 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="chenhao"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/2534e46258 '[192.168.2.190]'
<192.168.2.190> (0, b'sftp> put /root/.ansible/tmp/ansible-local-273259kefazu3d/tmpm3u_vtf6 /home/chenhao/.ansible/tmp/ansible-tmp-1712730639.3515742-220442692124249/AnsiballZ_command.py\n', b'')
<192.168.2.190> ESTABLISH SSH CONNECTION FOR USER: chenhao
<192.168.2.190> SSH: EXEC sshpass -d9 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="chenhao"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/2534e46258 192.168.2.190 '/bin/sh -c '"'"'chmod u+x /home/chenhao/.ansible/tmp/ansible-tmp-1712730639.3515742-220442692124249/ /home/chenhao/.ansible/tmp/ansible-tmp-1712730639.3515742-220442692124249/AnsiballZ_command.py && sleep 0'"'"''
<192.168.2.190> (0, b'', b'')
<192.168.2.190> ESTABLISH SSH CONNECTION FOR USER: chenhao
<192.168.2.190> SSH: EXEC sshpass -d9 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="chenhao"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/2534e46258 -tt 192.168.2.190 '/bin/sh -c '"'"'/usr/bin/python3 /home/chenhao/.ansible/tmp/ansible-tmp-1712730639.3515742-220442692124249/AnsiballZ_command.py && sleep 0'"'"''


//hang ...




host 192.168.2.190) hao@10.2.27.225:/home/hao/nfs on /home/chenhao/mount-test type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=1001,group_id=1001)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
