### ISSUE TITLE
Is this provided example in csvfile_lookup plugin correct?

### ISSUE THREAD

**Issue by robpou** [ansible/ansible#83031]
### Summary

There is a very high chance that I'm wrong, but as for now, the provided example in https://github.com/ansible/ansible/blob/stable-2.17/lib/ansible/plugins/lookup/csvfile.py#L54-L65 doesn't make sense to me.

It states that the lookup

```yaml
    csvline: "{{ lookup('ansible.builtin.csvfile', bgp_neighbor_ip, file='bgp_neighbors.csv', delimiter=',') }}"
```

returns the whole line as an array, which then can be used as csvline[0], csvline[1] etc.

```
 name: Define Values From CSV File, this reads file in one go, but you could also use col= to read each in it's own lookup.
  ansible.builtin.set_fact:
    loop_ip: "{{ csvline[0] }}"
    int_ip: "{{ csvline[1] }}"
   [...]
```

But the csv lookup plugin doesn't work like this? The same documentation also states

> The lookup looks for the row where the first column matches keyname (which can be multiple words) and returns the value in the [col] column (default 1, which indexed from 0 means the second column in the file).

### Issue Type

Documentation Report

### Component Name

ansible.builtin.csvfile lookup

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.5]
  config file = /home/username/.ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /home/username/.ansible.cfg
DEFAULT_VAULT_IDENTITY(/home/username/.ansible.cfg) = prod
DEFAULT_VAULT_IDENTITY_LIST(/home/username/.ansible.cfg) = ['prod@~/.ansible/.vault-prod', 'dev@~/.ansible/.vault-dev']
PAGER(env: PAGER) = less
```

### OS / Environment

Ubuntu 22.04 LTS

### Additional Information

input.csv file:

```
backup3,Y,290,300,300,254,191
backup4,Y,294,300,300,253,189
```

Play:

```
    - name: Test csv
      ansible.builtin.debug:
        msg: "{{ csvline }}"
      delegate_to: localhost
      vars:
        csvline: "{{ lookup('ansible.builtin.csvfile', 'backup4', file='input.csv', delimiter=',') }}"
      tags:
        - test
```

Result:

```
ASK [netbox_power : Test csv] ***************************************************
ok: [backup4 -> localhost] => {
    "msg": "Y"
}
```

That's not the whole line, that's the first column after the match, just as the documentation states.

`csvline` isn't an array...? Or am I missing something?

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
