### ISSUE TITLE
deb822: Puts Keys in wrong directory

### ISSUE THREAD

**Issue by KevinHonka** [ansible/ansible#83074]
### Summary

We noticed that the deb822 module puts the keys it downloads into the `/etc/apt/keyrings` folder. The [official documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/deb822_repository_module.html#parameter-signed_by) says that they should be stored in `trusted.gpg.d` folder.  

This is a show-stopper in adopting the deb822 module, as keys stored in `/etc/apt/keyrings` will not be loaded on the current Debian 12 cloud image.

### Issue Type

Bug Report

### Component Name

deb822_repository

### Ansible Version

```console
ansible [core 2.16.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kevin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kevin/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/kevin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/kevin/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 30
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = debian
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False
remote_user(/etc/ansible/ansible.cfg) = debian
ssh_args(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s

ssh:
___
control_path_dir(/etc/ansible/ansible.cfg) = /tmp/.ansible/cp
host_key_checking(/etc/ansible/ansible.cfg) = False
remote_user(/etc/ansible/ansible.cfg) = debian
ssh_args(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
```

### OS / Environment

Debian 12

### Steps to Reproduce

```yaml (paste below)
- name: Install | Add gitlab apt repository
  ansible.builtin.deb822_repository:
    name: gitlab
    components:
      - main
    suites: '{{ ansible_distribution_release }}'
    signed_by: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    types: deb
    uris: 'https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution | lower }}/'
```

### Expected Results

The imported key is placed in `/etc/apt/trusted.gpg.d`

### Actual Results

```console
The imported key is placed in `/etc/apt/keyrings`.

This happens because the folder is hard coded in the [deb822 module](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/deb822_repository.py#L256).
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
