### ISSUE TITLE
Add docker_compose_v2 to plugin_routing

### ISSUE THREAD

**Issue by ihard** [ansible/ansible#83086]
### Summary

Ability to use a short module name in task descriptions 
please add

```
    docker_compose_v2:
      redirect: community.docker.docker_compose_v2
```
to https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml

### Issue Type

Feature Idea

### Component Name

docker_compose_v2

### Additional Information

```yaml (paste below)

- name: start service
  docker_compose_v2:
    project_src: '{{ service_conf_dir }}'

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
