### ISSUE TITLE
Need ansible.builtin.dpkg_selections to hold package even if not already installed

### ISSUE THREAD

**Issue by rclilly** [ansible/ansible#83087]
### Summary

When I try to use **ansible.builtin.dpkg_selections** to put a hold on **python2.7-minimal** (or any **python2.7** package) in Ubuntu 22.04.4 it fails. This appears to be related to [dpkg_selections: Check if package exists before selection operation](https://github.com/ansible/ansible/pull/81406). I would expect **dpkg_selections** to be able to put holds on _**any**_ package in the repos regardless of whether it is installed or not, similar to how **`apt-mark hold`** works manually. My goal is to prevent the installation of **python2.7**.

### Issue Type

Bug Report

### Component Name

dpkg_selections

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.5]
  config file = /srv/home/rlilly/repos/ansible/ansible.cfg
  configured module search path = ['/home/rlillyx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/rlillyx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /srv/home/rlilly/repos/ansible/ansible.cfg
DEFAULT_FORKS(/srv/home/rlilly/repos/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/srv/home/rlilly/repos/ansible/ansible.cfg) = ['/srv/home/rlilly/repos/ansible/inventory.yml']
DEFAULT_JINJA2_EXTENSIONS(/srv/home/rlilly/repos/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_PRIVATE_KEY_FILE(/srv/home/rlilly/repos/ansible/ansible.cfg) = /home/szollin/.ssh/internal.key
HOST_KEY_CHECKING(/srv/home/rlilly/repos/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/srv/home/rlilly/repos/ansible/ansible.cfg) = auto
INVENTORY_CACHE_ENABLED(/srv/home/rlilly/repos/ansible/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/srv/home/rlilly/repos/ansible/ansible.cfg) = jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(/srv/home/rlilly/repos/ansible/ansible.cfg) = /tmp/ansible_inventory
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/srv/home/rlilly/repos/ansible/ansible.cfg) = False

CONNECTION:
==========
:...skipping...
CONFIG_FILE() = /srv/home/rlilly/repos/ansible/ansible.cfg
DEFAULT_FORKS(/srv/home/rlilly/repos/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/srv/home/rlilly/repos/ansible/ansible.cfg) = ['/srv/home/rlilly/repos/ansible/inventory.yml']
DEFAULT_JINJA2_EXTENSIONS(/srv/home/rlilly/repos/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_PRIVATE_KEY_FILE(/srv/home/rlilly/repos/ansible/ansible.cfg) = /home/szollin/.ssh/internal.key
HOST_KEY_CHECKING(/srv/home/rlilly/repos/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/srv/home/rlilly/repos/ansible/ansible.cfg) = auto
INVENTORY_CACHE_ENABLED(/srv/home/rlilly/repos/ansible/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/srv/home/rlilly/repos/ansible/ansible.cfg) = jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(/srv/home/rlilly/repos/ansible/ansible.cfg) = /tmp/ansible_inventory
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/srv/home/rlilly/repos/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/srv/home/rlilly/repos/ansible/ansible.cfg) = False
private_key_file(/srv/home/rlilly/repos/ansible/ansible.cfg) = /home/szollin/.ssh/internal.key

ssh:
___
host_key_checking(/srv/home/rlilly/repos/ansible/ansible.cfg) = False
pipelining(/srv/home/rlilly/repos/ansible/ansible.cfg) = True
private_key_file(/srv/home/rlilly/repos/ansible/ansible.cfg) = /home/szollin/.ssh/internal.key
scp_if_ssh(/srv/home/rlilly/repos/ansible/ansible.cfg) = true
```

### OS / Environment

Both the control machine and the target are Ubuntu 22.04.4

### Steps to Reproduce

Vars:
```
base_pkg_setup_apt_pkg_hold:
  - "python2.7-minimal"

```
Play:
```
    - name: Hold selected package(s) Ubuntu 22 and above
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items: "{{ base_pkg_setup_apt_pkg_hold }}"
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] >= "22"
        - "item not in held_packages.stdout_lines"
```

### Expected Results

I expect the package **python2.7-minimal** to be held even if it's not installed, similar to how **`apt-mark hold python2.7-minimal`** works.

### Actual Results

```console
TASK [base_pkg_setup : Hold selected package(s) Ubuntu 22 and above] **************************************************************************
failed: [upgrade-test-ws.ostc.intel.com] (item=python2.7-minimal) => {"ansible_loop_var": "item", "changed": false, "item": "python2.7-minimal", "msg": "Failed to find package 'python2.7-minimal' to perform selection 'hold'."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/dpkg_selections.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dpkg_selections.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by rclilly** [comment]
@bcoca Thank you for your quick reply! I haven't tried using **`dpkg --set-selections`**, only **`apt-mark hold`** which works. If this module uses **`dpkg`**, and it can't do this task, then is there a way to accomplish this with the **`apt`** module?

**Comment by bcoca** [comment]
I might have been a bit premature since my debian based distros are pretty updated and there is no Python2 available, so its 'non existant', but i kept testing other cases, of which i've found 4:

  - package exists, is in dpkg cache and selections are available, action works fine, matches dpkg 
  - package does not exist anywhere, action works fine, matches dpkg
  - package exists in repository, but dpkg cache was not updated, so action reacts as if it didnt exist, i think this is still correct and matches dpkg
  - package exists in repo and dpkg cache, but was never in selections, in this case action incorrectly treats as non existant but dpkg itself does work.

I'll push a fix for this last case.

**Comment by sivel** [comment]
This would also be fairly trivial to implement with just running `apt-mark`:

```yaml
- name: Get list of packages on hold
  command: apt-mark showhold
  register: apt_mark_hold

- name: Set hold for python2.7-minimal
  command: apt-mark hold python2.7-minimal
  when: '"python2.7-minimal" not in apt_mark_hold.stdout'
```

**Comment by bcoca** [comment]
i've been testing this and sadly i get different results on different versions of Debian and Debian derivatives. Some allow any package name to be held w/o error, so it won't catch misspellings, other versions ONLY allow packages they recognize so they need to be in the local cache.  I'm not sure we should bypass this behavior as it opens up many doors to user error and complexity in tracking the different underlying responses from the tool.

**Comment by btravouillon** [comment]
This seems like a regression though. I just hit the same issue after upgrading to ansible-core 2.16.7.

On a freshly imaged node where the packages are not installed yet: 

```
TASK [mila.monitoring.netdata : Install netdata_repo] *************************
vendredi 14 juin 2024  19:12:35 -0400 (0:00:00.025)       0:00:07.534 ********* 
The following NEW packages will be installed:
  debian-archive-keyring
0 upgraded, 1 newly installed, 0 to remove and 57 not upgraded.

Selecting previously unselected package netdata-repo.
(Reading database ... 119325 files and directories currently installed.)
Preparing to unpack .../downloap61lx9ir.deb ...
changed: [headlab]

TASK [mila.monitoring.netdata : Update repository cache] **********************
vendredi 14 juin 2024  19:12:39 -0400 (0:00:04.266)       0:00:11.800 ********* 
changed: [headlab]

TASK [mila.monitoring.netdata : Ensure Netdata packages are unlocked] *********
vendredi 14 juin 2024  19:12:41 -0400 (0:00:01.686)       0:00:13.487 ********* 
failed: [headlab] (item=netdata) => changed=false 
  ansible_loop_var: item
  item: netdata
  msg: Failed to find package 'netdata' to perform selection 'install'.
failed: [headlab] (item=netdata-plugin-freeipmi) => changed=false 
  ansible_loop_var: item
  item: netdata-plugin-freeipmi
  msg: Failed to find package 'netdata-plugin-freeipmi' to perform selection 'install'.
```

The tasks:
```
- name: Install netdata_repo
  ansible.builtin.apt:
    deb: "{{ netdata_repo_url }}"
    state: present
    allow_downgrade: true

- name: "Update repository cache"
  ansible.builtin.apt:
    update_cache: yes

# In a previous version of this role, netdata packages were locked after
# install. Make sure these are not locked anymore.
- name: Ensure Netdata packages are unlocked
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - netdata
    - netdata-plugin-freeipmi
```

After a downgrade to 2.15.12 (`pip install -U ansible-core==2.15.12 ansible==8.3.0`), this works:
```
TASK [mila.monitoring.netdata : Install netdata_repo] *************************
vendredi 14 juin 2024  20:04:41 -0400 (0:00:00.034)       0:00:07.965 ********* 
ok: [headlab]

TASK [mila.monitoring.netdata : Update repository cache] **********************
vendredi 14 juin 2024  20:04:44 -0400 (0:00:02.504)       0:00:10.469 ********* 
changed: [headlab]

TASK [mila.monitoring.netdata : Ensure Netdata packages are unlocked] *********
vendredi 14 juin 2024  20:04:47 -0400 (0:00:03.390)       0:00:13.859 ********* 
changed: [headlab] => (item=netdata)
changed: [headlab] => (item=netdata-plugin-freeipmi)

```

**Comment by btravouillon** [comment]
A workaround could be to check if the packages are installed before using `ansible.builtin.dpkg_selections`.

```
# In a previous version of this role, netdata packages were locked after
# install. Make sure these are not locked anymore.
- name: Register packages list first
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure Netdata packages are unlocked
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - netdata
    - netdata-plugin-freeipmi
  when: item in ansible_facts['packages']
```
