### ISSUE TITLE
wait_for_connection not working properly with Juniper QFX

### ISSUE THREAD

**Issue by ziyedbe** [ansible/ansible#83104]
### Summary

When I reboot my Juniper QFX system and use wait_for_connection using the example playbook below, the wait_for_connection is successful before the system is back online.

### Issue Type

Bug Report

### Component Name

wait_for_connection

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.9]
  config file = /data/scripts/Switch_QFX/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /data/scripts/.venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /data/scripts/.venv/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/data/scripts/.venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /data/scripts/Switch_QFX/ansible.cfg
HOST_KEY_CHECKING(/data/scripts/Switch_QFX/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/data/scripts/Switch_QFX/ansible.cfg) = False

ssh:
___
host_key_checking(/data/scripts/Switch_QFX/ansible.cfg) = False
```

### OS / Environment

Target OS versions
`JUNOS 18.4 to JUNOS 21.4`

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  connection: netconf
  gather_facts: False
  vars_files:
  - ../vars/vars.yml
  tasks:
    - name: request system reboot all-members
      junipernetworks.junos.junos_command:
        commands:
          - "request system reboot all-members"
      register: reboot_command_output
    - name: Wait for Remote host to come online
      wait_for_connection:
        delay: 90 
        timeout: 1600

```

### Expected Results

wait_for_connection is sucessful after system is back online.

### Actual Results

```console
wait_for_connection is sucessful before system is back online.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
```[tasklist]
### Tasks
```
