### ISSUE TITLE
handlers are skipped on conditional role include

### ISSUE THREAD

**Issue by MorphBonehunter** [ansible/ansible#83112]
### Summary

In our structure we using an basic role where we define an handler which could be used by other roles.
The basic role doesn't have any tasks, its only there for the handler stuff.
The other roles which want to use the basic role must declare an dependency to the basic role.
This works smooth over the last couple of years.

Today i realized that the handler isn't executed if there is an role which is included in the playbook with an condition.
So i fiddle up a simple example to demonstrate the behavior.

### Issue Type

Bug Report

### Component Name

handlers

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.6]
  config file = None
  configured module search path = ['/home/dwendler/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/dwendler/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/sbin/ansible
  python version = 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801] (/usr/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = /usr/bin/vim
```

### OS / Environment

Arch Linux

### Steps to Reproduce

./debug.yml
```yaml
---
- name: Testcase
  gather_facts: false
  hosts: localhost

  vars:
    r_enable: false

  roles:
    - role: one

    - role: two
      when: r_enable
```

./roles/dep/handlers/main.yml
```yaml
---
- name: Debug output dep
  ansible.builtin.debug:
    msg: "Debug output dep"
```

./roles/one/tasks/main.yml
```yaml
---
- name: Task one
  ansible.builtin.debug:
    msg: "Task one with notify"
  changed_when: true
  notify: "Debug output dep"

- name: Flush
  ansible.builtin.meta: flush_handlers

- name: Task onetwo
  ansible.builtin.debug:
    msg: "Task onetwo with notify"
  changed_when: true
  notify: "Debug output dep"
```

./roles/one/meta/main.yml
```yaml
---
dependencies:
  - role: dep
```

./roles/two/tasks/main.yml
```yaml
---
- name: Task two
  ansible.builtin.debug:
    msg: "Task two with notify"
  notify: "Debug output dep"
```

./roles/two/meta/main.yml
```yaml
---
dependencies:
  - role: dep
```

### Expected Results

The handler should be executed.
This doesn't happen as the conditional use of the role with the `r_enable` to `false` seems to inherit the conditional down to the handler what leeds to the fact that handler is never executed (see example).

Maybee that has somethin to to with #77955 but i don't know.
As this was working in an oder version (we do have an Debian 11 with ansible [core 2.12.10]) this is an regression.

### Actual Results

```console
ansible-playbook debug.yml -vD
No config file found; using defaults
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Testcase] *************************************************************************************************************************************************************************************************

TASK [one : Task one] *******************************************************************************************************************************************************************************************
changed: [localhost] => {
    "msg": "Task one with notify"
}

TASK [one : Flush] **********************************************************************************************************************************************************************************************

RUNNING HANDLER [dep : Debug output dep] ************************************************************************************************************************************************************************
skipping: [localhost] => {"false_condition": "r_enable"}

TASK [one : Task onetwo] ****************************************************************************************************************************************************************************************
changed: [localhost] => {
    "msg": "Task onetwo with notify"
}

TASK [two : Task two] *******************************************************************************************************************************************************************************************
skipping: [localhost] => {"false_condition": "r_enable"}

RUNNING HANDLER [dep : Debug output dep] ************************************************************************************************************************************************************************
skipping: [localhost] => {"false_condition": "r_enable"}

PLAY RECAP ******************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
