### ISSUE TITLE
 String quotes are kept when use during an include

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8315]
##### Issue Type:

 “Bug Report”
##### Ansible Version:

1.7
##### Environment:

Centos 6.5
##### Summary:

Using a parameterized include with a string in single quotes will cause the string to preserve the single quotes.  
##### Steps To Reproduce:

```
- include: assert_user.yml user_name=user1 priv='ALL PRIVILEGES' 
```

```
- name: run command to show privileges for user (expect privileges in stdout)
  command: mysql "-e SHOW GRANTS FOR '{{ user_name }}'@'localhost';"
  register: result
  when: priv is defined

- set_fact: 
      grant_test: "GRANT {{priv}} ON *.*"
  when: priv is defined

- name: assert user has giving privileges 
  assert: { that: "grant_test in result.stdout" }
  when: priv is defined
```
##### Expected Results:

Single quotes should be removed.
##### Actual Results:

```
changed: [testhost] => {"changed": true, "cmd": ["mysql", "-e SHOW GRANTS FOR 'db_user2'@'localhost';"], "delta": "0:00:00.007479", "end": "2014-07-28 16:06:25.097876", "rc": 0, "start": "2014-07-28 16:06:25.090397", "stderr": "", "stdout": "Grants for db_user2@localhost\nGRANT ALL PRIVILEGES ON *.* TO 'db_user2'@'localhost' IDENTIFIED BY PASSWORD '*86F4B678F048D8E35C66C5D514444E11B09042CE'"}

TASK: [test_mysql_user | set_fact ] ******************************************* 
ok: [testhost] => {"ansible_facts": {"grant_test": "GRANT 'ALL PRIVILEGES' ON *.*"}}

TASK: [test_mysql_user | assert user has giving privileges] ******************* 
failed: [testhost] => {"assertion": "grant_test in result.stdout", "evaluated_to": false, "failed": true}
```
