### ISSUE TITLE
handlers not fired when using roles

### ISSUE THREAD

**Issue by Mapel88** [ansible/ansible#83172]
### Summary

I have a role with handlers, but they doesn't seem to fire on change.

The files were changed but there is no indication for handlers being executed and the services were not restarted:

![image](https://github.com/ansible/ansible/assets/12735495/74d14cd6-3e5c-452a-a8b8-0b4c2448a8d9)

![image](https://github.com/ansible/ansible/assets/12735495/96ac87d3-7c3a-494f-ad48-95380e87a92e)

Am i missing something?
Do I need to include the handlers anywhere?
According to the documentation handlers should be included automatically from handlers/main.yaml.. so not sure what's the issue..

### Issue Type

Bug Report

### Component Name

ansible handlers

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Oct 13 2023, 04:53:37) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18.0.6)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Red Hat Enterprise Linux release 8.8 (Ootpa)

### Steps to Reproduce

role/handlers/main.yaml:
```
- name: restart salt-master
  become: true
  service: 
    name: salt-master 
    state: restarted

- name: restart salt-minion
  become: true
  service: 
    name: salt-minion 
    state: restarted
```

role/tasks/main.yaml
```
- name: Setup saltmaster
  include_tasks: saltmaster/salt.yaml
```

role/tasks/saltmaster/salt.yaml
```
- name: Set auto_accept to False in /etc/salt/master
  ansible.builtin.lineinfile:
    path: /etc/salt/master
    search_string: '#auto_accept: False'
    line: 'auto_accept: False'
    owner: root
    group: root
    mode: '0640'
  notify: restart salt-master

- name: Edit the salt configuration on the minion and add the Master
  shell: |
    printf "master: {{ ansible_hostname }}.{{ my_domain }}\n" > /etc/salt/minion.d/99-master-address.conf
    printf "$(hostname)\n" > /etc/salt/minion_id
  notify: restart salt-minion
```

I also tried the following syntax for handlers which also doesn't work:
```
- name: restart saltmaster
  service: name=salt-master state=restarted

- name: restart salt-minion
  service: name=salt-minion state=restarted
```

my playbook:
```
- hosts: some-server
  become: true
  vars_files:
    - "{{ playbook_dir }}/../vars.yaml"
  vars:
    env: "{{ ansible_local['local']['env'] }}"
    
  roles:
     - salt
```

### Expected Results

expected services salt-minion and salt-master to be restarted

### Actual Results

```console
TASK [salt : Set auto_accept to True in /etc/salt/master] *********************************************************************************************************************************************************
changed: [some server]

TASK [salt : Set target_env based on hostname] ********************************************************************************************************************************************************************
ok: [some-server]


TASK [salt : Edit the salt configuration on the minion and add the Master] ****************************************************************************************************************************************
changed: [some-server]

TASK [salt : Pause for 1 minute to make sure minion is registered] ************************************************************************************************************************************************
Pausing for 60 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [some-server]

```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
