### ISSUE TITLE
ansible.builtin.command not passing args to useradd correctly with argv parameter

### ISSUE THREAD

**Issue by lmouelle** [ansible/ansible#83171]
### Summary

Noticed this setting up a playbook.

This snippet generates an error saying the --key arg is unrecognized:

```yaml
- name: Create "{{ username }}" user
  become: true
  become_user: root
  ansible.builtin.command:
    creates: "/home/{{ username }}" # This works as long as we use standard home paths
    argv:
      - useradd
      - --create-home
      - --system
      - --add-subids-for-system
      - --user-group
      - --key UMASK=077
      - "{{ username }}"
```

Output (omitting some noise): "stderr": "useradd: unrecognized option '--key UMASK=077'\n..."

If  I change --key to -K I get this: 

```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["useradd", "--create-home", "--system", "--add-subids-for-system", "--user-group", "-K UMASK=077", "torrents"], "delta": "0:00:00.007341", "end": "2024-04-30 20:43:11.039934", "msg": "non-zero return code", "rc": 3, "start": "2024-04-30 20:43:11.032593", "stderr": "configuration error - unknown item ' UMASK' (notify administrator)", "stderr_lines": ["configuration error - unknown item ' UMASK' (notify administrator)"], "stdout": "", "stdout_lines": []}
```

  
I switched from using argv over to "cmd: "useradd --create-home --system --add-subids-for-system --user-group --key UMASK=077 {{ username }}" and it works fine, though I prefer the argv overload. I guess something is adding extra whitespace somewhere along the line or mangling it. I ran these commands from my shell as a wheel user and was able to create the users with any combination of arguments without errors, so this is scoped to ansible and likely the command module

### Issue Type

Bug Report

### Component Name

command

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/PII/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/PII/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Fedora Server 39

### Steps to Reproduce

```yaml (paste below)
- name: Create "{{ username }}" user
  become: true
  become_user: root
  ansible.builtin.command:
    creates: "/home/{{ username }}" # This works as long as we use standard home paths
    argv:
      - useradd
      - --create-home
      - --system
      - --add-subids-for-system
      - --user-group
      - --key UMASK=077
      - "{{ username }}"
```

### Expected Results

I expected the command to run and not fail to recognize user provided arguments

### Actual Results

```console
useradd: unrecognized option '--key UMASK=077'

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["useradd", "--create-home", "--system", "--add-subids-for-system", "--user-group", "-K UMASK=077", "torrents"], "delta": "0:00:00.007341", "end": "2024-04-30 20:43:11.039934", "msg": "non-zero return code", "rc": 3, "start": "2024-04-30 20:43:11.032593", "stderr": "configuration error - unknown item ' UMASK' (notify administrator)", "stderr_lines": ["configuration error - unknown item ' UMASK' (notify administrator)"], "stdout": "", "stdout_lines": []}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
