### ISSUE TITLE
service_facts returns non-existent services

### ISSUE THREAD

**Issue by myllynen** [ansible/ansible#83190]
### Summary

With systemd the service_facts module returns non-existent services which makes the typical check of `when: "'foo.service' in ansible_facts.services"` unreliable.

This is because the service_facts module returns all service names known to systemd, not just those present on the system. A service can be known to systemd even if it doesn't exist when an existing service mentions it. For example:

```
root@bastion:~# grep -r ntpd.service /etc /usr
/usr/lib/systemd/system/chronyd.service:After=ntpdate.service sntp.service ntpd.service
/usr/lib/systemd/system/chronyd.service:#Conflicts=ntpd.service systemd-timesyncd.service
/usr/lib/systemd/system/chronyd.service:Conflicts=ntpd.service
```

This means that in case `ntpd.service` would be present then it would not be possible to run that service at the same time as `chronyd.service`. This makes systemd aware of `ntpd.service` but it doesn't necessarily exist on the system and there is nothing that could be done with it using Ansible.

It would seem appropriate to filter out non-existent ("not found") services in the service_facts module to avoid returning non-existent services.

### Issue Type

Bug Report

### Component Name

service_facts

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.6]
  config file = None
  configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/testuser/ansible/ansible-2.16/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/testuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/testuser/ansible/ansible-2.16/bin/ansible
  python version = 3.11.7 (main, Jan 22 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/home/testuser/ansible/ansible-2.16/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = None
EDITOR(env: EDITOR) = vi
PAGER(env: PAGER) = less
```

### OS / Environment

Linux / systemd

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  become: true
  tasks:
    - yum:
        name: chrony
        state: present
    - yum:
        name: ntpd
        state: absent
    - service_facts:
    - service:
        state: stopped
        name: ntpd.service
      when: "'ntpd.service' in ansible_facts.services"
```

### Expected Results

Ansible does not try to stop a non-existent service.

### Actual Results

```console
...
TASK [service] **********************
fatal: [bastion.example.com]: FAILED! => {"changed": false, "msg": "Could not find the requested service ntpd.service: host"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/service_facts.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/service_facts.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
The module returns detailed information about all of the services, not just a simple list.

```yaml
    - service:
        state: stopped
        name: ntpd.service
      when: ansible_facts['services']['ntpd.service']['status'] | default('not-found') != 'not-found'
```
