### ISSUE TITLE
'CustomHTTPSConnection' object has no attribute 'cert_file' when using get_url

### ISSUE THREAD

**Issue by vdmkenny** [ansible/ansible#83213]
### Summary

I am trying to provision a ubuntu 24.04LTS host with the system default python 3.12.
I am using a playbook that we used against 22.04LTS hosts in the past.
Only on 24.04LTS, I get a python error.

### Issue Type

Bug Report

### Component Name

get_url

### Ansible Version

```console
$ ansible --version
ansible is already the newest version (5.10.0-1ppa~focal).
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
Not sure how to dump this since it's all in a CI system, but I don't think it matters on the host side.
```

### OS / Environment

target OS: Ubuntu 24.04LTS
We're running this playbook from a slightly older Ubuntu using a github action.

### Steps to Reproduce

```yaml
- name: Download .tar.gz
  get_url:
    url: https://example.com/package-v{{ version }}-linux-amd64-bin.tar.gz
    dest: $HOME/package-v{{ version }}-linux-amd64-bin.tar.gz
    mode: "0644"
    checksum: sha256:https://example.com/package-v{{ version }}-linux-amd64-bin.tar.gz.sha256
  register: downloaded
  when: package_copy_from_local == "false"
  tags: update
```

### Expected Results

I expected to download and extract the tarbal like before on older Ubuntu versions.

### Actual Results

```console
qemu.ubuntu24: TASK [internal/package : Download .tar.gz] **************
    qemu.ubuntu24: fatal: [<sensitive>]: FAILED! => ***"changed": false, "dest": "/home/<sensitive>/package-v1.2.3-linux-amd64-bin.tar.gz", "elapsed": 0, "msg": "An unknown error occurred: 'CustomHTTPSConnection' object has no attribute 'cert_file'", "url": "https://example.com/package-v1.2.3-linux-amd64-bin.tar.gz.sha256"***
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
