### ISSUE TITLE
 run_once task is not executed when first host in the list is being skipped

### ISSUE THREAD

**Issue by RobinR1** [ansible/ansible#83216]
### Summary

I have a playbook running the same role 3 times in a row, every time with a different `when:` clause for the installation of software on a cluster consisting of a master node, other main nodes and slave nodes. The master node needs to be up and running before the other main nodes are installed and finally installs the slave nodes.

Inside this role one of the steps is to download the software to localhost using a `run_once` to prevent that it gets downloaded over and over again for every host (the download is quite big).

However this download step is skipped entirely whenever the first host in the list happens to be one that is skipped by the  `when` clause defined in the play.

I am aware of #19966, and it is there explained that the where cause on the run_once (or pause) task should be defined in a way that it would trigger on any host if it would trigger on one of the hosts in list. But in my case the when clause is defined far above that level, in the playbook itself and not in the role. No matter what I do in the role, the hosts that are skipped won't execute any task in the role, so I see no possible solution on how to trigger this run_once task on the first host in the list, skipped by the when clause in the playbook.

I feel, like many in #19966 this is a bug in `run_once` (despite it being documented now), and should be fixed somehow or an alternative `run_once_on_any` or something like that should be available.

### Issue Type

Bug Report

### Component Name

run_once

### Ansible Version

```console
$ ansible --version
2.15.0
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

SLES 15 SP5 
Ansible running in AWX on Kubernetes

### Steps to Reproduce

inventory:
```
all:
   children:
      cluster:
         vars:
             master: host2
         children:
             host1:
                 mode: server
             host2:
                 mode: server
             host3:
                 mode: server
             host4:
                 mode: agent
             host5:
                 mode: agent
```

playbook:

```
- hosts: cluster
  roles:
    - role: software
      when:
         - master is defined
         - master == inventory_hostname
     - role: software
       when:
          - master is defined
          - master != inventory_hostname
          - mode == "server"
      - role: software
        when: (master is defined and mode == "agent") or master is not defined
```

role:

```
- name: Fetching binary from {{ download_url }}
  ansible.builtin.get_url:
    url: '{{ download_url }}'
    checksum: sha256:{{ checksum_url }}
    dest: '{{ download_target }}'
    mode: "0644"
    force: true
  changed_when: false
  run_once: true
  delegate_to: localhost
```

### Expected Results

Software is downloaded on localhost whenever at least one host is not skipped

### Actual Results

```console
When first host is skipped, software is not downloaded. Any subsequent task trying to install the software will fail as there is no download.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
