### ISSUE TITLE
Issues cross-compiling Mac targets with Rust through Ansible

### ISSUE THREAD

**Issue by jackfarzan** [ansible/ansible#83210]
### Summary

When I try to cross-compile Rust with an x86_64 iOS target on either an x86_64 or arm64 Mac, I get a cross-compilation or linking error when run through Ansible. I'm not able to reproduce this error at all when running the commands manually on the target machines. I've verified that Ansible has access to the same Openssl, Xcode-tools, Path, etc as when run manually. There are no additional Rust or other flags set on the machines that I am aware of. 

What could be causing this? 

As a note, I don't think the issue is with the command component itself. I'm not sure where exactly the issue is, I'm trying to narrow it down between Rust and Ansible. My investigations so far have pointed me to Ansible. 

### Issue Type

Bug Report

### Component Name

cmd

### Ansible Version

```console
$ ansible --version                                                                                                                                                           
ansible [core 2.16.5]
  config file = None
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/jenkins/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all                                                                                                                                   
WARNING: terminal is not fully functional
Press RETURN to continue 
CONFIG_FILE() = None
```

### OS / Environment

Ansible itself is being initiated in an Ubuntu 22 container. It then connects to Mac x86_64 and ARM runners. The ultimate goal is to build iOS arm64 and x86_64 on the Mac arm64 machine, but as an interim step I am attempting to run in on x86_64 but still encountering issues. 

### Steps to Reproduce

```yaml (paste below)
command being run:
    - name: Run make release
      ansible.builtin.command:
      args:
        cmd: |
          make build-release-x86_64-ios
          
build-release-x86_64-ios:
	rustup target add x86_64-apple-ios
	IPHONEOS_DEPLOYMENT_TARGET=15.0 cargo build \
		--target=x86_64-apple-ios \
		--release \
		--no-default-features
```

### Expected Results

I expect my x86_64-ios artifact to cross-compile successfully on an arm64 or x86_64 Mac machine.

### Actual Results

```console
The artifact does not cross compile due to either an OpenSSL cross-compilation or a linking error.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
