### ISSUE TITLE
Implement Attribute Specific No Log Parameter

### ISSUE THREAD

**Issue by Poseidon6473** [ansible/ansible#83238]
### Summary

When writing playbooks and roles, it would be very helpful for the process of debugging to allow for functionality that either stands alongside the typical "no_log: true" or changes it in some way to _only_ remove logging for specific attributes of a task.

For example, I add a host to the current play, but I want to see all other information printed to the logs/stdout _except_ the password, with current no_log functionality, this is not possible -- it's either all or nothing.

I was looking through the Ansible Core code to see if this was something that I could just put a PR up for myself, but the no_log functionality is quite intertwined with a lot of other stuff -- and is out of my purview for myself (I don't know Python lol); so this may be a feature that is too much work for too little reward, but I think it's a very good nice-to have (I just can't implement it myself)

### Issue Type

Feature Idea

### Component Name

ansible-core core

### Additional Information

```yaml (paste below)
- name: Add Host to Play
  add_host:
    name: "{{ target.host.ip }}"
    groups: target-platform
    ansible_connection: ssh
    ansible_user: "{{ target.host.user }}"
    ansible_password: "{{ passwd }}"
  no_log_attr: true, ansible_password

# Select, 'True' to enable no logging of specific attribute. Referance ansible_password as the argument to specify the attribute to not be logged.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
