### ISSUE TITLE
group_names var ordered by name instead of level 

### ISSUE THREAD

**Issue by CroutonDigital** [ansible/ansible#83248]
### Summary

I have inventory like: 

```
testnet:
  vars:
    var_file: "group_vars/testnets/{{ group_names[-1] }}.yml"
  children: 
    side:
      hosts:
        side_test: { ansible_user: side, ansible_host: 65.109.93.124, type: testrelay, prepare: true }
    warden:
      hosts:
        warden_test: { ansible_user: warden, ansible_host: 65.109.93.124, type: testrelay, prepare: true }
    hedgeblock:
      hosts:
        hedgeblock_test: { ansible_user: hedgeblock, ansible_host: 65.109.93.124, type: testrelay, prepare: true }
```
When I var {{ group_names[1] }} I got: 

Issue discus but not fixed: https://github.com/ansible/ansible/issues/12730 

### Issue Type

Bug Report

### Component Name

etc

### Ansible Version

```console
$ ansible --version
2.16.11
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING(/Users/maxi/Documents/GIT/ECNG/CROUTON-DIGITAL/ansible-cosmos/ansible.cfg) = True
CONFIG_FILE() = /Users/maxi/Documents/GIT/ECNG/CROUTON-DIGITAL/ansible-cosmos/ansible.cfg
DEFAULT_FORKS(/Users/maxi/Documents/GIT/ECNG/CROUTON-DIGITAL/ansible-cosmos/ansible.cfg) = 20
DEFAULT_HASH_BEHAVIOUR(/Users/maxi/Documents/GIT/ECNG/CROUTON-DIGITAL/ansible-cosmos/ansible.cfg) = merge
DEFAULT_HOST_LIST(/Users/maxi/Documents/GIT/ECNG/CROUTON-DIGITAL/ansible-cosmos/ansible.cfg) = ['/Users/maxi/Documents/GIT/ECNG/CROUTON-DIGITAL/ansible-cosmos/inventory.yml']
HOST_KEY_CHECKING(/Users/maxi/Documents/GIT/ECNG/CROUTON-DIGITAL/ansible-cosmos/ansible.cfg) = False

CONNECTION:
==========

local:
_____
pipelining(/Users/maxi/Documents/GIT/ECNG/CROUTON-DIGITAL/ansible-cosmos/ansible.cfg) = True
```

### OS / Environment

OS X

### Steps to Reproduce

```yaml (paste below)
---
- name: Print
  ansible.builtin.debug:
    msg:
      - "KEY which is: {{ group_names[1] }}"
```

### Expected Results

TASK [support_sync_snapshot : Print] *******************************************************************************************************************************************
ok: [side_test] => {
    "msg": [
        "KEY which is: side"
    ]
}
ok: [warden_test] => {
    "msg": [
        "KEY which is: warden"
    ]
}
ok: [hedgeblock_test] => {
    "msg": [
        "KEY which is: hedgeblock"
    ]
}

### Actual Results

```console
TASK [support_sync_snapshot : Print] *******************************************************************************************************************************************
ok: [side_test] => {
    "msg": [
        "KEY which is: testnet"
    ]
}
ok: [warden_test] => {
    "msg": [
        "KEY which is: warden"
    ]
}
ok: [hedgeblock_test] => {
    "msg": [
        "KEY which is: testnet"
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
