### ISSUE TITLE
Single string not cast to list of strings in role argument_spec validation

### ISSUE THREAD

**Issue by egdoc** [ansible/ansible#83268]
### Summary

During module parameters validation, if a value must be a list and a single string is provided, the value is turned into a list with that string as the only element, due to this code:

https://github.com/ansible/ansible/blob/667526c22ff59bbe7bc790bf505b7f09cae3856f/lib/ansible/module_utils/common/validation.py#L390-L410

Although the validation passes, the function doesn't seem to be applied when validating a role.

### Issue Type

Bug Report

### Component Name

Role Argument Spec Validation

### Ansible Version

```console
ansible [core 2.16.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/doc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/doc/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = /usr/bin/vim
```

### OS / Environment

Fedora 40

### Steps to Reproduce

`meta/argument_specs.py`

```yaml (paste below)
---
argument_specs:
  main:
    short_description: test_role description.
    options:
      test_option:
        type: list
        elements: str
        required: true
```

`tasks/main.yml`

```yaml (paste below)
---
- name: Print var
  ansible.builtin.debug:
    msg: '{{ test_option }}'
```

`test_playbook.yml`

```yaml (paste below)
---
- name: Test
  hosts: localhost
  roles:
    - role: test_role
      test_option: singlestring
```

Playbook run:

`ansible-playbook test_playbook.yml`

```shell
PLAY [Test] **************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************
ok: [localhost]

TASK [test_role : Validating arguments against arg spec 'main' - test_role description.] *******************************************************************
ok: [localhost]
```

### Expected Results

```shell
TASK [test_role: Print var] ******************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [ 
              "singlestring",
    ]
}
```

### Actual Results

```console
TASK [test_role: Print var] ******************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "singlestring"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
