### ISSUE TITLE
Allow usage of extra vars in `ansible.builtin.generator` inventory plugin, enabling the dynamic generation of inventory host names at runtime.

### ISSUE THREAD

**Issue by Roysav** [ansible/ansible#83270]
### Summary

# Use Cases
##  VM Creation
- *Scenario:* Using Ansible to both create VMs and configure them. Consistency in hostname generation is critical to ensure seamless transitions between creation and configuration phases.
- *Solution:* By enabling the `ansible.builtin.generator` plugin to use extra vars, it will be possible to dynamically generate consistent hostnames based on variables provided at runtime. This ensures consistency across already existing virtual machines (that may be sourced from dynamic inventory plugin) and newly created virtual machines. This consistency is important for the use of `group_vars` and `host_vars` in the configuration phase.

### Issue Type

Feature Idea

### Component Name

plugins/inventory/generator.py

### Additional Information

In `inventory.yaml` file:
```yaml
plugin: ansible.builtin.generator
hosts:
    # The `region` variable is provided at runtime
    name: "{{ region }}{{ machine_type }}"
layers:
    machine_type:
        - web
        - db
```
Running:
```sh
ansible-inventory -i inventory.yaml -e region=region10 --list
```
Should output:
```
@all:
  |--@ungrouped:
  |  |--region10web
  |  |--region10db
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
