### ISSUE TITLE
fetch checksum with auth

### ISSUE THREAD

**Issue by yukha-dw** [ansible/ansible#83286]
### Summary

I am unable to use `checksum` parameter on `ansible.builtin.get_url` because it's located on protected artifactory.

### Issue Type

~Feature  Idea~
Bug

### Component Name

get_url

### Additional Information

I'd be great if ansible also use `url_username` & `url_password` to fetch the checksum (or new parameters would be great too). Running `get_url` twice is ok, but `checksum` only accepts url or string, I have to run `command` to extract the sha

```YAML
- name: download package from protected artifactory
  ansible.builtin.get_url:
    url: "https://protected-artifactory/package/package.deb"
    checksum: "sha256:https://protected-artifactory/package/package.deb.sha256"
    dest: /package.deb
    url_username: "{{ artifactory_id }}"
    url_password: "{{ artifactory_api_key }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
