### ISSUE TITLE
win_iis_webapppool

### ISSUE THREAD

**Issue by kossioni** [ansible/ansible#83304]
### Summary

cannot add multiple env vars only 1 accepted using:

```
- name: Create IIS Application Pool
  community.windows.win_iis_webapppool:
    name: MouzakisAnsibleAppPool
    state: present
    attributes:
      managedPipelineMode: Classic
      queueLength: 2000
      processModel.identityType: SpecificUser
      processModel.userName: '{{ ansible_user }}'
      processModel.password: '{{ ansible_password }}'
      processModel.loadUserProfile: true
      processModel.maxProcesses: 20
      environmentVariables:
        - name: foo
          value: bar
```
      
From the above I see the env var added but I cannot specify a list of them no matter what I try...

for example:

TRY#1
```
- name: Create IIS Application Pool
  community.windows.win_iis_webapppool:
    name: MouzakisAnsibleAppPool
    state: present
    attributes:
      managedPipelineMode: Classic
      queueLength: 2000
      processModel.identityType: SpecificUser
      processModel.userName: '{{ ansible_user }}'
      processModel.password: '{{ ansible_password }}'
      processModel.loadUserProfile: true
      processModel.maxProcesses: 20
      environmentVariables:
        - name: foo
          value: bar
        - name: foo2
           value: bar2
```

The above doesn't work....

If I try to add multiple environmentVariables attributes only the last gets applied for example:

TRY #2
```
- name: Create IIS Application Pool
  community.windows.win_iis_webapppool:
    name: MouzakisAnsibleAppPool
    state: present
    attributes:
      managedPipelineMode: Classic
      queueLength: 2000
      processModel.identityType: SpecificUser
      processModel.userName: '{{ ansible_user }}'
      processModel.password: '{{ ansible_password }}'
      processModel.loadUserProfile: true
      processModel.maxProcesses: 20
      environmentVariables:
        - name: foo
          value: bar
      environmentVariables:
        - name: last1
          value: only_applies
```

How can I add multiple env vars?

### Issue Type

Bug Report

### Component Name

win_iis_webapppool

### Ansible Version

```console
$ ansible --version

core 2.16.5
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
...
```

### OS / Environment

RHEL 8.x

### Steps to Reproduce

```yaml (paste below)

```
see above

### Expected Results

I expect multi env vars to appear in applicationHost.config

### Actual Results

```console
only 1 env var gets applied
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
