### ISSUE TITLE
The _vault_ filter does not encrypt file content from _lookup_

### ISSUE THREAD

**Issue by teodorkostov** [ansible/ansible#83309]
### Summary

I would expect the _vault_ filter to encrypt a value. However, when the value is the contents of a file (_lookup_) nothing is encrypted. The operation succeeds and produces the plain text as result. Also, keep in mind, the original file is still encrypted at the destination.

My workflow is this:
1. Copy an encrypted file to a new location. The file gets decrypted automatically. (OK)
2. Modify the decrypted file with an external process. (OK)
3. Encrypt the file and place the new encrypted file at the old location. (NOK)

### Issue Type

Bug Report

### Component Name

ansible.builtin

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.0]
  config file = /projects/operations/ansible.cfg
  configured module search path = ['/projects/operations/library']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417] (/usr/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/projects/operations/ansible.cfg) = True
CONFIG_FILE() = /projects/operations/ansible.cfg
DEFAULT_HOST_LIST(/projects/operations/ansible.cfg) = ['/projects/operations/inventory']
DEFAULT_MANAGED_STR(/projects/operations/ansible.cfg) = Ansible managed: Do NOT edit this file manually!
DEFAULT_MODULE_PATH(/projects/operations/ansible.cfg) = ['/projects/operations/library']
DEFAULT_ROLES_PATH(/projects/operations/ansible.cfg) = ['/projects/operations/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = ./pass
EDITOR(env: EDITOR) = helix
INTERPRETER_PYTHON(/projects/operations/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/projects/operations/ansible.cfg) = False
```

### OS / Environment

Arch Linux

### Steps to Reproduce

```yaml (paste below)
 - name: Decrypt
      ansible.builtin.copy:
        src: "./location/{{ item }}"
        dest: /dev/shm/
      loop:
        - fileA
        - fileB
      check_mode: false

    - name: Work
      ...

    - name: Encrypt
      ansible.builtin.copy:
        content: "{{ lookup('ansible.builtin.file', '/dev/shm/' + item) | vault(lookup('ansible.builtin.file', './pass')) }}"
        dest: "./location/{{ item }}"
      loop:
        - fileA
        - fileB
```

### Expected Results

I expected the files `./localtion/fileA` and `./location/fileB` to have changed and to be encrypted by Ansible Vault.

### Actual Results

```console
The files (`./localtion/fileA` and `./location/fileB`) contain the plain text contents of the files from `/dev/shm`.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
