### ISSUE TITLE
Children in host.yml gets conflicting

### ISSUE THREAD

**Issue by Spatenheinz** [ansible/ansible#83303]
### Summary

The way hosts are found seems either broken or are confusing.

If i have a structure like so in my hosts file:

```

all:
  children:
    parent1:
        children:
          subdomain:
             hosts:
                ......
    parent2:
        children:
           subdomain:
             hosts:
                ......           
```

Then in my site.yml I have

```
- hosts: parent1
  gather_facts: no
  roles:
     .....
     
- hosts: parent2
  gather_facts: no
  roles:
``` 

Then hosts under parent1 will also execute the roles for parent2 and vice versa.
If changing subdomain under parent2 to subdomain fixes the issue. Is this intended behaviour, if so this is very misleading, since they are clearly different domains.

### Issue Type

Bug Report

### Component Name

playbook

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.5]
  config file = /home/jchb/Documents/ansible/ansible.cfg
  configured module search path = ['/home/jchb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/c5m88lsdicmk25y9v18m8mqrk6bqjqh1-python3.11-ansible-core-2.16.5/lib/python3.11/site-packages/ansible
  ansible collection location = /home/jchb/.ansible/collections:/usr/share/ansible/collections
  executable location = /nix/store/c5m88lsdicmk25y9v18m8mqrk6bqjqh1-python3.11-ansible-core-2.16.5/bin/ansible
  python version = 3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.2.0] (/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/home/jchb/Documents/ansible/ansible.cfg) = ['/home/jchb/Documents/ansible/roles', '/home/jchb/Documents/roles']
```

### OS / Environment

target OS is many different versions of Debian (10-12)

### Steps to Reproduce

see summary.

### Expected Results

I expect children of different parents to be able to have the same name.
Especially, the plays for different parents should be executed twice just because they share a common name for the children.
I would still expect it to work to use --limit subdomain and get from both parents, but using --limit parent1 should never execute parent2, and likewise --limit "specific_host" should not trigger parent2 play if only a part of parent2's tree.

### Actual Results

```console
Children of different parents cannot share name.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/cli/playbook.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/playbook.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@Spatenheinz `ansible-core` 2.12 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by prokopto-dev** [comment]
@Spatenheinz : So this is a pretty understandable formatting mistake, and I can see the source of the confusion.

So let me write you an equivalent version of your example, albeit more pedantic formatting:

```yaml

all:
  children:
    parent1:
    parent2:

parent1:
  children:
    subdomain:

parent2:
  children:
    subdomain:

subdomain:
  hosts:
    host1:
    host2:
    host3:
```

Now it is possible you intended those two `subdomain` entries in your file to be different, in which case, my mistake, but in your example this is whats being written out.

Importantly, what this means is that any roles that apply to the parent groups apply to their children.

With that being the case, since both have `subdomain` listed as their child group, that means hosts `host1`, `host2`, and `host3` all will inherit any properties, roles, tasks, etc assigned to all members and children of the parent group targeted, regardless if its `parent1` or `parent2`.

If you were to change it to something like this:

```yaml

all:
  children:
    parent1:
    parent2:

parent1:
  children:
    subdomain1:

parent2:
  children:
    subdomain2:

subdomain1:
  hosts:
    host1:
    host2:

subdomain2:
  hosts:
    host3:
    host4:
```

That would accomplish a separation where `parent1` has only the `subdomain1` hosts, and `parent2` has only the `subdomain2` hosts inheriting anything.

In that case though, everything would still remain under the `all` heading.


I think that would solve your problem.

**Comment by prokopto-dev** [comment]
@Spatenheinz : And assuming you want to keep your formatting, the way would be not dissimilar in the condensed format:

```yaml
all:
  children:
    parent1:
        children:
          subdomain1:
             hosts:
                ......
    parent2:
        children:
           subdomain2:
             hosts:
                ......  
```

But basically, if it isn't any of `hosts:`, `children:`, or `vars:` (and a couple other reserved keywords in there too), it is treated as a variable name in the same scope for the inventory, and because `subdomain` was already assigned, it is treated as identical, and thus, shared.

**Comment by prokopto-dev** [comment]
@sivel : Actually, it's not quite a duplicate, but similar for sure.

In this case, it's more about how namespaces are dealt with, not so much the fact two groups can inherit the same host.

@Spatenheinz : You may be right about the oddness in how the AST constructs these things, but it is unfortunately exactly how its intended. 

Let me expand my example a little more:

Take the following from before:

```yaml
all:
  children:
    parent1:
    parent2:

parent1:
  children:
    subdomain:

parent2:
  children:
    subdomain:

subdomain:
  hosts:
    host1:
    host2:
    host3:
```

Then take the following that mimics, what I guess, is your example:

```yaml
all:
  children:
    parent1:
        children:
          subdomain:
             hosts:
                host1:
    parent2:
        children:
           subdomain:
             hosts:
                host2:
                host3:
```

These both result in the same output object (here it is in JSON-esque format)

```json
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped",
            "parent1",
            "parent2"
        ]
    },
    "parent1": {
        "children": [
            "subdomain"
        ]
    },
    "parent2": {
        "children": [
            "subdomain"
        ]
    },
    "subdomain": {
        "hosts": [
            "host1",
            "host2",
            "host3"
        ]
    }
}
```

As you can see, what it does it evaluate each level of the tree, from top down; so the actual children of `all` are `parent1`, `parent2` and then the `ungrouped`. That's partially how `all` works, but whatever.

Then we have `parent1` and `parent2`. They have a child of `subdomain`. Then that `subdomain` entry gets its own section and all hosts listed under `subdomain`, regardless of where they were written, are added.

**Comment by s-hertel** [comment]
There have been many duplicates, it's a common misunderstanding about groups/hosts. The name of the group/host is the unique identifier globally. You could use the generator inventory https://docs.ansible.com/ansible/latest/collections/ansible/builtin/generator_inventory.html to simplify creating unique host/group names:
```yaml
plugin: ansible.builtin.generator
hosts:
  name: "host{{ hosts['label'] }}"
  parents:
    - name: "subdomain_{{ hosts['stage'] }}"
      parents:
        - name: "{{ hosts['stage'] }}"
layers:
  hosts:
    - stage: dev
      label: 0
    - stage: prod
      label: 1
    - stage: prod
      label: 2
```

A few more related issues: https://github.com/ansible/ansible/issues/17100#issuecomment-504467928, https://github.com/ansible/ansible/issues/45163#issuecomment-418380881, https://github.com/ansible/ansible/issues/76447#issuecomment-985023061
