### ISSUE TITLE
A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").

### ISSUE THREAD

**Issue by mspanc** [ansible/ansible#8331]
I got the following error:

```
A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").
```

The task is

```
- name: MySQL security - update mysql root password for all root accounts
  mysql_user: name=root host="{{item}}" password="{{ lookup('password', '../../../../credentials/mysql/root/' + ansible_hostname + ' length=32') }}"
  with_items:
    - "{{ansible_hostname}}"
    - 127.0.0.1
    - ::1
```

There's no equal sign in the password. There are dots, commas, and underscores but no equal sign.

Ansible 1.6.7 / mac os
