### ISSUE TITLE
`required_one_of` doesn't check variable type

### ISSUE THREAD

**Issue by libvoid** [ansible/ansible#83314]
### Summary

In `argument_specs`,`required_one_of` and `required_if` don't check the type of the variable. This is not the expected behavior.

In comparison, this issue doesn't show up when using `required: true`.

### Issue Type

Bug Report

### Component Name

validate_argument_spec

### Ansible Version

```console
ansible [core 2.16.7]
  config file = /home/libvoid/Documents/aw-security/pki/ansible.cfg
  configured module search path = ['/home/libvoid/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/libvoid/.cache/pypoetry/virtualenvs/cve-jzrDeld9-py3.10/lib/python3.10/site-packages/ansible
  ansible collection location = /home/libvoid/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/libvoid/.cache/pypoetry/virtualenvs/cve-jzrDeld9-py3.10/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/home/libvoidfre/.cache/pypoetry/virtualenvs/cve-jzrDeld9-py3.10/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Debian 12

### Steps to Reproduce

Minimal role:

```yaml
---
- debug:
   msg: "{{ users.a }}"
```

Minimal `meta/argument_specs.yml.yml`:

```yaml
---
argument_specs:
  main:
    options:
      users:
        required: true
        type: dict
        required_one_of:
          - [a, b]
        options:
          a:
            required: false
            type: list
            elements: str
          b:
            required: false
            type: list
            elements: str
```

Minimal playbook:

```yaml
---
- name: test
  hosts: localhost
  roles:
    - { role: roles/test, tags: [all] }
```

`host_vars/localhost`:

```
users:
  a:
```

### Expected Results

`a` variable is a boolean whereas it is defined as a `list` in the `meta/argument_specs.yml` file.

The automatic *Validating arguments against arg* task should **fail** if the type of the variable is wrong when using `required_one_of`.

### Actual Results

```console
TASK [roles/test : Validating arguments against arg spec 'main'] *********************************************************************
ok: [localhost]

TASK [roles/test : debug] ************************************************************************************************************
ok: [localhost] => 
    msg: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
