### ISSUE TITLE
include_tasks with loop and when is not skipping tasks #40746 is back

### ISSUE THREAD

**Issue by lukum2118** [ansible/ansible#83315]
### Summary

Same problem as was fixed in #40746 is back in 2.16.2

include_task with a loop and 'when' clause is not skipped if condition does not match.
it is not skipped even for a block with 'when'. Without a loop it is working perfectly.

### Issue Type

Bug Report

### Component Name

include_task

### Ansible Version

```console
$ ansible --version

ansible [core 2.16.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/app/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /app/ansible_collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.5 (main, Sep 22 2023, 15:34:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ANSIBLE_HOME(env: ANSIBLE_HOME) = /app/ansible
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['ansible.posix.profile_tasks', 'ansible.posix.profile_roles']
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/app/ansible_collections']
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/filter', '/app/ansible/plugins/filter']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/app/ansible/inventory/stacks']
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/ansible-local-2000860npiauasq
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/app/ansible/roles']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False
timeout(/etc/ansible/ansible.cfg) = 60

ssh:
___
host_key_checking(/etc/ansible/ansible.cfg) = False
timeout(/etc/ansible/ansible.cfg) = 60
```

### OS / Environment

RHEL 8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

### Steps to Reproduce

```yaml (paste below)
- name: "manifest certificates length"
      ansible.builtin.debug:
        msg: 
          - "certs: {{ manifest_certificates }}"
          - "len: {{ manifest_certificates | length }}"

    - name: run only if certificates section is a list
      block:
        - name: "case of multiple certificates"
           ansible.builtin.debug:
            msg: 
              - "running multiple certs"

        - name: "Pull certs in a loop/list"
          ansible.builtin.include_tasks: "tasks/import_custom_certificate.yml"
          vars:
            manifest_certificate: "{{ item }}"
            keystore_password: "{{ _EPV_SECRET }}"
          loop: "{{ manifest_certificates }}"
          when: manifest_certificates | length >1

      when: manifest_certificates | length >1

```

### Expected Results

I expect the task 
    - name: "Pull certs in a loop/list" 
should be skipped as length == 1 same as a 'debug' before the include task.

TASK [manifest certificates length] *****************************************************************************************************************************************************************************************************************
Tuesday 28 May 2024  17:52:20 -0400 (0:00:00.562)       0:00:39.847 ***********
Tuesday 28 May 2024  17:52:20 -0400 (0:00:00.562)       0:00:39.847 ***********
ok: [xxxxxx] => {
    "msg": [
        "certs: {'Certificate': {'name': 'xxxxxx.com'}}",
        "len: 1"
    ]
}

TASK [case of multiple certificates] ****************************************************************************************************************************************************************************************************************
Tuesday 28 May 2024  17:52:20 -0400 (0:00:00.047)       0:00:39.894 ***********
skipping: [xxxxxx]

TASK [Pull certs in a loop/list] ********************************************************************************************************************************************************************************************************************
Tuesday 28 May 2024  17:52:20 -0400 (0:00:00.039)       0:00:39.934 ***********
skipping: [xxxxxx]

### Actual Results

```console
TASK [manifest certificates length] *****************************************************************************************************************************************************************************************************************
Tuesday 28 May 2024  17:52:20 -0400 (0:00:00.562)       0:00:39.847 ***********
Tuesday 28 May 2024  17:52:20 -0400 (0:00:00.562)       0:00:39.847 ***********
ok: [xxxxxx] => {
    "msg": [
        "certs: {'Certificate': {'name': 'xxxxxx.com'}}",
        "len: 1"
    ]
}

TASK [case of multiple certificates] ****************************************************************************************************************************************************************************************************************
Tuesday 28 May 2024  17:52:20 -0400 (0:00:00.047)       0:00:39.894 ***********
skipping: [xxxxxx]

TASK [Pull certs in a loop/list] ********************************************************************************************************************************************************************************************************************
Tuesday 28 May 2024  17:52:20 -0400 (0:00:00.039)       0:00:39.934 ***********
fatal: [xxxxxx]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {'Certificate': {'name': 'xxxxxx.com'}}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by sivel** [comment]
https://docs.ansible.com/ansible-core/devel/playbook_guide/playbooks_conditionals.html#using-conditionals-in-loops

**Comment by flowerysong** [comment]
This is not a bug. As noted in the link sivel provided conditionals are evaluated for loop items, not for the loop as a whole, so the loop declaration needs to be valid even if the conditional ends up not being true.

If you're trying to let users provide either a list of dictionaries or a single dictionary, one way to achieve that might be:

```yaml
        - name: Pull certs in a loop
          ansible.builtin.include_tasks: tasks/import_custom_certificate.yml
          vars:
            manifest_certificate: "{{ item }}"
            keystore_password: "{{ _EPV_SECRET }}"
          loop: "{{ [manifest_certificates] | flatten }}"
```
