### ISSUE TITLE
no_log does not honor variable interpretation.

### ISSUE THREAD

**Issue by r-pufky** [ansible/ansible#83323]
### Summary

Using `no_log` is essential for removing sensitive material from logs during production execution, however, it can interfere with complex roles during development and debugging.

Using a role variable or even a role default allows for toggling `no_log` off in development and molecule testing environments. However:

* The variable is never honored when used with `no_log`.
* It seems that the presence of *any* value except static boolean values is interpreted as `no_log: true`.
* There seems to be order of operations error interpreting values provided to `no_log`.

As the steering committee voted against the ability to [toggle individual variables appearing in `no_log` ](https://github.com/ansible/proposals/issues/109); this is a good middle path that doesn't change the how `no_log` works, just how *easy* it is to toggle on/off for development of roles (and removing errors from leaving it accidentially disabled).

### Issue Type

Bug Report

### Component Name

no_log

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.7]
  config file = None
  configured module search path = ['/home/{REDACTED}/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/{REDACTED}/.config/venv/ansible/lib/python3.12/site-packages/ansible
  ansible collection location = /home/{REDACTED}/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/{REDACTED}/.config/venv/ansible/bin/ansible
  python version = 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417] (/home/{REDACTED}/.config/venv/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
(ansible)
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
(ansible)
```

### OS / Environment

``` bash
$ cat /etc/lsb-release 
DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="24.0.0"
DISTRIB_CODENAME="Wynsdey"
DISTRIB_DESCRIPTION="Manjaro Linux"
```

### Steps to Reproduce

roles/example/defaults/main.yml
``` yaml
sensitive_info:
  - '{{ vault_example_user_password }}'
```

roles/example/vars/main.yml
``` yaml
example_debug_false: false
example_debug_true: true
```

roles/example/tasks/main.yml
``` yaml
- name: 'Example debug values'
  ansible.builtin.debug:
    msg: |
      example_debug_false: '{{ example_debug_false }}'
      example_debug_true: '{{ example_debug_true }}'

- name: 'Loop through sensitive user data (log should NOT appear)'
  ansible.builtin.include_tasks: 'task.yml'
  loop: '{{ sensitive_info | default([]) }}'
  no_log: '{{ example_debug_true }}'  # passwords

- name: 'Loop through sensitive user data (log should NOT appear)'
  ansible.builtin.include_tasks: 'task.yml'
  loop: '{{ sensitive_info | default([]) }}'
  no_log: true  # passwords

- name: 'Loop through sensitive user data (log *SHOULD* appear)'
  ansible.builtin.include_tasks: 'task.yml'
  loop: '{{ sensitive_info | default([]) }}'
  no_log: '{{ example_debug_false }}'  # passwords

- name: 'Loop through sensitive user data (log *SHOULD* appear)'
  ansible.builtin.include_tasks: 'task.yml'
  loop: '{{ sensitive_info | default([]) }}'
  no_log: false  # passwords
```

### Expected Results
```
TASK [example : Value of example_debug'] *******************************************
ok: [molecule-test] => {
    "msg": "example_debug_false: 'False'\nexample_debug_true: 'True'"
}

TASK [example : Loop through sensitive user data (log should NOT appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=(censored due to no_log))

TASK [example : Loop through sensitive user data (log should NOT appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=(censored due to no_log))

TASK [example : Loop through sensitive user data (log *SHOULD* appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=my_super_secret_password)

TASK [example : Loop through sensitive user data (log *SHOULD* appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=my_super_secret_password)
```
### Actual Results

```console
TASK [example : Value of example_debug'] *******************************************
ok: [molecule-test] => {
    "msg": "example_debug_false: 'False'\nexample_debug_true: 'True'"
}

TASK [example : Loop through sensitive user data (log should NOT appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=(censored due to no_log))

TASK [example : Loop through sensitive user data (log should NOT appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=(censored due to no_log))

TASK [example : Loop through sensitive user data (log *SHOULD* appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=(censored due to no_log))

TASK [example : Loop through sensitive user data (log *SHOULD* appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=my_super_secret_password)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
Have you tried?
```
no_log: '{{ example_debug_false|bool }}'  # passwords
```

no_log, unlike other boolean keywords, will always fail to 'True' if assigned and if Ansible cannot figure out the proper boolean.

**Comment by r-pufky** [comment]
Casting to `bool` does not resolve the issue:

defaults/main.yml
``` yaml
enable_debug_false: false
```

tasks/main.yml
``` yaml
- name: 'Loop through sensitive user data (log *SHOULD* appear)'
  ansible.builtin.include_tasks: 'task.yml'
  loop: '{{ sensitive_info | default([]) }}'
  no_log: '{{ example_debug_false|bool }}'  # passwords
```

``` log
TASK [example : Loop through sensitive user data (log *SHOULD* appear)'] ********************************************
included: /home/{REDACTED}/test_case/roles/example/tasks/main.yml for molecule-test => (item=(censored due to no_log))
```

**Comment by r-pufky** [comment]
I should also note that this very likely exists for *ALL* ansible versions.

I’ve been able to find references to this going back 8 years: https://www.reddit.com/r/ansible/comments/4g6xdk/setting_no_log_via_variable/

**Comment by bcoca** [comment]
As i mentioned above, `no_log` is the one boolean that fails to `true`  instead of default value when the assigned expression is not understood, this was a conscious decision in core code to fail on the safe side.

**Comment by s-hertel** [comment]
I can reproduce with `include_role`|`include_tasks`, with or without `loop`, even when using extra vars or `|default` to ensure variables are defined.  Adding `always_post_validate=True` to the `no_log` FieldAttribute would fix it.

```python
no_log = FieldAttribute(isa='bool', default=C.DEFAULT_NO_LOG, always_post_validate=True)
```

It's not totally clear to me if there's a reason we can't post validate TaskInclude and IncludeRole here though https://github.com/ansible/ansible/blob/stable-2.17/lib/ansible/playbook/base.py#L531 (I guess any FA for these are relying on piecemeal templating still).

**Comment by sivel** [comment]
data tagging may be solving this already, since they get post validated in the TE before returning, which means we also remove all of the one off templating from `IncludedFile`.  I haven't validated this yet, just making a guess based on changes that I know have been made.

That `elif` has been extended to:

```
        elif not attribute.always_post_validate and self.__class__.__name__ not in ('Task', 'Handler', 'PlayContext', 'IncludeRole', 'TaskInclude'):
```

**Comment by bcoca** [comment]
Ilooked into it and its an issue with having 2 sources for no_log  (play_context/task) and waiting to template no_log both inside and outside the loop, making it possible to change during loop iterations. Forcing post_validation will 'fix' this issue but might cause issues with per loop values.

**Comment by s-hertel** [comment]
That doesn't fix it for me. I've was testing with 2 identical sources. The variable is available and the post validated, but the FA isn't applicable to be templated. If `always_post_validate` is too heavy of a hammer, this also fixes it:
```diff
diff --git a/lib/ansible/playbook/included_file.py b/lib/ansible/playbook/included_file.py
index d2fdb76364..6dc64a9051 100644
--- a/lib/ansible/playbook/included_file.py
+++ b/lib/ansible/playbook/included_file.py
@@ -103,8 +103,6 @@ class IncludedFile:
                         task_vars['_ansible_item_label'] = special_vars['_ansible_item_label'] = include_result['_ansible_item_label']
                     if 'ansible_loop' in include_result:
                         task_vars['ansible_loop'] = special_vars['ansible_loop'] = include_result['ansible_loop']
-                    if original_task.no_log and '_ansible_no_log' not in include_args:
-                        task_vars['_ansible_no_log'] = special_vars['_ansible_no_log'] = original_task.no_log
 
                     # get search path for this task to pass to lookup plugins that may be used in pathing to
                     # the included file
@@ -116,6 +114,10 @@ class IncludedFile:
 
                     templar = Templar(loader=loader, variables=task_vars)
 
+                    if original_task.no_log and '_ansible_no_log' not in include_args:
+                        task_vars['_ansible_no_log'] = special_vars['_ansible_no_log'] = templar.template(original_task.no_log)
+
                     if original_task.action in C._ACTION_INCLUDE_TASKS:
                         include_file = None
```

**Comment by bcoca** [comment]
```
TASK [test : Loop through sensitive user data (log should NOT appear)] **************************************************************************************
 [started TASK: test : Loop through sensitive user data (log should NOT appear) on localhost]
included: /home/bcoca/work/testing/no_log/roles/test/tasks/task.yml for localhost => (item=(censored due to no_log))

TASK [test : Loop through sensitive user data (log should NOT appear)] **************************************************************************************
 [started TASK: test : Loop through sensitive user data (log should NOT appear) on localhost]
included: /home/bcoca/work/testing/no_log/roles/test/tasks/task.yml for localhost => (item=(censored due to no_log))

TASK [test : Loop through sensitive user data (log *SHOULD* appear)] ****************************************************************************************
 [started TASK: test : Loop through sensitive user data (log *SHOULD* appear) on localhost]
included: /home/bcoca/work/testing/no_log/roles/test/tasks/task.yml for localhost => (item=secret)

TASK [test : Loop through sensitive user data (log *SHOULD* appear)] ****************************************************************************************
 [started TASK: test : Loop through sensitive user data (log *SHOULD* appear) on localhost]
included: /home/bcoca/work/testing/no_log/roles/test/tasks/task.yml for localhost => (item=secret)

```
^ with my patch i get the expected "last 2 tasks not censored", but i expect it won't cover many other cases

**Comment by s-hertel** [comment]
@bcoca I was testing with and without `loop`, and because it affects both, `_run_loop` didn't seem like the root cause. I thought IncludedFile would be a common denominator, but maybe it needs fixing in multiple places for consistency.

**Comment by bcoca** [comment]
yes, that is why i was not happy with 'my fix' that handles just this example, we have too many 'side paths' for these things and it is prone to both divergence and bug duplication.

I'm trying to think of a good way to just eliminate "include helpers"  so we can have 'one fix'.

**Comment by bcoca** [comment]
@s-hertel if we do add templating to the other sections outside of loop, you have to be able to ignore errors/default to true as they can depend on the loop var, so no_log should not be fatal until it gets reevaluated in the loop

**Comment by mattclay** [comment]
Since we've reworked no_log in data tagging, we shouldn't try to fix this until DT has been merged and the issue has been verified to still exist.

**Comment by bcoca** [comment]
@mattclay, the problem with that, data tagging is not backportable, other fixes will be

**Comment by mattclay** [comment]
@bcoca I realize we'll need one (or possibly two, if DT doesn't resolve the issue) fixes for this. However, if we merge a fix to devel before DT, we're likely to end up with some rather messy merge conflicts. The fix could be written for stable-2.17 and then a separate fix (if needed) could be written for devel.

**Comment by parmstro** [comment]
I am merely an ansible automation developer and haven't looked under the hood. I found this issue because I was experiencing the issue outline in the initial issue statement. 

I would like to implement this sort of capability within my roles...
if the main_logging is true OR the local module logging is true, ensure that logging occurs
If both are false, do not log any data

```
- name: "Configure the idm users specified for rh-isam sample environment"
  when: idm_users_rhisam is defined
  ansible.builtin.include_tasks: "ensure_user.yml"
  loop: "{{ idm_users_rhisam }}"
  loop_control:
    loop_var: user
  no_log: "{{ not (main_logging or idm_users_logging) }}"
  tags:
    - tags_rhisam
    - tags_authentication_config
    - tags_idm_users
    - tags_idm_users_rhisam
```
