### ISSUE TITLE
(facts) include microarch in system facts

### ISSUE THREAD

**Issue by jcpunk** [ansible/ansible#83331]
### Summary

I am trying to identify systems across my infrastructure that do not support `x86_64v3` in prep for RHEL10.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.setup

### Additional Information

```yaml (paste below)
  tasks:
    - name: Gather ansible system facts
      ansible.builtin.setup:
        gather_subset:
        - 'all'
        - '!facter'
        - '!ohai'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
