### ISSUE TITLE
to_yaml / to_nice_yaml is not able to decrypt Vault password

### ISSUE THREAD

**Issue by boutetnico** [ansible/ansible#83359]
### Summary

Follow-up of https://github.com/ansible/ansible/issues/77771.

JSON decoder `to_json` proposes a `vault_to_text`(default to `true`) parameter to be able to decrypt Vault password.

The YAML decoder `to_yaml` and `to_nice_yaml` does not have this parameter.

Current workaround:

`my_var_yaml: "{{ my_var | to_json(vault_to_text=True) | from_json | to yaml }}"`

### Issue Type

Bug Report

### Component Name

to_yaml

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.7]
  config file = /Users/myuser/Code/ansible/ansible.cfg
  configured module search path = ['/Users/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/myuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/opt/python@3.12/bin/python3.12)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ansible-config dump --only-changed
```

### OS / Environment

macOS 14

### Steps to Reproduce

```yaml
---
- hosts: localhost
  gather_facts: false
  vars:
    testvar: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      REDACTED
    testvar_json: "{{ testvar | to_json }}"
    testvar_yaml: "{{ testvar | to_nice_yaml }}"
  tasks:
    - name: Print results
      ansible.builtin.debug:
        msg: "JSON: {{ testvar_json }}, YAML: {{ testvar_yaml }}"
```

### Expected Results

```
ok: [localhost] => {
    "msg": "JSON: \"bugfix\", YAML: \"bugfix\""
}
```

### Actual Results

```console
ok: [localhost] => {
    "msg": "JSON: \"bugfix\", YAML: !vault |\n    $ANSIBLE_VAULT;1.1;AES256\nREDACTEDn"
}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
