### ISSUE TITLE
Sudo password error when including role

### ISSUE THREAD

**Issue by dryewo** [ansible/ansible#8337]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.8
##### Environment:

From OS X 10.9.4 to Ubuntu 14.04
##### Summary:

I'm getting sudo password error when attemting to install Java by including `groover.java` role in my playbook.
##### Steps To Reproduce:

Im my working directory there are files:

`hosts`:

``` ini
[scm]
123.123.123.123 ansible_ssh_user=master
```

`ansible.cfg`:

``` ini
[defaults]
hostfile = ./hosts
host_key_checking = False
nocows=1
```

`csvn.yml`:

``` yml

---
- name: Setup CollabNet Subversion Edge
  hosts: scm
  sudo: yes
  roles:
     - { role: groover.java, java_default_distribution: jre }
```
1. First I install the `groover.java` role:

``` sh
$ sudo ansible-galaxy install groover.java
```
1. Then I run the playbook:

``` sh
$ ansible-playbook -K csvn.yml -vvvv
```

Then it asks me for the sudo password, which I correctly type in an then press Enter.
##### Expected Results:

Ansible gives no error.
Java gets installed on the target host, so that `java -version` will show.
##### Actual Results:

Ansible gives me the following error:

```
failed: [123.123.123.123] => {"failed": true, "parsed": false}
invalid output was: Sorry, try again.
[sudo via ansible, key=sexsehsjjjrnatxkxhbsecbnudhiwojs] password: 
sudo: 1 incorrect password attempt
```

It can't be the wrong sudo password, because I tried other actions with sudo, for example:

``` yml

---
- name: Setup CollabNet Subversion Edge
  hosts: scm
  sudo: yes
  roles:
#     - { role: groover.java, java_default_distribution: jre }
  tasks:
    - name: Create group
      group: name=svn
    - name: Create svn user
      user: name=svn groups=svn

```

The users get created, no errors. When I mistyped the password, it gave me different error:

```
fatal: [123.123.123.123] => Incorrect sudo password
```
