### ISSUE TITLE
(edited) shell command quote filtering issue

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#8338]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.9
##### Environment:

OS X 10.9.4
##### Summary:

Referring to a file that includes an escaped space character as the value for the "creates" argument makes the command or shell module non-idempotent
##### Steps To Reproduce:

This seems to have been introduced in 1.6.9

Run this playbook twice:

``` yaml

---
- hosts: all
  connection: local

  tasks:
    - command: touch Sample\ File.txt creates=Sample\ File.txt
```
##### Expected Results:

```
TASK: [command touch Sample\ File.txt creates=Sample\ File.txt] *************** 
<localhost> REMOTE_MODULE command touch Sample\ File.txt creates=Sample\ File.txt
skipping: [localhost]
```
##### Actual Results:

```
TASK: [command touch Sample\ File.txt creates=Sample\ File.txt] *************** 
<localhost> REMOTE_MODULE command touch Sample\ File.txt creates=Sample\ File.txt
changed: [localhost] => {"changed": true, "cmd": ["touch", "Sample File.txt"], "delta": "0:00:00.004000", "end": "2014-07-29 12:41:08.626214", "rc": 0, "start": "2014-07-29 12:41:08.622214", "stderr": "", "stdout": ""}
```
