### ISSUE TITLE
`file`: incomplete/misleading/missing diff when recursively setting attributes

### ISSUE THREAD

**Issue by simonLeary42** [ansible/ansible#83435]
### Summary

When recursively setting file attributes, I expect to see all changes in the diff, but there are none. When the directory's attributes are modified as well as the files within, the diff shows that only the directory has been modified, when in fact much more is being done.

### Issue Type

Bug Report

### Component Name

file

### Ansible Version

```console
ansible [core 2.17.0]
...
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu Focal

### Steps to Reproduce

```yaml
- name: play
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create directory with same perms
      ansible.builtin.file:
        path: /tmp/foo/bar
        state: directory
        mode: "0755"
      diff: false

    - name: create directory with different perms
      ansible.builtin.file:
        path: /tmp/fu/bar
        state: directory
        mode: "0770"
      diff: false

    - name: create file with different perms
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
        mode: "0770"
      diff: false
      loop:
        - /tmp/foo/bar/file1
        - /tmp/foo/bar/file2
        - /tmp/fu/bar/file1
        - /tmp/fu/bar/file2

    - name: recursively modify permissions on directory with same perms
      ansible.builtin.file:
        path: /tmp/foo/bar
        mode: "0755"
        recurse: true
      diff: true

    - name: recursively modify permissions on directory with different perms
      ansible.builtin.file:
        path: /tmp/fu/bar
        mode: "0755"
        recurse: true
      diff: true

```

### Expected Results

```console
PLAY [play] *******************************************************************************************************************************

TASK [create directory with same perms] ***************************************************************************************************
changed: [localhost]

TASK [create directory with different perms] **********************************************************************************************
changed: [localhost]

TASK [create file with different perms] ***************************************************************************************************
changed: [localhost] => (item=/tmp/foo/bar/file1)
changed: [localhost] => (item=/tmp/foo/bar/file2)
changed: [localhost] => (item=/tmp/fu/bar/file1)
changed: [localhost] => (item=/tmp/fu/bar/file2)

TASK [recursively modify permissions on directory with same perms] ************************************************************************
--- before
+++ after
@@ -1,2 +1,2 @@
-mode: '0770'
+mode: '0755'
 path: /tmp/foo/bar/file2

--- before
+++ after
@@ -1,2 +1,2 @@
-mode: '0770'
+mode: '0755'
 path: /tmp/foo/bar/file1

changed: [localhost]

TASK [recursively modify permissions on directory with different perms] *******************************************************************
--- before
+++ after
@@ -1,2 +1,2 @@
-mode: '0770'
+mode: '0755'
 path: /tmp/fu/bar

--- before
+++ after
@@ -1,2 +1,2 @@
-mode: '0770'
+mode: '0755'
 path: /tmp/fu/bar/file2

--- before
+++ after
@@ -1,2 +1,2 @@
-mode: '0770'
+mode: '0755'
 path: /tmp/fu/bar/file1

changed: [localhost]

PLAY RECAP ********************************************************************************************************************************
localhost                  : ok=5    changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### Actual Results

```console
PLAY [play] *******************************************************************************************************************************

TASK [create directory with same perms] ***************************************************************************************************
changed: [localhost]

TASK [create directory with different perms] **********************************************************************************************
changed: [localhost]

TASK [create file with different perms] ***************************************************************************************************
changed: [localhost] => (item=/tmp/foo/bar/file1)
changed: [localhost] => (item=/tmp/foo/bar/file2)
changed: [localhost] => (item=/tmp/fu/bar/file1)
changed: [localhost] => (item=/tmp/fu/bar/file2)

TASK [recursively modify permissions on directory with same perms] ************************************************************************
changed: [localhost]

TASK [recursively modify permissions on directory with different perms] *******************************************************************
--- before
+++ after
@@ -1,2 +1,2 @@
-mode: '0770'
+mode: '0755'
 path: /tmp/fu/bar

changed: [localhost]

PLAY RECAP ********************************************************************************************************************************
localhost                  : ok=5    changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
