### ISSUE TITLE
`file`: incomplete diff when creating parent directories

### ISSUE THREAD

**Issue by simonLeary42** [ansible/ansible#83434]
### Summary

If I create a directory and ansible automatically creates nonexistent parent directories, ansible should tell about all the directories it created, not just the deepest one.

### Issue Type

Bug Report

### Component Name

file

### Ansible Version

```console
ansible [core 2.17.0]
...
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu Focal

### Steps to Reproduce

```
- name: play
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: /tmp/fu/bar
        state: directory
        mode: "0770"
      diff: true

changed: [localhost]
```

### Expected Results

```console
TASK [create directory] ************************************************************************************************
--- before
+++ after
-mode: '0775'
+mode: '0770'
 path: /tmp/fu
-state: absent
+state: directory

-mode: '0775'
+mode: '0770'
 path: /tmp/fu/bar
-state: absent
+state: directory
```

### Actual Results

```console
TASK [create directory] *************************************************************************************************
--- before
+++ after
@@ -1,3 +1,3 @@
-mode: '0775'
+mode: '0770'
 path: /tmp/fu/bar
-state: absent
+state: directory
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
