### ISSUE TITLE
Multi-line tasks that used to work now require "args: " syntax?

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#8343]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Mac OSX controller managing Slackware64 14.1 machines
##### Summary:

Some recent change (both latest 1.6.x and 1.7 git are affected) now gives errors with task multi-line syntax ">" that used to work properly earlier.

 Now I need to instead do:

```
- name: mdadm.conf backup
  command: >
    mv mdadm.conf mdadm.conf.orig
  args:
    creates: mdadm.conf.orig
    chdir: /mnt/etc
```

Wondering if this was an intentional change to force a more "correct" syntax or an unintended side-effect of some recent change.
##### Steps To Reproduce:

I used to be able to write tasks as follows:

```
- name: mdadm.conf backup
  command: >
    mv mdadm.conf mdadm.conf.orig
    creates=mdadm.conf.orig
    chdir=/mnt/etc
```
##### Expected Results:

Successful execution/skip of tasks
##### Actual Results:

```
TASK: [install | mdadm.conf backup] ******************************************* 
failed: [dev4] => {"failed": true, "rc": 258}
msg: cannot change to directory '/mnt/etc
': path does not exist

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Questions are a better topic for ansible-project, we don't want to require the args syntax here at all and have never suggested it, but we can look into what's going on with multi-line command parsing here for sure.

Thanks for the report!

**Comment by astorije** [comment]
I have another test case here.

I was using the distribution packages (`Ansible 1.6.6` on Ubuntu 13.10) and now uses the source directly (`ansible 1.7 (devel c9bfcf40d3) last updated 2014/07/30 14:44:19 (GMT +200)`, same system).

On the former one, this was working:

``` yaml
- name: Test command
  command: >
    ls
    chdir=/
  tags: test
```

On the latter one, this produces the output given by @edrozenberg, and this works instead:

``` yaml
- name: Test command
  command: ls chdir=/
  tags: test
```

I can investigate to work on a PR if it helps, but I am new to Ansible development and might waste some time for nothing, so any advice is appreciated.

For what it's worth, I am using multi-lines on almost every single task I am declaring, including `git` ones (as @edrozenberg reported that the `git` module was affected) and it only broke when running the handlers, in which are some `shell` tasks.
