### ISSUE TITLE
`meta: end_host` returns `rc=2` when run in a rescue block

### ISSUE THREAD

**Issue by spetrosi** [ansible/ansible#83447]
### Summary

When I run `meta: end_host` in a `rescue` block, Ansible finishes with `rc=2`. I expect it to exit with `rc=0` as usual.

### Issue Type

Bug Report

### Component Name

meta

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/spetrosi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/spetrosi/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/spetrosi/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/spetrosi/.local/bin/ansible
  python version = 3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = vim
```

### OS / Environment

Fedora 38

### Steps to Reproduce

1. Run this playbook to reproduce rc=2:
```yaml
---
- name: Ensure that the role runs with default parameters
  hosts: all
  tasks:
    - name: Run in a block to clean up afterwards
      block:
        - name: Fail
          fail:
            msg: Test fail
      rescue:
        - name: Assert failure
          assert:
            that: __str in ansible_failed_result.msg
          vars:
            __str: Test fail

        - name: End host
          meta: end_host
```

2. Assert that `rc` == 2:
```shell
$ echo $?
2
```

3. Run this playbook that would return rc=0:
```yaml
---
- name: Ensure that the role runs with default parameters
  hosts: all
  tasks:
    - name: End host
      meta: end_host
```

2. Assert that `rc` == 0:
```shell
$ echo $?
0
```

### Expected Results

rc == 0 in both cases

### Actual Results

```console
rc == 2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
