### ISSUE TITLE
File descriptor leak in lib/ansible/plugins/connection/ssh.py

### ISSUE THREAD

**Issue by nicksms** [ansible/ansible#83449]
### Summary

`reset()` in `ssh.py` calls `_build_command()`, which allocates a pipe when sshpass is used. `_bare_run()` frees this normally, but `reset()` calls `Popen()` directly, causing a file descriptor leak. 

### Issue Type

Bug Report

### Component Name

connection/ssh.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.3]
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /root/.ansible.cfg
HOST_KEY_CHECKING(/root/.ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/root/.ansible.cfg) = False

ssh:
___
host_key_checking(/root/.ansible.cfg) = False
```

### OS / Environment

Originally noticed on Devuan daedalus. Also present on Fedora 38.

### Steps to Reproduce

Use the following playbook:
```yaml
---
- name: Test play
  gather_facts: false
  hosts: unreachable
  tasks:
    - name: Wait for connection 
      ansible.builtin.wait_for_connection:
        timeout: 9000
```
with this inventory (where 192.168.15.102 is replaced with any unreachable host):
```yaml
all:
  hosts:
    unreachable:
      ansible_host: 192.168.15.102
      ansible_user: root
      ansible_password: password
```

Watch the output with -vvv.

### Expected Results

Ansible should fail to connect to the server, but continue trying.

### Actual Results

```console
After about 500 seconds it ceases trying to connect. Checking `lsof` reveals 1000 file descriptors for Ansible, mostly pipes, hitting the default cap. Also, when Ansible is run with -vvv, the file descriptor referenced in -d{{fd}} keeps incrementing.

<192.168.15.102> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/nick/.ansible/cp/0cfd1cec36"' 192.168.15.102 '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
