### ISSUE TITLE
Handlers use only last role variable when flushed in multiple role executions.

### ISSUE THREAD

**Issue by martin-micimo** [ansible/ansible#83479]
### Summary

Handlers use only last role variable when flushed in multiple role executions.

### Issue Type

Bug Report

### Component Name

flush_handlers, notify, handlers, ansible.builtin.meta

### Ansible Version

```console
$ ansible --version

ansible [core 2.17.1]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/ansible/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = None
```

### OS / Environment

Debian Bookworm

### Steps to Reproduce

You need these files:

playbook.yml

```yaml
---
- name: Local
  hosts: localhost
  roles:
    - role: foo
      vars:
        bar: "one"
    - role: foo
      vars:
        bar: "two"
...
```

roles/foo/tasks/main.yml

```yaml
---
- name: Do something.
  ansible.builtin.command: "{{ item }}"
  loop:
    - "echo {{ bar }}"
  notify: Handler

- name: Flush Handlers.
  ansible.builtin.meta: flush_handlers
...
```

roles/foo/handlers/main.yml

```yaml
---
- name: Handler
  ansible.builtin.debug:
    msg: "{{ bar }}"
...
```

Then you run it with `ansible-playbook playbook.yml`.

### Expected Results

```
PLAY [Local] ********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [foo : Do something.] ******************************************************************************************************************************************************************
changed: [localhost] => (item=echo one)

TASK [foo : Flush Handlers.] ****************************************************************************************************************************************************************

RUNNING HANDLER [foo : Handler] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "one"
}

TASK [foo : Do something.] ******************************************************************************************************************************************************************
changed: [localhost] => (item=echo two)

TASK [foo : Flush Handlers.] ****************************************************************************************************************************************************************

RUNNING HANDLER [foo : Handler] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "two"
}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### Actual Results

```console
PLAY [Local] ********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [foo : Do something.] ******************************************************************************************************************************************************************
changed: [localhost] => (item=echo one)

TASK [foo : Flush Handlers.] ****************************************************************************************************************************************************************

RUNNING HANDLER [foo : Handler] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "two"
}

TASK [foo : Do something.] ******************************************************************************************************************************************************************
changed: [localhost] => (item=echo two)

TASK [foo : Flush Handlers.] ****************************************************************************************************************************************************************

RUNNING HANDLER [foo : Handler] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "two"
}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/meta.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/meta.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@martin-micimo `ansible-core` 2.14 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by martin-micimo** [comment]
> @martin-micimo `ansible-core` 2.14 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.
> 
> [click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

Thanks for pointing this out.

Rechecked with ansible-core 2.17.1 ... Bug is still here.

**Comment by martin-micimo** [comment]
There is a workaround, but I find it lacks elegance:

roles/foo/tasks/main.yml

```yaml
---
- name: Do something.
  ansible.builtin.command: "{{ item }}"
  loop:
    - "echo {{ bar }}"
  notify: Handler

- name: Register foobar
  ansible.builtin.set_fact:
    foobar: "{{ bar }}"

- name: Flush Handlers.
  ansible.builtin.meta: flush_handlers
...
```

roles/foo/handlers/main.yml

```yaml
---
- name: Handler
  ansible.builtin.debug:
    msg: "{{ foobar }}"
...
```

Now everything works as expected.

**Comment by mkrizek** [comment]
This is not a bug. The `roles:` section and `import_role` are statically preprocessed during parsing so by the time the roles are executed the value of `bar` is already `"two"`.

If you want to achieve the behavior you want you need to use `include_role` which is processed at runtime.

**Comment by martin-micimo** [comment]
Thank you for looking into this. It felt like a bug, because I was not aware of the preprocessing.

Inside the role I can use the `bar` variable and it has the right value ... but Handlers seem to run outside the role somehow. To make things more funny, I can trigger `flush_handlers` and then continue with `bar` still having the value that was assigned to this iteration of the role (and not the last value).

I decided to not use a tasklist in my playbooks to do `include_role` in it ... I find this looks quite ugly with a larger amount of roles. Instead I decided to set all the variables with `set_fact` that I use in my Handlers inside the role before flushing the Handlers.

Do you think this looks good/fine?

```yaml
- name: Local
  hosts: localhost
  tasks:
    - name: Include foo role for one.
      ansible.builtin.include_role:
        name: foo
      vars:
        bar: "one"
    - name: Include foo role for two.
      ansible.builtin.include_role:
        name: foo
      vars:
        bar: "two"
```

I will close this Bug Request, but I am sad about the answer.
