### ISSUE TITLE
User module trying to modify permissions in home directory after GID change (even when setting home: false) 

### ISSUE THREAD

**Issue by mapsacosta** [ansible/ansible#83478]
### Summary

Our scenario: 

We are testing a user management playbook that reads inputs from a variables file, the input looks like: 
```
  users:
  - username: someuser
    shell: /bin/bash
    group: 12345
    groups: 12345,618
    uid: 12345
    home: /nfs/home/someuser
    comment: "Some User"
```
And our playbook task looks like this:
```
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.username }}"
        shell: "{{ item.shell }}"
        groups: "{{ item.groups }}"
        group: "{{ item.group }}"
        uid: "{{ item.uid }}"
        home: "{{ item.home }}"
        create_home: false
        comment: "{{ item.comment }}"
      loop: "{{ host.users }}"
```

When users are created for the first time (i.e the module uses `useradd`) everything works fine. However, if for some reason we change the `group` variable and re-run the playbook, it complains that it can't change ownership (correctly so, as this is an NFS mount)
```
["msg": "usermod: Failed to change ownership of the home directory"](failed: [hostname] (item={'username': 'someuser', 'shell': '/bin/bash', 'group': 12345, 'groups': '12345,618', 'uid': 12345, 'home': '/nfs/home/someuser', 'comment': 'Some User'}) => {"ansible_loop_var": "item", "changed": false, "item": {"comment": "Some User", "group": 12345, "groups": "12345,618", "home": "/nfs/home/someuser", "shell": "/bin/bash", "uid": 12345, "username": "someuser"}, "msg": "usermod: Failed to change ownership of the home directory", "name": "someuser", "rc": 12})
```

The interesting part is that if I re-run the playbook after the error, it succeeds as if nothing happened. This has me puzzled as I don't see any differences from one run to the other nor any change in NFS permisions. Am I missing something here?

```
TASK [Create users] *************************************************************************************************************************************************************************************************************************************************************************
changed: [hostname] => (item={'username': 'someuser', 'shell': '/bin/bash', 'group': 12345, 'groups': 12345, 'uid': 12345, 'home': '/nfs/home/someuser"', 'comment': 'Some User'})
```

Is there any way to avoid this? I would like the module to not touch the home directories, not even when gids or permissions theoretically should change. Any insight is appreciated! 

### Issue Type

Bug Report

### Component Name

ansible.builtin.user

### Ansible Version

```console
[root@hostname tasks]# ansible --version
ansible [core 2.14.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, Sep 12 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
[root@hostname tasks]# ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

AlmaLinux9

### Steps to Reproduce

variables.yml
```
  users:
  - username: someuser
    shell: /bin/bash
    group: 12345
    groups: 12345,618
    uid: 12345
    home: /nfs/home/someuser
    comment: "Some User"
```
Playbook looks like this:
```
- name: Ensure groups and users are present
  hosts: all
  become: yes
  tasks:
    - name: Include variables from a file
      include_vars: variables.yml

    - name: Create users
      ansible.builtin.user:
        name: "{{ item.username }}"
        shell: "{{ item.shell }}"
        groups: "{{ item.groups }}"
        group: "{{ item.group }}"
        uid: "{{ item.uid }}"
        home: "{{ item.home }}"
        create_home: false
        comment: "{{ item.comment }}"
      loop: "{{ host.users }}"
```

To reproduce:

1. Run the playbook once 
2. Make a change to the `group` for a user in `variables.yml`
3. Re-run the playbook (fails)
4. Re-run the paybook (succeeds)

### Expected Results

I expected the playbook to register the gid change but NOT attempt to change home directory permissions

### Actual Results

```console
["msg": "usermod: Failed to change ownership of the home directory"](failed: [hostname] (item={'username': 'someuser', 'shell': '/bin/bash', 'group': 12345, 'groups': '12345,618', 'uid': 12345, 'home': '/nfs/home/someuser', 'comment': 'Some User'}) => {"ansible_loop_var": "item", "changed": false, "item": {"comment": "Some User", "group": 12345, "groups": "12345,618", "home": "/nfs/home/someuser", "shell": "/bin/bash", "uid": 12345, "username": "someuser"}, "msg": "usermod: Failed to change ownership of the home directory", "name": "someuser", "rc": 12})
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
