### ISSUE TITLE
`copy`: create parent directories

### ISSUE THREAD

**Issue by simonLeary42** [ansible/ansible#83518]
### Summary

[This issue](https://github.com/ansible/ansible/issues/81760) was previously locked, but I'd like to add to the discourse.

If I try to loop over such a data structure using the `copy` module, it will fail if the parent directory does not exist.

```
fatal: [hostname]: FAILED! => changed=false
msg: Destination directory /foo/bar does not exist
```

So I make a block:

```yml
- name: copy files
  block:
    - name: directory exists # noqa: risky-file-permissions
      ansible.builtin.file:
        path: "{{ item.src }}"
        state: directory
    - name: copy file
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0644"
  loop: "{{ copy_these }}"
```

Surprise, you can't loop over a block. A quick google yields [this](https://www.reddit.com/r/ansible/comments/17gefuo/how_to_loop_over_a_block/):

> When your Ansible playbooks are growing complex, ask yourself: who is the problem, Ansible or me?

I understand the sentiment, but I really don't feel like I am the problem if I don't want so much boilerplate for something as straightforward, repetitive, and ubiquitous as copying files.

The fix is simple, just let the `copy` module create the directory. Afaik permissions will default to the umask of the SSH session, so they might be overly permissive, but I specify the permissions on the files themselves, so an arbitrary user could maybe list my directory but nothing more. If the devs don't want an extra parameter for setting parent dir permissions, I'd say that's OK as long as ansible-lint creates the `risky-file-permissions` warning, as it does when no `mode` is specified for the destination file. Acknowledge the risk by disabling the warning, or restrict the permissions when you really need to by making a separate `file` task.

Design principles on the front page:
* Have an extremely simple setup process with a minimal learning curve.
* Be the easiest IT automation system to use, ever.

My playbook writing experience:
* prototype/iterate my playbook with a mix of ansible and manual edits. Sometimes it just makes sense to use a shell when you're trying to get set up for the first time.
* try to apply my playbook to another machine
* playbook/role fails due to nonexistent directory
* that's annoying, maybe `copy` can do that
* nope, that would add "complexity to the already very complex copy module"
* OK, to avoid this happening again in the future, I need to package every single `copy` task along with an extra `file` task to create a parent directory. maybe ansible provides a radically simple way for me to do that?
* nope, I'm trying too hard. I shouldn't be writing logic in YAML.

### Issue Type

Feature Idea

### Component Name

copy

### Additional Information

I've been writing an apache web server role. When writing my role, I don't want to pigeonhole the user into learning how to use my custom tempates, which surely do not fully encompass the functionality of the apache config file format. I control all the logic surrounding the file copies, but not the files themselves. What am I to do? How is a role supposed to cover a wide range of use cases? If I write tasks for each and every file, now my role is specific to just my system. Want to add a new file? You have to modify the role. The role is cloned from github? Now you're maintaining a fork of the role. 

Here are some workarounds I can think of:

* recreate the remote directory structure locally, then copy the local directory as a whole
    * pro: makes it obvious what the remote destination is just by listing the local directory tree
    * con: the copy module still silences diff output when handling multiple files, despite [the fix](https://github.com/ansible/ansible/pull/81346) patiently waiting to be merged
    * con: still ugly, but at least the ugliness is abstracted inside the role
* create a loop for parent directories, then create a loop for copies
    * con: it's really slow
    * con: still ugly, but at least the ugliness is abstracted inside the role
* let the user specify an arbitrary list of tasks rather than just file paths
    * con: my role no longer controls destination prefix, permissions, handlers 
    * con: it could be literally anything, not just copy
    * con: not intuitive
    * con: now the user is going to create a task list ... in `host_vars`?
 
From a role-writer's perspective, I guess I still can achieve my goals by using one of the above workarounds. From a playbook-writer's perspective, it's plain bad user experience.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/copy.py)
* [`lib/ansible/modules/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/copy.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
> What am I to do? How is a role supposed to cover a wide range of use cases?

Use a loop and create the directories that you need. You already have the user passing in all of the data about the files that they want to copy, so this is very straightforward.

```yaml
    - name: Create parent directories # noqa: risky-file-permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
     loop: "{{ copy_these | map(attribute='dest') | map('dirname') | unique }}"
```

I consider this far less ugly than adding additional error-prone magic to `copy`.

It makes it clear to people reading your code what your intent is, and it makes it clear to people reading the output what directories have been created.
