### ISSUE TITLE
Support state: absent on ansible.builtin.template

### ISSUE THREAD

**Issue by saltyblu** [ansible/ansible#83512]
## description

Support state parameter in `ansible.builtin.template`

## General

Im currently installing multiple versions of packages with different configs handled as ansible templates. 
A seamless update process is also in place, this update needs to remove existing old config "templates".
This needs to be handled via a second file module, what is really hard to maintain and to a lot of unneeded code. 

Also I want to test my roles, therefore a state absent parameter inside the template would make life much easier. 

### Shrink down duplicate file/template declarations

```yml
- name: Ensure template absend if not needed
  ansible.builtin.file:
    path: "{{ crazy_dest}}/awesome.conf"
    state: absent
  when:
    - awesome_config_state == 'absent'

- name: Ensure template
  ansible.builtin.template:
    src: awesome.conf.j2
    dest: "{{ crazy_dest }}//awesome.conf"
    mode: '0644'
    force: false
  when:
    - awesome_config_state == 'present'
```

would lead to:

```yaml
- name: Ensure template
  ansible.builtin.template:
    state: "{{ awesome_config_state }}"
    src: awesome.conf.j2
    dest: "{{ crazy_dest }}//awesome.conf"
    mode: '0644'
    force: false
```
### Ansible run output will be less confusing for "non ansible users"

The ansible tasks includes a lot of "skipped" tasks, that also needs certain configuration of ansible callback plugins.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.template

### Additional Information

```yaml (paste below)
- name: Ensure template
  ansible.builtin.template:
    state: "{{ awesome_config_state }}"
    src: awesome.conf.j2
    dest: "{{ crazy_dest }}//awesome.conf"
    mode: '0644'
    force: false
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
