### ISSUE TITLE
Support slicing based on hostname

### ISSUE THREAD

**Issue by skwde** [ansible/ansible#83533]
### Summary

Support for slicing based on the hostname (and not number of nodes)

E.g. Specifying something like `node[009:012]` should deploy to `node009` to `node012`.

Instead it deploys to `node018` to `node021`.

There is also an old related issue: https://github.com/ansible/ansible/issues/9670

### Issue Type

Feature Idea

### Component Name

playbook host specification

### Additional Information

Use the playbook `test-play.yaml`

```yaml (paste below)
- name: Test stuff
  gather_facts: false
  hosts: node[009:012]

  tasks:
    - name: DEBUG
      ansible.builtin.debug:
        msg: test
```

with the inventory `inventory.yaml`

```yaml
node:
  children:
    cpu:
      hosts:
        node[009:020]
```

and run

```sh
ansible-playbook test-play.yaml -i inventory.yaml 
```

to reproduce above output.

To correctly deploy to the correct hosts in above case one needs to deploy to `node[0:3]` or `node[000:003]`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
