### ISSUE TITLE
path searching for first_found inconsistent with documentation and previous ansible versions

### ISSUE THREAD

**Issue by tolland** [ansible/ansible#83579]
### Summary

When porting some ansible roles to ansible 2.17, it seems that using `with_first_found` from a task in a subdirectory has stopped working (it doesn't find sibling task files in the same directory).

It has been convenient, ever since at least 2.10, to have a tasks directory like so

```
role/
└── tasks
    ├── install
    │   ├── Debian.yml
    │   ├── Linux.yml
    │   └── main.yml
```

And have a `role/tasks/main.yml that calls into it like so:
```yaml
    - name: install packages
      tags: always
      include_tasks: install/main.yml
```

Then in the `tasks/install/main.yml` file, search for a tasks file by specificity, like so;

```yaml
    - include_tasks: "{{ include_install_tasks }}"
      with_first_found:
      - files:
          - "{{ ansible_distribution }}-\
              {{ ansible_distribution_version }}.yml"
          - "{{ ansible_distribution }}-\
              {{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_distribution }}.yml"
          - "{{ ansible_os_family }}.yml"
          - "{{ ansible_system }}.yml"
```          

Would search for `Ubuntu.yml`, then `Debian.yml`, then `Linux.yml` and finally `default.yml` in the `tasks/install` directory and according to my reading of the docs it should. 

e.g. It effectively searches something like this, allowing overriding specific distros with custom tasks:

```yaml
    - include_tasks: "{{ include_install_tasks }}"
      with_first_found:
      - files:
        - Ubuntu.yml
        - Debian.yml
        - Linux.yml
        - default.yml
```

The docs <https://ansible.readthedocs.io/projects/ansible-core/en/stable-2.17/collections/ansible/builtin/first_found_lookup.html#ansible-collections-ansible-builtin-first-found-lookup> say it should look for siblings i the same directory:

> As all lookups, when fed relative paths it will try use the current **task’s location first** and go up the chain to the containing locations of role / play / include and so on.

Also it previously worked in earlier versions of ansible e.g. 2.12 through 2.15. See from my tests below that this starts failing in 2.16

It now produces an error like so:

```
fatal: [testhost]: FAILED! => {}

MSG:

No file was found when using first_found.
```

__

### Issue Type

Bug Report

### Component Name

first_found

### Ansible Version

```console
$ ansible --version


ansible [core 2.17.1]
  config file = /home/user1/.ansible.cfg
  configured module search path = ['/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user1/ansible/venv/lib64/python3.12/site-packages/ansible
  ansible collection location = /home/user1/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user1/ansible/venv/bin/ansible
  python version = 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)] (/home/user1/ansible/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ANSIBLE_NOCOWS(/home/user1/.ansible.cfg) = True
CONFIG_FILE() = /home/user1/.ansible.cfg
DEFAULT_HOST_LIST(/home/user1/.ansible.cfg) = ['/home/user1/ansible/ansible_hosts.yml']
DEFAULT_LOG_PATH(/home/user1/.ansible.cfg) = /home/user1/ansible/log.outman
DEFAULT_ROLES_PATH(/home/user1/.ansible.cfg) = ['/home/user1/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/user1/.ansible.cfg) = debug
DEPRECATION_WARNINGS(/home/user1/.ansible.cfg) = False
EDITOR(env: EDITOR) = /usr/bin/vim
HOST_KEY_CHECKING(/home/user1/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/user1/.ansible.cfg) = auto_silent
PAGER(env: PAGER) = /usr/bin/less -X -r
RETRY_FILES_ENABLED(/home/user1/.ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/user1/.ansible.cfg) = False

ssh:
___
control_path(/home/user1/.ansible.cfg) = %(directory)s/%%h-%%p-%%r
host_key_checking(/home/user1/.ansible.cfg) = False

SHELL:
=====

sh:
__
world_readable_temp(/home/user1/.ansible.cfg) = True
```

### OS / Environment

    Operating System: Fedora Linux 40 (Workstation Edition)

### Steps to Reproduce

This repo contains a playbook.yml and role which exercise the above functionality, and run it against increasing versions of ansible <https://github.com/tolland/test_ansible_role1> it can be used to show where the regressions happened.

But generally, using this block in a subdirectory of tasks, i.e. `tasks/install/main.yml` should search in `tasks/install` for tasks of increasing specificity e.g. `Ubuntu-20.yml`,... `Debian.yml`, finally `Linux.yml` in the same directory as `main.yml`. however it produces an error with 2.17

```yaml
- tags: [ test-install ]
  block:
    - name: call the distro specific tasks
      tags: always
      include_tasks: "{{ include_install_tasks }}"
      with_first_found:
      - files:
          - "{{ ansible_distribution }}-\
              {{ ansible_distribution_version }}.yml"
          - "{{ ansible_distribution }}-\
              {{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_distribution }}.yml"
          - "{{ ansible_os_family }}.yml"
          - "{{ ansible_system }}.yml"
      loop_control:
        loop_var: include_install_tasks

```

### Expected Results

I expect the tasks subdirectory to be searched first

### Actual Results

```console
fatal: [test]: FAILED! => {}

MSG:

No file was found when using first_found.
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
