### ISSUE TITLE
Unexpected behaviour when applying `copy` to vaulted variable

### ISSUE THREAD

**Issue by bertptrs** [ansible/ansible#83590]
### Summary

When I use the `ansible.builtin.copy` module with an encrypted value, the value is inconsistently decrypted depending on various circumstances.

### Issue Type

Bug Report

### Component Name

ansible.builtin.copy

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.4]
  config file = REDACTED/ansible/ansible.cfg
  configured module search path = ['REDACTED/ansible/modules']
  ansible python module location = /nix/store/18bjvmjpn468ql6g7ji75cgkqghxnpvx-python3.11-ansible-core-2.16.4/lib/python3.11/site-packages/ansible
  ansible collection location = /home/bert/.ansible/collections:/usr/share/ansible/collections
  executable location = /nix/store/18bjvmjpn468ql6g7ji75cgkqghxnpvx-python3.11-ansible-core-2.16.4/bin/ansible
  python version = 3.11.8 (main, Feb  6 2024, 21:21:21) [GCC 13.2.0] (/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_VAULT_PASSWORD_FILE(/home/bert/Documents/ansible-repro/ansible.cfg) = /home/bert/Documents/ansible-repro/vault-pass

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

config:
______
_terms(None) = None

dict:
____
_terms(None) = None

env:
___
_terms(None) = None

file:
____
_terms(None) = None

fileglob:
________
_terms(None) = None

indexed_items:
_____________
_terms(None) = None

ini:
___
_terms(None) = N
```

### OS / Environment

Ubuntu/NixOS

### Steps to Reproduce

Apply the following playbook:

```yaml (paste below)
---
- hosts: localhost
  vars:
    my_value:
      my_secret: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              30343733626635623263373433643933613832373939623833653566313962383039393062306161
              6638346238643631656162383063333732616165633866610a616537383865316464383834663035
              36333732346635636634393732376239343030623363326635323837303933613434333233303965
              3339646331353436630a376533313837323162383462336536326466663338386562386565383037
              3163


    my_wrapper:
      secrets: "{{ my_value }}"
  tasks:
    - ansible.builtin.copy:
        dest: "/tmp/secret.yml"
        content: "{{ my_value | to_nice_yaml }}"

    - ansible.builtin.copy:
        dest: "/tmp/visible.yml"
        content: "{{ my_wrapper | to_nice_yaml }}"
```

The vault password is `password`.

### Expected Results

I expect the secret word to be decrypted in both of the files created in `/tmp`, but is decrypted only in one of them.

### Actual Results

In `/tmp/secret.yml`:

```yaml
my_secret: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30343733626635623263373433643933613832373939623833653566313962383039393062306161
    6638346238643631656162383063333732616165633866610a616537383865316464383834663035
    36333732346635636634393732376239343030623363326635323837303933613434333233303965
    3339646331353436630a376533313837323162383462336536326466663338386562386565383037
    3163
```

While in `/tmp/visible.yml`:

```yaml
secrets:
    my_secret: test
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
