### ISSUE TITLE
validate-modules test: does not notice if alias is added to the wrong option in documentation

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#83598]
### Summary

Assume you have two options, `foo` and `bar`, where `bar` has an alias `bam`:
```py
module = AnsibleModule(dict(foo=dict(), bar=dict(aliases=['bam'])))
```
Now assume the documenation looks like:
```yaml
DOCUMENTATION = """
options:
  foo:
    description: Foo.
    type: str
    aliases: [ bam ]
  bar:
    description: Bar.
    type: str
"""
```
Right now, the validate-modules test will not notice that `bam` has been added to `aliases` of the wrong option.

(I found this while looking into https://github.com/CiscoDevNet/ansible-mso/issues/489#issuecomment-2226865962)

### Issue Type

Bug Report

### Component Name

ansible-test validate-modules

### Ansible Version

```console
devel
```

### Configuration

```console
-
```

### OS / Environment

-

### Steps to Reproduce

See above

### Expected Results

Sanity test fails

### Actual Results

```console
Sanity test passes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
