### ISSUE TITLE
`/usr/bin/env python3: not found` when using as a Shebang in a module

### ISSUE THREAD

**Issue by mabezi** [ansible/ansible#83603]
### Summary

We have a self-written module that is supposed to automatically determine the management IP (and a few other parameters) of our Ansible hosts when running a playbook.

In this module we use `/usr/bin/env python3` as the shebang, so that a static path to a Python installation does not have to be specified. (for example to use a venv)

Since the last update, I have noticed that using this shebang leads to an error message. And since the use of `/usr/bin/env` makes sense in my opinion and because I don't think that this is intentional, I assume it is a bug.

### Issue Type

Bug Report

### Component Name

python module

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.1]
  config file = /home/.../Ansible/ansible.cfg
  configured module search path = ['/home/.../Ansible/library']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/.../Ansible/.ansible/galaxy
  executable location = /usr/bin/ansible
  python version = 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ANSIBLE_NOCOWS(/home/.../Ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/.../Ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/home/.../Ansible/ansible.cfg) = ['/home/.../Ansible/.ansible/galaxy']
CONFIG_FILE() = /home/.../Ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/.../Ansible/ansible.cfg) = ['/home/.../Ansible/production']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/.../Ansible/ansible.cfg) = True
DEFAULT_MODULE_PATH(/home/.../Ansible/ansible.cfg) = ['/home/.../Ansible/library']
DEFAULT_ROLES_PATH(/home/.../Ansible/ansible.cfg) = ['/home/.../Ansible/.ansible/galaxy/roles']
DEFAULT_STDOUT_CALLBACK(/home/.../Ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/.../Ansible/ansible.cfg) = 20
EDITOR(env: EDITOR) = nano
INTERPRETER_PYTHON(/home/.../Ansible/ansible.cfg) = auto_silent
USE_PERSISTENT_CONNECTIONS(/home/.../Ansible/ansible.cfg) = True

CONNECTION:
==========

local:
_____
pipelining(/home/.../Ansible/ansible.cfg) = True

paramiko_ssh:
____________
ssh_args(/home/.../Ansible/ansible.cfg) = -F ssh_config -o ControlMaster=auto -o ControlPersist=60s
timeout(/home/.../Ansible/ansible.cfg) = 20
use_persistent_connections(/home/.../Ansible/ansible.cfg) = True

psrp:
____
pipelining(/home/.../Ansible/ansible.cfg) = True

ssh:
___
pipelining(/home/.../Ansible/ansible.cfg) = True
ssh_args(/home/.../Ansible/ansible.cfg) = -F ssh_config -o ControlMaster=auto -o ControlPersist=60s
timeout(/home/.../Ansible/ansible.cfg) = 20

winrm:
_____
pipelining(/home/.../Ansible/ansible.cfg) = True
```

### OS / Environment

Manjaro Linux 24.0.3

### Steps to Reproduce

`preamble.yml`
```yaml
---
- name: Ensure facts are gathered
  hosts: "{{ preamble_hosts }}"
  become: true
  tags: [always, ip_facts]
  gather_facts: true

- name: check ansible requirements
  hosts: "{{ preamble_hosts }}"
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Verify Ansible meets version requirements.
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.4', '>=')
        msg: "You must update Ansible to at least 2.4 to use this playbook."
      run_once: true  # noqa: run-once[task]
  tags: [always]

# Gather ip_facts for all hosts before anything else
- name: gather ip facts
  hosts: "{{ preamble_hosts }}, !static_mgmt_ip"
  become: true
  tags: [always, ip_facts]
  gather_facts: false
  pre_tasks:
    - name: Gather IP facts
      ip_facts:
        mgmt_ipv4: "{{ ansible_ipv4_management | default('None') }}"
      when: not ansible_ip_facts_gathered | default(False)
```

example module where i got this error:
```python
#!/usr/bin/env python3
# -*- coding: utf-8; -*-

from ansible.module_utils.basic import AnsibleModule

def main():
    module_args = dict(
        mgmt_ipv4=dict(type='str', required=True)
    )

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    facts = {} 

    facts['ansible_ip_facts_gathered'] = True

    module.exit_json(msg="ok", ansible_facts=facts)


if __name__ == '__main__':
    main()
```

### Expected Results

No error message should appear.

### Actual Results

```console
$ ansible-playbook -i production site.yml --diff -l example.org -e preamble_hosts="example.org"

PLAY [Ensure facts are gathered] *********************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************
ok: [example.org]

PLAY [check ansible requirements] ********************************************************************************************************

TASK [Verify Ansible meets version requirements.] ****************************************************************************************
ok: [example.org] => changed=false 
  msg: All assertions passed

PLAY [gather ip facts] *******************************************************************************************************************

TASK [Gather IP facts] *******************************************************************************************************************
fatal: [example.org]: FAILED! => changed=false 
  module_stderr: |-
    /bin/sh: 1: /usr/bin/env python3: not found
  module_stdout: ''
  msg: |-
    The module failed to execute correctly, you probably need to set the interpreter.
    See stdout/stderr for the exact error
  rc: 127

PLAY RECAP *******************************************************************************************************************************
example.org    : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
