### ISSUE TITLE
Unable to configure url credentials for private collection installed by url

### ISSUE THREAD

**Issue by fbartnitzek** [ansible/ansible#83623]
### Summary

I try to install a collection from an private https-fileserver, as described for roles [in the docs](https://cn-ansibledoc.readthedocs.io/zh-cn/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file).

To not include the authentication-credentials in the `requirements.yml` file, I would like to configure those in the `ansible.cfg` file and found a matching paragraph in the [galaxy-client docs](https://docs.ansible.com/ansible/2.9/user_guide/collections_using.html#configuring-the-ansible-galaxy-client).

But this configuration doesn't work for https-fileservers.

### Issue Type

Feature Request

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.2]
  config file = /Users/frankbartnitzek/tmp/ansible-issue/ansible.cfg
  configured module search path = ['/Users/frankbartnitzek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/frankbartnitzek/tmp/ansible-issue/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/frankbartnitzek/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/frankbartnitzek/tmp/ansible-issue/.venv/bin/ansible
  python version = 3.12.3 (main, Apr 12 2024, 17:16:04) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/Users/frankbartnitzek/tmp/ansible-issue/.venv/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /Users/frankbartnitzek/tmp/ansible-issue/ansible.cfg
GALAXY_SERVER_LIST(/Users/frankbartnitzek/tmp/ansible-issue/ansible.cfg) = ['dacoso']
```

### OS / Environment

```
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
```

### Steps to Reproduce

If I store the fileserver-credentials into an `ansible.cfg` file:

```
[galaxy]
server_list = dacoso

[galaxy_server.dacoso]
url=https://MY_HOST
username=MY_USER
password=MY_TOKEN
```

And declare the requirements without credentials in `requirements.yml`:

```yaml
collections:
  - name: dacoso.connection_reports
    type: url
    source: https://MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz
```

The authentication against the fileserver fails.

### Expected Results

I expect that the ansible-galaxy client in the `ansible.cfg` file also supports a fileserver with username + password/token authentication.

With an `requirements_with_credentials.yml` exposing the credentials in the source-url:

```yaml
collections:
  - name: dacoso.connection_reports
    type: url
    source: https://MY_USER:MY_TOKEN@MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz
```

The installation of the collection works as expected:

```sh
$ ansible-galaxy install -r requirements_with_credentials.yml
Downloading https://MY_USER:MY_TOKEN@MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz to /Users/frankbartnitzek/.ansible/tmp/ansible-local-12889g9yxe5qv/tmpbk2cwvvf/dacoso-connection_reports-1.0.1-rl953_6y
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'dacoso.connection_reports:1.0.1' to '/Users/frankbartnitzek/.ansible/collections/ansible_collections/dacoso/connection_reports'
dacoso.connection_reports:1.0.1 was installed successfully
```

### Actual Results

```console
$ ansible-galaxy install -r requirements.yml -vvvv
ansible-galaxy [core 2.17.2]
  config file = /Users/frankbartnitzek/tmp/ansible-issue/ansible.cfg
  configured module search path = ['/Users/frankbartnitzek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/frankbartnitzek/tmp/ansible-issue/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/frankbartnitzek/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/frankbartnitzek/tmp/ansible-issue/.venv/bin/ansible-galaxy
  python version = 3.12.3 (main, Apr 12 2024, 17:16:04) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/Users/frankbartnitzek/tmp/ansible-issue/.venv/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
Using /Users/frankbartnitzek/tmp/ansible-issue/ansible.cfg as config file
Reading requirement file at '/Users/frankbartnitzek/tmp/ansible-issue/requirements.yml'
Collection requirement 'dacoso.connection_reports' is a URL to a tar artifact
Downloading https://MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz to /Users/frankbartnitzek/.ansible/tmp/ansible-local-605343zbi_7bo/tmpzlphvfjz/dacoso-connection_reports-1.0.1-w_do_yrj
ERROR! Failed to download collection tar from 'https://MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz': HTTP Error 401: . HTTP Error 401:

# statuscode 401 hides the existence of non-authorized resources
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`bin/ansible-galaxy`](https://github.com/ansible/ansible/blob/devel/bin/ansible-galaxy)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by s-hertel** [comment]
The requirements.yml isn't valid syntax and it is a bug that isn't a clear error. `source` is the URL of a Galaxy server, not a URL to an individual collection. The expected syntax is:

```
collections:
  - name: dacoso.connection_reports
    type: galaxy  # optional
    source: https://MY_HOST
```

> I try to install a collection from an private https-fileserver, as described for roles [in the docs](https://cn-ansibledoc.readthedocs.io/zh-cn/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file).

For format for role and collection requirements is different. This is the collection documentation https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html#install-multiple-collections-with-a-requirements-file.

**Comment by fbartnitzek** [comment]
Thanks for the immediate response.

You are right, the documentation mentions all supported types in this section:
`The type key can be set to file, galaxy, git, url, dir, or subdirs. If type is omitted, the name key is used to implicitly determine the source of the collection.`

But I found no hint, how to use the type `url` correctly.
So with a bit of trial & error and the [role-documentation](https://cn-ansibledoc.readthedocs.io/zh-cn/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file), I came up with the above solution.

What would be the right way to use the type `url` for a collection?
And can we configure the authentication credentials for the url somewhere except in the url?

**Comment by s-hertel** [comment]
These requirements are all equivalent ways of installing a collection from a URL:
```
collections:
  - https://MY_USER:MY_TOKEN@MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz
  - name: https://MY_USER:MY_TOKEN@MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz
  - name: https://MY_USER:MY_TOKEN@MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz
    type: url
```
which is equivalent to `ansible-galaxy collection install https://MY_USER:MY_TOKEN@MY_HOST/MY_PATH/connection_reports/dacoso-connection_reports-1.0.1.tar.gz`.

There is no way to configure credentials for URLs so this would be a feature.
