### ISSUE TITLE
Setting a mac address in a docker_container isnt respected

### ISSUE THREAD

**Issue by bdeluca** [ansible/ansible#83631]
### Summary

When I try and create a container and specify the mac address the mac address request is not respected. 

earlier discussion started here -> https://forum.ansible.com/t/setting-a-mac-address-in-a-docker-container/7315/2

### Issue Type

Bug Report

### Component Name

docker

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.1]
  config file = None
  configured module search path = ['/home/myname/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myname/miniconda3/envs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/myname/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/myname/miniconda3/envs/ansible/bin/ansible
  python version = 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (/home/myname/miniconda3/envs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
[WARNING]: Ansible is being run in a world writable directory (/mnt/d/work/companyname-code/infra/infrastructure), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-
world-writable-dir
CONFIG_FILE() = None

Hi, I am on windows in a vm reading from a windows dir (hence the world writeable directory)
```

### OS / Environment

target:
cat /etc/redhat-release
Rocky Linux release 9.4 (Blue Onyx)

docker -vv
Docker version 27.0.3, build 7d4bcd8

client is ubuntu latest. 

### Steps to Reproduce

Ansible playbook
```
 ---
  - hosts: my-host
    tasks:
      - name: Pull the latest Ubuntu image
        docker_image:
          name: ubuntu
          tag: latest
          source: pull
      - name: Create a custom Docker network
        docker_network:
          name: custom_network
          driver: bridge
      - name: Create a Docker container with a specific MAC address
        docker_container:
          name: my_container
          image: ubuntu:latest
          state: started
          networks:
            - name: custom_network
              mac_address: "02:42:ac:11:65:43"
          command: /bin/bash -c "while true; do sleep 1000; done"
```

### Expected Results

I would expect, to have the specified mac address not

### Actual Results

```console
docker inspect my_container | grep MacAddress
            "MacAddress": "",
                    "MacAddress": "02:42:ac:12:00:02",
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
