### ISSUE TITLE
ansible.builtin.sh add docs for shell plugin parameter usage

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#83646]
### Summary

Please add documentation for how shell plugin parameters have to be specified.
E.g. How would one specify the environment parameter of ansible.builtin.sh?

Example use case for this one, using add_host and wanting to overwrite e.g. PATH with a different value so that execution further down in the playbook happens successfully when the remote either has a broken or undesired PATH e.g. like often found in docker containers.

### Issue Type

Documentation Report

### Component Name

lib/ansible/plugins/shell/sh.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.2]
  config file = /home/user/git/ansible-main-server/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/git/ansible-main-server/venv/lib/python3.12/site-packages/ansible
  ansible collection location = /home/user/git/ansible-main-server
  executable location = /home/user/git/ansible-main-server/venv/bin/ansible
  python version = 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] (/home/user/git/ansible-main-server/venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

ArchLinux

### Additional Information

-

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/shell/sh.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/shell/sh.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by bcoca** [comment]
As docs show:
```
  environment:
    type: list
    elements: dictionary
    default: [{}]
    description:
      - List of dictionaries of environment variables and their values to use when executing commands.
    keyword:
      - name: environment
```

The `environment` keyword in a play sets it.
