### ISSUE TITLE
Unable to upload zip.bin file using uri module correctly

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#83645]
### Summary

Im trying to upload a zip.bin file using the uri module and for some reason it is changing the file type from the correct file type which is binay "data" to ASCII.

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible==10.2.0
ansible-core==2.17.2
python version = 3.10.8
jinja version = 3.1.2
libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

runing playbooks using macos with venv, files are on a remote linux ubuntu servers Ubuntu 20.04.3 LTS

### Steps to Reproduce

```yaml (paste below)
  - name: upload using uri
    uri: 
      url: "https://127.0.0.1:8080/uploads"
      headers:
        Authorization: "Bearer {{ login.json.access_token }}"
        Accept: application/json
        Content-Type: application/octet-stream
      validate_certs: no
      body_format: form-multipart
      force_basic_auth: yes
      method: POST
      timeout: 1200
      remote_src: yes
      use_proxy: false
      decompress: false
      return_content: true
      body:
        in_file:
            filename: /home/user/files/{{ item.key }}.zip.bin
    loop: "{{ template | dict2items }}"

```

### Expected Results

The expected result is for the uri module to upload the file as is and not decompress it or whatever is happening to the file
using curl and shell module is working fine, when i convert it to uri file type issue started.

'''
   - name: install  via shell
     shell: "curl -k --fail --connect-timeout 1 --max-time 1200 -X \"POST\" \"https://127.0.0.1:8080/uploads\" -H \"Authorization: Bearer {{ login.json.access_token }}\" -H \"Content-Type: multipart/form-data\" -F \"in_file=@/home/user/files/{{ item.key }}.zip.bin\""
     loop: "{{ template|dict2items }}"
'''

With that file type is binary and of type "data"

### Actual Results

```console
in the file that is Posted using the shell curl module i see file size is smaller, file type is DATA and file inside looks binary.(correct behavior)
with URI module file size is bigger, file type is ASCII and file inside containing big letters and readable.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
