### ISSUE TITLE
java_cert gets stuck waiting for user prompt when keystore_pass contains empty string

### ISSUE THREAD

**Issue by Cajova-Houba** [ansible/ansible#83658]
### Summary

When I try to import a CA to cacerts keystore with empty password (""), the java_cert module gets stuck waiting for user prompt. I'm using the collection community.general v 9.2.0.

### Issue Type

Bug Report

### Component Name

java_cert

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
ERROR_ON_MISSING_HANDLER(/home/runner/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/runner/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/runner/.ansible.cfg) = 60

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/runner/.ansible.cfg) = False
ssh_args(/home/runner/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s

ssh:
___
host_key_checking(/home/runner/.ansible.cfg) = False
pipelining(/home/runner/.ansible.cfg) = True
ssh_args(/home/runner/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

sh:
__
remote_tmp(/home/runner/.ansible.cfg) = /tmp

VARS:
====
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
- name: Import custom CA
  community.general.java_cert:
    cert_path: "/opt/ca.crt"
    keystore_path: "/opt/java/lib/security/cacerts"
    keystore_pass: ""
    keystore_create: false
    state: present
    cert_alias: "test_CA"
    trust_cacert: true
    executable: "/opt/java/bin/keytool"
```

### Expected Results

Certificate from file `/opt/ca.crt` gets imported into the `/opt/java/lib/security/cacerts`.

### Actual Results

```console
Ansible gets stuck on the task `Import custom CA` because it is waiting for user prompt.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
