### ISSUE TITLE
ansible.builtin.uri reports broken pipe instead of server's response during PUT operation

### ISSUE THREAD

**Issue by cnyk** [ansible/ansible#83669]
### Summary

When uploading large files (HTTP PUT) to Jfrog's Artifactory, Ansible fails with fatal error "-1, broken pipe". It looks like Artifactory is behaving a little weird, but as far as I understand, not outside of RFC 9110 specifications. What happens is that the server is closing the connection some 3–5 seconds after the upload starts, and Ansible does not know how to handle this kind of behaviour. The closing of connection with 403 is expected from the server, but the uri module mishandles the response. I had a little dig inside the python side of things, and my guess is that the actual issue is in the python side (the uri module uses urllib.Request under the hood), but I'm not 100% sure how to continue here.

### Issue Type

Bug Report

### Component Name

ansible.builtin.uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.1]
  config file = *CENSORED*/ansible.cfg
  configured module search path = ['*CENSORED*/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = *CENSORED PYTHON VENV PATH*/lib/python3.12/site-packages/ansible
  ansible collection location = *CENSORED*/.ansible/collections:/usr/share/ansible/collections
  executable location = *CENSORED PYTHON VENV PATH*/bin/ansible
  python version = 3.12.3 (macOS)
  jinja version = 3.1.3
  libyaml = True

### Same behaviour with ansible 2.15, python 3.9 from RHEL 8, and 9 ###
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = *CENSORED CWD*/ansible.cfg
DEFAULT_BECOME_METHOD(*CENSORED CWD*/ansible.cfg) = sudo
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
DEFAULT_ROLES_PATH(*CENSORED CWD*/ansible.cfg) = ['*CENSORED CWD*/roles']
```

### OS / Environment

MacOS, RHEL 8, RHEL 9

### Steps to Reproduce

```yaml (paste below)
- name: 06. Import file into Artifactory
  ansible.builtin.uri:
    url: "{{ server_url }}/{{ repo }}/{{ upload_path }}/{{ file_name }}"
    method: PUT
    src: "{{ file_path }}/{{ file_name }}"
    force_basic_auth: true
    return_content: true
    user: "{{ auth_username }}"
    password: "{{ auth_password }}"
    status_code:
      - 201
      - 403
    timeout: 3600
    remote_src: true

```

### Expected Results

```console
ok: [localhost] => {
    "changed": false,
    "connection": "close",
    "content": "{\n  \"errors\" : [ {\n    \"status\" : 403,\n    \"message\" : \"*CENSORED VALID RESON TO REFUSE UPLOAD*\"\n  } ]\n}",
    "content_type": "application/json;charset=ISO-8859-1",
    "date": "Thu, 25 Jul 2024 11:18:49 GMT",
    "elapsed": 0,
...
    "json": {
        "errors": [
            {
                "message": "*CENSORED VALID RESON TO REFUSE UPLOAD*",
                "status": 403
            }
        ]
    },
    "msg": "HTTP Error 403: ",
    "redirected": false,
    "set_cookie": "*CENSORED*",
    "status": 403,
    "transfer_encoding": "chunked",
    "url": "*CENSORED*",

}
```

### Actual Results

```console
fatal: [localhost]: FAILED! => {
    "changed": false,
    "content": "",
    "elapsed": 1,
...
    "msg": "Status code was -1 and not [201, 403]: Request failed: <urlopen error EOF occurred in violation of protocol (_ssl.c:2406)>",
    "redirected": false,
    "status": -1,
    "url": "*CENSORED*"
}

Ansible fails with broken pipe error. It looks like the server initially permits the upload, but during the upload process it returns a 403 and promptly closes the connection. This only happens if the file is large enough so that the transfer takes more than 5 seconds
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
