### ISSUE TITLE
When using ansible.builtin.get_url the regex only uses "attachment" in the regex, 

### ISSUE THREAD

**Issue by budgester** [ansible/ansible#83690]
### Summary

When trying to download a VSCode extension from the marketplace the Content-Disposition header is not recognised in the regex meaning the name value is not used.

### Issue Type

Bug Report

### Component Name

get_url

### Ansible Version

```console
$ ansible --version

ansible [core 2.17.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/budgester/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/budgester/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/budgester/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/budgester/venv/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/home/budgester/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

RHEL9

### Steps to Reproduce

Example - https://marketplace.visualstudio.com/items?itemName=redhat.ansible

```
---                                                                                                 
- name: Download                                                                                    
  hosts: localhost                                                                                  
  gather_facts: false                                                                               
  tasks:                                                                                            
    - name: Download                                                                                
      ansible.builtin.get_url:                                                                      
        url: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/ansible/24.9.2928907/vspackage
        dest: /tmp/                                                 
        decompress: true
```

The file is downloaded as vspackage, but the Content-Dispostion header is 

`inline; filename=redhat.ansible-24.9.2928907.vsix; filename*=utf-8''redhat.ansible-24.9.2928907.vsix`

So the file should be saved as `redhat.ansible-24.9.2928907.vsix`

The regex in the module is below and will only detect attachments not inline

`cont_disp_regex = 'attachment; ?filename="?([^"]+)'`

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/get_url.py#L447

### Expected Results

Expected file to download as `redhat.ansible-24.9.2928907.vsix`

### Actual Results

```console
File downloaded as `vspackage`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
The [`uri`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html) module handles the request correctly:
```yaml
- uri:                                                                      
    url: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/ansible/24.9.2928907/vspackage
    dest: /tmp/                                                 
    decompress: true
```
