### ISSUE TITLE
ansible.builtin.success reports that skipped tasks completed successfully

### ISSUE THREAD

**Issue by rptaylor** [ansible/ansible#83698]
### Summary

The `ansible.builtin.success` test reports true for skipped tasks.

Even if this is somehow the intended behaviour it is still a serious documentation bug.
If not doing a task at all is somehow meant to be interpreted as completing a task successfully then any reference to "completed", "finished", or "success" should be removed from [the docs](
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/success_test.html).

### Issue Type

Bug Report

### Component Name

ansible.builtin.success

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/fedora/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/fedora/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 14.0.1 20240217 (Red Hat 14.0.1-0)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True


$ rpm -q ansible
ansible-9.8.0-1.fc40.noarch
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = /usr/bin/nano
```

### OS / Environment

Fedora 40

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  tasks:
    - name: Do something really important but it might be skipped
      ansible.builtin.reboot:
      register: thing
      when: false

    - name: Print result
      debug:
        msg: "Actually that really important thing definitely completed successfully"
      when: thing is ansible.builtin.success

```

### Expected Results

The task is skipped. It did not complete successfully so the `success` test must not return true.

### Actual Results

```console
$ ansible-playbook test.yml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [localhost]

TASK [Do something really important but it might be skipped] ****************************************************************************************************************
skipping: [localhost]

TASK [Print result] *********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Actually that really important thing definitely completed successfully"
}

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
