### ISSUE TITLE
Find module behaves inconsistently with depth 1

### ISSUE THREAD

**Issue by slarti-b** [ansible/ansible#83709]
### Summary

Was using the find module to find files and directories in a given directory.  If I use find with `recurse: false` I get what I expect.  If I use find with `depth: 1` then I get what I expect _if the path given does not end with a `/`_.  However, if the path given ends with a `/` then it does not find anything at all.

I would expect the same results in both cases.  The command line find command behaves the same in both cases.  Also, the [documentation for the find](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/find_module.html#parameter-depth) module, when describing the `depth` parameter, says

> Setting recurse to false will override this value, which is effectively depth 1.

So I expect both to be the same

### Issue Type

Bug Report

### Component Name

find

### Ansible Version

```console
$ ansible --version
2.9.27
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/opt/ansible/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
```

### OS / Environment

CentOS 7

### Steps to Reproduce

Simply run the following playbook
```yaml (paste below)
- hosts: localhost
  tasks:
    - name: Create folders
      file:
        path: "/tmp/{{ item }}"
        state: directory
      loop:
        - 'foo'
        - 'foo/bar'
        - 'foo/baz'
    - name: Create files
      file:
        path: "/tmp/foo/{{ item }}"
        state: touch
      loop:
        - 'a'
        - 'b'
        - 'bar/m'
        - 'baz/x'
        - 'baz/y'
        - 'baz/z'

    - name: Find things in /tmp/foo
      find:
        paths: '/tmp/foo'
        depth: 1
        file_type: any
        hidden: true
      register: result_without_slash_max_depth_one

    - name: Show files found
      debug:
        var: files
      vars:
        files: "{{ result_without_slash_max_depth_one.files | map(attribute='path') | list }}"

    - name: Find things in /tmp/foo/
      find:
        paths: '/tmp/foo/'
        depth: 1
        file_type: any
        hidden: true
      register: result_with_slash_max_depth_one

    - name: Show files found
      debug:
        var: files
      vars:
        files: "{{ result_with_slash_max_depth_one.files | map(attribute='path') | list }}"

    - name: Find things in /tmp/foo
      find:
        paths: '/tmp/foo'
        recurse: false
        file_type: any
        hidden: true
      register: result_without_slash

    - name: Show files found
      debug:
        var: files
      vars:
        files: "{{ result_without_slash.files | map(attribute='path') | list }}"

    - name: Find things in /tmp/foo/
      find:
        paths: '/tmp/foo/'
        recurse: false
        file_type: any
        hidden: true
      register: result_with_slash

    - name: Show files found
      debug:
        var: files
      vars:
        files: "{{ result_with_slash.files | map(attribute='path') | list }}"

```

### Expected Results

I expected all four debug statements to output the same list of files as each other.  If I edit what I got, to show what I expected, it would be
```
TASK [Find things in /tmp/foo] *******************************************************************************************************
ok: [localhost]

TASK [Show files found] **************************************************************************************************************
ok: [localhost] => {
    "files": [
        "/tmp/foo/a",
        "/tmp/foo/b",
        "/tmp/foo/bar",
        "/tmp/foo/baz"
    ]
}

TASK [Find things in /tmp/foo/] ******************************************************************************************************
ok: [localhost]

TASK [Show files found] **************************************************************************************************************
ok: [localhost] => {
    "files": [
        "/tmp/foo/a",
        "/tmp/foo/b",
        "/tmp/foo/bar",
        "/tmp/foo/baz"
    ]
}

TASK [Find things in /tmp/foo] *******************************************************************************************************
ok: [localhost]

TASK [Show files found] **************************************************************************************************************
ok: [localhost] => {
    "files": [
        "/tmp/foo/a",
        "/tmp/foo/b",
        "/tmp/foo/bar",
        "/tmp/foo/baz"
    ]
}

TASK [Find things in /tmp/foo/] ******************************************************************************************************
ok: [localhost]

TASK [Show files found] **************************************************************************************************************
ok: [localhost] => {
    "files": [
        "/tmp/foo/a",
        "/tmp/foo/b",
        "/tmp/foo/bar",
        "/tmp/foo/baz"
    ]
}
```

### Actual Results

```console
TASK [Find things in /tmp/foo] *******************************************************************************************************
ok: [localhost]

TASK [Show files found] **************************************************************************************************************
ok: [localhost] => {
    "files": [
        "/tmp/foo/a",
        "/tmp/foo/b",
        "/tmp/foo/bar",
        "/tmp/foo/baz"
    ]
}

TASK [Find things in /tmp/foo/] ******************************************************************************************************
ok: [localhost]

TASK [Show files found] **************************************************************************************************************
ok: [localhost] => {
    "files": []
}

TASK [Find things in /tmp/foo] *******************************************************************************************************
ok: [localhost]

TASK [Show files found] **************************************************************************************************************
ok: [localhost] => {
    "files": [
        "/tmp/foo/a",
        "/tmp/foo/b",
        "/tmp/foo/bar",
        "/tmp/foo/baz"
    ]
}

TASK [Find things in /tmp/foo/] ******************************************************************************************************
ok: [localhost]

TASK [Show files found] **************************************************************************************************************
ok: [localhost] => {
    "files": [
        "/tmp/foo/a",
        "/tmp/foo/b",
        "/tmp/foo/bar",
        "/tmp/foo/baz"
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
