### ISSUE TITLE
ansible.builtin.group does not diagnose absence of group as specified

### ISSUE THREAD

**Issue by pabigot** [ansible/ansible#83728]
### Summary

When I attempt to ensure a group named `tftp` with gid 127 is present, ansible does not diagnose the fact that gid 127 is present but with a different name.

This is operationally similar to #76774 (except that I'm not getting the error mentioned in that issue), but IMO it's a bug rather than absence of a rename feature, because when I say I want a `tftp:127` in /etc/group, I should be told that this isn't what's actually there.

### Issue Type

Bug Report

### Component Name

ansible.builtin.group

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.1]
  config file = None
  configured module search path = ['/home/pbigot/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pipx/venvs/ansible-dev-tools/lib/python3.10/site-packages/ansible
  ansible collection location = /home/pbigot/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/opt/pipx/venvs/ansible-dev-tools/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
DEFAULT_VAULT_IDENTITY_LIST(env: ANSIBLE_VAULT_IDENTITY_LIST) = ['hwadmin@/usr/local/bin/keyctl-client']
EDITOR(env: EDITOR) = /bin/vi
PAGER(env: PAGER) = less
```

### OS / Environment

Debian 12.6

### Steps to Reproduce

```yaml (paste below)
- name: Run the test play
  hosts: all # restricted by -l/--limit
  become: true
  tasks:
    - name: Pre-configure groups referenced in LDAP
      ansible.builtin.group:
        name: tftp
        gid: 127
        state: present
      register: rc
    - name: Show results
      ansible.builtin.debug:
        var: rc
```

when

```
pab@hwscli1:~$  egrep 'tftp|:127:' /etc/group
Debian-exim:x:127:
```

### Expected Results

The task should fail because it did not leave the system configured with a group named `tftp` with group number 127.

### Actual Results

```console
TASK [Pre-configure groups referenced in LDAP] *********************************************************************
ok: [hwscli1]

TASK [Show results] ************************************************************************************************
ok: [hwscli1] => {
    "rc": {
        "changed": false,
        "failed": false,
        "gid": 127,
        "name": "tftp",
        "state": "present",
        "system": false
    }
}

PLAY RECAP *********************************************************************************************************
hwscli1                    : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
