### ISSUE TITLE
ansible.builtin.ini lookup doesn't take '%' chars in value as a literal

### ISSUE THREAD

**Issue by djasa** [ansible/ansible#83755]
### Summary

`ansible.builtin.ini` filter doesn't treat the option value as a raw string, `%` chars are treated as formatting chars

### Issue Type

Bug Report

### Component Name

lib/ansible/plugins/lookup/ini.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/djasa/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/djasa/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.0rc1 (main, Aug  6 2024, 00:00:00) [GCC 14.1.1 20240701 (Red Hat 14.1.1-7)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = vim
```

### OS / Environment

Fedora rawhide/41

### Steps to Reproduce

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.debug:
        msg: "Name val is: {{ lookup('ansible.builtin.ini', 'Name', section='Desktop Action new-window', file='org.mozilla.firefox.desktop') }}"

    - ansible.builtin.debug:
        msg: "Exec val is: {{ lookup('ansible.builtin.ini', 'Exec', section='Desktop Action new-window', file='org.mozilla.firefox.desktop') }}"
```

test ini file adapted from Firefox Flatpak desktop file:
```ini
[Desktop Action new-window]
Name=Open a New Window
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=firefox --file-forwarding org.mozilla.firefox --new-window @@u %u @@
```

### Expected Results

Both values should be printed verbatim:
```
$ ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook ansible-ini-filter.yaml

PLAY [localhost] **********************************************************************************
TASK [ansible.builtin.debug] **********************************************************************
ok: [<hostname>] => {}

MSG:

Name val is: Open a New Window

TASK [ansible.builtin.debug] **********************************************************************
ok: [<hostname>]: => {}

MSG:

Exec val is: /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=firefox --file-forwarding org.mozilla.firefox --new-window @@u %u @@

PLAY RECAP ****************************************************************************************<hostname> : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Actual Results

```console
$ ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook ansible-ini-filter.yaml

PLAY [localhost] **********************************************************************************

TASK [ansible.builtin.debug] **********************************************************************
ok: [<hostname>] => {}

MSG:

Name val is: Open a New Window

TASK [ansible.builtin.debug] **********************************************************************
fatal: [<hostname>]: FAILED! => {}

MSG:

An unhandled exception occurred while running the lookup plugin 'ansible.builtin.ini'. Error was a <class 'configparser.InterpolationSyntaxError'>, original message: '%' must be followed by '%' or '(', found: '%u @@'. '%' must be followed by '%' or '(', found: '%u @@'

PLAY RECAP ****************************************************************************************
<hostname> : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
