### ISSUE TITLE
Support for conntrack flags in iptables module

### ISSUE THREAD

**Issue by Japje** [ansible/ansible#83763]
### Summary

I'm trying to implement a custom firewall with rules for docker containers. 
One of the recommended ways [according to docker](https://docs.docker.com/network/packet-filtering-firewalls/#match-the-original-ip-and-ports-for-requests) is using conntrack. These flags are not available in the ansible iptables module.

Some of the flags (but not limited to) for conntrack that would help with these are:
```
--ctorigsrc address[/mask]
--ctorigdst address[/mask]
--ctorigdstport port[:port]
--ctreplsrcport port[:port]
```

I think a lot of people managing docker containers would benefit from support of these flags.

My workaround is to use command to add these rules. But that means i have to do a lot of redundant things currently handled by the iptables module.

### Issue Type

Feature Idea

### Component Name

iptables

### Additional Information

The iptables module now already supports adding the cstate so its easy to add a rule allowing related and established connections, and adding a DROP or RETURN rule at the end. 

```
- name: Open HTTPs for allowed hosts
  ansible.builtin.iptables:
    chain: "DOCKER-USER"
    ctorigsrc: 203.0.113.0/24
    ctorigdstport: 443
    protocol: tcp
    action: insert
    jump: ACCEPT
    comment: Allow ipblock for https
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
