### ISSUE TITLE
Fix for #83235 does not fix atomic_move() os.rename() error recovery code

### ISSUE THREAD

**Issue by grantma** [ansible/ansible#83805]
Checked the fix put in for #83235.  It does not fix the attempt to use shutil.copystat() via shutil.copy2() implemented further down in the os.rename() error recovery code in the atomic_move() function.

_Originally posted by @grantma in https://github.com/ansible/ansible/issues/83013#issuecomment-2290328215_

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@grantma: Greetings! Thanks for taking the time to open this Issue. In order for the community to handle your Issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- Component Name
- Issue Type
- Summary

Please set the description of this Issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE
or
https://github.com/ansible/ansible/tree/devel/.github/PULL_REQUEST_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by grantma** [comment]
Here are the two patch files I have previously posted.

[0010-atomic-move-mtime-fix.PATCH](https://github.com/user-attachments/files/16627746/0010-atomic-move-mtime-fix.PATCH)

[0012-atomic-move-fix-recovery-logic-inversion.PATCH](https://github.com/user-attachments/files/16627748/0012-atomic-move-fix-recovery-logic-inversion.PATCH)

**Comment by grantma** [comment]
Here's the patch that is the FIX for this issue:

[ansible-atomic-move-error-recovery-mtime-fixes.PATCH](https://github.com/user-attachments/files/16627881/ansible-atomic-move-error-recovery-mtime-fixes.PATCH)

**Comment by s-hertel** [comment]
Would you mind sharing patches inline (you can use Github markdown and put the diff in a dropdown if it's overly verbose), or attach as a gist/pastebin?

**Comment by s-hertel** [comment]
@grantma Apologies if you've posted one somewhere and I've missed it, but could you share a reproducer as well? I can reproduce the issue with template prior to 26375e7f12d476b5db5441a89a7b0d6356781140 but not on devel.

<details><summary>Here's the test case I used to reproduce the issue:</summary>
<br>

```yaml
- name: Verify atime and mtime update on content change (same partition)
  vars:
    remote_file: "{{ remote_tmp_dir }}/test.txt"
    ansible_remote_tmp: "{{ remote_tmp_dir }}"
  block:
    - name: Create a dest file
      shell: "echo Test content > {{ remote_file }}"
      register: create_dest_result

    - name: Check the stat results of the file before copying
      stat:
        path: "{{ remote_file }}"
      register: stat_results_before_template

    - name: Overwrite the file using template
      template:
        src: "empty_template.j2"
        mode: 0644
        dest: "{{ remote_tmp_dir }}/test.txt"
      register: template_result

    - name: Check the stat results of the file after copying
      stat:
        path: "{{ remote_file }}"
      register: stat_results_after_template

    - name: Assert that the file has changed
      assert:
         that:
           - "create_dest_result is changed"
           - "template_result is changed"
           - "stat_results_before_template.stat.atime < stat_results_after_template.stat.atime"
           - "stat_results_before_template.stat.mtime < stat_results_after_template.stat.mtime"
```
</details>
