### ISSUE TITLE
Json key is not returned when using builtin uri module

### ISSUE THREAD

**Issue by ChristopheLRTE** [ansible/ansible#83821]
### Summary

Hello,

I'm using ansible-core 2.15.12 (Python virtual environment) with python 3.9.
When I launch a uri task calling an api from a Centos 7.9 host no json key is returned
When I launch exactly the same from a Oracle Linux 8 the json key exists well.
Would you know why ?

Thank you for your help,
Regards
C.L.   

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.12]
  config file = ~/deploiement/bdp-cluster-deploiement/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/deploiement/bdp-cluster-deploiement/venv-ansible-2-15/lib64/python3.9/site-packages/ansible
  ansible collection location = ~/deploiement/bdp-cluster-deploiement/livraison/installation/ansible_roles/collections
  executable location = ~/venv-ansible-2-15/bin/ansible
  python version = 3.9.19 (main, May 30 2024, 06:55:59) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22.0.1)] (~/venv-ansible-2-15/bin/python3.9)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
COLLECTIONS_PATHS(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = ['~c>CONFIG_FILE() = ~/deploiement/bdp-cluster-deploiement/ansible.cfg
DEFAULT_BECOME(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = True
DEFAULT_BECOME_USER(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = root
DEFAULT_HASH_BEHAVIOUR(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = merge
DEFAULT_LOG_PATH(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = ~/>DEFAULT_REMOTE_USER(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = ['~>DEFAULT_STDOUT_CALLBACK(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = yaml
DEFAULT_TIMEOUT(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = 30
HOST_KEY_CHECKING(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(~/deploiement/bdp-cluster-deploiement/ansible.cfg) =>INVENTORY_CACHE_TIMEOUT(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = 7200

BECOME:
======

runas:
_____
become_user(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = root

su:
__
become_user(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = root

sudo:
____
become_user(~/deploiement/bdp-cluster-deploiement/ansible.cfg) = root
```

### OS / Environment

CentOS 7.9

### Steps to Reproduce

```yaml (paste below)
- name: Create kms service
  run_once: true
  ansible.builtin.uri:
    url: "{{ kms_install_properties.POLICY_MGR_URL }}/service/plugins/services"
    method: POST
    body:
      name: "{{ kms_install_properties.REPOSITORY_NAME }}"
      isEnabled: true
      configs:
        username: my_user
        password: *****
        provider: "{{ ranger_kms_url }}"
      type: kms
    body_format: json
    force_basic_auth: true
    user: my_user
    password: *******
    headers:
      Content-Type: application/json
    status_code: [200, 400]
    validate_certs: false
  register: reg_kms
  changed_when: reg_kms.status == 200
  failed_when: |
    reg_kms is failed or
    reg_kms.status == 400 and
    (reg_kms.json.msgDesc is not defined or
    'Duplicate service name' not in reg_kms.json.msgDesc)
```

### Expected Results

Query a rest api and if 200 or 400 is returned read the json key of the return and pass the task

### Actual Results

```console
fatal: [node01]: FAILED! => changed=false 
  cache_control: no-cache, no-store, max-age=0, must-revalidate
  connection: close
  content: '{"statusCode":1,"msgDesc":"(0) Validation failure: error code[1007], reason[Duplicate service name: name=[kms-tdp]], field[name], subfield[null], type[semantically incorrect] "}'
  content_security_policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline';font-src 'self'
  content_type: application/json
  date: Mon, 19 Aug 2024 15:26:02 GMT
  elapsed: 0
  expires: '0'
  failed_when_result: true
  invocation:
    module_args:
      attributes: null
      body:
        configs:
          password: myuser
          provider: kms://my_fqdn:my_port/kms
          username: *****
        isEnabled: true
        name: kms-tdp
        type: kms
      body_format: json
      ca_path: null
      ciphers: null
      client_cert: null
      client_key: null
      creates: null
      decompress: true
      dest: null
      follow_redirects: safe
      force: false
      force_basic_auth: true
      group: null
      headers:
        Content-Type: application/json
      http_agent: ansible-httpget
      method: POST
      mode: null
      owner: null
      password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      remote_src: false
      removes: null
      return_content: true
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: null
      status_code:
      - 200
      - 400
      timeout: 30
      unix_socket: null
      unredirected_headers: []
      unsafe_writes: false
      url: https://my_fqdn:my_port/service/plugins/services
      url_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      url_username: admin
      use_gssapi: false
      use_netrc: true
      use_proxy: true
      user: admin
      validate_certs: false
  msg: 'HTTP Error 400: Bad Request'
  pragma: no-cache
  redirected: false
  server: Apache Ranger
  set_cookie: RANGERADMINSESSIONID=**************************; Path=/; Secure; HttpOnly
  status: 400
  strict_transport_security: max-age=31536000 ; includeSubDomains
  transfer_encoding: chunked
  url: https://my_fqdn:my_port/service/plugins/services
  x_content_type_options: nosniff
  x_frame_options: DENY
  x_xss_protection: 1; mode=block
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
