### ISSUE TITLE
Add a possibility to control minimum TLS version in ansible.builtin.uri

### ISSUE THREAD

**Issue by GD1200** [ansible/ansible#83832]
### Summary

While having a discussion about a possibility of setting minimum TLS version for _ansible.builtin.uri_ in [the Ansible mailing list](https://groups.google.com/g/ansible-project/c/eQIW17eKeck), it got clear that relying on the default system-wide _MinProtocol_ value in the OpenSSL configuration is not possible in some Python environements. The reason is that the Python team [started enforcing default cipher and minimum TLS version 1.2 values in Python 3.10](https://github.com/python/cpython/issues/88164), unless downstream distributors revert the old behaviour for reading the defaults from the OpenSSL configuration file.

Although _ansible.builtin.uri_ allows to set custom ciphers that are compatible with TLS protocols 1.0 and 1.1, the TLS protocol version itself is not possible to control. As a result, in the environments depending on the official CPython 3.10+ binaries, it is not possible to use _ansible.builtin.uri_ to access legacy TLS 1.0/1.1 web servers. One example of such environments are the [official Python Docker images](https://hub.docker.com/_/python).

### Issue Type

Feature Idea

### Component Name

ansible.builtin.uri

### Additional Information

For example, setting the official TLS protocol name with a parameter like 'ssl_min_protocol' could be an option.

```yaml (paste below)
- name: Test legacy host
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Fetch URL
      ansible.builtin.uri:
        url: https://legacybox.example.com
        ciphers:
          - 'DEFAULT@SECLEVEL=2'
        ssl_min_protocol: 'TLSv1'
      register: out

    - ansible.builtin.debug:
        var: out
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
