### ISSUE TITLE
Change backup=yes behavior to feature remote backups

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#8383]
Change the way backup=yes works on modules

If supplied, module must return names of files in a "should_backup" array of those filenames to backup, in which case we should copy these to the following

configured backup path / {{ inventory_hostname }} // {{ timestamp }}

and keep a configured number of versions around.

**Comment by mpdehaan** [comment]
Possibly something for Ansible 1.8

**Comment by ansibot** [comment]
Thanks for filing a ticket! I am the friendly GitHub Ansibot. I see you did not fill out your issue description based on our new issue template. Please copy the contents of this [template](https://raw2.github.com/ansible/ansible/devel/examples/issues/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket. 

Our system will automatically close tickets that do not have an issue template filled out within 7 days. Please note that due to large interest in Ansible, humans may not comment on your ticket if you ask them questions. Don't worry, you're still in the queue and the robots are looking after you.

**Comment by nifr** [comment]
awesome idea - this would be incredibly helpful :+1: 

One thing isn't quite clear to me:

Are you talking about a backup path on the remote machine itself ... or do you imagine the file to be downloaded to the machine which runs ansible? 

Both possibilities would make sense in certain situations.

**Comment by PatBee** [comment]
I will "third" this request.  A co-worker and I agree this is good idea.  

Issue Type: Feature Idea
Ansible Version: 1.8 
Environment: Centos 6 & RHEL 6 
Summary:  Ability to limit backup files created by number (last 5) or by age (delete backups older than 60 days). 
Steps To Reproduce: N/A
Expected Results:  Keep from cluttering directories with large numbers of unused backup files. 
Actual Results:  Backup files build up in definitely.  

I am speaking of the current behavior of backup files on the target servers.  However the idea of copying the backup locally is interesting and could be useful.

**Comment by EvanK** [comment]
Here's an idea...whether it's good, I will leave up for debate: record backed up files in a dedicated git repository for each machine (eg, each `inventory_hostname`).

It has the neat effect of only storing the delta of files that are backed up multiple times, and leaves backups accessible to anyone with a working knowledge of `git blame`. Plus, a task that iterates & modifies a single file multiple times would generate multiple commits for each modification.

Some (bash based) pseudocode of how I'd imagine it to work: https://gist.github.com/EvanK/ec9bcb08c61bf541b4e7

**Comment by nifr** [comment]
Storing the backups in some kind of VCS (git,mercurial,...) is obviously a good idea. 

We have to take into account that not everybody has git installed on their local/remote machines. 
Therefore I suggest a backup mechanism where we can add multiple "providers". 

 The following pseudo-configuration shall demonstrate the idea:

```
backup:
   providers:
      - type: git
        dest: https://repo.io/project-backup.git
      - type: remote
        dest: /var/www/project/backup
      - type: local
        dest: ./backup/
```

This would backup the file(s) to a remote git repository + store them in `/var/www/project/backup/<someidentifier>` on the remote server itself + download them to a directory relative to the playbook on the ansible-executing machine.

**Comment by mpdehaan** [comment]
Storing binary files in git is something to be avoided, it might be sufficient to keep just the last N.

For full disclosure, this is unlikely to hit 1.8, but is still in plan.

**Comment by nifr** [comment]
I was thinking that having a "local" and "remote" file-backup provider with a common interface (which  can be used by vcs providers lateron) would be a good starting point for a rework of the backup functionality.

What do you think @mpdehaan ?

_additonal note_:
[git-annex](https://github.com/joeyh/git-annex)  ([doc](https://git-annex.branchable.com/git-annex/)) can be considered a (more or less) standard when dealing with git and binary files in my oppinion.

**Comment by ant31** [comment]
Without refactoring you can already use handlers to send all backups with the method of your choice.
In this exemple I use rsync (synchronize), but you can replace it with vcs or any other existing modules

``` yaml
tasks:
  - name: send projectA configuration                                                            
    template: src=projectA.conf.j2 dest=/etc/projectA/conf backup=yes                
    register: new_conf                                                            
    notify:                                                                       
     - backup conf 

  - name: send projectB configuration                                                            
    template: src=projectB.conf.j2 dest=/etc/projectB/conf backup=yes                
    register: new_conf                                                             
    notify:                                                                       
       - backup conf 

handlers:
   - name: backup conf
     synchronize: mode=pull src={{item.backup_file}}   dest=/archive/{{inventory_hostname}}/{{item.backup_file | basename}}
     delegate_to: backup-server-1
     when: '{{item.backup_file is defined}}'
     with_items: new_conf
     register: backup
```
