### ISSUE TITLE
Exception in postgresql_user module managing users for AWS RDS

### ISSUE THREAD

**Issue by iragsdale** [ansible/ansible#8384]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

Running on Mac OS 10.9.4 and managing an AWS RDS instance from an Ubuntu 12.04 EC2 instance.
##### Summary:

The second execution of the postgres_user module will fail if setting a password or role attributes, because the pg_authid table is not readable by the master user.
##### Steps To Reproduce:

1) Provision AWS RDS postgresql instance.
2) Write playbook to create a postgres user with a password.
3) Execute that playbook twice
##### Expected Results:

The 2nd execution should return no change for this user.
##### Actual Results:

Traceback:
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1744, in <module>
  File "<stdin>", line 497, in main
  File "<stdin>", line 201, in user_alter
psycopg2.ProgrammingError: permission denied for relation pg_authid

More info here (may require an AWS login): https://forums.aws.amazon.com/thread.jspa?threadID=151248

**Comment by mpdehaan** [comment]
Can you please supply the playbook line that resulted in the following?

Thanks!

**Comment by iragsdale** [comment]
Sure thing!

```
  postgresql_user:
    name: boxer_{{item.key}}
    password: "{{lookup('password', 'creds/boxer/db/'+item.key+' chars=ascii_letters,digits')}}"
    db: boxer_{{item.key}}_production
    state: present
    login_host: "{{dbhost}}"
    login_user: "{{dbuser}}"
    login_password: "{{dbpassword}}"
```
