### ISSUE TITLE
to_nice_yaml corrupts multiline text with linebreaks

### ISSUE THREAD

**Issue by jwalzer** [ansible/ansible#83868]
### Summary

Multiline text fields are wrapped and linebreaks are inserted when linelength seems to reach a limit
Example testcase:
```
- copy:
    content: "{{ content | to_nice_yaml(sort_keys=false) }}"
    dest: "test.yaml"
  vars:
    content:
      text: |
        aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaa
        bbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb bbbbb
```
result:
````
$ cat test.yaml
text: 'aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaa

    bbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbb

    '
````

Please realize, that there is explicit linebreaks before the last word in the line, and even after every line.
This corrupts config file generation.

### Issue Type

Bug Report

### Component Name

jinja2

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.6]
  config file = /Users/jwalzer/redhat/Phoenix CH/src/red.Kvant/ansible.cfg
  configured module search path = ['/Users/jwalzer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/9.5.1_1/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/jwalzer/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/9.5.1_1/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/Users/jwalzer/redhat/ansible.cfg) = True
CONFIG_FILE() = /Users/jwalzer/redhat/ansible.cfg
DEFAULT_FORKS(/Users/jwalzer/redhat/ansible.cfg) = 20
DEFAULT_GATHERING(/Users/jwalzer/redhat/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/Users/jwalzer/redhat/ansible.cfg) = merge
DEFAULT_HOST_LIST(/Users/jwalzer/redhat/ansible.cfg) = ['/Users/jwalzer/redhat/inventory/dev/hosts.yaml']
DEFAULT_LOG_PATH(/Users/jwalzer/redhat/ansible.cfg) = /Users/jwalzer/ansible.log
DEFAULT_REMOTE_USER(/Users/jwalzer/redhat/ansible.cfg) = root
DEFAULT_ROLES_PATH(/Users/jwalzer/redhat/ansible.cfg) = ['/Users/jwalzer/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', '/Use>
DEFAULT_TIMEOUT(/Users/jwalzer/redhat/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/Users/jwalzer/redhat/ansible.cfg) = /Users/jwalzer/redhat/.vaultpasswd
HOST_KEY_CHECKING(/Users/jwalzer/redhat/ansible.cfg) = False
INVENTORY_IGNORE_EXTS(/Users/jwalzer/redhat/ansible.cfg) = ['secrets.py', '.pyc', '.cfg', '.crt', '.ini']
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/Users/jwalzer/redhat/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/Users/jwalzer/redhat/ansible.cfg) = /Users/jwalzer/ansible-installer-retries

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/Users/jwalzer/redhat/ansible.cfg) = False
remote_user(/Users/jwalzer/redhat/ansible.cfg) = root
ssh_args(/Users/jwalzer/redhat/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s
timeout(/Users/jwalzer/redhat/ansible.cfg) = 10

ssh:
___
control_path(/Users/jwalzer/redhat/ansible.cfg) = %(directory)s/%%h-%%r
host_key_checking(/Users/jwalzer/redhat/ansible.cfg) = False
pipelining(/Users/jwalzer/redhat/ansible.cfg) = True
remote_user(/Users/jwalzer/redhat/ansible.cfg) = root
ssh_args(/Users/jwalzer/redhat/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s
timeout(/Users/jwalzer/redhat/ansible.cfg) = 10
```

### OS / Environment

MacOS Sonoma 14.6.1 (23G93)
Ansible 2.16.6 via homebrew

### Steps to Reproduce

```yaml
- copy:
    content: "{{ content | to_nice_yaml(sort_keys=false) }}"
    dest: "test.yaml"
  vars:
    content:
      text: |
        aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaa
        bbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb bbbbb
```
result:
````
$ cat test.yaml
text: 'aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaa

    bbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbb

    '
````

Please realize, that there is explicit linebreaks before the last word in the line, and even after every line.

### Expected Results

I expect the same or similar results like explicitely outputting the field.

```yaml
- copy:
    content: |
      text: |
          {{ content.text | indent(width=4) }}
    dest: "test.yaml"
  vars:
    content:
      text: |
        aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaa
        bbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb bbbbb
```
result
```
$ cat test.yaml
text: |
    aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaa
    bbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb bbbbb
```

- At least the lines must not be wrapped by the filter.
- I suggest an additional option, if someone thinks this feature is needed but it shouldn't be activated by default
- Additional points if the to_yaml filter supports multiline block output of multiline text.

### Actual Results

```console
see above
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
