### ISSUE TITLE
I'm having an issue with "become"

### ISSUE THREAD

**Issue by tjc-jhol** [ansible/ansible#83877]
### Summary

When I try to deploy playbooks using a non-root user, the playbook never runs as root even though I have "become=True" set in ansible.cfg/playbook/cli.

### Issue Type

Bug Report

### Component Name

ansible.builtin.file

### Ansible Version

```console
$ ansible --version

ansible [core 2.17.3]
  config file = /home/josh/repos/Redhat Playbooks/ansible.cfg
  configured module search path = ['/home/josh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/josh/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/josh/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/josh/.local/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ANSIBLE_NOCOWS(/home/josh/repos/Redhat Playbooks/ansible.cfg) = True
CONFIG_FILE() = /home/josh/repos/Redhat Playbooks/ansible.cfg
DEFAULT_BECOME(/home/josh/repos/Redhat Playbooks/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/josh/repos/Redhat Playbooks/ansible.cfg) = ['/home/josh/repos/Redhat Playbooks/inventory.yaml']
EDITOR(env: EDITOR) = nano
INTERPRETER_PYTHON(/home/josh/repos/Redhat Playbooks/ansible.cfg) = auto_silent
```

### OS / Environment

Target OS is RedHat 8

### Steps to Reproduce

```yaml (paste below)
---
- name: Download and Update files
  hosts: all
  gather_facts: true
  vars:
    txt_file: "somefile.txt"
    txt_full_path: "{{ file_path }}/{{ file_name }}"
  tasks:
    - name: Validate txt file path exists
      ansible.builtin.file:
        path: "{{ file_path }}"
        state: directory
        mode: "0755"
        owner: someuser
        group: someuser

    - name: Remove old txt File
      ansible.builtin.file:
        path: "{{ txt_full_path }}.old"
        state: absent

    - name: Test for existing txt file
      ansible.builtin.stat:
        path: "{{ txt_full_path }}"
      register: existing_txt_file

    - name: Rename existing txt file
      when: existing_txt_file.stat.exists
      ansible.builtin.copy:
        remote_src: true
        src: "{{ txt_full_path }}"
        dest: "{{ txt_full_path }}.old"
        mode: "0600"
        owner: someuser
        group: someuser

    - name: Copy new txt file to remote server
      ansible.builtin.copy:
        src: "{{ txt_new_file }}"
        dest: "{{ txt_full_path }}"
        mode: "0600"
        owner: someuser
        group: someuser

```

### Expected Results

I expect the playbook ssh as our 'ansible_automate' user and execute tasks as 'root'.

### Actual Results

```console
https://gist.github.com/tjc-jhol/6008d52620d8937dfb6fbec647b667c4
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
