### ISSUE TITLE
uri module encodes uploaded file in base64 but it can't be handled by the server

### ISSUE THREAD

**Issue by cwhuang** [ansible/ansible#83884]
### Summary

I have the exact same issue as described in
https://github.com/ansible/ansible/issues/73621

Since that issue was closed and no more comments could be added.
So I have to create another issue to address it. Sorry for this.

I saw your comments in that issue. I agree base64 encoding is the standard way.
However, the server can't handle it and we have no way to change it
since we don't own that server. It expects the file in the raw format.

Could it be fixed or work around in any way?

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.11]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/cwhuang/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/cwhuang/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg

$ cat /etc/ansible/ansible.cfg
# Since Ansible 2.12 (core):
# To generate an example config file (a "disabled" one with all default settings, commented out):
#               $ ansible-config init --disabled > ansible.cfg
#
# Also you can now have a more complete file by including existing plugins:
# ansible-config init --disabled -t all > ansible.cfg

# For previous versions of Ansible you can check for examples in the 'stable' branches of each version
# Note that this file was always incomplete  and lagging changes to configuration settings

# for example, for 2.9: https://github.com/ansible/ansible/blob/stable-2.9/examples/ansible.cfg
```

### OS / Environment

Fedora 38

### Steps to Reproduce

```yaml (paste below)

ansible-playbook -l rs700 -t update -i ~/ansible/inventory.yaml ~/ansible/customer.yaml

    - name: "Update {{ t }} of {{ inventory_hostname }}"
      tags: update
      ansible.builtin.uri:
        url: "https://{{ bmc_addr }}/redfish/v1/UpdateService/upload"
        method: POST
        force_basic_auth: true
        user: "{{ bmc_user }}"
        password: "{{ bmc_password }}"
        status_code: 202,200
        body_format: form-multipart
        body:
          UpdateParameters:
            mime_type: application/json
            filename: "/tmp/update-bios.json"
          OemParameters:
            mime_type: application/json
            filename: "/tmp/oem-bios.json"
          UpdateFile:
            filename: "~/{{ inventory_hostname }}/{{ hostvars[inventory_hostname][t]['image'] }}"
            mime_type: application/octet-stream
            encoding: none
          text_form_field: value
        validate_certs: false
        timeout: 300

### Expected Results

The firmware file could be uploaded correctly and the server (an BMC) can handle it correctly.

### Actual Results

```console
fatal: [rs700]: FAILED! => {"changed": false, "connection": "close", "content_length": "643", "content_type": "application/json; charset=UTF-8", "date": "Fri, 30 Aug 2024 22:58:19 GMT", "elapsed": 6, "json": {"error": {"@Message.ExtendedInfo": [{"@odata.type": "#Message.v1_0_8.Message", "Message": "The file, UpdateParameters, submitted is a malformed JSON file and could not be parsed successfully by the receiving service.", "MessageArgs": ["UpdateParameters"], "MessageId": "UpdateService.1.0.MalformedJSONFile", "RelatedProperties": ["UpdateParameters"], "Resolution": "Ensure that the file sent is a proper valid JSON file and resubmit the request.", "Severity": "Critical"}], "code": "UpdateService.1.0.MalformedJSONFile", "message": "The file, UpdateParameters, submitted is a malformed JSON file and could not be parsed successfully by the receiving service."}}, "msg": "Status code was 400 and not [202, 200]: HTTP Error 400: Bad Request", "odata_version": "4.0", "redirected": false, "server": "AMI MegaRAC Redfish Service", "status": 400, "url": "https://10.10.95.111/redfish/v1/UpdateService/upload"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
