### ISSUE TITLE
uri module changes quotation mark to apostrophe of json format variables in file content

### ISSUE THREAD

**Issue by cwhuang** [ansible/ansible#83885]
### Summary

When use uri module to upload content in json format the quotation mark " (ascii 0x22) will be kept. However, if the content contains variables, all quotation mark will be convert to apostrophe (ascii 0x27). This is unexpected and causes a format error in the destination web server.

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.3]
  config file = None
  configured module search path = ['/home/cwhuang/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cwhuang/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/cwhuang/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cwhuang/.local/bin/ansible
  python version = 3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = /usr/bin/nano
```

### OS / Environment

Fedora 38

### Steps to Reproduce

```yaml (paste below)

The GOOD case:
  tasks:
    - name: "GOOD case"
      ansible.builtin.uri:
        url: "{{ protocol }}://{{ bmc_addr }}/redfish/v1/UpdateService/upload"
        method: POST
        force_basic_auth: true
        user: "{{ bmc_user }}"
        password: "{{ bmc_password }}"
        status_code: 202,200
        body_format: form-multipart
        body:
          UpdateParameters:
            content: "{\"Targets\": [\"/redfish/v1/UpdateService/FirmwareInventory/BIOS\"]}"
            mime_type: application/json

Using tcpdump to capture the sent http request:
--===============6874603775766322307==
Content-Type: application/json
Content-Disposition: form-data; name="UpdateParameters"

{"Targets": ["/redfish/v1/UpdateService/FirmwareInventory/BIOS"]}
--===============6874603775766322307==--

This is expected and good to the BMC server.

The BAD case: if using variable in content, all " are converted to '

  vars:
    real_content: "{\"Targets\": [\"/redfish/v1/UpdateService/FirmwareInventory/BIOS\"]}"

  tasks:
    - name: "BAD case"
      ansible.builtin.uri:
        url: "{{ protocol }}://{{ bmc_addr }}/redfish/v1/UpdateService/upload"
        method: POST
        force_basic_auth: true
        user: "{{ bmc_user }}"
        password: "{{ bmc_password }}"
        status_code: 202,200
        body_format: form-multipart
        body:
          UpdateParameters:
            content: "{{ real_content }}"
            mime_type: application/json

The http request becomes:
--===============6874603775766322307==
Content-Type: application/json
Content-Disposition: form-data; name="UpdateParameters"

{'Targets': ['/redfish/v1/UpdateService/FirmwareInventory/BIOS']}
--===============6874603775766322307==--

The BMC server will think it's a malformed json and throw an error.

I have no idea why the quotation mark will be converted in the http request.
Checking the real_content variable via debug module, it looks fine:

    - name: debug
      tags: debug
      ansible.builtin.debug:
        msg: '{{ real_content }}'

TASK [debug] ****************************************************************************************************************************************************************
ok: [sony] => {
    "msg": {
        "Targets": [
            "/redfish/v1/UpdateService/FirmwareInventory/BIOS"
        ]
    }
}

### Expected Results

The BAD case will send the same http request as the GOOD case.

### Actual Results

```console
When test the BAD case, the server replied

"The file, UpdateParameters, submitted is a malformed JSON file and could not be parsed successfully by the receiving service.", "MessageArgs": ["UpdateParameters"], "MessageId": "UpdateService.1.0.MalformedJSONFile", "RelatedProperties": ["UpdateParameters"], "Resolution": "Ensure that the file sent is a proper valid JSON file and resubmit the request."
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/test/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/test/uri.py)
* [`lib/ansible/plugins/action/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/uri.py)
* [`lib/ansible/modules/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/uri.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
This is expected in Ansible's current default config. You do not have [jinja2_native](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-jinja2-native) enabled, so when the result of templating is a string which looks like a data structure Ansible converts it to a data structure.

Instead of painstaking constructing an escaped JSON string, you can make your life easier by specifying it as a data structure in the first place, then converting it to JSON (which also [lets the templating engine know that you want it to remain a string](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#string-type-filters)):
```yaml
  vars:
    real_content:
      Targets:
        - /redfish/v1/UpdateService/FirmwareInventory/BIOS

  tasks:
    - name: "BAD case"
      ansible.builtin.uri:
        url: "{{ protocol }}://{{ bmc_addr }}/redfish/v1/UpdateService/upload"
        method: POST
        force_basic_auth: true
        user: "{{ bmc_user }}"
        password: "{{ bmc_password }}"
        status_code: 202,200
        body_format: form-multipart
        body:
          UpdateParameters:
            content: "{{ real_content | to_json }}"
            mime_type: application/json
```

Or, with your current variable just make sure you cast it to a string as the last operation:
```yaml
            content: "{{ real_content | string }}"
```
