### ISSUE TITLE
set_fact module does not substitute the first {{ item }} from the loop when appending to the same fact

### ISSUE THREAD

**Issue by MarianMacik** [ansible/ansible#83895]
### Summary

Hi,

when I execute this playbook:

``` yaml
- name: example
  hosts: localhost
  tasks:
    - name: create list
      set_fact:
        myList: "{{ myList | default([]) + ['my-{{ item }}'] }}"
      loop: "{{ range(0,3,1) | list }}"
    - name: "print myList"
      debug:
        msg: "{{ myList }}"
```

the myList fact is set to `['my-1', 'my-2', 'my-{{ item }}']`, so it is missing the first "item" evaluated to 0 for some reason. The subsequent debug task thus fails with:

```
PLAY [example] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************
ok: [localhost]

TASK [create list] ********************************************************************************************************************************************************************************
ok: [localhost] => (item=0)
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)

TASK [print myList] *******************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: ['my-1', 'my-2', 'my-{{ item }}']: 'item' is undefined. 'item' is undefined. ['my-1', 'my-2', 'my-{{ item }}']: 'item' is undefined. 'item' is undefined\n\nThe error appears to be in '/home/mmacik/Stiahnuté/worker_hosts/create_cluster.yaml': line 70, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      loop: \"{{ range(0,3,1) | list }}\"\n    - name: \"print myList\"\n      ^ here\n"}
```

However, if I do:

``` yaml
- name: example
  hosts: localhost
  vars:
    myListTemplate:
    - 'my-{{ item }}'
  tasks:
    - name: create list
      set_fact:
        myList: "{{ myList | default([]) + myListTemplate }}"
      loop: "{{ range(0,3,1) | list }}"
    - name: "print myList"
      debug:
        msg: "{{ myList }}"
```

it suddenly starts working:

```
PLAY [example] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************
ok: [localhost]

TASK [create list] ********************************************************************************************************************************************************************************
ok: [localhost] => (item=0)
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)

TASK [print myList] *******************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "my-0",
        "my-1",
        "my-2"
    ]
}
```

To me both solutions look equivalent, the difference being just that the first solution has the template inline.

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
$ ansible --version
config file = None
  configured module search path = ['/home/mmacik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mmacik/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/mmacik/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mmacik/.local/bin/ansible
  python version = 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = /usr/bin/vim
```

### OS / Environment

Fedora 39

### Steps to Reproduce

Explained above.

### Expected Results

I expect both solutions to behave equivalently.

### Actual Results

```console
Explained above.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
