### ISSUE TITLE
Anisble fails for retires which is more than a minutes for windows server

### ISSUE THREAD

**Issue by duckingbread** [ansible/ansible#83900]
### Summary

When I try to use the retry function for a task, and define the delays as more than a minute, I get 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: winrm.exceptions.WinRMTransportError: Bad HTTP response returned from server. Code 400

This causes issues because for some task I might want to wait a longer time in between retries.

### Issue Type

Bug Report

### Component Name

winrm

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/admchristina_bonnyma/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, May 24 2024, 06:39:46) [GCC 8.5.0 20210514 (Red Hat 8.5.0-21.0.1)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
cant provide as its company's config
```

### OS / Environment

OracleLinux Server release 8.8 Plus

### Steps to Reproduce

```yaml (paste below)
- hosts: all
  vars:
    threshold: "{{ threshold_var }}"
  tasks:
    - name: Check folder size
      win_stat:
        path: C:\Windows\WinSxS
      register: folder_size

    - name: Print folder size 
      debug:
        msg: "Folder size before: {{ folder_size.stat.size / 1024 / 1024 / 1024 | round(2) }} GB"

    - name: recheck the disk space
      win_stat:
        path: C:\Windows\WinSxS
      register: folder_size_check
      until: folder_size_check.stat.size < 773741824
      retries: 4
      delay: 300 
      when: folder_size.stat.size > threshold



```

### Expected Results

Expected program to retry normally .

### Actual Results

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: winrm.exceptions.WinRMTransportError: Bad HTTP response returned from server. Code 400
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
