### ISSUE TITLE
local_action does not delegate to controller when remote is localhost

### ISSUE THREAD

**Issue by Jackenmen** [ansible/ansible#83915]
### Summary

When port forwarding a remote SSH server to a local port and using that local port in Ansible, delegation to the controller node does not seem to be possible with either the `local_action` or `delegate_to` as, in both cases, Ansible runs delegated tasks on the remote node.
While it does make sense to me that `delegate_to` would use whatever is defined in the inventory, I assumed that `local_action` (per its name) would run the module *locally* - on the controller node.

### Issue Type

Bug Report

### Component Name

local_action,delegate_to

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/repro/.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = .venv/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/tmp/repro/.venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = subl -w
```

### OS / Environment

Running Ubuntu 22.04 on both the controller node and the remote.

### Steps to Reproduce

In a real environment, I forward the SSH port of a different machine in the network that the machine I ssh into is (i.e. bastion setup) but this example should highlight the issue as well and is simple to create a reproduction for.

1. Create a file `playbook.yaml` with the following contents:
```yaml
---
- hosts: all
  tasks:
    - name: Runs on remote node as expected
      ansible.builtin.file:
        path: /tmp/file1
        state: touch

    - name: Runs on remote node which I guess makes sense but I don't know how to delegate to controller node in this case
      ansible.builtin.file:
        path: /tmp/file2
        state: touch
      delegate_to: localhost

    - name: Runs on remote node which is unexpected
      local_action:
        module: ansible.builtin.file
        path: /tmp/file3
        state: touch
```
2. Create a file `inventory.yaml` with the following contents (replace `<user>` with the user to connect with):
```
all:
  hosts:
    127.0.0.1:
      ansible_connection: ssh
      ansible_port: 1234
      ansible_user: <user>
```
3. Run `ssh <user>@<host> -L 127.0.0.1:1234:127.0.0.1:22` in another terminal window.
4. Run `ansible-playbook playbook.yaml -i inventory.yaml`.
5. Validate that all of the files have been created on the remote node and that none of the files (namely /tmp/file2 and /tmp/file3) have been created on the controller node.

### Expected Results

For comparison to how I would expect it work, you can change the `inventory.yaml` file to:
```yaml
all:
  hosts:
    <host>:
      ansible_connection: ssh
      ansible_port: 22
      ansible_user: <user>
```

You'll see that in this case, the `/tmp/file2` and `/tmp/file3` files are created on the controller node, while `/tmp/file1` is created on the remote node.

### Actual Results

```console
Too long to fit into the issue, here's the gist: https://gist.githubusercontent.com/Jackenmen/fa7ddca29eaf9704dd65d57d1b7511b9/raw/c8e530b9071a00768dc92fa830003d537b2ffa3e/actual_result_83915.log
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by Jackenmen** [comment]
@ansibot component +lib/ansible/parsing/mod_args.py

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/parsing/mod_args.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/mod_args.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
This is not a bug. `local_action` is just alternate syntax for `delegate_to: 127.0.0.1`, so if you have defined `127.0.0.1` as being a remote host then `local_action` will connect to that remote host.

There are two ways to address this in your Ansible content; the one that makes the most sense is to give the remote host its real name, instead of calling it `127.0.0.1`.

```yaml
all:
  hosts:
    myremote:
      ansible_host: 127.0.0.1
      ansible_connection: ssh
      ansible_port: 1234
      ansible_user: <user>
```

The other is to add a distinct entry for the actual localhost:
```yaml
all:
  hosts:
    127.0.0.1:
      ansible_connection: ssh
      ansible_port: 1234
      ansible_user: <user>
    localhost:
      ansible_connection: local
```
and then use `delegate_to: localhost` instead of `local_action` (which is a good idea anyway, `local_action` is less flexible than `delegate_to` and uses the same mechanism internally.)
