### ISSUE TITLE
vmware_host ssl thumbprint

### ISSUE THREAD

**Issue by cfsnate** [ansible/ansible#83935]
### Summary

Cannot add esxi host to vcenter, does not appear to fetch the ssl thumbprint properly. Can be added through the vCenter GUI and then ansible will show it as ok.

### Issue Type

Bug Report

### Component Name

vmware_host

### Ansible Version

```console
$ ansible --version

ansible [core 2.17.3]
  config file = None
  configured module search path = ['/conf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /conf/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.5 (main, Aug 13 2024, 10:19:35) [GCC 12.2.0] (/usr/local/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = None
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = False
PAGER(env: PAGER) = less
```

### OS / Environment

Debian

### Steps to Reproduce

```yaml (paste below)

- name: Add ESXi Hosts to vCenter
  community.vmware.vmware_host:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ datacenter_name }}'
    cluster: '{{ cluster_name }}'
    esxi_hostname: '{{ item.hostname }}.{{ fqdn }}'
    esxi_username: '{{ esxi_username }}'
    esxi_password: '{{ esxi_password }}'
    state: present
    validate_certs: false
  delegate_to: localhost
  loop: '{{ hosts }}'

```

### Expected Results

Host is added to vcenter

### Actual Results

```console
"msg": "Cannot connect to host: example.hostname.com"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
