### ISSUE TITLE
Pass handlers into imported playbooks

### ISSUE THREAD

**Issue by EdwardCooke** [ansible/ansible#83947]
### Summary

I am building a playbook that I would like to import into others. I was hoping to be able to add extension points into it via handlers or some other means.

For example, when installing Kubernetes, after it's initialized, but before adding additional nodes I want to call a handler that allows the consumer of the playbook to inject tasks at that stage. Like installing a CNI for example.

This would allow the option to extend playbooks so they aren't copied, and instead reused. I could see this being especially important in larger playbooks.

### Issue Type

Feature Idea

### Component Name

import_playbook

### Additional Information

```yaml (paste below)
- name: "Install k8s"
  ansible.builtin.import_playbook: ../../../ansible-kubernetes/playbooks/install.yml
  handlers:
  - name: Install Cilium
    listen: Kubeadm init
    ansible.builtin.import_tasks: install-cilium.yml
    delegate_to: "{{ first_kube_control_plane }}"
    run_once: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/import_playbook.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/import_playbook.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by mkrizek** [comment]
Handlers are play scoped. Would handlers passed into an imported playbook be added into every play of the playbook? That would be inconsistent with how handlers are added into plays currently and IMHO would create confusion for users.

> This would allow the option to extend playbooks so they aren't copied, and instead reused.

Wouldn't it be better to restructure the playbook so the parts that need to be reused are included/imported via roles?

**Comment by EdwardCooke** [comment]
My goal is to have something like kubespray, where there is a playbook that will pretty large. That playbook looks to be designed as reusable via variables. However, it lacks extension points to be able to do custom things during different stages in that playbook. After going down the route of building my own because I needed to do things differently, I found this is a limitation, sort of. I did find a way to go about it that I almost like better since the hooks don't necessarily fire off when they're signaled without the meta task to flush them.

I use variables and the include_tasks task.

Here's an example of the task that gives an extension point into my playbook and roles

```yaml
- name: Preinstall hooks
  ansible.builtin.include_tasks:
    file: "{{ inventory_dir }}/{{ hookfiles.preinstall }}"
  when:
  - hookfiles.preinstall is defined
  - hookfiles.preinstall != None
```

This seems to work pretty well and can be used in both playbooks and roles and gives what I'm looking for.

My current playbook already imports roles, those roles handle all of the actual tasks.
