### ISSUE TITLE
flush_handlers doesn't activate handlers notified from the role section

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#8395]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.5.5
##### Environment:

Crontol System : OSX 10.9.4 
Target System : CentOS 6.4
##### Summary:

I'm not sure if this is how it was designed or if it's a bug but I'm experiencing an issue when trying to run the bellow example. Handlers that have been notified from tasks that consist the role "web" will not be flushed when the flush_handlers in located in the post_tasks section.
##### Steps To Reproduce:

```
- hosts: webservers
   handlers:
    - include: roles/common/handlers/main.yml

  pre_tasks:

  roles:
    - role : web

  post_tasks:

  - name: flushing handlers
    meta: flush_handlers

  - name: post tasks things
    shell: echo "etc..."
```
##### Expected Results:

flush_handlers to be executed successfully
##### Actual Results:

flush_handlers is never executed , it's confirmed we have takss notifying handlers from the role "web"
