### ISSUE TITLE
Allow retry/loops on blocks

### ISSUE THREAD

**Issue by arty-hlr** [ansible/ansible#83959]
### Summary

There seems to be no way to retry/loop blocks, which makes no sense unfortunately. There was already discussion about this years ago here: https://github.com/ansible/ansible/issues/46203 but nothing came out of it for blocks. I'd like to open this discussion again as I think many people (as is to be seen by the number of upvotes in the original issue) would use this.

Different potential uses:
- loop a whole block n times
- retry a whole block if failed until successful

Right now my experience is that `rescue` tasks in a block are not enough to "fix" failed tasks, unless the task is copy pasted in the rescue block, and that'd be only for one retry...

One specific use case I have:
- in an Exchange installation play, there is one step (prepare schema) that might fail, and requires a reboot before retrying. Unfortunately, there is no way to make that work in a block unless with some copy/paste that only works once...

![image](https://github.com/user-attachments/assets/a8b5f042-d80b-4556-a5d6-12827057aea5)

### Issue Type

Feature Idea

### Component Name

block

### Additional Information

Here an example from https://dev.to/nodeselector/retrying-groups-of-tightly-coupled-tasks-in-ansible-579d of how it might look like:
```yaml
- name: Group of tasks that are tightly coupled
  block:
  - name: Setup for the next task that needs to run after each failed attempt
    setting_up:
        some: prerequisite action

  - name: Some task that might fail
    failing_task:
        some: setting
    register: outcome
  retries: 3
  delay: 10
  until: outcome.result == 'success'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
