### ISSUE TITLE
Error in atomic_move when path is filename only

### ISSUE THREAD

**Issue by thorsteinbn** [ansible/ansible#83950]
### Summary

After upgrading to Ansible 2.16.11, I had an issue with the community.crypto.openssl_csr module, although I think this can be a problem for other modules as well. When defining a filename not containing a full path, the task fails. When changing path to include full path or relative path, the task works as expected.

I suspect this may be related to the following change https://github.com/ansible/ansible/pull/83718/files#diff-f349dd7dd94c979d979664b11f27222e562b7444ec38407a4a511614fc5248edR1688

### Issue Type

Bug Report

### Component Name

atomic_move

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.11]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.6 (main, Sep 12 2024, 21:12:04) [GCC 12.2.0] (/usr/local/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
CONFIG_FILE() = None
DEFAULT_LOAD_CALLBACK_PLUGINS(env: ANSIBLE_LOAD_CALLBACK_PLUGINS) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = auto
CONNECTION:
==========
paramiko_ssh:
____________
host_key_checking(env: ANSIBLE_HOST_KEY_CHECKING) = False
ssh:
___
host_key_checking(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

### OS / Environment

RHEL 8

### Steps to Reproduce

The following fails, when just supplying a filename in path
```
- name: Create CSR
  community.crypto.openssl_csr:
    path: selfsigned.csr
    common_name: "common-name"
    privatekey_path: "{{ key_file }}"
    organization_name: "XXXXXX"
```

To fix the issue, I changed the CSR task to include relative path, the following works:
```
- name: Create CSR
  community.crypto.openssl_csr:
    path: ./selfsigned.csr
    common_name: "common-name"
    privatekey_path: "{{ key_file }}"
    organization_name: "XXXXXX"
```

### Expected Results

I expect atomic_move to not fail when supplying just a filename in path.

### Actual Results

```console
File "/tmp/ansible_community.crypto.openssl_csr_payload_0h7qzfoi/ansible_community.crypto.openssl_csr_payload.zip/ansible_collections/community/crypto/plugins/module_utils/io.py", line 95, in write_file
    module.atomic_move(tmp_name, file_args['path'])
  File "/tmp/ansible_community.crypto.openssl_csr_payload_0h7qzfoi/ansible_community.crypto.openssl_csr_payload.zip/ansible/module_utils/basic.py", line 1762, in atomic_move
    dest_dir_stat = os.stat(os.path.dirname(b_dest))
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
