### ISSUE TITLE
tags are not inherited by role dependencies, breaking the dependencies

### ISSUE THREAD

**Issue by dannysauer** [ansible/ansible#83975]
### Summary

When a role has tags applied to it, dependencies should inherit those tags like the documentation implies.  This does not work.

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version

ansible [core 2.17.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sauer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sauer/venv/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/sauer/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/sauer/venv/ansible/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/home/sauer/venv/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = /etc/ansible/ansible.cfg
PAGER(env: PAGER) = less
```
```


### OS / Environment

```
(ansible) sauer@host:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

### Steps to Reproduce

<!--- Paste example playbooks or commands between quotes below -->
```yaml (paste below)
---
# file: site.yml
- name: stuff
  hosts: localhost
  gather_facts: true
  roles:
    - role: thing
      tags:
        - thing
```
```yaml
---
# file roles/thing/meta/main.yml
dependencies:
  - role: another
#    tags:
#      - thing
```

### Expected Results

When running `ansible-playbook --tags thing site.yml`, I expect tasks from both the `thing` role and the `another` role to run, because the tags from the role definition are inherited by dependent roles.

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#tag-inheritance-adding-tags-to-multiple-tasks
> If you want to apply the same tag or tags to multiple tasks without adding a tags line to every task, you can define the tags at the level of your play or block, or when you add a role or import a file. Ansible applies the tags down the dependency chain to all child tasks. With roles and imports, Ansible appends the tags set by the roles section or import to any tags set on individual tasks or blocks within the role or imported file. This is called tag inheritance. Tag inheritance is convenient because you do not have to tag every task. However, the tags still apply to the tasks individually.

### Actual Results

```console
`ansible-playbook --tags thing site.yml`
...

TASK [another : Validating arguments against arg spec 'main'] ******
```

Then the tasks in `thing` start going, skipping over the tasks in `another`.

Uncommenting the additional tagging in the role meta file's dependencies causes the tasks in `another` to run.  But that means keeping roles in sync with the playbook, which is horrible. :D
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
