### ISSUE TITLE
Make include_vars module concatenate the same list from different vars files instead of overwriting

### ISSUE THREAD

**Issue by w4hf** [ansible/ansible#83978]
### Summary

Is it possible to improve the builtin `include_vars` module so that it will be able to concatenate lists with the same name read from different vars files instead of overwriting the list ?
~~Exactly like the `hash_behaviour: merge` but for lists.~~
The order of the element of the list could be the order of the files read.

This will help enormously simplify the reading of the same list from different files.
Example of resulting complicated role is the infra.controller_configuration.filetree_read that is widely used in AWX/AAP configuration as code ([EXAMPLE](https://github.com/redhat-cop/controller_configuration/blob/devel/roles/filetree_read/tasks/organizations.yml))

This also helps keep the original variables instead of using intermediate variables therefore keeping the information of the original variables such as if they are vaulted or not.

### Issue Type

Feature Idea

### Component Name

include_vars.py

### Additional Information

Example : I have two files `vars1.yml` and `vars2.yml` under the folder `my_vars/` with the following content :

vars1.yml :
```yaml
my_list:
  - user: test1
    email: test1@test.com
  - user: test2
    email: test2@test.com
```

vars2.yml :
```yaml
my_list:
  - user: test3
    email: test3@test.com
```

The playbook
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Read vars
      ansible.builtin.include_vars:
        dir: my_vars/
    - name: Print
      ansible.builtin.debug:
        var: my_list
```

Should give the desired result (concatenated lists)
```
TASK [debug] ***********************************
ok: [localhost] => {
    "my_list": [
        {
            "email": "test1@test.com",
            "name": "test1"
        },
        {
            "email": "test2@test.com",
            "name": "test2"
        },
        {
            "email": "test3@test.com",
            "name": "test3"
        }
    ]
}
```

Instead of the current behavior (overwritten list) : 
```yaml
TASK [debug] ***********************************
ok: [localhost] => {
    "my_list": [
        {
            "email": "test3@test.com",
            "name": "test3"
        }
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/include_vars.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/include_vars.py)
* [`lib/ansible/plugins/action/include_vars.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/include_vars.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by s-hertel** [comment]
This can be achieved using the `combine` filter https://docs.ansible.com/ansible/latest/collections/ansible/builtin/combine_filter.html, for example:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - include_vars:
        file: "{{ item }}"
      loop: "{{ q('fileglob', 'my_vars/*') }}"
      register: include_vars

    - debug:
        msg: "{{ my_list }}"
      vars:
        my_list: "{{ include_vars.results | map(attribute='ansible_facts') | combine(list_merge='append') }}"
```

The include_vars module doesn't support apply `hash_behaviour` to individual vars files, it's just used to merge the vars result with the existing task variables. So even to merge dictionaries across files, you'd need to loop over individual files instead of using the dir option.
