### ISSUE TITLE
No error issued on `is defined` references a variable that reference an undefined variable

### ISSUE THREAD

**Issue by hv15** [ansible/ansible#83993]
### Summary

When I set some variables for a task, I expect that when these are referenced, that any issue with how the variables are defined causes an error (or some kind of message) in Ansible. When using `is defined` any error in the definition of a variable is masked, hiding any cause for why the variable isn't defined. Through this, mistakes in variable definitions might go unnoticed or lead to confusion.

### Issue Type

Bug Report

### Component Name

is defined behaviour

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/home/hans/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/hans/pytestansible/lib/python3.12/site-packages/ansible
  ansible collection location = /home/hans/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/hans/pytestansible/bin/ansible
  python version = 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805] (/home/hans/pytestansible/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ANSIBLE_NOCOWS=1 ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
CONFIG_FILE() = None
EDITOR(env: EDITOR) = /usr/bin/vim
```

### OS / Environment

ArchLinux

### Steps to Reproduce

Playbook:
```yaml
---
- name: test play
  hosts: all
  ignore_errors: true
  vars:
    test_dict:
      not: "sure"
    test_dict2:
      what: "is going on"
  tasks:
    - name: test1
      vars:
        hello: >
          {{ test_dict | ansible.builtin.combine(test_dict2,) }}
      ansible.builtin.debug:
        msg: "{{ hello }}"
      when: hello is defined    # this succeeds
    - name: test2
      vars:
        hello: >
          {{ test_dict | ansible.builtin.combine(test_dict2, test) }}
      ansible.builtin.debug:
        msg: "{{ hello }}"      # here we get a error message that `test` isn't defined
    - name: test3
      vars:
        hello: >
          {{ test_dict | ansible.builtin.combine(test_dict2, test) }}
      ansible.builtin.debug:
        msg: "{{ hello }}"
      when: hello is defined   # this is skipped, as `is defined` evaluates to `False`, but we get no error message about `test` not being defined
```

Command:
```
ANSIBLE_NOCOWS=1 ansible-playbook -vvvv -D ./test.yaml
```

### Expected Results

For test case `test3` I would expect the `is defined`, as part of evaluating variable `hello`, to error out (or show some message) due to `test` not being defined similar to the failure in `test2`.

### Actual Results

```console
ansible-playbook [core 2.17.4]
  config file = None
  configured module search path = ['/home/hans/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/hans/pytestansible/lib/python3.12/site-packages/ansible
  ansible collection location = /home/hans/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/hans/pytestansible/bin/ansible-playbook
  python version = 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805] (/home/hans/pytestansible/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
setting up inventory plugins
Loading collection ansible.builtin from 
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /etc/ansible/hosts inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /home/hans/pytestansible/lib/python3.12/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test.yaml *****************************************************************************************************************************************************************************************************************************************************************************************************************************************
Positional arguments: ./test.yaml
verbosity: 4
connection: ssh
become_method: sudo
tags: ('all',)
diff: True
inventory: ('/etc/ansible/hosts',)
forks: 5
1 plays in ./test.yaml

PLAY [test play] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /tmp/wtf/test.yaml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: hans
<localhost> EXEC /bin/sh -c 'echo ~hans && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/hans/.ansible/tmp `"&& mkdir "` echo /home/hans/.ansible/tmp/ansible-tmp-1727177243.4224443-61518-102959644351318 `" && echo ansible-tmp-1727177243.4224443-61518-102959644351318="` echo /home/hans/.ansible/tmp/ansible-tmp-1727177243.4224443-61518-102959644351318 `" ) && sleep 0'
Using module file /home/hans/pytestansible/lib/python3.12/site-packages/ansible/modules/setup.py
<localhost> PUT /home/hans/.ansible/tmp/ansible-local-615009jizqfb2/tmpnquk37cl TO /home/hans/.ansible/tmp/ansible-tmp-1727177243.4224443-61518-102959644351318/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/hans/.ansible/tmp/ansible-tmp-1727177243.4224443-61518-102959644351318/ /home/hans/.ansible/tmp/ansible-tmp-1727177243.4224443-61518-102959644351318/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/hans/.ansible/tmp/ansible-tmp-1727177243.4224443-61518-102959644351318/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/hans/.ansible/tmp/ansible-tmp-1727177243.4224443-61518-102959644351318/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [test] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /tmp/wtf/test.yaml:11
ok: [localhost] => {
    "msg": {
        "not": "sure",
        "what": "is going on"
    }
}

TASK [test2] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /tmp/wtf/test.yaml:18
skipping: [localhost] => {
    "false_condition": "hello is defined"
}

TASK [test3] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /tmp/wtf/test.yaml:25
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check 'hello | length > 0' failed. The error was: error while evaluating conditional (hello | length > 0): {{ test_dict | ansible.builtin.combine(test_dict2, test) }}\n: 'test' is undefined\n\nThe error appears to be in '/tmp/wtf/test.yaml': line 25, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      when: hello is defined\n    - name: test3\n      ^ here\n"
}
...ignoring

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=1  
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
