### ISSUE TITLE
Support upsert when merging vars

### ISSUE THREAD

**Issue by konstruktoid** [ansible/ansible#84009]
### Summary

When using variable dictionaries, eg for readability, `ansible` will replace the dict instead of updating or inserting the values.
Supporting  updating and inserting variables will reduce the amount of work need when using a large number of values in a variable dictionary.

Initial comment: https://github.com/konstruktoid/ansible-role-hardening/pull/723#discussion_r1744724708

Example using `yq`:

```sh
$ cat group_vars/all/test_vars.yml host_vars/localhost/mod_vars.yml
---
ipv4_sysctl_settings:
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.all.log_martians: 3
---
ipv4_sysctl_settings:
  net.ipv4.conf.all.log_martians: 0
  net.ipv4.conf.default.log_martians: 0
  this.is.a.test: 1
```
```sh
$ yq m -x group_vars/all/test_vars.yml host_vars/localhost/mod_vars.yml
ipv4_sysctl_settings:
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.all.log_martians: 0
  net.ipv4.conf.default.log_martians: 0
  this.is.a.test: 1
```

Compared to the `ansible` result:

```sh
$ ansible-playbook -c local -i 'localhost,' test.yml

PLAY [Various Ansible tests] *****************************************************************

TASK [Get sysctl settings] ******************************************************************
ok: [localhost] => {
    "msg": {
        "net.ipv4.conf.all.log_martians": 0,
        "net.ipv4.conf.default.log_martians": 0,
        "this.is.a.test": 1
    }
}

PLAY RECAP ******************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
``´

### Issue Type

Feature Idea

### Component Name

vars

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/lookup/vars.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/vars.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by bcoca** [comment]
The combine filter already does https://docs.ansible.com/ansible/latest/collections/ansible/builtin/combine_filter.html#parameter-list_merge

**Comment by konstruktoid** [comment]
Thanks @bcoca.
The  below works, but it's not pretty in my opinion. 
Any reason this isn't the default?

```yaml
---
- name: Various Ansible tests
  hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  tasks:
    - name: Set sysctl host vars as facts
      set_fact:
        pre_merge: "{{ ipv4_sysctl_settings }}"

    - name: Include group vars
      include_vars:
        file: group_vars/all/test_vars.yml

    - name: Combine sysctl settings
      set_fact:
        merged_post_include: "{{ ipv4_sysctl_settings | ansible.builtin.combine(pre_merge) }}"

    - name: Print merged sysctl settings
      debug:
        msg: "{{ merged_post_include }}"
```

```sh
$ ansible-playbook -c local -i 'localhost,' test.yml

PLAY [Various Ansible tests] ***************************************************

TASK [Gathering Facts] ********************************************************
ok: [localhost]

TASK [Set sysctl host vars as facts] *********************************************
ok: [localhost]

TASK [Include group vars] *****************************************************
ok: [localhost]

TASK [Combine sysctl settings] ************************************************
ok: [localhost]

TASK [Print merged sysctl settings] *********************************************
ok: [localhost] => {
    "msg": {
        "net.ipv4.conf.all.accept_redirects": 0,
        "net.ipv4.conf.all.accept_source_route": 0,
        "net.ipv4.conf.all.log_martians": 0,
        "net.ipv4.conf.default.log_martians": 0,
        "this.is.a.test": 1
    }
}

PLAY RECAP *******************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
