### ISSUE TITLE
setting get_url timeout seems to disable its timeout altogether

### ISSUE THREAD

**Issue by schichtnudelauflauf** [ansible/ansible#84010]
### Summary

Env: Debian Bookworm on x86_64, Ansible from repo.

### Issue Type

Bug Report

### Component Name

get_url

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.16]
  config file = /home/user/projectname/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/home/user/projectname/ansible.cfg) = True
CONFIG_FILE() = /home/user/projectname/ansible.cfg
DEFAULT_BECOME(/home/user/projectname/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/user/projectname/ansible.cfg) = ['/home/user/projectname/hosts']
DEFAULT_MANAGED_STR(/home/user/projectname/ansible.cfg) = Ansible managed: {file} modified on %Y>
INTERPRETER_PYTHON(/home/user/projectname/ansible.cfg) = auto_silent
RETRY_FILES_SAVE_PATH(/home/user/projectname/ansible.cfg) = /home/user/ansible

SHELL:
=====

sh:
__
remote_tmp(/home/user/projectname/ansible.cfg) = ~/.ansible/tmp
```

### OS / Environment

Debian Bookworm x86_64

### Steps to Reproduce

```yaml (paste below)
    - name: Download release archives
      ansible.builtin.get_url:
        url: "https://downloads.example.org/releases/{{ latest_known_version }}.tar.xz
        dest: "{{ playbook_dir }}/example/releases_bin/{{ latest_known_version }}.tar.xz
        force: false
        timeout: 60  # Difference is here
      loop: "{{ arches }}"
      tags: online
```

I am either ratelimited or some part of the link is slow, the release binary is about 500mb. So it happens that sometimes download takes longer than the default timeout of apparently 10 seconds. Thing aborts then because I set abort on any failure.

Then I set the timeout to 60 seconds to accomodate this.

### Expected Results

I expected a download to timeout after 60 seconds each.

### Actual Results

```console
The command does not abort after 60 seconds but seems to behave like no timeout at all.

EXEC /bin/sh -c '/usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1727276047.0849218-38762-109713046907924/AnsiballZ_get_url.py && sleep 0'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
