### ISSUE TITLE
Ansible plugin gcp_compute skipping

### ISSUE THREAD

**Issue by Hraesvelg** [ansible/ansible#84020]
### Summary

When i try to use gcp_compute plugin, ansible skip always the plugin. No specific error... just it skip the plugin and then it can"t load gcp_compute.yml config and finaly my inventory is empty

### Issue Type

Bug Report

### Component Name

gcp_compute

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.3]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu

### Steps to Reproduce

```yaml (paste below)
[defaults]
host_key_checking = False
inventory = gcp_compute.yml
interpreter_python = auto_silent

[inventory]
enable_plugins = host_list, script, auto, yaml, ini, toml, google.cloud.gcp_compute
```

```yaml (paste below)
plugin: google.cloud.gcp_compute
zones: # populate inventory with instances in these regions
  - us-central1-a
projects:
  - my-project
service_account_file: ./service_account.json
auth_kind: serviceaccount
keyed_groups:
  # Create groups from GCE labels
  - key: labels
    prefix: label
  - key: zone
    prefix: zone
hostnames:
  - my_hostname
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
```

### Expected Results

He should found all inventory

### Actual Results

```console
[WARNING]: Failed to load inventory plugin, skipping google.cloud.gcp_compute
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
