### ISSUE TITLE
ansible.builtin.uri loses response headers during redirects

### ISSUE THREAD

**Issue by buzz-tee** [ansible/ansible#84056]
### Summary

I am calling a webservice using ansible.builtin.uri and this webservice performs authentication through a series of complex redirects. During these redirects several cookies get set which need to be specified in subsequent calls.

The cookies are normally set via the Set-Cookie header, one header per cookie. During redirects only one Set-Cookie header is evaluated, thus further cookies are lost.

The reason for this behaviour lies in the exception handler of the `fetch_url` function: https://github.com/ansible/ansible/blob/50604e84615e239c2b83e0c55969dbf68e5de0cf/lib/ansible/module_utils/urls.py#L1253-L1274

Redirects result in HTTPError exceptions so code execution branches from the "normal" flow after the call to `open_url`. Like for normal responses the exception handling also converts response info keys to lower case (line 1270). However it does not concatenate duplicate headers as it is done by the non-exception code flow. The non-exception code does this in https://github.com/ansible/ansible/blob/50604e84615e239c2b83e0c55969dbf68e5de0cf/lib/ansible/module_utils/urls.py#L1224-L1233

## Suggestion
Adding these same normalizations to the exception handling code after line 1270 would fix this issue and all cookie headers would be preserved for the response.

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.12]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.virtualenvs/ansible-lbxw/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.virtualenvs/ansible-lbxw/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/home/user/.virtualenvs/ansible-lbxw/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
```

### OS / Environment

Ubuntu 22.04.4 LTS (jammy)

### Steps to Reproduce

```yaml
- name: Load landing page, init session
  ansible.builtin.uri:
    url: https://webservice.com/endpoint
    status_code: [401]
  register: _landing

- name: Login webservice
  ansible.builtin.uri:
    url: https://authservice.com/login.form
    body:
      username: "{{ username }}"
      password: "{{ password }}"
      login-form-type: pwd
    body_format: form-urlencoded
    headers:
      Cookie: "{{ _landing.set_cookie }}"
    register: _login

```

### Expected Results

```json
"_login": {
  "set_cookie": "SESSID=my-session, AUTH_PARAM=some-auth-data",
  ...
}
```

### Actual Results

```json
"_login": {
  "set_cookie": "SESSID=my-session",
  ...
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
