### ISSUE TITLE
argument_specs.yaml validation don't start if `include_role` have `tasks_from:`

### ISSUE THREAD

**Issue by ASLanin** [ansible/ansible#84058]
### Summary

Ansible do not check for the missed variables if `include_role` have `tasks_from:` parameter. And of cause works fine if no `tasks_from:` exists. 

### Issue Type

Bug Report

### Component Name

main

### Ansible Version

```console
$ ansible --version

ansible [core 2.15.2]
  config file = /home/user/git/path/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ANSIBLE_PIPELINING(/home/user/git/path/ansible/ansible.cfg) = True
CALLBACKS_ENABLED(/home/user/git/path/ansible/ansible.cfg) = ['profile_tasks']
COLOR_ERROR(/home/user/git/path/ansible/ansible.cfg) = bright yellow
CONFIG_FILE() = /home/user/git/path/ansible/ansible.cfg
DEFAULT_FORKS(/home/user/git/path/ansible/ansible.cfg) = 32
DEFAULT_HOST_LIST(/home/user/git/path/ansible/ansible.cfg) = ['/home/user/git/path/ansible/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/home/user/git/path/ansible/ansible.cfg) = /home/user/.pass
HOST_KEY_CHECKING(/home/user/git/path/ansible/ansible.cfg) = False

CONNECTION:
==========

local:
_____
pipelining(/home/user/git/path/ansible/ansible.cfg) = True

paramiko_ssh:
____________
host_key_checking(/home/user/git/path/ansible/ansible.cfg) = False
ssh_args(/home/user/git/path/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHo>

psrp:
____
pipelining(/home/user/git/path/ansible/ansible.cfg) = True

ssh:
___
host_key_checking(/home/user/git/path/ansible/ansible.cfg) = False
pipelining(/home/user/git/path/ansible/ansible.cfg) = True
ssh_args(/home/user/git/path/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHo>

winrm:
_____
pipelining(/home/user/git/path/ansible/ansible.cfg) = True
...skipping...
ANSIBLE_PIPELINING(/home/user/git/path/ansible/ansible.cfg) = True
CALLBACKS_ENABLED(/home/user/git/path/ansible/ansible.cfg) = ['profile_tasks']
COLOR_ERROR(/home/user/git/path/ansible/ansible.cfg) = bright yellow
CONFIG_FILE() = /home/user/git/path/ansible/ansible.cfg
DEFAULT_FORKS(/home/user/git/path/ansible/ansible.cfg) = 32
DEFAULT_HOST_LIST(/home/user/git/path/ansible/ansible.cfg) = ['/home/user/git/path/ansible/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/home/user/git/path/ansible/ansible.cfg) = /home/user/.pass
HOST_KEY_CHECKING(/home/user/git/path/ansible/ansible.cfg) = False

CONNECTION:
==========

local:
_____
pipelining(/home/user/git/path/ansible/ansible.cfg) = True

paramiko_ssh:
____________
host_key_checking(/home/user/git/path/ansible/ansible.cfg) = False
ssh_args(/home/user/git/path/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHo>

psrp:
____
pipelining(/home/user/git/path/ansible/ansible.cfg) = True

ssh:
___
host_key_checking(/home/user/git/path/ansible/ansible.cfg) = False
pipelining(/home/user/git/path/ansible/ansible.cfg) = True
ssh_args(/home/user/git/path/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHo>

winrm:
_____
pipelining(/home/user/git/path/ansible/ansible.cfg) = True```
```

### OS / Environment

>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
>uname -a
Linux homelin 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

```yaml
# playbook get error on missing SROOT_FOLDER var as intended
- name: testplaybook
  hosts: n01.prod
  gather_facts: false
  tasks:
    - debug:
        var: TEST_VAR
    - name: "test01 deployment"
      include_role:
        name: test1
        # tasks_from: main.yaml
# playbook do not get error on missing SROOT_FOLDER var
- name: testplaybook
  hosts: n01.prod
  gather_facts: false
  tasks:
    - debug:
        var: TEST_VAR
    - name: "test01 deployment"
      include_role:
        name: test1
        tasks_from: main.yaml # this line lead to the unwanted behavior 
# argument_specs.yaml for the test1 role
argument_specs:
  main:
    short_description: test role data for debug
    options:
      TEST_VAR:
        type: str
        required: true
        description: Test var - exist.
      SROOT_FOLDER:
        type: str
        required: true
        description: Test var - not exist.
```

### Expected Results

I expected that `ansible-playbook ./test.yaml` execution would fire error on missing variable in the arguments_spec.yaml if task file explicitly selected by `tasks_from: main.yaml` in the role include.

### Actual Results

```console
There is NO errors.
But I expect error:
TASK [test1 : Validating arguments against arg spec 'main' - test role data for debug] *****************************************************************************************
fatal: [n01.prod]: FAILED! => {"argument_errors": ["missing required arguments: SROOT_FOLDER"], "argument_spec_data": {"SROOT_FOLDER": {"description": "Test var - not exist.", "required": true, "type": "str"}, "TEST_VAR": {"description": "Test var - exist.", "required": true, "type": "str"}}, "changed": false, "msg": "Validation of arguments failed:\nmissing required arguments: SROOT_FOLDER", "validate_args_context": {"argument_spec_name": "main", "name": "test1", "path": "/home/user/git/path/ansible/roles/test1", "type": "role"}}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@ASLanin `ansible-core` 2.15 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by s-hertel** [comment]
This is due to the `.yaml` extension. The `tasks_from` field is used verbatim to find the entrypoint, so you could work around the issue by either omitting the extension from the `tasks_from` field or adding the extension to the entrypoint.

```yaml
tasks_from: main
```

or 

```yaml
argument_specs:
  main.yaml:
    ...
```

`tasks_from: {{ filename }}` loads the first found:

1) {{ filename }}
2) {{ filename }}.yml
3) {{ filename }}.yaml
4) {{ filename }}.json

The extensions aren't configurable, but match the default for the YAML_FILENAME_EXTENSIONS config https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/__init__.py#L395.

I'm not sure this is the correct precedence, but instead of only checking for a spec identical to {{ filename }}, we could check for a similar list:

1) {{ filename }}  # prefer the current behavior
2) {{ filename }}.yml  # handle extension-specific entrypoints in case there multiple files with the same name otherwise
3) {{ filename }}.yaml  # ^ ditto
4) {{ filename }}.json  # ^ ditto
5) {{ filename | splitext }}[0]  # handle tasks_from including an extension when the argument spec entrypoint does not

I also noticed that omitting `tasks_from` is not the same as `tasks_from: main` as I would have assumed. When `tasks_from` is omitted, `main.(yml|yaml|json)` is preferred and the `main` file is only used if it's the only candidate (but the `main` entrypoint is used for the arg spec, rather than one with a matching extension).
