### ISSUE TITLE
Ansible: ansible.windows.win_copy error. Could not find or access

### ISSUE THREAD

**Issue by NobeliY** [ansible/ansible#84051]
### Summary

I use win_copy to copy programs to the windows server, but it gives an error: could not find or access /home/u/Packages/
The sequence of actions:
1. synchronize. Copy from a trusted remote server to a local AWX server:
---
```
- name: Sync
      synchronize:
        recursive: yes
        src: "{{ hostvars['delegateMachine'].main_path }}/"
        dest: "/home/{{ hostvars['localMachine'].ansible_user }}/.ansible/tmp/Packages/"
        archive: no
        mode: push
        # owner: yes
        # group: yes
        rsync_path: "sudo rsync"
      delegate_to: delegateMachine`
```
---
2. shell: Change of owner and chmod
--- 
``` 
name: Change permissions for packages directory
      become: yes  
      ansible.builtin.shell: |
        chown {{ hostvars['localMachine'].ansible_user }}:{{ hostvars['localMachine'].ansible_user }} /home/{{ hostvars['localMachine'].ansible_user }}/Packages/ -R \
          && chmod 757 /home/{{ hostvars['localMachine'].ansible_user }}/.ansible/tmp/Packages/ -R `
```
---
3. win_copy:
---
```
- name: Copy Zabbix to Windows
      become: yes
      become_method: sudo
      become_user: "{{ hostvars['localMachine'].ansible_user }}"
      ansible.windows.win_copy:
        src: "{{ main_install_unix }}/Zabbix/"
        dest: C:/Packages/ZabbixAgent/
        mode: '0777'
        remote_src: no
      ignore_errors: no`
```
---
### Issue Type

Bug Report

### Component Name

rsync

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.0]
  config file = None
  configured module search path = ['/home/u/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/u/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
  jinja version = 3.0.3
  libyaml = True

```

### Configuration

```console
ansible default config by AWX on Kubernetes
```

### OS / Environment

Ubuntu 22.04 LTS (jammy)

## zabbix_run.yml
```
---
- name: Prepare installation Zabbix Agent
  hosts: localMachine
  gather_facts: yes
  tasks:
    - name: Sync
      synchronize:
        recursive: yes
        src: "{{ hostvars['delegateMachine'].main_path }}/"
        dest: "/home/{{ hostvars['localMachine'].ansible_user }}/.ansible/tmp/Packages/"

        archive: no
        mode: push
        # owner: yes
        # group: yes
        rsync_path: "sudo rsync"
      delegate_to: delegateMachine
    
    - name: Test pwd before chmod
      ansible.builtin.shell: pwd && ls -la
    
    - name: Change permissions for packages directory
      become: yes  
      ansible.builtin.shell: |
        chown {{ hostvars['localMachine'].ansible_user }}:{{ hostvars['localMachine'].ansible_user }} /home/{{ hostvars['localMachine'].ansible_user }}/Packages/ -R \
          && chmod 757 /home/{{ hostvars['localMachine'].ansible_user }}/.ansible/tmp/Packages/ -R 
        
    - name: Test pwd after chmod!!!
      ansible.builtin.shell: pwd && ls -la && ls -la /home/{{ ansible_user_id }}/.ansible/tmp/Packages/Zabbix/Win

- name: Install deb pkg (Zabbix Agent) in slave machines
  gather_facts: yes
  hosts: slave_servers
  vars:
    main_install_unix: "/home/{{ hostvars['localMachine'].ansible_user }}/.ansble/tmp/Packages"
    path_to_zabbix: "{{ main_install_unix }}/Zabbix"
    path_to_zabbix_unix: "{{ main_install_unix }}/Zabbix/Unix"
    zabbix_install_dir_win: C:/Packages/ZabbixAgent
    main_install_dir_win: C:/Packages

    path_to_bin_executable_file: /usr/sbin/zabbix_agentd
  tasks:
  - include_tasks: playbooks/zabbix.yml
```
### playbooks/zabbix.yml
```
--- 
- name: Block for Windows
  block:
    - name: Ping Windows servers
      ansible.windows.win_ping:

    - name: Check folder if not exists
      ansible.windows.win_file:
        path: "{{ zabbix_install_dir_win }}"
        state: directory
    - name: Test pwd on slave_servers
      ansible.windows.win_shell: |
        dir

    - name: Copy Zabbix to Windows
      become: yes
      become_method: sudo
      become_user: "{{ hostvars['localMachine'].ansible_user }}"
      ansible.windows.win_copy:
        src: "{{ main_install_unix }}/Zabbix/"
        dest: C:/Packages/ZabbixAgent/
        mode: '0777'
        remote_src: no
      ignore_errors: no

    - name: Install Zabbix on Windows
      ansible.windows.win_command: |
        C:\Packages\ZabbixAgent\bin\zabbix_agent2.exe --config C:\Packages\ZabbixAgent\conf\zabbix_agent2.conf --install
      args:
        chdir: C:\Packages\ZabbixAgent\conf\
      ignore_errors: yes

    - name: Start ZabbixAgent as service
      ansible.windows.win_service:
        name: "Zabbix Agent 2"
        state: started
  when: ansible_os_family == 'Windows'
  ignore_errors: true

- name: Block for Astra Linux
  block:
    - name: Ping server
      ansible.builtin.ping:
    - name: Check folders
      become: yes
      become_user: "{{ ansible_user_id }}"
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
      loop:
        - /usr/bin
        - /usr/sbin
        - /etc/zabbix
        - /usr/local/etc
        - /etc/systemd/system

    - name: Copy Zabbix on bin to Linux Server
      ansible.posix.synchronize:
        recursive: yes
        src: "{{ hostvars['delegateMachine'].path_to_zabbix }}/Unix/bin/"
        dest: "/usr/bin/"
        mode: push
        archive: no
        rsync_path: "sudo rsync"
      delegate_to: delegateMachine
      ignore_errors: no

    - name: Copy Zabbix on conf to Linux Server
      become_user: "{{ hostvars['delegateMachine'].ansible_user }}"
      remote_user: "{{ ansible_user_id }}"
      ansible.posix.synchronize:
        recursive: yes
        src: "{{ hostvars['delegateMachine'].path_to_zabbix }}/Unix/conf/"
        dest: "/etc/zabbix/"
        mode: push
        archive: no
        rsync_path: "sudo rsync"
      delegate_to: delegateMachine

    - name: Copy Zabbix on sbin to Linux Server
      become_user: "{{ hostvars['delegateMachine'].ansible_user }}"
      remote_user: "{{ ansible_user_id }}"
      ansible.posix.synchronize:
        recursive: yes
        src: "{{ hostvars['delegateMachine'].path_to_zabbix }}/Unix/sbin/"
        dest: "/usr/sbin/"
        mode: push
        archive: no
        rsync_path: "sudo rsync"
      delegate_to: delegateMachine

    - name: Change mod for sbin file
      become: true
      remote_user: "{{ ansible_user_id }}"
      ansible.builtin.shell: "chmod +x {{ path_to_bin_executable_file }}"
    
    - name: Copy Zabbix service runner file
      become_user: "{{ hostvars['delegateMachine'].ansible_user }}"
      remote_user: "{{ ansible_user_id }}"
      ansible.posix.synchronize:
        recursive: yes
        src: "{{ hostvars['delegateMachine'].path_to_zabbix }}/Unix/runner/"
        dest: "/etc/systemd/system/"
        mode: push
        archive: no
        rsync_path: "sudo rsync"
      delegate_to: delegateMachine
      ignore_errors: no

    - name: Copy Zabbix conf on /usr/local/etc to Linux Server
      become_user: "{{ hostvars['delegateMachine'].ansible_user }}"
      remote_user: "{{ ansible_user_id }}"
      ansible.posix.synchronize:
        recursive: yes
        src: "{{ hostvars['delegateMachine'].path_to_zabbix }}/Unix/conf/"
        dest: "/usr/local/etc/"
        mode: push
        archive: no
        rsync_path: "sudo rsync"
      delegate_to: delegateMachine

    - name: Start Zabbix Agent
      ansible.builtin.shell: "zabbix_agentd"
      ignore_errors: no
    
    - name: Verify Zabbix Agent
      ansible.builtin.shell: "cat /tmp/zabbix_agentd.log"

    - name: Start Zabbix Agent as service 
      become: true
      ansible.builtin.shell: |
        systemctl daemon-reload && systemctl start zabbix-agentd && systemctl enable zabbix-agentd
    
  when: ansible_os_family == 'Debian'
  ignore_errors: true
```

### Expected Results

I wanted to see the correct installation of the application and its correct launch

### Actual Results

```console
unrecognised<dolfin.rst.local> (0, b'/home/u\n', b'OpenSSH_8.7p1, OpenSSL 3.0.7 1 Nov 2022\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 55: Including file /etc/ssh/ssh_config.d/50-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf\r\ndebug2: checking match for \'final all\' host dolfin.rst.local originally dolfin.rst.local\r\ndebug3: /etc/ssh/ssh_config.d/50-redhat.conf line 3: not matched \'final\'\r\ndebug2: match not found\r\ndebug3: /etc/ssh/ssh_config.d/50-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1 (parse only)\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-]\r\ndebug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512]\r\ndebug1: configuration requests final Match pass\r\ndebug2: resolve_canonicalize: hostname dolfin.rst.local is address\r\ndebug1: re-parsing configuration\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 55: Including file /etc/ssh/ssh_config.d/50-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf\r\ndebug2: checking match for \'final all\' host dolfin.rst.local originally dolfin.rst.local\r\ndebug3: /etc/ssh/ssh_config.d/50-redhat.conf line 3: matched \'final\'\r\ndebug2: match found\r\ndebug3: /etc/ssh/ssh_config.d/50-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-]\r\ndebug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512]\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/runner/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/runner/.ssh/known_hosts2\'\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/runner/cp/64f2cf233b" does not exist\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to dolfin.rst.local [dolfin.rst.local] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x48\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 60000 ms remain after connect\r\ndebug1: identity file /runner/.ssh/id_rsa type -1\r\ndebug1: identity file /runner/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /runner/.ssh/id_dsa type -1\r\ndebug1: identity file /runner/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /runner/.ssh/id_ecdsa type -1\r\ndebug1: identity file /runner/.ssh/id_ecdsa-cert type -1\r\ndebug1: identity file /runner/.ssh/id_ecdsa_sk type -1\r\ndebug1: identity file /runner/.ssh/id_ecdsa_sk-cert type -1\r\ndebug1: identity file /runner/.ssh/id_ed25519 type -1\r\ndebug1: identity file /runner/.ssh/id_ed25519-cert type -1\r\ndebug1: identity file /runner/.ssh/id_ed25519_sk type -1\r\ndebug1: identity file /runner/.ssh/id_ed25519_sk-cert type -1\r\ndebug1: identity file /runner/.ssh/id_xmss type -1\r\ndebug1: identity file /runner/.ssh/id_xmss-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_8.7\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3ubuntu0.10\r\ndebug1: compat_banner: match: OpenSSH_8.9p1 Ubuntu-3ubuntu0.10 pat OpenSSH* compat 0x04000000\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to dolfin.rst.local:22 as \'u\'\r\ndebug1: load_hostkeys: fopen /runner/.ssh/known_hosts: No such file or directory\r\ndebug1: load_hostkeys: fopen /runner/.ssh/known_hosts2: No such file or directory\r\ndebug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory\r\ndebug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory\r\ndebug3: order_hostkeyalgs: no algorithms matched; accept original\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ext-info-c\r\ndebug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256\r\ndebug2: ciphers ctos: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr\r\ndebug2: ciphers stoc: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr\r\ndebug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512\r\ndebug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512\r\ndebug2: compression ctos: zlib@openssh.com,zlib,none\r\ndebug2: compression stoc: zlib@openssh.com,zlib,none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com\r\ndebug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com\r\ndebug2: compression stoc: none,zlib@openssh.com\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256\r\ndebug1: kex: host key algorithm: ssh-ed25519\r\ndebug1: kex: server->client cipher: aes256-gcm@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: client->server cipher: aes256-gcm@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: curve25519-sha256 need=32 dh_need=32\r\ndebug1: kex: curve25519-sha256 need=32 dh_need=32\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: SSH2_MSG_KEX_ECDH_REPLY received\r\ndebug1: Server host key: ssh-ed25519 SHA256:wtXLqFvqakwmHHWKtc9tSCa5z8RgklGrtjI92ZRI4gY\r\ndebug1: load_hostkeys: fopen /runner/.ssh/known_hosts: No such file or directory\r\ndebug1: load_hostkeys: fopen /runner/.ssh/known_hosts2: No such file or directory\r\ndebug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory\r\ndebug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory\r\ndebug1: SELinux support disabled\r\nWarning: Permanently added \'dolfin.rst.local\' (ED25519) to the list of known hosts.\r\ndebug1: check_host_key: hostkey not known or explicitly trusted: disabling UpdateHostkeys\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey out after 4294967296 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey in after 4294967296 blocks\r\ndebug1: Will attempt key: /runner/.ssh/id_rsa \r\ndebug1: Will attempt key: /runner/.ssh/id_dsa \r\ndebug1: Will attempt key: /runner/.ssh/id_ecdsa \r\ndebug1: Will attempt key: /runner/.ssh/id_ecdsa_sk \r\ndebug1: Will attempt key: /runner/.ssh/id_ed25519 \r\ndebug1: Will attempt key: /runner/.ssh/id_ed25519_sk \r\ndebug1: Will attempt key: /runner/.ssh/id_xmss \r\ndebug2: pubkey_prepare: done\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 7\r\ndebug1: SSH2_MSG_EXT_INFO received\r\ndebug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>\r\ndebug1: kex_input_ext_info: publickey-hostbound@openssh.com (unrecognised)\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug3: start over, passed a different list publickey,password\r\ndebug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: keyboard-interactive,password\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Trying private key: /runner/.ssh/id_rsa\r\ndebug3: no such identity: /runner/.ssh/id_rsa: No such file or directory\r\ndebug1: Trying private key: /runner/.ssh/id_dsa\r\ndebug3: no such identity: /runner/.ssh/id_dsa: No such file or directory\r\ndebug1: Trying private key: /runner/.ssh/id_ecdsa\r\ndebug3: no such identity: /runner/.ssh/id_ecdsa: No such file or directory\r\ndebug1: Trying private key: /runner/.ssh/id_ecdsa_sk\r\ndebug3: no such identity: /runner/.ssh/id_ecdsa_sk: No such file or directory\r\ndebug1: Trying private key: /runner/.ssh/id_ed25519\r\ndebug3: no such identity: /runner/.ssh/id_ed25519: No such file or directory\r\ndebug1: Trying private key: /runner/.ssh/id_ed25519_sk\r\ndebug3: no such identity: /runner/.ssh/id_ed25519_sk: No such file or directory\r\ndebug1: Trying private key: /runner/.ssh/id_xmss\r\ndebug3: no such identity: /runner/.ssh/id_xmss: No such file or directory\r\ndebug2: we did not send a packet, disable method\r\ndebug3: authmethod_lookup password\r\ndebug3: remaining preferred: ,password\r\ndebug3: authmethod_is_enabled password\r\ndebug1: Next authentication method: password\r\ndebug3: send packet: type 50\r\ndebug2: we sent a password packet, wait for reply\r\ndebug3: receive packet: type 52\r\ndebug1: Enabling compression at level 6.\r\nAuthenticated to dolfin.rst.local ([dolfin.rst.local]:22) using "password".\r\ndebug1: pkcs11_del_provider: called, provider_id = (null)\r\ndebug1: setting up multiplex master socket\r\ndebug3: muxserver_listen: temporary control path /runner/cp/64f2cf233b.CKHrGMMgkA90YeBE\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug3: fd 4 is O_NONBLOCK\r\ndebug3: fd 4 is O_NONBLOCK\r\ndebug1: channel 0: new [/runner/cp/64f2cf233b]\r\ndebug3: muxserver_listen: mux listener channel 0 fd 4\r\ndebug2: fd 3 setting TCP_NODELAY\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x20\r\ndebug1: control_persist_detach: backgrounding master process\r\ndebug2: control_persist_detach: background process is 27\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug1: forking to background\r\ndebug1: Entering interactive session.\r\ndebug1: pledge: id\r\ndebug2: set_control_persist_exit_time: schedule exit in 60 seconds\r\ndebug1: multiplexing control connection\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug3: fd 5 is O_NONBLOCK\r\ndebug1: channel 1: new [mux-control]\r\ndebug3: channel_post_mux_listener: new mux channel 1 fd 5\r\ndebug3: mux_master_read_cb: channel 1: hello sent\r\ndebug2: set_control_persist_exit_time: cancel scheduled exit\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x00000001 len 4\r\ndebug2: mux_master_process_hello: channel 1 client version 4\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x10000004 len 4\r\ndebug2: mux_master_process_alive_check: channel 1: alive check\r\ndebug3: mux_client_request_alive: done pid = 29\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x10000002 len 67\r\ndebug2: mux_master_process_new_session: channel 1: request tty 0, X 0, agent 0, subsys 0, term "", cmd "/bin/sh -c \'echo ~u && sleep 0\'", env 0\r\ndebug3: mux_master_process_new_session: got fds stdin 6, stdout 7, stderr 8\r\ndebug1: channel 2: new [client-session]\r\ndebug2: mux_master_process_new_session: channel_new: 2 linked to control channel 1\r\ndebug2: channel 2: send open\r\ndebug3: send packet: type 90\r\ndebug3: receive packet: type 80\r\ndebug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0\r\ndebug3: receive packet: type 91\r\ndebug2: channel_input_open_confirmation: channel 2: callback start\r\ndebug2: client_session2_setup: id 2\r\ndebug1: Sending command: /bin/sh -c \'echo ~u && sleep 0\'\r\ndebug2: channel 2: request exec confirm 1\r\ndebug3: send packet: type 98\r\ndebug3: mux_session_confirm: sending success reply\r\ndebug2: channel_input_open_confirmation: channel 2: callback done\r\ndebug2: channel 2: open confirm rwindow 0 rmax 32768\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: channel 2: rcvd adjust 2097152\r\ndebug3: receive packet: type 99\r\ndebug2: channel_input_status_confirm: type 99 id 2\r\ndebug2: exec request accepted on channel 2\r\ndebug3: receive packet: type 96\r\ndebug2: channel 2: rcvd eof\r\ndebug2: channel 2: output open -> drain\r\ndebug2: channel 2: obuf empty\r\ndebug2: chan_shutdown_write: channel 2: (i0 o1 sock -1 wfd 7 efd 8 [write])\r\ndebug2: channel 2: output drain -> closed\r\ndebug3: receive packet: type 98\r\ndebug1: client_input_channel_req: channel 2 rtype exit-status reply 0\r\ndebug3: mux_exit_message: channel 2: exit message, exitval 0\r\ndebug3: receive packet: type 98\r\ndebug1: client_input_channel_req: channel 2 rtype eow@openssh.com reply 0\r\ndebug2: channel 2: rcvd eow\r\ndebug2: chan_shutdown_read: channel 2: (i0 o3 sock -1 wfd 6 efd 8 [write])\r\ndebug2: channel 2: input open -> closed\r\ndebug3: receive packet: type 97\r\ndebug2: channel 2: rcvd close\r\ndebug3: channel 2: will not send data after close\r\ndebug2: channel 2: send close\r\ndebug3: send packet: type 97\r\ndebug2: channel 2: is dead\r\ndebug2: channel 2: gc: notify user\r\ndebug3: mux_master_session_cleanup_cb: entering for channel 2\r\ndebug2: channel 1: rcvd close\r\ndebug2: channel 1: output open -> drain\r\ndebug2: chan_shutdown_read: channel 1: (i0 o1 sock 5 wfd 5 efd -1 [closed])\r\ndebug2: channel 1: input open -> closed\r\ndebug2: channel 2: gc: user detached\r\ndebug2: channel 2: is dead\r\ndebug2: channel 2: garbage collecting\r\ndebug1: channel 2: free: client-session, nchannels 3\r\ndebug3: channel 2: status: The following connections are open:\r\n  #1 mux-control (t16 nr0 i3/0 o1/16 e[closed]/0 fd 5/5/-1 sock 5 cc -1)\r\n  #2 client-session (t4 r0 i3/0 o3/0 e[write]/0 fd -1/-1/8 sock -1 cc -1)\r\n\r\ndebug2: channel 1: obuf empty\r\ndebug2: chan_shutdown_write: channel 1: (i3 o1 sock 5 wfd 5 efd -1 [closed])\r\ndebug2: channel 1: output drain -> closed\r\ndebug2: channel 1: is dead (local)\r\ndebug2: channel 1: gc: notify user\r\ndebug3: mux_master_control_cleanup_cb: entering for channel 1\r\ndebug2: channel 1: gc: user detached\r\ndebug2: channel 1: is dead (local)\r\ndebug2: channel 1: garbage collecting\r\ndebug1: channel 1: free: mux-control, nchannels 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug3: channel 1: status: The following connections are open:\r\n  #1 mux-control (t16 nr0 i3/0 o3/0 e[closed]/0 fd 5/5/-1 sock 5 cc -1)\r\n\r\ndebug2: Received exit status from master 0\r\ndebug2: set_control_persist_exit_time: schedule exit in 60 seconds\r\n')
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
