### ISSUE TITLE
regex_replace fails to to work on passed in strings, OK on variables

### ISSUE THREAD

**Issue by hobson42** [ansible/ansible#84059]
### Summary

ansible.builtin.regex_replace works fine when used on a variable
```
   set_fact: 
     var: "{{ aVariable | ansible.builtin.regex('old','new') }}" 
```
but does nothing to the text, if it is prevouslt filtered, thus
```
   set_fact:
     wrong: "{{ my_var1+myavr2 | string |  ansible.builtin.regex('old','new') }}"  
```

### Issue Type

Bug Report

### Component Name

ansible.builtin.regex_replace

### Ansible Version

```console
$ ansible --version 
ansible [core 2.16.11]
  config file = /home/ian/.ansible.cfg
  configured module search path = ['/home/ian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ian/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ian/.local/bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
BECOME_PASSWORD_FILE(/home/ian/.ansible.cfg) = /home/ian/.ansible/password
CONFIG_FILE() = /home/ian/.ansible.cfg
DEFAULT_BECOME(/home/ian/.ansible.cfg) = True
DEFAULT_HOST_LIST(/home/ian/.ansible.cfg) = ['/home/ian/Ansible/playbooks/config/hosts']
DEFAULT_LOG_PATH(/home/ian/.ansible.cfg) = /home/ian/Ansible/logfile
DEFAULT_VAULT_PASSWORD_FILE(/home/ian/.ansible.cfg) = /home/ian/.ansible/password
```

### OS / Environment

PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

### Steps to Reproduce

```yaml (paste below)
---
# test.yml
#
- hosts: "elara.hcs"
  become: yes
  gather_facts: false      

  vars:
    bitfolkBackup: "/home/ian/Backupfiles/Bitfolk/setB/"
    dir: "/home/ian"

  tasks:
        
  - name: Compute restore dir
    set_fact:
      r_dir: "{{ bitfolkBackup+dir }}"
      
  - name: Remove double slashes
    set_fact:
      restore_dir1: "{{ r_dir | regex_replace('//','/') }}"
 
  - name: Do them both together
    set_fact:
       restore_dir2: "{{ bitfolkBackup+dir | string | regex_replace('//','/') }}"
 
  - name: show result of 2 steps
    debug:
      var: restore_dir1
      
  - name: show result of one step
    debug:    
      var: restore_dir2

  - name: Report error
    debug: msg="The two results are not the same"
    when: (restore_dir1 != restore_dir2)

```

### Expected Results

 ansible.builtin.regex('old','new') should replace old with new in both cases. It fails when string provided is previously filtered. 

### Actual Results

```console
PLAY [elara.hcs] ***********************************************************************************************

TASK [Compute restore dir] *************************************************************************************
ok: [elara.hcs]

TASK [Remove double slashes] ***********************************************************************************
ok: [elara.hcs]

TASK [Do them both together] ***********************************************************************************
ok: [elara.hcs]

TASK [show result of 2 steps] **********************************************************************************
ok: [elara.hcs] => {
    "restore_dir1": "/home/ian/Backupfiles/Bitfolk/setB/home/ian"
}

TASK [show result of one step] *********************************************************************************
ok: [elara.hcs] => {
    "restore_dir2": "/home/ian/Backupfiles/Bitfolk/setB//home/ian"
}

TASK [Report error] ********************************************************************************************
ok: [elara.hcs] => {
    "msg": "The two results are not the same"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
This is not a bug, it's the expected result of Jinja's operator precedence. You are adding together `bitfolkBackup` and `dir | string | regex_replace('//','/') `, and since `dir` does not contain any double forward slashes nothing gets replaced.

```yaml
  - name: Do them both together
    set_fact:
       restore_dir2: "{{ (bitfolkBackup ~ dir) | regex_replace('//','/') }}"
```
