### ISSUE TITLE
yum module should have option to list updates without "--show-duplicates" argument

### ISSUE THREAD

**Issue by mehulgogri-hpe** [ansible/ansible#84062]
### Summary

I am trying to get the list of packages that has the update available and it should only list the latest available package version.

```
- name: Use the Yum module to get a list of installed packages
  yum:
    list: updates
```

because this runs `yum list --show-duplicates <package>` in the backend, this command ends up listing same packages with multiple available version. 

There should be a parameter for this yum and dnf module to do yum list without --show-duplicates.

### Issue Type

Feature Idea

### Component Name

yum and dnf

### Additional Information

We could use this feature as follow:

```
- name: Use the Yum module to get a list of installed packages
  yum:
    list: updates
    show-duplicates: false
```

This will help to just list the latest available version of the packages to update to.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
