### ISSUE TITLE
deb822_repository: Allow multiple sources in a single file 

### ISSUE THREAD

**Issue by ltog** [ansible/ansible#84060]
### Summary

Using the deb822_repository module, I am trying to write multiple APT sources into a single file. However, when trying to do that by writing multiple tasks, the file gets overwritten each time. When trying to provide a list it won't work at all.

I would like to request a new feature that allows to do that.

Also: Would you be willing to accept PRs for this?

### Issue Type

Feature Idea

### Component Name

deb822_repository

### Additional Information

Here is how it could look:

### Variant 1: Two tasks

```yaml
- name: Write source foo
  deb822_repository:
    - name: somename
      types: deb
      uris: https://example.org/foo/
      suites: "{{ ansible_distribution_release }}"
      components: main
      signed_by: /usr/share/keyrings/some-keyring.gpg

- name: Write source foo
  deb822_repository:
    - name: somename
      types: deb
      uris: https://example.org/bar/
      suites: "{{ ansible_distribution_release }}"
      components: main
      signed_by: /usr/share/keyrings/some-keyring.gpg
```

### Variant 2: Providing a list

```yaml
- name: Write source foo
  deb822_repository:
    repositories:
      - name: somename
        types: deb
        uris: https://example.org/foo/
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: /usr/share/keyrings/some-keyring.gpg
      - name: somename
        types: deb
        uris: https://example.org/bar/
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: /usr/share/keyrings/some-keyring.gpg
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
