### ISSUE TITLE
Deprecate a few esoteric playbook syntax cases

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#84101]
### Summary

The core team discussed and agreed to deprecate three relatively ancient and undocumented playbook syntax features that exist in the code but did not have tests, and caused difficulties with new feature implementations:

```yaml
  # DEPRECATION 1
  - name: action-as-dict (static-only, template-to-dict never worked anyway)
    action:
      module: "{{ 'echo' }}"
      args: "{{ echo_args }}"  # note that `module` and `args` are children of `action`
    vars:
      echo_args:
        a: 1'
```

```yaml
  # DEPRECATION 3
  - name: kv and task args at the same time
    echo: kv1=kv
    args:
      kv1: task_arg
      kv2: task_arg
```

(The following case was more-or-less fixed by arg finalization and chaining, so was excluded from the deprecation)

```yaml
  # DEPRECATION 2 - EXCLUDED
  - name: silent shadowing of task args dict resolved from a template by variable params dict resolved from a template
    echo: '{{ variable_params }}'
    args: '{{ task_args }}'
    vars:
      variable_params:
        a: from_vp
        c: from_vp
      task_args:
        a: from_task_args
        b: from_task_args  # note that `b` is completely omitted because all task args are lost
```

### Issue Type

Feature Idea

### Component Name

mod_args.py

### Additional Information

To be clear: these deprecations *do not* affect the general ability to use dynamic/templated values for the `action` keyword, dynamic arguments, or old-style k=v arguments.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
