### ISSUE TITLE
git module does not update origin on remote when repo url changes

### ISSUE THREAD

**Issue by sethrh** [ansible/ansible#84114]
### Summary

When my deployment token in gitlab expires, I update it in ansible. However, if the repository has already been cloned, ansible uses the git remote value on the clone instead of the url specified in the playbook. 

This: 

    - name: Fetch Repository
      git: 
      repo: https://gitlab+deploy-token-38:blahblahblah@gitlab.company.com/group/repository.git
      dest: /path/to/dest
      version: master
      force: yes
      update: yes

Generates an access denied error from gitlab, even though the token is valid. 

Checking on the remote, the origin URL doesn't get updated and still uses the old token. 
    
    $ cd /path/to/dest
    $ git remote -v 
    origin https://gitlab+deploy-token-37:blahblahblah@gitlab.company.com/group/repository.git
 
Similar/same issues have been reported here: https://github.com/ansible/ansible/issues/12931 and again here https://github.com/ansible/ansible/issues/26369 but both were (apparently) closed without being fixed. 

### Issue Type

Bug Report

### Component Name

git

### Ansible Version

```console
$ ansible --version
core 2.15.0
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Mac OS Sonoma host, linux remote. 

### Steps to Reproduce

See above and prior tickets. 

Clone a repository at a URL. 
Change the URL
The git origin url does not change

### Expected Results

The URL specified in `repo:` should update the origin URL. Maybe the existing behavior is desirable to prevent clobbering an existing repository, perhaps there should be an option like "update-origin-url: true" to make it explicit. 

### Actual Results

```console
The user & password was not updated on the remote so the git operations all failed with access denied errors.
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/git.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/git.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by s-hertel** [comment]
@sethrh I'm unable to reproduce this on 2.15 or more recent versions. Can you please provide a minimal reproducer? The module shouldn't ignore a mismatch between the remote and the repo (though depending on how you're triggering this issue, it might be better handled by another module, like community.general.git_config). Here's the playbook I used to try to reproduce the issue:

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone repository
    git:
      repo: https://s-hertel:{{ token1 }}@github.com/s-hertel/private-repo.git
      dest: /tmp/test_git_module
      version: HEAD

  - name: Fetch from another URL
    git:
      repo: https://s-hertel:{{ token2 }}@github.com/s-hertel/private-repo.git
      dest: /tmp/test_git_module
      version: HEAD
      force: yes
      update: yes
```

The fetch task includes `"remote_url_changed": true` in the result, and changing to the dest directory shows the URL for origin has the new token. Embedding the token in the URL is not good practice though, using a .netrc file would be better.
