### ISSUE TITLE
Version test fails when variable is created from output of shell module

### ISSUE THREAD

**Issue by ohmydds** [ansible/ansible#84128]
### Summary

Creating version variables from the shell module's output, the version test fails.
Creating version variables manually with the same format, the version test succeeds.

I didn't notice this was an issue until comparing xx.xx.xx.89 to xx.xx.xx.100 which I assume is failing to assert that 89 is less than 100.

I found a similar issue which led me to checking the type:
https://github.com/ansible/ansible/issues/69975

When I assign the variable manually it's `AnsibleUnicode`
The variable created from shell command's output is `NativeJinjaUnsafeText`.

I've tried passing the variable through the string filter to convert `NativeJinjaUnsafeText` to something that works but it did not work.

I've tried using the different version_types but none produce the desired results (or they fail stating invalid semantic version)

Are there any workarounds I can implement to get around this issue?

### Issue Type

Bug Report

### Component Name

ansible.builtin.version

### Ansible Version

```console
ansible [core 2.17.5]
  config file = /Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg
  configured module search path = ['/Users/$username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/$username/.local/lib/venv/venv/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/$username/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/$username/.local/lib/venv/venv/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)] (/Users/$username/.local/lib/venv/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
CONFIG_FILE() = /Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg
DEFAULT_BECOME_ASK_PASS(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = False
DEFAULT_GATHER_SUBSET(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = ['all', '!hardware', '!facter', '!ohai']
DEFAULT_REMOTE_USER(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = ubuntu
DEFAULT_STDOUT_CALLBACK(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = yaml
DEFAULT_VAULT_IDENTITY_LIST(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = ['tier-6@~/.dds-vault-client.sh', 'tier-7@~/.dds-vault-client.sh']
DEPRECATION_WARNINGS(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = False
EDITOR(env: EDITOR) = vim
INTERPRETER_PYTHON(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = auto_silent
MAX_FILE_SIZE_FOR_DIFF(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = 208896
PAGER(env: PAGER) = less

CALLBACK:
========

default:
_______
display_skipped_hosts(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
remote_user(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = ubuntu

ssh:
___
pipelining(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = True
remote_user(/Users/$username/Projects/ansible/provisioning/ansible_cloud/ansible.cfg) = ubuntu
```

### OS / Environment

Local machine: Mac OS Sonoma 14.4
Remote machine: Ubuntu 22

### Steps to Reproduce

```yaml (paste below)
#!/usr/bin/env -S ansible-playbook -i hosts
---
- name: Version example
  hosts: chrome-test-1.example.com
  become: true
  vars:
    chrome_version_manual: "129.0.6668.100"
    chromedriver_version_manual: "129.0.6668.89"
  tasks:
    - name: Check for existing ChromeDriver
      ansible.builtin.stat:
        path: "{{ chrome_user.home_dir }}/bin/chromedriver"
      register: "chromedriver_exists"
      changed_when: false

    - name: Get existing ChromeDriver version
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          {{ chrome_user.home_dir }}/bin/chromedriver --version | awk -F ' ' '{ print $2 }'
        executable: "/bin/bash"
      register: "chromedriver_installed_version_query"
      when: (chromedriver_exists.stat.isreg is defined and chromedriver_exists.stat.isreg)
      changed_when: false
      check_mode: false

    - name: Get Chrome version
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          google-chrome --version | awk -F ' ' '{ print $3 }'
        executable: "/bin/bash"
      register: "chrome_installed_version_query"
      changed_when: false
      check_mode: false

    - name: Set Chrome version facts
      ansible.builtin.set_fact:
        chrome_installed_version: "{{ chrome_installed_version_query.stdout | string }}"
        chrome_major_version: "{{ chrome_installed_version_query.stdout | split('.') | first | string }}"

    - name: Set chromedriver version facts
      ansible.builtin.set_fact:
        chromedriver_installed_version: "{{ chromedriver_installed_version_query.stdout | string }}"
        chromedriver_major_version: "{{ chromedriver_installed_version_query.stdout | split('.') | first | string }}"
      when: (chromedriver_exists.stat.isreg is defined and chromedriver_exists.stat.isreg)

    - name: Set ChromeDriver archive fact
      ansible.builtin.set_fact:
        chromedriver_download_url: 'https://storage.googleapis.com/chrome-for-testing-public/{{ chrome_installed_version }}/linux64/chromedriver-linux64.zip'
        chromedriver_archive: "chromedriver-{{ chrome_major_version }}-linux64.zip"

    - name: Chromedriver Versions
      ansible.builtin.debug:
        msg:
          - "### FROM CMD"
          - "Installed Version: {{ chromedriver_installed_version }}"
          - "Available Version: {{ chrome_installed_version }}"
          - "Installed Version Type: {{ chromedriver_installed_version | type_debug }}"
          - "Available Version Type: {{ chrome_installed_version | type_debug }}"
          - "### MANUAL"
          - "Installed Version Manual: {{ chromedriver_version_manual }}"
          - "Available Version Manual: {{ chrome_version_manual }}"
          - "Installed Version Manual Type: {{ chromedriver_version_manual | type_debug }}"
          - "Available Version Manual Type: {{ chrome_version_manual | type_debug }}"

    - name: Version test examples
      ansible.builtin.assert:
        that:
          - chromedriver_version_manual is ansible.builtin.version(chrome_version_manual, operator='lt')  # Succeeds
          - chromedriver_installed_version is ansible.builtin.version(chrome_major_version, operator='lt')  # Fails

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 sr et
```

### Expected Results

Expected assertions to succeed.

### Actual Results

```console
$ ./chrome.yml

PLAY [Version example] *****************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [chrome-test-1.example.com]

TASK [Check for existing ChromeDriver] *************************************************************************************************************************************
ok: [chrome-test-1.example.com]

TASK [Get existing ChromeDriver version] ***********************************************************************************************************************************
ok: [chrome-test-1.example.com]

TASK [Get Chrome version] **************************************************************************************************************************************************
ok: [chrome-test-1.example.com]

TASK [Set Chrome version facts] ********************************************************************************************************************************************
ok: [chrome-test-1.example.com]

TASK [Set chromedriver version facts] **************************************************************************************************************************************
ok: [chrome-test-1.example.com]

TASK [Set ChromeDriver archive fact] ***************************************************************************************************************************************
ok: [chrome-test-1.example.com]

TASK [Chromedriver Versions] ***********************************************************************************************************************************************
ok: [chrome-test-1.example.com] =>
  msg:
  - '### FROM CMD'
  - 'Installed Version: 129.0.6668.89'
  - 'Available Version: 129.0.6668.100'
  - 'Installed Version Type: NativeJinjaUnsafeText'
  - 'Available Version Type: NativeJinjaUnsafeText'
  - '### MANUAL'
  - 'Installed Version Manual: 129.0.6668.89'
  - 'Available Version Manual: 129.0.6668.100'
  - 'Installed Version Manual Type: AnsibleUnicode'
  - 'Available Version Manual Type: AnsibleUnicode'

TASK [Version test examples] ***********************************************************************************************************************************************
fatal: [chrome-test-1.example.com]: FAILED! => changed=false
  assertion: chromedriver_installed_version is ansible.builtin.version(chrome_major_version, operator='lt')
  evaluated_to: false
  msg: Assertion failed

PLAY RECAP *****************************************************************************************************************************************************************
chrome-test-1.example.com : ok=8    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by flowerysong** [comment]
You have quite a bit going on in your reproducer, but this doesn't appear to be a bug.
The failing assertion is:
```
chromedriver_installed_version is ansible.builtin.version(chrome_major_version, operator='lt')
```
`chrome_major_version` is defined here:
```
        chrome_major_version: "{{ chrome_installed_version_query.stdout | split('.') | first | string }}"
```

So this is a more minimal version of what you're doing:
```yaml
- hosts: localhost
  tasks:
    - shell: |
        echo 129.0.6668.100
        echo 129.0.6668.89
      register: result

    - set_fact:
        chromedriver_installed_version: "{{ result.stdout_lines.1 }}"
        chrome_major_version: "{{ result.stdout | split('.') | first | string }}"

    - debug:
        msg:
          - "Installed Version: {{ chromedriver_installed_version }}"
          - "Installed Version Type: {{ chromedriver_installed_version | type_debug }}"
          - "Major Version: {{ chrome_major_version }}"
          - "Major Version Type: {{ chrome_major_version | type_debug }}"

    - assert:
        that: chromedriver_installed_version is ansible.builtin.version(chrome_major_version, operator='lt')
```

Output:
```plain
TASK [debug] *******************************************************************
ok: [localhost] => 
    msg:
    - 'Installed Version: 129.0.6668.89'
    - 'Installed Version Type: AnsibleUnsafeText'
    - 'Major Version: 129'
    - 'Major Version Type: NativeJinjaUnsafeText'

TASK [assert] ******************************************************************
fatal: [localhost]: FAILED! => 
    assertion: chromedriver_installed_version is ansible.builtin.version(chrome_major_version,
        operator='lt')
```
Version `129.0.6668.89` is not less than `129`, so this is the correct result for this task. If I change it so that it's comparing to a higher version, the assertion passes.

```plain
TASK [debug] *******************************************************************
ok: [localhost] => 
    msg:
    - 'Installed Version: 129.0.6668.89'
    - 'Installed Version Type: AnsibleUnsafeText'
    - 'Major Version: 130'
    - 'Major Version Type: NativeJinjaUnsafeText'

TASK [assert] ******************************************************************
ok: [localhost] => 
    changed: false
    msg: All assertions passed
```
