### ISSUE TITLE
`ansible.builtin.yum:` list always return "repo": "@System" as result

### ISSUE THREAD

**Issue by yhzs8** [ansible/ansible#84123]
### Summary

when I try running the following:
```
- name: Retrieve all installed RPM information
  ansible.builtin.yum:
    list=installed
  register: rpm_packages

- name: debug
  ansible.builtin.debug:
    var: rpm_packages.results
```

the result has always "repo": "@System" in every entry despite when running `dnf list --installed`, the repo varies. for instance:
`rpm_packages.results` entry:
```
{
            "arch": "noarch",
            "envra": "0:yum-4.7.0-20.el8.noarch",
            "epoch": "0",
            "name": "yum",
            "nevra": "0:yum-4.7.0-20.el8.noarch",
            "release": "20.el8",
            "repo": "@System",
            "version": "4.7.0",
            "yumstate": "installed"
        }
```
and the corresponding `dnf list --installed | grep yum` resulted in:
```
yum.noarch                                                 4.7.0-20.el8                                  @anaconda
```

### Issue Type

Bug Report

### Component Name

dnf

### Ansible Version

```console
ansible [core 2.13.13]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mrorange/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mrorange/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/mrorange/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mrorange/.local/bin/ansible
  python version = 3.8.20 (default, Sep  7 2024, 18:35:08) [GCC 11.4.0]
  jinja version = 3.1.4
  libyaml = False
```
update: also tested on 2.16.11, (last known working version before broken in 2.17: https://github.com/ansible/ansible/issues/82068) still same issue

### Configuration

```console
ansible-config dump --only-changed
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['<our local path>']
```

### OS / Environment

Target node: RHEL8.10

Trying to running newer version of ansible on the control node (2.17.5) resulting in another issue stated in  https://github.com/ansible/ansible/issues/82068 so need to fallback to version 2.13.13.

### Steps to Reproduce

```yaml (paste below)
- name: Retrieve all installed RPM information
  ansible.builtin.yum:
    list=installed
  register: rpm_packages

- name: debug
  ansible.builtin.debug:
    var: rpm_packages.results
```

### Expected Results

{
            "arch": "noarch",
            "envra": "0:yum-4.7.0-20.el8.noarch",
            "epoch": "0",
            "name": "yum",
            "nevra": "0:yum-4.7.0-20.el8.noarch",
            "release": "20.el8",
            "repo": "@anaconda",
            "version": "4.7.0",
            "yumstate": "installed"
        }

### Actual Results

```console
{
            "arch": "noarch",
            "envra": "0:yum-4.7.0-20.el8.noarch",
            "epoch": "0",
            "name": "yum",
            "nevra": "0:yum-4.7.0-20.el8.noarch",
            "release": "20.el8",
            "repo": "@System",
            "version": "4.7.0",
            "yumstate": "installed"
        }
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/dnf.py)
* [`lib/ansible/modules/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dnf.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@yhzs8 `ansible-core` 2.13 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by yhzs8** [comment]
As advised by the bot, retested on 2.16.11 (last known working version before `dnf` is broken towards RHEL8 https://github.com/ansible/ansible/issues/82068), same result.
```
ansible [core 2.16.11]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mrorange/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/mrorange/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mrorange/.local/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 08:52:12) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = False
```

**Comment by yhzs8** [comment]
also tried `ansible.builtin.dnf` instead of `ansible.builtin.yum`, same result:

```
- name: Retrieve all installed RPM information
  ansible.builtin.dnf:
    list=installed
  register: rpm_packages

- name: debug
  ansible.builtin.debug:
    var: rpm_packages.results
 ```
