### ISSUE TITLE
ansible.builtin.unarchive fails to extract single file from .tar.gz archive with just this file

### ISSUE THREAD

**Issue by senarclens** [ansible/ansible#84142]
### Summary

Running eg the following task

```yaml
- name: Extract archive
  ansible.builtin.unarchive:
    remote_src: yes
    src: 'https://github.com/extrawurst/gitui/releases/download/v0.26.3/gitui-linux-x86_64.tar.gz'
    dest: '{{ download_dir }}'
    include:
     - gitui
```

fails. Note that this archive contains only a single file called `gitui`. However the following two tasks work as expected:

```yaml
- name: Extract archive
  ansible.builtin.unarchive:
    remote_src: true
    src: 'https://github.com/jesseduffield/lazygit/releases/download/v0.44.1/lazygit_0.44.1_Linux_x86_64.tar.gz'
    dest: '{{ download_dir }}'
    include:
      - lazygit

- name: Extract archive
  ansible.builtin.unarchive:
    remote_src: yes
    src: 'https://github.com/extrawurst/gitui/releases/download/v0.26.3/gitui-linux-x86_64.tar.gz'
    dest: '{{ download_dir }}'
```

In the first case, the archive contains three files (LICENSE, README.md and lazygit). The second case is the exact same task as the failing one, however not limited to the single `gitui` file it includes.

The failure is:
```
TASK [Extract archive] **********************************************************************************************************************************************************************
fatal: [sandbox.bulme.at]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/root/.ansible/tmp/ansible-tmp-1729266248.625658-212277-25726237746138/gitui-linux-x86_643ik238tk.tar.gz\". Make sure the required command to extract the file is installed.\nCommand \"/usr/bin/unzip\" could not handle archive:   End-of-central-directory signature not found.  Either this file is not\n  a zipfile, or it constitutes one disk of a multi-part archive.  In the\n  latter case the central directory and zipfile comment will be found on\n  the last disk(s) of this archive.\nunzip:  cannot find zipfile directory in one of /root/.ansible/tmp/ansible-tmp-1729266248.625658-212277-25726237746138/gitui-linux-x86_643ik238tk.tar.gz or\n        /root/.ansible/tmp/ansible-tmp-1729266248.625658-212277-25726237746138/gitui-linux-x86_643ik238tk.tar.gz.zip, and cannot find /root/.ansible/tmp/ansible-tmp-1729266248.625658-212277-25726237746138/gitui-linux-x86_643ik238tk.tar.gz.ZIP, period.\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: xz: (stdin): File format not recognized\n/usr/bin/tar: Child returned status 1\n/usr/bin/tar: Error is not recoverable: exiting now\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: /usr/bin/tar: gitui: Not found in archive\n/usr/bin/tar: Exiting with failure status due to previous errors\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: bzip2: (stdin) is not a bzip2 file.\n/usr/bin/tar: Child returned status 2\n/usr/bin/tar: Error is not recoverable: exiting now\n"}
```

### Issue Type

Bug Report

### Component Name

ansible.builtin.unarchive

### Ansible Version

```console
$ ansible --version

ansible [core 2.16.3]
  config file = /home/gerald/repos/bulme/infra/ansible/ansible.cfg
  configured module search path = ['/home/gerald/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/gerald/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.7 (main, Oct  3 2024, 15:15:22) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = /home/gerald/repos/bulme/infra/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/gerald/repos/bulme/infra/ansible/ansible.cfg) = ['/home/gerald/repos/bulme/infra/ansible/inventory.yml']
DEFAULT_MANAGED_STR(/home/gerald/repos/bulme/infra/ansible/ansible.cfg) = "Ansible managed: generated on %Y-%m-%d %H:%M:%S by {uid} on {host}"
EDITOR(env: EDITOR) = vim
```
```


### OS / Environment

controller: kubuntu 24.10
host: ubuntu jammy

### Steps to Reproduce

<!--- Paste example playbooks or commands between quotes below -->
```yaml (paste below)
- name: Extract archive
  ansible.builtin.unarchive:
    remote_src: yes
    src: 'https://github.com/extrawurst/gitui/releases/download/v0.26.3/gitui-linux-x86_64.tar.gz'
    dest: '{{ download_dir }}'
    include:
     - gitui
```

run the above task as part of any playbook but make sure to define {{ download_dir }}

### Expected Results

A single file `gitui` is extracted after the task finishes.

### Actual Results

```console
TASK [Extract archive] **********************************************************************************************************************************************************************
fatal: [sandbox.bulme.at]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/root/.ansible/tmp/ansible-tmp-1729266248.625658-212277-25726237746138/gitui-linux-x86_643ik238tk.tar.gz\". Make sure the required command to extract the file is installed.\nCommand \"/usr/bin/unzip\" could not handle archive:   End-of-central-directory signature not found.  Either this file is not\n  a zipfile, or it constitutes one disk of a multi-part archive.  In the\n  latter case the central directory and zipfile comment will be found on\n  the last disk(s) of this archive.\nunzip:  cannot find zipfile directory in one of /root/.ansible/tmp/ansible-tmp-1729266248.625658-212277-25726237746138/gitui-linux-x86_643ik238tk.tar.gz or\n        /root/.ansible/tmp/ansible-tmp-1729266248.625658-212277-25726237746138/gitui-linux-x86_643ik238tk.tar.gz.zip, and cannot find /root/.ansible/tmp/ansible-tmp-1729266248.625658-212277-25726237746138/gitui-linux-x86_643ik238tk.tar.gz.ZIP, period.\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: xz: (stdin): File format not recognized\n/usr/bin/tar: Child returned status 1\n/usr/bin/tar: Error is not recoverable: exiting now\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: /usr/bin/tar: gitui: Not found in archive\n/usr/bin/tar: Exiting with failure status due to previous errors\n\nCommand \"/usr/bin/tar\" could not handle archive: Unable to list files in the archive: bzip2: (stdin) is not a bzip2 file.\n/usr/bin/tar: Child returned status 2\n/usr/bin/tar: Error is not recoverable: exiting now\n"}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/unarchive.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/unarchive.py)
* [`lib/ansible/modules/unarchive.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/unarchive.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by Akasurde** [comment]
@senarclens Thanks for reporting this issue. I am not able to reproduce this issue.

With `gnutar` I can unarchive both files.
With `bsdtar` both tasks fail individually (which is expected).

What is the output of `tar` on the system which is failing - 

```
tar --version
bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.12 liblzma/5.4.3 bz2lib/1.0.8
```

**Comment by senarclens** [comment]
```shell
> tar --version
tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
```

Did you try to extract an archive with only one file limiting the extraction to this one file (eg.     `include: gitui`)? Without the include it also works fine for me.

**Comment by flowerysong** [comment]
> Without the include it also works fine for me.

That's because your include is incorrect.

https://github.com/jesseduffield/lazygit/releases/download/v0.44.1/lazygit_0.44.1_Linux_x86_64.tar.gz contains files named `LICENSE`, `README`, and `lazygit`, the last of which matches your include on that task. https://github.com/extrawurst/gitui/releases/download/v0.26.3/gitui-linux-x86_64.tar.gz contains just one file, and it's named `./gitui`. This does not match your include, so extraction fails.

```yaml
- hosts: localhost
  vars:
    download_dir: /var/tmp
  tasks:
    - name: Extract archive
      ansible.builtin.unarchive:
        remote_src: yes
        src: https://github.com/extrawurst/gitui/releases/download/v0.26.3/gitui-linux-x86_64.tar.gz
        dest: '{{ download_dir }}'
        include:
         - ./gitui
```

Output:
```
TASK [Extract archive] *********************************************************
task path: /home/ec2-user/test.yml:6
changed: [localhost] => 
    changed: true
    dest: /var/tmp
    extract_results:
        cmd:
        - /bin/gtar
        - --extract
        - -C
        - /var/tmp
        - -z
        - -f
        - /home/ec2-user/.ansible/tmp/ansible-tmp-1729373712.132985-721028-255031241617180/gitui-linux-x86_64hm634rod.tar.gz
        - ./gitui
        err: ''
        out: ''
        rc: 0
    gid: 0
    group: root
    handler: TgzArchive
    mode: '01777'
    owner: root
    size: 4096
    src: /home/ec2-user/.ansible/tmp/ansible-tmp-1729373712.132985-721028-255031241617180/gitui-linux-x86_64hm634rod.tar.gz
    state: directory
    uid: 0
```

It may be possible to improve this experience, but `unarchive` is a big pile of ugly so it's also possible that this is the best that can be done.
