### ISSUE TITLE
Permission denied when user has group permissions

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#8414]
##### Issue Type:

Bug Report
##### Ansible Version:

I noticed this issue with both `ansible 1.6.6` and `ansible 1.7` (`devel`), I don't know about older versions.
##### Environment:
- Host machine: `Ubuntu 13.10 64 bits`
- Managed machine: Tried several VM images for `Debian Wheezy 32 bits`
##### Summary:

Adding a user in a group (using the `group` module) and, right after that, trying to make this user write in a folder he has write access to through this group only (without being the owner of the folder) gets denied permissions.
##### Steps To Reproduce:

Here is a minimal playbook to execute to reproduce the issue. Note that you need to change the username if not using a Vagrant machine.

``` yaml
- hosts: all
  gather_facts: no
  remote_user: vagrant

  tasks:

  - name: Ensure group testgroup is present
    group: name=testgroup state=present
    sudo: yes

  - name: Ensure user vagrant is in testgroup
    user: >
      append=yes
      groups=testgroup
      name=vagrant
    sudo: yes

  - name: Ensure testfolder exists
    file: >
      path=/testfolder
      state=directory
      owner=nobody
      group=testgroup
      mode=2070
    sudo: yes

  - name: Ensure testfile exists
    command: touch /testfolder/testfile
    tags: only_touch
```
##### Expected Results:

The last task should create `testfile` as expected (and return `changed`/`ok`) as the user is in the `testgroup` group and the `testfolder` folder was created with `rwx` permissions for `testgroup`.
##### Actual Results:

The results depends on how you execute the playbook:
- Executing all the playbook _but_ the last task and then **running the `touch` command manually is successful** through SSH
- **Executing the entire playbook fails** when it runs the last task: 

```
failed: [default] => {"changed": true, "cmd": ["touch", "/var/www/testfolder/testfile"], "delta": "...", "end": "...", "rc": 1, "start": "..."}
stderr: touch: cannot touch `/var/www/testfolder/testfile': Permission denied
```
- Since, when running the commands manually, you have to logout and login again so that your group permissions apply, I was assuming that this would apply here, but **running the entire playbook multiple times fails** the same way
- Executing the entire playbook (failure) and then **only the last command using the `touch_only` tag is successful**!
