### ISSUE TITLE
apt_repository not support http_proxy when add ppa repo

### ISSUE THREAD

**Issue by AlexAugustJr** [ansible/ansible#84162]
### Summary

When ansible.builtin.app_reporitory call apt-key task failed because can't connect to keyserver behind proxy server. Trying add vars {http|https}_proxy to environment and apt.conf all settings ignored.  ansible.builtin.apt_key module support http_proxy from environment https://github.com/ansible/ansible/blob/stable-2.12/lib/ansible/modules/apt_key.py#L198

Still actual after fix in https://github.com/ansible/ansible/issues/42534

### Issue Type

Bug Report

### Component Name

ansible.builtin.apt_repository

### Ansible Version

```console
2.12.10
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 22.0.4

### Steps to Reproduce

```
- apt_repository:
    repo: 'ppa:git-core/ppa'
    state: absent
    validate_certs: false
    update_cache: yes
  environment:
    http_proxy: http://proxy.example.com:8080
  become: yes
```

### Expected Results

repo been added

### Actual Results

```console
apt-ket can't connect to hkp://keyserver.ubuntu.com:80
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
