### ISSUE TITLE
"NO" always interpreted as boolean

### ISSUE THREAD

**Issue by dbond007** [ansible/ansible#84174]
### Summary

I am extracting fields from certificates and comparing their details to see if a new cert needs to be issued. When working with country codes, if the country code is NO (Norway), it will be interpreted as False, this happens even when cast as a string with | string. Only way it to add additional characters for example a space or "". But this only happens with the values retrieved from the certificate, if I have created a variable and defined it with "NO" it is a string.
idrac_cert_country_code: "NO"  this is ok
but 
idrac_current_country_code: "{{ idrac_cert_info.subject.C | string' }}"
taken from a certificate is always a boolean
 
The result is - 'False matches NO : False'

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/david/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
- name: Get the idrac cert
  community.crypto.get_certificate:
    host: "{{ idrac_ip }}"
    port: 443
  delegate_to: "{{ idrac_management_delegate }}"
  register: idrac_cert_info

- name: Extract attributes from certificate
  ansible.builtin.set_fact:
  idrac_current_country_code: "{{ idrac_cert_info.subject.C | string' }}"
 # idrac_current_country_code: "{{ idrac_cert_info.subject.C if idrac_cert_info.subject.C != False else 'NO' }}"
# idrac_current_country_code: "{{ ' NO' | string if idrac_cert_info.subject.C == 'NO' or idrac_cert_info.subject.C is boolean and not idrac_cert_info.subject.C else idrac_cert_info.subject.C | string }}" # working, space in front also works if using '\"NO\"' but then has "" in the string

- name: Do issued cert attributes match
  ansible.builtin.set_fact:
    idrac_current_match_country_code: "{{ idrac_current_country_code | string is search( idrac_cert_country_code | string ) }}"

- name: The current state of the certificate
  debug:
    msg:
      - "{{ idrac_current_country_code | string }} matches {{ idrac_cert_country_code | string }} : {{ idrac_current_match_country_code }}"

```

### Expected Results

TASK [ansible-role-idrac_baseline : The current state of the certificate] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [server] => 
  msg:
  - 'NO matches NO : True'

### Actual Results

```console
TASK [ansible-role-idrac_baseline : The current state of the certificate] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [server] => 
  msg:
  - 'False matches NO : False'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
