### ISSUE TITLE
_remote_md5 fails when passing -K but no sudo password is required. 

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#8418]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel b9a5242f03) last updated 2014/08/04 09:22:22 (GMT +1000)
##### Environment:

N/A
##### Summary:

When running e.g. the unarchive module in an ansible-playbook in sudo mode against a server and passing -K (ask sudo password) to a server that doesn't require a password to sudo, it fails with the message `dest '/target/directory'  must be an existing dir`. 

The source of this message the unarchive action_plugin, and that plugin believes that the directory does not exist because the `runner._remote_md5` call returns `INVALIDMD5SUM`. 

It would be good to get the error message improved. 
##### Steps To Reproduce:

Have a server with sudo (-u user) -i not require a password. 
Use unarchive to unarchive against the target server as the sudo user

```
  hosts: target

  tasks:
  - get_url: url="https://github.com/ansible/ansible-examples/archive/master.zip" dest=/var/tmp/ansible-examples.zip

  - unarchive: src="/var/tmp/ansible-examples.zip" dest="/var/tmp/" copy=no
```

Then run that playbook with the -K option and enter a password. 
##### Expected Results:

A message along the lines of 'You sent a password to a system that didn't ask for one'
Or ignoring the password if it is not required. 
##### Actual Results:

Failure with the message `dest '/target/directory' must be an existing dir`
