### ISSUE TITLE
Fedora 41 Server - Could not import the libdnf5 python module

### ISSUE THREAD

**Issue by openmarmot** [ansible/ansible#84206]
### Summary

When I try to run ansible to perform DNF updates against a fresh Fedora 41 Server install the Ansible DNF module errors out with "Could not import the libdnf5 python module". However this is installed by default in Fedora 41

### Issue Type

Bug Report

### Component Name

dnf

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/andrew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/andrew/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/andrew/.local/bin/ansible
  python version = 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = /usr/bin/nano
```

### OS / Environment

Fedora 41 Server Edition. Left all choices as default
Linux localhost.localdomain 6.11.4-301.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 20 15:02:33 UTC 2024 x86_64 GNU/Linux

### Steps to Reproduce

Client : Fedora 41 Workstation. I installed Ansible with 'sudo dnf install ansible -y' and then ran this ansible template
Target : Fedora 41 Server. This was a fresh install, taking all defaults

Before running you will want to SSH to the server once in order to accept the fingerprint.

Note that package "python3-libdnf-0.73.3-1.fc41.x86_64" is already installed by default on Fedora 41 Server Edition.

```yaml (paste below)
# do some inital setup tasks on a new fedora server vm
# ansible-playbook -i your_server_ip, -u andrew --ask-pass --ask-become-pass fedora-initial.yml

- name: Configure Fedora server
  hosts: all
  become: yes
  
  vars_prompt:
    - name: "public_key"
      prompt: "Enter the public SSH key"
      private: no

  tasks:
    - name: Ensure user exists and has wheel
      user:
        name: "{{ ansible_user }}"
        state: present
        groups: wheel
        append: yes

    - name: Add public key to the user
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_key }}"

    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Ensure Cockpit service is stopped
      ansible.builtin.systemd:
        name: cockpit.socket
        state: stopped

    - name: Ensure Cockpit does not start at boot
      ansible.builtin.systemd:
        name: cockpit.socket
        enabled: no

    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Reboot the server
      reboot:

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted

```

### Expected Results

I expect the Ansible DNF module to install all updates with DNF

### Actual Results

```console
TASK [Update all packages] ****************************************************************************************
fatal: [192.168.1.100]: FAILED! => {"changed": false, "failures": [], "msg": "Could not import the libdnf5 python module using /usr/bin/python3 (3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]). Please install python3-libdnf5 package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
`python3-libdnf-0.73.3-1.fc41.x86_64` isn't the correct package.  `python3-libdnf5` is required, note the suffix of `5`.

**Comment by openmarmot** [comment]
> `python3-libdnf-0.73.3-1.fc41.x86_64` isn't the correct package. `python3-libdnf5` is required, note the suffix of `5`.

ah yup sure enough. Installing python3-libdnf5 fixes the Ansible DNF module functionality. 
Interestingly this was not a issue with Fedora 40. Ansible must use python3-libdnf on Fedora 40.

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/action/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/dnf.py)
* [`lib/ansible/modules/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dnf.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by mkrizek** [comment]
> Ansible must use python3-libdnf on Fedora 40.

By default ansible-core uses whatever is the default package manager for the OS on the target system.

* For Fedora 40 it is dnf4 that is implemented using Python bindings provided by `python3-libdnf` package.
* For Fedora 41 it is dnf5 that is implemented using Python bindings provided by `python3-libdnf5` package.

In a playbook you can just do:
```yaml
- name: install packages
  dnf:
    name: "{{ list_of_packages }}"
    state: present
```

and ansible-core will select the underlying module (either dnf4 or dnf5) automatically (unless you specify it manually). But as with any module you are expected to install the module's dependencies yourself.

If you have further questions please stop by the Ansible Forum:

* [Ansible Forum](https://forum.ansible.com)

See this page for a complete and up to date list of communication channels and their purposes:

* <https://docs.ansible.com/ansible/latest/community/communication.html>
