### ISSUE TITLE
ansible.builtin.user: home created with wrong (non-existent) GID

### ISSUE THREAD

**Issue by cbugneac-nex** [ansible/ansible#84243]
### Summary

Sporadically on RHEL 7.9 the user is created with wrong GID for created home directory.

### Issue Type

Bug Report

### Component Name

ansible.builtin.user

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.12]
  config file = /Users/***/ansible/ansible.cfg
  configured module search path = ['/Users/***/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/***/ansible/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/***/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/***/ansible/.venv/bin/ansible
  python version = 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.3.9.4)] (/Users/***/ansible/.venv/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
N/A
```

### OS / Environment

Target OS: RHEL 7.9
Management system: MacOS 14.7.1 , GutHub Runner with Ubuntu Linux 22.04

### Steps to Reproduce

```yaml (paste below)
# defaults/main.yml:
oracle_user: oracle
oracle_user_id: 1012
oracle_user_home: "/home/{{ oracle_user }}"
oracle_user_shell: /bin/bash
oracle_group: oinstall
oracle_group_id: "{{ oracle_user_id }}"

#tasks/main.yml:
- name: Add oracle group
  ansible.builtin.group:
    name: "{{ oracle_group }}"
    gid: "{{ oracle_group_id }}"
    state: present
  tags: oracle

- name: Add oracle user
  ansible.builtin.user:
    name: "{{ oracle_user }}"
    uid: "{{ oracle_user_id }}"
    group: "{{ oracle_group }}"
    home: "{{ oracle_user_home }}"
    shell: "{{ oracle_user_shell }}"
    state: present
  tags: oracl
```

### Expected Results

Home for user `oracle` created with correct group owner id, i.e. 1012.

### Actual Results

```console
Home directory created with wrong (non-existent) user id 1003 which doesn't exist in /etc/group.


# ll /home
total 0
drwx------. 5 ec2-user ec2-user 195 Sep 30 06:13 ec2-user
drwx------. 2 oracle       1003  83 Oct 22 15:28 oracle
drwx------. 2 splunk   splunk    62 Sep 30 06:10 splunk
drwx------. 4 ssm-user ssm-user 111 Oct 30 09:24 ssm-user
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/user.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/user.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
Are you sure that this directory didn't already exist before you ran the task? The timestamp is suspiciously old compared to `ssm-user`'s:
```
drwx------. 2 oracle       1003  83 Oct 22 15:28 oracle
[...]
drwx------. 4 ssm-user ssm-user 111 Oct 30 09:24 ssm-user
```

**Comment by cbugneac-nex** [comment]
I'm not actually sure TBH, it's on one server which happened this issue.
Shouldn't the module detect that the home directory has wrong group owner and correct it ?
PS: I've run the playbook second time and it doesn't detect the difference in home group id. 
Based on https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#parameter-create_home the home is created if user doesn't exist

**Comment by flowerysong** [comment]
No, the module just adds the flag for `useradd` to create a home directory; if the path already exists it's not recreated or modified:
```
-m, --create-home
           Create the user's home directory if it does not exist.
```

**Comment by cbugneac-nex** [comment]
In this case I will just make sure the home dir is created explicitely before user.

```yaml
- name: Create home directory for oracle user
  ansible.builtin.file:
    path: "{{ oracle_user_home }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: '0700'
    state: directory
  tags: oracle
```
