### ISSUE TITLE
Hide `ansible_host` in the delegate_to output

### ISSUE THREAD

**Issue by e-minguez** [ansible/ansible#84260]
### Summary

When running a task with `delegate_to` with `ansible_host` being set, it shows both the host and the `ansible_host` value. 

```
TASK [Wait for port 6443 to be open (via hypervisor)] **************************
Tuesday 05 November 2024  08:11:58 +0000 (0:02:14.111)       0:02:17.759 ****** 
ok: [localhost -> hypervisor(10.1.2.3)]
```

Sometimes this is not intended as `ansible_host` can be an internal hostname/IP and ideally that behaviour should be configurable.

### Issue Type

Feature Idea

### Component Name

default callback output plugin

### Additional Information

For example this task:

```yaml
    - name: Wait for port 6443 to be open (via hypervisor)
      when: is_vm == True
      ansible.builtin.wait_for:
        port: 6443
        delay: 10
        timeout: 3600
        host: "{{ host.ip }}"
      delegate_to: "{{ hypervisor }}"
```

When having an ansible inventory like:

```
[hypervisors]
edge288 ansible_host=10.1.2.3
```

Returns the following output:

```
TASK [Wait for port 6443 to be open (via hypervisor)] **************************
Tuesday 05 November 2024  08:11:58 +0000 (0:02:14.111)       0:02:17.759 ****** 
ok: [localhost -> hypervisor(10.1.2.3)]
```

I _think_ this is the part of the code affected, where it appends the `ansible_host` to the output if it is set.
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/__init__.py#L195C76-L197

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
