### ISSUE TITLE
Group variables get mixed up when the same host is part of multiple groups

### ISSUE THREAD

**Issue by fildafer** [ansible/ansible#84320]
### Summary

I'm trying to deploy an application that has a different frontend for each feature and some shared components as backends. Every time I deploy a new feature frontend, I need to update the shared "control plane" with the name of the feature and other parameters, which I set as group variables. 

My static inventory looks like this:

```yaml
all:
  children:
    _customer1:
      vars:
        customer_name: "customer1"
      children:      
        _app_server_1:
          vars:
            application_name: "application-1"
          hosts:
            app-server-1:
              ansible_host: 192.168.61.100
            shared-control-plane:
              ansible_host: 192.168.61.101
        _app_server_2:
          vars:
            application_name: "application-2"
          hosts:
            app-server-2:
              ansible_host: 192.168.61.102
            shared-control-plane:
              ansible_host: 192.168.61.101
        _app_server_3:
          vars:
            application_name: "application-3"
          hosts:
            app-server-3:
              ansible_host: 192.168.61.103
            shared-control-plane:
              ansible_host: 192.168.61.101
```

The host `shared-control-plane` is the same in all three groups, but the variable `application_name` is set to a different value in each group.

Unfortunately, though, if I run the playbook against the groups `_app_server_1` or `_app_server_2`, the value of the variable `application_name` for the host `shared-control-plane` is always "application-3"

The issue happens both if I set `hosts: _app_server_2` or `hosts: _app_server_1` in the playbook, and if I set `hosts: all` and then limit the run with `--limit _app_server_1` or `--limit _app_server_2` in the command line.

See below for an example playbook and role to replicate the issue.

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.12]
  config file = /home/debian/ansible/ansible.cfg
  configured module search path = ['/home/debian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/debian/ansible_venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/debian/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/debian/ansible_venv/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/home/debian/ansible_venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING(/home/debian/ansible/ansible.cfg) = False
CALLBACKS_ENABLED(/home/debian/ansible/ansible.cfg) = ['ansible.posix.profile_tasks']
CONFIG_FILE() = /home/debian/ansible/ansible.cfg
DEFAULT_NO_TARGET_SYSLOG(/home/debian/ansible/ansible.cfg) = True
DEFAULT_TIMEOUT(/home/debian/ansible/ansible.cfg) = 120
HOST_KEY_CHECKING(/home/debian/ansible/ansible.cfg) = False

CONNECTION:
==========

local:
_____
pipelining(/home/debian/ansible/ansible.cfg) = False

paramiko_ssh:
____________
host_key_checking(/home/debian/ansible/ansible.cfg) = False
timeout(/home/debian/ansible/ansible.cfg) = 120

psrp:
____
pipelining(/home/debian/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/home/debian/ansible/ansible.cfg) = False
pipelining(/home/debian/ansible/ansible.cfg) = False
reconnection_retries(/home/debian/ansible/ansible.cfg) = 3
timeout(/home/debian/ansible/ansible.cfg) = 120

winrm:
_____
pipelining(/home/debian/ansible/ansible.cfg) = False
```

### OS / Environment

$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

### Steps to Reproduce

Put the static inventory provided in the summary in the file `inventories/static_inventory_test.yaml`.

Create a role called `test_role` in `roles/test_role/tasks/main.yaml` with the following content:

```yaml
- name: Print the value of the variable "application_name" for each host
  ansible.builtin.debug:
    msg: "App name for the host {{ inventory_hostname }} is {{ application_name }}"
```

Create the following playbook in the file `test_site.yaml`:

```yaml
- hosts: _app_server_2
  become: no
  gather_facts: false
  roles:
    - role: test_role
```

You can replace `hosts: _app_server_2` with `hosts: _app_server_1`

Run the playbook with:

```bash
ansible-playbook -i inventory/static_inventory_test.yaml test_site.yaml 
```

### Expected Results

The value of the variable `application_name` should reflect the one set as a group variable for all hosts present in the group, irregardless of some hosts being part of other groups.

### Actual Results

```console
If one host is part of multiple groups, the value of the variable `application_name` for that host is always the one set in the last group: 


$ ansible-playbook -i inventory/static_inventory_test.yaml test_site.yaml

PLAY [_app_server_2] *********************************************************************************************************************************

TASK [test_role : Print the value of the variable "application_name" for each host] ******************************************************************
Friday 15 November 2024  10:48:04 +0000 (0:00:00.050)       0:00:00.050 *******
ok: [app-server-2] => {
    "msg": "App name for the host app-server-2 is application-2"
}
ok: [shared-control-plane] => {
    "msg": "App name for the host shared-control-plane is application-3"
}

PLAY RECAP *******************************************************************************************************************************************
app-server-2               : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
shared-control-plane       : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@fildafer `ansible-core` 2.15 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by fildafer** [comment]
Just tried with freshly installed `ansible-core` 2.17.6. 


```bash
ansible [core 2.17.6]
  config file = /home/debian/ansible/ansible.cfg
  configured module search path = ['/home/debian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/debian/.pyenv/versions/ansible_venv_2_17_6/lib/python3.11/site-packages/ansible
  ansible collection location = /home/debian/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/debian/.pyenv/versions/ansible_venv_2_17_6/bin/ansible
  python version = 3.11.10 (main, Nov 15 2024, 14:06:00) [GCC 10.2.1 20210110] (/home/debian/.pyenv/versions/ansible_venv_2_17_6/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

Same results:

```bash
$ ansible-playbook -i inventory/static_inventory_test.yaml test_site.yaml

PLAY [_app_server_2] *********************************************************************************************************************************

TASK [test_role : Print the value of the variable "application_name" for each host] ******************************************************************
Friday 15 November 2024  14:55:39 +0000 (0:00:00.020)       0:00:00.020 *******
ok: [app-server-2] => {
    "msg": "App name for the host app-server-2 is application-2"
}
ok: [shared-control-plane] => {
    "msg": "App name for the host shared-control-plane is application-3"
}

PLAY RECAP *******************************************************************************************************************************************
app-server-2               : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
shared-control-plane       : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Friday 15 November 2024  14:55:40 +0000 (0:00:00.189)       0:00:00.210 *******
===============================================================================
test_role : Print the value of the variable "application_name" for each host ------------------------------------------------------------------ 0.19s
```

**Comment by flowerysong** [comment]
This is not a bug. A host variable can only have one value; you have put the same host in three different groups, but it's still a single host with a single, predictable value for that variable. The subset of hosts targeted in a play does not (and should not) have any effect on variable resolution.

**Comment by flowerysong** [comment]
It's not inconsistent, you've changed the value of that variable for that host so now it will consistently resolve to a different value.

The core thing you seem to be misunderstanding is that there's absolutely no difference between using `hosts: hostA, hostB` and `hosts: group1` with the following inventory:

```yaml
group1:
  hosts:
    hostA:
    hostB:
```

The play pattern (`hosts:`) is ultimately just a list of hosts to operate on. Patterns can use groups as a convenient way of targeting multiple hosts without listing them individually, but that doesn't change anything about the "context" of the tasks or the resolution for host variables.

When a host is a member of multiple groups that just means there are more places that variables can be set. One of the values will win, determined by the [variable precedence rules](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence) and the [defined merge order](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#how-we-merge) for group variables.
