### ISSUE TITLE
Play-level variables with templates are re-evaluated upon reading

### ISSUE THREAD

**Issue by navoooo** [ansible/ansible#84331]
### Summary

Variables with templates set at play-level are re-evaluated upon each read, causing issues with non-idempotent templating actions like generation of random strings. The behavior is unexpected and also inconsistent with the way other variables (at least set facts) are handled.

The behavior has been confirmed on two different setups with different ansible versions.

This seems to be caused by play-level vars never actually being templated until they reach [the strategy](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/linear.py#L137), i.e. templates are resolved once per task. The templates used in set_fact [are resolved immediately](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/set_fact.py#L46C17-L46C46), thus the issue does not occur here. 

[This comment in playbook_executor.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/playbook_executor.py#L159) seems to indicate, that all play-level variables with templates should be resolved at this point, which is not the case.

### Issue Type

Bug Report

### Component Name

lib/ansible/executor/playbook_executor

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.6]
  config file = /home/omitted/ansible.cfg
  configured module search path = ['/home/omitted/library']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/omitted/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CACHE_PLUGIN(/home/omitted/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/omitted/ansible.cfg) = .fact_cache/
CACHE_PLUGIN_TIMEOUT(/home/omitted/ansible.cfg) = 86400
CONFIG_FILE() = /home/omitted/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(env: ANSIBLE_FILTER_PLUGINS) = ['/home/omitted/filter_plugins', '/home/omitted/roles/omitted/filter_plugins']
DEFAULT_FORKS(/home/omitted/ansible.cfg) = 16
DEFAULT_GATHERING(/home/omitted/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/home/omitted/ansible.cfg) = ['/home/omitted/hosts']
DEFAULT_LOG_PATH(/home/omitted/ansible.cfg) = /home/omitted/ansible.log
DEFAULT_MODULE_PATH(/home/omitted/ansible.cfg) = ['/home/omitted/library']
DEFAULT_REMOTE_USER(/home/omitted/ansible.cfg) = omitted
DEFAULT_ROLES_PATH(/home/omitted/ansible.cfg) = ['/home/omitted/roles']
DEFAULT_VAULT_IDENTITY_LIST(/home/omitted/ansible.cfg) = ['omitted']
RETRY_FILES_ENABLED(/home/omitted/ansible.cfg) = False

CACHE:
=====

jsonfile:
________
_timeout(/home/omitted/ansible.cfg) = 86400
_uri(/home/omitted/ansible.cfg) = /home/omitted/.fact_cache

CONNECTION:
==========

paramiko_ssh:
____________
remote_user(/home/omitted/ansible.cfg) = omitted
ssh_args(/home/omitted/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s

ssh:
___
remote_user(/home/omitted/ansible.cfg) = omitted
ssh_args(/home/omitted/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
```

### OS / Environment

Ubuntu 22.04 LTS (jammy) using the ansible/ansible PPA

### Steps to Reproduce

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    testvar: "{{ lookup('community.general.random_string', length=40, special=false, min_numeric=1, min_upper=1, min_lower=1, ignore_similar_chars=true) }}"
    loops: "{{ [1,2] }}"
  tasks:
    - name: "Debug"
      debug:
        var: testvar
      loop: "{{ loops }}"
    - name: Set fact
      ansible.builtin.set_fact:
        set_testvar: "{{ lookup('community.general.random_string', length=40, special=false, min_numeric=1, min_upper=1, min_lower=1, ignore_similar_chars=true) }}"
    - name: "Debug"
      debug:
        var: set_testvar
      loop: "{{ loops }}"

```

### Expected Results

I expected the template of the play variable to be evaluated once, like the set fact, thus resulting in a fixed random string in the variable for the remainder of the play.

### Actual Results

```console
TASK [Debug] ******************************************************************************************
ok: [localhost] => (item=1) => {
    "ansible_loop_var": "item",
    "item": 1,
    "testvar": "8hwgNDzDppDmqMuh5Fxh9b6jJb2pkyx2T2QcR7k5"
}
ok: [localhost] => (item=2) => {
    "ansible_loop_var": "item",
    "item": 2,
    "testvar": "99BHfIr3IhHEI3X6UzqIK28Tc36YZmrqWeCp9hE8"
}

TASK [Set fact] ***************************************************************************************
ok: [localhost]

TASK [Debug] ******************************************************************************************
ok: [localhost] => (item=1) => {
    "set_testvar": "556RYX9Me6ZYAThrgWEjkbXUTT7PpdD5k9WuIBgf",
    "ansible_loop_var": "item",
    "item": 1
}
ok: [localhost] => (item=2) => {
    "set_testvar": "556RYX9Me6ZYAThrgWEjkbXUTT7PpdD5k9WuIBgf",
    "ansible_loop_var": "item",
    "item": 2
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
