### ISSUE TITLE
inconsistent behavior between delegate_to: "" and delegate_to: "{{ undef() | default('') }}"

### ISSUE THREAD

**Issue by craph** [ansible/ansible#84332]
### Summary

Hello,

I'm opening this issue because I'm seeing a weird behavior of the `delegate_to` when it's combined with conditional set to `false`

For example, with conditional set to false, if delegate_to contains a variable that contains an empty string, I have the following error message : 
```
fatal: [localhost -> {{ my_var }}]: FAILED! => {"msg": "Empty hostname produced from delegate_to: \"{{ my_var  }}\""}
```

But instead, if delegate_to is defined like this `delegate_to: ""` there is no error message like the previous one. 

Why ???

Delegate_to shouldn't be evaluated when he's surrounded by conditional defined to false.

Knowing my playbook, I have some block of tasks with conditional. This conditional can be set to false for specific use case and then the variable inside the block shouldn't have to be set because we know that the block will be skipped.

### Issue Type

Bug Report

### Component Name

lib/ansible/vars/manager.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.0]
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/home/ubuntu/.local/share/pipx/venvs/ansible-core/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu, RHEL9

### Steps to Reproduce

Here is the block that produce the error
```yaml (paste below)
---
- name: Debug
  hosts: localhost
  vars:
    my_var: ""

 - name : Debug block
    when: false
    block:
      - name: Echo toto
        ansible.builtin.debug:
          msg: "toto should be skipped"
        delegate_to: "{{ my_var }}"

      - name: Echo titi
        ansible.builtin.debug:
          msg: "titi should be skipped"
        delegate_to: "{{ my_var }}"
```

Here is the block that doesn't produce the error
```yaml (paste below)
---
- name: Debug
  hosts: localhost

 - name : Debug block
    when: false
    block:
      - name: Echo toto
        ansible.builtin.debug:
          msg: "toto should be skipped"
        delegate_to: ""

      - name: Echo titi
        ansible.builtin.debug:
          msg: "titi should be skipped"
        delegate_to: ""
```

### Expected Results

Here is the expect result for the block that have delegate_to with variable :
```
TASK [Echo toto] *******************************************************************************************
skipping: [localhost]

TASK [Echo titi] *******************************************************************************************
skipping: [localhost]
```

### Actual Results

```console
Here is the result for the block that produce the error :

TASK [Echo toto] *******************************************************************************************
fatal: [localhost -> {{ my_var }}]: FAILED! => {"msg": "Empty hostname produced from delegate_to: \"{{ my_var }}\""}
```

Here is the result for the block that doesn't produce the error :
```
TASK [Echo toto] *******************************************************************************************
skipping: [localhost]

TASK [Echo titi] *******************************************************************************************
skipping: [localhost]
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by craph** [comment]
@rayamos Same problem for me and also have the issue in version `2.15.9`

**Comment by craph** [comment]
Here is another issue related to the same behavior #83253 
@sivel why this is an expected behavior ?
In my example tests cases the conditional when is ignored when this is a variable inside the delegate_to. The when conditional mustn't be ignored.
Thank you very much for your help on this subject.
Best regards,

**Comment by mat-m** [comment]
I have a similar use case

```yaml
- name: Migration
  when:
    - do_migration | bool
  tags: synchronize_files
  block:
    - name: "Create ssh keygen temporarily on {{ old_server }}"
      community.crypto.openssh_keypair:
        path: "~{{ user }}/.ssh/id_ssh_4_mig"
      become: true
      become_user: "{{ user }}"
      delegate_to: "{{ old_server }}"
      tags: sshkey

```

When we do not process data migration, we do not have the `old_server` variable set, obviously. I totally agree to break if `do_migration` is `true`, but it should be transparent if it is `false`.
I didn't test, but I guess the task does not fail if `user` is not set for `become_user`.
