### ISSUE TITLE
restart / reload systemd service based on comparision of start time and config files

### ISSUE THREAD

**Issue by redeye86** [ansible/ansible#84347]
### Summary

After editing config files you typically have to restart the corresponding service. But if the file did not change, the service should not be restarted, but it still should be ensured that it is running.

In my case I ended up in a construct like this:

```
 - name: copy config
   template:
     src: "etc/some/config.j2"
     dest: "/etc/some/config"
   register: config_file

 - name: restart some daemon
   ansible.builtin.systemd_service:
     name: some-service
     state: "{{ 'restarted' if config_file is defined and config_file.changed else 'started' }}"
     enabled: true
```

and even this is not perfect. What we actually want to ensure is that the service runs with the most recent version of the config settings. So if the file was potentially changed in multiple steps of the script or was changed in a previous run, is may not be picked up. So to do this correctly you would need at least one additional "stat"-step.

In my opinion the ideal solution would be to be able to pass a list of config files to "ansible.builtin.systemd". This way it could internally obtain the last (re-)start time of the service from systemd and restart or reload if the config files were changed in the meantime.

```
 - name: restart some daemon
   ansible.builtin.systemd_service:
     name: some-service
     reload_config_if_changed:
         reload_by: (restart|reload)
         config_files: 
           - /etc/some/config
           - /etc/some/config2
```

I know this is not super necessary as it can be accomplished by additional steps, but I think it is used quite often and also the "creates"  parameter of "ansible.builtin.command" is similar.

### Issue Type

Feature Idea

### Component Name

systemd_service

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
