### ISSUE TITLE
http-agent not taken in account in get_url

### ISSUE THREAD

**Issue by dberardo-com** [ansible/ansible#84349]
### Summary

i am running ansible behind a proxy that checks the http user agent header and thus need to use the firefox user agent in order order to surf.

i was hoping to user the http_agent var of get_url and uri modules but by looking at the code it seems they are not used. is there a way to set the user agent globally for lal requests or at least when using those modules ? 

### Issue Type

Documentation Report

### Component Name

get_url.py

### Ansible Version

```console
ansible [core 2.13.13]
```

### Configuration

```console
ansible [core 2.13.13]
```

### OS / Environment

WSL linux

### Additional Information

ansible [core 2.13.13]

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/get_url.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/get_url.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by flowerysong** [comment]
`get_url` (and `uri`) have an `http_agent` parameter, which is [documented](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#parameter-http_agent) and works.

```yaml
- hosts: localhost
  tasks:
    - ansible.builtin.uri:
        url: https://www.whatsmyua.info/api/v1/ua
        http_agent: "{{ item }}"
      loop:
        - "{{ omit }}"
        - Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0
        - curl/7.76.1
      register: result

    - ansible.builtin.debug:
        msg: "{{ result.results | map(attribute='json.0.ua.rawUa') }}"
```

```plain
TASK [ansible.builtin.uri] *****************************************************
ok: [localhost] => (item=__omit_place_holder__664e93edb98ce0766f389658b4062695c439e862)
ok: [localhost] => (item=Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0)
ok: [localhost] => (item=curl/7.76.1)

TASK [ansible.builtin.debug] ***************************************************
ok: [localhost] => 
    msg:
    - ansible-httpget
    - Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0
    - curl/7.76.1
```

If you believe that you have encountered a bug and it is not working as documented you need to provide information supporting this and a way to reproduce your result, which you have not done.
