### ISSUE TITLE
Copy module, content, and variable interpolation

### ISSUE THREAD

**Issue by mikeweinberg** [ansible/ansible#84355]
### Summary

I am writing several simple tasks to enforce settings in Linux (RHEL 9-compatible). I've provided example tasks using the copy module and content. The content is at least partially provided using a variable, as is typically used in Ansible playbooks.

However, I see in the [documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html) that there is a vague warning about using variable interpolation:

> If you need variable interpolation in copied files, use the [ansible.builtin.template](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#ansible-collections-ansible-builtin-template-module) module. Using a variable with the [content](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#ansible-collections-ansible-builtin-copy-module-parameter-content) parameter produces unpredictable results.

This warning was [added](https://github.com/ansible/ansible/pull/50940/files) in January 2019 in response to a 2018 bug report (#34595). Since then, there has been little discussion of the problem.

I'd prefer not to use the template module and a separate jinja2 template because it adds unnecessary complexity. It's also a common pattern in [example code](https://github.com/ComplianceAsCode/content/blob/444895fab527330481b182994c7dbd83ad6ca81f/linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/ansible/shared.yml#L22) to use variable interpolation with content in the copy module.

If variable interpolation doesn't work in copy, I'd prefer it to error/warning, be fixed, or better described what works and what doesn't. Another possibility is include a "content" parameter in the template module that can be used for small jinja2 templates.

Is there any real harm in using the example code I've provided? It would be helpful to have more clarity on this.

### Issue Type

Bug Report

### Component Name

copy

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.17]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/USERNAME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/USERNAME/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.19 (main, Aug 23 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2.0.1)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

RHEL 9-compatible

### Steps to Reproduce

```yaml
---
- name: Set up banner and umask
  hosts: all
  become: true
  vars:
    banner_text: "Don't hack this system"
    user_umask: "027"
  tasks:

    - name: Set system issue banner
      ansible.builtin.copy:
        dest: /etc/issue
        content: "{{ banner_text }}"
        owner: root
        group: root
        mode: '0644'

    - name: Create /etc/profile.d/umask.sh with umask setting
      ansible.builtin.copy:
        dest: /etc/profile.d/umask.sh
        content: |
          umask {{ user_umask }}
        owner: root
        group: root
        mode: '0644'
```

### Expected Results

Two files are correctly created with the desired output, with variable interpolation.

### Actual Results

```console
PLAY [Set up banner and umask] *****************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************
[WARNING]: Platform linux on host 10.32.8.180 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python
interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.14/reference_appendices/interpreter_discovery.html for more
information.
ok: [10.32.8.180]

TASK [Set system issue banner] *****************************************************************************************************************************
changed: [10.32.8.180]

TASK [Create /etc/profile.d/umask.sh with umask setting] ***************************************************************************************************
changed: [10.32.8.180]

PLAY RECAP *************************************************************************************************************************************************
10.32.8.180                : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
