### ISSUE TITLE
Need ability to close stdin

### ISSUE THREAD

**Issue by mike-burns** [ansible/ansible#84360]
### Summary

Feature request: add the ability for `stdin` to be None or False in `command`/`shell`/`raw`.

### Issue Type

Feature Idea

### Component Name

command

### Additional Information

Example:

```yaml
shell:
  no_stdin: true
  cmd: op item create testing
```

---

I am trying to use the 1Password command line tool, [`op`](https://developer.1password.com/docs/cli/reference/management-commands/item), from Ansible. The `op item edit` and `op item create` commands can take command-line arguments to modify items in the password manager. They can also take JSON on stdin, which provides a base to any command-line args.

The `shell` (and `command` and `raw`) tasks always open stdin. This means that a simple command line `op item create --title testing` gives the error:

```
invalid JSON in piped input
```

We've been working around this for `create` by feeding in stdin, e.g.

```yaml
shell:
  stdin: '{"fields": []}'
  cmd: op item create --title testing 'whatever[password]=big secret'
  delegate_to: localhost
```

But for `edit` it needs the entirety of the existing value, so we have to do a more complicated dance (I'll show it here for others trying to figure this out):

```yaml
- name: build update json
  shell:
    cmd: >-
      op item get 'testing' --format json |
      jq '.fields = (.fields | map(if (.label == "whatever") then (.value = "bigger secret") else . end))'
  delegate_to: localhost
  register: onepass_input

- name: update 1pass
  shell:
    stdin: "{{ onepass_input.stdout | string }}"
    cmd: op item edit testing
  delegate_to: localhost
```

And what if I want to add a new value that isn't in the existing JSON? Then I need to read even more `jq` docs ...

Point is, this is all because [stdin cannot be false](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py#L259). If it could be false, we could simply call `op item edit testing 'whatever=bigger secret'` without parsing JSON.

---

As a minimal reproduction, I made a quick program:

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int
main(void)
{
	fd_set readfds;
	FD_ZERO(&readfds);

	struct timeval timeout;
	timeout.tv_sec = 0;
	timeout.tv_usec = 0;

	FD_SET(STDIN_FILENO, &readfds);

	if (select(1, &readfds, NULL, NULL, &timeout)) {
		printf("stdin is open\n");
	} else {
		printf("stdin is closed\n");
	}

	return 0;
}
```

And a quick playbook:

```yaml
- hosts: localhost
  gather_facts: false

  tasks:
    - name: running command
      shell:
        cmd: "/home/mike/t/a.out"
      delegate_to: localhost
      register: output

    - debug:
        msg: "{{ output.stdout }}"
```

Works like so:

```
~/t% cc foo.c                
~/t% ./a.out       
stdin is closed
~/t% echo | ./a.out
stdin is open
```

```
~/t% ansible-playbook foo.yml
TASK [running command] *********************************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "stdin is open"
}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
