### ISSUE TITLE
Cant set connection plugin variables to another variable in task when task is delegated to another host

### ISSUE THREAD

**Issue by dshuffin** [ansible/ansible#84374]
### Summary

When I try to set variables **used by a connection plugin** to another variables value within a task that is delegated to another host I get "msg: '''var'' is undefined'" where var is my own variable that holds the value that I want to pass.
I have tested this behavior with paramiko_ssh and httpapi connection plugins, and included those tests in the sample playbook.
I've also included similar tasks that are delegated but do not use connection plugins and tasks that use connection plugins but are not delegated, as well as task that are delegated and use connection plugins, but set a target variable that is not used by the connection plugin itself. All those additional tasks do not fail, just like they should.

### Issue Type

Bug Report

### Component Name

task_executor.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.6]
  config file = /home/<>/infrastructure/ansible.cfg
  configured module search path = ['/home/<>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/<>/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /home/<>/infrastructure/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/<>/infrastructure/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/<>/infrastructure/ansible.cfg) = ['/home/<>/infrastructure/galaxy_roles', '/home/<>/infrastructure/roles']
DEFAULT_STDOUT_CALLBACK(/home/<>/infrastructure/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/<>/infrastructure/ansible.cfg) = 60

CONNECTION:
==========

paramiko_ssh:
____________
timeout(/home/<>/infrastructure/ansible.cfg) = 60

ssh:
___
timeout(/home/<>/infrastructure/ansible.cfg) = 60
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
- name: test httpapi
  hosts: admitrzat01.rmd.remedy.fi
  gather_facts: False
  tasks:

    - name: Setting variable
      ansible.builtin.set_fact:
        test: 443

    - name: debug without delegation with httpapi
      vars:
        ansible_connection: httpapi
        ansible_httpapi_port: "{{ test }}"
      debug:
        var: ansible_httpapi_port

    - name: debug with delegation without httpapi
      vars:
        ansible_httpapi_port: "{{ test }}"
      debug:
        var: ansible_httpapi_port
      delegate_to: localhost

    - name: debug with delegation and httpapi
      vars:
        ansible_connection: httpapi
        ansible_httpapi_port: "{{ test }}"
      debug:
        var: ansible_httpapi_port
      delegate_to: localhost
      ignore_errors: true

    - name: debug with delegation and httpapi and unused target var
      vars:
        ansible_connection: httpapi
        test_target: "{{ test }}"
      debug:
        var: test_target
      delegate_to: localhost
      ignore_errors: true

    - name: debug with delegation and httpapi and novar
      vars:
        ansible_connection: httpapi
        ansible_httpapi_port: 443
      debug:
        var: ansible_httpapi_port
      delegate_to: localhost

- name: test paramiko_ssh
  hosts: admitrzat01.rmd.remedy.fi
  gather_facts: False
  tasks:

    - name: Setting variable
      ansible.builtin.set_fact:
        test2: false

    - name: debug without delegation with paramiko
      vars:
        ansible_connection: paramiko_ssh
        ansible_paramiko_host_key_checking: "{{ test2 }}"
      debug:
        var: ansible_paramiko_host_key_checking

    - name: debug with delegation without paramiko
      vars:
        ansible_paramiko_host_key_checking: "{{ test2 }}"
      debug:
        var: ansible_paramiko_host_key_checking
      delegate_to: localhost

    - name: debug with delegation and paramiko
      vars:
        ansible_connection: paramiko_ssh
        ansible_paramiko_host_key_checking: "{{ test2 }}"
      debug:
        var: ansible_paramiko_host_key_checking
      delegate_to: localhost
      ignore_errors: true

    - name: debug with delegation and paramiko and unused target var
      vars:
        ansible_connection: paramiko_ssh
        test_target2: "{{ test2 }}"
      debug:
        var: test_target2
      delegate_to: localhost

    - name: debug with delegation and paramiko and novar
      vars:
        ansible_connection: paramiko_ssh
        ansible_paramiko_host_key_checking: false
      debug:
        var: ansible_paramiko_host_key_checking
      delegate_to: localhost
```

### Expected Results

I expected all tasks to succeed.

### Actual Results

```console
ansible-playbook [core 2.17.6]
  config file = /home/<>/infrastructure/ansible.cfg
  configured module search path = ['/home/<>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/<>/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /home/<>/infrastructure/ansible.cfg as config file
setting up inventory plugins
Loading collection ansible.builtin from
host_list declined parsing /home/<>/infrastructure/inventories/development/hosts.yml as it did not pass its verify_file() method
script declined parsing /home/<>/infrastructure/inventories/development/hosts.yml as it did not pass its verify_file() method
Parsed /home/<>/infrastructure/inventories/development/hosts.yml inventory source with yaml plugin
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading collection community.general from /usr/lib/python3/dist-packages/ansible_collections/community/general
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading callback plugin community.general.yaml of type stdout, v2.0 from /usr/lib/python3/dist-packages/ansible_collections/community/general/plugins/callback/yaml.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test.yml ****************************************************************************************************************************************************************************************************
Positional arguments: playbooks/test.yml
verbosity: 4
connection: ssh
become_method: sudo
tags: ('all',)
inventory: ('/home/<>/infrastructure/inventories/development',)
forks: 5
2 plays in playbooks/test.yml

PLAY [test httpapi] ***************************************************************************************************************************************************************************************************

TASK [Setting variable] ***********************************************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:6
ok: [zat01] => changed=false
  ansible_facts:
    test: 443

TASK [debug without delegation with httpapi] **************************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:10
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /home/<>/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /usr/lib/python3/dist-packages/ansible_collections/ansible/utils
ok: [zat01] =>
  ansible_httpapi_port: '443'

TASK [debug with delegation without httpapi] **************************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:17
ok: [zat01 -> localhost] =>
  ansible_httpapi_port: '443'

TASK [debug with delegation and httpapi] ******************************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:24
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /home/<>/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /usr/lib/python3/dist-packages/ansible_collections/ansible/utils
fatal: [zat01 -> localhost]: FAILED! =>
  msg: '''test'' is undefined'
...ignoring

TASK [debug with delegation and httpapi and unused target var] ********************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:33
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /home/<>/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /usr/lib/python3/dist-packages/ansible_collections/ansible/utils
ok: [zat01 -> localhost] =>
  test_target: '443'

TASK [debug with delegation and httpapi and novar] ********************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:42
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /home/<>/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /usr/lib/python3/dist-packages/ansible_collections/ansible/utils
ok: [zat01 -> localhost] =>
  ansible_httpapi_port: 443

PLAY [test paramiko_ssh] **********************************************************************************************************************************************************************************************

TASK [Setting variable] ***********************************************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:55
ok: [zat01] => changed=false
  ansible_facts:
    test2: false

TASK [debug without delegation with paramiko] *************************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:59
ok: [zat01] =>
  ansible_paramiko_host_key_checking: false

TASK [debug with delegation without paramiko] *************************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:66
ok: [zat01 -> localhost] =>
  ansible_paramiko_host_key_checking: false

TASK [debug with delegation and paramiko] *****************************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:73
fatal: [zat01 -> localhost]: FAILED! =>
  msg: '''test2'' is undefined'
...ignoring

TASK [debug with delegation and paramiko and unused target var] *******************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:82
ok: [zat01 -> localhost] =>
  test_target2: false

TASK [debug with delegation and paramiko and novar] *******************************************************************************************************************************************************************
task path: /home/<>/infrastructure/playbooks/test.yml:90
ok: [zat01 -> localhost] =>
  ansible_paramiko_host_key_checking: false

PLAY RECAP ************************************************************************************************************************************************************************************************************
zat01  : ok=12   changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
