### ISSUE TITLE
Add rootdir support for user module on FreeBSD

### ISSUE THREAD

**Issue by TLINDEN** [ansible/ansible#84370]
### Summary

I am building a bastille chroot on FreeBSD using ansible. I need to maintain lots of users inside the jail, but the builtin users module just works on the target host system.

I could add the jail dynamically to the inventory and then execute the user module on it, but it would be much easier to just provide a root dir variable to the users module, since it already supports this kind of thing. From the man page:

>      -R rootdir    Specifies an alternate root directory within which pw will
>                   operate.  Any paths specified will be relative to rootdir.

### Issue Type

Feature Idea

### Component Name

user

### Additional Information

```yaml (paste below)
- name: Add a jail user
  ansible.builtin.user:
    name: james18
    shell: /bin/zsh
    groups: developers
    rootdir: /usr/local/bastille/jails/jumper/root
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
