### ISSUE TITLE
ansible.builtin.iptables inconsistent parser behavior with 'owner' extension

### ISSUE THREAD

**Issue by xrzi** [ansible/ansible#84387]
### Summary

When matching 'uid-owner' & 'gid-owner' flags, rule constructor automatically adds -m 'owner' to parameters. This results in an error, when user explicitly specifies `match: owner` in the task:
```
iptables v1.8.7 (nf_tables): owner: At least one of --uid-owner, --gid-owner or --socket-exists is required
Try 'iptables -h' or 'iptables --help' for more information.
```
This seems inconsistent with behavior of iptables itself, since it does require `-m owner` when performing any owner-related matching, moreover using other extensions does require appropriate match flag to be set.

### Issue Type

Bug Report

### Component Name

iptables

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
- name: This task executes
  ansible.builtin.iptables:
    table: nat
    chain: OUTPUT
    #match: owner # Notice the line i commented out
    uid_owner: 1001
    ctstate: NEW
    jump: ACCEPT
    comment: "Explicitly allow packets from user mitmproxy to avoid loopback and succeed"

- name: This task fails
  ansible.builtin.iptables:
    table: nat
    chain: OUTPUT
    match: owner # Uncommented line
    uid_owner: 1001
    ctstate: NEW
    jump: ACCEPT
    comment: "Explicitly allow packets from user mitmproxy to avoid loopback and fail miserably"
```

### Expected Results

I expected the task without `match: owner` to fail, and with it to succeed, so naturally I was shocked to learn it worked the other way around!

### Actual Results

```console
fatal: [default]: FAILED! => {
    "changed": false,
    "cmd": "/usr/sbin/iptables -t nat -A OUTPUT -m owner -j ACCEPT -m conntrack --ctstate NEW -m owner --uid-owner 1001 -m comment --comment 'Explicitly allow packets from user mitmproxy to avoid loopback and fail miserably'",
    "invocation": {
        "module_args": {
            "action": "append",
            "chain": "OUTPUT",
            "comment": "Explicitly allow packets from user mitmproxy to avoid loopback and fail miserably",
            "ctstate": [
                "NEW"
            ],
            "destination": null,
            "destination_port": null,
            "dst_range": null,
            "flush": false,
            "fragment": null,
            "gateway": null,
            "gid_owner": null,
            "goto": null,
            "icmp_type": null,
            "in_interface": null,
            "ip_version": "ipv4",
            "jump": "ACCEPT",
            "limit": null,
            "limit_burst": null,
            "log_level": null,
            "log_prefix": null,
            "match": [
                "owner"
            ],
            "out_interface": null,
            "policy": null,
            "protocol": null,
            "reject_with": null,
            "rule_num": null,
            "set_counters": null,
            "set_dscp_mark": null,
            "set_dscp_mark_class": null,
            "source": null,
            "source_port": null,
            "src_range": null,
            "state": "present",
            "syn": "ignore",
            "table": "nat",
            "tcp_flags": null,
            "to_destination": null,
            "to_ports": null,
            "to_source": null,
            "uid_owner": "1001",
            "wait": null
        }
    },
    "msg": "iptables v1.8.7 (nf_tables): owner: At least one of --uid-owner, --gid-owner or --socket-exists is required\nTry `iptables -h' or 'iptables --help' for more information.",
    "rc": 2,
    "stderr": "iptables v1.8.7 (nf_tables): owner: At least one of --uid-owner, --gid-owner or --socket-exists is required\nTry `iptables -h' or 'iptables --help' for more information.\n",
    "stderr_lines": [
        "iptables v1.8.7 (nf_tables): owner: At least one of --uid-owner, --gid-owner or --socket-exists is required",
        "Try `iptables -h' or 'iptables --help' for more information."
    ],
    "stdout": "",
    "stdout_lines": []
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
