### ISSUE TITLE
include_tasks: option to chose if included tasks run in sequence/parallel

### ISSUE THREAD

**Issue by dajas22** [ansible/ansible#84385]
### Summary

Hello, I'm trying to find the best way to provision our etcd clusters, which run in docker. Down below is dummy example of our playbook.

The suggestion is to make it possible to control this behavior, eg.: `execution_mode` variable with options: (`serial`, `normal`), which will decide if tasks are included as in the `Serial rollout etcd update`, or as normal. The part with looping over template variable, is just a hack I found by mistake, I didn't found anything about this behavior in docs, neither I'm sure if it will work in the future, but it does exactly what we want. 

Do you have any other suggestion, I know there is serial option in play, but it would carry over some difficulty, which we don't want. We are looking forward to your suggestion.

Thank you in advance.

### Issue Type

Feature Idea

### Component Name

include_tasks

### Additional Information

```
$ ansible --version
ansible [core 2.17.4]
  config file = /home/dalibor/ansible_issue/ansible.cfg
  configured module search path = ['/home/dalibor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dalibor/ansible_issue/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/dalibor/ansible_issue
  executable location = /home/dalibor/ansible_issue/venv/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/home/dalibor/ansible_issue/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

provision.yml:
```yaml
- name: Main
  hosts: all
  tasks:
    - name: Setup certs
      ansible.builtin.debug:
        msg: Certs done

    - name: Include role
      ansible.builtin.include_role:
        name: etcd
      vars:
        etcd_vars: boo

```

etcd role:
```yaml
# task which decides to update or create cluster

- name: Serial rollout etcd update
  ansible.builtin.include_tasks:
    file: docker-etcd.yaml
  loop:
    - foo: "{{ inventory_hostname }}"
  # when: bar

- name: Parallel new cluster
  ansible.builtin.include_tasks:
    file: docker-etcd.yaml
  # when: foo
```

docker-etcd.yaml:
```yaml
- name: Etcd container
  ansible.builtin.debug:
    var: inventory_hostname

- name: Wait for member healthy
  ansible.builtin.debug:
    msg: member healthy

```

result:
```yaml
PLAY [Main] *****************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-3]
ok: [dev1-etcd-1]
ok: [dev1-etcd-2]

TASK [Setup certs] **********************************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-1] => {
    "msg": "Certs done"
}
ok: [dev1-etcd-2] => {
    "msg": "Certs done"
}
ok: [dev1-etcd-3] => {
    "msg": "Certs done"
}

TASK [Include role] *********************************************************************************************************************************************************************************************************************************
included: etcd for dev1-etcd-1, dev1-etcd-2, dev1-etcd-3

TASK [etcd : Serial rollout etcd update] ******************************************************************************************************************************************************************************************************
included: /tmp/docker-etcd.yaml for dev1-etcd-1 => (item={'foo': 'dev1-etcd-1'})
included: /tmp/docker-etcd.yaml for dev1-etcd-2 => (item={'foo': 'dev1-etcd-2'})
included: /tmp/docker-etcd.yaml for dev1-etcd-3 => (item={'foo': 'dev1-etcd-3'})

TASK [etcd : Etcd container] ************************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-1] => {
    "inventory_hostname": "dev1-etcd-1"
}

TASK [etcd : Wait for member healthy] ***************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-1] => {
    "msg": "member healthy"
}

TASK [etcd : Etcd container] ************************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-2] => {
    "inventory_hostname": "dev1-etcd-2"
}

TASK [etcd : Wait for member healthy] ***************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-2] => {
    "msg": "member healthy"
}

TASK [etcd : Etcd container] ************************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-3] => {
    "inventory_hostname": "dev1-etcd-3"
}

TASK [etcd : Wait for member healthy] ***************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-3] => {
    "msg": "member healthy"
}

TASK [etcd : Parallel new cluster] ******************************************************************************************************************************************************************************************************************
included: /tmp/docker-etcd.yaml for dev1-etcd-1, dev1-etcd-2, dev1-etcd-3

TASK [etcd : Etcd container] ************************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-1] => {
    "inventory_hostname": "dev1-etcd-1"
}
ok: [dev1-etcd-2] => {
    "inventory_hostname": "dev1-etcd-2"
}
ok: [dev1-etcd-3] => {
    "inventory_hostname": "dev1-etcd-3"
}

TASK [etcd : Wait for member healthy] ***************************************************************************************************************************************************************************************************************
ok: [dev1-etcd-1] => {
    "msg": "member healthy"
}
ok: [dev1-etcd-2] => {
    "msg": "member healthy"
}
ok: [dev1-etcd-3] => {
    "msg": "member healthy"
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************
dev1-etcd-1 : ok=9    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
dev1-etcd-2 : ok=9    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
dev1-etcd-3 : ok=9    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by balous** [comment]
I need similar thing - our inventory contains hosts that compose multiple clusters. Some tasks need to be run just once per cluster, we use `run_once: true` for such tasks. But there is a problem - if ansible play contains hosts accross different clusters, the task is performed for just one of the clusters, not for all clusters.

Recently, I noticed following behavior of `include_tasks`/`include_role` and `loop` combination:

```
        - name: Create users
          ansible.builtin.include_tasks:
            file: users.yaml
          loop: "{{ [ cluster_name ] }}"
```

When `include_tasks` is looped across list (for this purpose I use just a single element), where the element contain different value across different groups of hosts, these hosts are divided to groups by the value of the element. The groups are than run in sequence while hosts in the group are run in parallel. Inside `users.yaml`, `run_once: true` is used to not create the same user three times.

The problem of this solution is that it is not documented (I was unable to find it's doc) so we're affraid it might stop working in some future Ansible update.

As I think about it, I came to conclusion that it would be handy if `run_once` semantics is extended from `bool` to general expression. The behavior would be that ansible chooses just one host for each of the values the expression evaluates to (except `false` to retain compatibility with current semantics).

Does this make sense?
