### ISSUE TITLE
Override check_mode for ansible.builtin.uri

### ISSUE THREAD

**Issue by Hipska** [ansible/ansible#84386]
### Summary

I am using `uri` to get some data from an API to be used by another task. However this fails in check mode since the `uri` task gets skipped and thus the required data is not available.

I understand it is done this way in the scenario when `uri` is doing `POST` request or when the request would do some actions on the server side, which makes it not idempotent anymore, but in this case it is only used to retrieve data.

A parameter to also allow this module in check mode would be useful.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.uri

### Additional Information

```yaml
- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://www.example.com
    also_in_check_mode: true

- name: Check that a page returns successfully but fail if the word AWESOME is not in the page contents
  ansible.builtin.uri:
    url: http://www.example.com
    return_content: true
    also_in_check_mode: true
  register: this
  failed_when: this is failed or "'AWESOME' not in this.content"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
