### ISSUE TITLE
Set IPv4 and IPv6 simultaneously in iptables module

### ISSUE THREAD

**Issue by Bilge** [ansible/ansible#84404]
### Summary

I want to set IPv4 and IPv6 rules at the same time. We could loop, but not if we're looping already to provide the rules. This makes sense when the rules are for interfaces rather than addresses and the rules should be applied to both network stacks.

This could either be implemented with a new keyword (e.g. `both`) or by accepting a list, e.g. `ip_version: [ipv4, ipv6]`.

### Issue Type

Feature Idea

### Component Name

iptables

### Additional Information

```yaml (paste below)
- iptables:
    chain: INPUT
    in_interface: '{{ item|first }}'
    comment: '{{ item[item|first] }}'
    jump: ACCEPT
  loop:
    - foo: My foo interface
    - bar+: My bar interfaces
```

### Code of Conduct

- [ ] I agree to follow the Ansible Code of Conduct
