### ISSUE TITLE
Add the possibility to change username with ansible.builtin.user

### ISSUE THREAD

**Issue by N3leeh** [ansible/ansible#84410]
### Summary

I am trying to change the name of an existing user with ansible. In fact i want to something like:
usermod -d /home/new_username -m -l new_username existing_user 

Everything else, like the uid, the comment etc. should stay as it is.  
Since ansible.builtin.user is already using usermod it would be nice to have a new option like "rename: " or "new_name" 

### Issue Type

Feature Idea

### Component Name

lib/ansible/modules/user.py

### Additional Information

```yaml (paste below)
- name: update existing user
  ansible.builtin.user:
    name: someusername
    new_username: newname
    uid: int
    home: /home/newname
    move_home: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
