### ISSUE TITLE
ansible.builtin.systemd_service should be able to link service

### ISSUE THREAD

**Issue by pglizniewicz** [ansible/ansible#84420]
### Summary

I'm trying to use `systemctl link` via Ansible, but I don't see a relevant parameter in `ansible.builtin.systemd_service`. I need link for this case, because it's to "register" a service that can by either run manually or via a timer.

### Issue Type

Feature Idea

### Component Name

[lib/ansible/modules/systemd_service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/systemd_service.py)

### Additional Information

```yaml (paste below)
- name: Link my.service
  ansible.builtin.systemd_service:
    name: /usr/local/lib/mystuff/my.service
    linked: true
```
`linked: false` should work like `enabled: false`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
