### ISSUE TITLE
template error while templating string:

### ISSUE THREAD

**Issue by jyothi-balla** [ansible/ansible#84433]
### Summary

We first try to do a lookup vault to fetch the password, the password has  characters "{%!" the below is how the rendered template file looks like 
```db:
  create: true
  admin_user: "user1"
  admin_password: !unsafe "4{%!<----"
  users:
    "pgsqladmin":
      password: !unsafe "4{%!<----"
    "applicationscourtorders":
      context_user: true
      password: "password"
```
      
during a combine step
```
- name: Combine db variables from item-specific service values
  set_fact:
    merged_db_vars: "{{ merged_db_vars | combine(specific_service_vars.ansible_facts.db, recursive=True) }}"
  when: specific_service_vars.ansible_facts.db is defined
  ```
  we get the following error
  " Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: unexpected char '!' at 3. String: 4{%!<-ka---\n\"
  
  Have tried multiple options using to_yaml, to_json, quote 
  Can someone please help in getting this problem solved? 
  

### Issue Type

Bug Report

### Component Name

jinja2

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.13]
  config file = None
  configured module search path = ['/home/azureadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/azureadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/ansible/bin/ansible
  python version = 3.8.8 (default, Aug 25 2021, 16:13:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
-
```

### OS / Environment

centos8

### Steps to Reproduce

We first try to do a lookup vault to fetch the password, the password has  characters "{%!" the below is how the rendered template file looks like 
```db:
  create: true
  admin_user: "user1"
  admin_password: !unsafe "4{%!<----"
  users:
    "pgsqladmin":
      password: !unsafe "4{%!<----"
    "applicationscourtorders":
      context_user: true
      password: "password"
```
      
during a combine step
```
- name: Combine db variables from item-specific service values
  set_fact:
    merged_db_vars: "{{ merged_db_vars | combine(specific_service_vars.ansible_facts.db, recursive=True) }}"
  when: specific_service_vars.ansible_facts.db is defined
  ```
 
  

### Expected Results

I expected this to combine 

### Actual Results

```console
" Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: unexpected char '!' at 3. String: 4{%!<-ka---\n\"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@jyothi-balla `ansible-core` 2.13 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by mkrizek** [comment]
Just by running what was provided in the issue description, I was not able to reproduce it on the `devel` branch:

```yaml
- hosts: localhost
  gather_facts: false
  vars:
    v:
      admin_password: !unsafe "4{%!<----"
      users:
        pgsqladmin:
          password: !unsafe "4{%!<----"
  tasks:
    - debug:
        msg: "{{ merged_db_vars | default({}) | combine(v, recursive=True) }}"
```

```
TASK [debug] ********************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "admin_password": "4{%!<----",
        "users": {
            "pgsqladmin": {
                "password": "4{%!<----"
            }
        }
    }
}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
