### ISSUE TITLE
When "content" option is used this module does not correctly detect file changes

### ISSUE THREAD

**Issue by raphaabreu** [ansible/ansible#8443]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 8646cc7988) last updated 2014/08/04 22:04:49 (GMT -200)
##### Environment:

MacOS 10.9.4
##### Summary:

The copy module is not correctly identifying if the file has been changed when the "content" option is used instead of "src".
##### Steps To Reproduce:

A task as described will always notify the handler even though when the file has not been changed and matches exactly the value of the "content" option.

```
  tasks:
  - name: set time zone
    copy: content="America/Sao_Paulo" dest=/etc/timezone
          owner=root group=root mode=0644
    notify:
    - update timezone

  handlers:
  - name: update timezone
    command: dpkg-reconfigure --frontend noninteractive tzdata
```

Possibly an issue on how the MD5 hash is being calculated. I noticed that the output of the ansible-playbook states a hash that does not match either the file or the value of the "content" option.
##### Expected Results:

```
TASK: [set time zone] ********************************************************* 
ok: [10.52.20.106] => {"changed": false, "dest": "/etc/timezone", "gid": 0, "group": "root", "md5sum": "1c978baa6e3453cca63bcbed6d20d232", "mode": "0644", "msg": "could not write content temp file: global name 'self' is not defined", "owner": "root", "size": 18, "src": "", "state": "file", "uid": 0}
```
##### Actual Results:

```
TASK: [set time zone] ********************************************************* 
changed: [10.52.20.106] => {"changed": true, "dest": "/etc/timezone", "gid": 0, "group": "root", "md5sum": "1c978baa6e3453cca63bcbed6d20d232", "mode": "0644", "owner": "root", "size": 17, "src": "/root/.ansible/tmp/ansible-tmp-1407201133.17-273344189894207/source", "state": "file", "uid": 0}

NOTIFIED: [update timezone] *************************************************** 
changed: [10.52.20.106] => {"changed": true, "cmd": ["dpkg-reconfigure", "--frontend", "noninteractive", "tzdata"], "delta": "0:00:00.974934", "end": "2014-08-04 22:12:27.138238", "rc": 0, "start": "2014-08-04 22:12:26.163304", "stderr": "\nCurrent default time zone: 'America/Sao_Paulo'\nLocal time is now:      Mon Aug  4 22:12:26 BRT 2014.\nUniversal Time is now:  Tue Aug  5 01:12:26 UTC 2014.", "stdout": ""}
```
