### ISSUE TITLE
assert module shows too much information in the logs

### ISSUE THREAD

**Issue by Olgerd96** [ansible/ansible#84434]
### Summary

in case the `assert` is **true**, I see more lines in the log than I expect:

> ok: [user@host] => {
>     "changed": false,
>     "msg": "'success_msg value'\n"
> }

i expect to see detailed logs only in case then `assert` is **false**.

in case then `assert` is **true** i expect only necessary information like:
> ok: [user@host] => ("msg": "success_msg value")

### Issue Type

Bug Report

### Component Name

ansible.builtin.assert

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.10]
  config file = /home/ogolub/ansible/infrastructure/ansible.cfg
  configured module search path = ['/home/zzz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zzz/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/zzz/ansible/infrastructure/.collections/ansible_collections
  executable location = /home/zzz/venv/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/home/zzz/venv/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
    - name: Checking that Pythons has access to pip
      ansible.builtin.shell:
        cmd: '{{ python3_binary }} -m pip --version'
      changed_when: false
      loop:
        - 'python3'
        - 'python3.11'
      loop_control:
        loop_var: python3_binary
      register: check_python3_pip


    - name: Checking expected pip version
      ansible.builtin.assert:
        that: check_python3_pip_version | split(".") | first | int >= 22
        fail_msg: '❌ pip version {{ item.stdout }} is lower than expected'
        success_msg: '✅ pip version {{ item.stdout }} meets expectations'
        # quiet: true
      vars:
        check_python3_pip_version: '{{ item.stdout | regex_search("([0-9]+\.[0-9]+\.[0-9]+)") }}'
      loop: '{{ check_python3_pip.results }}'
      loop_control:
        index_var: check_python3_pip_idx
        label: '{{ item.cmd }}'
```

### Expected Results

i expect:
when `that` condition is **true**
add only `success_msg` to `result` without any `task_vars`

### Actual Results

```console
ok: [user@host] => {
    "changed": false,
    "msg": "'success_msg value'\n"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
