### ISSUE TITLE
ansible.builtin.dnf became incompatible with AIX

### ISSUE THREAD

**Issue by snail59** [ansible/ansible#84444]
### Summary

The commit 665d2e15d74c27df5702ba17855eee3cbeda381e was created to "remove legacy code".
Unfortunately, this breaks the compatibilty with AIX.
NOTE:  the problem comes only from the usage of base.setup_loggers() (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dnf.py#L639), nothing else.
The latest version available on AIX is 4.2.17, while this function was introduced in the version 4.22.0 of dnf (https://github.com/rpm-software-management/dnf/commit/2fb605013654206c74b6e64f1bed69f4fece3623).

### Issue Type

Bug Report

### Component Name

ansible.builtin.dnf

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.1]
  config file = ~/tests/aix/ansible.cfg
  configured module search path = ['/~/.ansible/collection/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/venvs/molecule/lib/python3.12/site-packages/ansible
  ansible collection location = ~/.ansible/collection/collections:/usr/share/ansible/collections
  executable location = ~/venvs/molecule/bin/ansible
  python version = 3.12.7 (main, Dec  7 2024, 20:52:09) [GCC 14.2.1 20241116] (~/venvs/molecule/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /tests/aix/ansible.cfg
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = /usr/bin/less

GALAXY_SERVERS:
```

### OS / Environment

Gentoo

### Steps to Reproduce

```yaml (paste below)
- name: Prepare AIX
  hosts: aix
  gather_facts: false
  tasks:
    - name: Ensure tar is installed
      ansible.builtin.dnf:
        name: tar
        state: present
        use_backend: dnf4
      vars:
        ansible_python_interpreter: /opt/freeware/libexec/python3
      environment:
        PATH: /opt/freeware/bin
```

### Expected Results

I expected the package to be installed.

### Actual Results

```console
[...]
'Base' object has no attribute 'setup_loggers'\r\n", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
