### ISSUE TITLE
break_when doesn't properly evaluate variable state when used with include_tasks

### ISSUE THREAD

**Issue by ifalatik** [ansible/ansible#84443]
### Summary

When looping over a variable and wanting to execute multiple tasks for the item, until a condition is met, the newly introduced break_when directive doesn't properly evaluate the state of the checked for variable at the end of each iteration.

The only way to achieve the behavior is by using include_tasks, as blocks don't work with a loop.

### Issue Type

Bug Report

### Component Name

loop_control

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vscode/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/vscode/.ansible/collections:/usr/share/ansible/collections:/workspace/collections
  executable location = /home/vscode/.local/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 22:26:44) [GCC 10.2.1 20210110] (/usr/local/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Debian 11

### Steps to Reproduce

```yaml
# playbook.yml
---

- name: Reproduce break_when not breaking early
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initialize variables
      ansible.builtin.set_fact:
        break_loop: false
        processed_numbers: []

    - name: Process numbers
      ansible.builtin.include_tasks: tasks/included_tasks.yml
      with_items: [1, 2, 3, 4, 5]
      loop_control:
        break_when: break_loop
        loop_var: current_number
        extended: true

    - name: Final debug
      ansible.builtin.debug:
        var: processed_numbers

```
```yaml
# tasks/included_tasks.yml
---

- name: Add current number to processed_numbers
  ansible.builtin.set_fact:
    processed_numbers: "{{ processed_numbers + [current_number] }}"

- name: Break loop if number equals 3
  ansible.builtin.set_fact:
    break_loop: true
  when: current_number == 3
```

### Expected Results

Final output should be
```
ok: [localhost] => {
    "processed_numbers": [
        1,
        2
    ]
}
```

### Actual Results

```console
PLAY [Reproduce break_when not breaking early] ************************************************************************************************************************************************************************************

TASK [Initialize variables] *******************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Process numbers] ************************************************************************************************************************************************************************************************************
included: /workspace/collections/ansible_collections/ifalatik/aoc2024/playbooks/tasks/included_tasks.yml for localhost => (item=1)
included: /workspace/collections/ansible_collections/ifalatik/aoc2024/playbooks/tasks/included_tasks.yml for localhost => (item=2)
included: /workspace/collections/ansible_collections/ifalatik/aoc2024/playbooks/tasks/included_tasks.yml for localhost => (item=3)
included: /workspace/collections/ansible_collections/ifalatik/aoc2024/playbooks/tasks/included_tasks.yml for localhost => (item=4)
included: /workspace/collections/ansible_collections/ifalatik/aoc2024/playbooks/tasks/included_tasks.yml for localhost => (item=5)

TASK [Add current number to processed_numbers] ************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Break loop if number equals 3] **********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [Add current number to processed_numbers] ************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Break loop if number equals 3] **********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [Add current number to processed_numbers] ************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Break loop if number equals 3] **********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Add current number to processed_numbers] ************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Break loop if number equals 3] **********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [Add current number to processed_numbers] ************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Break loop if number equals 3] **********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [Final debug] ****************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "processed_numbers": [
        1,
        2,
        3,
        4,
        5
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
