### ISSUE TITLE
ignore_unreachable does not permit loops to continue

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#84468]
### Summary

When a task has a loop on it, and `ignore_unreachable: true`, if the host is unreachable at any point in the loop, consecutive loop iterations are not retried.

### Issue Type

Bug Report

### Component Name

lib/ansible/executor/task_executor.py

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

N/A

### Steps to Reproduce

```yaml (paste below)
- hosts: google.com
  gather_facts: false
  tasks:
    - ping:
      loop: [1,2,3]
      ignore_unreachable: true
```

### Expected Results

All loop iterations attempted

### Actual Results

```console
The first unreachable attempt aborts the task without trying consecutive loops
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
