### ISSUE TITLE
Allow `display_skipped_hosts` to be configured via vars

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#84469]
### Summary

Allow callback plugins to be dynamically configured via vars, specifically in this case, allow `display_skipped_hosts` to be configured dynamically

### Issue Type

Feature Idea

### Component Name

lib/ansible/plugins/callback/default.py

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/callback/default.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/default.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by o-farag** [comment]
Hello, I'm trying to work on this issue at the moment. 

To clarify what is wanted, you'd like to have more fine grain control over 'display_skipped_hosts' instead of it being globally configured in 'ansible.cfg' or an environment variable. Is that correct? In that case, would you like something like this to be possible:

```

**Comment by o-farag** [comment]
Hello, I'm trying to work on this issue at the moment.

To clarify what is wanted, you'd like to have more fine grain control over 'display_skipped_hosts' instead of it being globally configured in 'ansible.cfg' or an environment variable. Is that correct? In that case, would you like something like this to be possible:

```
- name: Example playbook
  hosts: kvm_hosts
  vars:
    display_skipped_hosts: "{{ enable_skipped_hosts_display | default(false) }}"
  tasks:
    - name: Task with a condition
      ansible.builtin.debug:
        msg: "This task runs only on RedHat systems"
      when: ansible_os_family == "RedHat"
```

And then be able to run `ansible-playbook example_pb.yaml -i inventory.ini -e "display_skipped_hosts=true"`

Before I get started, is this what you are looking for?
