### ISSUE TITLE
deb822_repository: cannot configure multiple repositories in one .sources file

### ISSUE THREAD

**Issue by JKDingwall** [ansible/ansible#84465]
### Summary

I am using this task to configure a .sources file for gitlab repositories (converting from apt_repository)

```yaml
- ansible.builtin.set_fact:
    apt_get_repo_name: "gitlab"

- name: "apt: adding Gitlab repository (deb822)"
  ansible.builtin.deb822_repository:
    name: "{{ apt_get_repo_name }}"
    enabled: true
    uris:
      - "{{ item }}"
    components:
      - "main"
    suites:
      - "{{ ansible_distribution_release }}"
    types:
      - "deb"
      - "deb-src"
    signed_by: "{{ lookup('ansible.builtin.file', 'keys/{{ apt_get_repo_name }}.gpg') }}"
    allow_insecure: false
    allow_weak: false
    check_date: true
    check_valid_until: true
  loop:
    - "https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution | lower }}"
    - "https://packages.gitlab.com/gitlab/gitlab-ee/{{ ansible_distribution | lower }}"
    - "https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_distribution | lower }}"
  when:
    - "ansible_distribution_version is version('24.04', '>=')"
  notify:
    - apt-get-update
```

During execution the gitlab.sources file is written three times, once for each item.  At the end of the loop the file only contains an entry for the final gitlab-runner url.  The expected result is that all three urls are configured in separate blocks in the same file.

```
$ apt-cache policy ansible-core
ansible-core:
  Installed: 2.17.7-1ppa~jammy
  Candidate: 2.17.7-1ppa~jammy
```

### Issue Type

Bug Report

### Component Name

ansible.builtin.deb822_repository

### Ansible Version

```console
$ ansible --version


$ ansible --version
ansible [core 2.17.7]
  config file = /home/username/.ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all


$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /home/username/.ansible.cfg
DEFAULT_JINJA2_EXTENSIONS(/home/username/.ansible.cfg) = jinja2.ext.do
EDITOR(env: EDITOR) = /bin/nano
```
```


### OS / Environment

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```

### Steps to Reproduce

<!--- Paste example playbooks or commands between quotes below -->
```yaml (paste below)

```
Example task included in summary.

### Expected Results

Three configuration blocks are written in to the .sources file.  (I had just done an upgrade on the target machine from jammy->noble which rewrote the equivalent .list to a .sources with multiple entries so this appears to be supported.)

### Actual Results

```console
The .sources file only contained configuration for the final item in the loop.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
