### ISSUE TITLE
Improve assert module: per-assert msg, iterative assertions

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#84474]
### Summary

I frequently arrive at a need to assert dynamic data. Before 2.15.13 this was possible by templating `that` with a list consisting of some static tests and dynamic tests.

Alternatives are either way too costly for performance (extra loop tasks) or too uninformative (asserting list of booleans with `all` test)

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

```yaml (paste below)
- assert:
  that:
    # per-assert fail_msg
    - that: a is string
      fail_msg: a should be a string, got {{ a | type_debug }}
    - that: a | length > 5
      fail_msg: a should be at least 5 chars long
    # iterative asserts, 'iterate' provides 'assert_item.key', 'assert_item.value' for testing
    - that: assert_item.key is search('^prefix_$')
      iterate: my_dict
    - that:
        - assert_item.value is string
        - assert_item.value is truthy
      iterate: my_list
      # fail_msg is rendered in iteration context
      fail_msg: each item of my_list should be truthy, item number {{ assert_item.key }} is not
```

Failure messages for each:
```
fatal: [localhost]: FAILED! => {
    "assertion": "a is string",
    "changed": false,
    "evaluated_to": false,
    "msg": "a should be a string, got dict"
}
```
```
fatal: [localhost]: FAILED! => {
    "assertion": "a | length > 5",
    "changed": false,
    "evaluated_to": false,
    "msg": "a should be at least 5 chars long"
}
```
```
fatal: [localhost]: FAILED! => {
    "assertion": "assert_item.key is search('^prefix_$')",
    "assert_iterator": "my_dict",
    "assert_item": "not_a_prefix",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```
```
fatal: [localhost]: FAILED! => {
    "assertion": "asert_item is truthy",
    "assert_iterator": "my_list",
    "assert_item": 4,
    "changed": false,
    "evaluated_to": false,
    "msg": "each item of my_list should be truthy, item number 4 is not"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
