### ISSUE TITLE
ansible.builtin.get_url checksum doesn't work with BSD-style tags

### ISSUE THREAD

**Issue by caycehouse** [ansible/ansible#84476]
### Summary

When downloading and verifying the checksum of a Fedora ISO using get_url, the process fails because it cannot read BSD-style checksum tags. Fedora provides checksums in BSD format, but the checksum parameter expects the GNU style format.

### Issue Type

Bug Report

### Component Name

ansible.builtin.get_url

### Ansible Version

```console
ansible [core 2.17.7]
  config file = None
  configured module search path = ['/home/housecay21/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/housecay21/.local/lib/python3.13/site-packages/ansible
  ansible collection location = /home/housecay21/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/housecay21/.local/bin/ansible
  python version = 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(env: ANSIBLE_HOST_KEY_CHECKING) = False

ssh:
___
host_key_checking(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

### OS / Environment

Fedora 41

### Steps to Reproduce

```yaml (paste below)
---
- name: Download Image
  hosts: localhost
  tasks:
    - ansible.builtin.get_url:
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
        checksum: sha256:https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-40-1.14-x86_64-CHECKSUM
        dest: images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
```

### Expected Results

I expected get_url to support BSD-style sha256 tags.

### Actual Results

```console
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": false,
            "checksum": "sha256:https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-40-1.14-x86_64-CHECKSUM",
            "ciphers": null,
            "client_cert": null,
            "client_key": null,
            "decompress": true,
            "dest": "images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "timeout": 10,
            "tmp_dest": null,
            "unredirected_headers": [],
            "unsafe_writes": false,
            "url": "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2",
            "url_password": null,
            "url_username": null,
            "use_gssapi": false,
            "use_netrc": true,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Unable to find a checksum for file 'Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2' in 'https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-40-1.14-x86_64-CHECKSUM'"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
