### ISSUE TITLE
Unsafe conditionals checks prevent from composing dynamic assert lists

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#84470]
### Summary

After upgrade from 2.15.6 to 2.15.13 a lot of asserts break.

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.13]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

FreeBSD 14.1

### Steps to Reproduce

An example of a complex assert that worked on 2.15.6:

```yaml (paste below)
    - name: assert git commit and push vars
      assert:
        fail_msg: |
          Ensure git_clone_worktree is leading to actual worktree
          Ensure git_cp_files is a list of relative file paths to be committed
        success_msg: |2
            Working on: {{ git_cp_worktree | regex_replace(home_path, '~') }}
          With git dir: {{ git_cp_gitdir | regex_replace(home_path, '~') }}
        quiet: no
        that: "{{ checks_static + checks_dynamic }}"
      vars:
        checks_static:
          - git_cp_worktree is string
          - git_cp_worktree is truthy
          - git_cp_worktree is directory
          - git_cp_gitdir is string
          - git_cp_gitdir is truthy
          - git_cp_gitdir is directory
          - git_cp_files is defined
          - git_cp_files|type_debug == 'list'
          - git_cp_files is truthy
          - git_cp_files | reject('string') | length == 0
          - git_cp_message is string
          - git_cp_message is truthy
          - git_cp_key_file|default('') is string
          - git_cp_key_file|default('') is falsy or git_cp_key_file is exists
          - git_cp_lock_timeout is integer or (git_cp_lock_timeout is string and git_cp_lock_timeout.isnumeric())
          - git_lock_timeout is integer or (git_lock_timeout is string and git_lock_timeout.isnumeric())
        checks_dynamic: |-
          {% set ns = namespace(out=[]) %}
          {% for idx in range(0, git_cp_files|length) %}
          {% set _ = ns.out.extend([
            'git_cp_files[{}] is not abs'.format(idx),
            '[git_cp_worktree, git_cp_files[{}]] | path_join is file'.format(idx)
          ]) %}
          {% endfor %}
          {{ ns.out }}
```
If I comment out ` set _ = ...` block in the template of `checks_dynamic`, error goes away, but those checks are lost. Any solution that removes templating from `that` either requires loops/extra tasks to assert dynamic data (heavy performance hit), or removes ability to see the specific check that failed (stuff like `that: "(checks_static + checks_dynamic) is all"` will not show anything useful on failure).

Additionally if any simple static item akin `- a[0] == a[1]` can fail unexpectedly if `a` set at block level and references other vars.

### Expected Results

I expected to be able to feed lists of checks to `that`.

### Actual Results

```console
"Conditional is marked as unsafe, and cannot be evaluated."
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
@Vladimir-csp `ansible-core` 2.15 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by vbotka** [comment]
The condition is wrong. It should be

```yaml
    that: (checks_static + checks_dynamic) is all
```

**Comment by vbotka** [comment]
Why do I receive email notifications on this issue?

quoting from the header:

```
Date: Fri, 13 Dec 2024 02:51:56 -0800
From: Vladimir-csp <notifications@github.com>
Reply-To: ansible/ansible <reply+ABJO4KUWOZYX4ZEXQOXBIAWFM7ZMZEVBNHHKGNBK5Q@reply.github.com>
To: ansible/ansible <ansible@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <ansible/ansible/issues/84470@github.com>
Subject: [ansible/ansible] Unsafe conditionals checks prevent from composing dynamic assert lists (Issue #84470)
  ...
X-GitHub-Sender: Vladimir-csp
X-GitHub-Recipient: vbotka
X-GitHub-Reason: subscribed
List-ID: ansible/ansible <ansible.ansible.github.com>
List-Archive: https://github.com/ansible/ansible
List-Post: <mailto:reply+ABJO4KUWOZYX4ZEXQOXBIAWFM7ZMZEVBNHHKGNBK5Q@reply.github.com>
List-Unsubscribe: <mailto:unsub+ABJO4KUWOZYX4ZEXQOXBIAWFM7ZMZEVBNHHKGNBK5Q@reply.github.com>, <https://github.com/notifications/unsubscribe/one-click/ABJO4KTQCQQLBVITCBBD6ZT2FK34ZANCNFSM6AAAAABTRXEIYU>
List-Unsubscribe-Post: List-Unsubscribe=One-Click
X-Auto-Response-Suppress: All
destinations: vbotka@gmail.com
X-GitHub-Recipient-Address: vbotka@gmail.com
```

**Comment by Vladimir-csp** [comment]
> The condition is wrong. It should be

Fixed this in the description, but again, this variant will not show what assertion failed.

**Comment by s-hertel** [comment]
The issue with `that: (checks_static + checks_dynamic) is all` is your `checks_static` list is a list of strings, not Jinja2 expressions. Similarly, `checks_dynamic` is something like:
```
[
        "git_cp_files[0] is not abs",
        "[git_cp_worktree, git_cp_files[0]] | path_join is file",
        "git_cp_files[1] is not abs",
        "[git_cp_worktree, git_cp_files[1]] | path_join is file",
        "git_cp_files[2] is not abs",
        "[git_cp_worktree, git_cp_files[2]] | path_join is file"
]
```

These are not boolean expressions, it's a list of strings, so an `is all` on either of these lists will be True regardless.

@vbotka You're following the ansible/ansible repo. If you click the drop down `Unwatch` at the top of https://github.com/ansible/ansible it will give you choices to limit or customize notifications.

**Comment by Vladimir-csp** [comment]
I'm not considering `that: (checks_static + checks_dynamic) is all` as a viable solution anyway.

**Comment by s-hertel** [comment]
If you want `assert` to give you details about what expression fails, you'd need to pass a list of expressions, not a single boolean returned by `is all`. `that: (checks_static + checks_dynamic)` is closer,  but fails for the same reason (it's a list of truthy strings, not a list of templates). You'd need curly braces around each of those check_statics items, for example, so they're Jinja2 expressions, not just strings.

FYI it's a breaking change that was called out in the porting guide (here's the 2.15 backport: https://github.com/ansible/ansible/pull/82294), so it's not a bug (but maybe addressable as a feature).

**Comment by Vladimir-csp** [comment]
> If you want `assert` to give you details about what expression fails, you'd need to pass a list of expressions, not a single boolean returned by `is all`

That is the point. `that` expects a list of strings containing expressions, the example did just that: fed `that` a list of strings, each an expression. This is a feature request then: an ability to assert dynamic list of expressions.

Although templating conditions gives much more room for optimizing tasks, builtin iterators can still be a solution: #84474

**Comment by s-hertel** [comment]
> This is a feature request then: an ability to assert dynamic list of expressions.

<details><summary>That's still functional.</summary><br>

```yaml
- hosts: localhost
  gather_facts: no
  ignore_errors: true
  vars:
    foo: good
    bar: 1
    expressions: &strings
      - "foo is string"
      - "bar is string"
    git_cp_worktree: /home/shertel/ansible/
    safe_git_cp_files: ["requirements.txt", "README.md", "Missing"]
    unsafe_git_cp_files: "{{ lookup('vars', 'safe_git_cp_files') }}"  # simulate the problem
  tasks:
    # Fine
    - assert:
        that: "{{ expressions }}"

    # Fine
    - assert:
        that: *strings

    # Problem
    - assert:
        that: "{{ expressions + checks_dynamic }}"
      vars:
        checks_dynamic: |-
          {% set ns = namespace(out=[]) %}
          {% for idx in range(0, unsafe_git_cp_files|length) %}
          {% set _ = ns.out.extend([
            'unsafe_git_cp_files[{}] is not abs'.format(idx),
            '[git_cp_worktree, unsafe_git_cp_files[{}]] | path_join is file'.format(idx)
          ]) %}
          {% endfor %}
          {{ ns.out }}

    # Fine
    - assert:
        that: "{{ expressions + checks_dynamic }}"
      vars:
        checks_dynamic: |-
          {% set ns = namespace(out=[]) %}
          {% for idx in range(0, safe_git_cp_files|length) %}
          {% set _ = ns.out.extend([
            'safe_git_cp_files[{}] is not abs'.format(idx),
            '[git_cp_worktree, safe_git_cp_files[{}]] | path_join is file'.format(idx)
          ]) %}
          {% endfor %}
          {{ ns.out }}
```
</details>

I'm not sure which of your variables are actually unsafe, because there's not enough context.

**Comment by flowerysong** [comment]
It's also possible to write these assertions without using an extra level of templating, which works even when the variables are unsafe.

```yaml
    - assert:
        that:
          - git_cp_files | select('abs') | length == 0
          - "[git_cp_worktree] | product(git_cp_files) | map('path_join') | reject('file') | length == 0"
```
