### ISSUE TITLE
user module hangs on ssh-keygen 9.9p1 and newer

### ISSUE THREAD

**Issue by leegarrett** [ansible/ansible#84484]
### Summary

When running a task like this against a target with openssh-client 9.9p1 or newer, it will hang indefinitely:
```
    - name: Create user with ssh key
      user:
        name: ansibulluser
        state: present
        generate_ssh_key: yes
        force: yes
        ssh_key_file: .ssh/test_id_rsa
        ssh_key_passphrase: secret_passphrase
```

This is the relevant code snippet:
https://github.com/ansible/ansible/blob/cae4f90b21bc40c88a00e712d28531ab0261f759/lib/ansible/modules/user.py#L1282-L1302

Problem is that openssh 9.9p1 and newer the first prompt is `Enter passphrase for "/home/ansibulluser/.ssh/test_id_rsa" (empty for no passphrase):`, so the resulting code never matches.

### Issue Type

Bug Report

### Component Name

user

### Ansible Version

```console
devel
```

### Configuration

```console
irrelevant, affects CI
```

### OS / Environment

Debian 13 (trixie), or other distros with openssh-client 9.9p1 or newer.

### Steps to Reproduce

```yaml (paste below)
    - name: Create user with ssh key
      user:
        name: ansibulluser
        state: present
        generate_ssh_key: yes
        force: yes
        ssh_key_file: .ssh/test_id_rsa
        ssh_key_passphrase: secret_passphrase

```

### Expected Results

* creates user an ssh key

### Actual Results

```console
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ********************************************************

TASK [Gathering Facts] **************************************************
ok: [localhost]

TASK [Create user with ssh key] *****************************************
[hangs]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
