### ISSUE TITLE
Ability to hide 'included' lines when using include_role or include_tasks with default callback plugin

### ISSUE THREAD

**Issue by eoli3n** [ansible/ansible#84499]
### Summary

I just upgraded, and notice that latest now prints "included: host1, host2, hostX" for all included roles.
I use this playbook to be able to auto tag roles.

```yaml
  tasks:
    - include_role:
        name: "{{ role_item }}"
        apply:
          tags: "{{ role_item | split('/') | last }}"
      tags: always
      loop_control:
        loop_var: role_item
      loop:
        - role1
        - role2
        - sub/rolea
        - sub/roleb
```

It produces an huge output with ~1000 hosts in inventory

```
included: role1 for host1, host2, host3
included: role2 for host1, host2, host3
included: sub/rolea for host1, host2, host3
included: sub/roleb for host1, host2, host3
```

### Issue Type

Feature Idea

### Component Name

callback

### Additional Information

I want to be able to configure default callback to ignore those lines, even in verbose

```
[defaults]
callback_pretty_results = yes
callback_result_format = yaml
display_skipped_hosts = no
display_failed_stderr = yes
show_custom_stats = yes
verbosity = 1

display_included = no
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
