### ISSUE TITLE
play_hosts in vars_prompt is restricted to hosts in play

### ISSUE THREAD

**Issue by jovial** [ansible/ansible#84515]
### Summary

Using ansible 2.15.13 play_hosts in vars_prompt is restricted to hosts in play

### Issue Type

Feature Request

### Component Name

vars_prompt

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/home/cloud-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible3.12/lib64/python3.12/site-packages/ansible
  ansible collection location = /home/cloud-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /tmp/ansible3.12/bin/ansible
  python version = 3.12.5 (main, Dec  3 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/tmp/ansible3.12/bin/python3.12)
  jinja version = 3.1.5
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Rocky 9

### Steps to Reproduce

```yaml (paste below)
---

- hosts: overcloud
  gather_facts: false
  vars_prompt:
    - name: confirm_deprovision
      prompt: |
        The following hosts will be deprovisioned:
        {{ play_hosts | join(', ') }}
        If you want to proceed type: yes
      default: "no"
      private: false
  tasks:
    - debug:
        var: play_hosts
```

inventory:
```
host1 ansible_connection=local

[overcloud]
host2 ansible_connection=local
```

```
$ ansible-playbook -i /tmp/inventory /tmp/test.yml
```

### Expected Results

play_hosts in vars_prompt matches play_hosts in tasks

### Actual Results

```console
(kayobe-venv) [cloud-user@kayobe-dev kayobe]$ ansible-playbook -i /tmp/inventory /tmp/test.yml
The following hosts will be deprovisioned:
host1, host2
If you want to proceed type: yes
 [no]: no

PLAY [overcloud] *********************************************************************************************************************************************************************************************************************************************

TASK [debug] *************************************************************************************************************************************************************************************************************************************************
ok: [host2] => {
    "play_hosts": [
        "host2"
    ]
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
host2                      : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
