### ISSUE TITLE
When using transfer_method = smart, only issue warning(s) if all methods fail.

### ISSUE THREAD

**Issue by jniggemann** [ansible/ansible#84516]
### Summary

When using `transfer_method = smart `in `[ssh_connection]` section of `ansible.cfg`, the methods sftp, scp, and piped are tried / used.
IMHO we have to issue a warning only when all three fail.

### Usecase
Using smart, I get 2 warning messages when targeting a host where method "piped" works. But when piped works, files can be transferred, making me think the 2 warnings displayed are unnecessary.  
OTOH, if none of the three methods work, a warning needs to be issued.

### Issue Type

Feature Idea

### Component Name

ansible.cfg

### Additional Information

```yaml (paste below)
---
- name: "tasks for all hosts"
  hosts: all
  tasks:
    - name: "Check virt"
      debug:
        msg: "ansible_virtualization_role: {{ansible_virtualization_role}}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
