### ISSUE TITLE
ansible.builtin.uri forms location incorrectly from relative redirect

### ISSUE THREAD

**Issue by rmuir** [ansible/ansible#84540]
### Summary

when a server returns a relative redirect, ansible `uri` module tries to form an absolute `location` result by joining the original url with the relative result from the http location header.

But this doesn't work correctly for many cases of relative redirects, especially if they contain parameters.

See the example reproducer, but it is easy to reproduce with a unit test too. I will take a stab at a PR.

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/home/rmuir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/rmuir/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.1 (main, Dec  4 2024, 18:05:56) [GCC 14.2.1 20240910] (/usr/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = nvim

GALAXY_SERVERS:
```

### OS / Environment

Happens on any OS (centos stream and arch at least)

### Steps to Reproduce

```yaml
- name: simple repro of uri issues
  hosts: localhost
  gather_facts: false
  tasks:
    - name: issue request that will redirect to /get
      uri:
        url: http://httpbin.org/relative-redirect/1?foo=bar
        status_code: 302
        follow_redirects: none
      register: response
    - name: verify correct absoluteized location header
      assert:
        that:
          # instead it is http://httpbin.org?foo=bar/get
          - response.location == 'http://httpbin.org/get'
```

### Expected Results

Expect correctly  formed `response.location` of `http://httpbin.org/get`

### Actual Results

```console
Instead `response.location` is set to `http://httpbin.org?foo=bar/get`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
