### ISSUE TITLE
Task timeout breaks failed_when handling in loop tasks

### ISSUE THREAD

**Issue by colml** [ansible/ansible#84558]
### Summary

If failed_when is used in a looping task with timeout, a timeout does not correctly register a task failure if there was a success earlier in the loop.

When a task timeout is hit, task_executor.py _execute() returns early with failed=True, omitting failed_when_result.

When task_result.py is_failed() processes results, if any of the results contain the failed_when_result key then only that key is used to determine if the task failed. So _check_key('failed_when_result') will only find the earlier success of the loop and ignore the timed out result that doesn't have the failed_when_result key.

This leads to inconsistent handling of task timeouts.

Assuming this is a valid bug, there are a couple approaches to resolve it:
1. Ensure failed_when_result=True is added on timeout for tasks with failed_when
2. Modify is_failed() and/or _check_key() to handle results with partial failed_when_result entries.

### Issue Type

Bug Report

### Component Name

lib/ansible/executor/task_result.py
lib/ansible/executor/task_executor.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/share/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] (/home/ubuntu/.local/share/pipx/venvs/ansible-core/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None

GALAXY_SERVERS:
```

### OS / Environment

Ubuntu 24.04

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Task 1, timeout
      command: sleep {{ item }}
      timeout: 2
      register: status
      failed_when: status.failed
      loop: [1, 4]

    - name: Task 2, show status
      debug:
        msg: "Second task was run. Task 1 status: {{ status }}"
```

### Expected Results

Task 2 should never be run as we will always fail due to the timeout in task 1 for the second loop item.

### Actual Results

```console
Task 1 is not marked as failed, execution continues. If task 1 was in a rescue block the rescue would never be called.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
