### ISSUE TITLE
Ansible exposes password in fatal error message

### ISSUE THREAD

**Issue by Stefanhg** [ansible/ansible#84557]
### Summary

Hello,

I was debugging some code where I needed to clone using the git module. In my case I used credentials stored under Resources in website in order to clone.

While debugging and going through the testresult the fatal error message exposed my password. 

### Issue Type

Bug Report

### Component Name

git

### Ansible Version

```console
Ansible AWX 24.6.2.dev0+g94e5795dfc.d20241107
(im not an Ansible administrator)
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Raspbian OS

### Steps to Reproduce

```
  ansible.builtin.git:
    repo: '{{git_user}}:{{git_password}}@https://git.local.net/my_project.git'
    dest: "{{ ansible_env.HOME }}/dect_noise_scanner"
    accept_hostkey: true
```

The credentials created is of type Simple Username/Password
And identifier is called "git" 

### Expected Results

Password completely hidden

### Actual Results

```console
I have hidden it away as "MY_EXPOSED_PASSWORD", which is what showed my informations.

fatal: [it-04182]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote 'shg:********@https://git.local.net/my_project.git' -h refs/heads/HEAD", "msg": "fatal:********@https' is not supported", "rc": 128, "stderr": "fatal: protocol 'shg:MY_EXPOSED_PASSWORD@https' is not supported\n", "stderr_lines": ["fatal: protocol 'shg:MY_EXPOSED_PASSWORD@https' is not supported"], "stdout": "", "stdout_lines": []}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
