### ISSUE TITLE
Make ansible.builtin.wait_for accept a list of files or a file regex to wait for

### ISSUE THREAD

**Issue by bergstenarn** [ansible/ansible#84565]
### Summary

I want to wait for either of two files to appear in the file system, or time out if neither file has appeared after X seconds. I thought I could use module _ansible.builtin.wait_for_, but I can't since it seems it's not possible to specify the path of the files with a regular expression nor as a list of files.

### Issue Type

Feature Request

### Component Name

ansible.builtin.wait_for

### Ansible Version

```
$ ansible --version
ansible [core 2.15.4]
  config file = None
  configured module search path = ['/home/********/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/*********/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.1
  libyaml = True
```

### Additional Information

Here is what I'd like to do where any file which appears and that matches the regular expression ends the wait:
```
- name: Wait for either file to appear
  ansible.builtin.wait_for:
    path: /the/path/to/dummyfile.*
    state: present
    timeout: 30
```
This might be an alternative where a file that matches any of the ones listed ends the wait:
```
- name: Wait for either file to appear
  ansible.builtin.wait_for:
    path:
      - /the/path/to/dummyfile.success
      - /the/path/to/dummyfile.failure
    state: present
    timeout: 30
```
Currently I have worked around the problem by doing this, which isn't ideal as the _wait_for_ module exists and could be used with the improvement outlined above:
```
- name: Wait for either file to appear # noqa no-changed-when
  ansible.builtin.shell: t=0; until [ -e '/the/path/to/dummyfile.*' ] || (( t++ >= 30 )); do sleep 1; done
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
