### ISSUE TITLE
DNF5 Packages for argument 'libavcodec-freeworld' available, but not installed

### ISSUE THREAD

**Issue by dankobg** [ansible/ansible#84578]
### Summary

I have this task to install a package from rpmfusion-free repo. It is enabled, installation of other pkgs from that repo are working but this one fails always. This is from a fresh installation of Fedora 41.

```
- name: Install libavcodec-freeworld
  ansible.builtin.dnf5:
    name:
      - libavcodec-freeworld
    state: latest
```

### Issue Type

Bug Report

### Component Name

dnf5

### Ansible Version

```console
ansible [core 2.16.14]
  config file = /home/danko/projects/fedora_workstation/ansible.cfg
  configured module search path = ['/home/danko/.local/share/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/danko/.local/share/ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.13.1 (main, Dec  9 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

### Configuration

```console
ANSIBLE_HOME(env: ANSIBLE_HOME) = /home/danko/.local/share/ansible
CONFIG_FILE() = /home/danko/projects/fedora_workstation/ansible.cfg
DEFAULT_HOST_LIST(/home/danko/projects/fedora_workstation/ansible.cfg) = ['/home/danko/project>
DEFAULT_VAULT_PASSWORD_FILE(/home/danko/projects/fedora_workstation/ansible.cfg) = /home/danko>
EDITOR(env: EDITOR) = /usr/local/bin/hx
```

### OS / Environment

Linux fedora 6.12.9-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jan  9 16:05:40 UTC 2025 x86_64 GNU/Linux

### Steps to Reproduce

It is kind of weird, it does not work but when i install pkg manually with: sudo dnf install libavcodec-freeworld, it worked after that.

### Expected Results

Expected to install normally

### Actual Results

```console
TASK [multimedia : Install libavcodec-freeworld] *******************************************
task path: /home/danko/projects/fedora_workstation/roles/multimedia/tasks/main.yaml:37
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: danko
<127.0.0.1> EXEC /bin/sh -c 'echo ~danko && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/danko/.ansible/tmp `"&& mkdir "` echo /home/danko/.ansible/tmp/ansible-tmp-1737302345.2812464-110821-266541792809684 `" && echo ansible-tmp-1737302345.2812464-110821-266541792809684="` echo /home/danko/.ansible/tmp/ansible-tmp-1737302345.2812464-110821-266541792809684 `" ) && sleep 0'
Using module file /usr/lib/python3.13/site-packages/ansible/modules/dnf5.py
<127.0.0.1> PUT /home/danko/.local/share/ansible/tmp/ansible-local-110723_v5fwrzu/tmpxrjdzp_b TO /home/danko/.ansible/tmp/ansible-tmp-1737302345.2812464-110821-266541792809684/AnsiballZ_dnf5.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/danko/.ansible/tmp/ansible-tmp-1737302345.2812464-110821-266541792809684/ /home/danko/.ansible/tmp/ansible-tmp-1737302345.2812464-110821-266541792809684/AnsiballZ_dnf5.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -p "[sudo via ansible, key=czkbgfomljzigvqqsjgnxcjhruchgsgy] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-czkbgfomljzigvqqsjgnxcjhruchgsgy ; /usr/bin/python3 /home/danko/.ansible/tmp/ansible-tmp-1737302345.2812464-110821-266541792809684/AnsiballZ_dnf5.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/danko/.ansible/tmp/ansible-tmp-1737302345.2812464-110821-266541792809684/ > /dev/null 2>&1 && sleep 0'
fatal: [workstation]: FAILED! => {
    "changed": false,
    "failures": [
        "Packages for argument 'libavcodec-freeworld' available, but not installed."
    ],
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "allowerasing": true,
            "auto_install_module_deps": true,
            "autoremove": false,
            "bugfix": false,
            "cacheonly": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "libavcodec-freeworld"
            ],
            "nobest": false,
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "sslverify": true,
            "state": "latest",
            "update_cache": false,
            "update_only": false,
            "validate_certs": true
        }
    },
    "msg": "Failed to install some of the specified packages",
    "rc": 1
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/dnf5.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dnf5.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@dankobg `ansible-core` 2.16 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by dankobg** [comment]
it's still the same error, tried with latest 2.18.1

**Comment by mkrizek** [comment]
I was not able to reproduce the issue on a fresh Fedora 41 container, created using:
`podman run --name container --rm -it --entrypoint bash fedora:41`.

I suspect a package installed on your system that is not installed on that container is causing the issue. Are you able to provide a list of packages installed on the target system (your Fedora 41 installation) that is not installed on a fresh container created as above?

**Comment by dankobg** [comment]
I think i replicated it with these steps:
playbook.yaml
```
- name: Test
  hosts: localhost
  connection: local
  become: true
  become_user: root
  gather_facts: false

  tasks:
    ### DRIVERS
    - name: Install some drivers
      ansible.builtin.dnf5:
        name:
          - libva-nvidia-driver
          - libva-utils
          - vdpauinfo
        state: latest
        update_cache: true

    # CODECS    
    - name: Swap ffmpeg-free with rpmfusion ffmpeg
      ansible.builtin.command:
        cmd: dnf swap -y --allowerasing ffmpeg-free ffmpeg
      register: swap_result
      changed_when: "'Nothing to do' not in swap_result.stdout"

    - name: Update group multimedia codecs
      ansible.builtin.dnf5:
        name:
          - '@multimedia'
          - '@sound-and-video'
        state: latest
        install_weak_deps: false
        exclude:
          - PackageKit-gstreamer-plugin
          - gstreamer1-plugins-bad-free
          - gstreamer1-plugins-ugly-free

    - name: Install additional plugins
      ansible.builtin.dnf5:
        name:
          - ffmpegthumbnailer
          - gstreamer1-plugins-bad-freeworld
          - gstreamer1-plugins-ugly
          - libavcodec-freeworld
          - mozilla-openh264
        state: latest
        enablerepo: fedora-cisco-openh264
        allowerasing: true
```
1.)
docker run -it -v ./playbook.yaml:/playbook.yaml fedora:41 bash
2.)
sudo dnf update -y && \
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y && \
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y && \
sudo dnf install ansible -y
3.)
ansible-playbook --connection=local --inventory 127.0.0.1, playbook.yaml
