### ISSUE TITLE
Cannot get correct base name of a SMB path using 'win_basename' filter

### ISSUE THREAD

**Issue by TerryzzzzzzZ** [ansible/ansible#84570]
### Summary

When I try to use **'win_basename'** filter to get the last name component of a Windows **SMB** folder path, it fails to get the correct name.

### Issue Type

Bug Report

### Component Name

win_basename

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.7]
  config file = /home/xxxxx/.ansible.cfg
  configured module search path = ['/home/xxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/xxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
    - name: Set fact
      ansible.builtin.set_fact:
        src_path: '\\machine_name\test'

    - name: Get basename
      ansible.builtin.debug:
        msg: "{{ src_path | win_basename }}"
```

### Expected Results

It is expected to get a debug message of "test" but actually it get ""

### Actual Results

```console
TASK [Get basename] ***************************************************************************************************************
ok: [localhost] => {
    "msg": ""
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by ansibot** [comment]
@TerryzzzzzzZ `ansible-core` 2.16 is not supported and no longer receives bug fixes. Please test against one of [the supported versions](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) of `ansible-core`, preferably the most recent one, to see whether the bug has been fixed.

[click here for bot help](https://github.com/ansible/ansibotmini#ansibotmini)

**Comment by jborean93** [comment]
The `win_basename` filter just wraps [ntpath.basename](https://github.com/ansible/ansible/blob/3398c102b5c41d48d0cbc2d81f9c004f07ac3fcb/lib/ansible/plugins/filter/core.py#L623). The reason why this is returning an empty string is because in a UNC path the root is both the server and share, if you were to add another entry beyond the share component it will work.

```python
>>> ntpath.basename(r"\\server\share\test\foo.txt")
'foo.txt'
>>> ntpath.basename(r"\\server\share\foo.txt")
'foo.txt'
>>> ntpath.basename(r"\\server\foo.txt")
''
```

When there is just the `\\server\share` side this is the path root and there is no basename.

**Comment by TerryzzzzzzZ** [comment]
Thanks @jborean93, is there a filter that can help me get 'server' in '\\server\share'?

**Comment by jborean93** [comment]
It's somewhat difficult due to backslash being used as an escape char but you can achieve the same thing with

```yml
- hosts: SERVER2025
  gather_facts: false
  vars:
    path: \\server\share
  tasks:
  - debug:
      msg: The share is '{{ path.split('\')[-1] }}'
```

Once you share quoting YAML values it gets a bit more difficult due to the escaping rules and parsing logic Ansible places on option values. In those scenarios it is just easier to store the backslash as a variable

```yaml
- hosts: SERVER2025
  gather_facts: false
  vars:
    path: \\server\share
    backslash: \
    # backslash: '\'  # Single quotes don't need to have it escaped
    # backslash: "\\"  # If double quoted you need to escape it
  tasks:
  - debug:
      msg: The share is '{{ path.split(backslash)[-1] }}'
```
