### ISSUE TITLE
Loop did process all items (when ignored)

### ISSUE THREAD

**Issue by reini-1** [ansible/ansible#84591]
### Summary

Given the following playbook:

test_loop_include_var_change.yml:

```yaml
- name: TEST loop with include and changed variable
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set test var
      ansible.builtin.set_fact:
        test_var: true

    - name: Some text before
      ansible.builtin.debug:
        msg: 'Before'

    - name: Call tasks in a loop
      ansible.builtin.include_tasks: test_loop_include_var_change_include.yml
      when: test_var
      loop: '{{ range(1, 5) | list }}'

    - name: Some text after
      ansible.builtin.debug:
        msg: 'After'
```

test_loop_include_var_change_include.yml:

```yaml
---
- name: Iteration
  ansible.builtin.debug:
    msg: '{{ item }}'

- name: Change test var
  ansible.builtin.set_fact:
    test_var: false
  when: item | int > 2
```

results in:

```shell
$ ansible-playbook tests/test_loop_include_var_change.yml -i localhost,

PLAY [TEST loop with include and changed variable] *********************************************************************

TASK [Set test var] ****************************************************************************************************
ok: [localhost]

TASK [Some text before] ************************************************************************************************
ok: [localhost] => {
    "msg": "Before"
}

TASK [Call tasks in a loop] ********************************************************************************************
included: /home/reini/Source/ops/ansible/tests/test_loop_include_var_change_include.yml for localhost => (item=1)
included: /home/reini/Source/ops/ansible/tests/test_loop_include_var_change_include.yml for localhost => (item=2)
included: /home/reini/Source/ops/ansible/tests/test_loop_include_var_change_include.yml for localhost => (item=3)
included: /home/reini/Source/ops/ansible/tests/test_loop_include_var_change_include.yml for localhost => (item=4)

TASK [Iteration] *******************************************************************************************************
ok: [localhost] => {
    "msg": 1
}

TASK [Iteration] *******************************************************************************************************
ok: [localhost] => {
    "msg": 2
}

TASK [Iteration] *******************************************************************************************************
ok: [localhost] => {
    "msg": 3
}

TASK [Change test var] *************************************************************************************************
ok: [localhost]

TASK [Iteration] *******************************************************************************************************
ok: [localhost] => {
    "msg": 4
}

TASK [Change test var] *************************************************************************************************
ok: [localhost]

TASK [Some text after] *************************************************************************************************
ok: [localhost] => {
    "msg": "After"
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
```

Why is the tasks in test_loop_include_var_change_include.yml still included/executed after condition is changed after the 2nd iteration?
Is this a bug or a feature? 

### Issue Type

Bug Report

### Component Name

ansible core

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.7]
  config file = /home/reini/ansible/ansible.cfg
  configured module search path = ['/home/reini/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/reini/.ansible/collections:/usr/share/ansible/collections:/home/reini/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING(/home/reini/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/home/reini/ansible/ansible.cfg) = ['/home/reini/.ansible/collections', '/usr/share/ansible/collections', '/home/reini/ansible/collections']
CONFIG_FILE() = /home/reini/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/reini/ansible/ansible.cfg) = ['/home/reini/ansible/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/reini/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/reini/ansible/ansible.cfg) = ['/home/reini/ansible/roles']
DEFAULT_TRANSPORT(/home/reini/ansible/ansible.cfg) = ssh
DEFAULT_VAULT_IDENTITY_LIST(/home/reini/ansible/ansible.cfg) = ['ansible-vault-helper.sh']
DEPRECATION_WARNINGS(/home/reini/ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/reini/ansible/ansible.cfg) = False
EDITOR(env: EDITOR) = /etc/alternatives/editor
INTERPRETER_PYTHON(/home/reini/ansible/ansible.cfg) = auto_silent
PAGER(env: PAGER) = /etc/alternatives/pager

CALLBACK:
========

default:
_______
display_skipped_hosts(/home/reini/ansible/ansible.cfg) = False
pretty_results(/home/reini/ansible/ansible.cfg) = True
show_task_path_on_failure(/home/reini/ansible/ansible.cfg) = True

minimal:
_______
pretty_results(/home/reini/ansible/ansible.cfg) = True

CONNECTION:
==========

local:
_____
pipelining(/home/reini/ansible/ansible.cfg) = True

psrp:
____
pipelining(/home/reini/ansible/ansible.cfg) = True

ssh:
___
pipelining(/home/reini/ansible/ansible.cfg) = True
scp_executable(/home/reini/ansible/ansible.cfg) = /usr/bin/scp
ssh_executable(/home/reini/ansible/ansible.cfg) = /usr/bin/ssh

winrm:
_____
pipelining(/home/reini/ansible/ansible.cfg) = True
```

### OS / Environment

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 24.04.1 LTS
Release: 24.04
Codename: noble

running in WSL on Windows 11

### Steps to Reproduce

see Summary

### Expected Results

included task is not included/executed after variable from condition changes to false.

### Actual Results

```console
change of variable is ignored and and tasks are included for all loop iterations.
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
