### ISSUE TITLE
Enhance inventory plugins by allowing dyanmic group names via jinja

### ISSUE THREAD

**Issue by minsis** [ansible/ansible#84605]
### Summary

Currently ansible inventory plugins are locked for `group` names either via groups or `keyed_groups`. It would be nice allow dynamic group names in some way.

### Issue Type

Feature Idea

### Component Name

lib.ansible.plugins.inventory.Constructable

### Additional Information

Currently, there is jinja templating for `parent_group` inside `keyed_groups`. So maybe add templating to default_value which allows a user to omit the key and update default_value with a jinja template.

https://github.com/ansible/ansible/blob/e6adddcaf8d4cf46185a90be89a574ba01cc6b84/lib/ansible/plugins/inventory/__init__.py#L410

```yaml (paste below)
keyed_groups:
  - key:
    default_value: "{{ name.split('.')[1] }}"
    separator: ""
```

Another option might be to add another variable.
```yaml
dynamic_groups:
  - name: "{{ name.split('.')[1] }}"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
