### ISSUE TITLE
ansible.builtin.service_facts incorrect and simplified state

### ISSUE THREAD

**Issue by NomakCooper** [ansible/ansible#84607]
### Summary

As indicated in the title, the **`ansible.builtin.service_facts`** module does not accurately report the state of services when the source is **`systemd`**.

On hosts using **`systemd`**, the state **`exited`** or **`dead`** indicates that the service is inactive. 
However, this does not confirm that the service is properly in the **`stopped`** state.

According to the code in the **`SystemctlScanService`** class [here](https://github.com/ansible/ansible/blob/e6adddcaf8d4cf46185a90be89a574ba01cc6b84/lib/ansible/modules/service_facts.py#L260C1-L295C127) :

```python
class SystemctlScanService(BaseService):

    BAD_STATES = frozenset(['not-found', 'masked', 'failed'])

    def systemd_enabled(self):
        return is_systemd_managed(self.module)

    def _list_from_units(self, systemctl_path, services):

        # list units as systemd sees them
        rc, stdout, stderr = self.module.run_command("%s list-units --no-pager --type service --all --plain" % systemctl_path, use_unsafe_shell=True)
        if rc != 0:
            self.module.warn("Could not list units from systemd: %s" % stderr)
        else:
            for line in [svc_line for svc_line in stdout.split('\n') if '.service' in svc_line]:

                state_val = "stopped"
                status_val = "unknown"
                fields = line.split()

                # systemd sometimes gives misleading status
                # check all fields for bad states
                for bad in self.BAD_STATES:
                    # except description
                    if bad in fields[:-1]:
                        status_val = bad
                        break
                else:
                    # active/inactive
                    status_val = fields[2]

                service_name = fields[0]
                if fields[3] == "running":
                    state_val = "running"

                services[service_name] = {"name": service_name, "state": state_val, "status": status_val, "source": "systemd"}
```

the service state on hosts is determined by the **`SUB`** parameter from the following command.

```bash
$ systemctl list-units --no-pager --type service --all --plain
```

Unfortunately, the **`SUB`** parameter, which is referenced as **`fields[3]`**, is later overridden by the **`state_val`** variable, which is set to **`stopped`** by default at the beginning.

As a result, this leads to the module always returning only two possible outcomes: **`stopped`** or **`running`**, rather than accurately reporting the true state of the services.

### Issue Type

Bug Report

### Component Name

lib/ansible/modules/service_facts.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.0 (main, Jan 24 2025, 20:49:13) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/local/bin/python3.11)
  jinja version = 3.1.5
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = False
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

* CentOS Linux 7
* CentOS Linux 8
* CentOS Stream 9
* Red Hat Enterprise Linux 7
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9

### Steps to Reproduce

This playbook captures the state of services both before and after kill the rsyslog service. 
After kill, the service enters a **`dead`** state, but the **`service_facts`** module reports it as **`stopped`**.

```yaml (paste below)
# systemd_test.yml
- name: Test systemd service_facts
  hosts: localhost
  gather_facts: no

  # Global Vars
  vars:
    servname: "rsyslog"

  tasks:

  - name: state of rsyslog now
    command: systemctl list-units --no-pager --type service --all --plain
    register: service_list_pre

  - name: set fact
    set_fact:
      rsyslog_state_pre: "{{ service_list_pre.stdout_lines | select('search', servname) | list | first | regex_replace('\\s+', ' ') | split(' ') }}"

  - name: print state from command
    debug:
      msg: "rsyslog is {{ rsyslog_state_pre[3]}}"

  - name: kill rsyslog
    command: killall rsyslogd

  - name: new state of rsyslog
    command: systemctl list-units --no-pager --type service --all --plain
    register: service_list_post

  - name: set fact
    set_fact:
      rsyslog_state_now: "{{ service_list_post.stdout_lines | select('search', servname) | list | first | regex_replace('\\s+', ' ') | split(' ') }}"

  - name: print new state from command
    debug:
      msg: "rsyslog is {{ rsyslog_state_now[3]}}"

  - name: populate service facts
    service_facts:

  - name: print state from service_facts
    debug:
      msg: "rsyslog is {{ ansible_facts['services'].values() | selectattr('name', 'equalto', servname + '.service') | map(attribute='state') }}"
```

Unfortunately, I cannot provide an output with the **`-vvv`** option as it exceeds 65536 characters.

### Expected Results

This module should report the true state of the services without overwriting it.

Accurately determining the state of a service is essential when using Ansible, particularly in enterprise environments.

Changing the existing state field might cause problems for all currently implemented playbooks/roles.

The best solution would be to add a new value, **`sub_state`**, that reflects the exact state from **`systemctl`**, but only when the source is **`systemd`**.

For example, like this:

```python
class SystemctlScanService(BaseService):

    BAD_STATES = frozenset(['not-found', 'masked', 'failed'])

    def systemd_enabled(self):
        return is_systemd_managed(self.module)

    def _list_from_units(self, systemctl_path, services):

        # list units as systemd sees them
        rc, stdout, stderr = self.module.run_command("%s list-units --no-pager --type service --all --plain" % systemctl_path, use_unsafe_shell=True)
        if rc != 0:
            self.module.warn("Could not list units from systemd: %s" % stderr)
        else:
            for line in [svc_line for svc_line in stdout.split('\n') if '.service' in svc_line]:

                state_val = "stopped"
                status_val = "unknown"
                fields = line.split()

                # systemd sometimes gives misleading status
                # check all fields for bad states
                for bad in self.BAD_STATES:
                    # except description
                    if bad in fields[:-1]:
                        status_val = bad
                        break
                else:
                    # active/inactive
                    status_val = fields[2]

                service_name = fields[0]
                sub_state_val = fields[3]
                if sub_state_val == "running":
                    state_val = "running"

                services[service_name] = {"name": service_name, "state": state_val, "sub_state": sub_state_val, "status": status_val, "source": "systemd"}
```

### Actual Results

```console
PLAY [Test systemd service_facts] ***********************************************************************************************************************************************

TASK [state of rsyslog now] *****************************************************************************************************************************************************
changed: [localhost]

TASK [set fact] *****************************************************************************************************************************************************************
ok: [localhost]

TASK [print state from command] *************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "rsyslog is running"
}

TASK [kill rsyslog] *************************************************************************************************************************************************************
changed: [localhost]

TASK [new state of rsyslog] *****************************************************************************************************************************************************
changed: [localhost]

TASK [set fact] *****************************************************************************************************************************************************************
ok: [localhost]

TASK [print new state from command] *********************************************************************************************************************************************
ok: [localhost] => {
    "msg": "rsyslog is dead"
}

TASK [populate service facts] ***************************************************************************************************************************************************
ok: [localhost]

TASK [print state from service_facts] *******************************************************************************************************************************************
ok: [localhost] => {
    "msg": "rsyslog is ['stopped']"
}

PLAY RECAP **********************************************************************************************************************************************************************
localhost                  : ok=9    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
