### ISSUE TITLE
Add an option for the `add_host` module to save the current hosts back to config

### ISSUE THREAD

**Issue by gregharvey** [ansible/ansible#84653]
### Summary

I am currently fighting with adding new hosts to Ansible's `hosts.yml` file with Ansible itself, use case being you have a new server and you want to have a playbook that can provision some basic config on that server *and* add it to your inventory file(s) so Ansible is aware of it.

It's doable (but a massive pain) to figure something out using jinja2 and templates and probably the `groups` variable, but it would be really cool if `add_host` had a `write_inventory` flag. If set to `true`, it would write the current in-memory hosts (i.e. including any added with `add_host`) back to the default inventory file(s) at the specified location in `ansible.cfg`. It would only make sense to support the `ini` and `yaml` plugins.  

Extra cool would be to have an additional option for `inventory_file` or something similar, so someone could point to a specific inventory file to update, again, must be either `.ini`, `.yml` or `.yaml`.

### Issue Type

Feature Idea

### Component Name

add_host

### Additional Information

```yaml
---
# Bare provisioning of a new server. To run on your controller.
# Use this command to execute:
#
#   ansible-playbook configure.yml -e "_provision_host=X.X.X.X"
#
# Replace X.X.X.X with your hostname or IP address.
- hosts: localhost
  tasks:
   # If ansible.cfg has inventory = /foo/bar then plugin will try to save to /foo/bar/hosts.(ini|yml|yaml)
    - name: Add a server to Ansible hosts in memory and on disk in the default location.
      ansible.builtin.add_host:
        hostname: "{{ _provision_host }}"
        write_inventory: true

   # Alternatively, allow full path to inventory file
    - name: Add a server to Ansible hosts in memory and on disk in a specified location.
      ansible.builtin.add_host:
        hostname: "{{ _provision_host }}"
        write_inventory: true
        inventory_file: /foo/bar/custom-inventory-file.yml

  # Do a bunch of other provisioning stuff...
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
