### ISSUE TITLE
`command`/`shell` should not set `skipped` in check mode

### ISSUE THREAD

**Issue by simonLeary42** [ansible/ansible#84674]
The fact that `command`/`shell` do this makes no sense to me. Every other module in ansible I've used in check mode sets `changed=True` in check mode even when it does nothing. Maybe this made sense at some point a long time ago before we had `creates`, `removes`, and `changed_when`. But with these three features there is useful information to be gained from a command that does nothing.

Example:
```yml
- name: a2enmod
  ansible.builtin.command:
    argv:
      - /sbin/a2enmod
      - -f
      - "{{ item }}"
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  loop: "{{ apache_mods_enabled  }}"
  notify: systemctl restart apache2
```

When I make changes to the list of modules to be enabled, and run this in check mode, everything says skipped, even though the `command` module already knows how to set `changed=True` when it sees that it creates a file that does not yet exist.
