### ISSUE TITLE
`command`/`shell` should not set `skipped` in check mode

### ISSUE THREAD

**Issue by simonLeary42** [ansible/ansible#84676]
### Summary

`command`/`shell` should not set `skipped` in check mode. Every other module I've used in check mode returns `ok` or `changed` in check mode even when it does nothing. In situations where skipped tasks are expected, it becomes impossible to tell in check mode which of your commands will actually be skipped.

Sorry for the noise, this is my 3rd issue because the 1st was created without a template, I realized the argument I was making in the 2nd was all wrong, and now I have a better argument and I'm not allowed to re-open an issue.

### Issue Type

Feature Idea

### Component Name

command, shell

### Additional Information

Example:
```yml
- name: command
  ansible.builtin.command: foobar
  when: "{{ item | foobar_filter }}"
  loop: "{{ foobar_list  }}"
```
If I make changes to `foobar_list` or `foobar_filter`, I cannot observe the results of those changes in check mode. All tasks are skipped in check mode.

same here:
```yml
- name: command
  ansible.builtin.command: foobar
  when: "{{ inventory_hostname | foobar_filter }}"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
