### ISSUE TITLE
Allow Action Plugins to disable omit stripping

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#84687]
### Summary

As noticed recently the task executor handles omit for action plugins. For most of them this is not an issue. However `ansible.builtin.debug` is also an action plugin and it becomes kinda confusing when it cannot distinguish between an undefined variable and one that is omitted (especially because `is defined` returns `true` for an omitted variable).

To **avoid** introducing a special case into the [task_executor](https://github.com/ansible/ansible/blob/cdb1ce000a7f26c8f4f5985df26da0c49edef790/lib/ansible/executor/task_executor.py#L651-L653) like this:
```
        if module_defaults_fqcn != "ansible.builtin.debug":
            # And filter out any fields which were set to default(omit), and got the omit token value
            omit_token = variables.get('omit')
            if omit_token is not None:
                self._task.args = remove_omit(self._task.args, omit_token)
```

I'd like to suggest adding a new action/module attribute that allows them to opt out of omit processing by the task executor. For the builtin modules this mainly affects `ansible.builtin.debug` and `ansible.builtin.failed`. However there could easily also be community ones that benefit from this.

### Issue Type

Feature Idea

### Component Name

task_executor

### Additional Information

```yaml
---
test_normal_file_content:
  key: value
test_omit_file_content: "{{ omit }}"
test_listEmpty_file_content: []
test_dictEmpty_file_content: {}
test_strEmpty_file_content: ""

---
- ansible.builtin.debug:
    msg: "{{ hostvars[inventory_hostname] | dict2items | selectattr('key', 'match', '^test_.*_file_content$') | list }}"
- name: Create files- name: Create sysctl dropin files
  loop: "{{ hostvars[inventory_hostname] | dict2items | selectattr('key', 'match', '^test_.*_file_content$') | list }}"
  when:
    - item.value
    - item.value != omit
    #- item.value is not none
    #- item.value != []
    #- item.value != omit
    #- item.value != {}
  ansible.builtin.debug:
    msg: "{{ item.key}}: {{ item.value|to_json }}"
---
ok: [localhost] => {
    "msg": [
        {
            "key": "test_normal_file_content",
            "value": {
                "key": "value"
            }
        },
        {
            "key": "test_omit_file_content"
        },
        ...
    ]
}
---
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
