### ISSUE TITLE
multiset filters (intersect, difference, symmetric_difference, union)

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#84688]
### Summary

It appears we currently only have intersect, difference, symmetric_difference, union for sets but not for multisets as all of these imply "unique".

Would it be possible to extend these filters for multisets?

This could be accomplished by
a) adding a multiset attribute like `intersect(list2, multiset=true)` or
b) by adding new multiset specific versions like `multi_intersect`, `multi_difference`, `multi_symmetric_difference`, and `multi_union`

I'm arguing for adding this to core because multisets are a fundamental concept of combinatorics, it is quite handy for list comprehension, and that's where the filters for sets currently are.

Edit: In addition the current [documentation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#selecting-from-sets-or-lists-set-theory) for union appears to be wrong, as it also enforces `unique` where as the documentation says it doesn't.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.intersect, ansible.builtin.difference, ansible.builtin.symmetric_difference, ansible.builtin.union

### Additional Information

Expected behavior for multisets:
* `[1, 2, 2, 2, 3, 4, 5 ] | intersect([1, 2, 3, 4, 2])` => `[1, 2, 2, 3, 4]`
* `[1, 2, 2, 2, 3, 4, 5 ] | difference([1, 2, 3, 4])` => `[2, 2, 5]`
* `[1, 2, 2, 2, 3, 4, 5 ] | difference([1, 2, 3, 4, 2])` => `[2, 5]`
* `[1, 2, 2, 2, 3, 4, 5 ] | symmetric_difference([1, 2, 3, 4, 2])` => `[2, 5]`
* `[1, 2, 2, 3, 4, 5 ] | symmetric_difference([1, 2, 3, 4, 2, 2])` => `[2, 5]`
* `[1, 2, 2, 2, 3, 4, 5 ] | union([1, 2, 6])` => `[1, 2, 2, 2, 3, 4, 5, 1, 2, 6 ]`

A more concrete example is when trying to check for conflicts. E.g. you've a group of 10 hosts and all of them are running redis and you've 5 public IPs. Now you need to ensure that each specific port does at most occur 5 times but both numbers can change (or are only known at runtime).
Therefore you'd my like to do:
```
fail_when: '{{ redisPortList | difference((public_IPs | count) * (redisPortList|unique|list)) | count }}'
ansible.builtin.debug:
  msg: "Cannot 1:1 map the following ports to public IPs: {{ redisPortList | difference((public_IPs | count) * (redisPortList|unique|list)) | list }}"
```
(If this is still a too simple example for you, consider wanting to derive the information of how many IPs you'll have to allocate from this while still keeping the playbook human-readable and without writing a custom filter)

Edit2: Or another example ensure a value is unique. This looks like it is working, but because of the implicit unique of difference it doesn't:
```
---
- name: Basic configuration
  hosts:
    - k8smaster
    - k8snode
  pre_tasks:
    - name: Ensure unique product_uuid
      failed_when: product_uuid | difference(product_uuid | unique) | count
      ansible.builtin.debug:
        msg: "Duplicate product uuid(s): {{ product_uuid | difference(product_uuid | unique) | unique| list }}"
      vars:
        product_uuid: "{{ hostvars | dict2items | selectattr('value.ansible_product_uuid', 'defined') | map(attribute='value.ansible_product_uuid') }}"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
