### ISSUE TITLE
delegate_to localhost listed as running on remote host in play recap

### ISSUE THREAD

**Issue by Spreadcat** [ansible/ansible#84794]
### Summary

When I run a task with Ansible on a remote host and a second task locally with `delegate_to`, the summary of all tasks shows both tasks ran at the remote host and none on the local host.
If I verify this, it shows that the location of where the tasks are supposed to run is correct, but the play recap is partly misleading.

The following playbook illustrates the issue

```yaml
---
# file: playbook.yml
- name: Test playbook
  hosts: all
  gather_facts: false
  tasks:

    - name: Run on the remote
      ansible.builtin.command:
        cmd: hostname
      register: _output_remote

    - name: Run locally
      ansible.builtin.command:
        cmd: hostname
      delegate_to: localhost
      register: _output_local

    - name: Output hostnames
      ansible.builtin.debug:
        msg: "Ran on {{ item }}"
      loop:
        - "{{ _output_remote['stdout'] }}"
        - "{{ _output_local['stdout'] }}"
```

If you run this playbook with `ansible-playbook, -i remote_host.example.com, playbook.yml` the output will show three tasks being executed:

1. `Run on the remote`
2. `Run locally`
3. `Output hostnames`

The output showing:

```

```

Task 2 and 3 are supposed to run locally. Task 2 runs locally, showing the local host name `local_host`. Task 3 runs locally, since all use of `ansible.builtin.debug` is automatically running locally.

### Issue Type

Bug Report

### Component Name

default_callback

### Ansible Version

```console
ansible --version
ansible [core 2.18.2]
  [...]
  python version = 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Fedora 40/41

### Steps to Reproduce

```yaml
---
# file: playbook.yml
- name: Test playbook
  hosts: all
  gather_facts: false
  tasks:

    - name: Run on the remote
      ansible.builtin.command:
        cmd: hostname
      register: _output_remote

    - name: Run locally
      ansible.builtin.command:
        cmd: hostname
      delegate_to: localhost
      register: _output_local

    - name: Output hostnames
      ansible.builtin.debug:
        msg: "Ran on {{ item }}"
      loop:
        - "{{ _output_remote['stdout'] }}"
        - "{{ _output_local['stdout'] }}"
```

### Expected Results

I was expecting to see `local_host.local.int` being added to the play recap. The output of task 2 indicates that the target host `remote_host.example.com` has been changed to `localhost`, but the recap at the bottom misses it completely.
There does not seem to be an attribution of locally delegated tasks to the local host within the recap. Other callback plugins with list by execution, time, etc seem to make this distinction, which then leads to contradicting information between the recap and the rest of the output.

### Actual Results

```console
[...]
TASK [Run on the remote] 
[...]
changed: [remote_.host.example.com]

TASK [Run locally] 
[...]
changed: [remote_host.example.com -> localhost]

TASK [Output hostnames] 
[....]
ok: [remote_host.example.com] => (item=remote_host) => {
    "msg": "Ran on remote_host"
}
ok: [remote_host.example.com] => (item=local_host) => {
    "msg": "Ran on local_host.local.int"
}

PLAY RECAP *******************************************************************************************************************
remote_host.example.com  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
....
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
