### ISSUE TITLE
uri module sends integers as strings in JSON body when using loop

### ISSUE THREAD

**Issue by phiratio** [ansible/ansible#84801]
### Summary

When using the uri module to send a JSON payload with an integer field **in the context of loop**, the integer is incorrectly converted to a string. This happens even when explicitly casting the value using | int in Jinja2.

### Issue Type

Bug Report

### Component Name

uri module

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.9]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less
```

### OS / Environment

Ubuntu 22.04.4 LTS

### Steps to Reproduce

1. Debug HTTP request with netcat `nc -l -p 8000`
2. Send HTTP request
```yaml (paste below)
---
- name: Execute a POST request
  uri:
    url: http://10.119.8.8:8000/
    method: POST
    body:
      id: "{{ item.id }}"
    body_format: json
    headers:
      Content-Type: application/json
    return_content: yes
  changed_when: false
  delegate_to: localhost
  loop:
    - { id: 72 }
```

### Expected Results

Payload id value is sent as integer:
{
  "id": 72
}

### Actual Results

```console
{
  "id": "72"
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/plugins/test/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/test/uri.py)
* [`lib/ansible/modules/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/uri.py)
* [`lib/ansible/plugins/action/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/uri.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by Akasurde** [comment]
@phiratio Thanks for reporting this. Unless you enable [native types](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-jinja2-native), the result of Jinja templating is always a string. 

You can do either of these things - 

1. Enable [native types](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-jinja2-native) for example - 

```console
$ ANSIBLE_JINJA2_NATIVE=true ansible-playbook int_post.yml -v
```
or

2. Pre-format the json body in the playbook itself -
 
```yaml
    - name: Execute a POST request
      uri:
        url: http://10.119.8.8:8000/
        method: POST
        # This change ->
        body: '{ "id" : {{ item.id }} }'
        body_format: json
        headers:
          Content-Type: application/json
        return_content: yes
      changed_when: false
      delegate_to: localhost
      loop:
        - { id: 72 }
```
