### ISSUE TITLE
`import_role` inside a block causes immediate evaluation of `environment`

### ISSUE THREAD

**Issue by flowerysong** [ansible/ansible#84813]
### Fallible Version

2025.3.11

### Summary

The following test playbook fails during parsing:
```yaml
- hosts: localhost
  tasks:
    - set_fact:
        foo: bar

    - environment:
        FOO: "{{ foo }}"
      block:
        - import_role:
            name: testrole
```

This worked fine under ansible-core 2.18, because by the time `environment` was relevant to execution `foo` was defined:
```text
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [testrole : command] ******************************************************
changed: [localhost]
```

While under fallible, it outputs:
```text
[ERROR]: Error processing keyword 'environment': 'foo' is undefined

Error processing keyword 'environment'.
Origin: <unknown>

[{'FOO': '{{ foo }}'}]

<<< caused by >>>

'foo' is undefined
Origin: /home/ezekielh/testing/test.yml:7:14

5
6     - environment:
7         FOO: "{{ foo }}"
               ^ column 14
```

This is possible to work around, but I don't see anything in the porting guide or changelog that suggests this is an expected change.

###
