### ISSUE TITLE
ansible.builtin.lineinfile and ansible.builtin.blockinfile charset support

### ISSUE THREAD

**Issue by roded** [ansible/ansible#84817]
### Summary

I'm trying to use `ansible.builtin.lineinfile` and `ansible.builtin.blockinfile` to make changes to a file which is not UTF-8.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.lineinfile
ansible.builtin.blockinfile

### Additional Information

Suggested usage (similar to `ansible.builtin.replace`):

```yaml (paste below)
- name: Set the license 
  ansible.builtin.lineinfile:
    path: "{{ conf_path }}/licenses.txt"
    line: "{{ license_key }}"
    insertafter: EOF
    encoding: cp037
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
