### ISSUE TITLE
[ec2_vpc_vpn] Doesn't allow TunnelInsideCidr without TunnelInsideIpv6Cidr but AWS returns InvalidParameterCombination

### ISSUE THREAD

**Issue by DandyDeveloper** [ansible/ansible#84828]
### Summary

Trying to create a VPN connection with 

```
  amazon.aws.ec2_vpc_vpn:
    state: present
    vpn_gateway_id: "{{ vgw.vgw.id }}"
    customer_gateway_id: "{{ cgw.gateway.customer_gateway.customer_gateway_id }}"
    static_only: true
    tunnel_options:
    - PreSharedKey: "{{ peer_passphrase }}"
      TunnelInsideCidr: "x.x.x.x/x"
      TunnelInsideIpv6Cidr: ""
    - PreSharedKey: "{{ peer_passphrase }}"
      TunnelInsideCidr: "x.x.x.x/x"
...
```

Results in: 

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Options.TunnelOptions[1].TunnelInsideIpv6Cidr, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

However, including the `TunnelInsideIpv6Cidr` to the tunnel options then gives the following error:

> : Failed to create vpn connection: An error occurred (InvalidParameterCombination) when calling the CreateVpnConnection operation: An ipv6 inside cidr is not allowed for VPNs using an ipv4 inside ip version

Which makes sense.

The module doesn't seem to agree with the AWS API expectations. 

### Issue Type

Bug Report

### Component Name

ec2_vpc_vpn

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.3]
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [GCC 11.4.0] (/home/linuxbrew/.linuxbrew/Cellar/ansible/11.3.0_1/libexec/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
N/A
```

### OS / Environment

```
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
```

### Steps to Reproduce

```yaml (paste below)
- name: Create a VPN connection
  amazon.aws.ec2_vpc_vpn:
    state: present
    vpn_gateway_id: "{{ vgw.vgw.id }}"
    customer_gateway_id: "{{ cgw.gateway.customer_gateway.customer_gateway_id }}"
    static_only: true
    tunnel_options:
    - PreSharedKey: "{{ peer_passphrase }}"
      TunnelInsideCidr: "x.x.x.x/x"
      TunnelInsideIpv6Cidr: ""
    - PreSharedKey: "{{ peer_passphrase }}"
      TunnelInsideCidr: "x.x.x.x/x"
      TunnelInsideIpv6Cidr: ""
    tags:
      Name: "{{ peer_name }}"
      ManagedBy: "Ansible"

```

### Expected Results

VPN to be created successfully. 

### Actual Results

```console
Errors described in original summary.
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
