### ISSUE TITLE
win_scheduled_task: The directory property cannot be found in the cache

### ISSUE THREAD

**Issue by drhirn** [ansible/ansible#84888]
### Summary

If using `password` or `logon_type: password` execution of the playbook always results in:

```
FAILED! => {"changed": false, "msg": "failed to modify scheduled task: The directory property cannot be found in the cache.\r\n"}
```

This is the same than #74742, but there has never been a reaction.

### Issue Type

Bug Report

### Component Name

win_scheduled_task

### Ansible Version

```console
$ ansible --version

ansible [core 2.16.3]
  config file = /home/.../.ansible.cfg
  configured module search path = ['/home/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/.../.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.8 (main, Dec  9 2024, 15:25:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = /home/.../.ansible.cfg
DEFAULT_HOST_LIST(/home/.../.ansible.cfg) = ['/data/ansible_windows/.../inventories']
DEFAULT_VAULT_PASSWORD_FILE(/home/.../.ansible.cfg) = /home/.../.ansible/vault
EDITOR(env: EDITOR) = nano
```

### OS / Environment

Red Hat Enterprise Linux 8.10

### Steps to Reproduce

Create a playbook using `password` and run it
```
---
- name: Add a scheduled task to remove old temporary files on converter servers
  gather_facts: no
  hosts: all
  tasks:
    - name: Create task
      community.windows.win_scheduled_task:
        name: Clean MSO Content
        description: Löscht Files aus dem Ordnern C:\Users\converteruser\AppData\Local\Microsoft\Windows\INetCache die älter als 30 Tage sind
        date: "2025-03-25T11:42:00"
        author: me
        actions:
          - path: C:\Windows\System32\cscript.exe
            arguments: '"C:\Program Files\CleanLogs\CleanLogs.vbs" "C:\Users\converteruser\AppData\Local\Microsoft\Windows\INetCache" 30'
        triggers:
          - type: daily
            start_boundary: '2025-03-25T01:00:00'
        username: user
        password: password
        run_level: limited
        logon_type: password
        compatibility: 4
        state: present
```

### Expected Results

Expected result would be a new task running under the given user

### Actual Results

```console
fatal: [host.example.com]: FAILED! => {
    "changed": true,
    "msg": "failed to modify scheduled task: The directory property cannot be found in the cache.\r\n"
}
```

The task is created, but only with the correct action. Everything else is missing (author, date, username, password, triggers, ...).

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
