### ISSUE TITLE
show example of async handlers or make it clear that they cannot be run async

### ISSUE THREAD

**Issue by dberardo-com** [ansible/ansible#84924]
### Summary

i am trying to restart a service in an handler that takes quite some time to restart. so i want to do it with async/poll: 0 . but the handler task is currently waiting on the service to restart, ignoring the poll = 0 option.

### Issue Type

Documentation Report

### Component Name

handler

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

linux

### Additional Information

.

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/playbook/handler.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/handler.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by s-hertel** [comment]
> i am trying to restart a service in an handler that takes quite some time to restart. so i want to do it with async/poll: 0 . but the handler task is currently waiting on the service to restart, ignoring the poll = 0 option.

It should work, but `poll: 0` would be ignored if `async` is `0` (the default) too.  If that's not the issue, can you share a reproducer of the issue and `ansible --version`?

Here's an example:

```yaml
- hosts: localhost
  gather_facts: no
  handlers:

  - name: Run handler
    command: sleep 9
    async: 10
    poll: 0
    register: handler_async_result

  tasks:
  - name: Cause handler to run
    command: /bin/true
    notify: Run handler

  - name: Flush handler before ending playbook
    meta: flush_handlers

  - name: Wait for slow handler to finish
    async_status:
      jid: "{{ handler_async_result.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 5
    delay: 2

  - name: Cleanup results file
    async_status:
      jid: "{{ handler_async_result.ansible_job_id }}"
      mode: cleanup
```

A handler is a type of task, so [task keywords](https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html#task) are available (with the exception of `tags`; [handler limitations are documented here](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html#limitations)).

Here's the documentation for `poll: 0` https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_async.html#run-tasks-concurrently-poll-0.

I can open a pull request against https://github.com/ansible/ansible-documentation to improve the documentation if you have suggestions.
