### ISSUE TITLE
Playbook for Windows failed when delegate_to localhost

### ISSUE THREAD

**Issue by svjatoslav-torn** [ansible/ansible#84928]
### Summary

Hi guys, I can call myself a beginner at Ansible. And I think I've run into a problem that I haven't been able to solve for 2 weeks now.

I will be very glad if you can tell me how to solve the issue, or maybe this is some kind of problem.

1. I have a fleet of Windows servers. I have prepared the servers for working with Ansible, installed OpenSSH, and checked the PowerShell version.
2. Ansible installed  on Ubuntu 2024
3. I've prepared an inventory with hosts, and it looks something like this:
```
---
all:
  vars:
    ansible_connection: ssh
    ansible_host_key_checking: false
    ansible_shell_type: cmd
  children:
    group1:
      hosts:
        137.184.1.179:
          ansible_ssh_user: Administrator
          ansible_ssh_password: password
```
That is, for all servers, I specified the SSH connection type and the CMD shell type.
Authorization occurs, as you have noticed, using SSHPass
3. And in general, everything works well until I want to perform any of the tasks within the playbook on the host machine with Ansible.

For example: I want to run a PowerShell script on all servers, save the results to files on a machine with Ansible, and then combine all these reports into one common report.

My playbook looks something like this:
```
---
- name: Get count query result frm FireBird DB
  hosts: all
  tasks:
    - name: Execute PowerShell script on remote servers
      win_shell: |
        ...
        Write-Output "PowerShell script result!"

      register: script_output

   - name: Save output to a local file on the control node
      copy:
        content: "{{ script_output.stdout }}"
        dest: "./results/{{ inventory_hostname }}_output.json"
      delegate_to: localhost

  - name: Collect all results into a single report
      assemble:
        src: ./results/
        dest: ./final_report.json
      delegate_to: localhost
      run_once: true
```

But as soon as it comes to the step of saving the content that was returned as a result of the script to a file on the local host, I get an error
```
TASK [Save output to a local file on the control node] *******************************************************************************************************************************************************************************************
fatal: [45.157.76.138 -> localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQ...fQA=, exited with result 127", "unreachable": true}
```

The most interesting thing, I think, in this conclusion is that the PowerShell command is trying to run on a Linux system. Although I use the copy module for linux.

I understand that a temporary directory is trying to be created somewhere under the hood and not specifically in my playbook, how do I get it to send the appropriate commands to the Linux server?

### Issue Type

Bug Report

### Component Name

copy

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.4]
  config file = None
  configured module search path = ['/home/ftp-dev/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/dist-packages/ansible
  ansible collection location = /home/ftp-dev/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None

GALAXY_SERVERS:
```

### OS / Environment

Ubuntu-2404-noble-amd64-base

### Steps to Reproduce

```yaml (paste below)
---
- name: Get count query result frm FireBird DB
  hosts: all
  vars:
    path_to_trade_db: path
    sql: "SELECT count(*) FROM accounts;"
  tasks:
    - name: Execute PowerShell script on remote servers
      win_shell: |
        ...
        Write-Output "PowerShell script result!"

      register: script_output

   - name: Save output to a local file on the control node
      copy:
        content: "{{ script_output.stdout }}"
        dest: "./results/{{ inventory_hostname }}_output.json"
      delegate_to: localhost

  - name: Collect all results into a single report
      assemble:
        src: ./results/
        dest: ./final_report.json
      delegate_to: localhost
      run_once: true
```

### Expected Results

A report file should appear on the ansible local host.

### Actual Results

```console
TASK [Save output to a local file on the control node] *******************************************************************************************************************************************************************************************
fatal: [45.157.76.138 -> localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQ...fQA=, exited with result 127", "unreachable": true}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
