### ISSUE TITLE
community.general.sudoers does not respect existing content

### ISSUE THREAD

**Issue by suhancz** [ansible/ansible#84929]
### Summary

When I apply `community.general.sudoers` twice after each other against the same file, the second one overrides the first one.

### Issue Type

Bug Report

### Component Name

sudoers

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.7]
  config file = *CENSORED*/ansible.cfg
  configured module search path = ['*CENSORED*/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = *CENSORED*/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jul 29 2024, 17:02:10) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_BECOME(*CENSORED*) = True
DEFAULT_BECOME_METHOD(*CENSORED*) = sudo
DEFAULT_BECOME_USER(*CENSORED*) = root
DEFAULT_HOST_LIST(*CENSORED*/ansible.cfg) = ['*CENSORED*/inventory.ini']
DEFAULT_PRIVATE_KEY_FILE(*CENSORED*/ansible.cfg) = *CENSORED*/.ssh/id_ed25519
DEFAULT_REMOTE_USER(*CENSORED*/ansible.cfg) = *CENSORED*
DEPRECATION_WARNINGS(*CENSORED*/ansible.cfg) = False
HOST_KEY_CHECKING(*CENSORED*/ansible.cfg) = False

BECOME:
======

runas:
_____
become_user(*CENSORED*/ansible.cfg) = root

su:
__
become_user(*CENSORED*/ansible.cfg) = root

sudo:
____
become_user(*CENSORED*/ansible.cfg) = root

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(*CENSORED*/ansible.cfg) = False
record_host_keys(*CENSORED*/ansible.cfg) = False
remote_user(*CENSORED*/ansible.cfg) = *CENSORED*
ssh_args(*CENSORED*/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

ssh:
___
host_key_checking(*CENSORED*/ansible.cfg) = False
private_key_file(*CENSORED*/ansible.cfg) = ~/.ssh/id_ed25519
remote_user(*CENSORED*/ansible.cfg) = *CENSORED*
ssh_args(*CENSORED*/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
```

### OS / Environment

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Steps to Reproduce

```yaml (paste below)
- name: Allow user to do stuff
  community.general.sudoers:
    name: "do_stuff"
    user: "user"
    state: present
    runas: root
    commands: "/do/stuff.sh"
- name: Allow group to do stuff
  community.general.sudoers:
    name: "do_stuff"
    group: "group"
    state: present
    runas: root
    commands: "/do/stuff.sh"
```

### Expected Results

`/etc/sudoers.d/do_stuff` should look like the following:

```sudoers
user ALL=(root)NOPASSWD: /do/stuff.sh
%group ALL=(root)NOPASSWD: /do/stuff.sh
```

### Actual Results

```sudoers
%group ALL=(root)NOPASSWD: /do/stuff.sh
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
