### ISSUE TITLE
lineinfile - changes birth time of file when updating

### ISSUE THREAD

**Issue by optica-phoffmann** [ansible/ansible#84967]
### Summary

I want to update the content of a text file. More precisely I want to add a new line to an existing file. A straightforward shell command would look like this `echo "my_new_line" >> /tmp/my_text_file.txt`. However, the use of shell module is discouraged and I thought I can get the same result when using `lineinfile` module like this: 
```      
ansible.builtin.lineinfile:
  dest: '/tmp/my_test_file.txt'
  line: my_new_line
  insertafter: EOF

```

The module updates the text file as expected. However, since I thought that I only do an update to an existing file the `lineinfile` would leave the timestamp of the birth time untouched. It turned out when examining the file via `stat` (shell command) the birth timestamp is changed each time a line is added via `lineinfile` module.

Behaviour tested with ansible-core 2.17.4 and 2.18.4

### Issue Type

Bug Report

### Component Name

lineinfile

### Ansible Version

```console
ansible [core 2.17.4]
python version = 3.11.9
jinja version = 3.1.4
libyaml = True
```

### Configuration

```console
not relevant
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

ansible-playbook  (add a `-v` to show shell stat output)
```yaml
- hosts: localhost
  tasks:
    - name: Touch file
      ansible.builtin.file:
        path: '/tmp/my_test_file.txt'
        state: 'touch'
        mode: '0755'
        access_time: preserve
        modification_time: preserve

    - name: add lineinfile
      ansible.builtin.lineinfile:
        dest: '/tmp/my_test_file.txt'
        line: "{{ lookup('community.general.random_string', length=12) }}"
        insertafter: EOF

    - name: stat 1
      ansible.builtin.shell: stat /tmp/my_test_file.txt | grep Birth

    - name: add lineinfile again
      ansible.builtin.lineinfile:
        dest: '/tmp/my_test_file.txt'
        line: "{{ lookup('community.general.random_string', length=12) }}"
        insertafter: EOF

    - name: stat 2
      ansible.builtin.shell: stat /tmp/my_test_file.txt | grep Birth


```

### Expected Results

From my perspective the `lineinfile` parameters clearly describe a change in an existing file. I expect the `lineinfile` module to either a) leave the birth date of the file untouched b) provide a parameter like `btime: preserve` , to provide an option for the desired behaviour to the user.

### Actual Results

```console
Extracted stat output to demonstrate the unexpected behaviour:
First stat: Birth: 2025-04-11 09:22:15.013843783 +0200
Second stat: Birth: 2025-04-11 09:22:15.492847656 +0200
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
