### ISSUE TITLE
vars not accessible in playbook when vars_files also exists

### ISSUE THREAD

**Issue by mgwilliams** [ansible/ansible#85]
- The playbook:

``` yaml

---
- hosts: all
  user: root

  vars:
    homedir: "/root/"

  vars_files:
  - "data.yaml"

  tasks:
  - action: file path="{{ homedir }}"  state=directory

```
- data.yaml:

``` yaml
a: b
```
- The error:

TASK: [file path="{{ homedir }}"  state=directory] *********
failed: [localhost] => file path= state=directory => {"failed": true, "msg": "", "parsed": false}
