### ISSUE TITLE
ec2_asg always returns as changed

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#8501]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.8 (devel 769a5738e3) last updated 2014/08/07 10:24:07 (GMT -700)
##### Environment:

N/A
##### Summary:

ec2_asg always reports changed = True.  I suspect it has to do with this block:

```
        as_group = as_groups[0]
        changed = False
        for attr in ASG_ATTRIBUTES:
            if module.params.get(attr) and getattr(as_group, attr) != module.params.get(attr):
                changed = True
                setattr(as_group, attr, module.params.get(attr))
```

It's comparing the module's inputs to the attributes of the autoscale object returned.  There is a mismatch on some attributes -- for example the module availability_zones -- the module supplied list of zones are not necessarily in the same order of the zones in the list returned from EC2.
##### Steps To Reproduce:

```
- name: create autoscale groups
  local_action:
    module: ec2_asg
    name: "{{ asg_group_name }}"
    health_check_period: 60
    load_balancers: "{{ load_balancers }}"
    health_check_type: ELB
    availability_zones: "{{ availability_zones | join(',')}}"
    launch_config_name: "{{ lc_name }}"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_desired_capacity }}"
    region: "{{ region }}"
    vpc_zone_identifier: "{{ asg_subnets | join(',') }}"
  tags: autoscale_group
```
##### Expected Results:

Nothing has changed, so task should not result in changed.
##### Actual Results:

```
TASK: [asg | create autoscale groups] *****************************************
<127.0.0.1> REMOTE_MODULE ec2_asg health_check_type=ELB launch_config_name=blue max_size=10 vpc_zone_identifier=subnet-3337f544,subnet-4ea8a466 desired_capacity=5 min_size=5 region=us-east-1 name=fancyapp-blue availability_zones=us-east-1b,us-east-1c
changed: [localhost -> 127.0.0.1] => {"availability_zones": ["us-east-1b", "us-east-1c"], "changed": true, "desired_capacity": 5, "health_check_period": 60, "health_check_type": "ELB", "instances": ["i-19b01d35", "i-1bb01d37", "i-1ab01d36", "i-0e7fbd24", "i-0d7fbd27"], "launch_config_name": "blue", "load_balancers": ["rollingAMI"], "max_size": 10, "min_size": 5, "vpc_zone_identifier": "subnet-3337f544,subnet-4ea8a466"}
```
