### ISSUE TITLE
Allow ansible_package_use to work with custom action plugins

### ISSUE THREAD

**Issue by millerthegorilla** [ansible/ansible#85021]
### Summary

I am trying to use an existing and mature ansible code base with an rpm-ostree system.   Due to the nature of the rpm-ostree package management system, when a package/s is installed, the system needs to be rebooted before path changes and configuration are available.

In `ansible.builtin.package` a variable (`ansible_package_use`) has been defined to allow the specification of a custom package manager.  This is already necessary to use, as the auto selected package manager for rpm-ostree systems is `atomic_container` which is both incorrect and deprecated.

But when I define the variable `ansible_package_use: community.general.rpm_ostree_pkg` the package installs, but the system doesn't reboot.  Immediately after installation configuration tasks then fail.

I discussed this with the package maintainers of rpm_ostree_pkg, ([here](https://github.com/ansible-collections/community.general/issues/10009#issuecomment-2818972747)) and it is perhaps possible to get the system to reboot following a package installation or removal, but this would require a rewrite of the module.   In the process of examining the issue, I learnt about action_plugins, which had been a mysterious part of ansible to me up until then.   I wrote a custom action plugin, but unfortunately, it wouldn't work with `ansible.builtin.package` as it uses `execute_module` during the code, and so cannot call custom action plugins.

In the following line, the `ansible_package_use` sets the module to use if it exists.   I wonder if a separate code path could be defined if a custom action plugin is detected, and instead of `execute_module`,  `action_loader` could be called.

https://github.com/ansible/ansible/blob/1daa8412d5a5ba8e1c2723127c4b5faf126b7036/lib/ansible/plugins/action/package.py#L56

I think that this would be consistent with the ansible mechanism of action_plugins, which can be defined to provide an alternative to modules.

An alternative would be to allow custom action plugins to work with fqdn.  I can call a module called `package` in my playbook, and my `action_plugins/package.py` action plugin is called.   But the code base I want to work with uses fqdn, and there is currently no way that I can find to place a custom action plugin in the `action_plugins` directory, and for it to get called when a fqdn is referenced in the playbook.

### Issue Type

Feature Idea

### Component Name

package

### Additional Information

```yaml (paste below)
- name: Test action plugin
  hosts: all
  become: true
  vars:
    ansible_package_use: "my_custom_action_plugin_name_here"
    ostree_reboot:    # custom action plugin vars
      always_reboot: True
      msg: "going down!"
      pre_reboot_delay: 10
  tasks:
    - name: Install_package
      ansible.builtin.package:
        name: nmap
        state: present
        reboot:
          always_reboot: true
      register: output
    - debug: var=output
```

custom action plugin:
https://gist.github.com/millerthegorilla/acedbc8c5a4eeea4beee9de42c0f29ea

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
