### ISSUE TITLE
Fetch module fails on remote host

### ISSUE THREAD

**Issue by leeclay95** [ansible/ansible#85033]
### Summary

I cannot understand why this error occurs and it seems to only happen with the fetch module of my playbook. The error is

`scp: /home/usrname/.ansible/tmp/ansible-tmp-1745270234.2538662-7527-117227521770514/AnsiballZ_async_status.py: Operation not permitted`
7527 1745270358.08502: stdout chunk (state=3):

7527 1745270358.08642: stderr chunk (state=3):

[WARNING]: scp transfer mechanism failed on [IP ADDR]. Use ANSIBLE_DEBUG=1 to see detailed information

The playbook execute fine on my local system however in the secure production test environment, I run into this issue.
The other modules fail as well with SFTP and piped.

Some of the playbook is here

```
- name: Identify reachable hosts
  hosts: all
  gather_facts: false
  remote_user: test1
  become: true
  strategy: linear

  tasks:
    - block:
        - name: Determine hosts that are reachable
          ansible.builtin.wait_for_connection:
            timeout: 5
        - name: Add devices with connectivity to the "reachable" group
          ansible.builtin.group_by:
            key: reachable
      rescue:
        - name: Debug unreachable host
          ansible.builtin.debug:
            msg: "Cannot connect to {{ inventory_hostname }}"



- name: Fetch archive from remote host
      fetch:
        src: "/tmp/{{ ansible_hostname | upper }}.zip"
        dest: "{{ outputpath }}/"
        flat: yes
#this is where the error occurs



```

### Issue Type

Bug Report

### Component Name

dnf

### Ansible Version

```console
$ ansible --version
2.16.3
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```
- name: Identify reachable hosts
  hosts: all
  gather_facts: false
  remote_user: test1
  become: true
  strategy: linear

  tasks:
    - block:
        - name: Determine hosts that are reachable
          ansible.builtin.wait_for_connection:
            timeout: 5
        - name: Add devices with connectivity to the "reachable" group
          ansible.builtin.group_by:
            key: reachable
      rescue:
        - name: Debug unreachable host
          ansible.builtin.debug:
            msg: "Cannot connect to {{ inventory_hostname }}"



- name: Fetch archive from remote host
      fetch:
        src: "/tmp/{{ ansible_hostname | upper }}.zip"
        dest: "{{ outputpath }}/"
        flat: yes
#this is where the error occurs

```

### Expected Results

Files should be removed from the remote host back to the ansible controller.

### Actual Results

```console
7527 1745270358.08403: stderr chunk (state=3):
>>>scp: /home/usrname/.ansible/tmp/ansible-tmp-1745270234.2538662-7527-117227521770514/AnsiballZ_async_status.py: Operation not permitted
<<<
  7527 1745270358.08502: stdout chunk (state=3):
>>><<<
  7527 1745270358.08642: stderr chunk (state=3):
>>><<<
[WARNING]: scp transfer mechanism failed on [IP ADDR]. Use ANSIBLE_DEBUG=1 to see detailed information
  7527 1745270358.08663:
  7527 1745270358.08665:
scp: /home/usrname/.ansible/tmp/ansible-tmp-1745270234.2538662-7527-117227521770514/AnsiballZ_async_status.py: Operation not permitted
<IP ADDR> ESTABLISH SSH CONNECTION FOR USER: usrname
<IP ADDR> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="usrname"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/f162a643f9"' IP ADDR 'dd of=/home/usrname/.ansible/tmp/ansible-tmp-1745270234.2538662-7527-117227521770514/AnsiballZ_async_status.py bs=65536'
  7527 1745270358.08806: Sending initial data
  7527 1745270358.44720: Sent initial data (125924 bytes)
  7527 1745270358.44747: stderr chunk (state=3):
\ndd: failed to open '/home/usrname/.ansible/tmp/ansible-tmp-1745270234.2538662-7527-117227521770514/AnsiballZ_async_status.py': Operation not permitted\n")
<IP ADDR> Failed to connect to the host via ssh:
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
