### ISSUE TITLE
async_status .started and .finished properties are ints, making them harder to be used in conditionals

### ISSUE THREAD

**Issue by evgeni** [ansible/ansible#85048]
### Summary

The current example of `async_status` reads:

```yaml
- name: Wait for asynchronous job to end
  ansible.builtin.async_status:
    jid: '{{ dnf_sleeper.ansible_job_id }}'
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10
```

However, `job_result.finished` is an integer, which leads to the following error in 2.19/devel:
```
Conditional result was '0' of type 'int', which evaluates to False. Conditionals must have a boolean result.
```

Either the example needs to use `| bool` explicitly, or `.finished` and `.started` need to become a Boolean (preferred).

### Issue Type

Bug Report

### Component Name

ansible.builtin.async_status

### Ansible Version

```console
$ ansible --version
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
ansible [core 2.19.0.dev0] (devel aab732cb82) last updated 2025/04/25 10:57:02 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/evgeni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/evgeni/Devel/ansible/ansible/lib/ansible
  ansible collection location = /home/evgeni/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/evgeni/Devel/ansible/ansible/bin/ansible
  python version = 3.13.3 (main, Apr  9 2025, 00:00:00) [GCC 15.0.1 20250410 (Red Hat 15.0.1-0)] (/usr/bin/python)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less

GALAXY_SERVERS:
```

### OS / Environment

Fedora 42

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  tasks:
    - name: Asynchronous task
      ansible.builtin.file:
        path: /tmp/test
        state: touch
      async: 1000
      poll: 0
      register: sleeper

    - name: Wait for asynchronous job to end
      ansible.builtin.async_status:
        jid: '{{ sleeper.ansible_job_id }}'
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 10
```

### Expected Results

It works :)

### Actual Results

```console
% ansible-playbook /tmp/lol.yml
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Asynchronous task] **************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Wait for asynchronous job to end] ***********************************************************************************************************************************************************************************************
[ERROR]: Task failed: Conditional result was '1' of type 'int', which evaluates to True. Conditionals must have a boolean result.

Task failed.
Origin: /tmp/lol.yml:12:7

10       register: sleeper
11
12     - name: Wait for asynchronous job to end
         ^ column 7

<<< caused by >>>

Conditional result was '1' of type 'int', which evaluates to True. Conditionals must have a boolean result.
Origin: /tmp/lol.yml:16:14

14         jid: '{{ sleeper.ansible_job_id }}'
15       register: job_result
16       until: job_result.finished
                ^ column 14

Broken conditionals can be temporarily allowed with the `ALLOW_BROKEN_CONDITIONALS` configuration option.

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Task failed: Conditional result was '1' of type 'int', which evaluates to True. Conditionals must have a boolean result."}

PLAY RECAP ****************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
