### ISSUE TITLE
hostname module: unusable in minimal Debian install

### ISSUE THREAD

**Issue by NightTsarina** [ansible/ansible#85069]
### Summary

Hi,

This has bothered me for years: in fresh Debian installs, I need to install dbus before I am able to do basic host set-up, such as setting the hostname.
Despite #56679 and many closed issues, I have not find a way to make this work:
* Passing `use: debian` changes nothing, as the module still insists on using systemd, despite there existing a separate `systemd` option
* With `use: generic` it just crashes, as the `BaseStragegy` raises `NotImplementedError`.
* Finally, `use: alpine` does not fail, but it is not able to change the "current" hostname because it does not implement `get_current_hostname`, and so the base class assumes it is already changed.

### Issue Type

Bug Report

### Component Name

hostname

### Ansible Version

```console
$ ansible --version
ansible [core 2.19.0.dev0]
  config file = None
  configured module search path = ['/home/tina/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/tina/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.2 (main, Mar 29 2025, 10:04:43) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None

GALAXY_SERVERS:
```

### OS / Environment

Controller: Debian Trixie (testing)
Target: Debian Bookworm (stable)

### Steps to Reproduce

Test playbook (`test.yaml`):

```yaml
- name: Test hostname module
  hosts: all
  tasks:
    - include_tasks: ./case.yaml
      loop:
        - DEFAULT
        - debian
        - generic
        - alpine
```

Test case (`case.yaml`):

```yaml
- name: '[use={{ item }}] Test case'
  block:
    - name: '[use={{ item }}] Set hostname'
      ansible.builtin.hostname:
        name: test-{{ item }}
        use: '{{ omit if item == "DEFAULT" else item }}'

    - name: '[use={{ item }}] Get current hostname'
      ansible.builtin.command:
        cmd: hostname
      register: current_hostname
      changed_when: false

    - name: '[use={{ item }}] Get permanent hostname'
      ansible.builtin.slurp:
        src: /etc/hostname
      register: permanent_hostname

    - name: '[use={{ item }}] Assert current hostname'
      ansible.builtin.assert:
        that: expected == actual
        msg: '{{ expected }} != {{ actual }}'
      vars:
        expected: test-{{ item }}
        actual: '{{ current_hostname.stdout }}'
      ignore_errors: true

    - name: '[use={{ item }}] Assert permanent hostname'
      ansible.builtin.assert:
        that: expected == actual
        msg: '{{ expected }} != {{ actual }}'
      vars:
        expected: test-{{ item }}
        actual: '{{ permanent_hostname.content | b64decode | trim }}'
      ignore_errors: true
  rescue:
    - ansible.builtin.meta: noop
```

Command line:
```
ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook --diff  --become --ask-become-pass ./test.yaml --inventory=mytest.srv,
```

### Expected Results

All tests not using the default strategy should have worked.

### Actual Results

```console
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.

PLAY [Test hostname module] ****************************************************

TASK [Gathering Facts] *********************************************************
[WARNING]: Host mytest.srv is using the discovered Python interpreter at
/usr/bin/python3.11, but future installation of another Python interpreter
could change the meaning of that path. See https://docs.ansible.com/ansible-
core/devel/reference_appendices/interpreter_discovery.html for more
information.
ok: [mytest.srv]

TASK [include_tasks] ***********************************************************
included: $HOME/poc/case.yaml for mytest.srv => (item=DEFAULT)
included: $HOME/poc/case.yaml for mytest.srv => (item=debian)
included: $HOME/poc/case.yaml for mytest.srv => (item=generic)
included: $HOME/poc/case.yaml for mytest.srv => (item=alpine)

TASK [[use=DEFAULT] Set hostname] **********************************************
fatal: [mytest.srv]: FAILED! => {
    "changed": false
}

MSG:

Command failed rc=1, out=, err=Failed to connect to bus: Connection refused


TASK [ansible.builtin.meta] ****************************************************

TASK [[use=debian] Set hostname] ***********************************************
fatal: [mytest.srv]: FAILED! => {
    "changed": false
}

MSG:

Command failed rc=1, out=, err=Failed to connect to bus: Connection refused


TASK [ansible.builtin.meta] ****************************************************

TASK [[use=generic] Set hostname] **********************************************
fatal: [mytest.srv]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDOUT:


Traceback (most recent call last):
  File "$HOME/.ansible/tmp/ansible-tmp-1745963703.031139-4056686-274730726925749/AnsiballZ_hostname.py", line 107, in <module>
    _ansiballz_main()
  File "$HOME/.ansible/tmp/ansible-tmp-1745963703.031139-4056686-274730726925749/AnsiballZ_hostname.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "$HOME/.ansible/tmp/ansible-tmp-1745963703.031139-4056686-274730726925749/AnsiballZ_hostname.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.hostname', init_globals=dict(_module_fqn='ansible.modules.hostname', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_ansible.builtin.hostname_payload_pinbxnhw/ansible_ansible.builtin.hostname_payload.zip/ansible/modules/hostname.py", line 908, in <module>
  File "/tmp/ansible_ansible.builtin.hostname_payload_pinbxnhw/ansible_ansible.builtin.hostname_payload.zip/ansible/modules/hostname.py", line 882, in main
  File "/tmp/ansible_ansible.builtin.hostname_payload_pinbxnhw/ansible_ansible.builtin.hostname_payload.zip/ansible/modules/hostname.py", line 640, in get_current_hostname
  File "/tmp/ansible_ansible.builtin.hostname_payload_pinbxnhw/ansible_ansible.builtin.hostname_payload.zip/ansible/modules/hostname.py", line 129, in get_current_hostname
  File "/tmp/ansible_ansible.builtin.hostname_payload_pinbxnhw/ansible_ansible.builtin.hostname_payload.zip/ansible/modules/hostname.py", line 135, in get_permanent_hostname
NotImplementedError



MODULE_STDERR:

Shared connection to mytest.srv closed.


TASK [ansible.builtin.meta] ****************************************************

TASK [[use=alpine] Set hostname] ***********************************************
--- before
+++ after
@@ -1 +1 @@
-hostname = mytest
+hostname = test-alpine

changed: [mytest.srv]

TASK [[use=alpine] Get current hostname] ***************************************
ok: [mytest.srv]

TASK [[use=alpine] Get permanent hostname] *************************************
ok: [mytest.srv]

TASK [[use=alpine] Assert current hostname] ************************************
fatal: [mytest.srv]: FAILED! => {
    "assertion": "expected == actual",
    "changed": false,
    "evaluated_to": false
}

MSG:

test-alpine != mytest
...ignoring

TASK [[use=alpine] Assert permanent hostname] **********************************
ok: [mytest.srv] => {
    "changed": false
}

MSG:

All assertions passed

PLAY RECAP *********************************************************************
mytest.srv           : ok=10   changed=1    unreachable=0    failed=0    skipped=0    rescued=3    ignored=1
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
