### ISSUE TITLE
Hashicorp Vault lookup in group_vars

### ISSUE THREAD

**Issue by paspflue** [ansible/ansible#85064]
### Summary

Because the lookups are re-evaluated in each task, the hashi_vault lookup in the group_vars cannot be used usefully. See #9623

This means that ansible cannot handle per host credentials (ansible_user, ansible_password, ...) in a meaningful way. You could certainly build a workaround here with set_fact. However, existing playbooks must be adapted and checked for side effects if individual hosts use other mechanisms.

Can't the groups_vars and host_vars be rebuilt so that all variables are resolved once at playbook start?

### Issue Type

Feature Idea

### Component Name

hashi_vault

### Additional Information

group_vars/vault_managed_host
```yaml
vault_cred: "{{ lookup('community.hashi_vault.hashi_vault', 'url=' + vault_address + ' secret=my_secret_path') }}"
ansible_user: "{{ vault_cred['user'] }}"
ansible_password: "{{ vault_cred['password']}}"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
