### ISSUE TITLE
ansible.builtin.script and become on Windows (Regression)

### ISSUE THREAD

**Issue by aidanleuck** [ansible/ansible#85076]
### Summary

Recently, we upgraded our docker image from ansible 2.16.2 to ansible 2.17.10. Upon upgrading one of our playbooks started failing unexpectedly.

We often use Ansible for doing Windows automation. One of our main use cases for Ansible is that it allows us to perform privilege escalation on Windows using the become syntax. We use `ansible.builtin.script` in order to run PowerShell scripts with escalated privileges allowing us to call functions that would normally fail due to the WinRM double hop issue. 

I am aware that Ansible has playbooks for mounting network drives, but for our use case we need to use PowerShell since this module is an abstraction that allows users to execute custom scripts after provisioning.

### Issue Type

Bug Report

### Component Name

become, ansible.builtin.script

### Ansible Version

```console
ansible [core 2.17.10]
  config file = None
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/vscode/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = None
```

### OS / Environment

Ubuntu 22.04 (executor)
Windows 11 23H2 (Remote)

### Steps to Reproduce

playbook.yaml
```
# Playbook for executing custom scripts after provisioning of a machine.
# This is useful if the machine goes through sysprep and needs some extra configuration
# In order to function.
- name: Running Playbook to execute custom scripts
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for WinRM to become available
      wait_for_connection:
        timeout: 600
    # Gets full name of the user account (domain + user)
    # If you don't specify the full name then become escalation can fail since it tries
    # to use a local account when logged into a domain account.
    - name: Get information about the current user
      win_whoami:
      register: user_info

    #Print a message about the current script that is running
    - name: Block
      block:
        - name: "whoami"
          win_whoami:
        - name: "Run Custom scripts" 
          ansible.builtin.script:
            # Use user input to dynamically run an arbitrary script on the VM
            cmd: "test.ps1"
            executable: "powershell"
      vars:
        ansible_become_user: "{{ user_info.account.domain_name }}\\{{ user_info.account.account_name }}"
        ansible_become_password: "{{ ansible_password }}"
        ansible_become_method: runas
        ansible_become: true
        ansible_become_flags: logon_type=interactive
```
inventory.yaml
```
all:
  hosts:
    <ip_addresses_here>
  vars:
    ansible_user: <redacted>
    ansible_password: <redacted>
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_winrm_read_timeout_sec: 1500
```

This is the script that started failing after upgrading. It calls `New-PSDrive` to mount a Samba network drive. This command is the one that is failing.
test.ps1
```
$ErrorActionPreference = "Stop"
$exitCode = 0
try {
    Start-Transcript -Path "$env:SYSTEMDRIVE\log.txt" -Force
    # Map K Drive
    New-PSDrive -Name "K" -Root "<unc-path>" -PSProvider "FileSystem" -Scope "Global" -Persist
    Stop-Process -Name Explorer -Force
}
catch {
    Write-Error $_
    $exitCode = -1
}
finally {
    Exit $exitCode
}
```

We are using the first `whoami` block to get the fully qualified user account name with the domain name + computer name appended. The second whoami block is there to for debugging purposes to see what type of login was obtained.

Below is the win_whoami output in the block directive. This correctly shows that when using `ansible_become` vars that we are now logged in interactively. See the `logon_type: interactive` json value. This appears to show that we are logged in interactively and should be able to use the user account to mount the `New-PSDrive` without passing user credentials to the script. (Note I have redacted some output and only left relevant data)
```
ok: [10.202.27.249] => {
    "account": {
        "type": "User"
    },
    "authentication_package": "Kerberos",
    "changed": false,
        {
            "account_name": "High Mandatory Level",
            "attributes": [
                "Integrity",
                "Integrity enabled"
            ],
            "domain_name": "Mandatory Label",
            "type": "Label"
        }
    ],
    "impersonation_level": "SecurityAnonymous",
    "invocation": {
        "module_args": {}
    },
    "label": {
        "account_name": "High Mandatory Level",
        "domain_name": "Mandatory Label",
        "type": "Label"
    },
    "login_time": "2025-04-30T18:26:47.6851058+00:00",
    "logon_id": 77884902,
    "logon_type": "Interactive",
    "privileges": {
        "SeBackupPrivilege": "disabled",
        "SeChangeNotifyPrivilege": "enabled-by-default",
        "SeCreateGlobalPrivilege": "enabled-by-default",
        "SeCreatePagefilePrivilege": "disabled",
        "SeCreateSymbolicLinkPrivilege": "disabled",
        "SeDebugPrivilege": "enabled",
        "SeDelegateSessionUserImpersonatePrivilege": "disabled",
        "SeImpersonatePrivilege": "enabled-by-default",
        "SeIncreaseBasePriorityPrivilege": "disabled",
        "SeIncreaseQuotaPrivilege": "disabled",
        "SeIncreaseWorkingSetPrivilege": "disabled",
        "SeLoadDriverPrivilege": "disabled",
        "SeManageVolumePrivilege": "disabled",
        "SeProfileSingleProcessPrivilege": "disabled",
        "SeRemoteShutdownPrivilege": "disabled",
        "SeRestorePrivilege": "disabled",
        "SeSecurityPrivilege": "disabled",
        "SeShutdownPrivilege": "disabled",
        "SeSystemEnvironmentPrivilege": "disabled",
        "SeSystemProfilePrivilege": "disabled",
        "SeSystemtimePrivilege": "disabled",
        "SeTakeOwnershipPrivilege": "disabled",
        "SeTimeZonePrivilege": "disabled",
        "SeUndockPrivilege": "disabled"
    },
    "rights": [
        "SeNetworkLogonRight",
        "SeInteractiveLogonRight",
        "SeBatchLogonRight",
        "SeRemoteInteractiveLogonRight"
    ],
    "token_type": "TokenPrimary",
    "user_flags": []
}
```

In order to execute the playbook, create these three files in the same directory on your system with the content above. `playbook.yaml` `test.ps1` and `inventory.yaml`. You will also need a Windows machine to execute the playbook against WinRM must be enabled with NTLM authentication

Run the playbook on 2.16.2 (succeeds)
Run the playbook on 2.17.10 (fails)
Run the playbook with `ansible-playbook -i inventory.yaml test.yaml -vvv` 

### Expected Results

The mount to succeed as it did in 2.16.2

### Actual Results
When running on Ansible 2.17.10 I get the following error message. This would seem to indicate `ansible.builtin.script` is not running in an interactive session.

```console
"changed": true,
    "rc": 0,
    "stderr": "New-PSDrive : The specified network password is not correct\r\nAt line:1 char:1\r\n+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (New-PSDrive : T... is not correct:String) [], RemoteException\r\n    + FullyQualifiedErrorId : NativeCommandError\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1\r\n\r\nAt C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746037609.1457684-3527-20928345987456\\test.ps1:11 char:5\r\nAt line:1 char:1\r\n+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (At C:\\Users\\svc...t.ps1:11 char:5:String) [], RemoteException\r\n    + FullyQualifiedErrorId : NativeCommandErrorMessage\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1\r\n\r\n+     New-PSDrive -Name \"K\" -Root \"<redacted>" -PSProvider \"FileSys ...\r\nAt line:1 char:1\r\n+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (+     New-PSDri...er \"FileSys ...:String) [], RemoteException\r\n    + FullyQualifiedErrorId : NativeCommandErrorMessage\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1\r\n\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nAt line:1 char:1\r\n+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (+     ~~~~~~~~~...~~~~~~~~~~~~~~~:String) [], RemoteException\r\n    + FullyQualifiedErrorId : NativeCommandErrorMessage\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1\r\n\r\n    + CategoryInfo          : InvalidOperation: (K:PSDriveInfo) [New-PSDrive], Win32Exception\r\nAt line:1 char:1\r\n+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (    + CategoryI... Win32Exception:String) [], RemoteException\r\n    + FullyQualifiedErrorId : NativeCommandErrorMessage\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1\r\n\r\n    + FullyQualifiedErrorId : CouldNotMapNetworkDrive,Microsoft.PowerShell.Commands.NewPSDriveCommand\r\nAt line:1 char:1\r\n+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (    + FullyQual...wPSDriveCommand:String) [], RemoteException\r\n    + FullyQualifiedErrorId : NativeCommandErrorMessage\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1\r\n\r\n \r\nAt line:1 char:1\r\n+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: ( :String) [], RemoteException\r\n    + FullyQualifiedErrorId : NativeCommandErrorMessage\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1\r\n\r\n",
    "stderr_lines": [
        "New-PSDrive : The specified network password is not correct",
        "At line:1 char:1",
        "+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...",
        "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "    + CategoryInfo          : NotSpecified: (New-PSDrive : T... is not correct:String) [], RemoteException",
        "    + FullyQualifiedErrorId : NativeCommandError",
        "",
        "ScriptStackTrace:",
        "at <ScriptBlock>, <No file>: line 1",
        "",
        "At C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746037609.1457684-3527-20928345987456\\test.ps1:11 char:5",
        "At line:1 char:1",
        "+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...",
        "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "    + CategoryInfo          : NotSpecified: (At C:\\Users\\svc...t.ps1:11 char:5:String) [], RemoteException",
        "    + FullyQualifiedErrorId : NativeCommandErrorMessage",
        "",
        "ScriptStackTrace:",
        "at <ScriptBlock>, <No file>: line 1",
        "",
        "+     New-PSDrive -Name \"K\" -Root \"<redacted>" -PSProvider \"FileSys ...",
        "At line:1 char:1",
        "+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...",
        "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "    + CategoryInfo          : NotSpecified: (+     New-PSDri...er \"FileSys ...:String) [], RemoteException",
        "    + FullyQualifiedErrorId : NativeCommandErrorMessage",
        "",
        "ScriptStackTrace:",
        "at <ScriptBlock>, <No file>: line 1",
        "",
        "+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "At line:1 char:1",
        "+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...",
        "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "    + CategoryInfo          : NotSpecified: (+     ~~~~~~~~~...~~~~~~~~~~~~~~~:String) [], RemoteException",
        "    + FullyQualifiedErrorId : NativeCommandErrorMessage",
        "",
        "ScriptStackTrace:",
        "at <ScriptBlock>, <No file>: line 1",
        "",
        "    + CategoryInfo          : InvalidOperation: (K:PSDriveInfo) [New-PSDrive], Win32Exception",
        "At line:1 char:1",
        "+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...",
        "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "    + CategoryInfo          : NotSpecified: (    + CategoryI... Win32Exception:String) [], RemoteException",
        "    + FullyQualifiedErrorId : NativeCommandErrorMessage",
        "",
        "ScriptStackTrace:",
        "at <ScriptBlock>, <No file>: line 1",
        "",
        "    + FullyQualifiedErrorId : CouldNotMapNetworkDrive,Microsoft.PowerShell.Commands.NewPSDriveCommand",
        "At line:1 char:1",
        "+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...",
        "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "    + CategoryInfo          : NotSpecified: (    + FullyQual...wPSDriveCommand:String) [], RemoteException",
        "    + FullyQualifiedErrorId : NativeCommandErrorMessage",
        "",
        "ScriptStackTrace:",
        "at <ScriptBlock>, <No file>: line 1",
        "",
        " ",
        "At line:1 char:1",
        "+ &  powershell C:\\Users\\<user>\\AppData\\Local\\Temp\\ansible-tmp-1746 ...",
        "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "    + CategoryInfo          : NotSpecified: ( :String) [], RemoteException",
        "    + FullyQualifiedErrorId : NativeCommandErrorMessage",
        "",
        "ScriptStackTrace:",
        "at <ScriptBlock>, <No file>: line 1",
        ""
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
