### ISSUE TITLE
config values returned by get_option() may lose tags

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#85085]
### Ansible Version

```console
devel
```

### Summary

If you have an option `foo` with `type=list` and `elements=str` for an inventory plugin and use the elements of `self.get_option('foo')`, these are sometimes trusted and sometimes not, depending on whether a YAML list was used or a string (that's split by commas).

I think a list of strings returned by `self.get_option()` that's loaded from a YAML file should always be trusted, no matter whether it was a YAML list or a string.

The same happens if `type=str` and the value provided in the YAML file is an integer or boolean. The resulting string will not be trusted.

This is problematic if the value(s) is/are used in templating (like as an expression or conditional). Before Data Tagging, these values would have been evaluated.

(This appeared in the Foreman collection with `type=list`/`elements=str`.)

###

**Comment by ansibot** [comment]
Files identified in the description:

* [`bin/ansible`](https://github.com/ansible/ansible/blob/devel/bin/ansible)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by evgeni** [comment]
We have the following snippet in the doc section of the [inventory](https://github.com/theforeman/foreman-ansible-modules/blob/effd9a3c0d2b7d6bcc7e4324c942526903f7b4a2/plugins/inventory/foreman.py#L168-L174):
```
      hostnames:
        description:
          - A list of templates in order of precedence to compose inventory_hostname.
          - If the template results in an empty string or None value it is ignored.
        type: list
        elements: str
        default: ['name']
```

Which I'd assume is already a list, but… I still get errors
