### ISSUE TITLE
Defined test fails for variables containing nested undefined variables, causing incorrect undefined evaluation

### ISSUE THREAD

**Issue by kreativmonkey** [ansible/ansible#85097]
### Summary

When checking if a variable containing nested undefined variables is defined, Ansible incorrectly reports the parent variable as undefined. This occurs even when the parent structure (e.g., a list of dictionaries) is explicitly defined.

### Issue Type

Bug Report

### Component Name

is defined

### Ansible Version

```console
Reproduced with version: 2.14.2, 2.14.14, 2.18.5
```

### Configuration

No special configuration and the bug is not related to any configuration. 

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Reproduced on: RHEL 8, RHEL 9, archlinux

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost  
  vars:  
    list_of_dicts:  
      - name: Valid entry  
        status: present  
      - name: "{{ some_missing_var }}"  # Undefined variable here  
        status: absent  

  tasks:  
    - name: Check if list_of_dicts is defined  
      debug:  
        msg: "list_of_dicts is {{ 'defined' if list_of_dicts is defined else 'undefined' }}"  
      # Output: "list_of_dicts is undefined" (incorrect)  

   - name: Output text if list_of_dicts is defined
     debug:
        msg: "I can see list_of_dicts"
     when: list_of_dicts is defined

    - name: Output list_of_dicts  
      debug:  
        var: list_of_dicts  
      # Fails with "some_missing_var is undefined" (expected error timing)  
```

### Expected Results

`list_of_dicts is defined` should return `true` if the variable exists, even if nested variables within its structure are undefined. Errors related to undefined nested variables should only surface when the specific nested value is accessed.

### Actual Results

```console
The existence check (is defined) fails entirely if any nested variable in the structure is undefined, incorrectly claiming the parent variable is undefined.


PLAY [localhost] *****************************************************************

TASK [Gathering Facts] ***********************************************************
ok: [localhost]

TASK [Check if list_of_dicts are defined] ****************************************
ok: [localhost] => {
    "msg": "list_of_dicts are undefined"
}

TASK [Print text if list_of_dicts is defined] ************************************
skipping: [localhost]

TASK [Output list_of_dicts] ******************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable.. [{'name': 'You can see me', 'status': 'present'}, {'name': '{{ some_missing_var }}', 'status': 'absent'}]: 'some_missing_var' is undefined\n\nThe error appears to be in '/home/sebastian/git/github.com/archsetup-ansible/test_definition_check.yml': line 19, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Output list_of_dicts\n      ^ here\n"}

PLAY RECAP ***********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
