### ISSUE TITLE
ansible.builtin.pipe behaves differently between ansible and ansible-playbook with relative paths

### ISSUE THREAD

**Issue by Everspace** [ansible/ansible#85105]
### Summary

When I use pipe to load in a password from a shell command for `ansible_password`, it works for `ansible -m win_ping myGroup` but not for `ansible-playbook playbookWinPing.yml`

### Issue Type

Bug Report

### Component Name

ansible.builtin.pipe

### Ansible Version

```console
ansible [core 2.18.2]
  config file = /Users/ahaaf/git/foundation-ansible/ansible.cfg
  configured module search path = ['/Users/ahaaf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ahaaf/.local/share/virtualenvs/foundation-ansible-M0gstIXb/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/ahaaf/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/ahaaf/.local/share/virtualenvs/foundation-ansible-M0gstIXb/bin/ansible
  python version = 3.12.9 (main, Feb  4 2025, 14:38:38) [Clang 16.0.0 (clang-1600.0.26.6)] (/Users/ahaaf/.local/share/virtualenvs/foundation-ansible-M0gstIXb/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Configuration

```console
CACHE_PLUGIN(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = ansible.builtin.jsonfile
CACHE_PLUGIN_CONNECTION(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = ./_temp/ansible_facts_cache
CACHE_PLUGIN_TIMEOUT(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = 86400
CONFIG_FILE() = /Users/ahaaf/git/foundation-ansible/ansible.cfg
DEFAULT_HOST_LIST(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = ['/etc/ansible/hosts', '/Users/ahaaf/git/foundation-ansible/inventory.aws_ec2.yml']
DEFAULT_ROLES_PATH(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = ['/Users/ahaaf/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', '/Users/ahaaf/git/foundation-ansible/role>
DEFAULT_STDOUT_CALLBACK(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = default
DEFAULT_VAULT_PASSWORD_FILE(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = /Users/ahaaf/git/foundation-ansible/.secret

GALAXY_SERVERS:


CACHE:
=====
jsonfile:
________
_timeout(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = 86400
_uri(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = /Users/ahaaf/git/foundation-ansible/_temp/ansible_facts_cache

CALLBACK:
========

default:
_______
result_format(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = yaml

minimal:
_______
result_format(/Users/ahaaf/git/foundation-ansible/ansible.cfg) = yaml
```

### OS / Environment

SSH'd into a Mac OSX machine.

### Steps to Reproduce

I'm using the following to login to a windows machine for a fresh EC2 instance:

```yaml
# group_vars/ec2_windows.yml
ansible_ssh_private_key_file: ./keys/shared-services.pem
aws_profile: shared-services
ansible_connection: psrp
ansible_pipelining: true
ansible_psrp_protocol: http
ansible_become_user: "{{ ansible_user }}"
ansible_become_method: ansible.builtin.runas
ansible_become_flags: logon_type=interactive logon_flags=with_profile

ansible_user: Administrator
ansible_become_password: "{{ ansible_password }}"
aws_password_invocation: >-
  aws ec2 get-password-data
  --profile {{ aws_profile }}
  --output text
  --priv-launch-key {{ ansible_ssh_private_key_file }}
  --instance-id {{ ansible_ec2_instance_id }}
  --query PasswordData

ansible_password: '{{ lookup("ansible.builtin.pipe", aws_password_invocation) }}'
```

This is using the aws cli to aquire the default password in plaintext for ansible to use for my dynamic inventory.

When I perform `ansible -i inventory.aws_ec2.yml -m win_ping 'ec2_windows,&ci_azure'` I get the following:

```
[WARNING]: Found variable using reserved name: tags
azure-windows-0 | SUCCESS => 
    changed: false
    ping: pong
```

When I use the following playbook
```yaml
- name: Setup initial system
  hosts: ec2_windows,&ci_azure
  become: true
  roles:
    - example_role
```
I get the following error:
```
PLAY [Setup initial system] ***************************
[WARNING]: Found variable using reserved name: tags

TASK [Gathering Facts] **************

priv-launch-key should be a path to the local SSH private key file used to launch the instance.
fatal: [azure-windows-0]: FAILED! => 
    msg: 'An unhandled exception occurred while running the lookup plugin ''ansible.builtin.pipe''.
        Error was a <class ''ansible.errors.AnsibleError''>, original message: lookup_plugin.pipe(aws
        ec2 get-password-data --profile shared-services --output text --priv-launch-key
        ./keys/shared-services.pem --instance-id i-0ca7b697608db34b5 --query PasswordData)
        returned 255. lookup_plugin.pipe(aws ec2 get-password-data --profile shared-services
        --output text --priv-launch-key ./keys/shared-services.pem --instance-id i-0ca7b697608db34b5
        --query PasswordData) returned 255'

PLAY RECAP  **************

azure-windows-0            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

The invocation of `aws ec2 get-password-data --profile shared-services --output text --priv-launch-key ./keys/shared-services.pem --instance-id i-0ca7b697608db34b5 --query PasswordData` Works fine on the commandline, and the problem persists even when I am not being "cute" with formatting the command with `>-` and perform it all on one line. 

It does work when I provide an absolute path for `ansible_ssh_private_key_file`

### Expected Results

I'm able to use `ansible.builtin.pipe` in ansible-playbook contexts with a relative path.

### Actual Results

```console
PLAY [Setup initial system] **********************************************************************************************************************************************************************
[WARNING]: Found variable using reserved name: tags

TASK [Gathering Facts] ***************************************************************************************************************************************************************************

priv-launch-key should be a path to the local SSH private key file used to launch the instance.
fatal: [azure-windows-0]: FAILED! => 
    msg: 'An unhandled exception occurred while running the lookup plugin ''ansible.builtin.pipe''.
        Error was a <class ''ansible.errors.AnsibleError''>, original message: lookup_plugin.pipe(aws
        ec2 get-password-data --profile shared-services --output text --priv-launch-key
        "./keys/shared-services.pem" --instance-id i-0ca7b697608db34b5 --query PasswordData)
        returned 255. lookup_plugin.pipe(aws ec2 get-password-data --profile shared-services
        --output text --priv-launch-key "./keys/shared-services.pem" --instance-id i-0ca7b697608db34b5
        --query PasswordData) returned 255'

PLAY RECAP ***************************************************************************************************************************************************************************************
azure-windows-0            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
