### ISSUE TITLE
ERROR! A worker was found in a dead state

### ISSUE THREAD

**Issue by m1hk3l** [ansible/ansible#85123]
### Summary

Mac user error or "non-ansible Ansible" error. 
When I tried to run my ansible book which fetched some secrets from hashicorp vault I managed to get this error:

> ERROR! A worker was found in a dead state

Solution >
The issue stems from using python compiled with pyenv because said binaries are not signed with a trusted "Apple Developer ID".
Deinstall all python versions installed with pyenv, destroy pyenv, clean .zshrc of any pyenv related variables.
Install python 3.xx with brew because Homebrew team uses a certificate issued by Apple to sign software.

specs: 
* macOS 15
* ansible core 2.18.4
* community.hashi_vault   6.2.0  
* tested with python 3.11, 3.12, 3.13

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.4]
```

### OS / Environment

ProductName:		macOS
ProductVersion:		15.3.2
arm64

### Steps to Reproduce

```yaml (paste below)
cat playbooks/ping.yml 
- name: Pinging all hosts
  hosts: cms
  gather_facts: false
  tasks:
    - name: Ping host
      ansible.builtin.ping:
    - name: Das message
      ansible.builtin.debug:
        msg: "Das variable: {{ db_user }}"

```

### Expected Results

I assumed to get the value of a variable after a successful ping

### Actual Results

```console
Ping was successful but after that playbook got shut down immediately  
and ERROR! A worker was found in a dead state was displayed.

Finally resolved the issue.  
I found several reports of this exact same error but not one helped resolve my issue.  
So I though this is important to report to help some other McTastic user.
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
