### ISSUE TITLE
Ansible skips role argument validation if `tasks_from` includes a file extension

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#85125]
### Summary

We are taking advantage of Ansible [role argument validation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation). If we have `roles/testrole/meta/argument_specs.yaml` like this:

```
argument_specs:
  main:
    options:
      testrole_var_1:
        type: str
        required: true

  tasklist1:
    options:
      testrole_var_2:
        type: int
        required: true
```

And then we call the role like this:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: testrole
        tasks_from: tasklist1.yaml
```

Ansible will skip the validation. This was a surprise! Validation works correctly if we call it like this:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: testrole
        tasks_from: tasklist1
```

But it seems like Ansible should apply argument validation in both cases. The documentation for `include_role` says that `tasks_from` is:

> File to load from a role’s tasks/ directory.

It doesn't specify that this should only be the *basename* of the file, and it doesn't throw any warnings or errors when one uses the file extension.

If we modify `arguments_specs.yaml` so that it includes the file extension:

```
argument_specs:
  tasklist1.yaml:
    options:
      testrole_var_2:
        type: int
        required: true
```

Then it works only if we have `tasks_from: tasklist1.yaml`, but does not apply if we have `tasks_from: tasklist1`.

### Issue Type

Bug Report

### Component Name

role argument validation

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.5]
  config file = None
  configured module search path = ['/home/lars/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lars/.local/share/pipx/venvs/ansible/lib64/python3.13/site-packages/ansible
  ansible collection location = /home/lars/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lars/.local/bin/ansible
  python version = 3.13.3 (main, Apr 22 2025, 00:00:00) [GCC 15.0.1 20250418 (Red Hat 15.0.1-0)] (/home/lars/.local/share/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim

GALAXY_SERVERS:
```

### OS / Environment

Fedora 42

### Steps to Reproduce

(see above)

### Expected Results

I expected Ansible to apply argument validation regardless of whether or not `tasks_from` includes the file extension.

### Actual Results

```console
(see above)
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
