### ISSUE TITLE
zos_unarchive for pax file - runs too long and fails

### ISSUE THREAD

**Issue by gomathibose01** [ansible/ansible#85208]
### Summary

with the following as reference - https://github.com/IBM/z-ansible-workshops/blob/main/ibm_z_collections/setup_zoau.yml ; I am trying to setup zoau ; I obtained the latest pax file from IBM download mainframe dev  and placed it directly onto USS ; (transferred via binary mode to uss).
and I am trying to user zos_unarchive but the playbook never ends and keeps executing too long on that particular task.  after unarchiving few files, the time out error occurs.

### Issue Type

Bug Report

### Component Name

zos_unarchive

### Ansible Version

```console
ansible [core 2.18.0]
  config file = None
  configured module search path = ['/home/popup/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/popup/.local/lib/python3.13/site-packages/ansible
  ansible collection location = /home/popup/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/popup/.local/bin/ansible
  python version = 3.13.3 (main, Apr  9 2025, 08:55:03) [GCC 13.3.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = False
```

### Configuration

```console
CONFIG_FILE() = None

GALAXY_SERVERS:
```

### OS / Environment

RHEL 9 

### Steps to Reproduce

```
---
- name: Install Z Open Automation Utilities pax version
  hosts: all
  vars_files:
    - group_vars/all.yaml
  vars:
    pax_src_dir_uss: "/u/ibmuser/paxinstalls"
    package_name: "zoau-1.3.5.0.pax.Z"
    remote_facts_dir: "/u/ibmuser/ansible/facts/"
  gather_facts: False
  fact_path: "{{ remote_facts_dir }}"
  environment:
    - "{{environment_vars}}"

  tasks:
    - name: Extract pax file on target
      ibm.ibm_zos_core.zos_unarchive:
        src: "{{ pax_src_dir_uss }}/{{ package_name }}"
        remote_src: true
        format:
          name: pax
      register: extract_output

    - ansible.builtin.debug:
       var: extract_output
```

### Expected Results

unpax of the file to happen successfully

### Actual Results

```console
Timeout error happens after running for too long ; runs for more than 20mins on the zos_unarchive step; 
On looking into the folder , could see few files are been extracted but it is not complete.
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
