### ISSUE TITLE
any_errors_fatal does not stop playbook if failure happens in block with always section

### ISSUE THREAD

**Issue by gdraelan** [ansible/ansible#85200]
### Summary

When a play has `any_errors_fatal: yes` and a failure happens inside a block that has an `always` section then the playbook is not aborted.

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.5]
  config file = /opt/ansible/ansible.cfg
  configured module search path = ['/opt/ansible/modules']
  ansible python module location = /opt/app-root/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/gdraelan/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/app-root/bin/ansible
  python version = 3.11.5 (main, Sep 22 2023, 15:34:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/opt/app-root/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CACHE_PLUGIN(/opt/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/opt/ansible/ansible.cfg) = /tmp/ansible_fact_cache_data
CACHE_PLUGIN_TIMEOUT(/opt/ansible/ansible.cfg) = 86400
CALLBACKS_ENABLED(/opt/ansible/ansible.cfg) = ['ansible.posix.profile_tasks', 'ansible.posix.timer']
CONFIG_FILE() = /opt/ansible/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/opt/ansible/ansible.cfg) = ['/opt/ansible/action_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/opt/ansible/ansible.cfg) = ['/opt/ansible/filter_plugins']
DEFAULT_FORKS(/opt/ansible/ansible.cfg) = 48
DEFAULT_GATHERING(/opt/ansible/ansible.cfg) = smart
DEFAULT_LOG_PATH(/opt/ansible/ansible.cfg) = /var/opt/ansible/log/ansible.log
DEFAULT_MODULE_PATH(/opt/ansible/ansible.cfg) = ['/opt/ansible/modules']
DEFAULT_MODULE_UTILS_PATH(/opt/ansible/ansible.cfg) = ['/opt/ansible/pythonlib']
DEFAULT_PRIVATE_KEY_FILE(/opt/ansible/ansible.cfg) = /home/gdraelan/.ssh/id_rsa
DEFAULT_REMOTE_USER(/opt/ansible/ansible.cfg) = gdraelan
DEFAULT_ROLES_PATH(/opt/ansible/ansible.cfg) = ['/opt/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/opt/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/opt/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(/opt/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/opt/ansible/ansible.cfg) = /var/tmp

CACHE:
=====

jsonfile:
________
_timeout(/opt/ansible/ansible.cfg) = 86400
_uri(/opt/ansible/ansible.cfg) = /tmp/ansible_fact_cache_data

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(env: ANSIBLE_HOST_KEY_CHECKING) = False
private_key_file(/opt/ansible/ansible.cfg) = ~/.ssh/id_rsa
remote_user(/opt/ansible/ansible.cfg) = gdraelan
ssh_args(/opt/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600s -o ForwardX11=no
timeout(/opt/ansible/ansible.cfg) = 30

ssh:
___
host_key_checking(env: ANSIBLE_HOST_KEY_CHECKING) = False
pipelining(/opt/ansible/ansible.cfg) = True
private_key_file(/opt/ansible/ansible.cfg) = ~/.ssh/id_rsa
remote_user(/opt/ansible/ansible.cfg) = gdraelan
ssh_args(/opt/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600s -o ForwardX11=no
timeout(/opt/ansible/ansible.cfg) = 30
```

### OS / Environment

RHEL 8.9

### Steps to Reproduce

Inventory
```yaml (paste below)
all:
  vars:
    error_count: 0
    active_location: false
  children:
    database:
      hosts:
        db.host.01:
        db.host.02:
        db.host.11:
        db.host.12:
    backend:
      hosts:
        be.host.01:
          error_count: 1
        be.host.02:
        be.host.11:
        be.host.12:
    location1:
      hosts:
        db.host.01:
        db.host.02:
        be.host.01:
        be.host.02:
      vars:
        active_location: true
    location2:
      hosts:
        db.host.11:
        db.host.12:
        be.host.11:
        be.host.12:
```

Playbook
```yaml

- name: Play1
  hosts: database
  gather_facts: no
  tasks:
    - ansible.builtin.debug:
        msg: "play1"

- name: Play2
  hosts: backend
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - ansible.builtin.meta: end_host
      when: not (active_location | bool)

    - block:
        - ansible.builtin.debug:
            msg: "play2"

        - ansible.builtin.assert:
            that:
              - error_count <= 0
      always:
        - ansible.builtin.debug:
            msg: "play2 - always"

- name: Play3
  hosts: backend
  gather_facts: no
  tasks:
    - ansible.builtin.debug:
        msg: "play3"

- name: Play4
  hosts: database
  gather_facts: no
  tasks:
    - ansible.builtin.debug:
        msg: "play4"
```

### Expected Results

Plays 3-4 should not be executed because of the failure in the play 2, i.e. I expect it to behave like the following playbook (minus the `always` section)

```yaml
- name: Play1
  hosts: database
  gather_facts: no
  tasks:
    - ansible.builtin.debug:
        msg: "play1"

- name: Play2
  hosts: backend
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - ansible.builtin.meta: end_host
      when: not (active_location | bool)

    - ansible.builtin.debug:
        msg: "play2"

    - ansible.builtin.assert:
        that:
          - error_count <= 0

- name: Play3
  hosts: backend
  gather_facts: no
  tasks:
    - ansible.builtin.debug:
        msg: "play3"

- name: Play4
  hosts: database
  gather_facts: no
  tasks:
    - ansible.builtin.debug:
        msg: "play4"

```

```
PLAY [Play1] **************************************************************************************************************************************************************************************************************************************************************************************************

TASK [ansible.builtin.debug] **********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:09:41 +0000 (0:00:00.022)       0:00:00.022 **********
ok: [db.host.01] =>
  msg: play1
ok: [db.host.02] =>
  msg: play1
ok: [db.host.11] =>
  msg: play1
ok: [db.host.12] =>
  msg: play1

PLAY [Play2] **************************************************************************************************************************************************************************************************************************************************************************************************

TASK [ansible.builtin.meta] ***********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:09:41 +0000 (0:00:00.048)       0:00:00.071 **********
skipping: [be.host.01]

TASK [ansible.builtin.meta] ***********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:09:41 +0000 (0:00:00.019)       0:00:00.091 **********
skipping: [be.host.02]

TASK [ansible.builtin.meta] ***********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:09:41 +0000 (0:00:00.002)       0:00:00.094 **********

TASK [ansible.builtin.meta] ***********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:09:41 +0000 (0:00:00.002)       0:00:00.096 **********

TASK [ansible.builtin.debug] **********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:09:41 +0000 (0:00:00.002)       0:00:00.098 **********
ok: [be.host.01] =>
  msg: play2
ok: [be.host.02] =>
  msg: play2

TASK [ansible.builtin.assert] *********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:09:41 +0000 (0:00:00.026)       0:00:00.125 **********
fatal: [be.host.01]: FAILED! => changed=false
  assertion: error_count <= 0
  evaluated_to: false
  msg: Assertion failed
ok: [be.host.02] => changed=false
  msg: All assertions passed

NO MORE HOSTS LEFT ********************************************************************************************************************************************************************************************************************************************************************************************

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************************************************
be.host.01                 : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
be.host.02                 : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
db.host.01                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
db.host.02                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
db.host.11                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
db.host.12                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

### Actual Results

```console
PLAY [Play1] **************************************************************************************************************************************************************************************************************************************************************************************************

TASK [ansible.builtin.debug] **********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.024)       0:00:00.024 **********
ok: [db.host.02] =>
  msg: play1
ok: [db.host.01] =>
  msg: play1
ok: [db.host.11] =>
  msg: play1
ok: [db.host.12] =>
  msg: play1

PLAY [Play2] **************************************************************************************************************************************************************************************************************************************************************************************************

TASK [ansible.builtin.meta] ***********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.050)       0:00:00.075 **********
skipping: [be.host.01]

TASK [ansible.builtin.meta] ***********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.020)       0:00:00.095 **********
skipping: [be.host.02]

TASK [ansible.builtin.meta] ***********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.002)       0:00:00.098 **********

TASK [ansible.builtin.meta] ***********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.002)       0:00:00.100 **********

TASK [ansible.builtin.debug] **********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.002)       0:00:00.102 **********
ok: [be.host.01] =>
  msg: play2
ok: [be.host.02] =>
  msg: play2

TASK [ansible.builtin.assert] *********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.023)       0:00:00.126 **********
fatal: [be.host.01]: FAILED! => changed=false
  assertion: error_count <= 0
  evaluated_to: false
  msg: Assertion failed
ok: [be.host.02] => changed=false
  msg: All assertions passed

TASK [ansible.builtin.debug] **********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.023)       0:00:00.149 **********
ok: [be.host.01] =>
  msg: play2 - always
ok: [be.host.02] =>
  msg: play2 - always

PLAY [Play3] **************************************************************************************************************************************************************************************************************************************************************************************************

TASK [ansible.builtin.debug] **********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.030)       0:00:00.179 **********
ok: [be.host.02] =>
  msg: play3
ok: [be.host.11] =>
  msg: play3
ok: [be.host.12] =>
  msg: play3

PLAY [Play4] **************************************************************************************************************************************************************************************************************************************************************************************************

TASK [ansible.builtin.debug] **********************************************************************************************************************************************************************************************************************************************************************************
Thursday 22 May 2025  13:17:30 +0000 (0:00:00.050)       0:00:00.230 **********
ok: [db.host.01] =>
  msg: play4
ok: [db.host.02] =>
  msg: play4
ok: [db.host.11] =>
  msg: play4
ok: [db.host.12] =>
  msg: play4

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************************************************
be.host.01                 : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
be.host.02                 : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
be.host.11                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
be.host.12                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
db.host.01                 : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
db.host.02                 : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
db.host.11                 : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
db.host.12                 : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
