### ISSUE TITLE
deb822_repository: embed Signed-By ASCII Armor key in .sources file when fetched from URL

### ISSUE THREAD

**Issue by igorakkerman** [ansible/ansible#85246]
### Summary

As far as I could see in the code, we have the option to either
- specify an ASCII Armor key in `signed_by` and it will be embedded in `Signed-By` in the `.sources` file
- or specify an URL to a key and it will be fetched and saved as a file in `keyrings`.

But we cannot specify an URL to a key and have it be fetched and embedded.

Please add an option or means to specify that the key should be fetched and embedded, if it is ASCII armored.

My current solution is to run `ansible.builtin.uri` and use its output as `signed_by` value for `deb822_repository`.

### Issue Type

Feature Idea

### Component Name

deb822_repository

### Additional Information

```yaml
- name: Add Docker apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    suites: '{{ ansible_distribution_release }}'
    components: stable
    signed_by: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    # NEW OPTION to specify location of the GPG key
    signed_by_target: embed # or 'file'/'keyring' by default
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by kirkzhangtech** [comment]
may i know if below output meets the requirement ?
```
Components: stable
X-Repolib-Name: docker
Signed-By: /etc/apt/keyrings/docker.asc
Signed-By-Target:
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    .
    mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
    lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
    38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
    L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
    UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
    cmhh4HgeQscQH...............................................................................................................
    .........................................
    =0YYh
    -----END PGP PUBLIC KEY BLOCK-----
Suites: noble
Types: deb
URIs: https://download.docker.com/linux/ubuntu
```

**Comment by kirkzhangtech** [comment]
@igorakkerman  i  saw your yesterday email . and read deeply  and recognize your email . 
your solution to add docker key  as below playbook.
```yml
  tasks:
    - name: Download Docker apt public signing key in OpenPGP armor format
      ansible.builtin.uri:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        return_content: true
      register: apt_key_armor_response

    - name: Add Docker apt repository
      become: true
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
        suites: '{{ ansible_distribution_release }}'
        components: stable
        signed_by: '{{ apt_key_armor_response.content }}'
```


but i found that if you run below playbook also meets your requirement. playbook can also download public key file.
```yml
- hosts: localhost
  become: true
  tasks:
    - name: Debug system information
      debug:
        msg:
          - "Ansible Distribution: {{ ansible_distribution }}"
          - "Ansible Distribution Release: {{ ansible_distribution_release }}"
    
    - name: Add Docker apt repository
      become: true
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
        suites: '{{ ansible_distribution_release }}'
        components: stable
        signed_by: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        
```

the important point here, if you run my playbook that i provide , the armor key will not store into `.source` file . so question here , if we need to enhance this feature  so that ansible could store key where is from url  into `.source` file.

if my understand correct or not . please let me know .
