### ISSUE TITLE
The profile report is missing tasks when callbacks_enabled = profile_tasks in ansible.cfg

### ISSUE THREAD

**Issue by tedheadster** [ansible/ansible#85240]
### Summary

When running a playbook and seeing the final profile report, it was missing many tasks that should have been listed with the "callbacks_enabled = profile_tasks" option.

### Issue Type

Bug Report

### Component Name

ansible.cfg option callbacks_enabled = profile_tasks

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.18]
  config file = /root/ansible-install-gentoo/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CALLBACKS_ENABLED(/root/ansible-install-gentoo/ansible.cfg) = ['profile_tasks']
CONFIG_FILE() = /root/ansible-install-gentoo/ansible.cfg
DEFAULT_HOST_LIST(/root/ansible-install-gentoo/ansible.cfg) = ['/root/ansible-install-gentoo/inventory']
```

### OS / Environment

Linux raspberrypi 6.6.51+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

### Steps to Reproduce

```yaml (paste below)

Unsure how to reproduce this yet.

This code snippet got different results in a larger playbook, but running it in a small playbook does not seem to reproduce it. The "Get disk size in GiB" was in the profile report, but the "Get RAM size in MiB" was NOT.

    - name: "Get RAM size in MiB"
      ansible.builtin.set_fact:
        ram_mb: "{{ ansible_facts['memtotal_mb'] }}"

    - name: "Get disk size in GiB"
      ansible.builtin.set_fact:
        disk_size_gb: "{{ (ansible_facts['devices'][ MAIN_DISK | basename ]['sectors'] | int * 512 / (1024*1024*1024)) | int }}"

Here MAIN_DISK is "/dev/sda".


```

### Expected Results

I expected all the tasks to appear in the profile report.

### Actual Results

```console
Here is a "diff -uNr" of what should have been in the profile report versus what did appear.

-Calculate swap size
-Create EFI partition
-Create GPT partition table
 Create Root partition
-Create swap partition
 Detect all mounted partitions on /dev/sda
 Disable swap on /dev/sda2
 Download latest stage3 file list
 Download the latest stage3 tarball
 Enable swap on /dev/sda2
-Ensure /mnt/gentoo exists
-Ensure /mnt/gentoo/boot exists
-Ensure /mnt/gentoo/boot/efi exists
-Ensure /mnt/gentoo/dev exists
-Ensure /mnt/gentoo/proc exists
-Ensure /mnt/gentoo/run exists
-Ensure /mnt/gentoo/sys exists
 Extract stage3 tarball
 Extract tarfile stage3_filename
-Format EFI partition (vfat)
-Format root partition (ext4)
-Format swap partition (swap)
 Gather facts in hosting system
-Get RAM size in MiB
 Get disk size in GiB
-Mount /mnt/gentoo
-Mount /mnt/gentoo/boot
-Mount /mnt/gentoo/dev rbind
-Mount /mnt/gentoo/dev rslave
 Mount /mnt/gentoo/proc
-Mount /mnt/gentoo/run
-Mount /mnt/gentoo/sys rbind
-Mount /mnt/gentoo/sys rslave
 Print important configuration variables
-Print memory and disk size
 Print tarfile stage3_filename
-Set EFI partition boot flag
 Try to download file:///root/.ssh/authorized_keys
 Try to download http://mirrors.rit.edu/gentoo/releases/arm64/autobuilds/current-stage3-arm64-systemd
 Unmount /mnt/gentoo/dev
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
