### ISSUE TITLE
Data Tagging: `Failed to serialize arguments` when passing a dict with int keys to a module that accepts `raw`

### ISSUE THREAD

**Issue by evgeni** [ansible/ansible#85250]
### Ansible Version

```console
ansible [core 2.19.0.dev0]
  config file = /home/evgeni/Devel/theforeman/foreman-ansible-modules/ansible.cfg
  configured module search path = ['/home/evgeni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/evgeni/Devel/theforeman/foreman-ansible-modules/venv/lib64/python3.13/site-packages/ansible
  ansible collection location = /home/evgeni/Devel/theforeman/foreman-ansible-modules/build/collections
  executable location = /home/evgeni/Devel/theforeman/foreman-ansible-modules/venv/bin/ansible
  python version = 3.13.3 (main, Apr 22 2025, 00:00:00) [GCC 15.0.1 20250418 (Red Hat 15.0.1-0)] (/home/evgeni/Devel/theforeman/foreman-ansible-modules/venv/bin/python)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
```

(this is a git install of df0b417f2db6a51a7f74a6bc1bfa8e8f24676899)

### Summary

We have modules that accept input as `raw`, like `ansible.builtin.uri`, to pass that input along to some (unrelated) third party.

With the merge of the Data Tagging feature, those modules fail if you pass them a `dict` with an `int` key with the following error:
```
Failed to serialize arguments for the 'ansible.legacy.uri' module: Key of type '_AnsibleTaggedInt' is not JSON serializable by the 'module_legacy_c2m' profile.
```

In https://github.com/ansible/ansible-documentation/blob/devel/docs/docsite/rst/porting_guides/porting_guide_core_2.19.rst#no-implicit-conversion-of-non-string-dict-keys it is documented that the module should handle the conversion to strings, but the argument serialization happens outside of the module and I don't think any code inside the module can influence it?

Example playbook:
```yaml
---
- hosts: localhost
  tasks:
    - name: uri
      ansible.builtin.uri:
        url: https://httpbin.org/post
        method: POST
        body:
          1: whoa
        body_format: json
        return_content: true
      register: result
    - name: debug
      ansible.builtin.debug:
        var: result
```

In this particular case, it can be re-written as
```yaml
---
- hosts: localhost
  tasks:
    - name: uri
      ansible.builtin.uri:
        url: https://httpbin.org/post
        method: POST
        body: '{1: "whoa"}'
        body_format: json
        return_content: true
      register: result
    - name: debug
      ansible.builtin.debug:
        var: result
```
But that doesn't seem like a generic solution. Neither is changing the `1` to an `"1"`, as that would change the submitted data.

PS: Why does the error say `ansible.legacy.uri` -- I called `ansible.builtin.uri` in the playbook.

###
