### ISSUE TITLE
Download GPG Keys result in: The handshake operation timed out

### ISSUE THREAD

**Issue by ReptoxX** [ansible/ansible#85311]
### Summary

When trying to install a "new" gpg key to a server it mostly failes with the "The handshake operation timed out" error.

### Issue Type

Bug Report

### Component Name

get_url

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.6]
  config file = None
  configured module search path = ['/Users/terzibaschian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/11.6.0/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/terzibaschian/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.4 (main, Jun  3 2025, 15:34:24) [Clang 17.0.0 (clang-1700.0.13.3)] (/opt/homebrew/Cellar/ansible/11.6.0/libexec/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = None

GALAXY_SERVERS:
```

### OS / Environment

OS Version (Ansible Caller): Mac OS Sequoia 15.5
OS Version (Host): Debian Bookworm
Python Version (Ansible Caller): 3.13.4
Python Version (Host): 3.11.2
OpenSSL Version: OpenSSL 3.0.16 11 Feb 2025

### Steps to Reproduce

```yaml (paste below)
 - name: Add Promtail Repo
   block:
     - name: install apt-key
       ansible.builtin.get_url:
         url: https://apt.grafana.com/gpg.key
         dest: /etc/apt/keyrings/grafana.asc
         mode: 0644
         timeout: 60
         use_proxy: false
         validate_certs: false

     - name: add grafana repo
       ansible.builtin.apt_repository:
         repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
         filename: grafana
         state: present
```

### Expected Results

The Signing Key should download and be present on the server.

### Actual Results

```console
{"changed": false, "dest": "/etc/apt/keyrings/grafana.asc", "elapsed": 11, "gid": 0, "group": "root", "mode": "0644", "msg": "Request failed: <urlopen error _ssl.c:975: The handshake operation timed out>", "owner": "root", "size": 2288, "state": "file", "uid": 0, "url": "https://apt.grafana.com/gpg.key"}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
