### ISSUE TITLE
My SSH keeps getting bricked by Ansible after a playbook fails

### ISSUE THREAD

**Issue by elibroftw** [ansible/ansible#85339]
### Summary

After I run a playbook with an error, I can no longer ssh into my server. Sometimes a restart isn't good enough. I have to straight up restore the server from a backup. I don't know what the hell is going on.

After restoring from backup, i also get:

[WARNING]: sftp transfer mechanism failed on [142.93.152.9]. Use ANSIBLE_DEBUG=1 to see detailed information
[WARNING]: scp transfer mechanism failed on [142.93.152.9]. Use ANSIBLE_DEBUG=1 to see detailed information

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.6]
  config file = None
  configured module search path = ['/home/maste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/maste/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/maste/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/maste/.local/bin/ansible
  python version = 3.12.9 (main, Feb  4 2025, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-5)] (/usr/bin/python3.12)
  jinja version = 3.1.6
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

AlmaLinux 9

### Steps to Reproduce

```yaml (paste below)
- name: Deploy website
  hosts: elijahlopez_ca_1
  tasks:
  - name: Install Caddy
    community.general.copr:
      name: '@caddy/caddy'
      chroot: fedora-rawhide-{{ ansible_facts.architecture }}
      includepkgs:
      - caddy

  - name: Config Caddy
    ansible.builtin.copy:
      src: ../config/Caddyfile
      dest: /etc/caddy/Caddyfile
      mode: '0644'
    notify: Reload Caddy

  - name: Remove podman, buildah
    ansible.builtin.dnf:
      state: absent
      name:
      - podman
      - buildah

  - name: Add Docker CE Repo
    ansible.builtin.command: "dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
    args:
      creates: /etc/yum.repos.d/docker-ce.repo

  - name: Install deps
    ansible.builtin.dnf:
      name:
      - python3-pip
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - git
      state: present

  - name: Enable docker daemon
    ansible.builtin.systemd_service:
      name: docker
      state: started
      enabled: true

  - name: Install docker SDK
    ansible.builtin.pip:
      name:
      - docker
      state: present

  - name: Log into GHCR registry
    community.docker.docker_login:
      registry_url: https://ghcr.io
      username: elibroftw
      password: "{{ docker_ghcr_pass }}"
      reauthorize: false

- name: Deploy Rybbit
  hosts: elijahlopez_ca_1
  tasks:
    - name: Clone or pull Rybbit repository
      ansible.builtin.git:
        repo: https://github.com/rybbit-io/rybbit.git
        dest: /opt/rybbit
        update: yes
      notify: Deploy Rybbit

    - name: Make setup.sh executable
      ansible.builtin.file:
        path: /opt/rybbit/setup.sh
        state: file
        mode: u+x

    - name: Run Rybbit setup script
      ansible.builtin.command: /opt/rybbit/setup.sh ryb.elijahlopez.ca --no-webserver
      args:
        creates: /opt/rybbit/.setup_done

    - name: Create sentinel file
      ansible.builtin.file:
        path: /opt/rybbit/.setup_done
        state: touch
        mode: '0644'

  handlers:
  - name: Deploy Rybbit
    community.docker.docker_compose_v2:
        project_src: /opt/rybbit
        services:
          - backend
          - client
          - clickhouse
          - postgres
        state: present
        started: true

```

### Expected Results

I should be to run the playbook

### Actual Results

```console
[maste@SURFACE personal-self-hosted]$ ansible-playbook --ask-vault-pass -i inventory.yml playbooks/self_hosting.yml
Vault password: 

PLAY [Deploy website] **************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
fatal: [elijahlopez_ca_1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: kex_exchange_identification: read: Connection reset by peer\r\nConnection reset by 142.93.152.9 port 22", "unreachable": true}

PLAY RECAP *************************************************************************************************************************************************************************************
elijahlopez_ca_1           : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

[maste@SURFACE personal-self-hosted]$ ansible-playbook --ask-vault-pass -i inventory.yml playbooks/self_hosting.yml
Vault password: 

PLAY [Deploy website] **************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
fatal: [elijahlopez_ca_1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 142.93.152.9 port 22: Connection refused", "unreachable": true}

PLAY RECAP *************************************************************************************************************************************************************************************
elijahlopez_ca_1           : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
