### ISSUE TITLE
HTTPSConnection.__init__() got an unexpected keyword argument 'cert_file' with unarchive

### ISSUE THREAD

**Issue by mhanke-ionos** [ansible/ansible#85341]
### Summary

When trying to download a file with https in the unarchive module from a control (python 3.11) on target node (python 3.13), the download fails due to unexpected keyword argument 'cert_file'.

### Issue Type

Bug Report

### Component Name

unarchive

### Ansible Version

```console
ansible==11.6.0
ansible-core==2.18.6
```

### Configuration

```console
CONFIG_FILE() = None
```

### OS / Environment

Debian 12 (Target system Debian 13)

### Steps to Reproduce

Running on Python < 3.13.3 on control to target system >= 3.13
```yaml (paste below)
  ansible.builtin.unarchive:
    src: https://example.com/example.zip
    dest: /usr/local/bin
    remote_src: yes
```

### Expected Results

Use new keyword for newer python versions.

### Actual Results

```console
Failure downloading https://example.com/example.zip, An unknown error occurred: HTTPSConnection.__init__() got an unexpected keyword argument 'cert_file'
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
