### ISSUE TITLE
run_once not working (needs info)

### ISSUE THREAD

**Issue by jimsmith** [ansible/ansible#8543]
Hello I posted this as run_once on Ansible 1.7 does not work and noticed the thread was closed 
https://github.com/ansible/ansible/pull/7421#issuecomment-51670943

Any chance this can be re-opened and fixed as I have DB Schema tasks that require to run once only.

Cheers.!

**Comment by mpdehaan** [comment]
Hi @jimsmith,

If you have a question, the best place to ask would be on the mailing list, though you may have found a problem.

Ultimately the most important thing for us to see is the output of "ansible --version" and the complete playbook you have that reproduces this item (with output).

Thank you!

**Comment by jimsmith** [comment]
ok well my playbook is doing web rolling deployments and the output is quite long and some confidential info in the output so I've omitted most of it and concentrated on the run_once 

## Issue Type:

Bug Report

## Ansible Version:

ansible --version
ansible 1.7

## Target:

ec2 tags_Name_STAGING_APPS

Steps To Reproduce:

playbook

``` yaml
# This playbook does a rolling update for all webservers serially (one at a time).
# Change the value of serial: to adjust the number of server to be updated.
#
- hosts: tag_Name_STAGING_APPS
  gather_facts: yes
  user: deployer
  serial: 1
  sudo: true
  sudo_user: deploy # temporarily required until this user is phased out on staging servers
  vars_files:
   - group_vars/stg.yml
  roles:
   - deploy

```

deploy role

``` yaml
- name: run django migrations
  command: "/path/to/db_migrations.sh"
# run_once: true -- this action will be availabe in ansible version 1.7, which is dev version now.
# run_once doesn't work in current release, so 'delegate_to' should be specified to be executed for particular host
  run_once: True
  delegate_to: "192.168.1.2"
#  tags:
#    - deploy
  register: run_migrations
# Print all contents of the shell task's output.
- debug: var=run_migrations.stdout_lines
```

This runs more than once on each ec2 instance in the tag, and the delegate_to the command when it runs on the next ec2 instance it runs the job again on the server that it's delegated to.

``` bash
ASK: [deploy | run django migrations] **************************************** 
<192.168.1.2> ESTABLISH CONNECTION FOR USER: deployer
<192.168.1.2> REMOTE_MODULE command /path/to/db_migrations.sh
<192.168.1.2> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ForwardAgent=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '192.168.1.2', "/bin/sh -c 'mkdir -p /tmp/ansible-tmp-1407748678.32-173513695411310 && chmod a+rx /tmp/ansible-tmp-1407748678.32-173513695411310 && echo /tmp/ansible-tmp-1407748678.32-173513695411310'"]
<192.168.1.2> PUT /tmp/tmpIWAZr4 TO /tmp/ansible-tmp-1407748678.32-173513695411310/command
<192.168.1.2> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ForwardAgent=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '192.168.1.2', u"/bin/sh -c 'chmod a+r /tmp/ansible-tmp-1407748678.32-173513695411310/command'"]
<192.168.1.2> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ForwardAgent=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '192.168.1.2', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=nmkdqfsvilbrcfkelfsnavutexqhzsoe] password: " -u deploy /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-nmkdqfsvilbrcfkelfsnavutexqhzsoe; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1407748678.32-173513695411310/command\'"\'"\'\'']
<192.168.1.2> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ForwardAgent=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '192.168.1.2', "/bin/sh -c 'rm -rf /tmp/ansible-tmp-1407748678.32-173513695411310/ >/dev/null 2>&1'"]
changed: [192.168.1.2 -> 192.168.1.2] => {"changed": true, "cmd": ["/path/to/db_migrations.sh"], "delta": "0:00:21.330655", "end": "2014-08-11 10:18:20.633114", "rc": 0, "start": "2014-08-11 10:17:59.302459", "stderr": "\nreal\t0m3.395s\nuser\t0m2.660s\nsys\t0m0.445s\n\nreal\t0m17.380s\nuser\t0m14.388s\nsys\t0m1.267s", "stdout": "OMITTED"}

TASK: [deploy | debug var=run_migrations.stdout_lines] ************************ 
<192.168.1.2> ESTABLISH CONNECTION FOR USER: deployer
ok: [192.168.1.2] => {
    "run_migrations.stdout_lines": [
        "PREPARING DATABASE...", 
        "Change the current working directory", 
        "SETTING OMMITTEDDJANGO ENVIRONMENT VARIABLES...", 
        "DATABASE-SYNCDB RUNNING FOR OMMITTED...", 
        "Syncing...", 
        "(use ./manage.py migrate to migrate these)", 
        "Running migrations for django_extensions:", 
        "- Nothing to migrate.", 
        " - Loading initial data for django_extensions.", 
        "", 
        "DATABASE-MIGRATIONS RAN"
    ]
}
```

**Comment by mpdehaan** [comment]
Thanks!

**Comment by ansibot** [comment]
Thanks for filing a ticket! I am the friendly GitHub Ansibot. I see you did not fill out your issue description based on our new issue template. Please copy the contents of this [template](https://raw2.github.com/ansible/ansible/devel/examples/issues/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket. 

Our system will automatically close tickets that do not have an issue template filled out within 7 days. Please note that due to large interest in Ansible, humans may not comment on your ticket if you ask them questions. Don't worry, you're still in the queue and the robots are looking after you.

**Comment by sivel** [comment]
There was discussion of this on the ansible-project list:  https://groups.google.com/forum/#!msg/ansible-project/kXeXAPXhrU4/FFHpvML0OawJ

The issue seems to be using `run_once` with `serial`.  `run_once` is simply a way to activate `BYPASS_HOST_LOOP` for any module, and to my knowledge this is the same behavior as would be seen with something like `add_host`.  `run_once` may simply not be the right choice when using `serial` and per Michael's suggestion, we may just need to error out in the event that they are used together.

**Comment by jimsmith** [comment]
Hello thank you for the response, I'm not fully understanding as I'm relatively new to Python.

However when I test using the when: inventory_hostname it is not working for me.

``` yaml
- name: test
  ec2_facts:
  register: facts

- name: migration
  command: "/path/migrations.sh"
# run_once: true -- this action will be availabe in ansible version 1.7, which is dev version now.
# run_once doesn't work in current release, so 'delegate_to' should be specified to be executed for particular host
# Bug submitted -> https://github.com/ansible/ansible/issues/8543
  run_once: True
# {{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}
  when: inventory_hostname == {{ ec2_tag_Name }}[0]

listing the hosts from the ec2 tag name does indeed display my 2 ec2 hosts

  play #1 (tag_Name_SERVER_INSTANCES): host count=2
    192.168.1.2
    192.168.1.3

however this error is what I get

Perform task: deploy | migrations (y/n/c):  ************************
fatal: [192.168.1.2] => error while evaluating conditional: inventory_hostname == SERVER_INSTANCES[0]

FATAL: all hosts have already failed -- aborting
```

I'm not entirely sure how the inventory_hostname is suppose to be setup ?
Any pointers or am I doing something obvious wrong ?

Thanks.!
