### ISSUE TITLE
copy module does not set directory_mode when copying recursively

### ISSUE THREAD

**Issue by kevinoid** [ansible/ansible#8572]
##### Issue Type:

Bug Report
##### Ansible Version:

devel (currently 8abd6370)
##### Environment:

Debian Linux testing, managing Debian Linux wheezy or testing.
##### Summary:

When copying recursively, `copy` does not set `directory_mode` on directories which already exist.
##### Steps To Reproduce:

In a directory with the following playbook named `permtest.yml`:

``` yml

---
- hosts: all
  tasks:
    - copy: src=testdir dest=/tmp directory_mode=0750 mode=0640
    - copy: src=testdir dest=/tmp directory_mode=0755 mode=0644
```

Run the following commands:

``` sh
mkdir -p testdir/subdir
touch testdir/subdir/testfile.txt
ansible-playbook -c local -i localhost, permtest.yml
find /tmp/testdir -printf "%m\t%p\n"
```
##### Expected Results:

```
755 /tmp/testdir
755 /tmp/testdir/subdir
644 /tmp/testdir/subdir/testfile.txt
```
##### Actual Results:

```
750 /tmp/testdir
750 /tmp/testdir/subdir
644 /tmp/testdir/subdir/testfile.txt
```
