### ISSUE TITLE
group_vars not evaluated for hosts added to group dynamically (edit: add_host module)

### ISSUE THREAD

**Issue by quentinsf** [ansible/ansible#8605]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Mac OS X 10.9.4
Python 2.7.5
##### Summary:

group_vars files do not appear to be evaluated for hosts added to a group dynamically - either using add_hosts or from a dynamic inventory such as ec2.py
##### Steps To Reproduce:

Here's a minimal demo:

```
- hosts: localhost
  tasks:
   - add_host: name=localhost
               groups=demo_group

- hosts: demo_group
  roles:
   # Localhost will ignore group_vars/demo_group 
   # when running this.
   - demo_role
```
##### Expected Results:

If a host is added to a group dynamically, either using the add_host module or by a dynamic inventory such as ec2.py, it will be in that group for the later plays in the playbook, and get assigned appropriate roles etc. It will run the tasks in the roles, and it will get variable values in roles/*/defaults directories.

I would expect it also to get the values from group_vars directories in the same way as if it came from a static inventory file, but it doesn't seem to.
##### Actual Results:

Variables from the role's 'defaults' directory do exist, but any variables defined in group_vars directories do not override them as described in the docs for variable precedence.  The only way I can change them is by using -e on the command line.

I'm guessing the group_vars directories are loaded at the time of loading traditional static inventory files, and are not applied after any more dynamic changes?

This means, for example, that groups defined by ec2.py are fundamentally different from groups defined in an inventory file.  To me, this is unexpected.  But if it is by design, or hard to fix, it should probably be documented.

I'm guessing this may be related to issue #6563 

Many thanks!

**Comment by quentinsf** [comment]
As a neat workaround, I can import the group_vars explicitly in this case:

```
- hosts: localhost
  tasks:
   - add_host: name=localhost
               groups=demo_group
   - include_vars: group_vars/demo_group
```

Slightly more complex if the groups come from a dynamic inventory, though.

And if the inventory and group_vars are in a subdirectory, I'm still stuck: I don't know the path to the groups_vars directory because I don't know which inventory was specified on the command line.
