### ISSUE TITLE
The alternatives module is erroneously reporting "changed" status.

### ISSUE THREAD

**Issue by yeroc** [ansible/ansible#8613]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel ba4693051b) last updated 2014/08/06 15:37:06 (GMT -600)
##### Environment:

CentOS 6
##### Summary:

The alternatives module is reporting "changed" status when re-running a task that has already been successfully applied.
##### Steps To Reproduce:

Given a task:

```
- name: Configure Java alternatives
  alternatives: name={{ item.name }} link={{ item.link }} path={{ item.path }}
  with_items:
  - { name: jar, link: /usr/bin/jar, path: "{{ jdkversions[ jdkversion ]['installdir'] }}/bin/jar" }
  - { name: jps, link: /usr/bin/jps, path: "{{ jdkversions[ jdkversion ]['installdir'] }}/bin/jps" }
  - { name: java, link: /usr/bin/java, path: "{{ jdkversions[ jdkversion ]['installdir'] }}/bin/java" }
  - { name: jmap, link: /usr/bin/jmap, path: "{{ jdkversions[ jdkversion ]['installdir'] }}/bin/jmap" }
  - { name: javac, link: /usr/bin/javac, path: "{{ jdkversions[ jdkversion ]['installdir'] }}/bin/javac" }
  - { name: javaws, link: /usr/bin/javaws, path: "{{ jdkversions[ jdkversion ]['installdir'] }}/bin/javaws" }
  - { name: jstack, link: /usr/bin/jstack, path: "{{ jdkversions[ jdkversion ]['installdir'] }}/bin/jstack" }
  - { name: jvisualvm, link: /usr/bin/jvisualvm, path: "{{ jdkversions[ jdkversion ]['installdir'] }}/bin/jvisualvm" }
```
##### Expected Results:

The first time the task is run the status is "changed" as expected.  We expect subsequent runs with the identical path specified to indicate an "ok" status.
##### Actual Results:

When running the task subsequently the status is actually reporting "changed".
