### ISSUE TITLE
Delegated Hosts Don't Use Inventory Details or Confirm Existence In Inventory

### ISSUE THREAD

**Issue by piffey** [ansible/ansible#8615]
I wasn't sure if this was a bug or intended behavior. When I think about the issue, it seems more intuitive that you'd use the same name that you would for a host in your inventory and expect Ansible to use the same connection details when running the task.
##### Summary:

When running a task with delegate_to it doesn't look the provided host up in the inventory. You can pass it anything and it will try to SSH to it. Since that's the case it also doesn't properly look up the ansible_ssh_port for the delegated host.
##### Steps To Reproduce:

Hosts File:
(Using 127.0.0.1 as an example, but assume that's a WAN IP with a bunch of NAT one-to-many forwards.)

```
 host1 ansible_ssh_host=127.0.0.1 ansible_ssh_port=22
 host2 ansible_ssh_host=127.0.0.1 ansible_ssh_port=22222
```

Playbook:

```
- name: A Most Noble Reproduction
  hosts: host1
  remote_user: root

  tasks:
    - name: Do The Delegationating
      shell: hostname
      delegate_to: host2

    - name: Do The Delegationating, Part Deux
      shell: echo 'If you see this in your syslog maybe someone should disable passwordless root logins at the googles.'
      delegate_to: google.com
```
##### Expected Results:

```
changed: [host1 -> host2] => {"changed": true, "cmd": "hostname", "stderr": "", "stdout": "host2"}
fatal: [host1 -> google.com] => Host google.com ain't all up in your inventory.
```
##### Actual Results:

```
changed: [host1 -> host2] => {"changed": true, "cmd": "hostname", "stderr": "", "stdout": "host1"}
fatal: [host1 -> google.com] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
```

Edit: Seems likely related to [Issue 8224](https://github.com/ansible/ansible/issues/8224).
Edit2: Made the title better. Seemed ambiguous/not as explanatory as it could be.
