### ISSUE TITLE
when using valid sudo_user - permission denied is returned

### ISSUE THREAD

**Issue by vladcosorg** [ansible/ansible#8623]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Vagrant 1.6.3
Ubuntu 14.04 x64 on both sides
##### Summary:

The command is not executed under sudo even though it should
##### Steps To Reproduce:

user is added into sudoers file
`vagrant ALL=(ALL) NOPASSWD:ALL`

run the playbook on the ubuntu server

```
- hosts: all
  remote_user: vagrant
  tasks:
    - shell: touch /etc/testing
      sudo_user: vagrant
```
##### Expected Results:

the command executes successfully because the user is sudoer
##### Actual Results:

Permission denied
error output: https://gist.github.com/chetzof/a3518d866079539a5ae9

Does work:

```
    - hosts: all
      remote_user: vagrant
      tasks:
        - shell: touch /etc/testing
          sudo: yes
```

Also does work:

```
    - hosts: all
      remote_user: vagrant
      tasks:
        - shell: sudo touch /etc/testing
```
