### ISSUE TITLE
pip command may be interactive; hangs provisioning

### ISSUE THREAD

**Issue by miohtama** [ansible/ansible#8625]
##### Summary:

[pip command](http://docs.ansible.com/pip_module.html) uses underlying Python's `pip` to install packages.

The installation may become interactive. E.g. if you supply pip a requirement in `requirements.txt` like (not a real one): 

```
    -e git+https://github.com/miohtama/my_egg_repo.git@dce74e99c911fb70854151b372629fb2912ce968#egg=my_egg
```

Here is a sample `tasks.yml` for Ubuntu 12.04:

```
#

- name: Bring box apt sources up-to-date
  apt: update_cache=yes
  sudo: yes

- name: Upgrade distro
  apt: upgrade=dist
  sudo: yes

- name: Install dependencies
  sudo: yes
  apt: name={{ item }} state=installed
  with_items:
    - git
    - python-dev
    - python-virtualenv

- name: Hang because pip install asks for HTTPS password using readline
  pip: name=git+https://github.com/miohtama/ansible-broken-repo.git@dce74e99c911fb70854151b372629fb2912ce968#egg=my_egg
```

... the pip will stop to prompt HTTPS username and password command from the command line. This is not echoed any way back to the ansible and thus the provisioning stops in limbo, waiting for the ghost fingers to type in the password.

With the quick look, I didn't find a command line option to disable ask password behavior in pip.

I am not sure what are the best practices regarding Ansible and interactive input (and disabling it), so I am looking for some feedback before trying to tackle this issue further.
##### Steps To Reproduce:

Add any HTTPS link to private Github repository in your `requirements.txt`
##### Expected Results:

The ansible aborts the execution. Either it tells HTTPS passwords are not supported or tells how to supply one.
##### Actual Results:

The ansible process hungs forever.
