### ISSUE TITLE
Task outputs "ok" and "changed" at the same time for devel with the commands module.

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#8645]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 91560c00a9) last updated 2014/08/16 14:27:59 (GMT +200)
##### Environment:

Debian GNU/Linux jessie/sid
##### Summary:

Task outputs "skipped" and "ok" at the same time
##### Steps To Reproduce:

Playbook:

```

---
- hosts: localhost
  tasks:
  - name: create dirs
    command: mkdir /tmp/bla creates=/tmp/bla
```
##### Expected Results:

Expected output on second run:

```
TASK: [create dirs] *********************************************************** 
skipping: [127.0.0.1]
```
##### Actual Results:

```
TASK: [create dirs] *********************************************************** 
skipping: [127.0.0.1]
ok: [127.0.0.1]
```
