### ISSUE TITLE
no_log does not control syslog and not valid at play level

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#8647]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel f4d649bea0) last updated 2014/08/16 20:00:09 (GMT +200)
##### Environment:

Debian GNU/Linux jessie/sid
##### Summary:

`no_log` seems to be broken and still logs to syslog
##### Steps To Reproduce:

Playbook:

```

---
- name: test
  gather_facts: no
  hosts: 127.0.0.1

  tasks:
    - name: testing
      copy: dest=/tmp/test content=123
      no_log: True
```
##### Expected Results:

Nothing in syslog
##### Actual Results:

Syslog says:

```
Aug 16 20:26:00 apollo13 ansible-file[26574]: Invoked with directory_mode=None force=False remote_src=None path=/tmp/test owner=None group=None serole=None content=123 state=None diff_peek=None setype=None dest=/tmp/test selevel=None original_basename=tmpAdXCKS regexp=None validate=None src=tmpAdXCKS seuser=None recurse=False delimiter=None mode=None backup=None
```

Additionally: no_log on the play itself throws: ERROR: no_log is not a legal parameter at this level in an Ansible Playbook -- even though I am running latest devel
