### ISSUE TITLE
rabbitmq_plugin file permissions

### ISSUE THREAD

**Issue by stevenringo** [ansible/ansible#8660]
##### Issue Type:

Potential Bug in `rabbitmq_plugin`
##### Ansible Version:

1.7
##### Environment:

RHEL 6.5, hardened to CIS.
##### Summary:

Not sure if this is a bug or the way I am using the module... :rabbit2:  

RabbitMQ is installed as `root`, yet it runs as the `rabbitmq` user.

When using the `rabbitmq_plugin` module, it defaults to writing the `/etc/rabbitmq/enabled_plugins` file as root. As we run a system that has a default umask of 0002, the file cannot be read and therefore the service fails to start.

There seems to be no way to change the owner/permissions on the file directly in the module, even with `sudo_user` and one has to change the file permissions manually after the module has executed.

Thanks
##### Steps To Reproduce:

```
- name: install RabbitMQ RPM key
  rpm_key: key={{ rabbitmq_key_url }}

- name: retrieve RabbitMQ RPM from RabbitMQ website
  get_url: url="{{rabbitmq_url}}" dest="/usr/share/{{rabbitmq_rpm}}" mode=0440

- name: install RabbitMQ RPM
  yum: name="/usr/share/{{rabbitmq_rpm}}" state=present

- name: enable the RabbitMQ management console
  command: "rabbitmq-plugins enable {{item}}"
  with_items:
    - rabbitmq_management
    - rabbitmq_management_visualiser
  notify: restart rabbitmq

- name: ensure rabbitmq permissions on etc/rabbitmq
  file: path=/etc/rabbitmq owner=rabbitmq group=rabbitmq mode=0755 state=directory

- name: ensure permissions on rabbitmq enabled_plugins file
  file: path=/etc/rabbitmq/enabled_plugins owner=rabbitmq group=rabbitmq mode=0644

- name: ensure RabbitMQ is running
  service: name=rabbitmq-server state=started enabled=yes
```
##### Expected Results:

Would like `rabbitmq-plugins` to allow overriding the owner and mode of the `/etc/rabbitmq/enabled_plugins` file
##### Actual Results:

`/etc/rabbitmq/enabled_plugins` is given root permissions and `umask` defaults
