### ISSUE TITLE
slack notification module error

### ISSUE THREAD

**Issue by hundredblocks** [ansible/ansible#8669]
I'm getting a 404 not found error using the slack notification module as follows:

failed: [104.131.219.13 -> 127.0.0.1] => {"failed": true}
msg:  failed to send payload={"username": "webhookbot", "text": "104.131.219.13 completed", "icon_emoji": ":ghost:", "channel": "#general", "link_names": 1} to https://cloudmode.slack.com/services/hooks/incoming-webhook?token=[obscured]: HTTP Error 404: Not Found

FATAL: all hosts have already failed -- aborting

the yml setup is:

```
- name: Send notification message via Slack all options
  local_action:
    module: slack
    domain: cloudmode.slack.com
    token: <my_token>
    msg: "{{ inventory_hostname }} completed"
    channel: "#general"
    username: "webhookbot"
    icon_emoji: ":ghost:"
```

the equivalent CURL command works from the host upon which the ansible script is executing. I've also verified my token using CURL to successfully post to a slack channel

Any ideas?

Ansible template below:
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 14.04
##### Summary:

I'm getting a 404 not found error using the slack notification module as follows:

failed: [104.131.219.13 -> 127.0.0.1] => {"failed": true}
msg:  failed to send payload={"username": "webhookbot", "text": "104.131.219.13 completed", "icon_emoji": ":ghost:", "channel": "#general", "link_names": 1} to https://cloudmode.slack.com/services/hooks/incoming-webhook?token=[obscured]: HTTP Error 404: Not Found
##### Steps To Reproduce:

the yml setup is:

```
- name: Send notification message via Slack all options
  local_action:
    module: slack
    domain: cloudmode.slack.com
    token: <my_token>
    msg: "{{ inventory_hostname }} completed"
    channel: "#general"
    username: "webhookbot"
    icon_emoji: ":ghost:"
```

with an incoming webhook setup on slack
##### Expected Results:

A message to the general channel of cloudmode.slack.com when ansible-playbook is called
##### Actual Results:

failed: [104.131.219.13 -> 127.0.0.1] => {"failed": true}
msg:  failed to send payload={"username": "webhookbot", "text": "104.131.219.13 completed", "icon_emoji": ":ghost:", "channel": "#general", "link_names": 1} to https://cloudmode.slack.com/services/hooks/incoming-webhook?token=[obscured]: HTTP Error 404: Not Found
