### ISSUE TITLE
ini_file strips out extension declaration in php.ini

### ISSUE THREAD

**Issue by jsmirnov** [ansible/ansible#8677]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7
##### Environment:

Vagrant machine with image "hashicorp/precise64".
Ubuntu 12.04 LTS
##### Summary:

I understand that this sounds really weird, but I can't find the source of the problem atm.
When I run mailcatcher task and ini_file command executed `extension=redis.so` line is stripped out. Seems like easter-egg %)
##### Steps To Reproduce:

I am running vagrant machine and configuring it with simple playbook. I am able to reproduce this issue with following data.
ansible.cfg

```
[defaults]
host_key_checking=false
```

ansible_hosts

```
vagrantbox ansible_connection=local
```

group_vars/all

```

---
env: prod
```

host_vars/vagrantbox

```

---
env: dev

```

playbook.yml

```

---
- hosts: vagrantbox
  remote_user: vagrant
  sudo: True
  roles:
     - php-fpm
     - { role: mailcatcher, when: env == "dev" }
```

roles/php-fpm/handler/main.yml

```

---
- name: restart php5-fpm
  service: name=php5-fpm state=restarted enabled=true

```

roles/php-fpm/tasks/main.yml

```

---
- name: Add php 5.4 repository
  apt_repository: repo='ppa:ondrej/php5-oldstable'
- name: Install php-fpm and deps
  apt: pkg={{ item }} state=present
  with_items:
    - php5-fpm
    - php5
    - php5-cli
    - php5-imagick
    - php5-gd
    - php5-mcrypt
    - php5-mysql
    - php-apc
    - php5-curl
    - php5-mhash
    - php-pear
    - php5-dev
- shell: pecl list | grep -ic lzf
  register: lzf_installed
  failed_when: false
  changed_when: false
- shell: pecl install lzf
  when: lzf_installed.stdout|int == 0
- shell: pecl list | grep -ic redis
  register: redis_installed
  failed_when: false
  changed_when: false
- shell: pecl install redis
  when: redis_installed.stdout|int == 0
- set_fact: >
    {% if env == "prod" %}apc_stat=0{% else %}apc_stat=1{% endif %}
- template: src=customizations.ini.j2 dest=/etc/php5/mods-available/customizations.ini mode=0644
  notify:
    - restart php5-fpm
- name: set symlink for custmizations file
  file: src=/etc/php5/mods-available/customizations.ini dest=/etc/php5/{{item}}/conf.d/customizations.ini owner=root group=root state=link
  with_items:
  - cli
  - fpm
  notify:
    - restart php5-fpm
```

roles/php-fpm/templates/customizations.ini.j2

```
; {{ ansible_managed }}
[extension]
extension=redis.so
extension=lzf.so

[Date]
date.timezone = Europe/Tallinn

[PHP]
memory_limit = 512M
expose_php = Off
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379?database=0&timeout=120"

[APC]
apc.enabled = "1"
apc.enable_cli=0
apc.stat = "{{ apc_stat }}"
apc.max_file_size = "5M"
apc.localcache = "1"
apc.localcache.size = "512"
apc.shm_segments = "1"
apc.ttl = "3600"
apc.user_ttl = "7200"
apc.gc_ttl = "3600"
apc.cache_by_default = "1"
apc.filters = ""
apc.write_lock = "1"
;apc.num_files_hint= "0"
;apc.user_entries_hint="0"
apc.num_files_hint = 10000
apc.user_entries_hint = 10000
apc.shm_size = "256M"
apc.mmap_file_mask=/tmp/apc.XXXXXX
apc.include_once_override = "0"
apc.file_update_protection="2"
apc.canonicalize = "1"
apc.report_autofilter="0"
apc.stat_ctime="0"
```

roles/mailcatcher/tasks/main.yml

```

---
- name: Add rubygems stable repository with latest versions
  apt_repository: repo='ppa:skottler/ruby193-latest' state=absent
- name: install ruby and rubygems
  apt: pkg={{ item }} state=present
  with_items:
    - ruby
    - ruby1.9.3
    - rubygems
    - libsqlite3-dev
- file: src=/usr/bin/ruby1.9.3 dest=/etc/alternatives/ruby state=link
- file: src=/etc/alternatives/ruby dest=/usr/bin/ruby state=link
- file: src=/usr/bin/gem1.9.3 dest=/etc/alternatives/gem state=link
- file: src=/etc/alternatives/gem dest=/usr/bin/gem state=link
- name: install mailcatcher
  gem: name=mailcatcher user_install=no
- name: get path to mailcatcher
  command: which catchmail
  register: catchmail_path
# strips out comment and extension=redis.so
- ini_file: dest=/etc/php5/mods-available/customizations.ini section="mail function" option=sendmail_path value="{{ catchmail_path.stdout}} -f sent.from@vagrant.box"
- shell: ps aux | grep "mailcatcher --ip=0.0.0.0" | grep -v grep | grep -c mailcatcher
  register: mailcatcher_started
  failed_when: False
```
##### Expected Results:

In 'dev' environment customizations.ini file contains extension=redis.so line as well as mail function config
##### Actual Results:

In 'dev' environment customizations.ini file does not contain extension=redis.so line as well as ansible managed comment.

**Comment by mpdehaan** [comment]
# Information Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

We have some questions we'd like to know about before we can get this request queued up.   If you can help answer them, we'd greatly appreciate it:
- please supply a minimial playbook that reproduces this problem.  Ideally this playbook would be limited to just 1 or 2 tasks.
- please test this on the most recent version of Ansible, which is 1.7.1

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by jsmirnov** [comment]
@mpdehaan 
currently I see all information required to reproduce an issue.
if you interested in some specific request please be more specific.
Thanks.

**Comment by oskarpearson** [comment]
Hi @jsmirnov - I've spent some time looking into this. The root cause is that there are two items with the same name field in the ini block. What's happening is that you are running into http://en.wikipedia.org/wiki/INI_file#Duplicate_names - and Ansible is dropping redis.so since the name field 'extension' has being used twice.

 You're expecting this output:

``` INI
[extension]
extension=redis.so
extension=lzf.so
```

but instead you are getting

``` INI
[extension]
extension=lzf.so
```

I've managed to get a much simplified example that shows this as follows:

In playbook.yml

```
---
- hosts: all
  gather_facts: no
  tasks:
    - name: Since ini_file changes the file inline, let's copy it first
      copy: src=customizations.ini-orig dest=/tmp/customizations.ini
    - name: Add a new section to customizations.ini
      ini_file: dest=/tmp/customizations.ini section="mail function" option=sendmail_path value="something"
```

Then, customizations.ini-orig:

```
[extension]
extension=redis.so
extension=lzf.so
```

resulting file:

```
[extension]
extension = lzf.so

[mail function]
sendmail_path = something
```
