### ISSUE TITLE
vars_prompt with private:no setting never continues

### ISSUE THREAD

**Issue by stefanvangastel** [ansible/ansible#8680]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 14.04 LTS 
Vagrant 1.6.3
Python 2.7.6
##### Summary:

Error is generated using Ansible 1.7 and the vars_prompt feature. 

I did not have the issue using Ansible 1.3 but upgraded tot the latest version because I needed the debconf feature.

The raw_input call in the on_vars_prompt function in /usr/lib/pymodules/python2.7/ansible/callbacks.py seems to 'freeze' when the private: no is set and the question is answered followed by a enter key.

If private is set to yes (or using the default) and thus the getpass.getpass is used, the prompt progresses after the enter key is pressed.
##### Steps To Reproduce:

Create a playbook using vars_prompt like this:

```

---
- name: Deploys the whole software stack for a CakePHP application
  hosts: development
  user: vagrant
  sudo: yes

  vars_prompt:
  - name: "cakephp_version"
    prompt: "\n\nWhat version of CakePHP do you want to deploy? (2 or 3)?"
    default: "2"
    private: no

  roles:
    - system
```
##### Expected Results:

```
What version of CakePHP do you want to deploy? (2 or 3)? [2]: 3
```

![works](https://cloud.githubusercontent.com/assets/2473490/3965007/faab2708-2790-11e4-8aff-0fdc34dbc7fc.png)
##### Actual Results:

```
What version of CakePHP do you want to deploy? (2 or 3)? [2]: 3

asfasfasf
asf
asf

```

![fail](https://cloud.githubusercontent.com/assets/2473490/3965032/5b9a18c6-2791-11e4-941b-1f0cf17a776e.png)
