### ISSUE TITLE
group_by makes Ansible think that a change happens

### ISSUE THREAD

**Issue by Signum** [ansible/ansible#8683]
I'm using ad-hoc groups like these in my site.yml:

```
- hosts: all
  tasks:
  # Create ad-hoc groups like 'dist_Ubuntu'
  - group_by: key=dist_{{ ansible_distribution }}
```

And when I run this playbook Ansible claims that something has changed on the system:

```
TASK: [group_by key=net_{{ ansible_default_ipv4['network'] }}] **************** 
changed: [web1]
```

At the end of the run I get:

```
PLAY RECAP ******************************************************************** 
web1                       : ok=34   changed=1    unreachable=0    failed=0   
```

I find this confusing because it tells me that Ansible has done changes to the "web1" server while in fact it hasn't. Can "group_by" be told not to count as a change? Thanks.
