### ISSUE TITLE
ACL module doesn't expand tildes.

### ISSUE THREAD

**Issue by kevincox** [ansible/ansible#8734]
Hello, I noticed that the acl module doesn't expand tildes like most other modules do, the first example doesn't act as expected (`path not found or not accessible!`) while the second one does.

``` yaml
- acl:
    name: ~user/file
    # ...
```

``` yaml
- acl:
    name: /home/user/file
    # ...
```

``` sh
% ansible --version
ansible 1.7.1
% uname -a
Linux kevinlap 3.16.1-1-ARCH #1 SMP PREEMPT Thu Aug 14 07:40:19 CEST 2014 x86_64 GNU/Linux
```

Bug Report
