### ISSUE TITLE
Unclear rules regarding escapes/decoding of content attribute of copy module

### ISSUE THREAD

**Issue by NomAnor** [ansible/ansible#8778]
##### Issue Type:

Documentation Report
##### Ansible Version:

1.7.1
##### Environment:

Arch Linux
##### Summary:

Some regex backreferences (eg. \1) in the content attribute of the copy module get replaced with their escape characters.
##### Steps To Reproduce:

I use the shell module to generate a script file (fwbuilder rules). As this file needs to be created in a temporary directory and afterward deleted I use something like:

```

---
- hosts: all
  tasks:
    - name: Generate script
      shell:
        TMP=$(mktemp -d) && ( echo "Content with regex s/abc(.*)/\1/"; rm -r $TMP )
      register: variable

    - name: Install script
      copy:
        content: "{{ variable.stdout }}"
        dest: /some/file

```
##### Expected Results:

The content of /some/file should be

```
Content with regex s/abc(.*)/\1/
```
##### Actual Results:

The content is

```
Content with regex s/abc(.*)/<byte 0x01>/
```

The backref is replaced like an escape character.
##### Possible Fix:

After reading the source code a way to prevent this is to use

```
- name: Install script
  copy:
    content: "{{ variable.stdout.encode('unicode-escape') }}"
```

From the docs it is not clear that the content gets decoded. I think this behaviour should be documented and an example to prevent it should be added. Possible a better way would be to have an option so the content option uses the raw input without any decoding.
