### ISSUE TITLE
using the word import and a single quote within the lineinfile module messes up line

### ISSUE THREAD

**Issue by uncreative** [ansible/ansible#8806]
##### Ansible Version:

$ ansible --version
ansible 1.8 (devel b7082677de) last updated 2014/08/28 11:27:43 (GMT -700)
##### Environment:

OS X Mavericks 10.9.4
##### Summary:

using the word import and a single quote within the lineinfile module places single quotes within double quotes
lineinfile: dest=/tmp/myline.txt line="import g'" create=yes
produces: 
import g'"'"'
##### Steps To Reproduce:

$ cat playtest.yml

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: append line with single quotes and double quotes
    lineinfile: dest=/tmp/myline.txt line="import g'" create=yes
```

run it like this: ansible-playbook playtest.yml
$ ansible-playbook playtest.yml && cat /tmp/myline.txt && rm -f /tmp/myline.txt
##### Expected Results:

file /tmp/myline.txt should contain this line
import g'
##### Actual Results:

file /tmp/myline.txt contains this line
import g'"'"'
