### ISSUE TITLE
 ansible does not preserve types when passing variables into modules

### ISSUE THREAD

**Issue by uncreative** [ansible/ansible#8807]
##### Ansible Version:

$ ansible --version
ansible 1.8 (devel b7082677de) last updated 2014/08/28 11:27:43 (GMT -700)
##### Environment:

OS X Mavericks 10.9.4
##### Summary:

module: ansible does not preserve types when passing variables into modules
##### Steps To Reproduce:

$ cat my_print_type_module

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - my_print_type_module: thingy="{{ item }}"
    with_items:
    - 123
    - 7.123
```

$ cat library/my_print_type_module

```
#!/usr/bin/env python
import sys
import os

def main():
    module = AnsibleModule(
        argument_spec=dict(
            thingy=dict(required=True,),
        ),
    )
    params = module.params
    thingy = module.params['thingy']

    msg = 'type of %s is %s' % (str(thingy), type(thingy))

    module.exit_json(changed=False, msg=msg)

# import module snippets
from ansible.module_utils.basic import *
from ansible.module_utils.splitter import *

main()
```

run it like this: ansible-playbook playtest.yml -v
##### Expected Results:

ok: [127.0.0.1] =&gt; (item=123) =&gt; {"changed": false, "item": 123, "msg": "type of 123 is &lt;type **'int'&gt;**"}
ok: [127.0.0.1] =&gt; (item=7.123) =&gt; {"changed": false, "item": 7.123, "msg": "type of 7.123 is &lt;type **'float'&gt;**"}
##### Actual Results:

$ ansible-playbook playtest.yml -v

TASK: [my_print_type_module thingy="{{ item }}"] *****************************\* 
ok: [127.0.0.1] =&gt; (item=123) =&gt; {"changed": false, "item": 123, "msg": "type of 123 is &lt;type **'str'&gt;**"}
ok: [127.0.0.1] =&gt; (item=7.123) =&gt; {"changed": false, "item": 7.123, "msg": "type of 7.123 is &lt;type **'str'&gt;**"}
##### Notes:

I understand the correct way to handle this is to specify the type of thingy within the module argument_spec. However, I'm trying to create a few more flexible modules that allow you to change json and OS X preferences values and setting these to dictionaries. 
For instance, I've created a module named preferences which uses CoreFoundation.CFPreferencesSetAppValue(top_key, fullvalue, app_id) (OS X's api) to set preferences for apps in OS X

```
- name: add some favorite databases for test, staging, beta, prod
  preferences:
  args:
    app_id: "/Users/{{ansible_user_id}}/Library/Application Support/Sequel Pro/Data/Favorites.plist"
    key_path:
    - 'Favorites Root'
    - 'Children'
    val_type: dict
    val: 
      'database': 'ourdb'
      'host': "{{ item['host'] }}"
      'id': "{{ item['id'] }}"
      'name': "{{ item['name'] }}"
      'type': 0
      'useSSL': 0
    arr_element_key: 'host'
    force: no
    state: append
  with_items:
   - {'host': 'testa.mycompany.com', 'id': 1, 'name': 'test - unsharded'}
   - {'host': 'testb.mycompany.com', 'id': 2, 'name': 'test - sharded'}
   - {'host': 'staginga.mycompany.com', 'id': 3, 'name': 'staging - unsharded'}
   - {'host': 'stagingb.mycompany.com', 'id': 4, 'name': 'staging - sharded'}
   - {'host': 'betaa.mycompany.com', 'id': -5, 'name': 'beta - unsharded'}
   - ...
```

This fails because the program utilizing Favorites.plist requires id to be an integer, and because id is coming through as a var, it is transformed into a string. 
I split this up into many different databases and hardcoded all vars and it works great, but is extremely long. Ideally we could solve this within ansible and preserve types of variables when they are passed into modules. Otherwise, I'll be forced do more parsing within my module and send something a bit more ugly like:

id: "int: {{item['id']}}"
