### ISSUE TITLE
ec2_vpc module always returns "changed = true"

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#8811]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.8 (devel 3bd1e4f8b5) last updated 2014/08/28 21:51:11 (GMT -400)
##### Environment:

boto 2.3.2.1
##### Summary:

Running the same VPC creation tasks always results in status changed.  This seems to be triggered by [line 492 of ec2_vpc](https://github.com/ansible/ansible/blob/devel/library/cloud/ec2_vpc#L492), but that is an indicator that something is happening that shouldn't be.  
##### Steps To Reproduce:

```
- hosts: localhost
  gather_facts: no
  tasks:
  - name: create vpc
    ec2_vpc:
      state: present
      cidr_block: 172.22.0.0/16
      resource_tags: { "Name": "TEST" }
      subnets:
        - cidr: 172.22.1.0/24
          resource_tags: { "Name":"TEST-1" }
          az: us-east-1b
        - cidr: 172.22.2.0/24
          resource_tags: { "Name":"TEST-2" }
          az: us-east-1c 
      route_tables:
        - subnets:
            - 172.22.1.0/24
            - 172.22.2.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw 
      internet_gateway: True
      region: "{{ region }}"
      wait: yes
    register: vpc
```
##### Expected Results:

Creation would happen on the first time, but subsequent times changed should be = False.
##### Actual Results:

first run

```
$: ansible-playbook -i inventory/hosts test.yml -v

PLAY [localhost] **************************************************************

TASK: [create vpc] ************************************************************
changed: [localhost] => {"changed": true, "subnets": [{"az": "us-east-1c", "cidr": "172.22.2.0/24", "id": "subnet-45f92c32", "resource_tags": {"Name": "TEST-2"}}, {"az": "us-east-1b", "cidr": "172.22.1.0/24", "id": "subnet-0b2f3823", "resource_tags": {"Name": "TEST-1"}}], "vpc": {"cidr_block": "172.22.0.0/16", "dhcp_options_id": "dopt-d2cadfb0", "id": "vpc-0c5fea69", "region": "us-east-1", "state": "available"}, "vpc_id": "vpc-0c5fea69"}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

second run

```
$: ansible-playbook -i inventory/hosts test.yml -v

PLAY [localhost] **************************************************************

TASK: [create vpc] ************************************************************
changed: [localhost] => {"changed": true, "subnets": [{"az": "us-east-1c", "cidr": "172.22.2.0/24", "id": "subnet-45f92c32", "resource_tags": {"Name": "TEST-2"}}, {"az": "us-east-1b", "cidr": "172.22.1.0/24", "id": "subnet-0b2f3823", "resource_tags": {"Name": "TEST-1"}}], "vpc": {"cidr_block": "172.22.0.0/16", "dhcp_options_id": "dopt-d2cadfb0", "id": "vpc-0c5fea69", "region": "us-east-1", "state": "available"}, "vpc_id": "vpc-0c5fea69"}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
