### ISSUE TITLE
Tags ignored

### ISSUE THREAD

**Issue by xpepermint** [ansible/ansible#8874]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

OSX 10.9.4
##### Summary:

Tags are ignored on roles.
##### Steps To Reproduce:

```
# mail.yml

---
- hosts: mailers
  roles:
    - { role: mailer, tags: ['aaa'] }
```

```
# roles/mailer/tasks/main.yml

---
- name: configure postfix
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'null-client/main.cf', dest: '/etc/postfix/main.cf' }
  tags:
    - 'aaa2'
- name: restart postfix
  action: service name=postfix state=restarted
```

```
ansible-playbook mail.yml -i hosts 
```
##### Expected Results:

I would expect tasks to be ignored when requesting only task with `aaa` tag on `mailer`.
##### Actual Results:

Task `configure postfix` is always executed.
