### ISSUE TITLE
`docker` module image pulling broken in `devel`

### ISSUE THREAD

**Issue by bensymonds** [ansible/ansible#8925]
##### Issue Type:

“Bug Report”
##### Ansible Version:

`ansible 1.8`
`devel`@`1711df3b75dd226bbb2b2592ca3ee5165c311e17`
##### Environment:

N/A
##### Summary:

When you use the `docker` module to run an image, the image should be pulled from registry if necessary. This was the behaviour in v1.7.1, but seems to be broken in `devel`.

I would blame this line: https://github.com/ansible/ansible/compare/v1.7.1...devel#diff-c2983e7efb083bc8a8ce86d6b1bcd059R629. `resource` is the combined image name and tag, whereas it should be the image name (hopefully that makes sense to you - the variables/params in this module are badly named).
##### Steps To Reproduce:

Use `docker` module to run an image which is not present on the machine.
##### Expected Results:

The image should be pulled from registry and then run.
##### Actual Results:

The module fails with an error: `failed to pull the specified image`.

**Comment by iragsdale** [comment]
I'm seeing this issue as well.

**Comment by abadger** [comment]
@bensymonds, @iragsdale What command are you running?  I'm trying to replicate this but what I'm trying is going down a different code path....

**Comment by iragsdale** [comment]
Just running a playbook that includes a task that looks like this:

```
- name: create BCC web instances
  sudo: yes
  with_items: XXX
  register: XXX
  docker:
    name: XXXX
    state: running
    image: XXXXX
    env:
      XXXX: XXXX
    expose: 3000
    command: XXXX
```

If the image doesn't already exist on the box, then it fails completely. If I manually pull the image, it works fine.
