### ISSUE TITLE
register fails with sudo in playbooks

### ISSUE THREAD

**Issue by l0neranger** [ansible/ansible#8928]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

From: Mac OS X 10.9
Client: Mac OS X 10.9
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.
##### Steps To Reproduce:

The register module or var.stdout_lines seems to be failing when sudo is set to true in playbooks. Seems to be related to or is https://github.com/ansible/ansible/issues/5533

``` yaml

---
- hosts: '{{ host }}'
  user: '{{ user }}'
  sudo: True

  tasks:
  - name: Git pull
    local_action: shell cd gitrepository && git pull
    register: git_pull_output
  - debug: var=git_pull_output.stdout_lines
```
##### Expected Results:

The expected output is a success of the git pull on the local directory. The above playbook works flawlessy if sudo is commented out.

``` yaml

---
- hosts: '{{ host }}'
  user: '{{ user }}'
#  sudo: True

  tasks:
  - name: Git pull
    local_action: shell cd gitrepository && git pull
    register: git_pull_output
  - debug: var=git_pull_output.stdout_lines
```
##### Actual Results:

``` bash
BASH$ ansible-playbook -i hosts site.yml --extra-vars="host=host user=user" -k
SSH password:

PLAY [host] **************************************************************

GATHERING FACTS ***************************************************************
ok: [host]

TASK: [Git pull] **************************************************************
failed: [host -> 127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: [sudo via ansible, key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx] password:


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/user/site.retry

host                  : ok=1    changed=0    unreachable=0    failed=1
```
