### ISSUE TITLE
Playbook host groups and -i not working together

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#893]
If I have a playbook with two host groups and use this with -i, it doesn't work (no hosts matched). I've spent a good while trying to trace this through but I can't yet work out where the passed in inventory and the playbook hosts should be merged. 

Playbook:

```
[will@tangerine test]$ cat inventory.yml 
# Author: Will Thames
# Name: inventory
# Description: tests inventory

---
- hosts: test-a:test-b
  vars:
    tmpdir: /var/tmp

  tasks:
  - name: say hello
    action: command echo hello
```

ansible hosts contains:

```
[test-a]
10.2.3.4

[test-b]
10.2.3.5
```

Results:

```
[will@tangerine test]$ ansible-playbook inventory.yml -i '10.2.3.4,'

PLAY [test-a:test-b] ********************* 

GATHERING FACTS ********************* 
no hosts matched or remaining


TASK: [say hello] ********************* 
no hosts matched or remaining


PLAY RECAP ********************* 
```
