### ISSUE TITLE
looping over generators doesn't work

### ISSUE THREAD

**Issue by b6d** [ansible/ansible#8938]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel)
##### Environment:

Ubuntu 12.04
##### Summary:

Some jinja filters (`select_attr` among others) return generators. It seems currently impossible to loop over these in playbooks. (also tested on ansible 1.6.3)
##### Steps To Reproduce:

run the following playbook

``` yaml

---
- hosts: 127.0.0.1
  connection: local
  vars:
    stuff:
      - my_attr: true
        msg: 'pick me!'
      - my_attr: true
        msg: 'pick me too!'
      - my_attr: false
        msg: 'but do not pick me ...'
  tasks:
    # this works ...
    - command: /bin/echo {{ item.msg }}
      when: item.my_attr
      with_items: stuff

    # ... this works (note the explicit creation of a list) ...
    - command: /bin/echo {{ item.msg }}
      with_items: stuff|selectattr("my_attr")|list

    # ... this doesn't (but it would be nice if it would ...)
    - command: /bin/echo {{ item.msg }}
      with_items: stuff|selectattr("my_attr")
```
##### Expected Results:

all tasks doing the same thing (echoing the first two messages)
##### Actual Results:

The third task fails with the the following error message:

`fatal: [127.0.0.1] => One or more undefined variables: 'unicode object' has no attribute 'msg'`
