### ISSUE TITLE
Yum module can't seem to put the path to .rpm file together

### ISSUE THREAD

**Issue by dfederlein** [ansible/ansible#8941]
##### Issue Type:

when specifying local rpm files, the path seems mangled when using with_items
##### Ansible Version:

1.7.1
##### Environment:

EL6/Ubuntu 14.04
##### Summary:

Possibly a simple string concatenation problem?
##### Steps To Reproduce:

```
- hosts: foo
  vars:
    some_path: /tmp
  tasks:
    yum: name={{ some_path }}/{{ item }} state=present
    with_items:
    - foo.rpm
    - bas.rpm
    - bar.rpm 
```
##### Expected Results:

RPMs get installed from path
##### Actual Results:

Errors and doom.
