### ISSUE TITLE
Fact Caching Bug with register/set_fact and accessing hostvars from other hosts

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#8944]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
##### Environment:

Control: Mac OS, virtualenv, python 2.7.5

Target: N/A
##### Summary:

When registering the results of a module, trying to access the registered var from another host fails.  This is without any fact caching mechanism defined.

git bisect leads to: aa419044c45e5227710b95fc5ddaaf3abb018f03
##### Steps To Reproduce:
1. Use an inventory with at least 2 hosts
2. Run the following playbook

```
test01 ansible_ssh_host=127.0.0.1 ansible_connection=local
test02 ansible_ssh_host=127.0.0.1 ansible_connection=local
```

```

---
- hosts: all
  tasks:
    - command: echo bar
      register: foo
    - assert:
        that: hostvars[play_hosts[0]].foo is defined
```
##### Expected Results:

Both hosts should have access to each others previously registered vars.

```
ok: [test01] => {"msg": "all assertions passed"}
ok: [test02] => {"msg": "all assertions passed"}
```
##### Actual Results:

The hosts do not appear to have access to each others vars

```
ok: [test01] => {"msg": "all assertions passed"}
failed: [test02] => {"assertion": "hostvars[play_hosts[0]].foo is defined", "evaluated_to": false, "failed": true}
```
