### ISSUE TITLE
Bug with dynamic playbook includes?

### ISSUE THREAD

**Issue by jclark360** [ansible/ansible#8947]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

Ubuntu 12.04 LTS
##### Summary:

Prior to 1.7 of ansible we could do something like the example below.  The reason we used this type of dynamic playbook include was to bake ec2 images with different playbooks

Usage example:
- create instance in ec2
- include playbook passed in through console variable to build up image
- create image
- destroy instance

Bug example:
- hosts: all
- include: "{{ playbook_name }}"

However currently this throws an exception:
##### Steps To Reproduce:

Create a playbook with this in it and then run it.
- hosts: all
- include: "{{ playbook_name }}"
##### Expected Results:

That ansible includes the playbook...
##### Actual Results:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 191, in main
    force_handlers=options.force_handlers
  File "/Library/Python/2.7/site-packages/ansible/playbook/**init**.py", line 180, in **init**
    (self.playbook, self.play_basedirs) = self._load_playbook_from_file(playbook, vars)
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 271, in _load_playbook_from_file
    inc_vars, inc_path = self._get_include_info(play, basedir, play_vars)
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 210, in _get_include_info
    (k,v) = t.split("=", 1)
ValueError: need more than 1 value to unpack

**Comment by mpdehaan** [comment]
"include playbook passed in through console variable to build up image"

Can you specify how this was passed in in this case and also indent the playbook example above so we can see how you have it formatted?

Thanks!

**Comment by mpdehaan** [comment]
(I would obviously agree that a traceback is always a bug, but I want to make sure we know how to replicate this - it does look like maybe your syntax is a little interesting... maybe, but that's not an excuse for a traceback)

**Comment by jclark360** [comment]
Example:

``` yml
- hosts: all

- include: "{{ playbook_name }}"
```

Command: ansible-playbook example.yml -i hosts --extra-vars="playbook_name=foo.yml"

Here is a complete example of how we wanted to use a dynamic playbook include:

``` yml
  - hosts: local
    connection: local
    gather_facts: false
    tasks:
      - local_action:
          module: ec2
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          group: "{{ security_groups }}"
          instance_type: "{{ instance_size | default('m3.medium') }}"
          region: "{{ aws_region | default('us-east-1') }}"
          image: ami-a49665cc
          count: 1
          instance_tags:
              Group: Staging
              Name: "{{ instance_name | default('base-image-creation') }}"
              Type: Development
              Usage: Staging
              Environment: Development
          wait: true
        register: ec2
      - name: Add new instance to host group
        local_action: add_host name={{ item.public_ip }} groups=launched
        with_items: ec2.instances
      - name: Wait for SSH to come up
        local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
        with_items: ec2.instances

  - include: "{{ playbook }}"

  - hosts: launched
    gather_facts: True
    sudo: True
    tasks:
      - ec2_facts:

  - hosts: launched
    connection: local
    gather_facts: false
    tasks:
      - local_action:
          module: ec2_ami
          region: "{{ aws_region | default('us-east-1') }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          instance_id: "{{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}"
          wait: yes
          name: '{{ image_name }}_{{ ansible_date_time.epoch }}'

      - local_action:
          module: ec2
          region: "{{ aws_region | default('us-east-1') }}"
          state: "absent"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          wait: True
          instance_ids: "{{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}"
```
