### ISSUE TITLE
[BUG?] Ansible unarchive behaves differently between running from Kitchen and running from Vagrant

### ISSUE THREAD

**Issue by cooniur** [ansible/ansible#8957]
## Ansible Version

1.7.1
## Environment

Mac 10.9.4
## Summary

Ansible unarchive behaves differently between running from Kitchen and running from Vagrant

When running from kitchen, it can successfully unpack the tar.gz file to a specified directory.
However, when running from vagrant, it fails with an error message "input file not found at (some location)", where the file does exist in that location though.

Here is my settings.
## ansible.cfg:

```
[defaults]
private_key_file=~/.vagrant.d/insecure_private_key
remote_user = vagrant
remote_tmp = $HOME/.ansible/tmp
sudo_user = root
timeout = 60
pipelining = True
```
## .kitchen.yml:

```

---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: app_servers
  require_ansible_repo: true
  ansible_verbose: false
  sudo: true

platforms:
  - name: centos-6.5
    driver_plugin: vagrant
    driver_config:
      box: chef/centos-6.5
      network:
      - ['forwarded_port', {guest: 8080, host: 9080}]
      - ['private_network', { ip: '10.0.34.11' } ]

suites:
  - name: default
    run_list:
    attributes:

busser:
    sudo: true
```
## Vagrantfile:

```
VAGRANTFILE_API_VERSION = "2"

vm_hostname = "appserver"
vm_memory = 2048

Vagrant.configure(VAGRANTFILE_API_VERSION) do |c|
    c.vm.define vm_hostname do |m|
        m.vm.box = "chef/centos-6.5"
        m.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"
        m.vm.hostname = vm_hostname

        m.vm.network(:private_network, {:ip=>"10.0.34.11"})

        m.vm.network(:forwarded_port, {:guest=>8080, :host=>9080})

        m.vm.synced_folder ".", "/vagrant", disabled: true

        m.vm.provider :virtualbox do |virtualbox|
            virtualbox.customize ["modifyvm", :id, "--memory", vm_memory]
            virtualbox.customize ["modifyvm", :id, "--name", vm_hostname]
        end # m.vm.provider

        m.vm.provision :ansible do |ansible|
            ansible.playbook = "../ansible/site.yml"
            ansible.inventory_path = "../ansible/hosts"
            ansible.sudo = true
            ansible.verbose = "vv"
            ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
        end
    end
end
```
## Ansible unarchive command:

```
- name: "---- Install Some Package..."
  unarchive:
    src="/tmp/some-package.tar.gz"
    dest="/usr/local/some-package-dir"
```

Hopefully it was just because there was something wrong with my settings. I used shell command "tar -xf {{ src_file }} --directory={{ dest_dir }}" instead, and it works for both kitchen and vagrant.
