### ISSUE TITLE
Feature Idea: Automatically tag each resource (e.g. play, role, task) with a default tag.

### ISSUE THREAD

**Issue by jgornick** [ansible/ansible#9010]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.7.1
##### Environment:

OS X 10.9.4
##### Summary:

For the following, I will only talk about tagging tasks. However, this could be applied to any resource (play, role, task) that can be tagged.

When you want to use tags to include **and** exclude specific tasks from a playbook, you need to use the --tags **and** --skip-tags options. However, the issue is that all of your tasks must be tagged. Would it make sense that every task declared is automatically tagged with a default tag. For the sake of this issue, let's say that tag is `default`.

An example:

My plays and roles are initially designed to be run against our environments in our data centers. When I want to use those same scripts for a Vagrant setup, there are certain tasks that I want to include **and** exclude. Just to reiterate, I don't tag all of my tasks. Currently, I can exclude tasks by assigning a tag like `skip-vagrant` and use `--skip-tags "skip-vagrant"`. However, when I want to also include a task, I can't simply tag it as `vagrant` and use `--tags "vagrant"` because Ansible won't run my other non-tagged tasks. If every task (i.e. resource) was automatically tagged with a default tag, I could include **and** exclude tasks using `--tags "default,vagrant" --skip-tags "skip-vagrant"`. This also prevents me from adding noise to my configurations with `tags: [default]` to every task.

**Comment by jgornick** [comment]
I forgot to mention that I understand there are other ways to handle a scenario like the one I've described. One of those is using a when statement on the specific tasks to include or exclude. The statement could look at the presence of a variable passed in as an extra variable (-e "is_vagrant=true") or adding all Vagrant hosts to the `vagrant` group and checking if the host is a Vagrant host.

I feel like using a when statement is semantically incorrect to include and exclude tasks. Tagging in Ansible is meant to include **and** exclude specific resources from running. The functionality already exists to do what I want to do, but it requires me to tag every resource. Like I said before, this just adds noise to my configurations.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

This feature has been proposed previously and has a PR in #7039, if you'd like to test that and comment there. We will close this issue as a duplicate.

If you have any further questions, please leave them on that issue, or let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jgornick** [comment]
Parts taken from https://github.com/ansible/ansible/pull/7039#issuecomment-56435828:

@jimi-c It doesn't appear that I described my proposal with enough detail, but let me see if I can summarize here:

In my proposal, every resource would automatically be tagged with "all", as it does right now. However, when a tag is specified on a resource, the automatic "all" tag is removed from the resource. This approach **overrides** the default tag assigned to the resource with the specified tag. Since the "all" tag is just a tag, you could still include the "all" tag in your overridden set of tags.

For example, if I have a set of resources tagged as:

```
  tasks:
    - name: "Task (default all)"
      command: "echo 'task:default-all'"

    - name: "Task (tagged all)"
      command: "echo 'task:tagged-all'"
      tags:
        - all

    - name: "Task (foo)"
      command: "echo 'task:foo'"
      tags:
        - foo

    - name: "Task (all, foo)"
      command: "echo 'task:all,foo'"
      tags:
        - all
        - foo

    - name: "Task (bar)"
      command: "echo 'task:bar'"
      tags:
        - bar

    - name: "Task (all, bar)"
      command: "echo 'task:all,bar'"
      tags:
        - all
        - bar

    - name: "Task (foo, bar)"
      command: "echo 'task:foo,bar'"
      tags:
        - foo
        - bar
```

The following is a list of acceptance criteria I would expect based the implementation I'm proposing:

**Command:** 

`ansible-playbook -i "127.0.0.1," -c local tag-test.yml`

**Expected Results:**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (default all)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (tagged all)] ***************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (all, foo)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (bar)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (all, bar)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

**Command:** 

`ansible-playbook -i "127.0.0.1," -c local --tags="all" tag-test.yml`

**Expected Results:**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (default all)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (tagged all)] ***************************************************** 
changed: [127.0.0.1]

TASK: [Task (all, foo)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (all, bar)] ******************************************************* 
changed: [127.0.0.1] 
```

**Command:** 

`ansible-playbook -i "127.0.0.1," -c local --tags="foo" tag-test.yml`

**Expected Results:**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (all, foo)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

**Command:** 

`ansible-playbook -i "127.0.0.1," -c local --tags="all,foo" tag-test.yml`

**Expected Results:**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (default all)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (tagged all)] ***************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (all, foo)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (all, bar)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

**Command:** 

`ansible-playbook -i "127.0.0.1," -c local --tags="foo" --skip-tags="all" tag-test.yml`

**Expected Results:**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

**Command:** 

`ansible-playbook -i "127.0.0.1," -c local --tags="all" --skip-tags="foo" tag-test.yml`

**Expected Results:**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (default all)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (tagged all)] ***************************************************** 
changed: [127.0.0.1]

TASK: [Task (all, bar)] ******************************************************* 
changed: [127.0.0.1]
```

This approach plays well with the current implementation of tagging.

**Comment by jgornick** [comment]
@jimi-c Because I'm proposing a different way of tagging resources, can this issue be re-opened?

**Comment by mpdehaan** [comment]
Hi,

I think your proposal would be the inverse of what is proposed in the other post, namely that people want to tag something with "all" to make sure it gets run even when _other_ tags are specified.

Also, it wouldn't make much sense to me to have to say "--tags=all" because that's effectively what leaving out --tags does really, it runs everything.   

As such, I think we need to go with the idea on the linked PR, and may be potentially confusing.
I'm hoping our reasoning is understandable in this one.

**Comment by jgornick** [comment]
@mpdehaan Thanks for looking into this. I can't help feel like I'm still missing something. I also feel like I'm not explaining my proposal correctly.

But, my proposal aside, I want to address the "all tag proposal". So, I **hear** the reason why "... people want to tag something with "all" to make sure it gets run even when other tags are specified.", but I don't understand **why** this is even a feature? I say this because you can already do this with Ansible.

Now hear me out, let's look at a playbook and some examples using the "all tag proposal" versus the way it can be done right now in Ansible:

**All Tag Playbook**

```
---
- name: Test Play for All Tags
  hosts: all
  gather_facts: no

  tasks:
    - name: "Task (default all)"
      command: "echo 'task:default-all'"

    - name: "Task (tagged all)"
      command: "echo 'task:tagged-all'"
      tags:
        - all

    - name: "Task (foo)"
      command: "echo 'task:foo'"
      tags:
        - foo

    - name: "Task (all, foo)"
      command: "echo 'task:all,foo'"
      tags:
        - all
        - foo

    - name: "Task (bar)"
      command: "echo 'task:bar'"
      tags:
        - bar

    - name: "Task (all, bar)"
      command: "echo 'task:all,bar'"
      tags:
        - all
        - bar

    - name: "Task (foo, bar)"
      command: "echo 'task:foo,bar'"
      tags:
        - foo
        - bar
```

**All Tag Playbook Test Cases**

**Run all tasks (tagged and untagged)**

`ansible-playbook -i "127.0.0.1," -c local tag-test.yml`

**Expect Results**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (default all)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (tagged all)] ***************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (all, foo)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (bar)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (all, bar)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

**Run tasks tagged with "all" and "foo"**

`ansible-playbook -i "127.0.0.1," -c local --tags="foo" tag-test.yml`

**Expect Results**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (tagged all)] ***************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (all, foo)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (all, bar)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

**Run tasks tagged with "foo"**

`ansible-playbook -i "127.0.0.1," -c local --tags="foo" --skip-tags="all" tag-test.yml`

**Expect Results**

```
PLAY [Test Play for All Tags] ************************************************* 

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (all, foo)] ******************************************************* 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

Ok, let's contrast that to what you can do right now in Ansible. I'm going to call this the "Always Tag Playbook" and the difference between this playbook and the "All Tag Playbook" is I switch the "all" tag with "always":

**Always Tag Playbook**

```
---
- name: Test Play for Always Tags
  hosts: all
  gather_facts: no

  tasks:
    - name: "Task (default all)"
      command: "echo 'task:default-all'"

    - name: "Task (tagged always)"
      command: "echo 'task:tagged-always'"
      tags:
        - always

    - name: "Task (foo)"
      command: "echo 'task:foo'"
      tags:
        - foo

    - name: "Task (always, foo)"
      command: "echo 'task:always,foo'"
      tags:
        - always
        - foo

    - name: "Task (bar)"
      command: "echo 'task:bar'"
      tags:
        - bar

    - name: "Task (always, bar)"
      command: "echo 'task:always,bar'"
      tags:
        - always
        - bar

    - name: "Task (foo, bar)"
      command: "echo 'task:foo,bar'"
      tags:
        - foo
        - bar
```

**Always Tag Playbook Test Cases**

**Run all tasks (tagged and untagged)**

`ansible-playbook -i "127.0.0.1," -c local tag-test.yml`

**Expect Results**

```
PLAY [Test Play for Always Tags] ********************************************** 

TASK: [Task (default all)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (tagged always)] ************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (always, foo)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (bar)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (always, bar)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

**Run tasks tagged with "always" and "foo"**

`ansible-playbook -i "127.0.0.1," -c local --tags="always,foo" tag-test.yml`

**Expect Results**

```
PLAY [Test Play for Always Tags] ********************************************** 

TASK: [Task (tagged always)] ************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (always, foo)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (always, bar)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

**Run tasks tagged with "foo"**

`ansible-playbook -i "127.0.0.1," -c local --tags="foo" tag-test.yml`

**Expect Results**

```
PLAY [Test Play for Always Tags] ********************************************** 

TASK: [Task (foo)] ************************************************************ 
changed: [127.0.0.1]

TASK: [Task (always, foo)] **************************************************** 
changed: [127.0.0.1]

TASK: [Task (foo, bar)] ******************************************************* 
changed: [127.0.0.1]
```

So, what's the difference?

In the first test test case, the command and **results are the same**. 

In the second test case, the command is different in the always scenario because we need to **explicitly** include the "always" tag. However, the **results are the same**.

In the third test case, the command is different in the all scenario because you need to skip the "all" tag. However, the **results are still the same**.

Back to the original point "... people want to tag something with "all" to make sure it gets run even when other tags are specified.". Based on these examples the benefit with the "all tag proposal" is in the second test, I don't need to specify the "all" tag. However, when I don't want to execute resources tagged with "all", I am required to skip the "all" tag. It's six of one and half a dozen of the other.

Here's my point as I said in the other issue:

> I feel that `ansible-playbook` should **not** assume what tagged resources I want to execute. I should have to explicitly specify them.

Ok, I'll stop beating the horse, which is beyond dead.
