### ISSUE TITLE
Add role paths to variables

### ISSUE THREAD

**Issue by malinoff** [ansible/ansible#9035]
Issue Type: Feature Idea

Ansible Version: 1.7.1

Environment: N/A

Summary: It is useful to have a path for specific role name as a variable within playbook. For example, if you need to specify path to specific file/template within a shell command. Such variable will be accessible only when `roles` directive was parsed.

Steps To Reproduce:
**example.yml** playbook:

``` yaml

---
- hosts: localhost
  roles: glassfish/build
```

**roles/glassfish/build/tasks/main.yml**:

``` yaml

---
- name: Build glassfish
  shell: "fpm -s dir -t rpm --name glassfish --version 4.0 --after-install {{ roles_path['glassfish/build'] }}/files/postinst.sh dir"
```

Expected Results: This variable will help to avoid using paths relative to inventory/playbook, or full paths, or using `copy` module to put file in a known location.

Actual Results: The only way to determine the file path is to copy it to a known location
