### ISSUE TITLE
route53 always thinks DNS entry has changed

### ISSUE THREAD

**Issue by sampierson** [ansible/ansible#9048]
##### Issue Type:

“Bug Report”, “Bugfix Pull Request”
##### Ansible Version:

devel + patches
ansible 1.8 (devel 48390eba24) last updated 2014/09/17 14:50:31 (GMT -700)
##### Environment:

What OS are you running Ansible from? Mac OS X
What OS are you managing?  Ubuntu 14.04 in EC2
##### Summary:

boto returns TTL values as strings. The route53 module is comparing them to integers, and thus thinks that the DNS entries are always different and updates them.
##### Steps To Reproduce:

Create DNS entry using route53 module.  Here's the that does that:

```
- name: Setup DNS record
  local_action:
    module: route53
    command: create
    overwrite: yes
    zone: omadahealth.net.
    type: CNAME
    record: "{{ inventory_hostname }}"
    value: "{{ ec2.tagged_instances[0].public_dns_name }}"
    ttl: 0
```
##### Expected Results:

```
TASK: [Setup DNS record] ****************************************************** 
ok: [sam-test-1.omadahealth.net -> 127.0.0.1]
ok: [sam-test-2.omadahealth.net -> 127.0.0.1]
```
##### Actual Results:

```
TASK: [Setup DNS record] ****************************************************** 
changed: [sam-test-2.omadahealth.net -> 127.0.0.1]
changed: [sam-test-1.omadahealth.net -> 127.0.0.1]
```
