### ISSUE TITLE
RFE: Shorthand syntax for 'delegate'

### ISSUE THREAD

**Issue by timlnx** [ansible/ansible#905]
I love that there is now `serial` and `delegate_to`! Would you accept code for making the common case of delegating to localhost `delegate_to: 127.0.0.1`, or some kind of configuration setting?

Perhaps, using the key with no value?

```
  - name: take out of load balancer pool
    action: command /usr/bin/take_out_of_pool $inventory_hostname
    delegate_to:
```

A 'vars' default?

```

---
- hosts: webservers
  vars:
    default_delegate: 127.0.0.1
  tasks:
  - name: take out of load balancer pool
    action: command /usr/bin/take_out_of_pool $inventory_hostname
    delegate_to:

# or (still with the vars set)
...
  tasks:
  - name: take out of load balancer pool
    delegated: command /usr/bin/take_out_of_pool $inventory_hostname
```

A 'local action' perhaps?

```
# ~/.ansible.cfg
DEFAULT_DELEGATE: localhost
...

# funtimeplaybook.yaml
...
  - name: take out of load balancer pool
    local_action: command /usr/bin/take_out_of_pool $inventory_hostname
```

Essentially, I'm looking for a way to minimize the amount of typing required. I've got potentially 200+ scripts I might port over to Ansible and setting a configuration value (the delegate host) so many times doesn't really follow the Don't Repeat Yourself mind-set.

So, what is the most Ansible-like syntax/style for doing this that you would accept into CORE?
