### ISSUE TITLE
Using `default` filter in role parameters ignores host variables

### ISSUE THREAD

**Issue by tahajahangir** [ansible/ansible#9071]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8-dev
##### Environment:

Host/remote OS: Ubuntu 14.04
##### Summary:

When using `foo: "{{ variable|default('bar') }}"` in role parameter, host variables is ignored. (The values is always bar)
##### Steps To Reproduce:

/hosts

```
127.0.0.1 variable=custom
```

/playbook.yml

```
- hosts: all
  roles:
    - role: arole
      foo: "{{ variable|default('bar') }}"
```

/roles/arole/tasks/main.yml

```
- debug: var=foo
```

and then run:

```
$ ansible-playbook -i hosts playbook.yml
```
##### Expected Results:

```
TASK: [arole | debug var=foo] ************************************************* 
ok: [127.0.0.1] => {
    "foo": "custom"
}
```
##### Actual Results:

```
TASK: [arole | debug var=foo] ************************************************* 
ok: [127.0.0.1] => {
    "foo": "bar"
}
```

Removing the `default` filter, or converting role parameter to play variable (like following code) fixes the problem.

```
- hosts: all
  vars:
    - foo: "{{ variable|default('bar') }}"
  roles:
    - role: arole
```
