### ISSUE TITLE
Problem with managing CentOS 5.x

### ISSUE THREAD

**Issue by blind-oracle** [ansible/ansible#9080]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8
##### Environment:

Debian 7 managing CentOS 5
##### Summary:

I've got latest Ansible from git with control machine on Debian and among managed hosts there are 2 CentOS hosts, which refuse to work with syntax error.

They have Python 2.4.3 with json module installed.
The same playbook works fine on Debian hosts with Python 2.7
##### Steps To Reproduce:

Try to run a following playbook on a CentOS 5 managed server:

```

---
- hosts: all
  remote_user: root

  tasks:
    - name: Update NTP config
      template: src=/etc/ansible/files/ntp.conf dest=/etc/ntp.conf
      notify:
        - restart ntp

  handlers:
    - name: restart ntp
      service: name=ntp state=restarted
```
##### Expected Results:

Ok
##### Actual Results:

Error:

```
failed: [10.2.200.190] => {"failed": true, "parsed": false}
  File "/root/.ansible/tmp/ansible-tmp-1411232120.58-121637091595063/file", line 342
    except SystemExit as e:
                       ^
SyntaxError: invalid syntax
```
