### ISSUE TITLE
No error reported on Nginx start/restart/reload failure

### ISSUE THREAD

**Issue by jooadam** [ansible/ansible#9108]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Controlling machine is Ubuntu 12.04, controlled is Ubuntu 14.04.
##### Summary:

Errors produced by syntactically invalid modifications to `nginx.conf` are not reported in playbook output on service start/restart/reload, the task is instead marked as `changed`. Probably this is not specific to Nginx.
##### Steps To Reproduce:

```
tasks:

- name:   nginx is installed
  action: apt name=nginx

- name:   nginx.conf is in place
  action: copy content='?.=x)@+!+!%+' dest=/etc/nginx/nginx.conf
  notify: restart nginx

handlers:

- name:   restart nginx
  action: service name=nginx state=restarted
```
##### Expected Results:

The handler reports an error.
##### Actual Results:

The handler reports a change.
