### ISSUE TITLE
when statements need to be propagated to role dependencies

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#9126]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1, and devel
##### Environment:

Debian 6/7
##### Summary:

When using playbooks with role based definitions, when statemements are not propagating to role dependencies defined in meta/main.yml
##### Steps To Reproduce:
# site.yml

```

---
 - hosts: 127.0.0.1
   connection: local

   roles:
     - { role: appserver,               when: "'APPSERVERS' in ansible_local.host_roles.roles" }
     - { role: hadoop_jobtracker, when: "'HADOOP_JOBTRACKER' in ansible_local.host_roles.roles" }
```
# roles/appserver/meta/main.yml

```

---
  dependencies:
    - { role: managed_interface, tags=initial }

# command line
ansible-playbook site.yml --tags "initial"
```
##### Expected Results:

```
PLAY [127.0.0.1] **************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [appserver | add pkg ifenslave] *****************************************
ok: [127.0.0.1]

TASK: [appserver | get vms] ***************************************************
changed: [127.0.0.1]

TASK: [appserver | get vms ip] ************************************************
changed: [127.0.0.1] => (item=appserver-vm1)

TASK: [appserver | test template] *********************************************
ok: [127.0.0.1]

TASK: [appserver | adding {{ item.item }} to /etc/hosts] **********************
ok: [127.0.0.1] => (item={u'stdout': u'10.10.126.27', u'changed': True, u'end': u'2014-09-24    12:45:16.183654', 'item': u'appserver-vm1', u'cmd': u"host appserver-vm1 | awk '{print $4}'", u'rc': 0,     u'start': u'2014-09-24 12:45:16.167779', u'stderr': u'', u'delta': u'0:00:00.015875', u'warnings': []})

TASK: [appserver | appserver packages] ****************************************
ok: [127.0.0.1] => (item=python-virtualenv)

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=5    changed=1    unreachable=0    failed=0
```
##### Actual Results:

The play errors out with tag:

```
 ansible-playbook site.yml --tags "initial"
ERROR: tag(s) not found in playbook: initial.  possible values: packages
```
