### ISSUE TITLE
tags typo in role dependencies not caught

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#9154]
#### Issue Type:

Bug Report
#### Ansible Version:

All versions
#### Environment:

Debian 6/7
#### Summary:

When using role dependencies, typos are not caught, and ultimately ignores the dependency:
#### Steps To Reproduce:

```
# site.yml

---
   - hosts: appserver
     connection: local
     sudo: yes

     roles:
       - appserver

# roles/appserver/meta/main.yml

---
dependencies:
  - { role: some_other_role, tags="initial" }

# roles/appserver/tasks/main.yml

---
- name: appserver packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: packages
  tags:
    - initial
    - packages
```
#### Expected Results:

 It should provide an error with parsing the role dependency, and utlimately will if there is nothing else tagged in the playbook role.
#### Actual Results:

```
$ ansible-playbook -i hosts  myrun.yml --tags "initial"

PLAY [appserver] **************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [appserver | appserver packages] ****************************************
ok: [127.0.0.1] => (item=python-virtualenv)

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0
```
