### ISSUE TITLE
yum state=present with with_items fails with conflict, while 'yum install ' works

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#9175]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Centos 6
##### Summary:

If you try to install `zabbix-server` and `zabbix-server-pgsql` package from the [official zabbix repository](http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm) with yum:

```
yum -y install zabbix-server zabbix-server-pgsql
```

It works without a problem, but if you do the same thing with Ansible:

```
- hosts: zabbix
  tasks:
    - yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present

    - yum: name={{ item }} state=present
      with_items:
        - zabbix-server
        - zabbix-server-pgsql
```

The task fails and reports:

```
Error: zabbix-server-mysql conflicts with zabbix-server-pgsql-2.4.0-1.el6.x86_64
Error: zabbix-server-pgsql conflicts with zabbix-server-mysql-2.4.0-1.el6.x86_64
```

I guess the reason for this is because zabbix-server depends on either `zabbix-server-mysql` or `zabbix-server-pgsql` and yum module tries to install one package at a time, so if it first installs `zabbix-server`, that package automatically installs `zabbix-server-mysql`, which later conflicts with `zabbix-server-pgsql`.

The workaround is very easy, you just have to only pass `zabbix-server-pgsql` to the yum module, since it will install `zabbix-server` as a dependency. The problem is that running a yum command with a list of packages doesn't work the same as the Ansible `yum` module with a list of packages passed using `with_items`. This means you will never know what will the module install, compared to the yum command, which is bad in my opinion.
##### Steps To Reproduce:

You can reproduce the bug, by just running the above playbook.
##### Expected Results:

It should install both packages.
##### Actual Results:

Only installs `zabbix-server` and the second package reports a conflict with `zabbix-server-mysql`, which was installed as a dependency for `zabbix-server-mysql`.
