### ISSUE TITLE
Bug Report: Accessing variables of other hosts does not work from j2 template

### ISSUE THREAD

**Issue by kosmodromov** [ansible/ansible#9260]
##### Issue Type:

Bug Report: Accessing variables of other hosts does not work from j2 template
##### Ansible Version:

ansible 1.7.2
##### Environment:

Running ansible from mac os mavericks, manage CentOS 7
##### Summary:

I can't get variables from other hosts from j2 template through {{hostvars[servers]['ansible_default_ipv4']['address']}} construction.

This is code from template.

```
{% if inventory_hostname in groups['haproxy_front'] %}
{% for servers in groups['front'] %}
    server  {{servers}} {{hostvars[servers]['ansible_default_ipv4']['address']}}:80 check
{% endfor %}
{% endif %}
```

Check this variables on hosts in 'front' group

```
ansible front -m setup |grep ansible_default_ipv4
        "ansible_default_ipv4": {
        "ansible_default_ipv4": {
```

Got this error when run playbook

```
fatal: [orion.host.ru] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
fatal: [orion.host.ru] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
```

Code from playbook

```
- name: Copy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
```
##### Steps To Reproduce:

---
##### Expected Results:

Get ip addresses from hosts in group 'front' with construction {{hostvars[servers]['ansible_default_ipv4']['address']}}
##### Actual Results:

```
fatal: [orion.host.ru] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
fatal: [orion.host.ru] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
```

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by soulmachine** [comment]
Today I bumped into this bug too. As follows:

```
- debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{ hostvars[inventory_hostname]["ansible_fqdn"] }} {{ hostvars[inventory_hostname]["ansible_hostname"] }}"
```

This line runs fine.

But if I put this line into a template, 

```
{% for host in groups['all'] %}
{{ hostvars[host]["ansible_default_ipv4"].address }} {{ hostvars[host]["ansible_fqdn"] }} {{ hostvars[host]["ansible_hostname"] }}
{% endfor %}
```

It will complain:

```
fatal: [us0701aopc172018080143] => {'msg': "One or more undefined variables: 'dict' object has no attribute 'ansible_default_ipv4'", 'failed': True}
```

My ansible version is 1.5.5, after I upgrade to 1.9, my template runs fine.

**Comment by drzraf** [comment]
Ansible 1.7.2: **bug** is here

**Comment by jaytaylor** [comment]
I am also running into this issue.

```
fatal: [a.b.c.d] => One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'
```

Code:

```
- name: "Build hosts file (cloud)"
  lineinfile: dest=/etc/hosts regexp=".*(?:{{ item }}|{{ hostvars[item].hostname }}).*$" line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].hostname }} {{ hostvars[item].hostname }}-{{ region_name }}.{{ domain_name }}" state=present
  with_items: groups["all"]
  when: (env is not defined or env != "lan") and hostvars[item].hostname is defined and hostvars[item].hostname != "" and item != inventory_hostname
  tags:
    - etc-hosts
```

Even when I have specified `gather_facts: yes` beforehand, this error still occurs.

My Ansible version is 1.9.0.

**_UPDATE**_

I narrowed the cause down to running `ansible-playbook` with `--limit host1,host2`.  When it is run this way, it appears that information about the other hosts is not available.

I don't think there is a real bug here per sé, it seems more likely to be a user expectation vs. reality impedance mismatch.

**Comment by drzraf** [comment]
I think it's a bug that ipv4/ipv6 of other hosts (and only these specific facts) aren't known.
Public ip are known from the inventory, or .ssh/config or even DNS requests, Ansible should provides this facts without having to "gather"" anything. About the other facts, well, that's another story (for which workaround alreadys exists like running a no-op task on said machines)

**Comment by jayunit100** [comment]
is this still a bug  ? I see it in 1.9?

**Comment by kosmodromov** [comment]
In my case it was my fault because before using facts you will need to take them from hosts. You may take them by running this code in beginning of your playbook.

```
- hosts: all
  tasks: []
```

**Comment by rk-git** [comment]
Why is this not a defect? How do I collect an attribute, say default IPv4 address, from each host to emit a configuration?

The "- host: all, tasks: []' method did not work as well.

Thanks,

Rk

**Comment by kosmodromov** [comment]
It works for me and I can get any available attribute from any host after that.

**Comment by ghost** [comment]
It works for me but I sophisticated a bit to be more usefull indeed

```
# Allow all host to be hitted even if nothing is executed
- hosts: all
  tasks:
     - name: Ping 
       ping:
```
