### ISSUE TITLE
an example in ansible doc does not work

### ISSUE THREAD

**Issue by h2suzuki** [ansible/ansible#9264]
##### Issue Type:

Bug Report (or possibly Documentation Report)
##### Ansible Version:
- ansible 1.7.1 (ansible-1.7.1-1.el7 or ansible-1.7-1.el6)
- ansible 1.7.2 (pip)

Both are tested.
##### Environment:
- CentOS7 running Ansible to manage CentOS7
- CentOS6.5 running Ansible to manage CentOS6.5

Both are tested.
##### Summary:

Ansible doc has the following example on [Task Include Files And Encouraging Reuse](http://docs.ansible.com/playbooks_roles.html#task-include-files-and-encouraging-reuse) page.  However, `remote_user` within include's vars does not take effect for the included tasks.

``` yaml
tasks:
  - include: wordpress.yml
    vars:
        remote_user: timmy
        some_list_variable:
          - alpha
          - beta
          - gamma
```
##### Steps To Reproduce:

Here is the site.yml to reproduce the issue.

``` yaml
--- # file: site.yml
- hosts: all
  tasks:

    # this remote_user works fine with a command task
    - name: direct whoami task
      command: whoami
      remote_user: testuser1
      register: result1

    - debug: var=result1.stdout

    # this ansible_ssh_user works, too
    - { include: included.yml, ansible_ssh_user: testuser1 }

    # this remote_user does not work
    - { include: included.yml, remote_user: testuser1 }
```

And the included playbook is here.

``` yaml
--- # file: included.yml
- name: included whoami task
  command: whoami
  register: result2

- debug: var=result2.stdout
```

Prepare testuser1 user on the remote host and the ssh connectivity to it so that the current ansibleman user can remote-login testuser1.  Then, run the following command from ansibleman user.

```
[ansibleman@localhost ~]$ ansible-playbook -i hosts site.yml
  --> from ansibleman@localhost to testuser1@remote
```
##### Expected Results:

If remote_user is effective, all output should show "testuser1" as the result of whoami command.

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [192.168.170.65]

TASK: [direct whoami task] ****************************************************
changed: [192.168.170.65]

TASK: [debug var=result1.stdout] **********************************************
ok: [192.168.170.65] => {
    "result1.stdout": "testuser1"
}

TASK: [included whoami task] **************************************************
changed: [192.168.170.65]

TASK: [debug var=result2.stdout] **********************************************
ok: [192.168.170.65] => {
    "result2.stdout": "testuser1"
}

TASK: [included whoami task] **************************************************
changed: [192.168.170.65]

TASK: [debug var=result2.stdout] **********************************************
ok: [192.168.170.65] => {
    "result2.stdout": "testuser1"
}

PLAY RECAP ********************************************************************
192.168.170.65             : ok=7    changed=3    unreachable=0    failed=0
```
##### Actual Results:

The last included case with remote_user is ignored.  Hence, whoami returns the current user.

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [192.168.170.65]

TASK: [direct whoami task] ****************************************************
changed: [192.168.170.65]

TASK: [debug var=result1.stdout] **********************************************
ok: [192.168.170.65] => {
    "result1.stdout": "testuser1"
}

TASK: [included whoami task] **************************************************
changed: [192.168.170.65]

TASK: [debug var=result2.stdout] **********************************************
ok: [192.168.170.65] => {
    "result2.stdout": "testuser1"
}

TASK: [included whoami task] **************************************************
changed: [192.168.170.65]

TASK: [debug var=result2.stdout] **********************************************
ok: [192.168.170.65] => {
    "result2.stdout": "ansibleman"   <==== THIS IS THE ISSUE
}

PLAY RECAP ********************************************************************
192.168.170.65             : ok=7    changed=3    unreachable=0    failed=0
```

I hope remote_user also works as documented on the web site.

**Comment by h2suzuki** [comment]
Another thought is that "ansible_ssh_user" is not appropriate wording for local connection.  So, "remote_user" is preferable to change the user for an set of included tasks.

So, I'm afraid that only hiding remote_user on the example does not resolve the real problem, which is why I reported it as a bug.

**Comment by bcoca** [comment]
remote_user is not a var but a directive

**Comment by bcoca** [comment]
so passing ansible_ssh_user works because it overrides the hostvar which has higher precedence.
remote_user cannot be passed as a var and work, it is a directive, part of the language. 

You can pass a myuser var and then template the remote_user in the included play/tasks.

```
tasks:
  - include: wordpress.yml
    vars:
        myuser: timmy
        some_list_variable:
```

and then have

```
- name: included whoami task
  command: whoami
  remote_user: "{{myuser}}"
  register: result2
```
