### ISSUE TITLE
Tags inside roles/includes don't behave as expected

### ISSUE THREAD

**Issue by ivanshaovchev** [ansible/ansible#9285]
If I have a role like this one:

```
roles:
  - {role: myrole, tags: ["foo", "bar"]}
```

And inside that role I have the following tasks:

```
- name: Install stuff  
   yum: name=python-devel  state=latest
   sudo: True
   tags:
     - foo

- name: Install more stuff  
  yum: name=python-dateutil  state=latest
  sudo: True
  tags:
     - bar
```

When the playbook is executed with a tag "foo", naturally one would expect only the task tagged with "foo" to be executed as per the description of tags: http://docs.ansible.com/playbooks_tags.html But the case is that both of the tasks are executed.
