### ISSUE TITLE
using variables in copy: content={{ foo }} duplicates linebreaks

### ISSUE THREAD

**Issue by a7p** [ansible/ansible#9306]
##### Issue Type:

Bug
##### Ansible Version:

ansible 1.7.2
##### Environment:

Macosx 10.9.5
##### Summary:

using variables assigned using "= | " in copy's content-option leeds to duplicated linebreaks
##### Steps To Reproduce:

```

---
- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  vars:
    testvar1: 'line1\nline2
    line3'
    testvar2: |
      line1
      line2

  tasks:
  - name: check out a git repository
    copy: content="hallo\nwelt" dest='./testfile.txt'
  - copy: content="{{ testvar1 }}" dest='./testfile1.txt'
  - copy: content="{{ testvar2 }}" dest='./testfile2.txt'
```
##### Expected Results:

testfile2.txt should contain:

```
line1
line2
```
##### Actual Results:

testfile2.txt contains:

```
line1

line2
```
