### ISSUE TITLE
Delegate_to with multi level depth vars

### ISSUE THREAD

**Issue by pierrefevrier** [ansible/ansible#9326]
Hi,

I'm facing a problem with 2 depth hostvars and delegate_to, as shown below:
- **Ansible version**
  1.8 (devel)
- **hosts**

```
[app-servers]
app-server-1 ansible_ssh_host=hostname1 ansible_ssh_user=user

[ngx-servers]
ngx-server-1 ansible_ssh_host=hostname2 ansible_ssh_user=user
```
- **group_vars**
  - ngx-servers

```
nginx_exec_command_base: "sudo /etc/init.d/nginx"
nginx_exec_command_reload: "{{ nginx_exec_command_base }} reload"
```
- **deploy.yml**

```
- hosts: app-server-1
  tasks:
  - shell: "{{ hostvars['ngx-server-1']['nginx_exec_command_reload'] }}"
    delegate_to: ngx-server-1
```
- **Play output**

```
PLAY [app-server-1] ***********************************************************

GATHERING FACTS ***************************************************************
<hostname1> ESTABLISH CONNECTION FOR USER: user
<hostname1> REMOTE_MODULE setup
<hostname1> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o ControlPath=/home/user/.ansible/cp/ansible-ssh-%h-%p-%r -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 hostname1 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'
ok: [app-server-1]

TASK: [shell {{ hostvars['ngx-server-1']['nginx_exec_command_reload'] }}] *****
<hostname2> ESTABLISH CONNECTION FOR USER: user
<hostname2> REMOTE_MODULE command {{ nginx_exec_command_base }} reload #USE_SHELL
<hostname2> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o ControlPath=/home/user/.ansible/cp/ansible-ssh-%h-%p-%r -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 hostname2 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'
failed: [app-server-1 -> ngx-server-1] => {"changed": true, "cmd": "{# nginx_exec_command_base #} reload", "delta": "0:00:00.015786", "end": "2014-10-13 17:44:48.171881", "rc": 127, "start": "2014-10-13 17:44:48.156095", "warnings": []}
stderr: /bin/sh: {{: command not found

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/user/deploy.retry

app-server-1               : ok=1    changed=0    unreachable=0    failed=1
```

It works with the following task command, which has one depth var (nginx_exec_command_base instead of nginx_exec_command_reload):

```
- hosts: app-server-1
  tasks:
  - shell: "{{ hostvars['ngx-server-1']['nginx_exec_command_base'] }} reload"
    delegate_to: ngx-server-1
```
