### ISSUE TITLE
Create a notify_when_failed feature

### ISSUE THREAD

**Issue by hahnicity** [ansible/ansible#9341]
##### Issue Type:

Feature Request
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

Create a notify_when_failed feature for triggering a handler when a task fails
##### Steps To Reproduce:

N/A
##### Expected Results:

The flow would look much nicer like this

```
- name: Check if server is started
  wait_for: port=80 timeout=0
  notify_when_failed:
   - server_started
```
##### Actual Results:

I have to create a hacky workaround for the same feature

```
- name: Check if server is started
  wait_for: port=80 timeout=0
  ignore_errors: yes
  register: server_started

- name: Start the server
  shell: "/bin/true"
  notify:
    - start server
  when: server_started|failed
```
