### ISSUE TITLE
Can with_subelements evaluate condition on each iteration?

### ISSUE THREAD

**Issue by thewebists** [ansible/ansible#9357]
I have the following task:

```
- name: Create external share dirs
  file: path={{item.1.1}}/{{ item.0.app_name }}
        state=directory
  with_subelements:
    - "{{ tws_sites | default({}) }}"
    - external_shares
  when: item.0.external_shares is defined
```

The task throws an error "could not find 'external_shares' key in iterated item" if external_shares is not defined in any one of the dictionary's elements.

I've tried the same code with the following evaluation and it still errors:

```
when: 1 == 0
```

Is there a better way of achieving this logic, or should the with_subelements be able to check the condition on each iteration before throwing exceptions?
