### ISSUE TITLE
Integers passed around using jinja variable references are converted to strings

### ISSUE THREAD

**Issue by feanil** [ansible/ansible#9362]
##### Summary:

In Ansible 1.6.9 a change was made that changed how the behavior of 'to_nice_json'.  Previously numbers being passed around as jinja variable references would be converted to numbers in the json output but now the numbers are returned as quoted.
##### Steps To Reproduce:

test.yml

```
- hosts: all
  gather_facts: False
  vars_files:
    - test_vars.yml
  tasks:
    - debug: msg="{{ Y }}"
    - debug: msg="{{ Y | to_json }}"
```

test_vars.yml

```
X: 4
Y:
  Z: "{{ X }}"
```

Command: `ansible-playbook test.yml -i localhost, -c local -vvv`
##### Expected Results:

Output from 1.6.8

```

PLAY [all] ******************************************************************** 

TASK: [debug msg="{'Z': u'4'}"] *********************************************** 
ok: [localhost] => {
    "msg": "{'Z': u'4'}"
}

TASK: [debug msg="{"Z": "4"}"] ************************************************ 
ok: [localhost] => {
    "msg": "{Z: 4}"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

```
##### Actual Results:

Output from 1.6.9

```

PLAY [all] ******************************************************************** 

TASK: [debug msg="{'Z': u'4'}"] *********************************************** 
ok: [localhost] => {
    "msg": "{'Z': u'4'}"
}

TASK: [debug msg="{"Z": "4"}"] ************************************************ 
ok: [localhost] => {
    "msg": "{\"Z\": \"4\"}"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

```

**Comment by feanil** [comment]
The same is true for Booleans I discovered and that is broken in 1.6.0  I would love to see this get a higher priority since it is preventing us from upgrading past 1.5.5.

**Comment by feanil** [comment]
Ok, thanks, in the case of your suggestion for the change above, it doesn't work because Y is actually a complex data structure which has an attribute that is an integer.

**Comment by jimi-c** [comment]
@feanil you can still do that: `somevar.whatever.should_be_an_integer|int`

**Comment by feanil** [comment]
Yes but the whole point of searializing the data structure as is that we don't have template out all of its content.  We can just add new vars to defaults and start using them during the ansible run and for the data that the application also needs, we serialize that to disk for it to reference.

**Comment by memelet** [comment]
So this is it? We can't create complex data (eg, marathon deploy) that contains non-string values? No workaround? This is pretty limiting.

**Comment by memelet** [comment]
Strange, it only applies to variables

```
  marathon_app:
    id: /svc/auth
    instances: 2
```

Yields an int value for instances after to_json.

```
  marathon_app:
    id: /svc/auth
    instances: "{{vi_instances | int}}"
```

But here instances is a string after to_json.

**Comment by memelet** [comment]
So this means for something line

```
- role: marathon_app
  marathon_app:
    id: /svc/auth
    cpus: 0.5
    mem: 64.0
    instances: "{{vi_instances | int}}"
    uris:
      - "{{dockercfg_uri}}"
    container:
      type: DOCKER
      docker:
        image: "systeminsights/ms-security-subjects:{{vi_version}}"
        network: BRIDGE
        dns: "{{consul_dns_ip}}"
        portMappings:
          - {containerPort: 3000, hostPort: 0}
        volumes:
          - {containerPath: /var/log/vimana, hostPath: /var/log/vimana}
```

Every value that needs to be an int needs to be hard coded.

**Comment by sdwr98** [comment]
@memelet We ran into the exact same issue.  I worked around it by breaking out my JSON information into a separate file and using the template command + file lookup to create JSON request bodies.  That mechanism allowed us to use variables for those integer/numeric values. 

I wrote about it more detail here: https://sdwr98.wordpress.com/2015/06/01/using-ansible-for-marathonchronos-deployments/

**Comment by memelet** [comment]
@sdwr98 Thanks Scott. Nice workaround. Did you try using lookup('template') and do away with the temporary file?

**Comment by sdwr98** [comment]
@memelet Cool! I didn't even see the template lookup.  That makes it even simpler.

**Comment by feanil** [comment]
A fix for this was merged in to devel last month.  It should be available in 2.0

https://github.com/ansible/ansible/pull/10465

There is a related PR for dealing with passing around nulls which has not been reviewed or merged yet.

https://github.com/ansible/ansible/pull/10957

**Comment by vcastellm** [comment]
This is broken for me in `2.1.0.0`

**Comment by simplesteph** [comment]
Any news on this or workarounds?

**Comment by shaharmor** [comment]
Still broken

**Comment by pablobm** [comment]
As I understand it, the mentioned PR (https://github.com/ansible/ansible/pull/10465) doesn't solve the problem at the root, but only one of its manifestations. It detects the case of a jinja2 template that only contains a single variable name, but this is not enough when the code is more complex and expected to evaluate as a non-string.

For those of you still having problems with this, I think it's the following you may be seeing: https://github.com/ansible/ansible/issues/18722

**Comment by alikins** [comment]
(Mentioning https://github.com/ansible/ansible/issues/17992 here to keep track of related issues)

**Comment by pzhuk** [comment]
still broken for me in 2.2.0.0

**Comment by alikins** [comment]
@simplesteph @shaharmor @pzhuk 

Post the playbooks that fail and the verbose output from the failed ansible-playbook invocation.
Aside from 'debug:' output, I'm curious what use case this causes failures on.

**Comment by pzhuk** [comment]
@alikins , my usecases are all about making a config dictionary in yaml, and than deploy them as json. So I found that some int vars are getting exposed in json with quotes like strings...

### **Test1** (typecasting string to int during variable exposure)

Playbook:
```
  vars:
    foo: '123'
    bar: 123
    config:
      foo: "{{ foo | int }}"
      bar: "{{ bar }}"

  tasks:
    - debug: msg="{{ config | to_json }}"
```
Result (variable foo, which was typecasted as int, still was exposed quoted like string. While actual int var called bar - exposed properly):
```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "{\"foo\": \"123\", \"bar\": 123}"
}
```


### **Test2** (variables which are pointing to int variables became strings!)

Playbook:
```
  vars:
    foo: 123
    bar: "{{ foo }}"
    config:
      bar_raw: "{{ bar }}"
      bar_int: "{{ bar|int }}"

  tasks:
    - debug: msg="{{ config | to_json }}"
```

Result (no way to expose bar variable as int, even though it's just pointing to a int var): 
```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "{\"bar_int\": \"123\", \"bar_raw\": \"123\"}"
}
```

**Comment by ryanwalls** [comment]
I would vote for reopening this until it is fixed, or a workaround is presented.  

Update:  Best workaround is from @sdwr98 above.  See https://github.com/ansible/ansible/issues/9362#issuecomment-107672910

**Comment by opennomad** [comment]
Just to embarrass myself I found that for my use case i can just brute force it with a `regex_replace`:

```yaml
{{ my_var | to_json | regex_replace('"([0-9]+)"','\1') }}
```

This appears to be working sufficiently for me when passing the output to other JSON aware tools that check on the type of things (awscli).

**Comment by alikins** [comment]
Some examples showing current behavior and what is desired (some of which currently doesnt work)

``` yaml
---
- hosts: localhost
  gather_facts: false
  vars:
    foo_string: '123'
    bar_int: 123
    config:
      foo2: "{{ foo_string | int }}"
      bar2: "{{ bar_int }}"

    foo_int: 123
    bar_string: "{{ foo_int }}"
    config2:
      bar_raw: "{{ bar_string }}"
      bar_int: "{{ bar_string|int }}"


  tasks:
    - name: debug foo_string type and value
      debug:
        msg: "foo_string value={{foo_string}} type={{foo_string | type_debug}}"

    - name: debug foo_string pipe int type and value
      debug:
        msg: "foo_string|int value={{foo_string|int}} type={{ foo_string| int| type_debug }}"

    - name: debug bar_int type and value
      debug:
        msg: "bar_int value={{bar_int }} type={{ bar_int|type_debug}}"

    - name: debug config.foo2 type and value
      debug:
        msg: "config.foo2 value={{config.foo2}} type={{config.foo2 | type_debug}}"

    - name: debug config.foo2 pipe int type and value
      debug:
        msg: "config.foo2|int value={{ config.foo2 | int }} type={{ config.foo2 | int | type_debug}}"

    - name: debug config.bar2 type and value
      debug:
        msg: "config.bar2 value={{ config.bar2 }} type={{ config.bar2 | type_debug }}"

    - name: config debug var
      debug:
        var: config

    - name: debug config to json
      debug:
        msg: "{{ config | to_nice_json }}"

    - name: config2 debug var
      debug:
        var: config2

    - name: debug config2 to json
      debug:
        msg: "{{ config2 | to_nice_json }}"

    - name: debug config2 to json and from json
      debug:
        msg: "{{ config2 | to_nice_json | from_json}}"

    - name: assert config.bar2 is an int 123 and not a string "123"
      assert:
        that:
            - config.bar2 == 123
      ignore_errors: true

    - name: assert config.bar2 is not a string "123"
      assert:
        that:
            - config.bar2 != "123"

    - name: assert config.foo2 is an int 123 and not a string "123"
      assert:
        that:
            - config.foo2 == 123
      ignore_errors: true

    - name: assert config.foo2 is not a string "123"
      assert:
        that:
            - config.foo2 != "123"
      ignore_errors: true

    - name: odd assert config.foo2 pipe int is an int 123 and not a string "123"
      assert:
        that:
            - '{{ config.foo2 | int }} == 123'
            - '{{ config.foo2 | int }} != 134323'
            - '"123" != {{ config.foo2 | int}}'
            - '"{{config.foo2 | int | type_debug}}" == "int"'

    - name: odd assert config2.bar_int is an int 123 and not a string "123"
      assert:
        that:
            - '{{ config2.bar_int| int }} == 123'
            - '"123" != {{ config2.bar_int | int}}'

    - name: assert config2.bar_int is an int 123 and not a string "123"
      assert:
        that:
            - config2.bar_int == 123
      ignore_errors: true

    - name: assert config2.bar_int is not a string "123"
      assert:
        that:
            - config2.bar_int != "123"
      ignore_errors: true

    - name: assert config2.bar_raw ais an int 123 and not a string "123"
      assert:
        that:
            - config2.bar_raw == 123
      ignore_errors: true

    - name: assert config2.bar_raw is not a string "123"
      assert:
        that:
            - config2.bar_raw != "123"
      ignore_errors: true
```

current output

```
[fedora-25:ansible (handle_future_builtins % u=)]$ ansible-playbook -vvv repro/jinja2_ints_as_strings_9362/test.yml
Using /home/adrian/.ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml *******************************************************************************************************************************************************************************************************************************************
1 plays in repro/jinja2_ints_as_strings_9362/test.yml

PLAY [localhost] *********************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [debug foo_string type and value] ***********************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:19
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "foo_string value=123 type=AnsibleUnicode"
}

TASK [debug foo_string pipe int type and value] **************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:23
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "foo_string|int value=123 type=int"
}

TASK [debug bar_int type and value] **************************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:27
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "bar_int value=123 type=int"
}

TASK [debug config.foo2 type and value] **********************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:31
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "config.foo2 value=123 type=unicode"
}

TASK [debug config.foo2 pipe int type and value] *************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:35
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "config.foo2|int value=123 type=int"
}

TASK [debug config.bar2 type and value] **********************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:39
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "config.bar2 value=123 type=int"
}

TASK [config debug var] **************************************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:43
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "config": {
        "bar2": 123, 
        "foo2": "123"
    }
}

TASK [debug config to json] **********************************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:47
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "{\n    \"bar2\": 123, \n    \"foo2\": \"123\"\n}"
}

TASK [config2 debug var] *************************************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:51
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "config2": {
        "bar_int": "123", 
        "bar_raw": "123"
    }
}

TASK [debug config2 to json] *********************************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:55
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "{\n    \"bar_int\": \"123\", \n    \"bar_raw\": \"123\"\n}"
}

TASK [debug config2 to json and from json] *******************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:59
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": {
        "bar_int": "123", 
        "bar_raw": "123"
    }
}

TASK [assert config.bar2 is an int 123 and not a string "123"] ***********************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:63
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [assert config.bar2 is not a string "123"] **************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:69
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [assert config.foo2 is an int 123 and not a string "123"] ***********************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:74
fatal: [localhost]: FAILED! => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "assertion": "config.foo2 == 123", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
...ignoring

TASK [assert config.foo2 is not a string "123"] **************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:80
fatal: [localhost]: FAILED! => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "assertion": "config.foo2 != \"123\"", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
...ignoring

TASK [odd assert config.foo2 pipe int is an int 123 and not a string "123"] **********************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:86
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [odd assert config2.bar_int is an int 123 and not a string "123"] ***************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:94
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [assert config2.bar_int is an int 123 and not a string "123"] *******************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:100
fatal: [localhost]: FAILED! => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "assertion": "config2.bar_int == 123", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
...ignoring

TASK [assert config2.bar_int is not a string "123"] **********************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:106
fatal: [localhost]: FAILED! => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "assertion": "config2.bar_int != \"123\"", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
...ignoring

TASK [assert config2.bar_raw ais an int 123 and not a string "123"] ******************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:112
fatal: [localhost]: FAILED! => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "assertion": "config2.bar_raw == 123", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
...ignoring

TASK [assert config2.bar_raw is not a string "123"] **********************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/jinja2_ints_as_strings_9362/test.yml:118
fatal: [localhost]: FAILED! => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "assertion": "config2.bar_raw != \"123\"", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
...ignoring
META: ran handlers
META: ran handlers

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=21   changed=0    unreachable=0    failed=0   

```
