### ISSUE TITLE
ignores dry run flag (--check) for template module when setting mode

### ISSUE THREAD

**Issue by gjuric** [ansible/ansible#9370]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
ansible 1.7.2
##### Environment:

OS X 10.9.5 (installed via homebrew)
##### Summary:

Ansible changes the remote system when playbook is being run with the "--check" flag.
##### Steps To Reproduce:

This feature used to work until I started adding tags and limits to the command. The command that ignores the "--check" flag looks like this:

```
ansible-playbook -i hosts play.yml --diff --check --limit=ONE-GROUP-NAME --tags=ONE-TAG --ask-vault-pass
```
##### Expected Results:

I expected that playbook will not actually change the remote system. I have noticed this while running the task that looks something like this:

```
- name: Action name
  template:
    src: template.src.j2
    dest: /remote/path/file.src
    group: group-name
    owner: owner-name
    mode: 0640
```
##### Actual Results:

Ansible applied the settings for group and owner from the action above.
