### ISSUE TITLE
Failed uploads to S3 bucket

### ISSUE THREAD

**Issue by mechcozmo** [ansible/ansible#9385]
##### Issue Type: Bug Report

Ansible fails to upload a file on the managed host to an S3 bucket.
##### Ansible Version: 1.7.2

```
$ansible --version
ansible 1.7.2
```

Installed from Homebrew
##### Environment:

I am running Ansible from Mac OS X 10.9.5, targeting EC2 instances running Amazon Linux (latest release, 2014.09)
##### Summary:

Ansible is failing to upload a file to an S3 bucket.  AWS credentials are specified in the command, and the file it is attempting to upload is visible in the CLI.

```
failed: [mcap2.censoredhostname.com] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1413820175.16-111146613354561/s3", line 2031, in <module>
    main()
  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1413820175.16-111146613354561/s3", line 390, in main
    pathrtn = path_check(src)
  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1413820175.16-111146613354561/s3", line 211, in path_check
    if os.path.exists(path):
  File "/usr/lib64/python2.6/genericpath.py", line 18, in exists
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found`
```
##### Steps To Reproduce:

I am using Ansible to capture the memory of EC2 instances and upload them to S3 with a series of plays.  The first two plays run without errors (provisioning instances, configuring instances).  The last play contains two tasks: 1) Run LiME to capture the memory image and 2) Upload the resulting file to S3

The failure occurs with the second task, when attempting to upload the file to S3.  While LiME must be run as root, the S3 upload does not have to be.  I have tried both ways of uploading content, and both end in failure.  The only difference is that when `sudo: true` is specified in the playbook, the failure output includes `invalid output was: SUDO-SUCCESS-hsuyekhqxevdebwqiylmgyxgixbozcwz` before the traceback.

Here is the play being run:

```
- hosts: memcaphosts
  user: ec2-user
  sudo: true

  tasks:
    - name: Run LiME
    command: /usr/sbin/insmod /home/ec2-user/bin/lime-3.14.20-20.44.amzn1.x86_64.ko "path=/home/ec2-user/{{ inventory_hostname_short }}.lime format=lime"

  - name: Upload memory capture to S3
    s3: bucket=memory-captures object=/home/ec2-user/{{ inventory_hostname_short }}.lime mode=put aws_access_key='[[[CENSORED]]]' aws_secret_key='[[[CENSORED]]]'
```
##### Expected Results:

I expect the S3 bucket 'memory-captures' to contain the memory images.  Each memory capture (for this instance size) is 4GB.
##### Actual Results:

What actually happens is Ansible crashes, leaving the files on-disk and unuploaded.
