### ISSUE TITLE
Dynamically loading vars from vars files based on ec2 variables broken by 313f26f

### ISSUE THREAD

**Issue by flibby-jibbit** [ansible/ansible#9411]
##### Issue Type:

Bug Report
##### Ansible Version:

``` bash
ansible 1.8 (devel c86851be2c) last updated 2014/10/23 22:35:42 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 7f611468a8) last updated 2014/10/23 22:36:35 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD a0df36c6ab) last updated 2014/10/23 22:36:35 (GMT -500)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/23 22:36:38 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/23 22:36:42 (GMT -500)
  configured module search path = None
```
##### Environment:

Management computer is OS X 10.9. Managing Ubuntu 12.04. Not sure it matters, though.
##### Summary:

Commit 313f26f866cec92e4dbe0e1d713a0ab0da647c98 fixed #9219, but causes a failure to properly merge variables dynamically loaded using ec2 variables.
##### Steps To Reproduce:

myplay.yml

``` yaml

---
- name: illustrate hash merge bug using module vars
  hosts: all

  vars_files:
    - myvars.yml
    - "{{ ec2_tag_Environment }}.yml"

  tasks:
    - name: inspect some_string
      debug: var=some_string
```

myvars.yml

``` yaml

---
some_string: 'this is the base value from myvars.yml'
```

myenv.yml

``` yaml

---
some_string: 'this is override value from myenv.yml'
```

and the command (1)

``` bash
$ ansible-playbook myplay.yml -i ec2.py -l 'tag_Environment_myenv'
```

(1) The command is purposefully abridged here for brevity.
##### Expected Results:

``` bash
TASK: [inspect some_string] ***************************************************
ok: [xxx.xxx.xxx.xxx] => {
    "some_string": "this is override value from myenv.yml"
}
```
##### Actual Results:

``` bash
TASK: [inspect some_string] ***************************************************
ok: [xxx.xxx.xxx.xxx] => {
    "some_string": "this is the base value from myvars.yml"
}
```
