### ISSUE TITLE
$item in task name

### ISSUE THREAD

**Issue by ernoaapa** [ansible/ansible#943]
In version: ansible 0.7 (devel 150a47c66c) 

In playbook:
- name: add user $item
  action: user name=$item state=present groups=wheel
  with_items: $somelist

It will output:
TASK: [add user $item] ********************\* 

Not the value of $item in $somelist

**Comment by mpdehaan** [comment]
This is not a bug, because the with_items logic expands inside the task, and no longer generates multiple tasks per item.

It will, depending on the module (yum and apt do not) still generate multiple internal SSH cycles.

**Comment by hayeah** [comment]
Let me describe my use case, perhaps there's a better way to go around this issue:

For my cron job setup, I do two things
1. Copy a cron script over from template to the destination.
2. Use cron module to setup invokation of the script.

Precisely, the tasks are partitioned out to a separate file, and included into the play,

```
# example play cron.yml
- tasks:
  - include tasks/cron.yml name="mysql-dump" args="minute=0 hour=4"
```

``` yaml
# tasks/cron.yml
- name: cron script ${name}
  template: src=cron/${name} dest=${cron_root}/${name} mode=0700
- name: setup cron ${name}
  cron: name=${name} user=deploy ${args}
        job="${cron_root}/${name}"
```

The "name" parameter is used to establish a convention so the template, the script, the cronjob all find things in the expected place.

It would be nice if there's a way so that the included tasks can have more descriptive names parameterized by variables.
