### ISSUE TITLE
module dnsmadeeasy. SSL error.

### ISSUE THREAD

**Issue by huguesalary** [ansible/ansible#9439]
##### Issue Type:

Bur report
##### Ansible Version:

`ansible 1.7.2`
##### Environment:

`Darwin 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64`
##### Summary:

the dnsmadeeasy module suddenly started to fail with the following error:

`failed: [localhost] => (item=www) => {"failed": true, "item": "www"}
msg: https://api.dnsmadeeasy.com/V2.0/dns/managed returned -1, with body: Request failed: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>`

Nothing has changed. Tried this on multiple computers, they all fail the same way. This makes me think that dnsmadeeasy (the company) may have changed something on their end (maybe they patched POODLE?).

It's worth noting that the dnsmadeeasy API is _working_ (I tested it).
##### Steps To Reproduce:

``` yml
- hosts: localhost
    - name: Create CNAME records in DNS
      dnsmadeeasy: account_key=thisisafakeaccountkey account_secret=thisisafakeaccountsecret validate_certs=no record_type=CNAME record_value=example.com. record_name=www.example.com domain=example.com record_ttl=60 state=present
```
##### Expected Results:

The output should be "ok"
##### Actual Results:

`failed: [localhost] => (item=www) => {"failed": true, "item": "www"}
msg: https://api.dnsmadeeasy.com/V2.0/dns/managed returned -1, with body: Request failed: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>`
