### ISSUE TITLE
Ansible su_pass doesn't transform variables

### ISSUE THREAD

**Issue by Flask** [ansible/ansible#9482]
When passing a variable to a task it does not get translated for su_pass.

Eg.

```

---
- hosts: server1
  vars:
    username: www-foobar
    password: foobar
  tasks:
    - name: test
      file: path=/home/www-foobar/testfile state=touch
      su: yes
      su_user: "{{ username }}"
      su_pass: "{{ password }}"
```

It passes  "{{ password }}" in ssh.py at `stdin.write(self.runner.su_pass + '\n')`

Ansible Version 1.7.2
