### ISSUE TITLE
add roles/x/tasks to the search path used to include task list files

### ISSUE THREAD

**Issue by olivier-heurtier** [ansible/ansible#9514]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.2
##### Environment:

N/A
##### Summary:

When including a task list file, the paths `roles/x/tasks` (where x is the name of a role used in the play) is not added.
For example, consider a role `as` containing instructions to setup an application server. This role could provide:
- `roles/as/tasks/main.yml` to install the application server
- `roles/as/tasks/deploy_app.yml` to deploy an application

It would be used from a playbook like in the following example:

```
- hosts: myserver
  roles:
  - as
  tasks:
  - include: deploy_app file=myapp1.war
  - include: deploy_app file=myapp2.war
```

In version 1.7.2, the full path to the included file must be specified, which gives something like:

```
  - include: /path_to_roles/as/tasks/deploy_app.yml file=myapp.war
```

In addition, this would make the documentation less ambiguous as it currently states:

> Any include tasks can reference files in roles/x/tasks/ without having to path them relatively or absolutely
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A
