### ISSUE TITLE
"file state=directory" silently skips if it's currently a file

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#9518]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.8 (devel 24bebd85b4) last updated 2014/11/08 17:09:34 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 6317d3a988) last updated 2014/11/08 17:15:30 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 5a514ccdda) last updated 2014/11/08 17:20:33 (GMT +000)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/08 17:25:52 (GMT +000)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/08 18:19:33 (GMT +000)
  configured module search path = /usr/share/ansible
##### Environment:

Ubuntu 14.04.1
##### Summary:

"file: path=xxx state=directory", if path xxx currently exists and is a file, silently does nothing as if xxx were already a directory.
##### Steps To Reproduce:

```
$ ansible host1.ws.nsrc.org -i hosts.local -u sysadm -skK -m copy -a 'src=/etc/lsb-release dest=/etc/foo'
SSH password:
sudo password [defaults to SSH password]:
host1.ws.nsrc.org | success >> {
    "changed": true,
    "checksum": "c4079be4e41af8bbe0ef2bfcf6a9640df22a1531",
    "dest": "/etc/foo",
    "gid": 0,
    "group": "root",
    "md5sum": "30c373a51f59c87d55f6e03c946d2962",
    "mode": "0644",
    "owner": "root",
    "size": 105,
    "src": "/home/sysadm/.ansible/tmp/ansible-tmp-1415471726.25-223448372374598/source",
    "state": "file",
    "uid": 0
}

$ ansible host1.ws.nsrc.org -i hosts.local -u sysadm -skK -m file -a 'path=/etc/foo state=directory'
SSH password:
sudo password [defaults to SSH password]:
host1.ws.nsrc.org | success >> {
    "changed": false,
    "gid": 0,
    "group": "root",
    "mode": "0644",
    "owner": "root",
    "path": "/etc/foo",
    "size": 105,
    "state": "file",
    "uid": 0
}
```

(Note: this result is in green text, and says "success"). But it clearly hasn't worked:

```
$ ansible host1.ws.nsrc.org -i hosts.local -u sysadm -skK -m shell -a 'ls -l /etc/foo'
SSH password:
sudo password [defaults to SSH password]:
host1.ws.nsrc.org | success | rc=0 >>
-rw-r--r-- 1 root root 105 Nov  8 18:35 /etc/foo
```
##### Expected Results:

Either that the file would be deleted and replaced with a directory, or that an error would be returned saying that this is not possible.
##### Actual Results:

The current result (success, changed=false) looks like the path is already a directory, which is untrue.

**Comment by sysadmin75** [comment]
Wasn't sure how to add the pull request from the new repo.
https://github.com/ansible/ansible-modules-core/pull/375

**Comment by sysadmin75** [comment]
My previous pull request was done on the devel branch. this new PR was done using a new branch.
https://github.com/ansible/ansible-modules-core/pull/505

**Comment by abadger** [comment]
new PR merged.  thanks again for the fix!

**Comment by redbaron** [comment]
This fix breaks the case when path is a symlink to the directory:

```
- hosts: all
  gather_facts: no
  tasks:
    # prepare
    - file: path=/tmp/dir state=directory
    - file: path=/tmp/link src=/tmp/dir state=link


    # master branch now breaks on following, 
    - file: path=/tmp/link state=directory follow=yes
    # this one used to work incorrectly with 1.8.2 because with default follow=no value it should fail
    # as the path in question is a symlink, not a dir
    - file: path=/tmp/link state=directory
```

Invoke like following:

```
ansible-playbook -c local -i '127.0.0.1,' test_dir_symlink.yml 
```

Output I got with current master:

```
PLAY [all] ******************************************************************** 

TASK: [file path=/tmp/dir state=directory] ************************************ 
ok: [127.0.0.1]

TASK: [file path=/tmp/link src=/tmp/dir state=link] *************************** 
ok: [127.0.0.1]

TASK: [file path=/tmp/link state=directory follow=yes] ************************ 
failed: [127.0.0.1] => {"failed": true, "gid": 100, "group": "users", "mode": "0777", "owner": "rossmohax", "path": "/tmp/link", "size": 8, "state": "link", "uid": 1000}
msg: /tmp/link already exists as a link

FATAL: all hosts have already failed -- aborting
```
