### ISSUE TITLE
vars_prompt private logging - feature

### ISSUE THREAD

**Issue by bputt** [ansible/ansible#9531]
##### Summary:

For some of my scripts, I am asking for some "protected" information from the user(passwords..etc) that are applied to configuration files. I am using the replace module that has the with_items portion. Each item is logged to the screen and it would be beneficial for the logged item to be XXX'd out if private was set to yes.
##### Steps To Reproduce:

```
- name: Replace config items
  replace: dest="/somefile" regexp="{{ item.regexp }}" replace="{{ item.replace }}"
  with_items:
    - { regexp: '^\s*someprop.password=', replace: 'someprop.password={{ var_prompted }}' }
```
##### Expected Results:

```
changed: [server] => (item={'regexp': u'^\s*someprop.password=', 'replace': u'someprop.password=XXXX'})
```
##### Actual Results:

```
changed: [server] => (item={'regexp': u'^\s*someprop.password=', 'replace': u'someprop.password=some_password'})
```
