### ISSUE TITLE
INCLUDE: It doesn't expand variables within its name/location

### ISSUE THREAD

**Issue by v1v** [ansible/ansible#9533]
**Issue Type:**  “Bug Report”

**Ansible Version**: ansible 1.7.2

**Environment:** MacOSX

**Summary:**

I´ve tried to use {{ ansible_distribution }} In order to execute tasks dynamically depending on the operating system but it doesn't expand the variables.

**Steps To Reproduce:**

_Create defaults/main.yml_

``` yaml
type: package
```

_Create hosts_

``` yaml
localhost
```

_Create site.yml_

``` yaml
- hosts: all
  vars_files:
    - 'defaults/main.yml'
  tasks:
    - include: 'tasks/main.yml'
```

_Create tasks/main.yml_

``` yaml

---
- include: "install_{{ type }}.yml"
```

_Create tasks/install_package.yml_

``` yaml

---
- include: "{{ type }}_{{ ansible_distribution }}.yml"
```

_Create tasks/package_MacOSX.yml_

``` yaml

---
- name: MacOSX | Set metadata facts
  set_fact:
    platform: "mac_os_x"
    version: "latest"
    installer_dest: "/tmp/{{ version }}.dmg"
```

_Create tasks/package_Centos.yml_

``` yaml

---
- name: Centos | Set metadata facts
  set_fact:
    platform: "centos"
    version: "17.5.0"
    installer_dest: "/tmp/{{ version }}.deb"
```

_Create tasks/package_Ubuntu.yml_

``` yaml

---
- name: Ubuntu | Set metadata facts
  set_fact:
    platform: "ubuntu"
    version: "16.0.0"
    installer_dest: "/tmp/{{ version }}.deb"
```

**Results:**

```
$ ansible-playbook -i hosts site.yml --connection=local -vv
ERROR: file could not read: /Users/v1v/Workspaces/github/ansible-role/tasks/{{ type }}_{{ ansible_distribution }}.yml
```

It doesn't expand those variables, is this a bug?
