### ISSUE TITLE
Problem with {{ item }} concatenation in use with with_items directive

### ISSUE THREAD

**Issue by decayofmind** [ansible/ansible#9552]
Hi! Let's have a playbook like these:

``` yaml
- hosts: all
  sudo: yes
  tasks:
    - name: Reproduce items bug
      yum: name=nagios-plugins-{{ item }} state=present
      with_items:
        - dhcp
        - disc
        - dummy
```

and if you run this playbook, you can see an error:

> failed: [mylovelyhost] => (item=dhcp,disc,dummy) => {"changed": false, "failed": true, "item":  "dhcp,disc,dummy", "rc": 0, "results": ["nagios-plugins-dhcp-1.4.16-10.fc20.x86_64 providing nagios-plugins-dhcp is already installed"]}
> msg: No Package matching 'disc' found available, installed or updated

So, string concatenation with {{ item }} variable in with_items cycle will only work for the first step. For next steps only pure {{ item }} will sended.
