### ISSUE TITLE
spaces in with_items object

### ISSUE THREAD

**Issue by Gerst20051** [ansible/ansible#9557]
any ideas as to allow spaces?

failed: [192.168.111.111] => (item={'job': u'curl -k https://localhost/mobile/api/index.php/flattentransactions >> /home/vagrant/logs/flattenlog', 'weekday': '_', 'name': 'flatten', 'hour': '_', 'day': '_', 'minute': '10,25,40,55', 'month': '_'}) => {"failed": true, "item": {"day": "_", "hour": "_", "job": "curl -k https://localhost/mobile/api/index.php/flattentransactions >> /home/vagrant/logs/flattenlog", "minute": "10,25,40,55", "month": "_", "name": "flatten", "weekday": "_"}}

msg: this module requires key=value arguments (['name=flatten', 'minute=10,25,40,55', 'hour=_', 'day=_', 'month=_', 'weekday=_', 'job=curl', '-k', 'https://localhost/mobile/api/index.php/flattentransactions', '>>', '/home/vagrant/logs/flattenlog'])

```
- name: add cronjobs
  cron: name={{ item.name }} minute={{ item.minute }} hour={{ item.hour }} day={{ item.day }} month={{ item.month }} weekday={{ item.weekday }} job="{{ item.job }}"
  with_items:
    - { name: flatten, minute: "10,25,40,55", hour: "*", day: "*", month: "*", weekday: "*", job: "curl -k https://localhost/mobile/api/index.php/flattentransactions >> /home/{{ remote_user }}/logs/flattenlog" }
```
