### ISSUE TITLE
with_ is not evaluating jinja2 expressions withouth '{{ }}'

### ISSUE THREAD

**Issue by Ernest0x** [ansible/ansible#9609]
_Issue Type:_
Bug Report

_Ansible Version:_
ansible 1.8 (devel 116109468c) last updated 2014/11/24 21:06:08 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 19b328c4df) last updated 2014/11/24 21:05:39 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD e64751b0eb) last updated 2014/11/24 21:05:40 (GMT +300)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/24 21:06:56 (GMT +300)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/24 21:07:01 (GMT +300)
  configured module search path = /usr/share/ansible

_Environment:_
Archlinux

_Summary:_
with_subelements fails when giving it a list of dicts passed through some jinja2 filter.

_Steps To Reproduce:_

```
 # inventory
 users:
   - name: someuser
     password: somepass
     authorized_keys:
       - ssh_public_keys/key1.pub
       - ssh_public_keys/key2.pub
   - name: anotheruser
     password: anotherpass

 # playbook task
 - name: Add authorized keys for users
   authorized_key: user="{{ item.0.name }}" key="{{ lookup('file', item.1) }}"
   with_subelements:
     - users|rejectattr("authorized_keys", "undefined")|list
     - authorized_keys
   tags:
     - users
```

_Expected Results:_
I expect it to work as it works on 1.7.x.

_Actual Results:_
Gives the error: 

```
 subelements lookup expects a dictionary, got 'users|rejectattr("authorized_keys", "undefined")|list'
```

**Comment by ansibot** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot. 

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!. 

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.  

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.  

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by udondan** [comment]
This should be higher prioritized. It looks like all lookup plugins (if not everything related to dicts) are broken.

Instead of passing the value of a dict, a string is passed to the plugin. In the above case the passed `terms` are: `['users|rejectattr("authorized_keys", "undefined")|list', 'authorized_keys']`

Confirming this was introduced in Ansible 1.8. It was working in 1.7.x

**Comment by bcoca** [comment]
can you test in current devel? there have been a few patches affecting lookup behavior that might account for this already

**Comment by udondan** [comment]
OK, just did that. Unfortunately the development branch has the same problem.

**Comment by udondan** [comment]
Here is another example, showing the problem applies as well to lists used with `with_itmes`:

Playbook:

``` yml
---

- hosts: localhost
  vars:
    some_list:
      - a
      - a
      - a

  tasks:
    - debug: var=item
      with_items: some_list | unique

...
```

Called with Ansible 1.7.2:

```
$ ansible-playbook -i blah test.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug var=item] ******************************************************** 
ok: [localhost] => (item=a) => {
    "item": "a"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0 
```

Called with Ansible 1.8.1+ (current devel branch):

```
$ /tmp/ansible/bin/ansible-playbook -i blah test.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug var=item] ******************************************************** 
ok: [localhost] => (item=some_list | unique) => {
    "item": "some_list | unique"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
