### ISSUE TITLE
sudo_user in task should imply sudo: True in task? [edited description]

### ISSUE THREAD

**Issue by eovolkov** [ansible/ansible#9616]
HI,
I had some problems with sudo_user switching. Config file not changed.
ansible 1.7.2
Server: Linux Mint 17
Remote host: Ubuntu Server 14.04 LTS

test.yml

```

---
- hosts: test_host.local
  remote_user: notroot
  tasks:
  - name: test1
    sudo_user: test
    shell: whoami

  - name: test2
    sudo: yes
    sudo_user: test
    shell: whoami
```

---

```
ansible-playbook test.yml -v

PLAY [test_host.local] *****************************

GATHERING FACTS ***************************************************************
ok: [test_host.local]

TASK: [test1] *****************************************************************
changed: [test_host.local] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.002587", "end": "2014-11-24 15:41:03.876659", "rc": 0, "start": "2014-11-24 15:41:03.874072", "stderr": "", "stdout": "notroot"}

TASK: [test2] *****************************************************************
changed: [test_host.local] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.002617", "end": "2014-11-24 15:41:04.847170", "rc": 0, "start": "2014-11-24 15:41:04.844553", "stderr": "", "stdout": "root"}

PLAY RECAP ********************************************************************
test_host.local : ok=3    changed=2    unreachable=0    failed=0
***********************************************************
```

In docs, I saw this example:
http://docs.ansible.com/playbooks_intro.html

```
You can also login as you, and then sudo to different users than root:
```

```
    ---
    - hosts: webservers
      remote_user: yourname
      sudo: yes
      sudo_user: postgres
```

But as you see it's not quite right.

Help please. How can i execute command under specific user, not root end not remote user?

**Comment by abadger** [comment]
@eovolkov, to be clear, from the docs you expected the first task to be notroot (which it was) and the second task to be test (which it was not).  Correct?

**Comment by abadger** [comment]
I've just executed your playbook on both ansible-1.7.2 and the devel branch with fedora20 to fedora20 and was unable to reproduce.  Here's my slightly modified playbook:

```
- hosts: fedora20-fips
  remote_user: testuser2
  tasks:
  - name: test1
    sudo_user: testuser3
    shell: whoami

  - name: test2
    sudo: yes
    sudo_user: testuser3
    shell: whoami
```

And my output:

```
$  ansible-playbook sudo-test.yml -v -K                       (09:25:24)
sudo password: 

PLAY [fedora20-fips] ********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [fedora20-fips]

TASK: [test1] ***************************************************************** 
changed: [fedora20-fips] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.002877", "end": "2014-11-25 09:25:30.248956", "rc": 0, "start": "2014-11-25 09:25:30.246079", "stderr": "", "stdout": "testuser2"}

TASK: [test2] ***************************************************************** 
changed: [fedora20-fips] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.004525", "end": "2014-11-25 09:25:30.541902", "rc": 0, "start": "2014-11-25 09:25:30.537377", "stderr": "", "stdout": "testuser3"}

PLAY RECAP ******************************************************************** 
fedora20-fips              : ok=3    changed=2    unreachable=0    failed=0 
```

which is what I expect from the docs.  If this is what you're trying to accomplish as well, we should probably take this to the mailing list to see if we can figure out what's different about your environment.
