### ISSUE TITLE
apt module issue when adding more items to `with_items`

### ISSUE THREAD

**Issue by mattupstate** [ansible/ansible#962]
Say I run the following task on a remote host:

``` yaml
- name: install postgres packages
      action: apt pkg=$item state=installed
      with_items:
        - postgresql
        - libpq-dev
```

And I change it to the following later on:

``` yaml
- name: install postgres packages
      action: apt pkg=$item state=present
      with_items:
        - postgresql
        - libpq-dev
        - python-dev
        - python-psycopg2
```

And then run it again against my remote host the additional packages are not installed

**Comment by mpdehaan** [comment]
I'll see if I can get some Debian/Ubuntu folks to look at this -- unless you want to?

**Comment by mpdehaan** [comment]
you may want to ask the list if you're not going to try and hit this yourself.   I mostly use a CentOS setup.

**Comment by marktheunissen** [comment]
I'll give it a go.

**Comment by mpdehaan** [comment]
excellent.

**Comment by marktheunissen** [comment]
Can't reproduce.

System: Ubuntu 12.04

Playbook used:

```
---
- hosts: all
  user: root
  tasks:
    - name: install postgres packages
      action: apt pkg=$item state=installed
      with_items:
        - postgresql
        - libpq-dev
        - python-dev
        - python-psycopg2
```

Output:

frontiers [~]# ansible-playbook -c local test.yml

PLAY [all] ********************\* 

GATHERING FACTS ********************\* 
ok: [127.0.0.1]

TASK: [install postgres packages] ********************\* 
ok: [127.0.0.1] => (item=postgresql,libpq-dev)

PLAY RECAP ********************\* 
127.0.0.1                      : ok=2    changed=1    unreachable=0    failed=0    

frontiers [~]# nano test.yml
frontiers [~]# ansible-playbook -c local test.yml

PLAY [all] ********************\* 

GATHERING FACTS ********************\* 
ok: [127.0.0.1]

TASK: [install postgres packages] ********************\* 
[ok: [127.0.0.1] => (item=postgresql,libpq-dev,python-dev,python-psycopg2)

PLAY RECAP ********************\* 
127.0.0.1                      : ok=2    changed=1    unreachable=0    failed=0
