### ISSUE TITLE
set_fact facts don't work in handler names

### ISSUE THREAD

**Issue by raags** [ansible/ansible#9628]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

N/A
##### Summary:

I'm not able to use facts set using the set_fact module in handler names. Dynamic handler names don't seem to work with facts, but work with variables set in "vars".
##### Steps To Reproduce:

``` yaml

---
- name: Test Playbook
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
   - set_fact:
       test_fact: test
   - command: echo hello
     notify: "{{test_fact}}-handler"
  handlers:
    - name: test-handler
      debug: msg="fired fact handler"
```
##### Expected Results:

``` shell
PLAY [Test Playbook] **********************************************************

TASK: [command echo hello] ****************************************************
changed: [localhost]

NOTIFIED: [test-handler] ******************************************************
ok: [localhost] => {
    "msg": "fired fact handler"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```
##### Actual Results:

``` shell
PLAY [Test Playbook] **********************************************************

TASK: [set_fact ] *************************************************************
ok: [localhost]

TASK: [command echo hello] ****************************************************
changed: [localhost]
ERROR: change handler ({{test_fact}}-handler) is not defined
```
