### ISSUE TITLE
mysql_user module doesn't add 'GRANT' privilege assigned to the user

### ISSUE THREAD

**Issue by pshanbhag** [ansible/ansible#9633]
##### Issue Type:

 Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.8
  configured module search path = None
##### Environment:

CentOS 6.5
##### Summary:

mysql_user module cannot provide GRANT OPTION to the database user.
##### Steps To Reproduce:

 Our ansible playbooks worked with an invocation of the module as below:

```
  mysql_user:
    name: "foo"
    password: "bar"
    priv: "*.*:ALL,GRANT"
    state: present
    host: "%"
    login_host: "{{ db_host }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
```

This is based off the example in http://docs.ansible.com/mysql_user_module.html:

```
# Creates database user 'bob' and password '12345' with all database privileges and 'WITH GRANT OPTION'
- mysql_user: name=bob password=12345 priv=*.*:ALL,GRANT state=present
```
##### Expected Results:

Ansible step succeeds with the user being granted the specified privileges.
##### Actual Results:

With 1.8, we get:
`msg: invalid privileges string: Invalid privileges specified: frozenset(['GRANT'])`

I have verified that this works in 1.7.2. 

I see two issues here: 
- Existing playbooks are not compatible with the new 1.8 version of Ansible.
- With an initial inspection of the new version of the code, it looks like there is an extra check to see "GRANT OPTION" is the keyword to be used in the priv values and not "GRANT", but then the code that eventually sets the user properties still expects "GRANT".
