### ISSUE TITLE
Ansible not detecting pre-existing EBS volume

### ISSUE THREAD

**Issue by davedash** [ansible/ansible#9643]
Getting this after I run a playbook a second time.  

```
msg: InvalidParameterValue: Invalid value '/dev/sdf' for unixDevice. Attachment point /dev/sdf is already in use
```

playbook snippet:

``` yaml
  pre_tasks:
    - name: Attach an EBS volume
      tags: ebs
      sudo: false
      local_action:
        module: ec2_vol
        encrypted: true
        instance: "{{ ec2_id }}"
        volume_size: 200
        region: us-east-1
        state: present
```
