### ISSUE TITLE
the command module's chdir arg is parsed incorrectly when using dictionary syntax and async

### ISSUE THREAD

**Issue by lukeorland** [ansible/ansible#9693]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:
- Running Ansible on and managing OS X 10.10.1.
- Running Ansible on Debian and managing Ubuntu 14.04
##### Summary:

A `command` where the `chdir` argument is specified in an `args` dictionary is ignored (or the value is replaced with the root directory `/`), when `async` is also used, e.g.:

```
- command: touch mycoolfile
  args:
    chdir: /tmp
  async: 3600
  poll: 1
```
##### Steps To Reproduce:

Download and run this gist: https://gist.github.com/lukeorland/1feaef1be7640ad8fa65
with the command

```
ansible-playbook ansible_chdir_async_bug.yml --connection=local -i hosts
```
##### Expected Results:

The expected result is for the playbook to run successfully without any failures.
##### Actual Results:

The task "Touch file with async, mapping syntax" fails with a permission-denied error due to Ansible attempting to touch a file under the `/` directory

```
 _____________________________________________
< TASK: Touch file with async, mapping syntax >
 ---------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [127.0.0.1] => {"ansible_job_id": "637018896337.51228", "changed": true, "cmd": ["touch", "mycoolfile"], "delta": "0:00:00.004807", "end": "2014-12-02 11:58:25.033617", "finished": 1, "rc": 1, "start": "2014-12-02 11:58:25.028810"}
stderr: touch: mycoolfile: Permission denied
<job 637018896337.51228> FAILED on 127.0.0.1

FATAL: all hosts have already failed -- aborting
```

**Comment by josef-spak** [comment]
I can reproduce this in Ansible 1.8.1, 1.8.2 and latest devel as well. 

```
ansible 1.9 (devel ade083a2e3) last updated 2014/12/18 15:28:59 (GMT +200)
  lib/ansible/modules/core: (detached HEAD dfe7f6c6d6) last updated 2014/12/18 15:28:59 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 317654dba5) last updated 2014/12/18 15:28:59 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:16:48 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:17:21 (GMT +200)
  configured module search path = None
```

Happens exactly as described, i.e. you have to use the `args:` syntax together with `async:` for this bug to show up.

I guess the gist could be shorter. Basically this:

``` yaml
---                                                                             
- name: bug 9693                                                                
  hosts: localhost                                                              
  gather_facts: no                                                              
  connection: local                                                             
  tasks:                      
# outputs /home/josef                                                  
    - name: run command using args + chdir                                      
      command: pwd                                                              
      args:                                                                     
        chdir: /home/{{ ansible_ssh_user }}                                     

# outputs /home/josef                                                                                
    - name: run command using chdir + async                                     
      command: pwd chdir=/home/{{ ansible_ssh_user }}                           
      async: 10                                                                 
      poll: 1

# outputs /                                                                             
    - name: run command using args + chdir + async                              
      command: pwd                                                              
      args:                                                                     
        chdir: /home/{{ ansible_ssh_user }}                                     
      async: 10                                                                 
      poll: 1
```

Results in this (the inventory file contains only localhost):

``` bash
ansible-playbook test.yml -i inventory -v
PLAY [bug 9693] *************************************************************** 

TASK: [run command using args + chdir] **************************************** 
changed: [localhost] => {"changed": true, "cmd": ["pwd"], "delta": "0:00:00.002298", "end": "2014-12-18 15:31:18.902846", "rc": 0, "start": "2014-12-18 15:31:18.900548", "stderr": "", "stdout": "/home/josef", "warnings": []}

TASK: [run command using chdir + async] *************************************** 
changed: [localhost] => {"changed": true, "cmd": ["pwd"], "delta": "0:00:00.002245", "end": "2014-12-18 15:31:18.965687", "rc": 0, "start": "2014-12-18 15:31:18.963442", "stderr": "", "stdout": "/home/josef", "warnings": []}

TASK: [run command using args + chdir + async] ******************************** 
changed: [localhost] => {"ansible_job_id": "379985754633.18188", "changed": true, "cmd": ["pwd"], "delta": "0:00:00.002256", "end": "2014-12-18 15:31:19.038636", "finished": 1, "rc": 0, "start": "2014-12-18 15:31:19.036380", "stderr": "", "stdout": "/", "warnings": []}
<job 379985754633.18188> finished on localhost
```

Note that **stdout is "/"** for the 3rd task. Expected: **/home/josef** (or whatever your username is).
