### ISSUE TITLE
Jinja2 Variables not being parsed in at head of Playbook correctly

### ISSUE THREAD

**Issue by mechastorm** [ansible/ansible#9706]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.1
##### Environment:

Ubuntu 14.04 LTS (Server)
##### Summary:

Jinja2 variables are no longer parsed correctly on Ansible 1.8.1 on playbook for properties before the tasks are defined such as Name and Host.
##### Steps To Reproduce:

I have a vars yml file like so

``` yml
aws:
  stg:
    ec2:
      name: stg-web
```

This is the playbook used

``` yaml
- name: Update {{ aws[env]['ec2']['name'] }}
  hosts: tag_Name_{{ aws[env]['ec2']['name'] }}
  remote_user: ubuntu
  gather_facts: yes
  vars_files:
      - "{{ playbook_config }}"

  tasks:
  - name: Debug
    debug: name=aws.ec2.name

```

I will then run the ansible command
ansible-playbook myplaybook.yml -i /etc/ansible/ec2.py --extra-vars="env=stg playbook_config=myvars.yml"
##### Expected Results:

In Ansible 1.7, the vars for at least the `hosts` property get parsed correctly. This is the method we use to dynamically touch AWS resources by tags. 

I understand that we can do this via custom inventories with "-i /my/custom/path/inventory" but wanted to check if this behaviour is still supported or if its a bug
##### Actual Results:

Since upgrading to 1.8.1, the vars are no longer parsed
