### ISSUE TITLE
cannot change to directory when using a wildcard

### ISSUE THREAD

**Issue by jwoertink** [ansible/ansible#9727]
**Issue Type:** Bug Report
**Ansible Version:** 1.8.1
**Environment:** OSX 10.9.5 / CentOS 6.5
**Summary:** When setting a command and using `chdir` with a wildcard, ansible fails with a "cannot change to directory" error. The error is fixed by using the full path, but as a convenience, it's nice just using the name of the project with the wildcard. 
**Steps To Reproduce:** 

``` yaml

---
- name: Download pjproject
  get_url: url=http://www.pjsip.org/release/2.3/pjproject-2.3.tar.bz2 dest=/usr/local/src
- name: Extract pjproject
  unarchive: src=/usr/local/src/pjproject-2.3.tar.bz2 dest=/usr/local/src copy=no
- name: Configure pjproject
  command: chdir=/usr/local/src/pjproject* ./configure --prefix=/usr/lib64/ --enable-shared
```

**Expected Results:** change into the `/usr/local/src/pjproject-2.3` folder to run the `./configure` script
**Actual Results:** 

```
failed: [default] => (item=./configure --prefix=/usr/lib64/ --enable-shared) => {"failed": true, "item": "./configure --prefix=/usr/lib64/ --enable-shared", "rc": 258}
msg: cannot change to directory '/usr/local/src/pjproject*': path does not exist
```
