### ISSUE TITLE
Included playbooks fail to match hosts

### ISSUE THREAD

**Issue by fago** [ansible/ansible#9733]
Issue Type: Bug Report
Ansible Version: 1.8.2 (from ubuntu ppa)
Environment: Ubuntu 14.04
Summary: When including a playbook, I'm using a hosts variable which denotes the hosts the playbook should be run for. As explained at https://groups.google.com/forum/#!topic/ansible-project/c8bdwPtR640, this worked fine with Ansible <1.8 but started failing with Ansible 1.8.

**Steps To Reproduce:**
I tried to come up with simple playbooks reproducing the problem. Take the following example playbooks and inventor files:
**test.inventory**

```
[group]
localhost ansible_connection=local
```

**test.yml**

```
- include: test-include.yml hosts="group"
```

**test-include-yml**

```

---
- hosts: "{{ hosts }}"
  tasks:
  - debug: msg="It works."
```

Then, run:
`ansible-playbook test.yml -i test.inventor`

**Expected Results**: (With ansible 1.7.2)
 $ansible-playbook test.yml -i test.inventory 

PLAY [group] *****************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [debug msg="It works."] ************************************************\* 
ok: [localhost] => {
    "msg": "It works."
}

PLAY RECAP *******************************************************************\* 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

**Actual Results**: (With ansible 1.8.2)

ansible-playbook test.yml -i test.inventory 

PLAY ["group"] ***************************************************************\* 
skipping: no hosts matched

PLAY RECAP *******************************************************************\*

**Comment by jimsmith** [comment]
I have also ran into this with ansible 1.8.4
has this been resolved yet as it's causing a real PITA when running a playbook from scratch.
EC2 instance is started up but then when ansible comes along to connect to the host after it's up and running for a role such as apache it does this:

skipping: no hosts matched

Re-running the playbook without changing anything then connects to the host and runs the role.

UPDATE: my workaround was based around these:
https://groups.google.com/forum/#!topic/ansible-project/QLKzYa5UeYA
http://stackoverflow.com/questions/24215187/can-i-update-the-hosts-inventory-and-use-new-hosts-in-same-playbook/28977513#28977513

```

 # so we add_host locally and create a temporarily inventory.
- hosts: localhost
  gather_facts: no
  tasks:
    # Get some facts about the instance.
    - action: ec2_facts
    - set_fact: hostname_next='myhostname.fqdn.something'
    - name: add new hostname to temporary inventory
      connection: local
      add_host: group=temp_inventory name='{{ hostname_next }}'

 # Now proceed with the real work on the designated host
- hosts: temp_inventory
```
