### ISSUE TITLE
git module clones but fails the task when version is specified

### ISSUE THREAD

**Issue by Jorge-Rodriguez** [ansible/ansible#9754]
##### Issue Type:

 “Bug Report”
##### Ansible Version:

ansible 1.8.1
  configured module search path = None
##### Environment:

Ansible running on Ubuntu 14.04
Managing Centos 7
##### Summary:

Git module task clones remote (github) repository as expected but returns failed status.
##### Steps To Reproduce:

```
- git:
    repo: https://github.com/rbCAS/CASinoApp.git
    dest: /var/www/casino
    version: 509debe
    depth: 1
```
##### Expected Results:

The task succeeds, (status OK or Changed)
##### Actual Results:

```
failed: [193.166.25.34] => {"failed": true}
msg: Failed to checkout 509debe
```

The repository is cloned on the target machine though.
