### ISSUE TITLE
Ansible 1.8.2 shell action doesn't handle ">" redirect correctly

### ISSUE THREAD

**Issue by mikesac** [ansible/ansible#9791]
##### Summary:

it seems that "shell" action has some issue handling stdout redirect.

my action is (I've tried any kind of quoting)

```
 - name : Dump previous database data - mysql_56
   shell: "mysqldump -u{{ item.value.user }} -p{{ item.value.pass }} {{ item.value.name }} > {{ deploy_path }}/db/{{ item.value.name }}-{{ nowdate.stdout }}.sql"
   with_dict: db
```

but it always fails with error:

```
stderr: mysqldump: Couldn't find table: ">"
```

simply rolling-back ansible to 1.7.2 made the action back to work as usual.

This seems to be affecting any "shell" action with redirect within.

**Comment by michalgasek** [comment]
This doesn't fix Ansible's problem but it might fix your problem.
http://dev.mysql.com/doc/refman/5.6/en/mysqldump.html#option_mysqldump_result-file

And then you can use `command` module instead of `shell` with redirect.
I just avoid shell module whenever I can.

**Comment by abadger** [comment]
I'm not able to reproduce with either 1.8.1, devel, or the 1.8.2 tag in the git repo using the following playbook:

```
---
- hosts: localhost
  vars:
    dir: '/var/tmp'
    echo_dict:
      one:
        msg:
          'blue'
        file:
          'redirect3'
  tasks:
    - name: redirection3
      shell: "echo {{ item.value.msg }} > {{ dir }}/{{ item.value.file }}"
      with_dict: echo_dict
```

Are you able to reproduce with that?  Do you have a simpler play that shows the problem or are you able to show us enough of your mysqldump play to reproduce it?
