### ISSUE TITLE
Error Evaluating Conditional when using async_status "until" parameter.

### ISSUE THREAD

**Issue by xelldran1** [ansible/ansible#9798]
##### Issue Type:

Bug Report
##### Ansible Version:

``` text
ansible 1.8.2 (detached HEAD 6f568bd649) last updated 2014/12/12 13:24:39 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 54ee8aa8e8) last updated 2014/12/12 13:24:45 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD c60441fddd) last updated 2014/12/12 13:24:46 (GMT -400)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/17 11:26:34 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/17 11:26:36 (GMT -400)
  configured module search path = /usr/share/ansible
```

&

``` text
ansible 1.9 (devel f88e2e1f01) last updated 2014/12/12 13:25:30 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 467ad65f73) last updated 2014/12/12 13:25:39 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b8071a8d5e) last updated 2014/12/12 13:25:39 (GMT -400)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/17 11:26:34 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/17 11:26:36 (GMT -400)
  configured module search path = /usr/share/ansible
```
##### Environment:

OS X Version 10.9.3 Build 13D65
##### Summary:

When using "fire and forget, check on it later" the async_status job has trouble with parsing the variable used in its "until" parameter "job_result.finished." Instead of checking to make sure the job is finished and looping, the playbook errors:

```
TASK: [check its done] ********************************************************
fatal: [localhost] => error while evaluating conditional: job_result.finished
```
##### Steps To Reproduce:

The following playbook reproduces the error:

```

---
# file:
#

- hosts: local
  gather_facts: false

  tasks:

  - name: long running task
    command: sleep 30
    async: 60
    poll: 0
    register: sleep_var

  - name: check its done
    async_status: jid="{{ sleep_var.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 30
```

The playbook output is:

```
PLAY [local] ******************************************************************

TASK: [long running task] *****************************************************
<job 517191460812.50956> finished on localhost

TASK: [check its done] ********************************************************
fatal: [localhost] => error while evaluating conditional: job_result.finished

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/matthewbrennan/async_check_test.retry

localhost                  : ok=2    changed=0    unreachable=1    failed=0
```
##### Expected Results:

When using ansible version 1.8.1 the playbook runs correctly.

``` text
ansible 1.8.1 (detached HEAD 6598c83b02) last updated 2014/12/12 13:38:55 (GMT -400)
  lib/ansible/modules/core: (detached HEAD dd4095137a) last updated 2014/12/12 13:38:59 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD cf54dc46b4) last updated 2014/12/12 13:38:59 (GMT -400)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/17 11:26:34 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/17 11:26:36 (GMT -400)
  configured module search path = /usr/share/ansible
```

With results that look like:

```
PLAY [local] ******************************************************************

TASK: [long running task] *****************************************************
<job 440524991018.51835> finished on localhost

TASK: [check its done] ********************************************************
changed: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```
##### Actual Results:

Results when using v1.8.2 or v1.9.0 (devel):

```
PLAY [local] ******************************************************************

TASK: [long running task] *****************************************************
<job 517191460812.50956> finished on localhost

TASK: [check its done] ********************************************************
fatal: [localhost] => error while evaluating conditional: job_result.finished

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/matthewbrennan/async_check_test.retry

localhost                  : ok=2    changed=0    unreachable=1    failed=0
```

**Comment by mpdehaan** [comment]
Seems like you'd want to just set the "poll" value on the async task for this.

**Comment by xelldran1** [comment]
Got it. Thanks for the heads up.

**Comment by mschurenko** [comment]
Is this a known issue? I'm having the same problem on 1.8.4 but only when using the cloudformation module. I'm not sure what this means in the above comment:

```
Seems like you'd want to just set the "poll" value on the async task for this.
```

It looks like poll is being set in the above example.

**Comment by ashukaul** [comment]
Facing the exact same issue. ansible version - 1.9.0.1. 

```
- name: "Execute Job "
  sudo_user: "<some_user>"
  sudo: "yes"
  shell: "<runningsomescript>"
  async: "1000"
  poll: "0"
  register: output
- name: "Check on build status"
  async_status:
      jid: "{{ output.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30
```

And as mentioned in the above e.g. "Poll" value "0" has been provided.
