### ISSUE TITLE
feature request: allow subelement loops to have missing subelements

### ISSUE THREAD

**Issue by geogdog** [ansible/ansible#9827]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.7.2
##### Environment:

CentOS 6.6
##### Summary:

Allow with_subelement loops to have missing subelements without error.
##### Steps To Reproduce:

Given the vars:

```

---
users:
  - name: alice
    authorized:
      - /tmp/alice/onekey.pub
      - /tmp/alice/twokey.pub
  - name: bob
    authorized:
      - /tmp/bob/id_rsa.pub
 - name: greg
```

I'd like to run the following code essentially skipping the _greg_ user because the subelement _authorized_ is deliberately missing:

```
- authorized_key: "user={{ item.0.name }} key='{{ lookup('file', item.1) }}'"
  with_subelements:
     - users
     - authorized
```

Currently I get the error:

```
could not find 'authorized' key in iterated item
```
##### Expected Results:

I expect the missing subelement to be skipped
##### Actual Results:

```
could not find 'authorized' key in iterated item
```

**Comment by vincentvdk** [comment]
Hi Greg, 

Maybe you can try this :

users:
  user:
    authorized:
      - /tmp/alice/onekey.pub
      - /tmp/alice/twokey.pub
    name: alice
  user:
    authorized:
      - /tmp/bob/id_rsa.pub
    name: bob
  user:
    name: greg
- authorized_key: "user={{ item.0.name }} key='{{ lookup('file', item.1) }}'"
  with_subelements:
  - users
  - authorized|default([])

**Comment by geogdog** [comment]
Hey Vincent,

Certainly works for now, but I suppose the discussion is whether this should be default behaviour or not.

**Comment by vincentvdk** [comment]
I would also expect an empty list when nothing is found..

**Comment by geogdog** [comment]
Actually, this isn't working for me.  I tried the above:

```
- authorized_key: "user={{ item.0.name }} key='{{ lookup('file', item.1) }}'"
  with_subelements:
     - users
     - authorized|default([])
```

but still get the error:

```
could not find 'authorized|default([])' key in iterated item
```

**Comment by bcoca** [comment]
try:
  with_subelements:
     - "{{users}}"
     - "{{authorized|default([])}}"

On Tue, Dec 16, 2014 at 9:17 AM, Greg Trahair notifications@github.com
wrote:

> Actually, this isn't working for me. I tried the above:
> - authorized_key: "user={{ item.0.name }} key='{{ lookup('file', item.1) }}'"
>   with_subelements:
>   - users
>   - authorized|default([])
> 
> but still get the error:
> 
> could not find 'authorized|default([])' key in iterated item
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/9827#issuecomment-67165058.

## 

Brian Coca

**Comment by vincentvdk** [comment]
@geogdog  have you modified your vars? I'm using the same thing to deploy keys and it works.

**Comment by geogdog** [comment]
@vincentvdk I've not modified the vars, but I'll take a close look into it tomorrow.  Using the example from @bcoca I get the error:

```
subelements lookup expects a list of two items, first a dict or a list, and second a string
```

I'll pair up with a colleague tomorrow to see if I deserve to wear a funny hat for the rest of the day :+1:

**Comment by abadger** [comment]
I wasn't able to get the filter to work either but this does work:

```
- hosts: localhost
  vars:
    users:
      - name: alice
        authorized:
          - /tmp/alice/onekey.pub
          - /tmp/alice/twokey.pub
      - name: bob
        authorized:
          - /tmp/bob/id_rsa.pub
      - name: greg
        authorized: []

  tasks:
    - authorized_key: "user={{ item.0.name }} key='{{ lookup('file', item.1) }}'"
      with_subelements:
         - users
         - authorized
```

If this does work for you probably should take the question of whether the current behaviour is a bug to the mailing list.  I think it should fail (as it does currently) because failing helps detect problems in your data that would otherwise be silent errors.. for instance, say you typo'd "autorized:" if an empty list was used by default, that user would be silently skipped and you either might not notice for a while or you might spend several hours trying to debug why the authorized_key module isn't creating all of the keys for you before noticing the mispelled data field.
