### ISSUE TITLE
Friendly role name doesn't seem to work for local files

### ISSUE THREAD

**Issue by mspiegle** [ansible/ansible#9837]
##### Summary:

Friendly role names don't work for local files.
##### Steps To Reproduce:

Include the following into a playbook:

``` yaml

---
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - { role: '../roles/register-ec2-hosts,,register-ec2-hosts',
        hosts: "{{machines[machine_type]}}",
        group: "{{machine_type}}_hosts",
        tags: ['main'] }
```
##### Expected Results:

Playbook runs that show the TASK as:

```
TASK: [register-ec2-hosts | launch instances]
```
##### Actual Results:

```
ERROR: cannot find role in <scrubbed>/ansible/includes/roles/register-ec2-hosts,,register-ec2-hosts or <scrubbed>/ansible/roles/register-ec2-hosts,,register-ec2-hosts or /etc/ansible/roles/register-ec2-hosts,,register-ec2-hosts
```
