### ISSUE TITLE
copy module fails with json and with_items

### ISSUE THREAD

**Issue by kvdveer** [ansible/ansible#9852]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.8.1, but present at least since 1.5.0
##### Environment:

Ubuntu 14.10, with ansible in a virtualenv

Jinja2==2.7.3
MarkupSafe==0.23
PyYAML==3.11
ansible==1.8.1
argparse==1.2.1
ecdsa==0.11
paramiko==1.15.1
pycrypto==2.6.1
wsgiref==0.1.2
##### Summary:

Similar to GH-5914, the copy module fails when there's json with variables in 
the content field, _and_ it is run with `with_items`.
##### Steps To Reproduce:

``` yaml
- hosts: localhost
  tasks:
  - copy:
        content: "[{{item}}]"
        dest: /tmp/bug
    with_items:
    - "123"
```
##### Expected Results:

A file containing `["123"]`.
##### Actual Results:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [copy ] ***************************************************************** 
failed: [localhost] => (item=123) => {"failed": true, "item": "123"}
msg: could not write content temp file: expected a character buffer object

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/username/jsonbug.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by gautamk** [comment]
+1 This is a huge pain for me, My playbook contains a lot of copying back and forth

**Comment by bcoca** [comment]
it seems to be in the yaml tranformation, as a workaround the following works:

```
- hosts: localhost
  tasks:
    - copy: content="[{{item}}]" dest=/tmp/bug
      with_items:
        - "123"
```

**Comment by brian-brazil** [comment]
I've just run into this on a json string with a colon for a map, substituting `\x3A` for the colon let me work around that. I'm not using with_items.

**Comment by duggan** [comment]
> as a workaround the following works

This is only a workaround for the example. If you wanted, say, more than one item in a list, it is not a workaround.

Here's my deeply unpleasant, but functional workaround:

```
---
- name: Test workaround
  hosts: localhost
  connection: local
  tasks:
    - set_fact:
        machines: "{{ groups.foo | to_nice_json | quote }}"

    - name: Updating /tmp/foo
      copy:
        content: "{{ machines }}"
        dest: /tmp/foo

    - name: Work around Ansible bug
      replace:
        dest: /tmp/foo
        regexp: ^\'\[$
        replace: '['

    - name: Work around Ansible bug
      replace:
        dest: /tmp/foo
        regexp: ^\]\'$
        replace: ']'
```

Note that this is not only for `with_items`, it's any list structure.

This takes the list, formats it to JSON, filters it through `quote` which turns it into a quoted string, then uses the `replace` function to remove the quotes. It's horrible. But there is no reasonable alternative.
