### ISSUE TITLE
0.8 - Turning off sudo in play when sudo_user set has unexpected behaviour

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#986]
Context - I want to download something on the local side (as it has connection to the internet) and then copy it to the server side and install it. I do the installation as a non-root user. 

The playbook looks a bit like:

```
# Author: Will Thames
# Name: nexus
# Description: installs nexus
# under /apps without removing other versions

---
- hosts: all
  vars:
    tmpdir: /var/tmp
    version: 2.1.2
    nexus_archive: nexus-$version-bundle.tar.gz
    dest: /apps/nexus/nexus-$version

- hosts: nexus-prod:nexus-uat
  connection: local
  sudo: False
  sudo_user: root
  tasks:
  - name: download nexus archive locally
    local_action: get_url url=http://www.sonatype.org/downloads/$nexus_archive dest=~/filesrepo/nexus/$nexus_archive

- hosts: nexus-prod:nexus-uat
  sudo_user: nexadm

  tasks:
  - name: put nexus archive $nexus_archive into $tmpdir
    action: copy src=~/filesrepo/nexus/$nexus_archive dest=$tmpdir/$nexus_archive mode=644
  - name: install nexus
    action: command chdir=/apps/nexus creates=$dest tar xzf $tmpdir/$nexus_archive
  ... rest snipped
```

I then run it using `ansible-playbook --sudo-user nexus --limit server-a setup.yml`

Because sudo-user is set, and not root, lines 92-93 of lib/ansible/playbook/play.py set sudo to True unless I add sudo: False _and_ sudo_user: root to my playbook.

There are plenty of ways to fix this, and I have a workaround, but it's unexpected to say the least. At the very least this issue demonstrates how to download from URLs when target nodes have no internet access.
