### ISSUE TITLE
run_once: misbehaving in combo with serial

### ISSUE THREAD

**Issue by fdutheil** [ansible/ansible#9861]
The final post "Possible Misunderstanding" in the closed issue #8543 is explaining what happens with current implementation.
So while it's being discussed or about to be implemented differently, can you please fix the documentation that is quite misleading (http://docs.ansible.com/playbooks_delegation.html)? A special warning would be nice when using run_once **and** serial.
##### Issue Type:

Documentation Report
##### Ansible Version:

Ansible 1.8.1
##### Environment:

CentOS 6.5 & Ubuntu 14.04
##### Summary:

a run_once task is executed once per pass resulting of the use of serial statement.
That's misleading, because the documentation (http://docs.ansible.com/playbooks_delegation.html) says it's similar to when: inventory_hostname == webservers[0]. It is not when serial is used.
An explicit/special "caution" should be inserted in that section regarding the use of serial combined to run_once.
##### Steps To Reproduce:

```
- name: some play
  hosts: some_hosts
  serial: 1
  tasks:
    - name: some task
      command: "some command"
      run_once: true
```
##### Expected Results:

The task should be executed only on the first host.
##### Actual Results:

The task is executed on each host.
