### ISSUE TITLE
with_subelements: Allow subelement property to be nested

### ISSUE THREAD

**Issue by alanvdam** [ansible/ansible#9863]
```
"rax": {
  "instances": [{
    "id": 0,
    "rax_addresses": {
       "public" : [ { "addr": "10.2.2.2" }, { "addr": "10.0.0.1" } ]
     }
  }]
}

- action: some attr=item.0.id ip=item.1.addr
  with_subelements:
    - rax.instances
    - rax_addresses.public 
```
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Mac OS X 10.10.1
##### Summary:

`with_subelements` should be able to loop over nested property.
The rax_addresses.public or tax_addresses['public'] does not work with the with_subelements. Only the first argument seems to support nested property names.
##### Steps To Reproduce:

See code above
##### Expected Results:

Be able to loop over the addr properties
##### Actual Results:

Fails with can not find `tax_addresses.public`

**Comment by mhoglan** [comment]
I ran into the same need when trying to define a list of users and wanted to include their MySQL configuration in the same dict.  Wanted to have one user dict that contained all the different applications configs for the user.   

example type of structure

``` yaml
---
users:
  - user: bob
    password: system-password
    mysql:
      password: mysql-password
      hosts:
        - "%"
        - "{{ ansible_hostname }}"
        - "127.0.0.1"
        - "::1"
        - "localhost"
      privs:
        - "*.*:SELECT"
        - "DB1.*:ALL"
```

wanted to be able to do something along the lines of

```
- name: Setup MySQL users
  mysql_user: name={{ item.0.user }} password={{ item.0.mysql.password }} host={{ item.1 }} priv={{ item.0.mysql.privs | join('/') }}
  with_subelements:
    - users
    - mysql.hosts
```

I worked around this, and I am sure there are a dozen ways to achieve similar behavior.   The ability to specify the second element to be a nested element or pass in jinja to perform it would be nice.
