### ISSUE TITLE
When using tags with roles, the notify actions run at the end of the role not the end of the script

### ISSUE THREAD

**Issue by ofir-petrushka** [ansible/ansible#9872]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.9
##### Environment:

Ubuntu 14.04
##### Summary:

When using tags with roles, the notify actions run at the end of the role not the end of the script.
Basically you get a different running order.
##### Steps To Reproduce:

```
playbook 1
- hosts:
  roles:
    - {role: a, tags: ['x']}
    - {role: b, tags: ['x']}

role a
  - name: a
  - command: echo 'a'
    notify:
      - a1

handlers:
  - name: a1
  - command: echo 'a1'

role b
  - name: b
  - command: echo 'b'
```

```
##### Expected Results:

Running the full book will show
a
b
a1

##### Actual Results:

Running the book with tag x will show
a
a1
b
```
