### ISSUE TITLE
cannot access registered variables in loop (with_items)

### ISSUE THREAD

**Issue by evantahler** [ansible/ansible#9879]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

OSX Yosemite 
##### Summary:

Cannot register variables within a loop
##### Steps To Reproduce:

``` yaml
- stat: path={{ item }}
  with_items: 
   - /home
   - /var
   - /fake
  register: stats_collection

- debug: var={{ item }}
  with_items: stats_collection.results
```

returns the error:

`A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").`
##### Expected Results:

not to crash
##### Actual Results:

`A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").`
