### ISSUE TITLE
lineinfile module does not detect the existence of multiline strings in file

### ISSUE THREAD

**Issue by dmlary** [ansible/ansible#9882]
With the following tasks, I am able to create the file correctly on the first run, but on the second run, the multiple line chunk is written a second time.

Playbook tasks:

``` yaml
- name: single line in file
  lineinfile:
    dest: /tmp/junk
    create: true
    state: present
    line: "# single line in file"
- name: Multiple lines in file
  lineinfile:
    dest: /tmp/junk
    create: true
    state: present
    line: |
      # These are my multiple lines of text
      # they are really long and important
```

After the first run of the playbook, the contents of the file are correct:

```
root@trusty:~# cat /tmp/junk
# single line in file
# These are my multiple lines of text
# they are really long and important

```

Following the second run of the playbook, the multi-line chunk is in the file twice:

```
root@trusty:~# cat /tmp/junk
# single line in file
# These are my multiple lines of text
# they are really long and important

# These are my multiple lines of text
# they are really long and important

```
