### ISSUE TITLE
Command line arguments that contain '='

### ISSUE THREAD

**Issue by rfleschenberg** [ansible/ansible#9899]
There does not seem to be a way to pass command line arguments that contain `=` to modules:

```
- synchronize: 
    src: "{{ src }}"
    dest: "{{ dst }}"
    rsync_opts: --chmod 'u=rwX,g=rX'
```

Despite the quoting, Ansible splits on the `=`, resulting in this on the command line:

```
--chmod 'u=rwX g=rX'
```

The same is true if you use Ansible's key=value syntax:

```
- synchronize: src="{{ pelican_src_dir }}"
               dest="{{ pelican_dst_dir }}"
               rsync_opts=--chmod='u=rwX,g=rX'
```
