### ISSUE TITLE
ansible_ssh_port template not expanded for synchronize

### ISSUE THREAD

**Issue by cazgp** [ansible/ansible#9926]
# Issue Type

 Bug Report
# Version

ansible --version
ansible 1.8.2
  configured module search path = None
# Environment

Vagrant VBox Ubuntu 14.04.
# Summary

We have a playbook which deploys onto a remote server through a non-standard SSH port. The variable is defined in roles/common/vars/main.yml as deploy_ssh_port: 3500. In the playbook file, vars: ansible_ssh_port: '{{deploy_ssh_port}}'. The playbook runs perfectly, communicating with the server and installing files until it reaches the synchronise task. Then, it fails with an error "msg: command-line line 0: Bad number. rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]"

Debugging this reveals the command being sent is `rsync --delay-updates -FF --compress --archive --no-owner --no-group --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port={#deploy_ssh_port#}' --rsync-path="sudo rsync" --files-from=/tmp/inventory_files --out-format='<<CHANGED>>%i %n%L' "/home/user/source" "user@ipaddress:/home/user"`

Note, `deploy_ssh_port` isn't expanded, which was validated by a print in ansible/modules/core/files/synchronize.py.
# Steps To Reproduce

Relevant task in roles/render/tasks/main.yml:

```
- name: rsync files
  tags: code
  synchronize:
  args:
    src: ~/source
    dest: /home/user
    owner: no
    group: no
    rsync_opts:
      - '--files-from=/tmp/{{inventory_hostname}}_files'
```

Relevant var in roles/common/vars/main.yml:

```
deploy_ssh_port: 3500
```

Relevant playbook:

```
- hosts: render
  user: user
  sudo: true
  vars:
    ansible_ssh_port: '{{deploy_ssh_port}}'
  roles:
    - wl_render
```
# Expected Results

`rsync` command to pass.
# Actual Results

 "msg: command-line line 0: Bad number. rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]"
# NB

All other tasks using the same template work perfectly, and changing `ansible_ssh_port: '{{deploy_ssh_port}}'` to `ansible_ssh_port: 3500` works as expected.
