### ISSUE TITLE
Ansible Sudo Fails in Playbook but Succeeds in Ad-Hoc

### ISSUE THREAD

**Issue by br-mcc** [ansible/ansible#9929]
Originally created [Server Fault question](http://serverfault.com/questions/655626/ansible-fails-to-authenticate-sudo-even-when-sudo-pass-is-given) to document the problem and now posting here.
### Software Versions
- **OS**: RHEL 6.4
- **Ansible version**: ansible 1.8.2
- **Sudo version**:
  <pre>
  Sudo version 1.8.6p3
  Sudoers policy plugin version 1.8.6p3
  Sudoers file grammar version 42
  Sudoers I/O plugin version 1.8.6p3
  </pre>
- **SSH version**: OpenSSH_5.3p1, OpenSSL 1.0.0-fips 29 Mar 2010
### Server Map

<pre>
                   -------- User1@Server1: sudo -H -S -p (Hangs on Gathering_Facts)
                  /
User1@Ansible ----
                  \
                   -------- User1@Server2: sudo -H -S -p (Works fine)
</pre>

### Users
- User1: NIS accessible user on both Server1 & Server2.
- root: local root user for each server.
## Ansible Configuration

Relevant parts of my **ansible.cfg**.

_ansible.cfg_

```
    sudo           = true
    sudo_user      = root
    ask_sudo_pass  = True
    ask_pass       = True
    ...
    gathering = smart
    ....
    # change this for alternative sudo implementations
    sudo_exe = sudo

    # what flags to pass to sudo
    #sudo_flags = -H
    ...
    # remote_user = ansible
```

Here is a simple test playbook to touch an empty file and then remove it.  Really, I'm just wanting to test if I can get Ansible to correctly use sudo on the remote server.  If the playbook runs at all, I'm in good shape.

_TEST.yml_

``` yml

---
- hosts: Server1:Server2
  vars:
  - test_file: '/tmp/ansible_test_file.txt'
  sudo: yes
  tasks:
  - name: create empty file to test connectivity and sudo access
    file: dest={{ test_file }}
          state=touch
          owner=root group=root mode=0600
    notify:
    - clean
  handlers:
  - name: clean
    file: dest={{ test_file }}
          state=absent
```
### Running the Playbook

<pre>
$ ansible-playbook test.yml
SSH password: 
sudo password [defaults to SSH password]:

PLAY [Server1:Server2] ********************************************** 

GATHERING FACTS *************************************************************** 
ok: [Server2]
failed: [Server1] => {"failed": true, "parsed": false}

Sorry, try again.
[sudo via ansible, key=mxxiqyvztlfnbctwixzmgvhwfdarumtq] password: 
sudo: 1 incorrect password attempt

TASK: [create empty file to test connectivity and sudo access] **************** 
changed: [Server2]

NOTIFIED: [clean] ************************************************************* 
changed: [Server2]

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/User1/test.retry

Server1                 : ok=0    changed=0    unreachable=0    failed=1   
Server2                 : ok=3    changed=2    unreachable=0    failed=0
</pre>

Fails regardless of if I explicitly enter both the SSH/Sudo passwords as well as implicitly (letting sudo pass default to SSH).
### Running Ad-Hoc

<pre>
-bash-4.1$ ansible Server1 -m file -a "dest=/tmp/ansible_test_file.txt state=touch"
SSH password: 
sudo password [defaults to SSH password]: 
Server1 | success >> {
    "changed": true, 
    "dest": "/tmp/ansible_test.txt", 
    "gid": 0, 
    "group": "root", 
    "mode": "0644", 
    "owner": "root", 
    "size": 0, 
    "state": "file", 
    "uid": 0
}
</pre>

I'm unsure of why I get different results in my Sudo access when I run from the playbook versus just running the ad-hoc command.

I tested Gather_Facts in case it was the issue, but I can run `setup` ad-hoc just fine like above.
