### ISSUE TITLE
failed_when and ignore_errors ignored in check mode in roles in copy module (and probably others)

### ISSUE THREAD

**Issue by youam** [ansible/ansible#9943]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9 (devel fe53d86a83) last updated 2015/01/05 18:45:42 (GMT +200)
  lib/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/12 16:11:49 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/12 16:11:56 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/12 16:12:01 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/12 16:12:14 (GMT +200)
  configured module search path = /usr/share/ansible
```

also verified in ansible 1.7.2
##### Environment:

Debian/Jessie, but probably irrelevant
##### Summary:

When running a playbook with roles in check mode, and a role has a copy task with a missing input file, ansible handles this as an failed task, even when instructed to ignore this check with

```
failed_when: false
```

or

```
ignore_errors: true
```

When the same task is executed in the master playbook file itself instead of the role's files, the failed status is ignored as requested.
##### Steps To Reproduce:

not-really-minimal playbook and role files:

```

---
# test.yml
- hosts: all
  gather_facts: false

  roles:
    - test
  tasks:                                                                                                                                                                                                        
    - copy: src=missinginplaybook dest=devnull                                                                                                                                                                  
      failed_when: false                          
```

```

---
# roles/test/tasks/main.yml
- fail: msg="this error is ignored"
  failed_when: false

- copy: src=doesnotexist dest=doesnotexisteither
  failed_when: false

- debug: msg="this task does not fail"
```

```
ansible-playbook -i hosts test.yml --check -v
```
##### Expected Results:

```
PLAY [all] ******************************************************************** 

TASK: [test | fail msg="this error is ignored"] ******************************* 
ok: [breandan] => {"failed": false, "failed_when_result": false, "msg": "this error is ignored"}

TASK: [test | copy src=doesnotexist dest=doesnotexisteither] ****************** 
ok: [breandan] => {"failed": false, "failed_when_result": false, "msg": "could not find src=/home/youam/ans-test/roles/test/files/doesnotexist"}

TASK: [test | debug msg="this task does not fail"] **************************** 
ok: [breandan] => {
    "msg": "this task does not fail"
}

TASK: [copy src=missinginplaybook dest=devnull] ******************************* 
ok: [breandan] => {"failed": false, "failed_when_result": false, "msg": "could not find src=/home/youam/ans-test/missinginplaybook"}

PLAY RECAP ******************************************************************** 
breandan                   : ok=4    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [all] ********************************************************************

TASK: [test | fail msg="this error is ignored"] *******************************
ok: [breandan]

TASK: [test | copy src=doesnotexist dest=doesnotexisteither] ******************
fatal: [breandan] => input file not found at /home/youam/ans-test/roles/test/files/doesnotexist or /home/youam/ans-test/doesnotexist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/youam/test.retry

breandan                   : ok=1    changed=0    unreachable=1    failed=0
```

If the failing task in roles/test/tasks/main.yml is removed, it's visible that the exact same task (modulo file names) in the playbook itself runs successfully, ignoring the error, as it should.

This happens because ansible is caling path_dwim_relative from lib/ansible/utils/**init**.py to figure out the full file name for a given relative file name. When this function does not find a file, and running in check mode, this raises an errors.AnsibleError, which aborts for this host. The ignore_errors setting or the failed_when constraint are not checked here. When not running in check mode, it just returns the last checked file name.

I removed the check, as seen in the patch below, and then it works as expected for me: not failing when run with failed_when: false or ignore_errors: true, failing when not run with either settings.

Removing this check makes my case work. I don't know what it does break...

```
diff --git a/lib/ansible/utils/__init__.py b/lib/ansible/utils/__init__.py
index 44db63e..9267579 100644
--- a/lib/ansible/utils/__init__.py
+++ b/lib/ansible/utils/__init__.py
@@ -366,8 +366,6 @@ def path_dwim_relative(original, dirname, source, playbook_base, check=True):
     obvious_local_path = path_dwim(playbook_base, source)
     if os.path.exists(obvious_local_path):
         return obvious_local_path
-    if check:
-        raise errors.AnsibleError("input file not found at %s or %s" % (source2, obvious_local_path))
     return source2 # which does not exist

 def repo_url_to_role_name(repo_url):
```
