### ISSUE TITLE
Support for variable Handlers

### ISSUE THREAD

**Issue by evantahler** [ansible/ansible#9953]
Consider:

``` yml
- hosts: all

  tasks:

    - name: echo stuff
      command: 'echo "{{ item }}"'
      notify: notifier {{ item }}
      with_items: 
        - "a"
        - "b"
        - "c"

  handlers:

    - name: notifier a
      command: 'echo "A OK"'

    - name: notifier b
      command: 'echo "B OK"'

    - name: notifier c
      command: 'echo "C OK"'
```

This errors (on ansible 1.8.2) with: 

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [test_server_3]
ok: [test_server_2]
ok: [test_server_1]

TASK: [echo stuff] ************************************************************
changed: [test_server_2] => (item=a)
changed: [test_server_3] => (item=a)
changed: [test_server_1] => (item=a)
changed: [test_server_2] => (item=b)
changed: [test_server_1] => (item=b)
changed: [test_server_3] => (item=b)
changed: [test_server_1] => (item=c)
changed: [test_server_2] => (item=c)
changed: [test_server_3] => (item=c)
ERROR: change handler (notifier {{ item }}) is not defined
```

It would awesome to define handlers with variable reference.
