### ISSUE TITLE
with_dict and with_items mishandle quotes

### ISSUE THREAD

**Issue by tals** [ansible/ansible#9955]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.8.2
```
##### Environment:

Ubuntu 14.04
##### Summary:

Items with quotes in them trip over ansible, and they can cause it to blow up or to silently discard quotations.
##### Steps To Reproduce:

Using ini_module for illustration - the issue applies to all modules, except debug.

``` yaml
- name: quote test
  ini_file: dest=/tmp/quote.ini section=section option={{ item.key }} value={{ item.value }}
  with_dict:
    some_key: "where 'are' the quotes"
- name: quote test 2
  ini_file: dest=/tmp/quote.ini section=section option=some_other_key value="'  here 'they' are '"
```

will explode with:

```
failed: [default] => (item={'key': 'some_key', 'value': "where 'are' the quotes"}) => {"failed": true, "item": {"key": "some_key", "value": "where 'are' the quotes"}}
msg: this module requires key=value arguments (['dest=/tmp/quote.ini', 'section=section', 'option=some_key', 'value=where', 'are', 'the', 'quotes'])
```

or it may silently discard the quotes (same issue, just less noticeable so it's easy to miss)

``` yaml
- name: quote test
  ini_file: dest=/tmp/quote.ini section=section option={{ item.key }} value={{ item.value }}
  with_dict:
    some_key: "'   where 'are' the quotes'"
- name: quote test 2
  ini_file: dest=/tmp/quote.ini section=section option=some_other_key value="'  here 'they' are '"
```

produces:

```
[section]
some_key = where are the quotes
some_other_key = '  here 'they' are '
```

Quoting the usage doesn't help, because:

``` yaml
- name: quote test
  ini_file: dest=/tmp/quote.ini section=section option={{ item.key }} value="{{ item.value }}"
  with_dict:
    some_key: "'   where \"are\" the quotes'"
- name: quote test 2
  ini_file: dest=/tmp/quote.ini section=section option=some_other_key value="'  here \"they\" are '"
```

produces:

```
[section]
some_key = '   where are the quotes'
some_other_key = '  here "they" are '
```
