### ISSUE TITLE
sudo_user from extra-vars

### ISSUE THREAD

**Issue by ronaldtx** [ansible/ansible#998]
i have this code at yml

<pre><code>

---
- hosts: $host
  user: ansible
  sudo: True
  sudo_user: $user
</code></pre>

and then i try to execute with this  --extra-vars "host=192.168.1.6 user=foo"

then i got this error message 

EXEC sudo -k && sudo -p "[sudo via ansible, key=yxklrigqhrftpybqxpcugzpcoivyjded] password: " -u $user "$SHELL" -c /tmp/ansible-1346822103.56-219316211348488/setup
fatal: [192.168.1.6] => failed to parse: usage: sudo [-D level] -h | -K | -k | -V

but if i change with 
sudo_user: foo 

it will be success, no error message.

**Comment by mpdehaan** [comment]
Looks like we need to add templating around this variable lookup like we have already done with a few other parameters.

Good catch!

This should be fixable for the 0.7 release.

**Comment by mpdehaan** [comment]
Fixed in d0eba79 ... apologies on missing this for 0.7

**Comment by skorokithakis** [comment]
I'm not sure what's wrong, but this isn't working for me on the latest HEAD:

> <staging> EXEC sudo -k && sudo -p "[sudo via ansible, key=x] password: " -u ${project_name} /bin/sh

```
---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true

  tasks:
  - name: Create the SSH directory.
    file: state=directory path=${project_root}/home/.ssh/
    sudo_user: ${project_name}
```

`vars.yml` contains `project_name: stavros`.

It didn't work when I tried putting it at the top either.
